### ISSUE TITLE
Conjunct support for DEVANAGARI LETTER MARWARI DDA

### ISSUE THREAD

**Issue by srinidhi97** [googlefonts/noto-fonts#1004]
Currently Noto Sans/Serif Devanagari are rendered with explicit virama without formation of ligatures. involving ॸ. For certain clusters ligatures exists in print and manuscripts. The following ligatures are formed.

1. ॸ्ॸ( MARWARI DDA+VIRAMA+MARWARI DDA) 
![dda dda](https://user-images.githubusercontent.com/27153077/33381465-1b99b4ca-d544-11e7-8027-e574d3a8974d.png)

2. ॸ्ढ(MARWARI DDA+VIRAMA+DDHA)  
![c4tyg7lvyamm6_j](https://user-images.githubusercontent.com/27153077/33381578-6e4d8764-d544-11e7-91f1-1bea7714ade5.jpg)

3.ण्ॸ( NNA+VIRAMA+MARWARI DDA) should form conjunct with NNA as half-form.
![ms-add-02318-000-00016](https://user-images.githubusercontent.com/27153077/33381789-01bb8618-d545-11e7-9d9a-b909aaa97dd2.jpg)

4. ॸ्य(MARWARI DDA+VIRAMA+YA) should form ligature
![unnamed](https://user-images.githubusercontent.com/27153077/33381980-87e10b28-d545-11e7-93ca-e4ac90573d87.jpg)

5.MARWARI DDA+VIRAMA+RA can form ra-vattu similar to क्र kra ,प्र, pra etc.

Other conjuncts which are not written as ligatures can be presented using explicit virama similar to Devanagari DDA and DDHA.

**Comment by JelleBosmaMT** [comment]
For 3: NNA+VIRAMA+MARWARI DDA should already render with half-NNA, provided software is new enough to support it. Of course this works with any consonant with half form.
For 5: This uses the below base form of RA. I don't know where to attach the stroke, if it is supposed to attach. It is always attached to a straight stroke in the lower-right of the base. The Marwari-dda has a straight stroke in the top-left only....

**Comment by srinidhi97** [comment]
I recommend ra-vottu may done similar to क्र or ह्र. 
In the last line in the word भांडारे (भांॸारे) ,lower right base is nearly a straight line.
![image](https://user-images.githubusercontent.com/27153077/33945943-668af81a-e046-11e7-92b5-3738e8fe702d.png)

**Comment by nizarsq** [comment]
Tested reported issues on NotoSansDevanagari and NotoSerifDevanagari.  Rendering looks good to me in the current version. Please reopen if any not fixed. 
<img width="1395" alt="Screen Shot 2020-06-07 at 9 01 53 PM" src="https://user-images.githubusercontent.com/22158882/83991899-2f31a480-a903-11ea-9448-d61111a0d689.png">
