### ISSUE TITLE
Noto Sans Chakma TTF incorrectly generated

### ISSUE THREAD

**Issue by punchcutter** [googlefonts/noto-fonts#1010]
The TTF for Noto Sans Chakma at https://www.google.com/get/noto/#sans-cakm was incorrectly generated. Maybe due to an older version of fontmake. Some GPOS is missing even though the source files are correct. The sample image shows the problem where the GPOS is missing from the U vowel like this:

![chakma_bad](https://user-images.githubusercontent.com/11257204/33746550-e1c86d42-db72-11e7-8c83-baa5a203af3e.png)

If I regenerate the TTF with the latest fontmake and the existing sources then the GPOS is correct like this:

![chakma_good](https://user-images.githubusercontent.com/11257204/33746619-407d302a-db73-11e7-9436-b588309d4cde.png)

**Comment by dougfelt** [comment]
Thanks for the report.

**Comment by punchcutter** [comment]
The TTF available on https://www.google.com/get/noto/#sans-cakm is still broken. The TTF in https://github.com/googlei18n/noto-fonts/tree/master/unhinted is ok. 

Also, I should have included the the test string for the above:
1111F,1111A,1112A,1110C,11134
