### ISSUE TITLE
Noto Khmer instance interpolation error 

### ISSUE THREAD

**Issue by punchcutter** [googlefonts/noto-fonts#1012]
The TTFs on https://www.google.com/get/noto/ show this issue. Here you can see it in Noto Serif Khmer SemiBold:

![khmer_ma_interpolation_error](https://user-images.githubusercontent.com/11257204/33802061-45055350-dd23-11e7-839a-67be2d03b32d.png)

This happens where the stem width for one component doesn't get interpolated the same way as the stem width of the base component. The same thing happens when exporting from Glyphs or using fontmake so it could be a source issue, but either way what should really happen here is the components should be decomposed as shown here: https://github.com/googlei18n/noto-fonts/issues/1011

**Comment by dougfelt** [comment]
Cosimo, can you or @behdad look at this?

**Comment by punchcutter** [comment]
Here's a tiny Glyphs file with a couple characters and the components that show this issue.

[NotoSerifKhmer_Interpolation_Test.glyphs.zip](https://github.com/googlei18n/noto-fonts/files/1545384/NotoSerifKhmer_Interpolation_Test.glyphs.zip)

**Comment by anthrotype** [comment]
I’ll have a look, but if you say it also happens when exporting from Glyphs, then i’d say it is a source rather than pipeline issue and the component should be decomposed and merged with the other contours in the sources.

**Comment by punchcutter** [comment]
In this case decomposing "fixes" the issue, but does not address it at all. I still want to know why, for example, one component is interpolated to 124 units while the attaching component is interpolated to 123 units. Well, I know why. It's just the math. Mostly I just opened this to track the issue and make everyone aware of it.

**Comment by schriftgestalt** [comment]
I could fix the issue in Glyphs (I had tried several times since some years ago). The solution is to not round any coordinates (the nodes and the position of the components) until the components are decomposed.

**Comment by punchcutter** [comment]
The issue seems to be fixed in Glyphs 2.5b (1097):

- Improve the rounding after interpolation to avoid minimal difference in stem width from components

**Comment by anthrotype** [comment]
> The solution is to not round any coordinates (the nodes and the position of the components) until the components are decomposed.

we should check that ufo2ft does the same. @punchcutter care to open an issue there as well?

**Comment by punchcutter** [comment]
Decompose components before interpolation to avoid rounding differences https://github.com/googlei18n/ufo2ft/issues/192

**Comment by simoncozens** [comment]
This seems to now be fixed:

<img width="795" alt="Screenshot 2022-02-18 at 10 27 56" src="https://user-images.githubusercontent.com/106728/154665223-985cfece-fa71-4774-b175-65068a37b72e.png">
