### ISSUE TITLE
Noto Sans Arabic: Wrong ligatures in Uyghur text

### ISSUE THREAD

**Issue by Buernia** [googlefonts/noto-fonts#1017]
### Font 
  > Noto Sans Arabic

### Where the font came from, and when
  >   Site: https://noto-website-2.storage.googleapis.com/pkgs/Noto-hinted.zip
  >   Date: 2017-12-19 

### Font Version
  > Version 2.0000

### Issue
  > Some ligatures in Uyghur text is wrong, for example, چە (_che_) in ئۇيغۇرچە (_uyghurche_), ھە (_he_) in ھەر (_her_), گە (_ge_) in گەۋدىلىك (_gewdilik_).

### Image
![Sample image](https://user-images.githubusercontent.com/11886946/34210252-3446758e-e5d0-11e7-9072-968af49593a8.png)

**Comment by marekjez86** [comment]
@Buernia : thank you I'll investigate it (and thank you for providing the text). Please let me know if you see any other issues.

**Comment by KrasnayaPloshchad** [comment]
Both ە, چ, ھ ,گ has an entry for joining, you just add rules to make their contextual forms works as expected.

**Comment by nizarsq** [comment]
This issue fixed for NotoSansArabic
<img width="494" alt="Screen Shot 2020-05-30 at 12 39 35 PM" src="https://user-images.githubusercontent.com/22158882/83337738-a6679880-a272-11ea-911f-535128aaeb26.png">

**Comment by nizarsq** [comment]
This issue fixed on unhinted font, on hinted font still reproducible.
<img width="812" alt="Screen Shot 2020-05-30 at 12 49 05 PM" src="https://user-images.githubusercontent.com/22158882/83337909-19bdda00-a274-11ea-8d94-7ed74f9de734.png">
<img width="799" alt="Screen Shot 2020-05-30 at 12 49 29 PM" src="https://user-images.githubusercontent.com/22158882/83337910-1aef0700-a274-11ea-8026-6b9149b0180f.png">

**Comment by nizarsq** [comment]
Issue fixed.
