### ISSUE TITLE
NotoSansTamil only (not Serif) uses older form of U+0BF7

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#1019]
0BF7 | CREDIT SIGN | JH (John Hudson) stated: “FIX. The extra vertical stroke corresponds to an older form in the Unicode glyph charts. This was corrected as per the note on page 24 of this document:http://unicode.org/L2/L2012/12231-tamil-fractions-symbols-proposal.pdf “

**Comment by sridatta1** [comment]
Also the glyph of Tamil debit sign 0BF6 ௶ was changed according to http://www.unicode.org/L2/L2013/13174-tamil-font-chg.pdf 
see
http://www.unicode.org/charts/PDF/U0B80.pdf

**Comment by nizarsq** [comment]
Look like U+0BF7 and U+0BF6 newer form ARE exist in NotoSansTamil. Closing the bug for now.
<img width="1058" alt="Screen Shot 2020-06-22 at 11 25 28 PM" src="https://user-images.githubusercontent.com/22158882/85368212-b2482280-b4df-11ea-837b-3def561c8b94.png">
