### ISSUE TITLE
Noto Sans Mono: fi ligature in “liga” seems unusual

### ISSUE THREAD

**Issue by sommerluk** [googlefonts/noto-fonts#1021]
Noto Sans Mono: fi ligature in “liga” seems unusual

I’m using this Noto Sans Mono version:
![screenshot 1](https://user-images.githubusercontent.com/6830724/34442738-f5e60dde-ecbb-11e7-9328-c0ba913933ff.png)

Noto Sans Mono has an fi ligature in the `liga` lookup table. As `liga` is enabled by default in the OpenType specification, many applications apply this ligature – and as the ligature glyph only needs half the space then separated “f” and “i”, this might be surprising. This happens for example when using Noto Sans Mono in Firefox.

Using `liga` seems to me a rather unusual choise for a monospace font. What is the reason?

**Comment by sommerluk** [comment]
Would it be an option to use `dlig` instead of `liga`?

**Comment by fitojb** [comment]
`dlig` seems fine to me.

**Comment by twardoch** [comment]
I’ve noticed that more and more people find standard Latin ligatures, esp. the "fi" one, odd. In future, I’ll be recommending to type designers that they consider using the `dlig` feature even for "f" ligatures — unless the design really requires the ligatures to be on by default. For non-Latin scripts, the orthographically required ligatures should be placed in `rlig` anyway, possibly with `liga` as a fallback for legacy implementations.  

So far, many designers have been including the "f" ligatures in the `liga` feature habitually, almost automatically. In addition, for Noto Sans Mono, the fact that the `fi` ligatures reduces the space taken by the glyphs by half, is an additional complication — so I’d certainly recommend that the ligatures are placed in `dlig` in Nono Sans Mono. 

My future recommendation would be to generally consider using `rlig` for the orthographically required ligatures and `dlig` for anything else, and be really picky about whether to include `liga` at all, and if it is included, to be really careful and conscious about what’s included in `liga`.

**Comment by fitojb** [comment]
To be clear, at least to me, the “fi” ligatures only stand out as odd in monospaced faces.

**Comment by sommerluk** [comment]
> To be clear, at least to me, the “fi” ligatures only stand out as odd in monospaced faces.

👍

**Comment by marekjez86** [comment]
@waksmonskiMT : Should there be  fi ligature in the liga lookup table in the Monospace font?

**Comment by AlexBlandin** [comment]
I don't get why they even have the "fi" ligatures in a monospace font, when I want to write "fields" or something it just butchers the length, making it seem like I wrote "felds".

**Comment by siikamiika** [comment]
I thought something was wrong with my font configuration when I was typing to a `<textarea>` that had `font-family: monospace` (resolved to `Noto Sans Mono Regular`) but the ligature for `fi` AND `fl` appeared.
Demo:
![test](https://user-images.githubusercontent.com/5602483/35743629-d579993e-0846-11e8-876e-eb5774105d42.gif)
I don't think that should happen with monospaced fonts.

**Comment by siikamiika** [comment]
@marekjez86 Don't know what happened but seems like my comment unassigned @waksmonskiMT

**Comment by marekjez86** [comment]
@siikamiika : looks that waksmonskiMT cannot be assigned (she dropped out of the system?). it wasn't your comment - IMHO, the system's "consistency checker" did it while it was updating your comment. I'll re-assign it when I have a chance back to waksmonskiMT

**Comment by siikamiika** [comment]
@marekjez86 Huh, strange. Never happened to me before on GitHub.

Anyway, I patched the `NotoSansMono-*.ttf` fonts for my own use and here's a .zip if somebody else needs them.
(LICENSE attached)

[noto-sans-mono-patched-ligatures.zip](https://github.com/googlei18n/noto-fonts/files/1690450/noto-sans-mono-patched-ligatures.zip)

**Comment by marekjez86** [comment]
@waksmonskiMT : here are the ligatures that seem to be in the Noto Sans Mono font. Could we deal with them properly (please take into consideration https://github.com/googlei18n/noto-fonts/issues/1021#issuecomment-354636142 ) but it's up to you as long as the font allows to built terminals?

sub f f l by f_f_l;
sub f f i by f_f_i;
sub f i by f_i;
sub f l by f_l;
sub f f by f_f;

**Comment by marekjez86** [comment]
@sommerluk , @fitojb @AlexBlandin @siikamiika @machfour @ariasuni  please check out https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansMono

**Comment by sommerluk** [comment]
Thanks a lot! Much better like this!

By the way: For the new version, there are entries in the “dlig” lookup table for various ligatures. ffi, ffl and st work. fi and fl don’t. (Anyway, that’s not so important…)

Thanks a lot!

**Comment by teiesti** [comment]
@marekjez86 

As I understand Your last comment, there is a patch for this issue. My tests indeed show that the [latest version in the repository](https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansMono) is not affected. But the version published on the [official website](https://www.google.com/get/noto/#sans-mono) still is.

What is blocking the patch from actually being shipped?

**Comment by marekjez86** [comment]
Just having someone who can dot it issue (nothing else)

**Comment by teiesti** [comment]
Mhmm, that sounds like the most unfortunate answer You can give me. I would really appreciate, if You find someone who can do... ;-)

Anyway, thanks for honestly answering my question. You've given me reason to argue that the version in the repository is considered to be stable. And thank for providing the Noto fonts for free!

**Comment by marekjez86** [comment]
@teiesti : the version in repository will be posted on get/noto in any case

**Comment by dontdieych** [comment]
noto-fonts-extra (20180322-1 -> 20181024-1

Looks like new version fixed this problem? Typing 'fi' in konsole does not make weird glitch anymore.

**Comment by teiesti** [comment]
@dontdieych I think, you're right!

**Comment by marekjez86** [comment]
should be fixed

**Comment by marekjez86** [comment]
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansMono
or
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansMono
or 
https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/variable-ttf/NotoSansMono-VF.ttf

**Comment by marekjez86** [comment]
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansMono
or
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansMono
or
https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/variable-ttf/NotoSansMono-VF.ttf

**Comment by dhouck** [comment]
The version downloadable from https://www.google.com/get/noto/ still has ligatures. Is that site otherwise up to date, or should the download and preview links post elsewhere?

**Comment by marekjez86** [comment]
@dhouck : 
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansMono
or
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansMono
or
https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/variable-ttf/NotoSansMono-VF.ttf
