### ISSUE TITLE
Help Wanted in Noto Sans alignment

### ISSUE THREAD

**Issue by Rajesh-Kagathara** [googlefonts/noto-fonts#1024]
I am working on map font change from open sans to Noto Sans but facing issue in road label alignment. After changing the font labels are not central aligned it is shifted downside. 

It would be great help if you can point some resolution steps for it.

**Comment by Rajesh-Kagathara** [comment]
![option2](https://user-images.githubusercontent.com/34761880/34479864-04e6b340-efcf-11e7-8b78-9f0f6f484d1c.png)

**Comment by nizarsq** [comment]
@Rajesh-Kagathara is this issue still reproducible?

**Comment by Rajesh-Kagathara** [comment]
@nizarsq  I am not working anymore on that project so not sure that issue still present, but when I was working before 2 year at that time it was there as attached image.

**Comment by simoncozens** [comment]
I don't think we have enough information to know whether this is a font bug or a maps bug, and if nobody working on maps can currently tell us, then I'm not sure we can do much more with this.
