### ISSUE TITLE
U+06E0 is too similar to U+06DF

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1031]
### Font 
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-01-14

### Font Version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+06DF ARABIC SMALL HIGH ROUNDED ZERO and U+06E0 ARABIC SMALL HIGH UPRIGHT RECTANGULAR ZERO look confusingly similar. At normal text sizes, it is hard to tell which is which. U+06E0 should be taller.

### Character data
ا۟ا۠
U+0627 ARABIC LETTER ALEF
U+06DF ARABIC SMALL HIGH ROUNDED ZERO
U+0627 ARABIC LETTER ALEF
U+06E0 ARABIC SMALL HIGH UPRIGHT RECTANGULAR ZERO

### Screenshot
![ا۟ا۠](https://user-images.githubusercontent.com/1124347/34917495-562784ba-f915-11e7-9cea-c4c9781f3038.png)

**Comment by nizarsq** [comment]
Tested reported issue on the latest NotoSansArabic (unhinted) regular and U+06E0 seems to be taller. Please reopen the bug if you have other thoughts.
<img width="1289" alt="Screen Shot 2020-05-31 at 3 18 00 PM" src="https://user-images.githubusercontent.com/22158882/83363999-aa6ae780-a352-11ea-9d1d-1fc9959eceb5.png">
