### ISSUE TITLE
Misplaced superscript alef in Arabic presentation forms

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1032]
### Font 
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-01-14

### Font Version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+FC5B ARABIC LIGATURE THAL WITH SUPERSCRIPT ALEF ISOLATED FORM and U+FC5C ARABIC LIGATURE REH WITH SUPERSCRIPT ALEF ISOLATED FORM do not look like the sequences to which they decompose under NFKC: the superscript alefs should be above the base letters but are instead to the right.

### Character data
ﱛﱜذٰرٰ
U+FC5B ARABIC LIGATURE THAL WITH SUPERSCRIPT ALEF ISOLATED FORM
U+FC5C ARABIC LIGATURE REH WITH SUPERSCRIPT ALEF ISOLATED FORM
U+0630 ARABIC LETTER THAL
U+0670 ARABIC LETTER SUPERSCRIPT ALEF
U+0631 ARABIC LETTER REH
U+0670 ARABIC LETTER SUPERSCRIPT ALEF

### Screenshot
![ﱛﱜذٰرٰ](https://user-images.githubusercontent.com/1124347/34917615-e4be8060-f916-11e7-9027-d1730dc964d3.png)

**Comment by nizarsq** [comment]
This issue partially fixed, superscript alefs currently above the base letters but in some cases it overlap the dot.
<img width="1113" alt="Screen Shot 2020-06-02 at 12 03 05 PM" src="https://user-images.githubusercontent.com/22158882/83559319-3dc62900-a4c9-11ea-9965-03ca12d98445.png">
