### ISSUE TITLE
Incorrect diacritics in U+FDFD

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1033]
### Font 
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-01-14

### Font Version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
The diacritics in U+FDFD  are inconsistent and wrong. The sukun on the seen in the first line has a different shape from the sukun on the hah in the second line. It is odd for the first sukun to be above the tatweel as opposed to directly above the seen. All three of these alefs can take a wasla, so it is inconsistent that only the second has a wasla. There are a couple of harakat between the lines on the left side; I am not sure whether they were intended to be fathas or kasras, but either all the harakat should be included or none should be. There is a strange short vertical line below the yeh in the second line; perhaps it is supposed to be the superscript alef which is missing above the shadda in the first line.

### Character data
﷽
U+FDFD ARABIC LIGATURE BISMILLAH AR-RAHMAN AR-RAHEEM

### Screenshot
![﷽](https://user-images.githubusercontent.com/1124347/34917763-6b42212c-f918-11e7-9517-8fc6e4c7dc24.png)

**Comment by khaledhosny** [comment]
I’d also add that the vertical stacking of the lines is rather odd.

**Comment by nizarsq** [comment]
Look like all diacritics are removed in unhinted NotoSansArabic. For hinted NotoSansArabic still looks the same with inconsistent diacritics.
<img width="1093" alt="Screen Shot 2020-05-30 at 11 20 38 PM" src="https://user-images.githubusercontent.com/22158882/83345888-bc09ac00-a2cc-11ea-8597-62326076f374.png">

**Comment by nizarsq** [comment]
This issue fixed.

**Comment by nizarsq** [comment]
Currently FDFD redesigned
<img width="1039" alt="Screen Shot 2020-12-13 at 3 38 13 PM" src="https://user-images.githubusercontent.com/22158882/102027480-38d81100-3d59-11eb-95b8-b47f86b8e6a9.png">

**Comment by dscorbett** [comment]
Why is there a tatweel between the second lam and the heh in “ٱللَّـه”? Was a superscript alef meant to go there?

**Comment by nizarsq** [comment]
> Why is there a tatweel between the second lam and the heh in “ٱللَّـه”? Was a superscript alef meant to go there?

@dscorbett there's no reason other than making the word الله rendering consistent with the rest of the words (in terms of width), I'm not aware of any regulation about using the tatweel. There's no superscript alef meant to go there.

**Comment by khaledhosny** [comment]
> @dscorbett there's no reason other than making the word الله rendering consistent with the rest of the words (in terms of width),

But this isn’t needed or even desired.

> I'm not aware of any regulation about using the tatweel. 

There are, [plenty of them](https://www.tug.org/tugboat/tb27-2/tb87benatia.pdf) actually. It depends on the calligraphic style and some times the calligrapher, but there are some general rules. In case of the word الله, tatweel is undesired as it usually have an overall shape as a single unit, but it is sometimes permissible before the ha’ to place the superscript alef in vertically-constraint situations, which is not the case here.
