### ISSUE TITLE
Add different weights of Arimo, Tinos and Cousine.

### ISSUE THREAD

**Issue by tankmohit** [googlefonts/noto-fonts#1034]
Arimo, Tinos and Cousine are beautiful fonts without a doubt.
I use them on my all machines even on windows. 
It would be great if Google decide to make some weights for those great fonts.

**Comment by KrasnayaPloshchad** [comment]
Alternatively, they can be achieved by adding font variations into them.

**Comment by CamelCase11** [comment]
Here I forgot to mention that I am talking about thin, light and medium(semibold) weights.

**Comment by CamelCase11** [comment]
But what about Tinos and cousine. Cousine is very beautiful font. All it need are different weights.

**Comment by KrasnayaPloshchad** [comment]
> Here I forgot to mention that I am talking about thin, light and medium(semibold) weights.

Yes, variable font can do it too.

**Comment by cssobral2013** [comment]
@davelab6, Archivo is good but has no Light nor Black weights, so I prefer to wait this issue to be solved.

**Comment by marekjez86** [comment]
duplicate of https://github.com/googlefonts/noto-fonts/issues/1081
