### ISSUE TITLE
No initial or medial glyph for U+06D1 ARABIC LETTER YEH WITH THREE DOTS BELOW

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1040]
### Font 
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-02-04

### Font Version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+06D1 ARABIC LETTER YEH WITH THREE DOTS BELOW, a dual-joining character, has no glyphs for its initial and medial forms.

### Character data
ۑۑـ
U+06D1 ARABIC LETTER YEH WITH THREE DOTS BELOW
U+06D1 ARABIC LETTER YEH WITH THREE DOTS BELOW
U+0640 ARABIC TATWEEL

### Screenshot
![ۑۑـ](https://user-images.githubusercontent.com/1124347/35780015-eb9efe4e-09a3-11e8-8c99-3a1eb49ad7e9.png)

**Comment by marekjez86** [comment]
@TidharC : any comment/suggestion/recommendation on this?

**Comment by nizarsq** [comment]
U+06D1 init and medial issue is fixed. See issue https://github.com/googlefonts/noto-fonts/issues/1177 for more details.
<img width="1133" alt="Screen Shot 2020-06-02 at 11 57 47 AM" src="https://user-images.githubusercontent.com/22158882/83558775-626dd100-a4c8-11ea-98de-d4e1695371fa.png">

**Comment by nizarsq** [comment]
Fix for NotoSansArabic revised. Fixing in 2.02. NotoKufiArabic has same issue

**Comment by nizarsq** [comment]
U+06D1 initial and medial glyph added to NotoKufiArabic

**Comment by nizarsq** [comment]
This issue fixed. U+06D initial and medial glyph added to NotoSansArabic.
