### ISSUE TITLE
Inverted three dots on two Arabic letters

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1041]
### Font 
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-02-04

### Font Version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
The three dots of U+08AE ARABIC LETTER DAL WITH THREE DOTS BELOW and U+08AF ARABIC LETTER SAD WITH THREE DOTS BELOW should point down, but in Noto Sans Arabic they point up.

### Character data
ࢮࢯ
U+08AE ARABIC LETTER DAL WITH THREE DOTS BELOW
U+08AF ARABIC LETTER SAD WITH THREE DOTS BELOW

### Screenshot
![ࢮࢯ](https://user-images.githubusercontent.com/1124347/35780088-a2988944-09a4-11e8-9ba4-dbe9557fcf79.png)

**Comment by marekjez86** [comment]
@TidharC : any comment/suggestion/recommendation on this?

**Comment by nizarsq** [comment]
This issue is fixed.
<img width="990" alt="Screen Shot 2020-06-02 at 11 49 42 AM" src="https://user-images.githubusercontent.com/22158882/83558097-59c8cb00-a4c7-11ea-917e-bec1cb501a58.png">

**Comment by nizarsq** [comment]
This issue fixed
