### ISSUE TITLE
Incorrect decomposition of U+FDF0

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1042]
### Font 
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-02-04

### Font Version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+FDF0 ARABIC LIGATURE SALLA USED AS KORANIC STOP SIGN ISOLATED FORM’s compatibility decomposition is U+0635 U+0644 U+06D2, but Noto Sans Arabic renders it as if the last character of the decomposition were U+064A.

### Character data
ﷰ صلے
U+FDF0 ARABIC LIGATURE SALLA USED AS KORANIC STOP SIGN ISOLATED FORM
U+0020 SPACE
U+0635 ARABIC LETTER SAD
U+0644 ARABIC LETTER LAM
U+06D2 ARABIC LETTER YEH BARREE

### Screenshot
![ﷰ صلے](https://user-images.githubusercontent.com/1124347/35780186-d8abc338-09a5-11e8-8df7-f7fa546f4516.png)

**Comment by marekjez86** [comment]
@TidharC : any comment/suggestion/recommendation on this?

**Comment by nizarsq** [comment]
This issue fixed.
<img width="1077" alt="Screen Shot 2020-05-30 at 10 52 29 PM" src="https://user-images.githubusercontent.com/22158882/83345492-88c51e00-a2c8-11ea-82e4-04f0470c9ff5.png">

**Comment by dscorbett** [comment]
This bug is back in [Noto Sans Arabic 2.002](https://github.com/googlefonts/noto-fonts/blob/ca8ab270d71a73fae3bba6915ae3d6231bfc5a96/unhinted/otf/NotoSansArabic/NotoSansArabic-Regular.otf).

**Comment by nizarsq** [comment]
In current NotoSansArabic and NotoSansArabicUI 2.002 this issue reproducible. Thank you @dscorbett.
![Screenshot_20201013-112756_Chrome](https://user-images.githubusercontent.com/22158882/95900881-639ced80-0d47-11eb-89be-99d0fe3accad.jpg)
