### ISSUE TITLE
Misplaced dot on U+FDFB ARABIC LIGATURE JALLAJALALOUHOU

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1043]
### Font 
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-02-04

### Font Version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
Noto Sans Arabic’s U+FDFB ARABIC LIGATURE JALLAJALALOUHOU glyph has a dot under the heh, on the left side. The dot should instead be under one of the jeems, on the right side.

### Character data
ﷻ
U+FDFB ARABIC LIGATURE JALLAJALALOUHOU

### Screenshot
![ﷻ](https://user-images.githubusercontent.com/1124347/35780661-cb8e943a-09ac-11e8-870f-554e8cf6addc.png)

**Comment by nizarsq** [comment]
The dot has been moved but still not aligned correctly. For NotoSansArabic hinted fints still showing the dot under the heh.
<img width="1296" alt="Screen Shot 2020-05-30 at 10 43 07 PM" src="https://user-images.githubusercontent.com/22158882/83345415-a940a880-a2c7-11ea-9846-ecdd06000fae.png">

**Comment by nizarsq** [comment]
This issue currently reproducible in NotoNaskhArabicUI Version 2.000 and NotoNaskhArabicUI Version 2.000
