### ISSUE TITLE
Incorrect diacritics in U+FDFB

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1044]
### Font 
NotoNaskhArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoNaskhArabic-unhinted.zip
Date: 2018-02-04

### Font Version
Version 1.07 uh

### Issue
The diacritics in U+FDFB are inconsistent and wrong. The glyph looks like it reads ⟨جَل جَّلُٰالُهُ⟩. The shadda–fatha combination should be above the first lam, not above a jeem. If one jeem has a fatha, so should the other. The second damma (above the lam) should be a fatha. Either the first damma (above the superscript alef) should be a madda, or the superscript alef and damma should be deleted; I am not sure a superscript alef can occur before an alef like that, so you should ask a native speaker of Arabic which fix is appropriate.

### Character data
ﷻ
U+FDFB ARABIC LIGATURE JALLAJALALOUHOU

### Screenshot
![ﷻ](https://user-images.githubusercontent.com/1124347/35780893-7ada521e-09b0-11e8-8794-e9021e083c01.png)

**Comment by marekjez86** [comment]
@TidharC : any comment on this?

**Comment by nizarsq** [comment]
This issue still reproducible
<img width="542" alt="Screen Shot 2020-05-23 at 2 17 19 AM" src="https://user-images.githubusercontent.com/22158882/82726862-c0fea800-9c9b-11ea-8be8-054fa7318a90.png">

**Comment by nizarsq** [comment]
Repositioned the damma locations, the rest looks ok to me. Changes will be in NotoNaskhArabic  2.008

**Comment by dscorbett** [comment]
This should be reopened. The new glyph still has three dammas. The shadda is still above the wrong letter.
![ﷻ](https://user-images.githubusercontent.com/1124347/128616527-46e6b272-87ea-41fc-95d1-765821dae129.png)
