### ISSUE TITLE
Do not camel-case style names

### ISSUE THREAD

**Issue by brawer** [googlefonts/noto-fonts#1050]
Currently, Noto uses camel-cased style names such as SemiBold or UltraCondensed, which is geeky but rather unusual for fonts. Proposal: Replace “SemiBold” by “Semibold”, “UltraCondensed” by “Ultracondensed”, and likewise for all other camel-cased style names. See also [this TypeDrawers discussion](http://typedrawers.com/discussion/2573/semi-bold-semibold-semi-bold-semi-bold-or-semibold).

**Comment by marekjez86** [comment]
@behdad , @dougfelt : any opinion on this?

**Comment by behdad** [comment]
Semibold is an exception in that it has become a word by itself. "Ultracondensed" would be horrible. I suggest doing nothing.
