### ISSUE TITLE
Inaccessible OpenType features in Serbian

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1052]
### Font 
NotoSans-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-unhinted.zip
Date: 2018-02-24

### Font Version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
Most features are not applied in Serbian. This is because most of the lookups do not include the language system 'SRB ' with the script 'cyrl'. For example, 'zero' does not work in Serbian.

### Character data
Љ0
U+0409 CYRILLIC CAPITAL LETTER LJE
U+0030 DIGIT ZERO

### Screenshot
`hb-view NotoSans-Regular.ttf -u 409,30 --features zero -O png`
![ij](https://user-images.githubusercontent.com/1124347/36633575-51201010-1966-11e8-9fec-11cf8414653d.png)
`hb-view NotoSans-Regular.ttf -u 409,30 --features zero -O png --language sr`
![ij](https://user-images.githubusercontent.com/1124347/36633584-6afd5204-1966-11e8-891f-9b9c1c94d2ec.png)

**Comment by twardoch** [comment]
This is a bug that pops out in various fonts from various vendors. All non-language-specific features need to be registered in all languagesystems that the font has any language-specific features registered in. 

This can be done in FEA syntax by enumerating all languagesystems that are ever used in the font at the beginning of the feature definitions via the "languagesystem" keyword. 

There quite a few fonts out there that neglect to do that.

**Comment by moyogo** [comment]
Confirmed as fixed in Noto Sans, Noto Sans Display, Noto Serif, Noto Serif Display, Noto Sans Mono.
The `languagesystem SRB` is in the beginning of the features and other features than locl work in Serbian:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/1923747/113221552-2e487580-927d-11eb-8689-fa94f19e1a38.png">
