### ISSUE TITLE
Noto Sans/Serif Malayalam: Missing glyph for ങ്ക്ല  /ng-k-la/ ligature

### ISSUE THREAD

**Issue by cibu** [googlefonts/noto-fonts#1053]
### Title 
  User reported issue: Noto Sans/Serif Malayalam: Missing glyph for ങ്ക്ല /ng-k-la/ ligature

### Font 
  NotoSansMalayalam-Regular.ttf
  NotoSerifMalayalam-Regular.ttf

### Font Version
  Sans Version 1.04
  Serif Version 1.01

### OS name and version
  Any

### Issue
 
Missing glyph for ങ്ക്ല /ng-k-la/ ligature:
  ‎0D19  MALAYALAM LETTER NGA
  ‎0D4D  MALAYALAM SIGN VIRAMA
  ‎0D15  MALAYALAM LETTER KA
  ‎0D4D  MALAYALAM SIGN VIRAMA
  ‎0D32  MALAYALAM LETTER LA
  
### Screenshot
Screenshot of the current output with Noto Sans Malayalam:
![image](https://user-images.githubusercontent.com/1966942/36749316-520932de-1bf2-11e8-8451-59d73649aa33.png)

Expected output (Malayalam Sangam MN, the default Malayalam font in MacOS is used):
![image](https://user-images.githubusercontent.com/1966942/36749230-0e4611fc-1bf2-11e8-93ba-f0380e99d01a.png)

**Comment by marekjez86** [comment]
should be fixed in the newly released https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSerifMalayalam ; not fixed in Sans though

**Comment by nizarsq** [comment]
Confirming the fix in Serif but not Sans.
<img width="1085" alt="Screen Shot 2020-06-19 at 11 11 50 PM" src="https://user-images.githubusercontent.com/22158882/85194400-6482ae80-b282-11ea-8f79-cacd8e0cd03a.png">
<img width="906" alt="Screen Shot 2020-06-19 at 11 11 23 PM" src="https://user-images.githubusercontent.com/22158882/85194426-6ba9bc80-b282-11ea-8355-2782ac6a6bc8.png">

**Comment by marekjez86** [comment]
fixed with the newest release of Sans (no issue for Serif)
