### ISSUE TITLE
Missing anchor on khanda ta in Noto Serif Bengali

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1055]
### Font 
NotoSerifBengali-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifBengali-unhinted.zip
Date: 2018-02-28

### Font Version
Version 1.01 uh

### Issue
The reph is not centered above the khanda ta, as it is in Noto Sans Bengali.

### Character data
র্ৎ
U+09B0 BENGALI LETTER RA
U+09CD BENGALI SIGN VIRAMA
U+09CE BENGALI LETTER KHANDA TA

### Screenshot
![র্ৎ](https://user-images.githubusercontent.com/1124347/36819849-17412568-1cb9-11e8-8617-2cc4a89b3d17.png)

**Comment by marekjez86** [comment]
We are in the process of making new Noto Serif Bengali. I'll keep this bug open to make sure that the new font behaves properly. We will NOT fix the older Noto Serif Bengali.

**Comment by marekjez86** [comment]
![bn-1055](https://user-images.githubusercontent.com/13322623/36871136-0da833d2-1d56-11e8-8d42-eee269e8fd03.jpg)

**Comment by marekjez86** [comment]
fixed in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSerifBengali
