### ISSUE TITLE
Dentistry symbols don’t connect

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1059]
### Font 
NotoSansSymbols-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansSymbols-unhinted.zip
Date: 2018-03-01

### Font Version
Version 1.06 uh

### Issue
Dentistry symbols should connect to each other like box-drawing symbols. For example, there should be no breaks in the top stroke of ⎾⏁ or the bottom stroke of ⏈⏌.

### Character data
⎾⏁⏈⏌
U+23BE DENTISTRY SYMBOL LIGHT VERTICAL AND TOP RIGHT
U+23C1 DENTISTRY SYMBOL LIGHT DOWN AND HORIZONTAL WITH CIRCLE
U+23C8 DENTISTRY SYMBOL LIGHT UP AND HORIZONTAL WITH WAVE
U+23CC DENTISTRY SYMBOL LIGHT VERTICAL AND BOTTOM LEFT

### Screenshot
![⎾⏁⏈⏌](https://user-images.githubusercontent.com/1124347/36875642-e24d77be-1d7e-11e8-98a0-b0606cff6704.png)

**Comment by nizarsq** [comment]
This issue fixed.
<img width="969" alt="Screen Shot 2020-07-27 at 8 45 09 PM" src="https://user-images.githubusercontent.com/22158882/88616862-12cfff80-d04a-11ea-8f57-226cebc3183b.png">
