### ISSUE TITLE
Misplaced holam on vav

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1067]
### Font 
NotoSerifHebrew-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifHebrew-unhinted.zip
Date: 2018-03-04

### Font Version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+05B9 (holam) is above and to the left of U+05D5 (vav), but it should be directly above. Cf. the canonically equivalent U+FB4B HEBREW LETTER VAV WITH HOLAM, which looks right.

Furthermore, the meaningless sequence U+05D5 U+05C1 (vav with shin dot) gets a single glyph in this font; there seems to be some misunderstanding in this font of how Hebrew points work in Unicode.

### Character data
וֹ
U+05D5 HEBREW LETTER VAV
U+05B9 HEBREW POINT HOLAM

### Screenshot
![וֹ](https://user-images.githubusercontent.com/1124347/36999405-fff5473a-208d-11e8-84c3-03f8eaaf4b01.png)

**Comment by dscorbett** [comment]
This bug is also present in Noto Rashi Hebrew.
![וֹ](https://user-images.githubusercontent.com/1124347/71425157-9e724f80-2667-11ea-861a-4b41e75363ef.png)

**Comment by nizarsq** [comment]
Issue reported is reproducible.
<img width="988" alt="Screen Shot 2020-08-04 at 10 11 45 PM" src="https://user-images.githubusercontent.com/22158882/89374180-7cca5380-d69f-11ea-9ced-995fa376c19d.png">

**Comment by nizarsq** [comment]
On U+05D5 HEBREW LETTER VAV, U+05B9 (HEBREW POINT HOLAM) should be positioned on the top center. U+05BA HEBREW POINT HOLAM HASER FOR VAV encoded to be used with U+05D5

**Comment by kosmynkab** [comment]
Resolved across all Noto Sans, Serif and Rashi versions (will be pushed in the collective update of multiple issue resolution).
