### ISSUE TITLE
Poor spacing of dagesh

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1071]
### Font 
NotoSansHebrew-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansHebrew-unhinted.zip
Date: 2018-03-04

### Font Version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
After the thin Hebrew letters vav, zayin, and yod, the dagesh intrudes into the following glyph’s space. In the sequence ⟨יּש⟩ the dagesh actually bumps into the following letter; in other sequences it just looks tightly kerned.

### Character data
יּש
U+05D9 HEBREW LETTER YOD
U+05BC HEBREW POINT DAGESH OR MAPIQ
U+05E9 HEBREW LETTER SHIN

### Screenshot
![יּש](https://user-images.githubusercontent.com/1124347/37007776-0551b8a2-20ad-11e8-9274-29a92e2e59b7.png)

**Comment by nizarsq** [comment]
Look like this issue resolved (at least after yod) @dscorbett any openion/thoughts?
<img width="877" alt="Screen Shot 2020-08-04 at 9 18 51 PM" src="https://user-images.githubusercontent.com/22158882/89371390-1857c600-d698-11ea-81a7-36dc71538550.png">

**Comment by dscorbett** [comment]
I tested vav, zayin, and yod, and they all look good now.
