### ISSUE TITLE
all Noto fonts: advance width of U+002c should be the same as period width if both are present

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#1072]
That's not the case for the following fonts (notice that this a noto_lint.py warning only)

======== NotoSansBengali-Regular.otf ========
W <advances/comma_period> The advance of U+002c (comma.beng, glyph 583) is 263, but expected 268.
======== NotoSansBengaliUI-Regular.otf ========
W <advances/comma_period> The advance of U+002c (comma.beng, glyph 574) is 263, but expected 268.
======== NotoSansKhmer-Regular.otf ========
W <advances/comma_period> The advance of U+002c (comma, glyph 9) is 250, but expected 268.
======== NotoSansMalayalam-Regular.otf ========
W <advances/comma_period> The advance of U+002c (comma.mlym, glyph 271) is 250, but expected 268.
======== NotoSansMalayalamUI-Regular.otf ========
W <advances/comma_period> The advance of U+002c (comma.mlym, glyph 271) is 250, but expected 268.
======== NotoSansTamil-Regular.otf ========
W <advances/comma_period> The advance of U+002c (comma.tamil, glyph 179) is 250, but expected 268.
======== NotoSansTamilUI-Regular.otf ========
W <advances/comma_period> The advance of U+002c (comma.tamil, glyph 179) is 250, but expected 268.
======== NotoSerifGujarati-Regular.otf ========
W <advances/comma_period> The advance of U+002c (comma, glyph 366) is 315, but expected 299.
======== NotoSerifKannada-Regular.otf ========
W <advances/comma_period> The advance of U+002c (comma, glyph 317) is 208, but expected 192.
======== NotoSerifDisplay-Italic.otf ========
W <advances/comma_period> The advance of U+002c (comma, glyph 15) is 251, but expected 237.

**Comment by JelleBosmaMT** [comment]
There is no general rule that requires period and comma to be designed in such a way that they are on the same advance width. There is a great variation in shapes that a comma might have. 
In the case of scripts that may use subscript marks, or other kind of elements below the baseline, the tail of the comma may have to be kept at a distance, requiring a larger advance width as the period, which does not descend.
