### ISSUE TITLE
U+110BD KAITHI NUMBER SIGN does not combine with digits

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1074]
### Font
NotoSansKaithi-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansKaithi-unhinted.zip
Date: 2018-03-05

### Font version
Version 1.05 uh

### Issue
U+110BD KAITHI NUMBER SIGN is a control character that extends beneath the following digit sequence; see examples B, C, and D of [L2/08-400](http://www.unicode.org/L2/L2008/08400-kaithi-num-sign.pdf). In this font, it acts exactly like the simple punctuation mark U+110BC KAITHI ENUMERATION SIGN.

### Character data
𑂽१
U+110BD KAITHI NUMBER SIGN
U+0967 DEVANAGARI DIGIT ONE

### Screenshot
![𑂽१](https://user-images.githubusercontent.com/1124347/37011748-7d0f5b26-20bf-11e8-97b8-8f6ace4d6e35.png)

**Comment by dscorbett** [comment]
When it comes time to add support for Unicode 11.0, be aware that U+110CD KAITHI NUMBER SIGN ABOVE is another control character with similar requirements.

**Comment by marekjez86** [comment]
should be fixed in OTF: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansKaithi and TTF: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansKaithi
