### ISSUE TITLE
Kannada Ra+halant+Ra

### ISSUE THREAD

**Issue by MayuraVerma** [googlefonts/noto-fonts#1076]
## Defect Report
As stated in this issue https://github.com/googlei18n/noto-fonts/issues/5
u+0cb0 u+0ccd u+0cb0 should rendered "ra ra-blwf" instead of "ra repha" 
Same view was expressed here https://github.com/googlei18n/noto-fonts/issues/815#issuecomment-290929086

### Title 
  > Kannada Ra+halant+Ra

### Font 
  > 'NotoSerifKannada-Regular.ttf'.

### Where the font came from, and when
  > https://www.google.com/get/noto/#sans-knda
  >  Date: 2018-03-06 (preferred format)

### Font Version
  > 1.01uh

### OS name and version
  > Windows 10, Mac OS

### Application name and version
  > Word 2016

### Issue
  > ರ್ರ , u+0cb0 u+0ccd u+0cb0 should be "ra ra-blwf" instead of "ra repha"
### Screenshot
![screen shot 2018-03-08 at 7 42 41 pm](https://user-images.githubusercontent.com/14062593/37186014-e94d6a76-2308-11e8-9f40-c423a6f45deb.png)

**Comment by MayuraVerma** [comment]
This is still unresolved in newer version of Noto Serif Kannada 2.001

**Comment by nizarsq** [comment]
This issue fixed.
<img width="813" alt="Screen Shot 2020-06-18 at 12 04 37 AM" src="https://user-images.githubusercontent.com/22158882/84988844-8ef43080-b0f7-11ea-95ee-07e56f471ec7.png">
