### ISSUE TITLE
U+FB4C HEBREW LETTER BET WITH RAFE is combining

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1080]
### Font
NotoSansHebrew-Regular.ttf
NotoSerifHebrew-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansHebrew-unhinted.zip
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifHebrew-unhinted.zip
Date: 2018-03-04

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+FB4C HEBREW LETTER BET WITH RAFE acts like a combining mark.

### Character data
&#x5D0;&#xFB4C;
U+05D0 HEBREW LETTER ALEF
U+FB4C HEBREW LETTER BET WITH RAFE

### Screenshot
![&#x5D0;&#xFB4C;](https://user-images.githubusercontent.com/1124347/37101260-1c4a8664-21f3-11e8-961c-2ada2a8058b8.png)
![&#x5D0;&#xFB4C;](https://user-images.githubusercontent.com/1124347/37101337-4a6782f4-21f3-11e8-981d-61a44729214e.png)

**Comment by nizarsq** [comment]
Issue fixed.
<img width="793" alt="Screen Shot 2020-08-04 at 8 49 09 PM" src="https://user-images.githubusercontent.com/22158882/89369785-f2c8bd80-d693-11ea-9bca-65414b3a0651.png">
