### ISSUE TITLE
Brahmi 'dist' lookup is not applied

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1082]
### Font
NotoSansBrahmi-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansBrahmi-unhinted.zip
Date: 2018-03-09

### Font version
Version 1.03 uh

### Issue
The font uses a 'dist' lookup to kern vowel signs. The lookup has the 'DFLT' script tag. Because the default shaper does not enable 'dist', the lookup is not applied.

### Character data
𑀔𑀼𑀢
U+11014 BRAHMI LETTER KHA
U+1103C BRAHMI VOWEL SIGN U
U+11022 BRAHMI LETTER TA

### Screenshot
![𑀔𑀼𑀢](https://user-images.githubusercontent.com/1124347/37213552-6305c7c4-2380-11e8-97c9-40cf7fbfeacd.png)

**Comment by simoncozens** [comment]
This has since been fixed.
