### ISSUE TITLE
Incorrect Nukta (diacritic) position to base character ड and ढ

### ISSUE THREAD

**Issue by JeetendraJ** [googlefonts/noto-fonts#1088]
### Title 
  > Incorrect (diacritic) dot position to base character ड and ढ.

### Font 
  > NotoSansDevanagari-Regular.ttf.
  > 
![dot poistion](https://user-images.githubusercontent.com/31063238/37337848-6f08a868-26ad-11e8-998c-718384c3db30.JPG)
.

### Where the font came from, and when
  > https://github.com/jenskutilek/free-fonts/tree/master/Noto/Noto%20Sans%20Devanagari/TTF

### Font Version

  > * Win -- 1.06  > 

### OS name and version
  > Windows 10 1706

### Application name and version
  > All applications. Like JW Library

### Issue
  > Summarize the issue briefly -- one paragraph preferred

  1. Type in Hindi ड़ु and ढ़ु
  2. The dot position shifts to left
  3. It should just below the base character
  
### Character data
  > Unicode codepoints 0922+093C+0941 and 0922+093C+0941

### Screenshot
  > 
![dot poistion](https://user-images.githubusercontent.com/31063238/37338395-3e2db1dc-26af-11e8-8182-4a853f938d79.JPG)

## Tools for reporting bugs
  Useful tools for reporting bugs are available at: https://github.com/googlei18n/
  
### Harfbuzz hb-view and hb-shape
  These are part of the HarfBuzz distribution and can help isolate if an issue is in the app/OS, shaping engine, or font.
  * hb-view renders the text with the exact font (for example, to see how ligatured characters shape) using your installed version of HarfBuzz.

For example:
```
  hb-view --font-file {path to font} --text-file {path to text file} --output-file '{sample}.png'
```

* hb-shape shows glyph selection and positioning

### Fontview
  * Fontview displays the text.

### Fontdiff
  * Fontdiff displays the text using two versions of the font side by side.

**Comment by nizarsq** [comment]
This issue fixed in NotoSansDevanagari, tested both NotoSansDevanagari and NotoSerifDevanagari, both looks good to me. 
<img width="1395" alt="Screen Shot 2020-06-07 at 8 49 49 PM" src="https://user-images.githubusercontent.com/22158882/83991079-8aae6300-a900-11ea-85e7-302570638df6.png">
