### ISSUE TITLE
Wrong glyph for U+1D09 LATIN SMALL LETTER TURNED I

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1090]
### Font
NotoSerif-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerif-unhinted.zip
Date: 2018-03-13

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+1D09 LATIN SMALL LETTER TURNED I doesn’t look like a turned i: it looks like a small capital i with a dot below.

### Character data
ᴉ
U+1D09 LATIN SMALL LETTER TURNED I

### Screenshot
![ᴉ](https://user-images.githubusercontent.com/1124347/37361184-b2fc1c88-26c8-11e8-9d2c-1f0b6a6859b3.png)

**Comment by dscorbett** [comment]
This goes for U+1D4E MODIFIER LETTER SMALL TURNED I too.

**Comment by nizarsq** [comment]
This issue has been fixed
<img width="548" alt="Screen Shot 2020-07-14 at 9 10 40 PM" src="https://user-images.githubusercontent.com/22158882/87502466-799af500-c616-11ea-91bc-84c6983196bf.png">
