### ISSUE TITLE
Sans-serif math symbols have serifs

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1092]
### Font
NotoSerif-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerif-unhinted.zip
Date: 2018-03-13

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
Four sans-serif math symbols have serifs.

### Character data
⅁⅂⅃⅄
U+2141 TURNED SANS-SERIF CAPITAL G
U+2142 TURNED SANS-SERIF CAPITAL L
U+2143 REVERSED SANS-SERIF CAPITAL L
U+2144 TURNED SANS-SERIF CAPITAL Y

### Screenshot
![⅁⅂⅃⅄](https://user-images.githubusercontent.com/1124347/37441336-598f7018-27d7-11e8-919d-9bf5efe561e2.png)

**Comment by nizarsq** [comment]
Math symbols looks ok now
<img width="648" alt="Screen Shot 2020-07-16 at 9 23 15 PM" src="https://user-images.githubusercontent.com/22158882/87748373-910ae700-c7aa-11ea-9d56-24d34500373f.png">
