### ISSUE TITLE
Wrong glyph for U+A7FF LATIN EPIGRAPHIC LETTER ARCHAIC M

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1096]
### Font
NotoSerif-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerif-unhinted.zip
Date: 2018-03-13

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+A7FF should be as tall as other capital letters. In the italic fonts, its left and right arms should not be curved like a lowercase ⟨w⟩’s.

### Character data
Mꟿ
U+004D LATIN CAPITAL LETTER M
U+A7FF LATIN EPIGRAPHIC LETTER ARCHAIC M

### Screenshot
![Mꟿ](https://user-images.githubusercontent.com/1124347/37550796-cd95dfcc-2969-11e8-8b73-af00f8b34ee7.png)
![Mꟿ](https://user-images.githubusercontent.com/1124347/37550841-a9633540-296a-11e8-830a-b67dafc44079.png)

**Comment by nizarsq** [comment]
U+A7FF looks ok
<img width="575" alt="Screen Shot 2020-07-16 at 9 20 14 PM" src="https://user-images.githubusercontent.com/22158882/87748210-248fe800-c7aa-11ea-9a45-c9ed3f6aafa6.png">
