### ISSUE TITLE
0F02 and 0F03 drawing not consistent with Unicode Chart

### ISSUE THREAD

**Issue by eroux** [googlefonts/noto-fonts#1103]
### Title 
  0F02 and 0F03 drawing not consistent with Unicode Chart.

### Font 
  'NotoSansTibetan-Regular.ttf'.

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansTibetan-hinted.zip
Date: 2018-03-21

### Font Version
  1.01

### OS name and version
  Debian stretch

### Issue
The characters for 0F02 and 0F03 are drawn using 0F83 for the symbol above the letter, while on the [Unicode Chart](https://unicode.org/charts/PDF/U0F00.pdf) it's pretty clear that 0F82 should be used instead.

### Character data
- 0F02 (༂) should be similar to 0F60 0F74 0F82 0F7F (འུྂཿ), not 0F60 0F74 0F83 0F7F (འུྃཿ)
- 0F03 (༃) should be similar to 0F60 0F74 0F82 0F14 (འུྂ༔), not 0F60 0F74 0F83 0F14 (འུྃ༔)

**Comment by dscorbett** [comment]
The decompositions with U+0F82 are supported by [L2/08-220](http://unicode.org/L2/L2008/08220-deprecated.html). (Of course, they aren’t decompositions in the NFC sense, which, _pace_ [L2/18-078](http://www.unicode.org/L2/L2018/18078-tibetan-comps.pdf), can never be fixed.)

**Comment by eroux** [comment]
I have to say I'm a bit lost here, can you plese elaborate?

I can see the link to the 2008 paper which seems to say something similar to mine, but I'm not sure what kind of conclusion I'm supposed to draw from it?

Why do you say it can never be fixed? Is there a policy in Unicode never to say that a character is decomposeable? If so, I can change my request to simply deprecate the character... this would be possible right?

I'm not as familiar as you seem to be with the Unicode workflow, I'd be most happy to learn a bit more.

**Comment by dscorbett** [comment]
The 2008 paper is just further evidence to support this bug report.

Unicode’s [normalization stability policy](http://unicode.org/policies/stability_policy.html#Normalization) forbids the kind of change you propose: new characters can be decomposed but current ones cannot. Deprecation is still possible.

**Comment by eroux** [comment]
I see, thanks a lot! I guess I'll just send a new report to ask for deprecation. Also, just to be clear: all of this has nothing to do with the initial bug report, which is still valid and is about the shape of the top diacritic in Noto, which currently looks like 0F83 but should look like 0F82.

**Comment by marekjez86** [comment]
@eroux  @dscorbett : Tibetan will be re-designed at the end of this year or early next and sources published on https://github.com/googlei18n/noto-source/tree/master/src . While I will use the bug to build a case to make sure that the new version is OK, we will not fix this one in the existing version.

**Comment by eroux** [comment]
@marekjez86 thanks for the info. Out of curiosity, is there some info available on why the font will be re-designed or what the changes will be? Thanks!

**Comment by marekjez86** [comment]
@eroux : I should have phrased my answer better. We are striving to make sources of all our Noto fonts available at https://github.com/googlei18n/noto-source/tree/master/src (when we have we compile them using https://github.com/googlei18n/fontmake into TTF, OTF and variable fonts [if relevant] for publication). In addition, we have been publishing new sources and fonts for scripts that weren't covered before. The conversion process from the old TTF to glyphs source is an opportunity to fix bugs or to redesign the font. We don't have any re-design plans yet, but we'll take this bug and any others for Tibetan into consideration re-issuing Tibetan.

**Comment by eroux** [comment]
I see, that's very clear, thanks a lot, this looks like exciting news!

**Comment by marekjez86** [comment]
should be fixed in newly updated https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSerifTibetan (and its TTF counterpart)

**Comment by marekjez86** [comment]
[tib-1103-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/3288443/tib-1103-Serif.pdf)
