### ISSUE TITLE
Questionable glyph for U+0F0E TIBETAN MARK NYIS SHAD

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1106]
### Font
NotoSansTibetan-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansTibetan-unhinted.zip
Date: 2018-03-21

### Font version
Version 1.01 uh

### Issue
U+0F0E TIBETAN MARK NYIS SHAD is slightly narrower than two adjacent U+0F0D TIBETAN MARK SHADs, but [_The Unicode Standard_ says that U+0F0E should be _wider_, or at least not narrower](http://www.unicode.org/versions/Unicode10.0.0/ch13.pdf#page=16). However, many Tibetan fonts, including some made by people who know Tibetan, do make U+0F0E narrower. It is not clear what to do, but as long as you’re redesigning Noto Sans Tibetan, you should be aware of the issue.

### Character data
﻿﻿﻿༎།།
U+0F0E TIBETAN MARK NYIS SHAD
U+0F0D TIBETAN MARK SHAD
U+0F0D TIBETAN MARK SHAD

### Screenshot
![༎ །།](https://user-images.githubusercontent.com/1124347/37794431-ce380cac-2de7-11e8-8965-4b094eb752d2.png)

**Comment by marekjez86** [comment]
@dscorbett : my reading of what's coming in Unicode that this is a designer choice (and Unicode will be changed) hence I'm closing this one

**Comment by marekjez86** [comment]
@dscorbett : 
Looks that for some Tibetan fonts which came from China's Tibetan Research Center the following are the same (so we might further revise Unicode spec):
U+0F0E TIBETAN MARK NYIS SHAD
two adjacent U+0F0D TIBETAN MARK SHADs
single U+0F0D TIBETAN MARK SHAD

My gut feeling is that there shouldn't be a spec regarding the distance between SHADs

see the following

[Qomolangma-Tsumachu.ttf.pdf](https://github.com/googlefonts/noto-fonts/files/3288144/Qomolangma-Tsumachu.ttf.pdf)

[Qomolangma-Tsuring.ttf.pdf](https://github.com/googlefonts/noto-fonts/files/3288145/Qomolangma-Tsuring.ttf.pdf)

[Qomolangma-Tsutong.ttf.pdf](https://github.com/googlefonts/noto-fonts/files/3288147/Qomolangma-Tsutong.ttf.pdf)
