### ISSUE TITLE
Wrong glyph for U+1F190 SQUARE DJ

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1110]
### Font
NotoSansSymbols-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansSymbols-unhinted.zip
Date: 2018-03-24

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
In Noto Sans Symbols, U+1F190 SQUARE DJ has a square, but it should not. In Unicode character names, “square” means it has the metrics of a CJK ideographic square, whereas “squared” means it is drawn inside a square.

### Character data
🆐
U+1F190 SQUARE DJ

### Screenshot
![🆐](https://user-images.githubusercontent.com/1124347/37865114-24d82d0a-2f4e-11e8-9e0b-991ea1478517.png)

**Comment by nizarsq** [comment]
This issue fixed.
<img width="822" alt="Screen Shot 2020-07-27 at 8 41 31 PM" src="https://user-images.githubusercontent.com/22158882/88616659-93423080-d049-11ea-89e1-1b766f2623b7.png">
