### ISSUE TITLE
U+110B9 KAITHI SIGN VIRAMA is never visible

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1111]
### Font
NotoSansKaithi-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansKaithi-unhinted.zip
Date: 2018-03-25

### Font version
Version 1.05 uh

### Issue
U+110B9 KAITHI SIGN VIRAMA always induces the half form of the preceding consonant, even in contexts where a visible virama would be more appropriate.

### Character data
𑂢𑂹
U+110A2 KAITHI LETTER NA
U+110B9 KAITHI SIGN VIRAMA

### Screenshot
![𑂢𑂹](https://user-images.githubusercontent.com/1124347/37880287-d2e5f5fc-3053-11e8-8da1-772d7352ba4b.png)

**Comment by marekjez86** [comment]
should be fixed in OTF: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansKaithi and TTF: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansKaithi
