### ISSUE TITLE
Wrong glyph for U+23D6 METRICAL TWO SHORTS JOINED

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1112]
### Font
NotoSansSymbols-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansSymbols-unhinted.zip
Date: 2018-03-24

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
The glyph of U+23D6 METRICAL TWO SHORTS JOINED consists of two shorts not joined.

### Character data
⏖
U+23D6 METRICAL TWO SHORTS JOINED

### Screenshot
![⏖](https://user-images.githubusercontent.com/1124347/37908668-dcea7aa4-30d6-11e8-86b5-37b432108404.png)

**Comment by nizarsq** [comment]
This issue fixed.
<img width="1097" alt="Screen Shot 2020-07-27 at 8 39 37 PM" src="https://user-images.githubusercontent.com/22158882/88616554-4cecd180-d049-11ea-8146-4d063a557da0.png">
