### ISSUE TITLE
Missing anchor points on Kaithi independent vowels

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1114]
### Font
NotoSansKaithi-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansKaithi-unhinted.zip
Date: 2018-03-25

### Font version
Version 1.05 uh

### Issue
Kaithi independent vowels lack anchor points. Compare, for example, a candrabindu on an independent au and on a dependent au.

### Character data
﻿𑂌𑂀𑂍𑂸𑂀
U+1108C KAITHI LETTER AU
U+11080 KAITHI SIGN CANDRABINDU
U+1108D KAITHI LETTER KA
U+110B8 KAITHI VOWEL SIGN AU
U+11080 KAITHI SIGN CANDRABINDU

### Screenshot
![﻿𑂌𑂀𑂍𑂸𑂀](https://user-images.githubusercontent.com/1124347/37981594-1d7051bc-31bc-11e8-800e-c04481849c71.png)

**Comment by marekjez86** [comment]
should be fixed in OTF: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansKaithi and TTF: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansKaithi
