### ISSUE TITLE
Inconsistent sans-serif heavy quotation mark glyphs

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1115]
### Font
NotoSansSymbols2-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansSymbols2-unhinted.zip
Date: 2018-03-24

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
The glyph of U+1F678 is inconsistent with the other sans-serif heavy quotation marks.

### Character data
🙶🙷🙸
U+1F676 SANS-SERIF HEAVY DOUBLE TURNED COMMA QUOTATION MARK ORNAMENT
U+1F677 SANS-SERIF HEAVY DOUBLE COMMA QUOTATION MARK ORNAMENT
U+1F678 SANS-SERIF HEAVY LOW DOUBLE COMMA QUOTATION MARK ORNAMENT

### Screenshot
![🙶🙷🙸](https://user-images.githubusercontent.com/1124347/38050720-f6b7eeb6-3299-11e8-8808-fb7fad862502.png)

**Comment by nizarsq** [comment]
This issue fixed.
<img width="1269" alt="Screen Shot 2020-07-26 at 3 33 23 PM" src="https://user-images.githubusercontent.com/22158882/88491103-5ac12a80-cf55-11ea-86a1-59f82c154fa3.png">
