### ISSUE TITLE
Poor positioning of marks with U+110BA KAITHI SIGN NUKTA

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1116]
### Font
NotoSansKaithi-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansKaithi-unhinted.zip
Date: 2018-03-25

### Font version
Version 1.05 uh

### Issue
U+110BA KAITHI SIGN NUKTA is ignored when positioning marks below, so they overlap the nukta. The exceptions are U+1109A KAITHI LETTER DDDHA and U+1109C KAITHI LETTER RHA, where the mark is attached to the nukta, which I find questionable.

### Character data
𑂔𑂺𑂳𑂚𑂳
U+11094 KAITHI LETTER JA
U+110BA KAITHI SIGN NUKTA
U+110B3 KAITHI VOWEL SIGN U
U+1109A KAITHI LETTER DDDHA
U+110B3 KAITHI VOWEL SIGN U

### Screenshot
![𑂔𑂺𑂳𑂚𑂳](https://user-images.githubusercontent.com/1124347/38093817-1763511e-333a-11e8-8652-d0d3b9d15232.png)

**Comment by marekjez86** [comment]
should be fixed in OTF: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansKaithi and TTF: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansKaithi
