### ISSUE TITLE
Inconsistency between 'guru' and 'gur2'

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1117]
### Font
NotoSansGurmukhi-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansGurmukhi-unhinted.zip
Date: 2018-03-29

### Font version
Version 1.03 uh

### Issue
Left-side vowel signs are reordered differently between the script tags 'guru' and 'gur2'. This is because the 'half' lookup is only defined for 'guru'.

### Character data
ਕ੍ਖਿ
U+0A15 GURMUKHI LETTER KA
U+0A4D GURMUKHI SIGN VIRAMA
U+0A16 GURMUKHI LETTER KHA
U+0A3F GURMUKHI VOWEL SIGN I

### Screenshot
`hb-view NotoSansGurmukhi-Regular.ttf -O png -u a15,a4d,a16,a3f --language x-hbscguru`
![ਕ੍ਖਿ](https://user-images.githubusercontent.com/1124347/38140066-328c8124-3400-11e8-98a5-a1cf6421340b.png)
`hb-view NotoSansGurmukhi-Regular.ttf -O png -u a15,a4d,a16,a3f --language x-hbscgur2`
![ਕ੍ਖਿ](https://user-images.githubusercontent.com/1124347/38140085-4840bdaa-3400-11e8-8295-bb2c26646a48.png)

**Comment by JelleBosmaMT** [comment]
It is not a font issue. The reported difference is a difference in rendering logic between the “guru” and “gur2” rendering.

**Comment by dscorbett** [comment]
It _is_ a font issue. It can’t be intentional for the font to behave differently for 'guru' and 'gur2'. It takes about a minute to fix it: just add 'gur2' to the existing 'half' lookup.

**Comment by JelleBosmaMT** [comment]
Gurmukhi does not have half forms.

 
Jelle Bosma
Typographic Development Consultant
Monotype Ltd.
Netherlands
Mobile +31 (64) 3509270
Our Brand Family
​
Monotype.com
Olapic.com
 
 
Monotype Ltd. Registered in England No. 2663485, Unit 2, Perrywood Business Park, Salfords, Redhill, Surrey, RH1 5DZ, UK.
 
This e-mail message and any accompanying documentation is intended for the addressee only and may contain legally privileged and confidential information. If you are not the addressee
 any use of this information is strictly prohibited. If you have received this e-mail in error please notify us immediately by reply e-mail or telephone call on +44 (0)1737 765959 and delete this
 e-mail from your systems.

﻿On 21-Feb-19, 16:27, "David Corbett" <notifications@github.com> wrote:

    It is a font issue. It can’t be intentional for the font to behave differently for 'guru' and 'gur2'. It takes about a minute to fix it: just add 'gur2' to the existing 'half' lookup.
    —
    You are receiving this because you commented.
    Reply to this email directly, 
    view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_googlei18n_noto-2Dfonts_issues_1117-23issuecomment-2D466041931&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=VnH-mkuVgDGcaqtfuNAH9a_L-zzaYSl7eNLCl16GOtM&m=e6XFJ-O3bsELe1HCw-2pIYz8w8e8tUlhP7i1Nxjnw_c&s=KdS5G_uUTQe04QeZFQeve92jsrq4O6nxUeM_JKLcY4Q&e=>, or 
    mute the thread <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AMI6sxBSyVcyY-2D9zYasFK5idn-5F6Re-5Fq8ks5vPrrfgaJpZM4TBuni&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=VnH-mkuVgDGcaqtfuNAH9a_L-zzaYSl7eNLCl16GOtM&m=e6XFJ-O3bsELe1HCw-2pIYz8w8e8tUlhP7i1Nxjnw_c&s=Y7MorHDriXRmKmzTSX3nkPkA_F6wZx7vLHdYC76B9hk&e=>.
    {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/googlei18n/noto-fonts","title":"googlei18n/noto-fonts","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/googlei18n/noto-fonts"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dscorbett in #1117: It _is_ a font issue. It can’t be intentional for the font to behave differently for 'guru' and 'gur2'. It takes about a minute to fix it: just add 'gur2' to the existing 'half' lookup."}],"action":{"name":"View Issue","url":"https://github.com/googlei18n/noto-fonts/issues/1117#issuecomment-466041931"}}}[
    {
    "@context": "http://schema.org",
    "@type": "EmailMessage",
    "potentialAction": {
    "@type": "ViewAction",
    "target": "https://github.com/googlei18n/noto-fonts/issues/1117#issuecomment-466041931",
    "url": "https://github.com/googlei18n/noto-fonts/issues/1117#issuecomment-466041931",
    "name": "View Issue"
    },
    "description": "View this Issue on GitHub",
    "publisher": {
    "@type": "Organization",
    "name": "GitHub",
    "url": "https://github.com"
    }
    }
    ]

**Comment by dscorbett** [comment]
Despite its name, 'half' isn’t specifically for half forms: it is for consonant–halant sequences to the left of which pre-base vowels should be reordered. The [OpenType Gurmukhi spec](https://docs.microsoft.com/en-us/typography/script-development/gurmukhi#introduction) explains that there are two options for rendering a syllable like ⟨ਕ੍ਗਿ⟩:

>Option 1: (default results) because the Ka is not listed in the half feature; the shaping engine treats the Ka as the first main consonant and re-orders the I-matra immediately in front of the previous base consonant.
>
>Option 2: While the Ka does not have a true half form in Gurmukhi, it can be listed in the 'half' feature lookup substituting the 'halant form' of Ka. Thus, the shaping engine will treat it as a half form and the I-matra will be positioned immediately in front of the "half-form" K(a).

Currently, users of this font on old Windows computers will get option 2, and other users of this font will get option 1. Normally, a font should as much as possible behave the same on all supported platforms, but here the font goes out of its way to be inconsistent with itself.

If you prefer option 1, delete the 'half' lookup. If you prefer option 2, add 'gur2' to the 'half' lookup. I have verified that both of these edits produce consistent results for both script tags.

**Comment by JelleBosmaMT** [comment]
If the goal was to have no difference between "guru" and "gur2" rendering, there would not have been a "gur2" rendering. 

The "guru" rendering was added to the original font in 2013, to support Windows XP generation shapers. It is set up within the assumptions and limitations of the initial attempt to support Indic shaping. I am not sure if the 2019 fonts will encounter the old rendering at all. But when they do, they are unlikely to be completely functional and render differently no matter what I do. The change to "gur2" intends to be an improvement. But even "gur2" renders different with Google, Apple, Adobe and Microsoft shapers for some of the characters. 

It was not possible to have option 1 rendering in the "guru" world, because the re-ordering took place before any feature was applied. 

I do not think Panjabi makes much use of the virama as a visible character. It isn't even mentioned in my language guide. It may show up in transliteration of Sanskrit or English. So this is a somewhat academic discussion.
