### ISSUE TITLE
Some characters are slighty bigger than others at small font sizes

### ISSUE THREAD

**Issue by ariasuni** [googlefonts/noto-fonts#1118]
## Font 
NotoMono-Regular.ttf

## Where the font came from, and when
Site: https://www.archlinux.org/packages/extra/any/noto-fonts/
Date: 2017-10-25

## Font Version
1.00

## Issue
Some characters, like the regular latin w, have an advance value inferior as the width of the bitmap rendered with small font size like 11 or 12 points (at least when computed and rendered using Freetype2 – see [Kitty source code]([kitty](https://github.com/kovidgoyal/kitty)), especially [freetype.c](https://github.com/kovidgoyal/kitty/blob/master/kitty/freetype.c#L277)).

You can see that in Kitty: v0.8.2 or earlier tries to render w but it’s bigger than other characters so Kitty make it smaller somehow; current version of Kitty crop the character so it’s slightly cropped. In other terminal applications like Konsole, I see that the w slightly overflows to the right.

## Screenshot
See [here](https://github.com/kovidgoyal/kitty/issues/417).

**Comment by nizarsq** [comment]
According to the [issue](https://github.com/kovidgoyal/kitty/issues/417) referred to in this issue, the behavior not reproducible. Closing this bug for now, please reopen if you have other thoughts.
