### ISSUE TITLE
Wrong glyph for U+FB20 HEBREW LETTER ALTERNATIVE AYIN

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1120]
### Font
NotoSansHebrew-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansHebrew-unhinted.zip
Date: 2018-03-04

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+FB20 HEBREW LETTER ALTERNATIVE AYIN has a descender in Noto Sans, but its code chart note says “this form of AYIN has no descender, for use with marks placed below the letter”. The glyph for the normal ayin has no descender in this font, so either their glyphs should be swapped or they should both use the same descenderless form.

### Character data
ﬠ
U+FB20 HEBREW LETTER ALTERNATIVE AYIN

### Screenshot
![ﬠ](https://user-images.githubusercontent.com/1124347/38173523-8fd7e2ae-358d-11e8-8e01-f72b4a728147.png)

**Comment by nizarsq** [comment]
This issue fixed.
<img width="827" alt="Screen Shot 2020-08-04 at 3 29 33 PM" src="https://user-images.githubusercontent.com/22158882/89351653-4cff5980-d667-11ea-923a-b73db873adae.png">
