### ISSUE TITLE
Noto Sans Arabic: U+0695 placement of "vbelow" 

### ISSUE THREAD

**Issue by Gue3bara** [googlefonts/noto-fonts#1122]
![](https://user-images.githubusercontent.com/12478169/38202914-bb3fb8fc-369d-11e8-886a-83cde12a55ad.jpg)

**Comment by nizarsq** [comment]
Issue reported reproducible on NotoSansArabic hinted. Unhited font looks ok.
<img width="1116" alt="Screen Shot 2020-05-30 at 10 25 48 PM" src="https://user-images.githubusercontent.com/22158882/83345173-f3745a80-a2c4-11ea-8d23-18cfd757d04b.png">

**Comment by nizarsq** [comment]
Issue fixed in NotoSansArabic.
