### ISSUE TITLE
Speakers have extra sound waves

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1124]
### Font
NotoSansSymbols2-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansSymbols2-unhinted.zip
Date: 2018-04-03

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+1F509 and U+1F569 are icons of speakers with one sound wave. Noto Sans Symbols2 gives each icon two sound waves.

### Character data
🔉🕩
U+1F509 SPEAKER WITH ONE SOUND WAVE
U+1F569 RIGHT SPEAKER WITH ONE SOUND WAVE

### Screenshot
![🔉🕩](https://user-images.githubusercontent.com/1124347/38275803-0f8e99c8-3761-11e8-9c65-0a97b8e5de40.png)

**Comment by marekjez86** [comment]
The Unicode names indicate "ONE SOUND WAVE" [U+1F509 SPEAKER WITH ONE SOUND WAVE, U+1F569 RIGHT SPEAKER WITH ONE SOUND WAVE]; Noto symbols have two

**Comment by nizarsq** [comment]
This issue fixed.
<img width="1197" alt="Screen Shot 2020-07-26 at 3 31 31 PM" src="https://user-images.githubusercontent.com/22158882/88491081-16358f00-cf55-11ea-9363-0185704884de.png">
