### ISSUE TITLE
Shape of GURMUKHI LETTER LLA (Gurmukhi) need to correct.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#113]
```
What steps will reproduce the problem?
1. http://utrrs-testing.rhcloud.com/language/pa/codepoint
2.  OR Check http://www.unicode.org/charts/PDF/U0A00.pdf Unicode Chart for 
Gurmukhi
3. ceck Image of Unicode Character A033 (ਲ਼)
4. Check Position of  GURMUKHI SIGN NUKTA (਼) with 0A32 (ਲ) GURMUKHI LETTER 
LA

What is the expected output? What do you see instead?
Current:
GURMUKHI SIGN NUKTA is on Left Side

Expected:
Should be on Right Side as per Unicode Image.

What version of the product are you using? On what operating system?
commit : e517fb85f7ee6beaa7204063cbe30709c4649617

Image Attached for Reference (compared with Unicode Chart (Gurmukhi))

```

Original issue reported on code.google.com by `amanpree...@gmail.com` on 4 Aug 2014 at 12:19

Attachments:
- [Gurmukhi_Fonts_LAA_0A33_Character_Big.png](https://storage.googleapis.com/google-code-attachments/noto/issue-113/comment-0/Gurmukhi_Fonts_LAA_0A33_Character_Big.png)

**Comment by behdad** [comment]
cc @waksmonskiMT @roozbehp @JelleBosmaMT

**Comment by marekjez86** [comment]
There's controversy about what's the right solution. We need to decide (after consulting the experts).

**Comment by Sarabveer** [comment]
It does not matter which side the `NUKTA`is. It is better if it is on the Left as that is how it is traditionally done.
