### ISSUE TITLE
Inconsistent kerning in Armenian

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1133]
### Font
NotoSansArmenian-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArmenian-unhinted.zip
Date: 2018-04-07

### Font version
Version 2.040;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+056C and U+0578 are kerned differently depending on whether U+0582 follows. This is because uni0578 and uni0582 ligate to uni0578_uni0582, which looks the same as those two glyphs unligated, but with different kerning behavior.

### Character data
լու
U+056C ARMENIAN SMALL LETTER LIWN
U+0578 ARMENIAN SMALL LETTER VO
U+0582 ARMENIAN SMALL LETTER YIWN

### Screenshot
![լու լո](https://user-images.githubusercontent.com/1124347/38458157-e3a4ad92-3a68-11e8-8292-e904a82814f2.png)

**Comment by marekjez86** [comment]
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansArmenian
