### ISSUE TITLE
In Noto Sans Mono, the top bar of lowercase l is too wide

### ISSUE THREAD

**Issue by ariasuni** [googlefonts/noto-fonts#1136]
### Font

NotoSansMono-Regular.ttf

### Where the font came from, and when

Arch Linux distribution
Date: 2018-04-05

### Font Version

131072

### OS name and version

Arch Linux (current)

### Issue

The lowercase `l` glyph in Noto Sans Mono has a top bar that is too wide; this makes the character stands out from the rest of the text. This character was great in Noto Mono in my opinion.

**Comment by nizarsq** [comment]
This issue still reproducible in the current font version https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSansMono
<img width="603" alt="Screen Shot 2020-07-08 at 8 44 10 AM" src="https://user-images.githubusercontent.com/22158882/86940066-3234d600-c0f7-11ea-818e-c6b5daeb368f.png">

**Comment by marekjez86** [comment]
Design decision. Will not be changed.
