### ISSUE TITLE
Missing diaeresis in Armenian

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1140]
### Font
NotoSansArmenian-Regular.ttf
NotoSerifArmenian-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArmenian-unhinted.zip
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifArmenian-unhinted.zip
Date: 2018-04-10

### Font version
Version 2.040;GOOG;noto-source:20170915:90ef993387c0

### Issue
According to [L2/17-315](https://www.unicode.org/L2/L2017/17315-armenian-diaeresis.pdf), U+0308 COMBINING DIAERESIS is used in Armenian dialects, but Noto does not support it.

### Character data
Ա̈ա̈օ̈ո̈
U+0531 ARMENIAN CAPITAL LETTER AYB
U+0308 COMBINING DIAERESIS
U+0561 ARMENIAN SMALL LETTER AYB
U+0308 COMBINING DIAERESIS
U+0585 ARMENIAN SMALL LETTER OH
U+0308 COMBINING DIAERESIS
U+0578 ARMENIAN SMALL LETTER VO
U+0308 COMBINING DIAERESIS

**Comment by marekjez86** [comment]
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansArmenian
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSerifArmenian
