### ISSUE TITLE
Excessive kerning in Armenian for Ս՞Ե՜

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1144]
### Font
NotoSansArmenian-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArmenian-unhinted.zip
Date: 2018-04-10

### Font version
Version 2.040;GOOG;noto-source:20170915:90ef993387c0

### Issue
Some sequences of Armenian letters and punctuation are kerned too closely, so that they overlap.

### Character data
Ս՞Ե՜
U+054D ARMENIAN CAPITAL LETTER SEH
U+055E ARMENIAN QUESTION MARK
U+0535 ARMENIAN CAPITAL LETTER ECH
U+055C ARMENIAN EXCLAMATION MARK

### Screenshot
![Ս՞Ե՜](https://user-images.githubusercontent.com/1124347/38769246-76f09ef8-3fcd-11e8-9f32-e5f66642c62c.png)

**Comment by marekjez86** [comment]
fixed in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansArmenian
