### ISSUE TITLE
Sloppy glyph for U+2B4D DOWNWARDS TRIANGLE-HEADED ZIGZAG ARROW

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1146]
### Font
NotoSansSymbols2-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansSymbols2-unhinted.zip
Date: 2018-04-03

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+2B4D has little triangles at its corners.

### Character data
⭍
U+2B4D DOWNWARDS TRIANGLE-HEADED ZIGZAG ARROW

### Screenshot
![⭍](https://user-images.githubusercontent.com/1124347/38833659-2a8e56fe-4194-11e8-85a6-d571456450c6.png)

**Comment by punchcutter** [comment]
This is in the Glyphs source file. This Glyphs drawing feature (Open Corners) can't currently be handled by the fontmake pipeline (https://github.com/googlei18n/fontmake/issues/288) so it needs to be fixed in the source file.

**Comment by marekjez86** [comment]
@dscorbett , @punchcutter : for now I'll wait for fontmake pipeline correction

**Comment by dscorbett** [comment]
This is also a problem with U+1F503 CLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS.

![🔃](https://user-images.githubusercontent.com/1124347/41539383-ab7db3d6-72db-11e8-8da6-6c2dc0711ee9.png)

**Comment by nizarsq** [comment]
Issue fixed.
<img width="1013" alt="Screen Shot 2020-07-26 at 3 10 18 PM" src="https://user-images.githubusercontent.com/22158882/88490687-1f712c80-cf52-11ea-999d-05f1ecdfa439.png">
