### ISSUE TITLE
No kerning for J with crossed tail

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1157]
### Font 
NotoSans-Regular.ttf
NotoSerif-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-unhinted.zip
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerif-unhinted.zip
Date: 2018-04-15

### Font Version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+A7B2 and U+029D need kerning.

### Character data
(Ʝʝ
U+0028 LEFT PARENTHESIS
U+A7B2 LATIN CAPITAL LETTER J WITH CROSSED-TAIL
U+029D LATIN SMALL LETTER J WITH CROSSED-TAIL

### Screenshot
![(Ʝʝ](https://user-images.githubusercontent.com/1124347/39149046-e3dabb08-470b-11e8-8904-042fb2adbc3e.png)![(Ʝʝ](https://user-images.githubusercontent.com/1124347/39149064-f2afba20-470b-11e8-8933-ab6bc3cd7eb5.png)

**Comment by nizarsq** [comment]
This issue fixed 
<img width="554" alt="Screen Shot 2020-07-14 at 10 19 44 PM" src="https://user-images.githubusercontent.com/22158882/87506440-2037c380-c620-11ea-9393-22569c1d192d.png">
