### ISSUE TITLE
Multiple U+102E0 COPTIC EPACT THOUSANDS MARKs overlie each other

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1159]
### Font
NotoSansSymbols2-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansSymbols2-unhinted.zip
Date: 2018-04-03

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
According to [L2/11-062R](https://www.unicode.org/L2/L2011/11062r-coptic-epact.pdf#page=3), U+102E0 COPTIC EPACT THOUSANDS MARK may be written multiple times on the same base number. Noto Sans Symbols2 overlays them so there appears to only be one U+102E0.

### Character data
𐋡𐋠𐋠
U+102E1 COPTIC EPACT DIGIT ONE
U+102E0 COPTIC EPACT THOUSANDS MARK
U+102E0 COPTIC EPACT THOUSANDS MARK

### Screenshot
![𐋡𐋠𐋠](https://user-images.githubusercontent.com/1124347/39273818-f66b9f32-48ad-11e8-8a12-5729c0c49f34.png)

**Comment by nizarsq** [comment]
This issue fixed
<img width="1111" alt="Screen Shot 2020-07-26 at 3 03 33 PM" src="https://user-images.githubusercontent.com/22158882/88490542-2fd4d780-cf51-11ea-947e-7d2cfe5953fd.png">
