### ISSUE TITLE
U+FE26 COMBINING CONJOINING MACRON is too short above U+2C98

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1163]
### Font
NotoSansCoptic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCoptic-unhinted.zip
Date: 2018-04-28

### Font version
Version 1.03 uh

### Issue
Above U+2C98, U+FE26 is too short to touch the adjacent macron fragment.

### Character data
Ⲙ︦Ⲙ︦
U+2C98 COPTIC CAPITAL LETTER MI
U+FE26 COMBINING CONJOINING MACRON
U+2C98 COPTIC CAPITAL LETTER MI
U+FE26 COMBINING CONJOINING MACRON

### Screenshot
![Ⲙ︦Ⲙ︦](https://user-images.githubusercontent.com/1124347/39399299-6b1043f0-4ae9-11e8-9a40-03eeaac47af4.png)

**Comment by speters33w** [comment]
Is anyone actively working on NotoSansCoptic? 
I'd like to try my hand at cleaning up the anchors, tables, lookups, changing combining glyphs and anchors to conform with tables in NotoSansRegular, adding combining glyphs from Noto that are commonly used in Coptic text processing, etc.
If that's something anyone is interested in me doing, reply to this comment.
