### ISSUE TITLE
NotoSansArabicUI connects some letters that should stay disconnected

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#1164]
The design of 'ARABIC LETTER WAW' (U+0648) appears to be such that in the NotoSansArabicUI fonts it gets connected to some letters where it should be disconnected [for example letter waw (U+0648) get connect with letter ain (U+0639)]

waw (U+0648) + ain (U+0639) on my Mac using NotoSansArabicUI:
![arabicui-waw-ain](https://user-images.githubusercontent.com/13322623/39407267-3bf9efdc-4b78-11e8-964e-39d7dc68128c.jpg)

waw (U+0648) + ain (U+0639) on my Mac using NotoSansArabic:
![arabic-waw-ain](https://user-images.githubusercontent.com/13322623/39407270-425c48f2-4b78-11e8-85fb-7c05b8f22c4a.jpeg)

waw (U+0648) + ain (U+0639) on my Mac using default font:
![macdefault-waw-ain](https://user-images.githubusercontent.com/13322623/39407260-0cf38176-4b78-11e8-842c-8dc8d16c1192.jpeg)

more examples
![screen shot 2017-02-23 at 9 51 37 am](https://user-images.githubusercontent.com/13322623/39407279-6755239a-4b78-11e8-9b24-63eefc5293a1.png)

**Comment by marekjez86** [comment]
@nizarsq : any other characters that you are aware that should stay disconnected in UI

**Comment by nizarsq** [comment]
@marekjez86 as far as I remember this is the only combination I found. Thank you

**Comment by marekjez86** [comment]
وقوع جوع
I realized that this is duplicate of https://github.com/googlei18n/noto-fonts/issues/851

**Comment by nizarsq** [comment]
This issue still reproducible, tested on hinted and unhinted. 
<img width="1055" alt="Screen Shot 2020-05-29 at 10 58 41 PM" src="https://user-images.githubusercontent.com/22158882/83320850-0709bd80-a200-11ea-8f04-061a57c6a30f.png">

**Comment by nizarsq** [comment]
This affects other codepoints as well. Here other combinations: جؤع بوغ 

<img width="1303" alt="Screen Shot 2020-11-05 at 8 13 51 PM" src="https://user-images.githubusercontent.com/22158882/98325337-6df78380-1fa3-11eb-9ada-c0c65348c794.png">

**Comment by nizarsq** [comment]
This issue requires design decision.

**Comment by marekjez86** [comment]
@khaledhosny : any advice on this? Should this be fixed?

**Comment by khaledhosny** [comment]
It looks a little unusual for a font, but it is perfectly normal in handwriting/calligraphy. A little bit of positive kerning might be enough to remedy it.

**Comment by nizarsq** [comment]
Issue fixed.
