### ISSUE TITLE
Missing dots on yeh barree with digit above

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1167]
### Font
NotoNaskhArabic-Regular.ttf
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoNaskhArabic-unhinted.zip
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-02-04

### Font version
Noto Naskh Arabic: Version 1.07 uh
Noto Sans Arabic: Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+077A and U+077B should have two dots below in the initial and medial positions, like U+06CC ARABIC LETTER FARSI YEH.

### Character data
ݺݻـ
U+077A ARABIC LETTER YEH BARREE WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE
U+077B ARABIC LETTER YEH BARREE WITH EXTENDED ARABIC-INDIC DIGIT THREE ABOVE
U+0640 ARABIC TATWEEL

### Screenshot
![ݺݻـ](https://user-images.githubusercontent.com/1124347/39485398-9d41f1fc-4d46-11e8-8267-cf57b400d4f6.png)![ݺݻـ](https://user-images.githubusercontent.com/1124347/39485399-9d5720a4-4d46-11e8-824c-416995c998fc.png)

**Comment by marekjez86** [comment]
@nizarsq : could you comment on this from Arabic point of view (if relevant)?
@behdad : could you comment on this from Farsi point of view (if relevant)?

**Comment by behdad** [comment]
Persian is NOT relevant. I don't know what the desired form is.

**Comment by behdad** [comment]
@roozbehp most probably knows.

**Comment by behdad** [comment]
@dscorbett what's your reference for this?  In general when YEH takes modifiers, the dots disappear. Do you have references to the contrary?

**Comment by dscorbett** [comment]
See [L2/06-149 pp. 8, 9](https://www.unicode.org/L2/L2006/06149-bashir-prop.pdf#page=8) and [_The Unicode Standard_, Table 9-8](https://www.unicode.org/versions/Unicode11.0.0/ch09.pdf#page=23). Unlike in Urdu, where the dotted initial and medial forms for /e/ are represented by U+06CC ARABIC LETTER FARSI YEH instead of U+06D2 ARABIC LETTER YEH BARREE because U+06D2 has Joining_Type=Right_Joining, these Burushaski variants have Joining_Type=Dual_Joining, so their dotted initial and medial forms use the same characters as their baṛī-style final and isolated forms.

**Comment by nizarsq** [comment]
This issue fixed for NotoSansArabic still reproducible for NotoNaskhArabic.

<img width="1356" alt="Screen Shot 2020-05-29 at 10 33 24 PM" src="https://user-images.githubusercontent.com/22158882/83320467-ab8a0080-a1fc-11ea-8809-e7a5be2c5540.png">

**Comment by nizarsq** [comment]
Issue fixed in both NotoSansArabic fonts and NotoNaskhArabic fonts.
