### ISSUE TITLE
Misplaced cedilla beneath Cyrillic psi

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1168]
### Font
NotoSerif-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerif-unhinted.zip
Date: 2018-04-15

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+0327 COMBINING CEDILLA is not centered below U+0471 CYRILLIC SMALL LETTER PSI. [This combination is used in typicon notation.](http://www.ponomar.net/files/okomarks.pdf#page=6)

### Character data
ѱ̧
U+0471 CYRILLIC SMALL LETTER PSI
U+0327 COMBINING CEDILLA

### Screenshot
![ѱ̧](https://user-images.githubusercontent.com/1124347/39536512-cca915ec-4e04-11e8-8ae0-8bec92fb7a89.png)

**Comment by nizarsq** [comment]
CEDILLA seems to be centered in the current NotoSerif 
<img width="592" alt="Screen Shot 2020-07-12 at 9 23 31 PM" src="https://user-images.githubusercontent.com/22158882/87270754-f054b880-c485-11ea-839f-62e8c24d27eb.png">
