### ISSUE TITLE
Wrong glyphs for U+1F5F5 and U+1F5F7 BALLOT BOX WITH (BOLD) SCRIPT X

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1176]
### Font
NotoSansSymbols2-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansSymbols2-unhinted.zip
Date: 2018-04-03

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
In this font, the ballot boxes with script Xs (U+1F5F5 and U+1F5F7) are based on the default ballot Xs (U+2717 and U+2718). They should be based on the ballot script Xs (U+1F5F4 and U+1F5F6). See [L2/11-344](https://www.unicode.org/L2/L2011/11344-wingdings.pdf) pages 31 and 34 for the disunification rationale.

### Character data
🗴✗🗵🗶✘🗷
U+1F5F4 BALLOT SCRIPT X
U+2717 BALLOT X
U+1F5F5 BALLOT BOX WITH SCRIPT X
U+1F5F6 BALLOT BOLD SCRIPT X
U+2718 HEAVY BALLOT X
U+1F5F7 BALLOT BOX WITH BOLD SCRIPT X

### Screenshot
![🗴✗🗵🗶✘🗷](https://user-images.githubusercontent.com/1124347/39884553-3aa9bebc-5458-11e8-9256-7b2d9b8a409f.png)

**Comment by nizarsq** [comment]
This issue fixed.
<img width="990" alt="Screen Shot 2020-07-25 at 9 27 04 PM" src="https://user-images.githubusercontent.com/22158882/88471375-97d9de00-cebd-11ea-848c-45b0ed86ac8a.png">
