### ISSUE TITLE
Spacing tashkil are not spacing in Noto Kufi Arabic

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1178]
### Font
NotoKufiArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoKufiArabic-unhinted.zip
Date: 2018-02-04

### Font version
Noto Kufi Arabic: Version 1.04 uh

### Issue
Some spacing compatibility tashkil have been given zero-width glyphs.

### Character data
اﱞا اﱟا اﱠا اﱡا اﱢا اﱣا اﹰا اﹲا اﹴا اﹶا اﹸا اﹺا اﹼا اﹾا
U+FC5E ARABIC LIGATURE SHADDA WITH DAMMATAN ISOLATED FORM
U+FC5F ARABIC LIGATURE SHADDA WITH KASRATAN ISOLATED FORM
U+FC60 ARABIC LIGATURE SHADDA WITH FATHA ISOLATED FORM
U+FC61 ARABIC LIGATURE SHADDA WITH DAMMA ISOLATED FORM
U+FC62 ARABIC LIGATURE SHADDA WITH KASRA ISOLATED FORM
U+FC63 ARABIC LIGATURE SHADDA WITH SUPERSCRIPT ALEF ISOLATED FORM
U+FE70 ARABIC FATHATAN ISOLATED FORM
U+FE72 ARABIC DAMMATAN ISOLATED FORM
U+FE74 ARABIC KASRATAN ISOLATED FORM
U+FE76 ARABIC FATHA ISOLATED FORM
U+FE78 ARABIC DAMMA ISOLATED FORM
U+FE7A ARABIC KASRA ISOLATED FORM
U+FE7C ARABIC SHADDA ISOLATED FORM
U+FE7E ARABIC SUKUN ISOLATED FORM

### Screenshot
Each character appears between two alefs to demonstrate the problem.
![اﱞا اﱟا اﱠا اﱡا اﱢا اﱣا اﹰا اﹲا اﹴا اﹶا اﹸا اﹺا اﹼا اﹾا](https://user-images.githubusercontent.com/1124347/39962458-2264182c-561d-11e8-8cf2-6756c0f98136.png)

**Comment by nizarsq** [comment]
This issue fixed. I can see there is width added. Please reopen if you have other thoughts
<img width="948" alt="Screen Shot 2020-06-02 at 11 42 51 AM" src="https://user-images.githubusercontent.com/22158882/83557505-a65fd680-a4c6-11ea-8568-e8ec68f24702.png">

**Comment by dscorbett** [comment]
This bug has not been fixed. Your test is unreliable because it uses HTML, which uses a font stack, so you can’t be sure that glyphs that look correct are coming from the font you mean to test. In this case, the first five glyphs have been removed from Noto Kufi Arabic; the next font in the stack happens to display them correctly. The remaining nine glyphs are still non-spacing, which means this issue has not been addressed and needs to be reopened.

**Comment by nizarsq** [comment]
I use blank font as a fallback font to avoid showing glyphs from other fonts. For some reason I didn't check the option to include the fallback font in this test. Regarding being fixed or not, you are right it is not fixed.
<img width="1402" alt="Screen Shot 2020-06-03 at 2 45 45 AM" src="https://user-images.githubusercontent.com/22158882/83622175-7a833600-a544-11ea-9eee-e4d5d5f3d81a.png">

**Comment by nizarsq** [comment]
@marekjez86 The following marks not enabled in NotoKufiArabic, look like the changes happen in 2019-10-24. Any idea why they currently disabled?

Test data: اﱞا اﱟا اﱠا اﱡا اﱢا
U+FC5E ARABIC LIGATURE SHADDA WITH DAMMATAN ISOLATED FORM
U+FC5F ARABIC LIGATURE SHADDA WITH KASRATAN ISOLATED FORM
U+FC60 ARABIC LIGATURE SHADDA WITH FATHA ISOLATED FORM
U+FC61 ARABIC LIGATURE SHADDA WITH DAMMA ISOLATED FORM
U+FC62 ARABIC LIGATURE SHADDA WITH KASRA ISOLATED FORM

<img width="1391" alt="Screen Shot 2020-12-28 at 2 07 42 PM" src="https://user-images.githubusercontent.com/22158882/103245759-0fe97b80-4916-11eb-85e0-28679a123ae4.png">

**Comment by nizarsq** [comment]
Fix will be in NotoKufiArabic Version 2.104

<img width="1238" alt="Screen Shot 2021-02-08 at 7 59 42 PM" src="https://user-images.githubusercontent.com/22158882/107313868-4b648300-6a48-11eb-969a-657716319a77.png">
