### ISSUE TITLE
Wrong glyph for U+FB51 ARABIC LETTER ALEF WASLA FINAL FORM

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1179]
### Font
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-02-04

### Font version
Noto Sans Arabic: Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+FB51 ARABIC LETTER ALEF WASLA FINAL FORM has an isolated glyph instead of a final glyph.

### Character data
ﭑ
U+FB51 ARABIC LETTER ALEF WASLA FINAL FORM

### Screenshot
![ﭑ](https://user-images.githubusercontent.com/1124347/39967230-bbbd6e20-5685-11e8-8bb2-b407a43fe817.png)

**Comment by nizarsq** [comment]
This issue fixed
<img width="1337" alt="Screen Shot 2020-05-28 at 1 04 16 AM" src="https://user-images.githubusercontent.com/22158882/83115481-43fa7680-a07f-11ea-949f-06f915d6d31c.png">
