### ISSUE TITLE
Wrong glyph for U+FE72 ARABIC DAMMATAN ISOLATED FORM

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1180]
### Font
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-02-04

### Font version
Noto Sans Arabic: Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+FE72 ARABIC DAMMATAN ISOLATED FORM looks like a damma.

### Character data
ﹲﹸ
U+FE72 ARABIC DAMMATAN ISOLATED FORM
U+FE78 ARABIC DAMMA ISOLATED FORM

### Screenshot
![ﹲﹸ](https://user-images.githubusercontent.com/1124347/40001113-776b48b0-575b-11e8-977a-fcc6dc7fb5aa.png)

**Comment by nizarsq** [comment]
This issue fixed.
<img width="1280" alt="Screen Shot 2020-05-27 at 2 13 03 AM" src="https://user-images.githubusercontent.com/22158882/83000780-b3109600-9fbf-11ea-824f-7054cb1cc4e1.png">

**Comment by nizarsq** [comment]
Reopening this issue as the fix revised. Fix needed in 2.02
