### ISSUE TITLE
U+08AD ARABIC LETTER LOW ALEF is too high

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1182]
### Font
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-02-04

### Font version
Noto Sans Arabic: Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
The glyphs of U+08AD ARABIC LETTER LOW ALEF in [L2/11-209](https://www.unicode.org/L2/L2011/11209-n4072-arabic.pdf) consistently have their highest points at the baseline. The glyph in Noto Sans Arabic has its lowest point at the baseline.

### Character data
ࢭیو
U+08AD ARABIC LETTER LOW ALEF
U+06CC ARABIC LETTER FARSI YEH
U+0648 ARABIC LETTER WAW

### Screenshot
![ࢭیو](https://user-images.githubusercontent.com/1124347/40068700-3f5b76c0-5837-11e8-841d-7243085702da.png)

**Comment by nizarsq** [comment]
This issue fixed.
<img width="1058" alt="Screen Shot 2020-05-28 at 12 57 22 AM" src="https://user-images.githubusercontent.com/22158882/83114797-4dcfaa00-a07e-11ea-8b56-bd05da4fe3a4.png">

**Comment by dscorbett** [comment]
This bug is back in [version 2.005](https://github.com/googlefonts/noto-fonts/blob/668e1995725bbc827ca71f6a4aeb791b6cb85cfc/unhinted/otf/NotoSansArabic/NotoSansArabic-Regular.otf).

**Comment by dscorbett** [comment]
@nizarsq, please reopen this.

**Comment by nizarsq** [comment]
Will fix this issue if fixes gone with the revised version
