### ISSUE TITLE
Wrong glyph for U+205F MEDIUM MATHEMATICAL SPACE

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1184]
### Font
NotoSerif-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerif-unhinted.zip
Date: 2018-04-15

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
Noto Serif’s glyph for U+205F MEDIUM MATHEMATICAL SPACE is not a space.

### Character data
&#x205F;
U+205F MEDIUM MATHEMATICAL SPACE

### Screenshot
![&#x205F;](https://user-images.githubusercontent.com/1124347/40212398-aae11b60-5a1d-11e8-91db-d8dacb6cf7f9.png)

**Comment by nizarsq** [comment]
This issue fixed.
<img width="552" alt="Screen Shot 2020-07-10 at 5 31 07 PM" src="https://user-images.githubusercontent.com/22158882/87212399-24d44300-c2d3-11ea-9576-f87e6b88dfdb.png">
