### ISSUE TITLE
Baybayin 'Ra' is not included on NotoSans Tagalog U+170D ( NotoSansTagalog-Regular.ttf ) https://www.google.com/get/noto/#sans-tglg

### ISSUE THREAD

**Issue by matt201005** [googlefonts/noto-fonts#1185]
## Defect Report
The Baybayin Character 'Ra' isn't supported on the Noto fonts, although 'Ra' could be written with 'Da' (ᜇ) because da and ra has the same character to write with in classical baybayin, rendering the Ra character would help the generation today, wanting to type Ra in baybayin using noto. Ra looks like a ᜇ but with a line on its last stroke? ithink.

### Font 
  NotoSansTagalog-Regular.ttf

### Where the font came from
  >   Site: https://www.google.com/get/noto/#sans-tglg

### Issue
Ra character in Baybayin isn't supported by Noto Fonts.

### Character data
 
ᜍ

Block | Tagalog
-- | --
Unicode | U+170D
UTF-8 | 0xE1 0x9C 0x8D
JavaScript | 0x170D

### Screenshot
  
![rendering ra](https://user-images.githubusercontent.com/39404991/40231328-58c4a88c-5acd-11e8-8fb8-bcad6d4b7251.png)

### Fontview
  ᜀ ᜊ ᜃ ᜇ ᜁ ᜄ ᜑ ᜎ ᜋ ᜈ ᜅ ᜂ ᜉ ᜍ ᜐ ᜆ ᜏ ᜌ
>>>>>>ᜍ<<<<<<

### Fontdiff
  * Fontdiff displays the text using two versions of the font side by side.

**Comment by matt201005** [comment]
Noto Bad, Noto Good. Just okay.

I just saw that the Google code project "Noto" font for world's scripts has been made available - Tagalog/Baybayin, Buhid, Tagbanwa, and Hanunoo are included in the Noto Sans font lineup: http://www.google.com/get/noto/

As they are right now, when I tested the font (Noto Sans), the Philippine scripts are still mostly useless;  a big chunk of the Surat Mangyan scripts are not mapped (incorrect character shapes plus Unicode still does not have the range for the various proper kudlit markers) and the updated RA are not included. The kudlits and virama still doesn't stack or render correctly, the baybayin characters are a mix of styles and not uniform, the whole collection does not really visually "harmonize" well. And unless you specifically chose Noto Sans as your default browser or mobile font, it still won't show or show properly (in other non Google/Chrome browsers). Also, you still need a custom keyboard layout to type Baybayin.

The project team are still ironing out some issues with the other language's scripts. I'll wait and see how they resolve those issues as well. It's still a little early to tell if the Noto project will be helpful to Baybayin scripts or not. Kulitan is still not included in Unicode. And Noto got most of its language data & sample texts are from the Unicode CLDR project.

The best thing to come out of it is that Chromebook laptops and Google tablets will have baybayin Noto fonts bundled with it. I guess it's a big step for Google fonts, but it's still barely a crawl for Baybayin fonts. We'll take what we can. Baby steps till we get there. :)

Moving on...

**Comment by ctrlcctrlv** [comment]
Is someone going to fix this?

**Comment by marekjez86** [comment]
Noto's goal is to support all the characters that are part of Unicode standard. If one looks at https://en.wikipedia.org/wiki/Tagalog_(Unicode_block) or https://www.unicode.org/charts/PDF/U1700.pdf U+170D is not listed there. Therefore the first step would be to convince Unicode to add U+170D to its list.

**Comment by ctrlcctrlv** [comment]
That is unfortunate but I understand your position. The fact that use of U+170D is a _de facto_ standard supported by many fonts is unlikely to sway you. They left the codepoint open for a reason, and people have been wondering why it's still open [since at least 2010](http://nordenx.blogspot.com/2010/02/to-do-list-tagalog-unicode-and-welding.html). Many fonts do put RA at U+170D.

However, if you defer to the standard over _de facto_ usage, what can I do?

**Comment by NorbertLindenberg** [comment]
The proposal that led to the encoding of Baybayin
https://www.unicode.org/L2/L1999/n1933.pdf
shows that four Philippine scripts were encoded in parallel, of which two have a Ra and two don’t. There’s no further discussion of Ra, which usually means that the available sources didn’t have sufficient evidence to justify encoding the character in Tagalog and Tagbanwa. The gaps at 170D and 176D appear to exist simply to maintain the parallel with the other two Philippine scripts.

If there’s evidence that a Tagalog Ra is actually used as a distinct character in documents, someone familiar with the situation should write a proposal to add the character to Unicode:
https://www.unicode.org/pending/proposals.html
If you’d like to have an informal discussion before going through the trouble of writing a full proposal, the Unicode mailing list (unicode@unicode.org) is a good place:
http://www.unicode.org/consortium/distlist.html

**Comment by ctrlcctrlv** [comment]
@NorbertLindenberg I took your advice and wrote a proposal. https://github.com/ctrlcctrlv/OpenBaybayin/blob/master/tex/ra/merge.pdf

I haven't submitted it yet, someone on the Unicode mailing list graciously offered to review it for me before I submit it to help its chances. But the final proposal I submit will look like that, and I plan to submit it very soon.

Thanks for the help and I hope that we can reopen this issue very soon after Unicode (fingers crossed) accepts my contribution.

**Comment by ctrlcctrlv** [comment]
Just an update, my proposal was approved. I am not sure what version of Unicode it will be in, but this should be reopened as it will be finalized soon.

https://unicode.org/alloc/Pipeline.html (search for TAGALOG LETTER RA)

**Comment by jungshik** [comment]
U+170D and one more Tagalog character are slated for an unspecified future version in the  Unicode pipeline.

**Comment by ctrlcctrlv** [comment]
So this should be reopened, no? Or must we wait for it to be published? That could take years.

**Comment by tommai4881** [comment]
> U+170D and one more Tagalog character are slated for an unspecified future version in the Unicode pipeline.

Good news! This September the character, included in Unicode 14, will be released

**Comment by ChiefMikeK** [comment]
@marekjez86

Please re-open and rename(so it's easier to search) this issue as follows vice creating three new issues.  
> Additional Unicode14.0 | 170D, 1715, 171F.  

[https://www.unicode.org/charts/PDF/Unicode-14.0/U140-1700.pdf] (Unicode® 14.0) draft new added characters 
---
* 170D  TAGALOG LETTER RA
* 1715  TAGALOG SIGN PAMUDPOD
* 171F  TAGALOG LETTER ARCHAIC RA

**Comment by ChiefMikeK** [comment]
@matt201005 would you please rename this issue as follows;  
> Additional Unicode14.0 | 170D, 1715, 171F.  
 
![Unicode14 0-TAGALOG](https://user-images.githubusercontent.com/20070053/124763954-0e54dc00-df67-11eb-8c43-0ba3add0c7aa.png)
