### ISSUE TITLE
U+2106 CADA UNA is combining

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1186]
### Font
NotoSans-Regular.ttf
NotoSerif-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-unhinted.zip
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerif-unhinted.zip
Date: 2018-04-15

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+2106 CADA UNA is positioned like a combining character.

### Character data
Z℆
U+005A LATIN CAPITAL LETTER Z
U+2106 CADA UNA

### Screenshot
![Z℆](https://user-images.githubusercontent.com/1124347/40237416-65e289fc-5a7e-11e8-8142-ab7d722b37c6.png)
![Z℆](https://user-images.githubusercontent.com/1124347/40237417-65f46050-5a7e-11e8-92f7-a65cfd370242.png)

**Comment by dscorbett** [comment]
This bug is also present in Noto Sans Mono.

**Comment by nizarsq** [comment]
Issue reported fixed. However, NotoSansMono not rendering U+2106 CADA UNA correctly there is some kind of overlapping @marekjez86 any thoughts? see screenshot attached.
<img width="620" alt="Screen Shot 2020-07-10 at 5 24 13 PM" src="https://user-images.githubusercontent.com/22158882/87212198-2ea97680-c2d2-11ea-8b0a-d3808a324237.png">

**Comment by moyogo** [comment]
Confirmed as fixed.

See  #2062 for the overlap issue for Noto Sans Mono.
