### ISSUE TITLE
Incorrect Arabic shaping with 'dlig'

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1187]
### Font
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-02-04

### Font version
Noto Sans Arabic: Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
'dlig' induces incorrect shaping. Any ligature of something with a medial heh changes the heh to its final form. Any ligature of a beh (or other letter with the same rasm) with something changes the beh to its initial form. Any ligature of a medial letter and a final letter changes the former to its initial form.

### Character data
مىهيسم
U+0645 ARABIC LETTER MEEM
U+0649 ARABIC LETTER ALEF MAKSURA
U+0647 ARABIC LETTER HEH
U+064A ARABIC LETTER YEH
U+0633 ARABIC LETTER SEEN
U+0645 ARABIC LETTER MEEM

### Screenshot
Default:
![مىهيسم](https://user-images.githubusercontent.com/1124347/40271362-536272fa-5b6a-11e8-9cf7-9a45b7c1fe62.png)
With 'dlig':
![مىهيسم](https://user-images.githubusercontent.com/1124347/40271363-56897e56-5b6a-11e8-943f-136c3f6d879b.png)

**Comment by nizarsq** [comment]
This issue fixed. 
<img width="1319" alt="Screen Shot 2020-05-27 at 12 49 37 AM" src="https://user-images.githubusercontent.com/22158882/82992514-1dbbd480-9fb4-11ea-976c-316120ad14e7.png">

**Comment by dscorbett** [comment]
This bug is back in [version 2.005](https://github.com/googlefonts/noto-fonts/blob/668e1995725bbc827ca71f6a4aeb791b6cb85cfc/unhinted/otf/NotoSansArabic/NotoSansArabic-Regular.otf).

**Comment by nizarsq** [comment]
Thank you. 
I believe this issue fixed in NotoSansArabic 2.5 (revised version). @marekjez86 for reopen/prioritize
This apply to https://github.com/googlefonts/noto-fonts/issues/1195

**Comment by dscorbett** [comment]
The correct fix is to delete the 'dlig' lookup. All its rules are redundant or wrong.
