### ISSUE TITLE
Malay Jawi letter ڽ 'NYA' appeared as wrong glyph in Noto Sans Arabic (UI)

### ISSUE THREAD

**Issue by mnh48** [googlefonts/noto-fonts#1188]
### Title 
Malay Jawi letter ڽ 'NYA' appeared as wrong glyph in Noto Sans Arabic (UI)

### Font 
1. NotoSansArabic-Regular.ttf
2. NotoSansArabicUI-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-hinted.zip
Date: 2018-05-19 (GMT+8)

### Font Version
NotoSansArabic-Regular.ttf - `Version 2.000;GOOG;noto-source:20170915:90ef993387c0; ttfautohint (v1.7)`
NotoSansArabicUI-Regular.ttf - `Version 2.000;GOOG;noto-source:20170915:90ef993387c0; ttfautohint (v1.7)`

### OS name and version
Windows 8.1 Single Language

### Application name and version
No specific app, the issue is global.

### Issue
The [Jawi letter](https://en.wikipedia.org/wiki/Jawi_alphabet) NYA ([ڽ](https://en.wiktionary.org/wiki/%DA%BD)) which is used for the /ɲ/ sound in writing Jawi-scripted Malay language is appearing as wrong glyph in the initial form and medial form when I use both fonts.

In Noto Sans Arabic, the letter just uses the isolated form in place of initial and medial form.
In Noto Sans Arabic UI, the placement of the three dots are wrong, it should be below and not above.

For comparison, Noto Kufi Arabic and Noto Naskh Arabic UI displayed the letter correctly, and non-Noto font Times New Roman also displays correctly. (This is shown at Screenshot section below)

  1. Steps to reproduce: just type as usual
  2. Observed results: see screenshot, on first two rows
  3. Expected results: see screenshot, on last three rows
  4. Additional information: none

### Character data
The unicode codepoint for 'NYA' (ڽ‬) is 06BD.

### Screenshot
![image](https://user-images.githubusercontent.com/12217018/40272295-8846fdec-5bdd-11e8-8054-3095b704b6f5.png)

### Harfbuzz hb-view
Using the [windows executable](https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-1.7.6-win32.zip) of Harfbuzz with the following input and command gives the corresponding output.

Input: in.txt
https://gist.github.com/MuhdNurHidayat/8630c720b064b6f3bcb9bad9fc768819
![image](https://user-images.githubusercontent.com/12217018/40272581-1e407810-5be2-11e8-8b17-a34d81ad959a.png)

First command to test Noto Sans Arabic:
`hb-view.exe --font-file "C:\Users\User\Desktop\NotoSansArabic-Regular.ttf" --text-file "in.txt" --output-file "out1.png"`
Output:
![out1](https://user-images.githubusercontent.com/12217018/40272482-3df56334-5be0-11e8-8672-1cece4d86da5.png)

Second command to test Noto Sans Arabic UI:
`hb-view.exe --font-file "C:\Users\User\Desktop\NotoSansArabicUI-Regular.ttf" --text-file "in.txt" --output-file "out2.png"`
Output:
![out2](https://user-images.githubusercontent.com/12217018/40272483-45255e34-5be0-11e8-9917-6371beec38ae.png)

### Fontview
The [tool](https://github.com/googlei18n/fontview/releases/tag/v0.3.1) is only released for OS X, I'm not a developer and I don't have the time to build the tool from source just for reporting wrong glyph.

### Fontdiff
The [tool](https://github.com/googlei18n/fontdiff/releases/tag/v0.2.3) is only released for OS X and Linux, I'm not a developer and I don't have the time to build the tool from source just for reporting wrong glyph.

**Comment by AzizMostafa** [comment]
Dear Friends,
Ever seen dynamic Arabic/J
[BungaBahasa.pdf](https://github.com/googlei18n/noto-fonts/files/2431507/BungaBahasa.pdf)
awi fonts?
https://www.youtube.com/watch?v=itZ66gUVVCI
Making use of Telegram? https://telegram.org/
Please go explore my link https://t.me/FonJawi
All the Best for All

**Comment by nizarsq** [comment]
Both issues reproducible in NotoSansArabic-Regular
NotoSansArabicUI-Regular
<img width="341" alt="Screen Shot 2020-05-23 at 9 14 33 PM" src="https://user-images.githubusercontent.com/22158882/82745549-9d3e6f00-9d3a-11ea-87bd-74e345413dcf.png">
<img width="349" alt="Screen Shot 2020-05-23 at 9 14 43 PM" src="https://user-images.githubusercontent.com/22158882/82745550-9f083280-9d3a-11ea-8ac2-5014f3ecde4a.png">

**Comment by nizarsq** [comment]
U+06BD current status in NotoSansArabic 2.002 and NotoSansArabicUI 2.002:
NotoSansArabic
U+06BD Initial and medial glyphs are missing from NotoSansArabic bug filed for known missing glyphs https://github.com/googlefonts/noto-fonts/issues/1856

NotoSansArabicUI
U+06BD Initial and medial wrong glyph in NotoSansArabicUI (dots should be below in Initial and medial forms)

<img width="1052" alt="Screen Shot 2020-10-08 at 12 10 27 PM" src="https://user-images.githubusercontent.com/22158882/95502810-43dc8280-095f-11eb-9a46-62b7a6174890.png">

NotoSansArabic 2.002
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf
NotoSansArabicUI 2.002
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansArabicUI/NotoSansArabicUI-

**Comment by nizarsq** [comment]
> U+06BD current status in NotoSansArabic 2.002 and NotoSansArabicUI 2.002:
> NotoSansArabic
> U+06BD Initial and medial glyphs are missing from NotoSansArabic bug filed for known missing glyphs #1856
> 
> NotoSansArabicUI
> U+06BD Initial and medial wrong glyph in NotoSansArabicUI (dots should be below in Initial and medial forms)
> 
> <img alt="Screen Shot 2020-10-08 at 12 10 27 PM" width="1052" src="https://user-images.githubusercontent.com/22158882/95502810-43dc8280-095f-11eb-9a46-62b7a6174890.png">
> 
> NotoSansArabic 2.002
> https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf
> NotoSansArabicUI 2.002
> https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansArabicUI/NotoSansArabicUI-

For tracking purpose NotoKufiArabic need fix as well

**Comment by nizarsq** [comment]
I need to check this issue in Kufi. Reopening.
