### ISSUE TITLE
Misplaced anchor points in Noto Naskh Arabic

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1191]
### Font
NotoNaskhArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoNaskhArabic-unhinted.zip
Date: 2018-02-04

### Font version
Version 1.07 uh

### Issue
Some marks’ anchor points are misplaced. U+08E8 ARABIC CURLY DAMMATAN is too low. U+08F9 ARABIC LEFT ARROWHEAD BELOW is too high. Any mark attached to U+08FA ARABIC RIGHT ARROWHEAD BELOW is too high.

### Character data
اࣨاࣹاࣺٕ
U+0627 ARABIC LETTER ALEF
U+08E8 ARABIC CURLY DAMMATAN
U+0627 ARABIC LETTER ALEF
U+08F9 ARABIC LEFT ARROWHEAD BELOW
U+0627 ARABIC LETTER ALEF
U+08FA ARABIC RIGHT ARROWHEAD BELOW
U+0655 ARABIC HAMZA BELOW

### Screenshot
![اࣨاࣹاࣺٕ](https://user-images.githubusercontent.com/1124347/40310535-1f320d7a-5cdb-11e8-95de-92448b961b42.png)

**Comment by nizarsq** [comment]
I can see the issue with U+08E8 ARABIC CURLY DAMMATAN are sitting little low. For U+08F9 ARABIC LEFT ARROWHEAD BELOW  and U+08FA ARABIC RIGHT ARROWHEAD BELOW they are fixed

**Comment by nizarsq** [comment]
NotoNaskhArabicUI has issue with U+08E8 ARABIC CURLY DAMMATAN

**Comment by nizarsq** [comment]
U+08F9 ARABIC LEFT ARROWHEAD BELOW positioning issue fixed
U+08E8 ARABIC CURLY DAMMATAN positioning issue fixed
For U+08FA ARABIC RIGHT ARROWHEAD BELOW overlap U+0655 ARABIC HAMZA BELOW I never saw this combination in Arabic.
