### ISSUE TITLE
U+FBB7 and U+FBB9 are swapped

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1192]
### Font
NotoNaskhArabic-Regular.ttf
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoNaskhArabic-unhinted.zip
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-02-04

### Font version
Noto Naskh Arabic: Version 1.07 uh
Noto Sans Arabic: Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
The glyphs of U+FBB7 and U+FBB9 are swapped.

### Character data
﮷﮹
U+FBB7 ARABIC SYMBOL THREE DOTS BELOW
U+FBB9 ARABIC SYMBOL THREE DOTS POINTING DOWNWARDS BELOW

### Screenshot
![﮷﮹](https://user-images.githubusercontent.com/1124347/40372120-0cba4216-5db2-11e8-88a2-a049bb38174d.png)![﮷﮹](https://user-images.githubusercontent.com/1124347/40372119-0ca2aeda-5db2-11e8-828e-67467b12d004.png)

**Comment by nizarsq** [comment]
This issue fixed in NotoSansArabic but still reproducible in NotoNaskhArabic
<img width="1140" alt="Screen Shot 2020-05-22 at 1 24 31 PM" src="https://user-images.githubusercontent.com/22158882/82707254-90355900-9c30-11ea-9595-09533a46fc8f.png">

**Comment by nizarsq** [comment]
This issue reproducible on NotoSansArabicUI and need fix

**Comment by nizarsq** [comment]
Issue fixed
