### ISSUE TITLE
Noto Serif Kannada alpha issues

### ISSUE THREAD

**Issue by sridatta1** [googlefonts/noto-fonts#1193]
### Title 
  > Noto Serif Kannada alpha issues

### Font 
>  Noto Serif Kannada
>Here using NotoSerifKannada-Medium.otf applies to other weights as well

### Where the font came from, and when
>https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/otf/serif/NotoSerifKannada
  >   Date: 2018-05-23

### Font Version
2.00

### OS name and version
Windows 10 10.0.16299
### Application name and version
  > Google Chrome 66.0.3359.181 (Official Build) (64-bit)

### Issue
1. The subscripts of SSA in ಕ್ಷ and NYA in ಜ್ಞ should be centred.
observed v 2.000
![image](https://user-images.githubusercontent.com/23263723/40427119-6a1c3dac-5eba-11e8-9914-7bcd6375dd03.png)
correct results  v 1.01
![image](https://user-images.githubusercontent.com/23263723/40427216-b28d4630-5eba-11e8-91ba-6a0eae814147.png)

2. FA (PHA+NUKTA)+ Vowel signs is broken
observed v 2.000
![image](https://user-images.githubusercontent.com/23263723/40427342-08f2ca5e-5ebb-11e8-864e-f1d2e448fa14.png)
correct results  v 1.01
![image](https://user-images.githubusercontent.com/23263723/40427440-5d990a6e-5ebb-11e8-9fcf-b97c071620fd.png)
3. jho is incorrect. It should be as in the original version.
![image](https://user-images.githubusercontent.com/23263723/40427571-bbbfdd52-5ebb-11e8-8a36-ec2213a0a1f7.png)
see #819
4.  ಟೆ ಟೇ ಟೈ ಟೊ ಟೋ ಟೌಟಾ
see comments of @JelleBosmaMT here- https://github.com/googlei18n/noto-fonts/issues/905#issuecomment-355229965
5. U+0C80 KANNADA SIGN SPACING CANDRABINDU needs to touch the base and should be larger. see https://www.unicode.org/L2/L2014/14153-kannada-chandrabindu.pdf
https://www.unicode.org/L2/L2015/15158-kannada-vedic-anusvara.pdf
![image](https://user-images.githubusercontent.com/23263723/40428546-267d39a8-5ebe-11e8-80f2-680cf95c223d.png)
6. Positioning of 
U+0951 DEVANAGARI STRESS SIGN UDATTA : Vedic tone svarita
U+0952 DEVANAGARI STRESS SIGN ANUDATTA : Vedic tone anudatta
U+1CDA VEDIC TONE DOUBLE SVARITA 
are incorrect. svarita and double svarita are centred above the syllable.
anudatta is placed below with some distance from the baseline.
When signs which occur below or below-right like ottus and vowel sign vocalic r, rr, ai etc. the signs should not clash with them.
![image](https://user-images.githubusercontent.com/23263723/40429328-1412f076-5ec0-11e8-9c24-ec0bd5321e53.png)
see- https://sanskritdocuments.org/doc_veda/puruSukta.html?lang=kn
[TSPP1_K_Goda_Sample.pdf](https://github.com/googlei18n/noto-fonts/files/2031409/TSPP1_K_Goda_Sample.pdf)

### Character data
   1.ಕ್ಷಜ್ಞಾ  ಕ್ಷಾಮಕ್ಷೋ
2. ಫ಼ಫ಼ಾಫ಼ಿಫ಼ೋ
3. ಝೊ ಝೋ
4. ಟೆ ಟೇ ಟೈ ಟೊ ಟೋ ಟೌಟಾ
5. 5. U+0C80 KANNADA SIGN SPACING CANDRABINDU
6.  U+0951 DEVANAGARI STRESS SIGN UDATTA : Vedic tone svarita
U+0952 DEVANAGARI STRESS SIGN ANUDATTA : Vedic tone anudatta
U+1CDA VEDIC TONE DOUBLE SVARITA

**Comment by sridatta1** [comment]
Also the svarita and double svarita ( vertical lines) need to longer than the current ones, though there is an issue of vertical metrics.
![image](https://user-images.githubusercontent.com/23263723/40438546-f90acb94-5ed5-11e8-82c1-e7fb522dfb15.png)
also see page 5 of https://www.unicode.org/L2/L2010/10392r2-chandrabindus.pdf

**Comment by sridatta1** [comment]
Positioning of Candrabindu
Chandrabindu is centred above the syllable.
Candrabindu is seen usage of Kannada script for Sanskrit, Prakrit, some Kannada dialects like Havyaka, minority languages of Karnataka like Sanketi etc and transliteration of Hindi etc.
![capture](https://user-images.githubusercontent.com/23263723/40440384-8c5a7868-5edb-11e8-8d47-8e1bc3d939ac.JPG)
The first line has correct positioning, second line doesn't have.
For vowels, vowel signs other than E,I, with a conjunct, virama etc. positioning is incorrect.

**Comment by anthrotype** [comment]
I believe some of the issues raised above have to do with the absence of "abvm" and "blwm" GPOS features in the current Noto Serif Kannada as it was built using the fontmake pipeline.
If you inspect the GPOS table, you'll see they have a generic "mark" feature where they should contain Indic-specific "abvm" and "blwm" features, which are enabled by default for those scripts.
When exported from Glyphs.app, the fonts will have these two features automatically generated.
We are working on adding support to auto-generating these Indic-related OTL features in our build pipeline (cf. https://github.com/googlei18n/ufo2ft/issues/179).
I implemented the "dist" feature (the equivalent of "kern") already (though unreleased yet). I'll work on "abvm" and "blwm" soon.
Apologies for the inconvenience.

**Comment by JelleBosmaMT** [comment]
In the days of metal type, compositors had to make do with what they had available.  These samples showing gigantic marks predate type design as we know it today.   Given the fact that these signs are going above and below the font's ascender and descender values anyway, they stand out clearly. They don't need to be larger than they need to be to be functional.

 
Jelle Bosma
Typographic Development Consultant
Monotype Ltd.
Netherlands
Mobile +31 (64) 3509270
Our Brand Family
​
Monotype.com
Olapic.com
 
 
Monotype Ltd. Registered in England No. 2663485, Unit 2, Perrywood Business Park, Salfords, Redhill, Surrey, RH1 5DZ, UK.
 
This e-mail message and any accompanying documentation is intended for the addressee only and may contain legally privileged and confidential information. If you are not the addressee
 any use of this information is strictly prohibited. If you have received this e-mail in error please notify us immediately by reply e-mail or telephone call on +44 (0)1737 765959 and delete this
 e-mail from your systems.

﻿On 23-May-18, 18:40, "Sridatta A" <notifications@github.com> wrote:

    Also the svarita and double svarita ( vertical lines) need to longer than the current ones, though there is an issue of vertical metrics.
     <https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_23263723_40438546-2Df90acb94-2D5ed5-2D11e8-2D82c1-2De7fb522dfb15.png&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=VnH-mkuVgDGcaqtfuNAH9a_L-zzaYSl7eNLCl16GOtM&m=klUtX3SFfTxF82Wq9suhHZehJGm8owvELya3hTs2HrQ&s=_9eYqGZyfj6RGxiV55raDiV8Fd4s1WuEK4XntDZY5Qo&e=>
    also see page 5 of https://www.unicode.org/L2/L2010/10392r2-chandrabindus.pdf <https://urldefense.proofpoint.com/v2/url?u=https-3A__www.unicode.org_L2_L2010_10392r2-2Dchandrabindus.pdf&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=VnH-mkuVgDGcaqtfuNAH9a_L-zzaYSl7eNLCl16GOtM&m=klUtX3SFfTxF82Wq9suhHZehJGm8owvELya3hTs2HrQ&s=be0ip7NxVv3-C-w2OCCl6XWtQGgp8GdeLOETdFB9oS8&e=>

**Comment by JelleBosmaMT** [comment]
@sridatta1: I have put them side by side in the soon to be completed Kannada Sans. Candrabindu left, single or double svarita to the right. The Sans doesn't rely on auto-generated features, so it should be functional from the start.

@anthrotype If mark attachment works in some syllables and not in others, the "mark" feature may work: if it is not a problem of missing attachment points, it may be in-between glyphs. In Unicode order the Vedic signs come last in the syllable. In scripts like Devanagari the base glyph is the last glyph before the non-spacing marks. But in Kannada or Telugu the base consonant is the first glyph of the syllable. There may be more than a few glyphs between base and mark. In the Kannada Sans there is quite some work going on in the OTL tables in order to get the marks to attach to the base.

**Comment by sridatta1** [comment]
also U+A833- U+A835
NORTH INDIC FRACTION ONE SIXTEENTH
NORTH INDIC FRACTION ONE EIGHTH
 NORTH INDIC FRACTION THREE SIXTEENTHS 
need to have horizontal bars, instead of bars slanting upward to the right.
![image](https://user-images.githubusercontent.com/23263723/40485822-34c5a65c-5f7d-11e8-98aa-821ea7fd31c1.png)
This is also explained in page 802 of Unicode standard core specification.
![image](https://user-images.githubusercontent.com/23263723/40485903-63c64bc8-5f7d-11e8-842f-2583cf19e0fd.png)
see https://www.unicode.org/L2/L2015/15243-kannada-frac.pdf

**Comment by sridatta1** [comment]
Have a question regarding placement of anudatta. In some printed books of Kannada and few other south Indian scripts like Malayalam, Grantha etc, anudatta is placed at consistent position despite the existence of descenders or not (this could also be due to limitations in metal type). For akṣaras without descenders e.g. ಕ ಮ ತ etc. this would cause large gap. This also affects line spacing. In Devanagari fonts anudatta is placed at a fixed distance from the bottom of the glyph, if there are any descenders  like matras it is placed below them. Should the practice in Devanagari be followed? See https://github.com/Sandhi-IITBombay/Shobhika/issues/6. 
I think in Kannada for consonant clusters with right-botto ottus and having right-side vowel signs like ಷ್ಣ್ಯಾ॒ ತ್ವಾ॒ ದ್ದ್ಯು॒ ಷ್ಣೋ॒ can be placed below the consonant rather than below the descenders so that extra height in the anudatta is avoided.

**Comment by JelleBosmaMT** [comment]
@sridatta1 So far I have used a consistent low and high position for Tamil, Malayalam, Telugu, Bengali and Kannada (all Sans). That is the only method I found being used in examples (using Grantha as example for Tamil). I haven't investigated Gurmukhi and Gujarati yet. 
I really would not like to change that for Kannada in particular, because the font's GSUB table size has already quadrupled in order to deal with these Vedic signs. That was a big puzzle. Even more so because Google, Microsoft and Apple shapers are doing things differently. I trust my current solution is good enough, so I don't have to add an extra layer of complexity. 

(I think that for displaying individual syllables at large sizes, having variable mark distances will look prettier. But in small text the line distance has to be quite large for the worst cases anyway. It could be an advantage if the additional marks align at their own level above and below the text.)

**Comment by sridatta1** [comment]
@JelleBosmaMT Thank you, I wasn't advocating variable mark distances, since Devanagari-style is already implemented, I was just looking if there are any challenges in implementing the current consistent position style or will it add additional complexities.

**Comment by sridatta1** [comment]
@JelleBosmaMT In Gujarat, Sanskrit (and thus vedas) is generally written in Devanagari. I haven't seen Vedic  texts in Gujarati script till now.
![image](https://user-images.githubusercontent.com/23263723/40493095-a7e814aa-5f8f-11e8-98c3-0a9ff4dd29b4.png)


![image](https://user-images.githubusercontent.com/23263723/40493125-b4121398-5f8f-11e8-99ed-b40235b6aa36.png)
Gurmukhi is not phonetically suitable for Sanskrit doesn't have letters for all sounds, conjuncts etc.
In undivided Punjab region Sanskrit was/is generally written in Devanagari.
Vedic texts published from pre-partition India's Lahore, today's Hoshairpur etc. are in Devanagari.
They may be added to Gujarati, Gurmukhi fonts only after getting evidence from published sources as supporting them involves lot of overhead and complexities

**Comment by sridatta1** [comment]
Any updates on this issue for Kannada Serif font? As many are using this font. There some stylistic/glyph improvements on which I may file issue when I find time.

**Comment by nizarsq** [comment]
@sridatta1 can you test the current font in this [directory](https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSerifKannada/NotoSerifKannada-Medium.ttf) and update the bug with what you can reproduce. Thanks
<img width="1301" alt="Screen Shot 2020-06-17 at 11 54 44 PM" src="https://user-images.githubusercontent.com/22158882/84988226-7cc5c280-b0f6-11ea-8d99-a6751c2e03a4.png">

**Comment by sridatta1** [comment]
Hi
Updating the results with the font from above directory.
![image](https://user-images.githubusercontent.com/23263723/85042449-d8e91f00-b1a8-11ea-9c02-8ff8d8f0c440.png)
All these issues are fixed. I'm closing the issue.
