### ISSUE TITLE
'dlig' changes positional forms of lam and alef presentation forms

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1194]
### Font
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-02-04

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
'dlig' composes isolated lam presentation forms and isolated alef presentation forms into lam–alef ligatures. These characters, encoded only for compatibility with glyph-based encodings, should not change positional forms like that.

### Character data
ﻝﭐﻝﺁﻝﺃﻝﺇﻝﺍ
U+FEDD ARABIC LETTER LAM ISOLATED FORM
U+FB50 ARABIC LETTER ALEF WASLA ISOLATED FORM
U+FEDD ARABIC LETTER LAM ISOLATED FORM
U+FE81 ARABIC LETTER ALEF WITH MADDA ABOVE ISOLATED FORM
U+FEDD ARABIC LETTER LAM ISOLATED FORM
U+FE83 ARABIC LETTER ALEF WITH HAMZA ABOVE ISOLATED FORM
U+FEDD ARABIC LETTER LAM ISOLATED FORM
U+FE87 ARABIC LETTER ALEF WITH HAMZA BELOW ISOLATED FORM
U+FEDD ARABIC LETTER LAM ISOLATED FORM
U+FE8D ARABIC LETTER ALEF ISOLATED FORM

### Screenshot
Default:
![ﻝﭐﻝﺁﻝﺃﻝﺇﻝﺍ](https://user-images.githubusercontent.com/1124347/40432239-3a5ed8ce-5e77-11e8-9801-55ada9828ef8.png)
With 'dlig':
![ﻝﭐﻝﺁﻝﺃﻝﺇﻝﺍ](https://user-images.githubusercontent.com/1124347/40432241-3a78b474-5e77-11e8-9713-00598dc808b4.png)

**Comment by nizarsq** [comment]
This issue fixed
<img width="1417" alt="Screen Shot 2020-05-27 at 2 02 49 AM" src="https://user-images.githubusercontent.com/22158882/82999723-4ba61680-9fbe-11ea-813d-61a4c85f9f68.png">
