### ISSUE TITLE
Misplaced anchor points in Noto Sans Arabic

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1197]
### Font
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-02-04

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
Some letters’ anchor points above are too low and some letters’ anchor points below are too high.

### Character data
ٲُږّݳُݴُݵُݶُݸُݹُݺُݻُݽُݯُ ڕِݕِݼِݷِݚِࢠۭࢳِ
U+0672 ARABIC LETTER ALEF WITH WAVY HAMZA ABOVE
U+064F ARABIC DAMMA
U+0696 ARABIC LETTER REH WITH DOT BELOW AND DOT ABOVE
U+0651 ARABIC SHADDA
U+0773 ARABIC LETTER ALEF WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE
U+064F ARABIC DAMMA
U+0774 ARABIC LETTER ALEF WITH EXTENDED ARABIC-INDIC DIGIT THREE ABOVE
U+064F ARABIC DAMMA
U+0775 ARABIC LETTER FARSI YEH WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE
U+064F ARABIC DAMMA
U+0776 ARABIC LETTER FARSI YEH WITH EXTENDED ARABIC-INDIC DIGIT THREE ABOVE
U+064F ARABIC DAMMA
U+0778 ARABIC LETTER WAW WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE
U+064F ARABIC DAMMA
U+0779 ARABIC LETTER WAW WITH EXTENDED ARABIC-INDIC DIGIT THREE ABOVE
U+064F ARABIC DAMMA
U+077A ARABIC LETTER YEH BARREE WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE
U+064F ARABIC DAMMA
U+077B ARABIC LETTER YEH BARREE WITH EXTENDED ARABIC-INDIC DIGIT THREE ABOVE
U+064F ARABIC DAMMA
U+077D ARABIC LETTER SEEN WITH EXTENDED ARABIC-INDIC DIGIT FOUR ABOVE
U+064F ARABIC DAMMA
U+076F ARABIC LETTER HAH WITH SMALL ARABIC LETTER TAH AND TWO DOTS
U+064F ARABIC DAMMA
U+0695 ARABIC LETTER REH WITH SMALL V BELOW
U+0650 ARABIC KASRA
U+0755 ARABIC LETTER BEH WITH INVERTED SMALL V BELOW
U+0650 ARABIC KASRA
U+077C ARABIC LETTER HAH WITH EXTENDED ARABIC-INDIC DIGIT FOUR BELOW
U+0650 ARABIC KASRA
U+0777 ARABIC LETTER FARSI YEH WITH EXTENDED ARABIC-INDIC DIGIT FOUR BELOW
U+0650 ARABIC KASRA
U+075A ARABIC LETTER DAL WITH INVERTED SMALL V BELOW
U+0650 ARABIC KASRA
U+08A0 ARABIC LETTER BEH WITH SMALL V BELOW
U+06ED ARABIC SMALL LOW MEEM
U+08B3 ARABIC LETTER AIN WITH THREE DOTS BELOW
U+0650 ARABIC KASRA

### Screenshot
![ٲُږّݳُݴُݵُݶُݸُݹُݺُݻُݽُݯُ](https://user-images.githubusercontent.com/1124347/40581504-701f866c-6128-11e8-8c34-88d141b51290.png)
![ڕِݕِݼِݷِݚِࢠۭࢳِ](https://user-images.githubusercontent.com/1124347/40581413-a4b30906-6125-11e8-9e04-d6d024cc7ab3.png)

**Comment by nizarsq** [comment]
Version 2.5 rendering is a little different, but definitely there is still an issue with letters’ anchor points.
<img width="489" alt="Screen Shot 2020-05-20 at 12 53 31 AM" src="https://user-images.githubusercontent.com/22158882/82420284-61eb2a00-9a34-11ea-813f-c0e7f4f12caa.png">

**Comment by nizarsq** [comment]
Looks to me the anchor points are missing
