### ISSUE TITLE
Ligatures between Arabic presentation forms and normal letters

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1198]
### Font
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-02-04

### Font version
Noto Sans Arabic: Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
The 'dlig' lookup includes some ligatures between presentation forms and normal letters.

### Character data
ڵﺍڶﺍڷﺍڸﺍﺋەﺌە
U+06B5 ARABIC LETTER LAM WITH SMALL V
U+FE8D ARABIC LETTER ALEF ISOLATED FORM
U+06B6 ARABIC LETTER LAM WITH DOT ABOVE
U+FE8D ARABIC LETTER ALEF ISOLATED FORM
U+06B7 ARABIC LETTER LAM WITH THREE DOTS ABOVE
U+FE8D ARABIC LETTER ALEF ISOLATED FORM
U+06B8 ARABIC LETTER LAM WITH THREE DOTS BELOW
U+FE8D ARABIC LETTER ALEF ISOLATED FORM
U+FE8B ARABIC LETTER YEH WITH HAMZA ABOVE INITIAL FORM
U+06D5 ARABIC LETTER AE
U+FE8C ARABIC LETTER YEH WITH HAMZA ABOVE MEDIAL FORM
U+06D5 ARABIC LETTER AE

### Screenshot
Default:
![ڵﺍڶﺍڷﺍڸﺍﺋەﺌە](https://user-images.githubusercontent.com/1124347/40591449-80dd8a28-61df-11e8-8e59-7488217cfcfc.png)
With 'dlig':
![ڵﺍڶﺍڷﺍڸﺍﺋەﺌە](https://user-images.githubusercontent.com/1124347/40591450-80f05180-61df-11e8-8a93-4c9fe6355fc1.png)

**Comment by nizarsq** [comment]
This issue fixed
<img width="1311" alt="Screen Shot 2020-05-27 at 2 22 48 AM" src="https://user-images.githubusercontent.com/22158882/83001833-1fd86000-9fc1-11ea-867c-33300c631595.png">
