### ISSUE TITLE
Wrong glyph for Kufi U+06C1 ARABIC LETTER HEH GOAL in Allah ligature

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1201]
### Font
NotoKufiArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoKufiArabic-unhinted.zip
Date: 2018-02-04

### Font version
Version 1.04 uh

### Issue
In the Allah ligature, U+06C1 ARABIC LETTER HEH GOAL takes the form of U+0647 ARABIC LETTER HEH instead.

### Character data
اللہ
U+0627 ARABIC LETTER ALEF
U+0644 ARABIC LETTER LAM
U+0644 ARABIC LETTER LAM
U+06C1 ARABIC LETTER HEH GOAL

### Screenshot
![اللہ](https://user-images.githubusercontent.com/1124347/40726121-1107d058-63f3-11e8-94bd-eb8a91785a9b.png)
Without the ligature:
![اللہ](https://user-images.githubusercontent.com/1124347/40726122-11281e76-63f3-11e8-8c9a-d422ef37bcad.png)

**Comment by nizarsq** [comment]
Tested on the lastest [NotoKufiArabic version 2.101](https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/ttf/NotoKufiArabic/NotoKufiArabic-Regular.ttf) and  U+06C1 (ARABIC LETTER HEH GOAL) rendering is correct in the current version
<img width="600" alt="Screen Shot 2020-05-21 at 9 12 41 PM" src="https://user-images.githubusercontent.com/22158882/82630769-9122a800-9ba8-11ea-9441-4f1e9227f05b.png">
