### ISSUE TITLE
Overlapping below-base marks in Kharoshthi

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1207]
### Font
NotoSansKharoshthi-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansKharoshthi-unhinted.zip
Date: 2018-04-09

### Font version
Version 1.03 uh

### Issue
In some sequences of bases with marks below, the marks overlap.

### Character data
𐨗𐨂𐨞𐨌
U+10A17 KHAROSHTHI LETTER JA
U+10A02 KHAROSHTHI VOWEL SIGN U
U+10A1E KHAROSHTHI LETTER NNA
U+10A0C KHAROSHTHI VOWEL LENGTH MARK

### Screenshot
![𐨗𐨂𐨞𐨌](https://user-images.githubusercontent.com/1124347/40881086-15ca33f6-668c-11e8-87d2-5d67641a1fd3.png)

**Comment by simoncozens** [comment]
This has been fixed.
