### ISSUE TITLE
Wrong glyph for U+274B HEAVY EIGHT TEARDROP-SPOKED PROPELLER ASTERISK

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1209]
### Font
NotoSansSymbols2-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansSymbols2-unhinted.zip
Date: 2018-04-03

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
The spokes of U+274B HEAVY EIGHT TEARDROP-SPOKED PROPELLER ASTERISK should look like teardrops. Cf. the other teardrop-spoked asterisks.

### Character data
❋
U+274B HEAVY EIGHT TEARDROP-SPOKED PROPELLER ASTERISK

### Screenshot
![❋](https://user-images.githubusercontent.com/1124347/40939259-29155508-6812-11e8-8e7b-2fb9f1846657.png)

**Comment by nizarsq** [comment]
Issue fixed.
<img width="1173" alt="Screen Shot 2020-07-25 at 9 23 54 PM" src="https://user-images.githubusercontent.com/22158882/88471328-2732c180-cebd-11ea-850b-6d65c1705bfb.png">
