### ISSUE TITLE
Wrong glyph for U+1F0F3 PLAYING CARD TRUMP-19

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1210]
### Font
NotoSansSymbols2-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansSymbols2-unhinted.zip
Date: 2018-04-03

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+1F0F3 PLAYING CARD TRUMP-19 depicts a snowflake, representing winter. A snowflake has six arms, not eight.

### Character data
🃳
U+1F0F3 PLAYING CARD TRUMP-19

### Screenshot
![🃳](https://user-images.githubusercontent.com/1124347/40978837-354bcc22-68a2-11e8-87b1-07cf4be6e06c.png)

**Comment by nizarsq** [comment]
Issue fixed.
<img width="991" alt="Screen Shot 2020-07-25 at 9 20 32 PM" src="https://user-images.githubusercontent.com/22158882/88471293-ad9ad380-cebc-11ea-84ab-87e0c546730d.png">
