### ISSUE TITLE
U+10A38 and U+10A3A block Kharoshthi ligatures

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1214]
### Font
NotoSansKharoshthi-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansKharoshthi-unhinted.zip
Date: 2018-04-09

### Font version
Version 1.03 uh

### Issue
The consonant modifiers U+10A38 and U+10A3A block consonant-vowel ligatures.

### Character data
𐨒𐨸𐨁𐨱𐨺𐨅
U+10A12 KHAROSHTHI LETTER GA
U+10A38 KHAROSHTHI SIGN BAR ABOVE
U+10A01 KHAROSHTHI VOWEL SIGN I
U+10A31 KHAROSHTHI LETTER HA
U+10A3A KHAROSHTHI SIGN DOT BELOW
U+10A05 KHAROSHTHI VOWEL SIGN E

### Screenshot
![𐨒𐨸𐨁𐨱𐨺𐨅](https://user-images.githubusercontent.com/1124347/41165157-ef43b79c-6b0a-11e8-80a3-5fbe18a50c2a.png)

**Comment by simoncozens** [comment]
This seems to have been fixed.
