### ISSUE TITLE
U+10198..10199 ROMAN SESTERTIUS/DUPONDIUS SIGN: too much internal space

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1219]
### Font
NotoSansSymbols2-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansSymbols2-unhinted.zip
Date: 2018-04-03

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
The sestertius and dupondius signs are IIS and II with an overlaid bar. (There are other glyph variants, but those are the ones used in Noto Sans Symbols2.) However, this font uses ⟨H⟩ instead of ⟨II⟩, so the spacing is wrong.

### Character data
𐆘 𐆙
U+10198 ROMAN SESTERTIUS SIGN
U+0020 SPACE
U+10199 ROMAN DUPONDIUS SIGN

### Screenshot
![𐆘 𐆙](https://user-images.githubusercontent.com/1124347/41376034-e90249b0-6f25-11e8-8ca4-99a100f4bc73.png)

**Comment by nizarsq** [comment]
I see the spacing changed. @dscorbett could you verify if this issue fixed? Thanks
<img width="999" alt="Screen Shot 2020-07-25 at 9 10 46 PM" src="https://user-images.githubusercontent.com/22158882/88471219-51837f80-cebb-11ea-894f-d0c9c0ebc7cd.png">

**Comment by dscorbett** [comment]
It is fixed.
