### ISSUE TITLE
Wrong glyph for U+2C77 LATIN SMALL LETTER TAILLESS PHI

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1221]
### Font
NotoSansMono-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansMono-unhinted.zip
Date: 2018-05-31

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+2C77 LATIN SMALL LETTER TAILLESS PHI has a tail.

### Character data
ⱷ
U+2C77 LATIN SMALL LETTER TAILLESS PHI

### Screenshot
![ⱷ](https://user-images.githubusercontent.com/1124347/41422154-4f4332c0-6fc6-11e8-82c5-27a55394f8fe.png)

**Comment by nizarsq** [comment]
This issue seems to be fixed in the current NotoSansMono font
<img width="610" alt="Screen Shot 2020-07-10 at 4 19 00 PM" src="https://user-images.githubusercontent.com/22158882/87210062-12550c00-c2c9-11ea-96fb-81674456f1d1.png">
