### ISSUE TITLE
Negative side-bearings on U+213A ROTATED CAPITAL Q

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1222]
### Font
NotoSansMono-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansMono-unhinted.zip
Date: 2018-05-31

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+213A ROTATED CAPITAL Q has negative side-bearings.

### Character data
―℺―
U+2015 HORIZONTAL BAR
U+213A ROTATED CAPITAL Q
U+2015 HORIZONTAL BAR

### Screenshot
![―℺―](https://user-images.githubusercontent.com/1124347/41470193-ea07a2e8-707d-11e8-96b1-7376d0855054.png)

**Comment by nizarsq** [comment]
This issue fixed
<img width="574" alt="Screen Shot 2020-07-10 at 5 18 51 PM" src="https://user-images.githubusercontent.com/22158882/87212047-6d8afc80-c2d1-11ea-9a8f-4b36c5c37745.png">
