### ISSUE TITLE
Meetei Mayek 'dist' lookup is not applied

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1224]
### Font
NotoSansMeeteiMayek-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansMeeteiMayek-unhinted.zip
Date: 2018-06-10

### Font version
Version 1.04 uh

### Issue
The font uses a 'dist' lookup to reorder vowels. The lookup has the 'DFLT' script tag. Because the default shaper does not enable 'dist', the lookup is not applied.

### Character data
ꫢꫫ
U+AAE2 MEETEI MAYEK LETTER CHA
U+AAEB MEETEI MAYEK VOWEL SIGN II

### Screenshot
![ꫢꫫ](https://user-images.githubusercontent.com/1124347/41508950-336929e6-721a-11e8-9cd2-d6c95ae9ed84.png)

**Comment by simoncozens** [comment]
This font now goes through the USE, which reorders the vowels.
