### ISSUE TITLE
Kharoshthi 'dist' lookup is not applied

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1228]
### Font
NotoSansKharoshthi-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansKharoshthi-unhinted.zip
Date: 2018-04-09

### Font version
Version 1.03 uh

### Issue
The font uses a 'dist' lookup with the 'DFLT' script tag. Because the default shaper does not enable 'dist', the lookup is not applied. This makes the vowel signs <i>u</i> and <i>o</i> sometimes overlap a following consonant.

### Character data
𐨗𐨂𐨲𐨞𐨆𐨲
U+10A17 KHAROSHTHI LETTER JA
U+10A02 KHAROSHTHI VOWEL SIGN U
U+10A32 KHAROSHTHI LETTER KKA
U+10A1E KHAROSHTHI LETTER NNA
U+10A06 KHAROSHTHI VOWEL SIGN O
U+10A32 KHAROSHTHI LETTER KKA

### Screenshot
![𐨗𐨂𐨲𐨞𐨆𐨲](https://user-images.githubusercontent.com/1124347/41609955-f1098ae0-73b9-11e8-8c3a-acf237a0f50c.png)

**Comment by marekjez86** [comment]
@behdad : is this in your "court"? If not, please remove yourself.
@dscorbett : is it platform related? if yes, then which platform did you use?

**Comment by dscorbett** [comment]
It depends not on the platform but on the shaper. I used HarfBuzz.

**Comment by punchcutter** [comment]
This is the really old version of the font. The updated version from late last year applies the dist. It's in noto-source and https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted, but the TTF in https://github.com/googlei18n/noto-fonts/tree/master/unhinted is still the old one. 

![khar_dist](https://user-images.githubusercontent.com/11257204/41945303-307f1724-7961-11e8-86cc-caab8e5671a4.png)

**Comment by behdad** [comment]
If the font uses DFLT script system, then dist is not applied.  If it uses Universal Shaping Engine, dist is applied.  Working as intended as far as I'm concerned.

**Comment by simoncozens** [comment]
This is indeed already fixed.
