### ISSUE TITLE
U+101A0 GREEK SYMBOL TAU RHO looks lowercase

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1233]
### Font
NotoSansSymbols2-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansSymbols2-unhinted.zip
Date: 2018-04-03

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+101A0 GREEK SYMBOL TAU RHO in Noto Sans Symbols2 looks almost the same as U+03FC GREEK RHO WITH STROKE SYMBOL in Noto Sans, but it should look more like a capital letter, as U+2627 CHI RHO does in Noto Sans Symbols. The examples in [L2/12-034](https://www.unicode.org/L2/L2012/12034-papyrological.pdf) show it as taller than lowercase letters; it may or may not have a descender.

### Character data
𐆠
U+101A0 GREEK SYMBOL TAU RHO

### Screenshot
![𐆠](https://user-images.githubusercontent.com/1124347/41819775-4024e5ba-7794-11e8-9f66-9facc6220f7c.png)

**Comment by nizarsq** [comment]
101A0 fixed.
<img width="1011" alt="Screen Shot 2020-07-25 at 5 42 33 PM" src="https://user-images.githubusercontent.com/22158882/88468867-39e9ce00-ce9e-11ea-85ed-708278e10995.png">
