### ISSUE TITLE
Extra alternative representation of chillu k

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1234]
### Font
NotoSansMalayalam-Regular.ttf
NotoSerifMalayalam-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansMalayalam-unhinted.zip
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifMalayalam-unhinted.zip
Date: 2018-04-03

### Font version
Noto Sans Malayalam: Version 1.04 uh
Noto Serif Malayalam: Version 1.01 uh

### Issue
In Noto, ⟨ക്‍⟩ looks like U+0D7F MALAYALAM LETTER CHILLU K, but that sequence is not defined, and should instead fall back to looking like ⟨ക്⟩. See [Table 12-39](https://www.unicode.org/versions/Unicode11.0.0/ch12.pdf#page=68).

### Character data
ക്‍
U+0D15 MALAYALAM LETTER KA
U+0D4D MALAYALAM SIGN VIRAMA
U+200D ZERO WIDTH JOINER

### Screenshot
![ക്‍](https://user-images.githubusercontent.com/1124347/41851748-e5979426-7856-11e8-9c0f-ce463dc92d96.png)![ക്‍](https://user-images.githubusercontent.com/1124347/41851751-e5d87086-7856-11e8-9754-3833c52d3238.png)

**Comment by marekjez86** [comment]
should be fixed in the newly released https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSerifMalayalam ; not fixed in Sans though

**Comment by nizarsq** [comment]
Confirming the fix in Serif but not Sans.
<img width="1284" alt="Screen Shot 2020-06-19 at 11 06 38 PM" src="https://user-images.githubusercontent.com/22158882/85194184-9e9f8080-b281-11ea-910c-05ef421e4ba9.png">

**Comment by marekjez86** [comment]
fixed with the newest release of Sans (no issue for Serif)
