### ISSUE TITLE
Wrong glyph for final U+075B ARABIC LETTER REH WITH STROKE

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1235]
### Font
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-02-04

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
In Noto Sans Arabic, the stroke of final U+075B ARABIC LETTER REH WITH STROKE is above the baseline. Cf. Noto Kufi Arabic and Noto Naskh Arabic.

### Character data
ـݛ
U+0640 ARABIC TATWEEL
U+075B ARABIC LETTER REH WITH STROKE

### Screenshot
![ـݛ](https://user-images.githubusercontent.com/1124347/41945885-7ce6645c-797d-11e8-99ba-b443cd66b78e.png)

**Comment by nizarsq** [comment]
This issue still reproducible.
<img width="597" alt="Screen Shot 2020-05-21 at 9 28 30 PM" src="https://user-images.githubusercontent.com/22158882/82631437-4b66df00-9baa-11ea-8823-2615af46284c.png">
