### ISSUE TITLE
Poor positioning of U+1BFF BATAK SYMBOL BINDU PANGOLAT

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1238]
### Font
NotoSansBatak-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansBatak-unhinted.zip
Date: 2018-06-28

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+1BFF BATAK SYMBOL BINDU PANGOLAT should curve around the preceding character. In this font, it is too high and does not interact with the preceding character. See [L2/08-011R](https://www.unicode.org/L2/L2008/08011r-n3320r-batak.pdf) and [<i>Tobasche spraakkunst</i>, pg. 22](https://archive.org/stream/tobaschespraakk00bijbgoog#page/n39/mode/1up) for examples.

### Character data
ᯤ᯿
U+1BE4 BATAK LETTER I
U+1BFF BATAK SYMBOL BINDU PANGOLAT

### Screenshot
![ᯤ᯿](https://user-images.githubusercontent.com/1124347/42101759-0f0ca3d0-7b92-11e8-9939-5bd46062c201.png)

**Comment by punchcutter** [comment]
<img width="289" alt="batak1238" src="https://user-images.githubusercontent.com/11257204/126869755-aefdd34e-43c3-4bfb-82e0-22f46d90f046.png">

Updated to curve around other letters like in example text.
