### ISSUE TITLE
The tail of J overlaps with the underscore in Noto Sans

### ISSUE THREAD

**Issue by cmfwyp** [googlefonts/noto-fonts#1241]
The descender of the letter J overlaps with the underscore in “_J”.

![](https://user-images.githubusercontent.com/20808761/42138312-4c57e1ba-7d49-11e8-9342-905cb14b684c.png)

The above image is generated with `hb-view --output-format=png --output-file=out.png NotoSans-Regular.otf _J`, where NotoSans-Regular.otf is https://github.com/googlei18n/noto-fonts/blob/449470a4d83f6eecdb4a537ab66fcbb5ff28917a/phaseIII_only/unhinted/otf/NotoSans/NotoSans-Regular.otf.

This also happens with the phase III unhinted TTF in `phaseIII_only/unhinted/ttf`, the hinted TTF, and the version of Noto Sans available on https://google.com/get/noto.

Noto Sans Italic:

![out](https://user-images.githubusercontent.com/20808761/42138404-14b4c38e-7d4b-11e8-8245-3fd3b950ca62.png)

Noto Sans Bold:

![out](https://user-images.githubusercontent.com/20808761/42138402-0aea6ebc-7d4b-11e8-9404-b95bb20cd6cc.png)

Noto Sans Bold Italic:

![out](https://user-images.githubusercontent.com/20808761/42138406-231b6f7c-7d4b-11e8-801e-6f7b4429e80c.png)

But Noto Serif is fine:

![out](https://user-images.githubusercontent.com/20808761/42138443-8eff6a7c-7d4b-11e8-8200-24fa8b5566ae.png)

**Comment by nizarsq** [comment]
This issue has been fixed.
<img width="512" alt="Screen Shot 2020-07-09 at 9 25 09 PM" src="https://user-images.githubusercontent.com/22158882/87116433-acb24280-c22a-11ea-8d6a-5cda7d4acd12.png">
