### ISSUE TITLE
Support copyleft symbol

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [googlefonts/noto-fonts#1250]
### Font 
NotoSans-Regular.ttf and NotoSerif-Regular.ttf

### Where the font came from, and when
Bundled in LibreOffice 6.1 RC1
https://download.documentfoundation.org/libreoffice/testing/6.1.0/win/x86_64/LibreOffice_6.1.0.1_Win_x64.msi

### Font Version
n/a

### OS name and version
Windows 10 v1803

### Application name and version
LibO 6.1 RC1

### Issue
Unicode 11.0 is released last month, this introduced copyleft symbol in U+1F12F (🄯), the shape should be looks like mirrored ©. It was often used in some "copyleft" declarations.

  1. Steps to reproduce
  * First, input 1F12F in LO Writer, second, select the text and press Alt + X.
  2. Observed results
  * The code is converted to copyleft symbol, but it was displayed by fallback fonts, not by Noto Sans or Noto Serif
  3. Expected results
  * Noto fonts should displaying copyleft symbol
  4. Additional information 
  * See https://www.unicode.org/charts/PDF/U1F100.pdf

**Comment by dougfelt** [comment]
Yes.  It's not clear though when Noto will support new Unicode characters in Unicode version 11 and beyond.

**Comment by marekjez86** [comment]
The code point U+1F12F 🄯 COPYLEFT SYMBOL was added in Unicode 11. We are going through planning process to figure out when we will start supporting it (Noto includes up to Unicode 9, we need to get 10+ 11 done in the future).

**Comment by NatoBoram** [comment]
Colour me disappointed when the "no more tofu" font showed me a tofu instead of the 🄯 copyleft symbol.

**Comment by marekjez86** [comment]
all fonts in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansSymbols
OR
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansSymbols

should support 1F12F
