### ISSUE TITLE
Poor size and positioning of U+A69E COMBINING CYRILLIC LETTER EF

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1251]
### Font
NotoSans-Regular.ttf
NotoSansMono-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-unhinted.zip
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansMono-unhinted.zip
Date: 2018-06-18

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
In Noto Sans and Noto Sans Mono, U+A69E COMBINING CYRILLIC LETTER EF is much larger than the other combining Cyrillic letters. In Noto Sans Mono, it is missing an anchor point.

### Character data
иⷬиꚞ
U+0438 CYRILLIC SMALL LETTER I
U+2DEC COMBINING CYRILLIC LETTER ER
U+0438 CYRILLIC SMALL LETTER I
U+A69E COMBINING CYRILLIC LETTER EF

### Screenshot
![иⷬиꚞ](https://user-images.githubusercontent.com/1124347/42421413-27e51e38-82a3-11e8-8b55-b3aa2982ed9f.png)
![иⷬиꚞ](https://user-images.githubusercontent.com/1124347/42421415-2819a234-82a3-11e8-9b0b-765a62e14a72.png)

**Comment by nizarsq** [comment]
This issue has been fixed.
<img width="568" alt="Screen Shot 2020-07-09 at 8 56 05 PM" src="https://user-images.githubusercontent.com/22158882/87114891-9d30fa80-c226-11ea-8a7f-c8dc2211f653.png">
