### ISSUE TITLE
Overlapping combining letters with descenders

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1252]
### Font
NotoSans-Regular.ttf
NotoSansMono-Regular.ttf
NotoSerif-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-unhinted.zip
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansMono-unhinted.zip
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerif-unhinted.zip
Date: 2018-06-18

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
Many combining Latin and Cyrillic letters with descenders overlap their bases. I’ve listed a few below but there are probably combinations of font, base, and mark that I didn’t try that are also wrong.

### Character data
zᷗzᷩzᷫzᷮzᷯвⷬвꙷ
U+007A LATIN SMALL LETTER Z
U+1DD7 COMBINING LATIN SMALL LETTER C CEDILLA
U+007A LATIN SMALL LETTER Z
U+1DE9 COMBINING LATIN SMALL LETTER BETA
U+007A LATIN SMALL LETTER Z
U+1DEB COMBINING LATIN SMALL LETTER F
U+007A LATIN SMALL LETTER Z
U+1DEE COMBINING LATIN SMALL LETTER P
U+007A LATIN SMALL LETTER Z
U+1DEF COMBINING LATIN SMALL LETTER ESH
U+0432 CYRILLIC SMALL LETTER VE
U+2DEC COMBINING CYRILLIC LETTER ER
U+0432 CYRILLIC SMALL LETTER VE
U+A677 COMBINING CYRILLIC LETTER U

### Screenshot
![zᷗzᷩzᷫzᷮzᷯвⷬвꙷ](https://user-images.githubusercontent.com/1124347/42470763-732df252-8389-11e8-9b64-505f7050033f.png)
![zᷗzᷩzᷫzᷮzᷯвⷬвꙷ](https://user-images.githubusercontent.com/1124347/42470764-7342ccd6-8389-11e8-8cb0-cd9f60e973c4.png)
![zᷗzᷩzᷫzᷮzᷯвⷬвꙷ](https://user-images.githubusercontent.com/1124347/42470765-7351aa3a-8389-11e8-9302-bf9c7eca364e.png)

**Comment by nizarsq** [comment]
Overlap issue resolvedfor NotoSans-Regular, NotoSansMono-Regular and NotoSerif-Regular
<img width="540" alt="Screen Shot 2020-07-08 at 11 11 31 AM" src="https://user-images.githubusercontent.com/22158882/86955035-c872f700-c10b-11ea-8735-403f5bee1d91.png">
