### ISSUE TITLE
Wrong glyph for U+A772 LATIN SMALL LETTER LUM

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1254]
### Font
NotoSansMono-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansMono-unhinted.zip
Date: 2018-06-18

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
The abbreviation stroke of U+A772 LATIN SMALL LETTER LUM should be on the right side.

### Character data
ꝲ
U+A772 LATIN SMALL LETTER LUM

### Screenshot
![ꝲ](https://user-images.githubusercontent.com/1124347/42578993-51c8a144-84f5-11e8-8b44-f8bbe8fb7e71.png)

**Comment by nizarsq** [comment]
Issue fixed.
<img width="587" alt="Screen Shot 2020-07-08 at 8 36 45 AM" src="https://user-images.githubusercontent.com/22158882/86939225-298fd000-c0f6-11ea-82f2-597e87c3474a.png">
