### ISSUE TITLE
Wrong glyph for U+027F LATIN SMALL LETTER REVERSED R WITH FISHHOOK

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1255]
### Font
NotoSansMono-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansMono-unhinted.zip
Date: 2018-06-18

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+027F LATIN SMALL LETTER REVERSED R WITH FISHHOOK should have a descender, as in Noto Sans and Noto Serif.

### Character data
ɿ
U+027F LATIN SMALL LETTER REVERSED R WITH FISHHOOK

### Screenshot
![ɿ](https://user-images.githubusercontent.com/1124347/42657339-ede268e4-85ef-11e8-963b-709272aa72c5.png)

**Comment by nizarsq** [comment]
Look like this issue has been resolved.
<img width="701" alt="Screen Shot 2020-07-07 at 11 01 52 AM" src="https://user-images.githubusercontent.com/22158882/86823101-44543d00-c041-11ea-9ed5-e1ee9bfd59f8.png">
