### ISSUE TITLE
Vend has serifs in sans-serif fonts

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1258]
### Font
NotoSans-Regular.ttf
NotoSansMono-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-unhinted.zip
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansMono-unhinted.zip
Date: 2018-06-18

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
The presence of serifs on the letter vend in Noto Sans and Noto Sans Mono is inconsistent with similar letters like wynn, which do not have serifs. The examples in [L2/06-027](https://www.unicode.org/L2/L2006/06027-n3027-medieval.pdf) do not show vend with unusually prominent serifs, and the sans-serif ones in figure 88 do not have serifs, so it should not have serifs in these two fonts.

### Character data
Ꝩꝩ Ƿƿ
U+A768 LATIN CAPITAL LETTER VEND
U+A769 LATIN SMALL LETTER VEND
U+01F7 LATIN CAPITAL LETTER WYNN
U+01BF LATIN LETTER WYNN

### Screenshot
![Ꝩꝩ Ƿƿ](https://user-images.githubusercontent.com/1124347/42734045-0e896634-880b-11e8-83c6-5577cf914a7c.png)![Ꝩꝩ Ƿƿ](https://user-images.githubusercontent.com/1124347/42734046-0ea24528-880b-11e8-8a1f-f906f06fe8e5.png)

**Comment by nizarsq** [comment]
This issue seems to be fixed. Please reopen if you have other thoughts
<img width="362" alt="Screen Shot 2020-07-07 at 10 04 03 AM" src="https://user-images.githubusercontent.com/22158882/86816859-31d60580-c039-11ea-946c-e8a47ddd255e.png">
