### ISSUE TITLE
Poor positioning of U+A75C LATIN CAPITAL LETTER RUM ROTUNDA

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1259]
### Font
NotoSans-Regular.ttf
NotoSansMono-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-unhinted.zip
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansMono-unhinted.zip
Date: 2018-06-18

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+A75C LATIN CAPITAL LETTER RUM ROTUNDA floats above the baseline in Noto Sans and Noto Sans Mono.

### Character data
Ꝝꝝ
Ꝝ U+A75C LATIN CAPITAL LETTER RUM ROTUNDA
ꝝ U+A75D LATIN SMALL LETTER RUM ROTUNDA

### Screenshot
![Ꝝꝝ](https://user-images.githubusercontent.com/1124347/42783045-b71c785a-8918-11e8-8c0d-d8f02c124007.png)
![Ꝝꝝ](https://user-images.githubusercontent.com/1124347/42783046-b7384b5c-8918-11e8-9bed-5818675b8553.png)

**Comment by nizarsq** [comment]
Look to me this issue has been resolved. Please reopen if you have other thoughts
<img width="302" alt="Screen Shot 2020-07-05 at 11 01 03 PM" src="https://user-images.githubusercontent.com/22158882/86560553-68b1fb80-bf13-11ea-92d5-aa5b4ba346ea.png">
