### ISSUE TITLE
Incorrect diacritics in U+FDFD in Noto Nastaliq Urdu

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1262]
### Font
NotoNastaliqUrdu-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoNastaliqUrdu-unhinted.zip
Date: 2018-07-18

### Font version
Version 1.02 uh

### Issue
In U+FDFD, only one sukun, two shaddahs, and a few harakat are present out of all those that could be there, which is inconsistent.

There is a short vertical line below the yeh, which could either be a misplaced superscript alef or a decorative ʿalāmatu l-ihmāl. If it is the former, it should be repositioned. If it is the latter, it looks out of place because there are no other ʿalāmāt al-ihmāl in this glyph.

### Character data
﷽
U+FDFD ARABIC LIGATURE BISMILLAH AR-RAHMAN AR-RAHEEM

### Screenshot
![﷽](https://user-images.githubusercontent.com/1124347/42914152-b88ff13a-8ac6-11e8-8277-fb41e26f9abd.png)

**Comment by khaledhosny** [comment]
In some Quranic orthographies, subscript Alif is used for long kasra, which
I think what is being done here.

>

**Comment by nizarsq** [comment]
I checked U+FDFD and I see not all diacritics exist. I believe it is inconsistent with other fonts
<img width="407" alt="Screen Shot 2020-05-21 at 4 04 45 PM" src="https://user-images.githubusercontent.com/22158882/82614620-214af800-9b7d-11ea-8448-c1438c55c7fc.png">
<img width="530" alt="Screen Shot 2020-05-21 at 4 03 25 PM" src="https://user-images.githubusercontent.com/22158882/82614626-2314bb80-9b7d-11ea-8938-dfa296d26e0c.png">

**Comment by khaledhosny** [comment]
There is no requirement that all vowel marks be added, and Nastaliq is usually light in the use of vowel marks compared to Naskh.

**Comment by khaledhosny** [comment]
Makes sense, I’d lower the shadda while doing so as well.
