### ISSUE TITLE
Overlapping U+08E4 and U+0679

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1267]
### Font
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-02-04

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+08E4 ARABIC CURLY FATHA may overlap a following medial U+0679 ARABIC LETTER TTEH.

### Character data
بࣤٹِࢬ
U+0628 ARABIC LETTER BEH
U+08E4 ARABIC CURLY FATHA
U+0679 ARABIC LETTER TTEH
U+0650 ARABIC KASRA
U+08AC ARABIC LETTER ROHINGYA YEH

### Screenshot
![بࣤٹِࢬ](https://user-images.githubusercontent.com/1124347/43871616-8aa35470-9b4b-11e8-9ab6-7f303e721424.png)

**Comment by nizarsq** [comment]
@marekjez86 U+08E4 ARABIC CURLY FATHA and U+0679 ARABIC LETTER TTEH should NOT  overlapped. Thanks

**Comment by nizarsq** [comment]
This issue resolved 
<img width="573" alt="Screen Shot 2020-05-21 at 3 13 03 PM" src="https://user-images.githubusercontent.com/22158882/82611710-f610da80-9b75-11ea-9391-9e9f27b2f638.png">

**Comment by nizarsq** [comment]
Fix revised reopening this bug. Fix needed in NotoSansArabic 2.02 and NotoSansArabicUI 2.02

**Comment by nizarsq** [comment]
This issue fixed on NotoSansArabic and NotoSansArabicUI
