### ISSUE TITLE
Noto Sans and Noto Serif not showing character sets, only "Other"

### ISSUE THREAD

**Issue by mohorko** [googlefonts/noto-fonts#1273]
## Noto Sans and Noto Serif not showing character sets, only "Other"

Noto Sans and Noto Serif are not showing character sets like Central European, Western, etc. in programs, only showing "Other".
This means Noto Sans and Noto Serif cannot be used in programs which request a certain character set (ie. Western). 

### Font 
  > All Noto Sans and Noto Serif fonts.

### Where the font came from, and when
  > For example:
  >   Site: https://www.google.com/get/noto/
  >   Date: 2018-08-30

### Font Version
  > Tried different versions, all with the same problem

### OS name and version
  > Windows 10

### Application name and version
  > Notepad

### Issue
  > Noto Sans and Noto Serif are not showing character sets like Central European, Western, etc. in programs, only showing "Other".
This means Noto Sans and Noto Serif cannot be used in programs which request a certain character set (ie. Western). 

  1. Steps to reproduce
        1. Install font
        2. Open Notepad and go to Format -> Font...
        3. Check which Scripts are available (see screenshot below).
  2. Observed results
        1. The only script available is "Other"
  3. Expected results
        1. Available scripts should be "Central European, Western, Greek, Turkish, Baltic, ..." 
  4. Additional information 
Confirmed on multiple computers all running Windows 10.

### Screenshot
  > Noto Sans in Notepad Font dialog:
![image](https://user-images.githubusercontent.com/5932690/44842565-85f64e80-ac46-11e8-92d4-d6db40e0fd72.png)
  > Arial in Notepad Font dialog (this is what it should be):
![image](https://user-images.githubusercontent.com/5932690/44842601-9a3a4b80-ac46-11e8-9ba5-c7e997037b3b.png)

### Interesting exception
  > Noto Mono works as expected (shows all the character sets, same as Arial).

**Comment by nizarsq** [comment]
@mohorko could you share characters data you are having issue with. Thank you

**Comment by mohorko** [comment]
> @mohorko could you share characters data you are having issue with. Thank you

It's been 2 years since I posted this and have since moved on to using other fonts. I'm not sure what you mean by "share characters data" ... I think the post is pretty self-explanatory. The actuall charaters which are problematic for my use case are "ščžŠČŽ", but it's quite possible that there are other issues for other users.

**Comment by moyogo** [comment]
Confirmed as fixed. Notepad shows multiple scripts. This was fixed when fontmake was updated to the version that write OS/2 code page ranges.
![VirtualBox_WinDev2102Eval_11_04_2021_05_46_54](https://user-images.githubusercontent.com/1923747/114292867-91aa8280-9a89-11eb-895d-7b7d5408e147.png)
![VirtualBox_WinDev2102Eval_11_04_2021_05_47_20](https://user-images.githubusercontent.com/1923747/114292868-92431900-9a89-11eb-8711-664ec3f4eb64.png)
