### ISSUE TITLE
No transitive mirroring in ’Phags-pa

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1275]
### Font
NotoSansPhagsPa-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansPhagsPa-unhinted.zip
Date: 2018-09-01

### Font version
Version 1.03 uh

### Issue
> When any of the letters <i>small a</i>, <i>i</i>, <i>u</i>, <i>e</i>, <i>ha</i>, or <i>subjoined ya</i> immediately follow either <i>tta</i>, <i>ttha</i>, <i>dda</i>, or <i>nna</i> directly or another mirrored letter, then a mirrored glyph form of the letter should be selected automatically by the rendering system.

— [<i>The Unicode Standard</i> 11.0, ch. 14](https://www.unicode.org/versions/Unicode11.0.0/ch14.pdf#page=21)

This font does not select mirrored glyphs after other mirrored glyphs.

### Character data
ꡩꡟꡟ
U+A869 PHAGS-PA LETTER TTA
U+A85F PHAGS-PA LETTER U
U+A85F PHAGS-PA LETTER U

### Screenshot
![ꡩꡟꡟ](https://user-images.githubusercontent.com/1124347/44949427-08297300-adff-11e8-8c18-db6ecdd70d71.png)

**Comment by simoncozens** [comment]
Oh, this was a journey. Because PhagsPa is now sent through the USE, and mirroring was being done via ccmp, all the mirroring broke since this was reported (see #2281). Moving the feature code into ltrm seems to do the right thing.
