### ISSUE TITLE
U+1D24 ᴤ has incorrect shape in Noto Sans, Noto Sans Mono and Noto Serif

### ISSUE THREAD

**Issue by moyogo** [googlefonts/noto-fonts#1279]
### Font 
NotoSans-*.ttf, NotoSerif-*.ttf, NotoSansMono-*.ttf

### Where the font came from, and when
noto-fonts repository

### Font Version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+1D24 ᴤ should be shaped as in [Antti Sovijärvi and Reino Peltola, *Suomalais-ugrilainen tarkekirjoitus*, 1970](https://helda.helsinki.fi/handle/10224/4089) or as in the [Unicode Phonetic Extensions chart](https://www.unicode.org/charts/PDF/U1D00.pdf). That is, with ascender height and shaped as two top halves of ʔ put together, one on top and one rotated 180 degree at the bottom.

Instead of having it with ascender height, all the Latin Noto fonts incorrectly have it as tall as x-height and, additionally, the Latin italic Noto Sans and Noto Serif incorrectly have it just as a reversed s (or U+01A8 LATIN SMALL LETTER TONE TWO ƨ).

See Sovijärvi and Peltola 1970, page 4, showing the italic form of ᴤ, clearly with ascender height:
![capture d ecran 2018-09-05 a 06 03 48](https://user-images.githubusercontent.com/1923747/45072141-7ad17180-b0d1-11e8-89c1-8d9bf4887876.png)

See Unicode Phonetic Extensions chart, showing the roman form of ᴤ, clearly with ascender height:
![capture d ecran 2018-09-05 a 06 02 46](https://user-images.githubusercontent.com/1923747/45072179-b79d6880-b0d1-11e8-8f81-8889c4ce866e.png)

### Screenshot
See incorrect shapes of ᴤ in the string ᴤʔ (with ʔ for ascender height reference) in Noto Sans (Regular and Italic), Noto Serif (Regular and Italic), Noto Sans Mono (Regular and Italic):
![capture d ecran 2018-09-05 a 06 00 08](https://user-images.githubusercontent.com/1923747/45072327-6772d600-b0d2-11e8-9b5f-cdd49a573e29.png)

Compare with correct shapes for ᴤ in the string ᴤʔ (with ʔ for ascender height reference) in Brill:
![capture d ecran 2018-09-05 a 06 10 47](https://user-images.githubusercontent.com/1923747/45072370-96894780-b0d2-11e8-99e5-ba2556e8de51.png)

**Comment by nizarsq** [comment]
Current rendering @moyogo any thoughts?
<img width="582" alt="Screen Shot 2020-07-06 at 11 40 40 AM" src="https://user-images.githubusercontent.com/22158882/86627654-86b44600-bf7d-11ea-9ca5-75bd483b7e80.png">

**Comment by moyogo** [comment]
@nizarsq Great! That looks good to me. :-)

**Comment by nizarsq** [comment]
> @nizarsq Great! That looks good to me. :-)

Amazing! Thanks
