### ISSUE TITLE
Noto Naskh importnant issue in Chrome "Only!"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#128]
```
I installed Noto Naskh in a magazine website and I noticed that it has an issue 
with Google Chrome only!

If you write مبدئي، رئيس the word break in GC (Win)...

You can see the attached files...

In Mac All letters are broken... No issues in other browsers...

What version of the product are you using? 
The last one, downloaded last week

On what operating system? Win & Mac


Please provide any additional information below.


```

Original issue reported on code.google.com by `oussama....@gmail.com` on 11 Aug 2014 at 5:58

Attachments:
- [Capture-GC.PNG](https://storage.googleapis.com/google-code-attachments/noto/issue-128/comment-0/Capture-GC.PNG)
- [Capture-FF.PNG](https://storage.googleapis.com/google-code-attachments/noto/issue-128/comment-0/Capture-FF.PNG)

**Comment by behdad** [comment]
cc @jungshik @behdad

**Comment by behdad** [comment]
cc @davelab6 @kuettel
