### ISSUE TITLE
Broken connecting stroke before reversed ’Phags-pa letters

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1283]
### Font
NotoSansPhagsPa-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansPhagsPa-unhinted.zip
Date: 2018-09-01

### Font version
Version 1.03 uh

### Issue
When U+A85E, U+A85F, U+A860, and U+A868 are reversed by a following VS1, the stroke connecting them to the previous letter is on the wrong side. Only [the syllable <i>ṭhi</i>](https://www.unicode.org/wg2/docs/n2719.pdf#page=11) is attested with reversed shaping among those I am reporting, but the same discontinuity in the connecting stroke appears in other combinations in this font and should probably be fixed too. I use <i>ṭha</i> and <i>tha</i> in the examples below, but this theoretically applies to all letters.

### Character data
ꡪꡞ︀ ꡉꡞ︀ ꡪꡟ︀ ꡉꡟ︀ ꡪꡠ︀ ꡉꡠ︀ ꡪꡨ︀ ꡉꡨ︀
One of:
* U+A86A PHAGS-PA LETTER TTHA
* U+A849 PHAGS-PA LETTER THA

Then one of:
* U+A85E PHAGS-PA LETTER I
* U+A85F PHAGS-PA LETTER U
* U+A860 PHAGS-PA LETTER E
* U+A868 PHAGS-PA SUBJOINED LETTER YA

Then:
* U+FE00 VARIATION SELECTOR-1

### Screenshot
![ꡪꡞ︀ ꡉꡞ︀ ꡪꡟ︀ ꡉꡟ︀ ꡪꡠ︀ ꡉꡠ︀ ꡪꡨ︀ ꡉꡨ︀](https://user-images.githubusercontent.com/1124347/45226135-1c9cbe00-b28c-11e8-8262-438413bdb9b3.png)

**Comment by simoncozens** [comment]
I'm going to fix this for TTHA + vowel, since that's attested, but not for anything else since it requires drawing.
