### ISSUE TITLE
Wrong glyph for U+1F7C8 REVERSE LIGHT FOUR POINTED PINWHEEL STAR

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1286]
### Font
NotoSansSymbols2-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansSymbols2-unhinted.zip
Date: 2018-04-03

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
The glyph of U+1F7C8 REVERSE LIGHT FOUR POINTED PINWHEEL STAR is not light. It should look like a reverse pinwheel version of U+1F7C4 LIGHT FOUR POINTED BLACK STAR, not a reversed version of U+1F7C7 MEDIUM FOUR POINTED PINWHEEL STAR.

### Character data
🟄🟈🟇
U+1F7C4 LIGHT FOUR POINTED BLACK STAR
U+1F7C8 REVERSE LIGHT FOUR POINTED PINWHEEL STAR
U+1F7C7 MEDIUM FOUR POINTED PINWHEEL STAR

### Screenshot
![🟄🟈🟇](https://user-images.githubusercontent.com/1124347/45317826-1ff0ad80-b509-11e8-9dd0-17cea72e037a.png)

**Comment by nizarsq** [comment]
This issue fixed, U+1F7C8 REVERSE LIGHT FOUR POINTED PINWHEEL STAR look like a reverse pinwheel version of U+1F7C4. 
<img width="1046" alt="Screen Shot 2020-07-24 at 10 51 55 PM" src="https://user-images.githubusercontent.com/22158882/88449995-46b7e480-ce00-11ea-94e7-06d479b6fedd.png">
.
