### ISSUE TITLE
Misplaced pairs of Miao vowel signs

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1288]
### Font
NotoSansMiao-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/db5c897c3954ab8dd49bfc3de4f3ef00a7ef6d06/phaseIII_only/hinted/ttf/NotoSansMiao/NotoSansMiao-Regular.ttf
Date: 2018-09-11

### Font version
Version 2.000

### Issue
Pairs of vowel signs are not centered above or below consonants, and so the second protrudes far into the following consonant’s space. See [figures 4 and 5 of L2/10-093](https://www.unicode.org/L2/L2010/10093-n3789-miao.pdf#page=10).

### Character data
𖼐𖽡𖽻𖾑𖼞𖽪𖽝𖾒
𖼐 U+16F10 MIAO LETTER NA
𖽡 U+16F61 MIAO VOWEL SIGN I
𖽻 U+16F7B MIAO VOWEL SIGN AU
𖾑 U+16F91 MIAO TONE ABOVE
𖼞 U+16F1E MIAO LETTER KA
𖽪 U+16F6A MIAO VOWEL SIGN U
𖽝 U+16F5D MIAO VOWEL SIGN E
𖾒 U+16F92 MIAO TONE BELOW

### Screenshot
![𖼐𖽡𖽻𖾑𖼞𖽪𖽝𖾒](https://user-images.githubusercontent.com/1124347/45383286-c8217780-b5d8-11e8-9e75-fb568c9ad1cb.png)

**Comment by cheuk879** [comment]
Version 2.001 (Revision 2.00101, last modified 2021-02-28) shows correct vowel centring, though the last vowel should really be much narrower:
![plrd-noto-vcentring](https://user-images.githubusercontent.com/10625598/109540171-5aef4e80-7a7f-11eb-8749-1befd8675747.png)
Pls. verify & close issue.

**Comment by moyogo** [comment]
Confirmed as fixed, the first vowel is now shifted left with the kern feature when followed by another vowel.
<img width="263" alt="image" src="https://user-images.githubusercontent.com/1923747/113011224-7e3a1600-9171-11eb-99d3-747526476985.png">

The design of U+16F5D MIAO VOWEL SIGN E could be narrower as well. It doesn't look as wide in SIL fonts but still slightly extending outiside the base letter width:
<img width="125" alt="image" src="https://user-images.githubusercontent.com/1923747/113011884-23ed8500-9172-11eb-810e-569b088fc6f0.png">

I'll close this. We can have another issue with the design of U+16F5D MIAO VOWEL SIGN E needs to be adjusted.
