### ISSUE TITLE
Inappropriately reversed mathematical tildes

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1289]
### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/db5c897c3954ab8dd49bfc3de4f3ef00a7ef6d06/phaseIII_only/unhinted/ttf/NotoSansMath/NotoSansMath-Regular.ttf
Date: 2018-09-12

### Font version
Version 1.900

### Issue
Some glyphs have reversed tildes that shouldn’t.

### Character data
≂≿⩳⭉
U+2242 MINUS TILDE
U+227F SUCCEEDS OR EQUIVALENT TO
U+2A73 EQUALS SIGN ABOVE TILDE OPERATOR
U+2B49 TILDE OPERATOR ABOVE LEFTWARDS ARROW

### Screenshot
![≂≿⩳⭉](https://user-images.githubusercontent.com/1124347/45428668-b4752000-b66f-11e8-9663-964dbd670e0a.png)

**Comment by marekjez86** [comment]
2.0 version is as follows
![math-1289-b](https://user-images.githubusercontent.com/13322623/52678608-1bc92180-2ee7-11e9-8b87-1595e763a795.jpeg)

**Comment by dscorbett** [comment]
Yes, they should all use the normal tilde. The glyph of U+2B49 is now correct.

**Comment by marekjez86** [comment]
per MT fixed

<img width="423" alt="Screen Shot 2019-05-17 at 20 43 56" src="https://user-images.githubusercontent.com/13322623/57964112-8cb41700-78e4-11e9-8677-4823e6b7efef.png">
