### ISSUE TITLE
Wrong glyph for U+27D4 UPPER LEFT CORNER WITH DOT

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1290]
### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/db5c897c3954ab8dd49bfc3de4f3ef00a7ef6d06/phaseIII_only/unhinted/ttf/NotoSansMath/NotoSansMath-Regular.ttf
Date: 2018-09-12

### Font version
Version 1.900

### Issue
The glyph of U+27D4 UPPER LEFT CORNER WITH DOT is a lower left corner with a dot.

### Character data
⟔
U+27D4 UPPER LEFT CORNER WITH DOT

### Screenshot
![⟔](https://user-images.githubusercontent.com/1124347/45492682-f0c18280-b73a-11e8-8e20-52eac5b0a646.png)

**Comment by marekjez86** [comment]
Version 2.0 has

![math-1290](https://user-images.githubusercontent.com/13322623/52678975-541d2f80-2ee8-11e9-8d09-bbcd2eb17933.jpeg)

It appears to be the lower left corner with dot (unchanged). Question for @waksmonskiMT : Do we have the same issue with lowerRightCornerWithDot.mir (I think it is meant to be for RTL systems)?

**Comment by marekjez86** [comment]
with https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansMath/NotoSansMath-Regular.otf

<img width="242" alt="Screen Shot 2019-05-17 at 19 47 45" src="https://user-images.githubusercontent.com/13322623/57963679-b701d680-78dc-11e9-9c09-2d8d5a55b0fc.png">
