### ISSUE TITLE
Noto Serif Kannada defect with nukta

### ISSUE THREAD

**Issue by MayuraVerma** [googlefonts/noto-fonts#1293]
### Title 
  > Noto Serif Kannada defect with nukta

### Font 
  > NotoSerifKannada-Regular.ttf

### Where the font came from, and when
  > https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSerifKannada

### Font Version
  > 2.001

### OS name and version
  > Windows 7 SP1

### Application name and version
  > MS Word 2016, version 16.0.6965.2117

### Issue
  >  ಫ಼ಾ (U+0CAB U+0CBC U+0CBE) and  ಫ಼ೌ (U+0CAB U+0CBC U+0CCC) are broken in Noto Serif Kannada

### Character data
  > test for all typical data

ಫ಼ | ಫ಼ಾ | ಫ಼ಿ | ಫ಼ೀ | ಫ಼ು | ಫ಼ೂ | ಫ಼ೃ | ಫ಼ೄ | ಫ಼ೆ | ಫ಼ೇ | ಫ಼ೈ | ಫ಼ೊ | ಫ಼ೋ | ಫ಼ೌ
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ಜ಼ | ಜ಼ಾ | ಜ಼ಿ | ಜ಼ೀ | ಜ಼ು | ಜ಼ೂ | ಜ಼ೃ | ಜ಼ೄ | ಜ಼ೆ | ಜ಼ೇ | ಜ಼ೈ | ಜ಼ೊ | ಜ಼ೋ | ಜ಼ೌ

### Screenshot
![image](https://user-images.githubusercontent.com/14062593/45558503-b375f700-b805-11e8-809a-f84bda73af53.png)

**Comment by MayuraVerma** [comment]
This is still unresolved in newer build Noto Serif Kannada V2.001.

**Comment by nizarsq** [comment]
I can't reproduce this issue on Windows 10, renderings looks ok. Please reopen if you still have this issue.
