### ISSUE TITLE
U+27CE and U+27CF are swapped

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1296]
### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/db5c897c3954ab8dd49bfc3de4f3ef00a7ef6d06/phaseIII_only/unhinted/ttf/NotoSansMath/NotoSansMath-Regular.ttf
Date: 2018-09-12

### Font version
Version 1.900

### Issue
The glyphs of U+27CE SQUARED LOGICAL AND and U+27CF SQUARED LOGICAL OR are swapped.

### Character data
⟎⟏
U+27CE SQUARED LOGICAL AND
U+27CF SQUARED LOGICAL OR

### Screenshot
![⟎⟏](https://user-images.githubusercontent.com/1124347/45604590-d79f2700-ba03-11e8-9776-55993ae69a2e.png)

**Comment by marekjez86** [comment]
Version 2.0 has

![math-1296](https://user-images.githubusercontent.com/13322623/52679774-0655f680-2eeb-11e9-970e-eaefe48a2d09.jpeg)


See 2227 for the correct "logical and", 2227 for "logical or" surround them with squares and you'll get the right symbols

**Comment by marekjez86** [comment]
with https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansMath/NotoSansMath-Regular.otf

<img width="362" alt="Screen Shot 2019-05-17 at 19 44 46" src="https://user-images.githubusercontent.com/13322623/57963652-4a86d780-78dc-11e9-9cd1-d49052a7aa62.png">
