### ISSUE TITLE
Inconsistent glyph for U+2A88 GREATER-THAN AND SINGLE-LINE NOT EQUAL TO

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1298]
### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/db5c897c3954ab8dd49bfc3de4f3ef00a7ef6d06/phaseIII_only/unhinted/ttf/NotoSansMath/NotoSansMath-Regular.ttf
Date: 2018-09-12

### Font version
Version 1.900

### Issue
The inequality stroke of U+2A88 GREATER-THAN AND SINGLE-LINE NOT EQUAL TO is reversed from how it looks on the other glyphs with inequality strokes on their bottom members.

### Character data
⪈
U+2A88 GREATER-THAN AND SINGLE-LINE NOT EQUAL TO

### Screenshot
![⪈](https://user-images.githubusercontent.com/1124347/45702263-5e0c5380-bb3f-11e8-9b14-0ab236374583.png)

**Comment by marekjez86** [comment]
![math-1298](https://user-images.githubusercontent.com/13322623/52679992-c6434380-2eeb-11e9-8c8f-ade9dc31ef33.jpeg)

**Comment by marekjez86** [comment]
@waksmonskiMT : if this is changed then also greaterThanAndSingleLineNotEqualTo.mir needs to change also

What was the design reason to have different strokes for some of the glyphs?

**Comment by marekjez86** [comment]
per MT fixed

**Comment by marekjez86** [comment]
<img width="420" alt="Screen Shot 2019-05-17 at 21 13 43" src="https://user-images.githubusercontent.com/13322623/57964336-bcfdb480-78e8-11e9-93be-d40b273ac2d8.png">
