### ISSUE TITLE
Wrong glyph for U+1EE7E ARABIC MATHEMATICAL STRETCHED DOTLESS FEH

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1300]
### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/db5c897c3954ab8dd49bfc3de4f3ef00a7ef6d06/phaseIII_only/unhinted/ttf/NotoSansMath/NotoSansMath-Regular.ttf
Date: 2018-09-12

### Font version
Version 1.900

### Issue
The glyph of U+1EE7E ARABIC MATHEMATICAL STRETCHED DOTLESS FEH has a dot.

### Character data
𞹾
U+1EE7E ARABIC MATHEMATICAL STRETCHED DOTLESS FEH

### Screenshot
![𞹾](https://user-images.githubusercontent.com/1124347/45821660-bd8d6f00-bcb7-11e8-9a7c-10e88edec0c4.png)

**Comment by marekjez86** [comment]
now it is unchanged

![math-1300](https://user-images.githubusercontent.com/13322623/52680699-47033f00-2eee-11e9-8b46-67b16212352f.jpeg)

**Comment by marekjez86** [comment]
with https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansMath/NotoSansMath-Regular.otf

<img width="1135" alt="Screen Shot 2019-05-17 at 19 30 09" src="https://user-images.githubusercontent.com/13322623/57963529-393ccb80-78da-11e9-8831-1a850b83fcf8.png">
