### ISSUE TITLE
Miao tone shifters should have spacing glyphs

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1302]
### Font
NotoSansMiao-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/db5c897c3954ab8dd49bfc3de4f3ef00a7ef6d06/phaseIII_only/hinted/ttf/NotoSansMiao/NotoSansMiao-Regular.ttf
Date: 2018-09-11

### Font version
Version 2.000

### Issue
The four Miao tone shifters should have base glyphs instead of mark glyphs. Currently, they are all 834 em units wide, but each overlaps the following glyph because the shaper cancels the width of mark glyphs. This only makes a difference in the unusual case that a tone shifter does not follow a vowel.

### Character data
𖼀𖾏𖼚
U+16F00 MIAO LETTER PA
U+16F8F MIAO TONE RIGHT
U+16F1A MIAO LETTER TLHA

### Screenshot
![𖼀𖾏𖼚](https://user-images.githubusercontent.com/1124347/45917741-0d03a480-be4a-11e8-879c-217a8d5acdf6.png)

**Comment by cheuk879** [comment]
Version 2.001 (Revision 2.00101, last modified 2020-12-25) does not show this behaviour:
![plrd-hmd-toneshifterglyphs](https://user-images.githubusercontent.com/10625598/104764023-05a3eb80-5724-11eb-88f7-7a8e8ad501a7.png)

**Comment by cheuk879** [comment]
Same correct result for the latest build (2021-02-28).  Pls. verify & close issue.

**Comment by moyogo** [comment]
Confirmed as fixed. Thank you @dscorbett and @cheuk879.
