### ISSUE TITLE
Southeast Asian Script Support in Noto Sans Mono?

### ISSUE THREAD

**Issue by jeffmcneill** [googlefonts/noto-fonts#1303]
Is Southeast Asian script support on the roadmap for Noto Sans Mono? In particular Thai, but also Lao and Burmese?

**Comment by marekjez86** [comment]
@jeffmcneill : No. At this point only Noto Sans Mono is published. However, we'll keep your request in mind for the future planning. What would you want to do with it?

**Comment by marekjez86** [comment]
We have no plans for these (unfortunately)
