### ISSUE TITLE
Visible and printable characters for line breaks and page breaks in Apple Pages with Noto Serif

### ISSUE THREAD

**Issue by einemarc** [googlefonts/noto-fonts#1305]
When I add a line break or page break in Apple Pages while using Noto Serif, a character is added at the end of the paragraph, respectively. The character for a line break is displayed in an empty paragraph (see below) while the one for a page break is not. Both characters are not just visible when editing the document but also when printing it or exporting it to PDF. It is the case with all styles of Noto Serif. However, it does not happen with Noto Sans and Noto Mono (see below).

The characters are:
<img width="600" alt="apple pages line break and page break" src="https://user-images.githubusercontent.com/29229924/45935233-a85f5b80-bfa9-11e8-94ba-55446cf229c8.png">

Packages for Noto Serif, Noto Sans and Noto Mono were downloaded on 2018-09-21 from the official Google website (google.com/get/noto). The version of NotoSerif-Regular.ttf is "2.000;GOOG;noto-source:20170915:90ef993387c0". macOS version is 10.13.6. Apple Pages version is 7.2 (5869).

**Comment by marekjez86** [comment]
@einemarc : could you try with one of the font weights in https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSerif and let me know what you see?

**Comment by einemarc** [comment]
@marekjez86 : Tried. As far as I can tell, the behavior is exactly the same.

**Comment by aourednik** [comment]
I confirm this behaviour for PowerPoint on MacOS. I'm not shure whether it is a page break, perhaps rather a new line (LF = \n = \u000A), as opposed to new paragraph (CR = \r = \u000D). In any case, the above illustrated L SEP box appears instead of the expected, invisible line break (produced with Ctrl-Return).

**Comment by nizarsq** [comment]
@einemarc @aourednik can you check if this behavior fixed in the current Noto Serif, you can get the latest version from https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSerif. Thanks

**Comment by einemarc** [comment]
@nizarsq: I am not able to reproduce the behaviour with the current version of Note Serif. It seems to be fixed. Thanks.

**Comment by nizarsq** [comment]
> @nizarsq: I am not able to reproduce the behaviour with the current version of Noto Serif. It seems to be fixed. Thanks.

Amazing! Thanks @einemarc.
