### ISSUE TITLE
Warang Citi letters shrink before ZWJ regardless of context

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1308]
### Font
NotoSansWarangCiti-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/cacbdb4e73916a4e929569e3368a26240ae9a9e8/phaseIII_only/unhinted/otf/NotoSansWarangCiti/NotoSansWarangCiti-Regular.otf
Date: 2018-09-24

### Font version
Version 2.000; ttfautohint (v1.8.2)

### Issue
In Warang Citi, two letters joined by a ZWJ are written stacked, with the second above the first, and both letters’ glyphs diminished so they fit within a line. In this font, any letter before a ZWJ is diminished, even if no letter follows the ZWJ. It should take context into account, and if it cannot form a stack, the font should ignore the ZWJ.

### Character data
𑢪𑣿𑢪‍𑣿
U+118AA WARANG CITI CAPITAL LETTER ANG
U+118FF WARANG CITI OM
U+118AA WARANG CITI CAPITAL LETTER ANG
U+200D ZERO WIDTH JOINER
U+118FF WARANG CITI OM

### Screenshot
![𑢪𑣿𑢪‍𑣿](https://user-images.githubusercontent.com/1124347/46018221-5d2b7280-c0a7-11e8-985c-515aac1336c6.png)

**Comment by sridatta1** [comment]
Wrong label, please change it to label:Script-WarangCiti @marekjez86

**Comment by marekjez86** [comment]
@dscorbett , @sridatta1 : what confused me is statement that  this was from NotoSansMultani-Regular.ttf font (I wasn't certain what to believe)
