### ISSUE TITLE
Consonant+ virama doesn't take vedic marks in Grantha

### ISSUE THREAD

**Issue by sridatta1** [googlefonts/noto-fonts#1319]
### Title 
  >Consonant+ virama doesn't take vedic marks in Grantha

### Font 
  > NotoSansGrantha-Regular.ttf

### Where the font came from, and when
  > Site: https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansGrantha
Date: 2018-09-30
### Font Version
  > 2.000

### Issue
  > Consonant+ virama doesn't take vedic marks in Grantha, throws dotted circles
 
  2. Observed results
![granthatest](https://user-images.githubusercontent.com/23263723/46415706-76858c00-c743-11e8-8b57-5958959a5e9e.png)

  3. Expected results
![image](https://user-images.githubusercontent.com/23263723/46415724-82714e00-c743-11e8-8989-0cc9cb399039.png)
  
### Character data
 ‎11328 GRANTHA LETTER NA
 ‎11348 GRANTHA VOWEL SIGN AI
" ‎11330 GRANTHA LETTER RA
 ‎1134D GRANTHA SIGN VIRAMA
 ‎1CF4 VEDIC TONE CANDRA ABOVE
 ‎1130B GRANTHA LETTER VOCALIC R "
 ‎0952 DEVANAGARI STRESS SIGN ANUDATTA
 ‎11324 GRANTHA LETTER TA
 ‎1133E GRANTHA VOWEL SIGN AA
 ‎11303 GRANTHA SIGN VISARGA
𑌨𑍈𑌰𑍍᳴𑌋॒𑌤𑌾𑌃

**Comment by punchcutter** [comment]
This is a shaper issue. USE shaping cluster validation doesn't allow this sequence, but once that is changed the font will work. If you know of other virama terminated clusters in other scripts that can be followed by Vedic marks or something similar please make a note here.

**Comment by punchcutter** [comment]
Because of this update https://github.com/harfbuzz/harfbuzz/commit/75114e01d29b90f72a9398ed5dbc4298aba5a6b8 for Tamil Brahmi we might be able to change the USE category of the Grantha Virama as well. Then it would allow Vedic marks. I updated harbuzz locally and it fixes this issue, but there could be other unintended consequences. 
Also, the GPOS will need some updates to make sure any Vedic marks don't conflict with the explicit virama.

**Comment by sridatta1** [comment]
Closing this issue as the I see it being fixed in the latest font https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/ttf/NotoSansGrantha/NotoSansGrantha-Regular.ttf
![image](https://user-images.githubusercontent.com/23263723/85044557-69286380-b1ab-11ea-85f9-587f87ee4933.png)
