### ISSUE TITLE
letters are clashing for certain syllable sequences in Grantha

### ISSUE THREAD

**Issue by sridatta1** [googlefonts/noto-fonts#1325]
### Title 
  >letters are clashing for certain syllable sequences in Grantha

### Font 
  > NotoSansGrantha-Regular.ttf

### Where the font came from, and when
  > Site: https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansGrantha
Date: 2018-09-30
### Font Version
  > 2.000

### Issue
  > In the word gimhassa( a Prakrit word) the below-vase form of sa in the cluster ssa is clashing with the below-base form of ha of the mha cluster, the may be many more such cases in real language words, and theoretical sequences.

![image](https://user-images.githubusercontent.com/23263723/46573031-214cb300-c9ad-11e8-9f44-e865996ff22d.png)
![image](https://user-images.githubusercontent.com/23263723/46573048-2d387500-c9ad-11e8-9f05-c9253ee944b3.png)
![image](https://user-images.githubusercontent.com/23263723/46573062-3c1f2780-c9ad-11e8-9694-f6ef81115421.png)

### Character data
  >  ‎1132E GRANTHA LETTER MA
 ‎1134D GRANTHA SIGN VIRAMA
 ‎11339 GRANTHA LETTER HA
 ‎11338 GRANTHA LETTER SA
 ‎1134D GRANTHA SIGN VIRAMA
 ‎11338 GRANTHA LETTER SA
𑌮𑍍𑌹𑌸𑍍𑌸

**Comment by dscorbett** [comment]
Here is another such sequence.
𑌜𑍍𑌜‍𑍍𑌞𑌞𑍍𑌞
U+1131C GRANTHA LETTER JA
U+1134D GRANTHA SIGN VIRAMA
U+1131C GRANTHA LETTER JA
U+200D ZERO WIDTH JOINER
U+1134D GRANTHA SIGN VIRAMA
U+1131E GRANTHA LETTER NYA
U+1131E GRANTHA LETTER NYA
U+1134D GRANTHA SIGN VIRAMA
U+1131E GRANTHA LETTER NYA
![𑌜𑍍𑌜‍𑍍𑌞𑌞𑍍𑌞](https://user-images.githubusercontent.com/1124347/46691097-0ad37100-cbd2-11e8-8fd2-afb75896cf4a.png)

**Comment by sridatta1** [comment]
Closing the issue as I see it is fixed
![image](https://user-images.githubusercontent.com/23263723/120221306-ce118800-c25b-11eb-83b5-df1bb81dbf69.png)
