### ISSUE TITLE
Missing Vedic characters for Tirhuta

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1329]
### Font
NotoSansTirhuta-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/b20c9c07139b22eb38013b1f80f9a5222c6058c6/phaseIII_only/hinted/ttf/NotoSansTirhuta/NotoSansTirhuta-Regular.ttf
Date: 2018-10-09

### Font version
Version 2.000; ttfautohint (v1.8.2)

### Issue
According to [L2/17-098](https://www.unicode.org/L2/L2017/17098-editorial-indic-updates.pdf#page=12), Tirhuta uses U+0951 DEVANAGARI STRESS SIGN UDATTA and U+0952 DEVANAGARI STRESS SIGN ANUDATTA, which this font does not support.

**Comment by marekjez86** [comment]
Build https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansTirhuta/NotoSansTirhuta-Regular.otf (and corresponding TTF file) fixes the issue.
