### ISSUE TITLE
Overlapping Tibetan vowel signs

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1337]
### Font
NotoSerifTibetan-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/b20c9c07139b22eb38013b1f80f9a5222c6058c6/phaseIII_only/unhinted/otf/NotoSerifTibetan/NotoSerifTibetan-Regular.otf
Date: 2018-10-12

### Font version
Version 2.000

### Issue
When wide vowel signs appear on adjacent clusters, they take alternative narrow forms to avoid overlapping. This substitution fails if the first cluster has a vowel modifier.

### Character data
ཀོཀོ
U+0F40 TIBETAN LETTER KA
U+0F7C TIBETAN VOWEL SIGN O
U+0F40 TIBETAN LETTER KA
U+0F7C TIBETAN VOWEL SIGN O
ཀོྃཀོ
U+0F40 TIBETAN LETTER KA
U+0F7C TIBETAN VOWEL SIGN O
U+0F83 TIBETAN SIGN SNA LDAN
U+0F40 TIBETAN LETTER KA
U+0F7C TIBETAN VOWEL SIGN O

### Screenshot
![ཀོཀོ ཀོྃཀོ](https://user-images.githubusercontent.com/1124347/46899754-45a10780-ce65-11e8-9c14-8ad7889b19db.png)

**Comment by marekjez86** [comment]
should be fixed in newly updated https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSerifTibetan (and its TTF counterpart)

**Comment by marekjez86** [comment]
[tib-1337-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/3288452/tib-1337-Serif.pdf)
