### ISSUE TITLE
tū isn't correct in Tirhuta

### ISSUE THREAD

**Issue by sridatta1** [googlefonts/noto-fonts#1338]
### Title 
  >tū isn't correct in Tirhuta
### Font 
  > Full file name, for example 

'NotoSansTirhuta-Regular.ttf.
  >

### Where the font came from, and when
  > 
  >   https://github.com/googlei18n/noto-fonts/blob/master/phaseIII_only/hinted/ttf/NotoSansTirhuta/NotoSansTirhuta-Regular.ttf
  >   Date: October 13, 2018

### Font Version
  > 2.000

### Issue
  > By going through the glyph set, the font supports only the contextual forms, consonant clusters etc. which are mentioned in the Unicode proposal. No other sources ( primary sources like manuscripts, primers etc.) seem to consulted/researched. Thus the font is unusable like most other complex historic and minority Indic scripts' Noto fonts. page 5 of the Unicode proposal L2/11-175R mentions some contextual/special forms for  vowel sign UU, but they are just examples not the only forms.
Observed form:
![image](https://user-images.githubusercontent.com/23263723/46907325-70a35e00-cf2e-11e8-8971-98da64a251c5.png)
Correct form from Tirhuta primers.
![image](https://user-images.githubusercontent.com/23263723/46907341-9892c180-cf2e-11e8-818f-77a85e6371bb.png) 
![image](https://user-images.githubusercontent.com/23263723/46907349-b2340900-cf2e-11e8-8706-e19c25de3f34.png)

 

### Character data
  > 𑒞𑒴
U+1149E TIRHUTA LETTER TA
U+114B4 TIRHUTA VOWEL SIGN UU

**Comment by marekjez86** [comment]
<img width="353" alt="Screen Shot 2019-04-23 at 12 07 27" src="https://user-images.githubusercontent.com/13322623/56608780-6ab6c580-65c0-11e9-9a6b-dd64d90f7177.png">

Build https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansTirhuta/NotoSansTirhuta-Regular.otf (and corresponding TTF file) fixes the issue.
