### ISSUE TITLE
Tibetan spacing marks are not spacing

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1339]
### Font
NotoSerifTibetan-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/b20c9c07139b22eb38013b1f80f9a5222c6058c6/phaseIII_only/unhinted/otf/NotoSerifTibetan/NotoSerifTibetan-Regular.otf
Date: 2018-10-12

### Font version
Version 2.000

### Issue
The Tibetan spacing combining marks U+0F3E, U+0F3F, and U+0F7F are not spacing in this font, because they are mark glyphs. They should be base glyphs, or a 'dist' lookup should add width for them.

### Character data
༠༾༶༠༿༶ཧཿ༶
U+0F20 TIBETAN DIGIT ZERO
U+0F3E TIBETAN SIGN YAR TSHES
U+0F36 TIBETAN MARK CARET -DZUD RTAGS BZHI MIG CAN
U+0F20 TIBETAN DIGIT ZERO
U+0F3F TIBETAN SIGN MAR TSHES
U+0F36 TIBETAN MARK CARET -DZUD RTAGS BZHI MIG CAN
U+0F67 TIBETAN LETTER HA
U+0F7F TIBETAN SIGN RNAM BCAD
U+0F36 TIBETAN MARK CARET -DZUD RTAGS BZHI MIG CAN

### Screenshot
![༠༾༶༠༿༶ཧཿ༶](https://user-images.githubusercontent.com/1124347/46910985-f79c0a80-cf1d-11e8-9bd5-ed0fef10cbf7.png)

**Comment by marekjez86** [comment]
should be fixed in newly updated https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSerifTibetan (and its TTF counterpart)

**Comment by marekjez86** [comment]
[tib-1339-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/3288455/tib-1339-Serif.pdf)
