### ISSUE TITLE
Misplaced Tibetan marks U+0F35 and U+0F37

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1343]
### Font
NotoSerifTibetan-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/b20c9c07139b22eb38013b1f80f9a5222c6058c6/phaseIII_only/unhinted/otf/NotoSerifTibetan/NotoSerifTibetan-Regular.otf
Date: 2018-10-12

### Font version
Version 2.000

### Issue
U+0F35 and U+0F37 should combine below. They should not confused with U+0F83 TIBETAN SIGN SNA LDAN and U+0F7E TIBETAN SIGN RJES SU NGA RO.

### Character data
འ༵འ༷
U+0F60 TIBETAN LETTER -A
U+0F35 TIBETAN MARK NGAS BZUNG NYI ZLA
U+0F60 TIBETAN LETTER -A
U+0F37 TIBETAN MARK NGAS BZUNG SGOR RTAGS

### Screenshot
![འ༵འ༷](https://user-images.githubusercontent.com/1124347/46983390-44aee680-d0ae-11e8-8ca4-e941a223bb72.png)

**Comment by marekjez86** [comment]
should be fixed in newly updated https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSerifTibetan (and its TTF counterpart)

**Comment by marekjez86** [comment]
[tib-1343-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/3288459/tib-1343-Serif.pdf)
