### ISSUE TITLE
Misplaced Tibetan astrological signs U+0F18 and U+0F19

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1345]
### Font
NotoSerifTibetan-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/b20c9c07139b22eb38013b1f80f9a5222c6058c6/phaseIII_only/unhinted/otf/NotoSerifTibetan/NotoSerifTibetan-Regular.otf
Date: 2018-10-12

### Font version
Version 2.000

### Issue
The astrological signs U+0F18 and U+0F19 are supposed to combine below [numerals and other characters](https://collab.its.virginia.edu/access/content/group/26a34146-33a6-48ce-001e-f16ce7908a6a/Tibetan%20fonts/Tibetan%20Legacy%20Fonts/Tibetan!.pdf#page=136). The glyph for U+0F18 has no anchor point. The glyphs for numerals have no anchor points. The anchor point for U+0F19 puts it above consonants and above-base vowels.

### Character data
༣༘༣༙ཀ༙ཀི༙
U+0F23 TIBETAN DIGIT THREE
U+0F18 TIBETAN ASTROLOGICAL SIGN -KHYUD PA
U+0F23 TIBETAN DIGIT THREE
U+0F19 TIBETAN ASTROLOGICAL SIGN SDONG TSHUGS
U+0F40 TIBETAN LETTER KA
U+0F19 TIBETAN ASTROLOGICAL SIGN SDONG TSHUGS
U+0F40 TIBETAN LETTER KA
U+0F72 TIBETAN VOWEL SIGN I
U+0F19 TIBETAN ASTROLOGICAL SIGN SDONG TSHUGS

### Screenshot
![༣༘༣༙ཀ༙ཀི༙](https://user-images.githubusercontent.com/1124347/47097534-9d41c900-d1ff-11e8-85b7-2e183441bfc0.png)

**Comment by marekjez86** [comment]
should be fixed in newly updated https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSerifTibetan (and its TTF counterpart)

**Comment by marekjez86** [comment]
[tib-1345-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/3288466/tib-1345-Serif.pdf)
