### ISSUE TITLE
Saltillos in Noto Sans Tai Viet

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1350]
### Font
NotoSansTaiViet-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/dbfc8a1858732279842454cac5da2ea1ff691a24/hinted/NotoSansTaiViet-Regular.ttf
Date: 2018-10-20

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770;ttfautohint (v1.8.2)

### Issue
Noto Sans Tai Viet includes the saltillos, which are not used in the Tai Viet script. [According to SIL](https://help.keyman.com/keyboard/sil_tai_dam_latin/1.4/sil_tai_dam_latin.php), the lowercase saltillo is used in Tai Dam, but only in the Latin-script orthography.

### Character data
Ꞌꞌ
U+A78B LATIN CAPITAL LETTER SALTILLO
U+A78C LATIN SMALL LETTER SALTILLO

### Screenshot
![Ꞌꞌ](https://user-images.githubusercontent.com/1124347/47273675-a2d44180-d566-11e8-9940-6e5ed56375df.png)

**Comment by nizarsq** [comment]
Saltillos exist in NotoSansTaiViet-Regular.ttf
<img width="821" alt="Screen Shot 2020-07-02 at 4 43 14 PM" src="https://user-images.githubusercontent.com/22158882/86417843-21154080-bc83-11ea-9b7c-78fd42f6d397.png">
