### ISSUE TITLE
Noto Nastaliq missing support for U+06C6 and U+065A

### ISSUE THREAD

**Issue by EricEnglert** [googlefonts/noto-fonts#1353]
### Noto Nastaliq missing support for U+06C6 and U+065A
U+06C6 is required for full representation of Kashmiri

### Font 
NotoNastaliq.ttc

### Where the font came from, and when
Preinstalled on macOS
Date: 2017-09-09

### Font Version
13.0d1e2

### OS name and version
macOS 10.13.4 (17E199)

### Issue
Most writers of Kashmiri use U+06C6 'ARABIC LETTER OE' or a combination of U+0648 and U+065A to represent [o]. Both are unsupported in Noto Nastaliq.

This is a small section from a poem (public domain) that shows the character used numerous times, notably in the title:

![img_4542](https://user-images.githubusercontent.com/44006374/47321860-af66a180-d61b-11e8-97d3-0a2f22e3d64d.JPG)

Reproduction of the title in any environment leads to this issue:

![screen shot 2018-10-22 at 4 50 32 pm](https://user-images.githubusercontent.com/44006374/47321846-a249b280-d61b-11e8-9554-163cc52befc0.png)

### Character data
Supporting U+0648 'ARABIC LETTER WAW' and U+065A 'ARABIC VOWEL SIGN SMALL V ABOVE' is the preferred method for input given that Kashmiri speakers generally do not perceive it as a separate letter and the small v above is treated as a diacritic on waw.

**Comment by nizarsq** [comment]
This issue reproducible
<img width="523" alt="Screen Shot 2020-05-21 at 3 44 58 PM" src="https://user-images.githubusercontent.com/22158882/82613525-543fbc80-9b7a-11ea-8983-64de686c7149.png">
<img width="372" alt="Screen Shot 2020-05-21 at 3 45 23 PM" src="https://user-images.githubusercontent.com/22158882/82613531-586bda00-9b7a-11ea-8774-944953ce3096.png">

**Comment by simoncozens** [comment]
This appears to be fixed, at least as of 2.001:
![shape](https://user-images.githubusercontent.com/106728/151338789-a0bad910-5250-469b-90c2-7b16801bd708.png)
