### ISSUE TITLE
Problems with the alternative U+1112B CHAKMA VOWEL SIGN UU

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1354]
### Font
NotoSansChakma-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/dbfc8a1858732279842454cac5da2ea1ff691a24/hinted/NotoSansChakma-Regular.ttf
Date: 2018-10-23

### Font version
Version 2.001;GOOG;noto-source:20181019:f8f3770;ttfautohint (v1.8.2)

### Issue
The alternative form of U+1112B CHAKMA VOWEL SIGN UU is not formed after a subjoined <i>rā</i> and overstrikes other subjoined letters.

### Character data
𑄛𑄳𑄢𑄫𑄛𑄳𑄣𑄫
U+1111B CHAKMA LETTER PAA
U+11133 CHAKMA VIRAMA
U+11122 CHAKMA LETTER RAA
U+1112B CHAKMA VOWEL SIGN UU
U+1111B CHAKMA LETTER PAA
U+11133 CHAKMA VIRAMA
U+11123 CHAKMA LETTER LAA
U+1112B CHAKMA VOWEL SIGN UU

### Screenshot
Default:
![𑄛𑄳𑄢𑄫𑄛𑄳𑄣𑄫](https://user-images.githubusercontent.com/1124347/47381326-c1a11800-d6cd-11e8-84e5-37fdc1142886.png)
With 'ss02' or 'ss03':
![𑄛𑄳𑄢𑄫𑄛𑄳𑄣𑄫](https://user-images.githubusercontent.com/1124347/47381327-c1a11800-d6cd-11e8-8b1f-0d32518e6819.png)

**Comment by Bivuti** [comment]
@dscorbett  I think my RibengUni font solve this issues. Here's the screenshot. I would be happy to test the font. 
Font download link:
https://languagetools-153419.appspot.com/ccp/downloads/

![IMG_20200609_160657](https://user-images.githubusercontent.com/13092086/84135275-98ccc280-aa6b-11ea-9f11-b7fa62b30f31.jpg)

**Comment by punchcutter** [comment]
Addressed in latest update

<img width="106" alt="chakma1354" src="https://user-images.githubusercontent.com/11257204/132978441-b51adcf7-153c-4441-a268-bce7b2669d73.png">

**Comment by marekjez86** [comment]
Source code change https://github.com/googlefonts/noto-source/pull/402 fixed the issue. Please see hinted font at https://github.com/googlefonts/noto-fonts/tree/main/hinted/ttf/NotoSansChakma or unhinted at https://github.com/googlefonts/noto-fonts/tree/main/unhinted/ttf/NotoSansChakma . Thank you @punchcutter
