### ISSUE TITLE
Noto Nastaliq Urdu Kerning Issues in Adobe Applications

### ISSUE THREAD

**Issue by zeerakahmed** [googlefonts/noto-fonts#1356]
NotoNastaliqUrdu-Regular.ttf 
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoNastaliqUrdu-unhinted.zip
Date: 2018-10-23
Version 1.02 uh
macOS 10.13.6 (tested using pre-installed version and fresh install referenced above)
Issue observed with Adobe Illustrator CC 2017

Used in Adobe apps the font displays serious kerning issues causing glyphs to overlap. These are unable to be fixed with kerning or tracking settings in Adobe typesetting options, while other Arabic script fonts appear to render correctly. Text was typed using the world ready composed. Attaching an image typesetting the following text:
ہیپاٹائیٹس سے پاکستان کو بچائے

<img width="412" alt="screen shot 2018-10-23 at 5 58 45 pm" src="https://user-images.githubusercontent.com/1581669/47400987-4d2d9f80-d6f4-11e8-817b-fdf975ec0da0.png">

**Comment by mynaah** [comment]
Hello, did you find a resolution to this problem? Is there another comparable font that I can use that does not have kerning issues? 

Thank you.

**Comment by zeerakahmed** [comment]
Sadly I did not at the time, and am unable to verify at the moment. I eventually used Pixelmator, where the rendering saw no issues. Pixelmator opened .psd files without much (if any) loss of formatting or data. 

You could try Mehr Nastaliq (though that has other issues) or versions of Jameel Noori Nastaliq (which is the most commonly used font).

**Comment by khaledhosny** [comment]
Adobe applications has broken layout engine(s), there is nothing to be done here.

**Comment by simoncozens** [comment]
Yes, unfortunately this is a won't-fix. Adobe Photoshop has moved to using Harfbuzz for its shaping and hopefully the other CC applications will soon. But there's nothing we can do about it.
