### ISSUE TITLE
Missing Runic U+0323 COMBINING DOT BELOW

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1365]
### Font
NotoSansRunic-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/d7af81e614086435102cca95961b141b3530a027/hinted/NotoSansRunic-Regular.ttf
Date: 2018-11-01

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770

### Issue
Noto Sans Runic is missing U+0323 COMBINING DOT BELOW, which Tolkien occasionally used as a doubling mark.

### Character data
ᛒ̣
U+16D2 RUNIC LETTER BERKANAN BEORC BJARKAN B
U+0323 COMBINING DOT BELOW

### Screenshot
![ᛒ̣](https://user-images.githubusercontent.com/1124347/47887605-b1e4aa80-de16-11e8-89c9-8c1a552b53d8.png)

**Comment by simoncozens** [comment]
Tolkien? Seriously? All right, because it's you...

**Comment by dscorbett** [comment]
I consider all of Tolkien’s runic innovations in scope for Unicode because U+16F1..U+16F3 were encoded only because Tolkien used them ([L2/11-096R](https://www.unicode.org/L2/L2011/11096r-n4013r-runic-additions.pdf)).

**Comment by simoncozens** [comment]
Fair enough. I anchored the dots under the strokes of runes based around a downstroke, and centered on the letter for all other runes:
![shape](https://user-images.githubusercontent.com/106728/163809773-c0e97622-fd58-49d7-856c-1322a0dbf773.png)
