### ISSUE TITLE
'dist' in Noto Sans New Tai Lue

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1366]
### Font
NotoSansNewTaiLue-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/d7af81e614086435102cca95961b141b3530a027/hinted/NotoSansNewTaiLue-Regular.ttf
Date: 2018-11-02

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770

### Issue
Noto Sans New Tai Lue uses 'dist' to reorder pre-base vowels, but those vowels have Logical_Order_Exception=Yes and should not be reordered. The bug is mitigated because, at least in HarfBuzz, the default shaper does not enable 'dist'; however, [Microsoft’s documentation](https://docs.microsoft.com/en-us/typography/script-development/standard#positioning-glyphs-with-otls) ambiguously implies that 'dist' should be enabled in the default shaper (see MicrosoftDocs/typography-issues#106). This font will be broken in anything that interprets the spec that way.

### Character data
ᦀᦵᦀ
U+1980 NEW TAI LUE LETTER HIGH QA
U+19B5 NEW TAI LUE VOWEL SIGN E
U+1980 NEW TAI LUE LETTER HIGH QA

### Screenshot
Correct rendering:
![ᦀᦵᦀ](https://user-images.githubusercontent.com/1124347/47936265-7cda6580-deb3-11e8-806a-5b75b1f2a405.png)
Rendering with 'dist':
![ᦀᦵᦀ](https://user-images.githubusercontent.com/1124347/47936266-7cda6580-deb3-11e8-9ac2-f7c6bf4ba21e.png)

**Comment by dscorbett** [comment]
As of version 2.6.1, HarfBuzz enables 'dist' in the default shaper (harfbuzz/harfbuzz#1908).

**Comment by r12a** [comment]
This font is now badly broken.  Here's another example from the name of the script itself.

Correct rendering, using the Nokyung font:
 
![Screenshot 2020-09-02 at 07 32 16](https://user-images.githubusercontent.com/4839211/91940220-05640000-ecef-11ea-9a99-5f6d2f1b172f.png)

Rendering using Noto font:

![Screenshot 2020-09-02 at 07 34 32](https://user-images.githubusercontent.com/4839211/91940255-14e34900-ecef-11ea-8030-9e985ab69043.png)

Any chance this can be fixed?

**Comment by punchcutter** [comment]
Yes, it's is definitely really bad to have this unnecessary reordering here. I removed that code and submitted a PR.
