### ISSUE TITLE
Missing U+1DFB COMBINING DELETION MARK for Newa

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1370]
### Font
NotoSansNewa-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/64f57055a31ee72789437d786e969ded9a1231f9/hinted/NotoSansNewa-Regular.ttf
Date: 2018-11-07

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770

### Issue
Noto Sans Newa does not support U+1DFB COMBINING DELETION MARK, which was encoded for use in Newa. Its Unicode code chart glyph has three strokes whereas its glyphs in various Unicode proposals like [L2/14-253](https://www.unicode.org/L2/L2014/14253-rec.pdf#page=3) have four; I don’t know whether that is significant.

**Comment by marekjez86** [comment]
It should be in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansNewa
