### ISSUE TITLE
Stylistically inconsistent Sharada dandas

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1373]
### Font
NotoSansSharada-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/64f57055a31ee72789437d786e969ded9a1231f9/hinted/NotoSansSharada-Regular.ttf
Date: 2018-11-09

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770

### Issue
The strokes of the Sharada dandas have slanted ends, unlike the other vertical stroke ends in the font. None of the samples in [L2/09-074R2](https://www.unicode.org/L2/L2009/09074r2-n3595-sharada.pdf) show the dandas with distinct ends like this. (Some of them show the dandas with angled ends, like figure 3, but that is a different style of danda than the one used in this font.)

### Character data
𑆱𑇀𑇅𑇆
U+111B1 SHARADA LETTER SA
U+111C0 SHARADA SIGN VIRAMA
U+111C5 SHARADA DANDA
U+111C6 SHARADA DOUBLE DANDA

### Screenshot
![𑆱𑇀𑇅𑇆](https://user-images.githubusercontent.com/1124347/48293847-fee80280-e44e-11e8-85ce-178fb751ccc6.png)

**Comment by marekjez86** [comment]
<MTI (Monotype Inc.) reply> Leave as is. This is a stylistic request, not an error.
