### ISSUE TITLE
Contextually inappropriate Bhaiksuki repha

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1378]
### Font
NotoSansBhaiksuki-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/64f57055a31ee72789437d786e969ded9a1231f9/hinted/NotoSansBhaiksuki-Regular.ttf
Date: 2018-11-11

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770

### Issue
The Bhaiksuki repha is formed even when it is not before a base.

### Character data
𑰨𑰿
U+11C28 BHAIKSUKI LETTER RA
U+11C3F BHAIKSUKI SIGN VIRAMA

### Screenshot
![𑰨𑰿](https://user-images.githubusercontent.com/1124347/48424061-d5b9c180-e72f-11e8-81da-e0eea690491e.png)

**Comment by punchcutter** [comment]
Fixed long ago, got sidetracked and didn't close.
𑰨𑰿
U+11C28 U+11C3F
![1378](https://user-images.githubusercontent.com/11257204/108512090-125bc680-7304-11eb-8e6b-baa50010984b.png)
