### ISSUE TITLE
Overlapping marks on headless Newa consonants

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1379]
### Font
NotoSansNewa-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/64f57055a31ee72789437d786e969ded9a1231f9/hinted/NotoSansNewa-Regular.ttf
Date: 2018-11-07

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770

### Issue
The Newa candrabindu and anusvara overlap the vowel sign <i>au</i> on most consonants without headstrokes, except <i>nya</i>.

### Character data
𑐐𑑁𑑃 𑐐𑑁𑑄 𑐛𑑁𑑃 𑐛𑑁𑑄 𑐞𑑁𑑃 𑐞𑑁𑑄 𑐠𑑁𑑃 𑐠𑑁𑑄 𑐢𑑁𑑃 𑐢𑑁𑑄 𑐱𑑁𑑃 𑐱𑑁𑑄

One of:

* U+11410 NEWA LETTER GA
* U+1141B NEWA LETTER TTHA
* U+1141E NEWA LETTER NNA
* U+11420 NEWA LETTER THA
* U+11422 NEWA LETTER DHA
* U+11431 NEWA LETTER SHA

U+11441 NEWA VOWEL SIGN AU

One of:
* U+11443 NEWA SIGN CANDRABINDU
* U+11444 NEWA SIGN ANUSVARA

### Screenshot
![𑐐𑑁𑑃𑐐𑑁𑑄 𑐛𑑁𑑃𑐛𑑁𑑄 𑐞𑑁𑑃𑐞𑑁𑑄 𑐠𑑁𑑃𑐠𑑁𑑄 𑐢𑑁𑑃𑐢𑑁𑑄 𑐱𑑁𑑃𑐱𑑁𑑄](https://user-images.githubusercontent.com/1124347/48509967-7a1b3100-e820-11e8-84ee-5961f47277cc.png)

**Comment by marekjez86** [comment]
using updated Newa from https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansNewa I get

<img width="1339" alt="Screen Shot 2019-05-16 at 09 54 11" src="https://user-images.githubusercontent.com/13322623/57872911-ad378080-77c1-11e9-9c94-2cf6eab797a5.png">

**Comment by marekjez86** [comment]
appears to be fixed
