### ISSUE TITLE
Truncation of Grantha da with subjoined consonant and post-base ya

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1381]
### Font
NotoSansGrantha-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/64f57055a31ee72789437d786e969ded9a1231f9/hinted/NotoSansGrantha-Regular.ttf
Date: 2018-11-15

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770;ttfautohint (v1.8.2)

### Issue
A <i>da</i> with a wide subjoined consonant and a post-base <i>ya</i> has its horizontal stroke truncated, but there is no need: even without truncation, the <i>da</i> would be farther from the <i>ya</i> with the subjoined consonant than it is without it.

### Character data
𑌦𑍍𑌘𑍍𑌯𑌦𑍍𑌯
U+11326 GRANTHA LETTER DA
U+1134D GRANTHA SIGN VIRAMA
U+11318 GRANTHA LETTER GHA
U+1134D GRANTHA SIGN VIRAMA
U+1132F GRANTHA LETTER YA
U+11326 GRANTHA LETTER DA
U+1134D GRANTHA SIGN VIRAMA
U+1132F GRANTHA LETTER YA

### Screenshot
![𑌦𑍍𑌘𑍍𑌯𑌦𑍍𑌯](https://user-images.githubusercontent.com/1124347/48590538-df008500-e90d-11e8-8e15-451022f83b86.png)

**Comment by simoncozens** [comment]
As of 2.002 (if not before), the da is no longer truncated.
