### ISSUE TITLE
Wrong glyph for italic U+0221 LATIN SMALL LETTER D WITH CURL

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1391]
### Font
NotoSerif-Italic.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/64f57055a31ee72789437d786e969ded9a1231f9/hinted/NotoSerif-Italic.ttf
Date: 2018-11-26

### Font version
Version 2.001;GOOG;noto-source:20181019:f8f3770;ttfautohint (v1.8.2)

### Issue
The italic U+0221 LATIN SMALL LETTER D WITH CURL looks like U+0256 LATIN SMALL LETTER D WITH TAIL.

### Character data
<i>ȡ</i>
U+0221 LATIN SMALL LETTER D WITH CURL

### Screenshot
![ȡ](https://user-images.githubusercontent.com/1124347/49035755-b71de680-f183-11e8-8a49-8ef84fef6a25.png)

**Comment by nizarsq** [comment]
This issue has been resolved
<img width="320" alt="Screen Shot 2020-07-02 at 4 05 09 PM" src="https://user-images.githubusercontent.com/22158882/86416063-cfb68280-bc7d-11ea-90b0-8325810599d6.png">
