### ISSUE TITLE
Wrong glyphs for contour tones and U+AB32 LATIN SMALL LETTER BLACKLETTER E

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1392]
### Font
NotoSerif-Italic.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/64f57055a31ee72789437d786e969ded9a1231f9/hinted/NotoSerif-Italic.ttf
Date: 2018-11-26

### Font version
Version 2.001;GOOG;noto-source:20181019:f8f3770;ttfautohint (v1.8.2)

### Issue
All of the italic glyphs of the contour tones and U+AB32 LATIN SMALL LETTER BLACKLETTER E are off by one: the glyph uniAB32 looks like <U+02E7 U+02E7 U+02E8>, the glyph uni02E7_uni02E7_uni02E8 looks like <U+02E7 U+02E7 U+02E6>, and so on until the glyph uni02E5_uni02E5_uni02E9, which looks like U+AB32.

### Character data
<i>˥˥˩ꬲ˧˧˨</i>
U+02E5 MODIFIER LETTER EXTRA-HIGH TONE BAR
U+02E5 MODIFIER LETTER EXTRA-HIGH TONE BAR
U+02E9 MODIFIER LETTER EXTRA-LOW TONE BAR
U+AB32 LATIN SMALL LETTER BLACKLETTER E
U+02E7 MODIFIER LETTER MID TONE BAR
U+02E7 MODIFIER LETTER MID TONE BAR
U+02E8 MODIFIER LETTER LOW TONE BAR

### Screenshot
![˥˥˩ꬲ˧˧˨](https://user-images.githubusercontent.com/1124347/49095054-a0d06300-f235-11e8-8deb-8a1c57f146b8.png)

**Comment by nizarsq** [comment]
<img width="343" alt="Screen Shot 2020-07-01 at 10 35 33 PM" src="https://user-images.githubusercontent.com/22158882/86320203-2fb01900-bbeb-11ea-8d71-4a5a1d59472e.png">

**Comment by moyogo** [comment]
This is partially fixed, the tone bars have been fixed and the glyph are mapped to the correct characters.

However, there's an issue with U+AB32 ꬲ in NotoSans Italic styles where it is italic in Regular but it is upright in the other italic styles. U+AB32 should be italic in all italic styles.

**Comment by moyogo** [comment]
Actually, to be consistent with U+AB3D ꬽ and U+AB3E ꬾ which are upright in all italic styles, U+AB32 ꬲ should be upright in Noto Sans Italic, instead of italic in the other Noto Sans Italic styles.

**Comment by moyogo** [comment]
Closing as confirmed fix as the issue with U+AB32 ꬲ is better to be followed in "Blackletter letters are not slanted in italic fonts" #1809.
