### ISSUE TITLE
Italic Cyrillic iotified a is in small caps

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1395]
### Font
NotoSans-Italic.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/64f57055a31ee72789437d786e969ded9a1231f9/hinted/NotoSans-Italic.ttf
Date: 2018-11-26

### Font version
Version 2.001;GOOG;noto-source:20181019:f8f3770;ttfautohint (v1.8.2)

### Issue
The italic iotified a looks like it is in small caps.

### Character data
<i>ꙗⷼ</i>
U+A657 CYRILLIC SMALL LETTER IOTIFIED A
U+2DFC COMBINING CYRILLIC LETTER IOTIFIED A

### Screenshot
![ꙗⷼ](https://user-images.githubusercontent.com/1124347/49231033-0c920780-f3bf-11e8-9863-f7df5dd82c07.png)

**Comment by nizarsq** [comment]
This issue fixed. 
<img width="374" alt="Screen Shot 2020-07-02 at 12 42 47 PM" src="https://user-images.githubusercontent.com/22158882/86402940-8c4e1b00-bc61-11ea-825b-837be1e194a0.png">
