### ISSUE TITLE
U+110B1 KAITHI VOWEL SIGN I too wide for three-base conjuncts

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1398]
### Font
NotoSansKaithi-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/85e78f831469323c85847e23f95026c894159135/hinted/NotoSansKaithi-Regular.ttf
Date: 2018-12-02

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770;ttfautohint (v1.8.2)

### Issue
The vowel sign <i>i</i> is too wide on horizontal conjuncts of three consonants.

### Character data
𑂍𑂹𑂞𑂹𑂨𑂱
U+1108D KAITHI LETTER KA
U+110B9 KAITHI SIGN VIRAMA
U+1109E KAITHI LETTER TA
U+110B9 KAITHI SIGN VIRAMA
U+110A8 KAITHI LETTER YA
U+110B1 KAITHI VOWEL SIGN I

### Screenshot
![𑂍𑂹𑂞𑂹𑂨𑂱](https://user-images.githubusercontent.com/1124347/49343875-2725e400-f63e-11e8-8662-8031cc23469c.png)

**Comment by marekjez86** [comment]
should be fixed in OTF: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansKaithi and TTF: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansKaithi
