### ISSUE TITLE
Missing anchor points on Kaithi ksa, tra, and thra

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1399]
### Font
NotoSansKaithi-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/85e78f831469323c85847e23f95026c894159135/hinted/NotoSansKaithi-Regular.ttf
Date: 2018-12-02

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770;ttfautohint (v1.8.2)

### Issue
The Kaithi conjuncts <i>ksa</i>, <i>tra</i>, and <i>thra</i> have no anchor points below, so marks like the vowel sign <i>u</i> are not attached properly to their stems.

### Character data
𑂍𑂹𑂮𑂳
U+1108D KAITHI LETTER KA
U+110B9 KAITHI SIGN VIRAMA
U+110AE KAITHI LETTER SA
U+110B3 KAITHI VOWEL SIGN U
𑂞𑂹𑂩𑂳
U+1109E KAITHI LETTER TA
U+110B9 KAITHI SIGN VIRAMA
U+110A9 KAITHI LETTER RA
U+110B3 KAITHI VOWEL SIGN U
𑂟𑂹𑂩𑂳
U+1109F KAITHI LETTER THA
U+110B9 KAITHI SIGN VIRAMA
U+110A9 KAITHI LETTER RA
U+110B3 KAITHI VOWEL SIGN U

### Screenshot
![𑂍𑂹𑂮𑂳 𑂞𑂹𑂩𑂳 𑂟𑂹𑂩𑂳](https://user-images.githubusercontent.com/1124347/49397249-037ba000-f709-11e8-8142-4b7d060afcdb.png)

**Comment by marekjez86** [comment]
should be fixed in OTF: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansKaithi and TTF: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansKaithi
