### ISSUE TITLE
Overlapping U+114C2 TIRHUTA SIGN VIRAMA

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1403]
### Font
NotoSansTirhuta-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/85e78f831469323c85847e23f95026c894159135/hinted/NotoSansTirhuta-Regular.ttf
Date: 2018-12-05

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770;ttfautohint (v1.8.2)

### Issue
After a dead <i>ta</i>, the virama under the following consonant overlaps a mark below.

### Character data
𑒞𑓂𑒟𑒳
U+1149E TIRHUTA LETTER TA
U+114C2 TIRHUTA SIGN VIRAMA
U+1149F TIRHUTA LETTER THA
U+114B3 TIRHUTA VOWEL SIGN U

### Screenshot
![𑒞𑓂𑒟𑒳](https://user-images.githubusercontent.com/1124347/49547923-1ed5df00-f8b2-11e8-81f5-b031bacdf49f.png)

**Comment by marekjez86** [comment]
<img width="353" alt="Screen Shot 2019-04-23 at 11 45 44" src="https://user-images.githubusercontent.com/13322623/56607464-6f2daf00-65bd-11e9-9b67-cd450bc08925.png">

**Comment by marekjez86** [comment]
Build https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansTirhuta/NotoSansTirhuta-Regular.otf (and corresponding TTF file) fixes the issue.
