### ISSUE TITLE
Unexpected ligatures with spaces in Noto Sans Mono

### ISSUE THREAD

**Issue by colemickens** [googlefonts/noto-fonts#1404]
### Font 
`NotoSansMono-Regular.ttf`

### Where the font came from, and when
from Git(hub): 85e78f831469323c85847e23f95026c894159135

### Font Version
  > * Mac - right mouse click on a font and try Preview to see version info.
  > * Win -- right mouse click on a font (Local Disc > Windows > Fonts) and see version info on Properties.
  > * Linux -- use (Gnome) Font Viewer: open a font and click on Info tab.
not available right now

### OS name and version
NixOS, `nixos-unstable`.

### Application name and version
  > If the issue is observed using a specific app.
Firefox Nightly (65)

### Issue
  > Summarize the issue briefly -- one paragraph preferred
Open an monospaced text.

Notice that `fi` and other ligatures are gone, but the spacing is still incorrect and characters are misaligned, despite being a monospaced font.

I'm not sure if it's ligatures or something else, but there appear to be alignment issues at play.

### Character data
n/a

### Screenshot
![screenshot-1544056934](https://user-images.githubusercontent.com/327028/49553563-2e9ef480-f8ad-11e8-9dbc-3c61d733ff1b.png)

Note, it's properly formatted Go... there are indeed spaces around the `:=` operator. Yet, they're barely visible, and you can see that characters after the spaces are misaligned with their respective columns in lines above/below.

---

I don't have the following tools available right now. I'll follow up on them.

## Tools for reporting bugs
  Useful tools for reporting bugs are available at: https://github.com/googlei18n/
  
### Harfbuzz hb-view and hb-shape
  These are part of the HarfBuzz distribution and can help isolate if an issue is in the app/OS, shaping engine, or font.
  * hb-view renders the text with the exact font (for example, to see how ligatured characters shape) using your installed version of HarfBuzz.

For example:
```
  hb-view --font-file {path to font} --text-file {path to text file} --output-file '{sample}.png'
```

* hb-shape shows glyph selection and positioning

### Fontview
  * Fontview displays the text.

### Fontdiff
  * Fontdiff displays the text using two versions of the font side by side.

**Comment by colemickens** [comment]
Here's another screenshot, but this time showing `gedit` too. Maybe this is just a Firefox issue.

![screenshot-1544059146](https://user-images.githubusercontent.com/327028/49554798-580e4f00-f8b2-11e8-92ad-bfd4b91e8efe.png)

**Comment by simoncozens** [comment]
It looks like what is going on here is that Firefox is not using the font's space width for the space character. (See how `else if` is very close in the Firefox example compared to gedit.) I'm inclined to believe this is a Firefox bug until persuaded otherwise, so closing unless there is further information.
