### ISSUE TITLE
Missing below-base form of U+114A9 TIRHUTA LETTER RA

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1405]
### Font
NotoSansTirhuta-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/85e78f831469323c85847e23f95026c894159135/hinted/NotoSansTirhuta-Regular.ttf
Date: 2018-12-05

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770;ttfautohint (v1.8.2)

### Issue
Noto Sans Tirhuta doesn’t use a below-base <i>ra</i> in conjuncts (except in the single-glyph ligatures <i>kra</i>, <i>tra</i>, and <i>hra</i>), but in many of the figures in [11-175R](https://www.unicode.org/L2/L2011/11175r-tirhuta.pdf) show a below-base <i>ra</i> that looks the same as it does in Bengali.

### Character data
𑒬𑓂𑒩
U+114AC TIRHUTA LETTER SHA
U+114C2 TIRHUTA SIGN VIRAMA
U+114A9 TIRHUTA LETTER RA

### Screenshot
![𑒬𑓂𑒩](https://user-images.githubusercontent.com/1124347/49613027-72a8fc80-f974-11e8-8a43-ae1fb5823168.png)

**Comment by marekjez86** [comment]
<img width="353" alt="Screen Shot 2019-04-23 at 12 09 06" src="https://user-images.githubusercontent.com/13322623/56608890-a3ef3580-65c0-11e9-9dbb-5e62fd584c70.png">

**Comment by marekjez86** [comment]
Build https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansTirhuta/NotoSansTirhuta-Regular.otf (and corresponding TTF file) fixes the issue.
