### ISSUE TITLE
Overlapping U+0F00 TIBETAN SYLLABLE OM

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1409]
### Font
NotoSerifTibetan-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/85e78f831469323c85847e23f95026c894159135/hinted/NotoSerifTibetan-Regular.ttf
Date: 2018-12-12

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770

### Issue
Before a syllable with a vowel sign above that has a narrow form, U+0F00 TIBETAN SYLLABLE OM does not behave like the sequence <U+0F68 U+0F7C U+0F7E> of which it is a duplicate encoding. I suggest substituting U+0F00 with that sequence in an early lookup.

### Character data
ༀཀོ
U+0F00 TIBETAN SYLLABLE OM
U+0F40 TIBETAN LETTER KA
U+0F7C TIBETAN VOWEL SIGN O
ཨོཾཀོ
U+0F68 TIBETAN LETTER A
U+0F7C TIBETAN VOWEL SIGN O
U+0F7E TIBETAN SIGN RJES SU NGA RO
U+0F40 TIBETAN LETTER KA
U+0F7C TIBETAN VOWEL SIGN O

### Screenshot
![ༀཀོ ཨོཾཀོ](https://user-images.githubusercontent.com/1124347/49885403-20009200-fe05-11e8-9522-de4b08aa9fdc.png)

**Comment by marekjez86** [comment]
should be fixed in newly updated https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSerifTibetan (and its TTF counterpart)

**Comment by marekjez86** [comment]
[tib-1409-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/3288468/tib-1409-Serif.pdf)
