### ISSUE TITLE
different glyphs for tonos and oxia in Greek

### ISSUE THREAD

**Issue by ousia** [googlefonts/noto-fonts#1418]
Although oxia is tonos (that is, the monotonic Greek accent is acute), all fonts that contains both accented glyphs (see below) have different strokes for both accents.

This is problematic with polytonic Greek, because both acute and grave accents are mixed, such as in the following sample:

![noto-sample-01](https://user-images.githubusercontent.com/203767/50457783-8be30e80-095e-11e9-889e-2ff751a76e05.png)
![noto-sample-02](https://user-images.githubusercontent.com/203767/50457782-8be30e80-095e-11e9-93b2-6723969c63f9.png)
![noto-sample-03](https://user-images.githubusercontent.com/203767/50457781-8b4a7800-095e-11e9-8655-d3b24ce3e0fc.png)
![noto-sample-04](https://user-images.githubusercontent.com/203767/50457780-8b4a7800-095e-11e9-8f96-a5c875b321ac.png)
![noto-sample-05](https://user-images.githubusercontent.com/203767/50457779-8b4a7800-095e-11e9-84b3-208020cbf86f.png)
![noto-sample-06](https://user-images.githubusercontent.com/203767/50457778-8ab1e180-095e-11e9-887d-02653167d65a.png)
![noto-sample-07](https://user-images.githubusercontent.com/203767/50457777-8ab1e180-095e-11e9-8dc4-4d322c455ed8.png)
![noto-sample-08](https://user-images.githubusercontent.com/203767/50457775-8ab1e180-095e-11e9-83da-9d265ed7a9ae.png)
![noto-sample-09](https://user-images.githubusercontent.com/203767/50457776-8ab1e180-095e-11e9-8133-81175427980e.png)
![noto-sample-11](https://user-images.githubusercontent.com/203767/50457774-8a194b00-095e-11e9-8dfe-c97bb54a565c.png)

In the first two sentences, oxia is used as acute accent. The last two sentences use tonos.

Comparing both, it seems that tonos is somewhat longer than oxia. I’m afraid that they don’t mix well in a polytonic text. Here you have all the glyphs with both oxia and tonos (click on the images to enlarge them):
 
* Noto Serif fonts:
    ![noto-oxiatonos-01](https://user-images.githubusercontent.com/203767/50457487-18d89880-095c-11e9-89bc-49b8b49ae72f.png)
    ![noto-oxiatonos-02](https://user-images.githubusercontent.com/203767/50457486-18d89880-095c-11e9-85a7-c3d45e2f086f.png)
    ![noto-oxiatonos-03](https://user-images.githubusercontent.com/203767/50457485-18d89880-095c-11e9-8dd7-2f92e425f80e.png)
    ![noto-oxiatonos-04](https://user-images.githubusercontent.com/203767/50457484-18d89880-095c-11e9-8d25-b90818e57204.png)

* Noto Sans fonts:
    ![noto-oxiatonos-05](https://user-images.githubusercontent.com/203767/50457483-18400200-095c-11e9-9be3-45e8e3084668.png)
    ![noto-oxiatonos-06](https://user-images.githubusercontent.com/203767/50457482-18400200-095c-11e9-9633-b4a1f4917788.png)
    ![noto-oxiatonos-07](https://user-images.githubusercontent.com/203767/50457481-18400200-095c-11e9-8816-1df7e0dca08a.png)
    ![noto-oxiatonos-08](https://user-images.githubusercontent.com/203767/50457480-18400200-095c-11e9-8db2-0c0da5b8e4cb.png)

* Noto Sans Mono fonts:
    ![noto-oxiatonos-09](https://user-images.githubusercontent.com/203767/50457479-17a76b80-095c-11e9-92ec-d1314c62757b.png)
    ![noto-oxiatonos-11](https://user-images.githubusercontent.com/203767/50457478-17a76b80-095c-11e9-80af-d2c3aa894c31.png)

Since OpenType allows a local feature that replaces tonos with oxia and polytonic Greek is defined as language, how about the following feature for polytonic Greek in the Noto typeface family?

```
feature locl {

    @tonosuppercase = [Alphatonos Epsilontonos Etatonos Iotatonos
                       Omicrontonos Omegatonos Upsilontonos];

    @tonoslowercase = [alphatonos epsilontonos etatonos iotatonos
                       iotadieresistonos omicrontonos omegatonos
                       upsilontonos upsilondieresistonos];

    @oxiauppercase = [uni1FBB uni1FC9 uni1FCB uni1FDB uni1FF9
                      uni1FFB uni1FEB];

    @oxialowercase = [uni1F71 uni1F73 uni1F75 uni1F77 uni1FD3
                      uni1F79 uni1F7D uni1F7B uni1FE3];

    script grek;

        language PGR exclude_dflt;

            lookup TonosOxia {
                sub @tonosuppercase by @oxiauppercase;
                sub @tonoslowercase by @oxialowercase;
            } TonosOxia;

} locl;
```

**Comment by marekjez86** [comment]
@ousia : Pablo, could you help me by pasting here the text for all of these? Thanks

**Comment by ousia** [comment]
@marekjez86, do you mean the ConTeXt source?

Here you have it:

``` tex
\startluacode
    fonts.handlers.otf.addfeature {
        name = "tonosoxia",
        type = "substitution",
        data = {
            Alphatonos = "Ά",
            Epsilontonos = "Έ",
            Etatonos = "Ή",
            Iotatonos = "Ί",
            Omicrontonos = "Ό",
            Omegatonos = "Ώ",
            Upsilontonos = "Ύ",
            alphatonos = "ά",
            epsilontonos = "έ",
            etatonos = "ή",
            iotatonos = "ί",
            iotadieresistonos = "ΐ",
            omicrontonos = "ό",
            omegatonos = "ώ",
            upsilontonos = "ύ",
            upsilondieresistonos = "ΰ"
            },
        }
\stopluacode

\definefontfeature[tonosoxia][tonosoxia=yes]

\definefontfamily
    [mainface]
    [rm]
    [Noto Serif]
    [features={default, tonosoxia}]

\definefontfamily
    [mainface]
    [ss]
    [Noto Sans]
    [features={default, tonosoxia}]

\definefontfamily
    [mainface]
    [tt]
    [Noto Sans Mono]
    [features={default, tonosoxia}]

\setupbodyfont[mainface, 70pt]

\setuppapersize[A4, landscape]
\setuplayout[width=middle]
\setupinteractionscreen[option=max]

\setupmakeup[standard][align=center]

\startbuffer[characters]
Ά Ὰ Έ Ὲ Ή Ὴ Ί Ὶ Ό Ὸ Ύ Ὺ Ώ Ώ

\feature[-][tonosoxia]
Ά Ὰ Έ Ὲ Ή Ὴ Ί Ὶ Ό Ὸ Ύ Ὺ Ώ Ώ

\feature[!][tonosoxia]
ά ὰ έ ὲ ή ὴ ί ὶ ΐ ῒ ό ὸ ύ ὺ ΰ ῢ ώ ὼ

\feature[-][tonosoxia]
ά ὰ έ ὲ ή ὴ ί ὶ ΐ ῒ ό ὸ ύ ὺ ΰ ῢ ώ ὼ
\stopbuffer

 \startbuffer[typefaces]
    \startTEXpage[offset=1em, align=center, width=17.5em]
        \getbuffer[characters]
    \stopTEXpage
    \startTEXpage[offset=1em, align=center, width=17.5em]
        \it\getbuffer[characters]
    \stopTEXpage
    \startTEXpage[offset=1em, align=center, width=17.5em]
        \bf\getbuffer[characters]
    \stopTEXpage
    \startTEXpage[offset=1em, align=center, width=17.5em]
        \bi\getbuffer[characters]
    \stopTEXpage
\stopbuffer

\starttext
    \getbuffer[typefaces]
    \ss\getbuffer[typefaces]
    \tt\getbuffer[typefaces]
\stoptext
```

**Comment by nizarsq** [comment]
If I'm not mistaken and my eyes still good, this issue has been fixed. I created test case for all fonts mentioned in the bug and below the regular ones. I think tonos still longer than oxia. @ousia can you verify?

<img width="1054" alt="Screen Shot 2020-07-01 at 7 59 28 PM" src="https://user-images.githubusercontent.com/22158882/86311488-60855380-bbd5-11ea-92fb-faa3f088b90a.png">

<img width="954" alt="Screen Shot 2020-07-01 at 7 58 23 PM" src="https://user-images.githubusercontent.com/22158882/86311422-392e8680-bbd5-11ea-8be1-1291b3a46074.png">

<img width="1152" alt="Screen Shot 2020-07-01 at 8 00 28 PM" src="https://user-images.githubusercontent.com/22158882/86311567-87438a00-bbd5-11ea-8741-d1e9b758d2e8.png">

**Comment by ousia** [comment]
@nizarsq, sorry but where can I find the generated fonts to check the issue?

**Comment by nizarsq** [comment]
> @nizarsq, sorry but where can I find the generated fonts to check the issue?

@ousia here is the fonts directory https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only

**Comment by ousia** [comment]
Many thanks for the hint, @nizarsq.

I cannot download all the fonts (I don’t have that much free space on my HD).

I have just checked it some of them randomly and they were fine.

Many thanks for your help. I’m closing the issue myself now.
