### ISSUE TITLE
1000 upem outline for NotoKufiArabic Fonts

### ISSUE THREAD

**Issue by vinodvar** [googlefonts/noto-fonts#1429]
Is there 1000 upem outline for NotoKufiArabic Fonts ??

in this link : https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/ttf/sans there is no Kufi Arabic fonts.

**Comment by marekjez86** [comment]
please see https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoKufiArabic (and corresponding ttf directory)
