### ISSUE TITLE
Kannada Glyphs have unnecessary points cause wrong halos

### ISSUE THREAD

**Issue by mnavada** [googlefonts/noto-fonts#1430]
## Defect Report
Several glyphs have additional points in the glyphs, that creates unnecessary halo in the graphical rendering. Use this template for filing a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
  > Glyphs causing unnecessary halo. 

### Font 
  >  'NotoSansKannada-Bold.ttf       NotoSansKannadaUI-Bold.ttf
 NotoSansKannadaUI-Regular.ttf   NotoSansKannada-Regular.ttf    

### Where the font came from, and when
https://www.google.com/get/noto/#sans-knda
latest version in the web
 
### Font Version
Any version
 

### OS name and version
Any version

### Application name and version
 Can be observed by loading TTF in https://mathew-kurian.github.io/CharacterMap/

### Issue
Several glyphs in Kannada fonts have unnecessary points as shown in screenshots. Normally they do not cause any trouble rendering. When we create halo around the glyph, they create unnecessary roundish halo at certain corners. 
They need to be deleted

### Character data
  Any character.

### Screenshot
![screenshot from 2019-01-30 19-51-39](https://user-images.githubusercontent.com/66946/51988081-d27dd880-24c9-11e9-91d3-759d13053133.png)
![img-20190129-wa0008](https://user-images.githubusercontent.com/66946/51988239-386a6000-24ca-11e9-88cc-b2d22e55ee9d.jpg)

**Comment by punchcutter** [comment]
You are using an old version of the font because the fonts from https://www.google.com/get/noto haven't been updated for a while. The newest Noto Sans Kannada is in https://github.com/googlei18n/noto-fonts/tree/master/hinted or https://github.com/googlei18n/noto-fonts/tree/master/unhinted. There are a lot more weights as well so you have more options.

**Comment by nizarsq** [comment]
Checked reported issue and the font in this [directory](https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansKannada/NotoSansKannada-Regular.ttf) looks Ok. Closing this bug
