### ISSUE TITLE
Incomplete 'ss02' in Noto Sans Kaithi

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1432]
### Font
NotoSansKaithi-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/c30307083469f0c05e216ac75216fd454a517858/unhinted/NotoSansKaithi-Regular.ttf
Date: 2019-02-02

### Font version
Version 2.000

### Issue
'ss02' changes the shape of U+110B3 KAITHI VOWEL SIGN U on some consonants, but not on any ligatures including those consonants.

### Character data
𑂍𑂳𑂍𑂹𑂍𑂳
𑂟𑂳𑂍𑂹𑂟𑂳
𑂧𑂳𑂍𑂹𑂧𑂳
𑂨𑂳𑂍𑂹𑂨𑂳
𑂍𑂳𑂍𑂹𑂩𑂳
𑂮𑂳𑂍𑂹𑂮𑂳
𑂎𑂳𑂎𑂹𑂩𑂳
𑂐𑂳𑂐𑂹𑂩𑂳
𑂒𑂳𑂒𑂹𑂩𑂳
𑂔𑂳𑂔𑂹𑂩𑂳
𑂞𑂳𑂞𑂹𑂩𑂳
𑂟𑂳𑂟𑂹𑂩𑂳
𑂡𑂳𑂡𑂹𑂩𑂳
𑂞𑂳𑂣𑂹𑂞𑂳
𑂣𑂳𑂣𑂹𑂩𑂳
𑂥𑂳𑂥𑂹𑂩𑂳
𑂨𑂳𑂦𑂹𑂨𑂳
𑂦𑂳𑂦𑂹𑂩𑂳
𑂧𑂳𑂧𑂹𑂩𑂳
𑂫𑂳𑂫𑂹𑂩𑂳
𑂭𑂳𑂭𑂹𑂩𑂳
𑂮𑂳𑂮𑂹𑂩𑂳

U+1108D KAITHI LETTER KA
U+110B3 KAITHI VOWEL SIGN U
U+1108D KAITHI LETTER KA
U+110B9 KAITHI SIGN VIRAMA
U+1108D KAITHI LETTER KA
U+110B3 KAITHI VOWEL SIGN U

U+1109F KAITHI LETTER THA
U+110B3 KAITHI VOWEL SIGN U
U+1108D KAITHI LETTER KA
U+110B9 KAITHI SIGN VIRAMA
U+1109F KAITHI LETTER THA
U+110B3 KAITHI VOWEL SIGN U

U+110A7 KAITHI LETTER MA
U+110B3 KAITHI VOWEL SIGN U
U+1108D KAITHI LETTER KA
U+110B9 KAITHI SIGN VIRAMA
U+110A7 KAITHI LETTER MA
U+110B3 KAITHI VOWEL SIGN U

U+110A8 KAITHI LETTER YA
U+110B3 KAITHI VOWEL SIGN U
U+1108D KAITHI LETTER KA
U+110B9 KAITHI SIGN VIRAMA
U+110A8 KAITHI LETTER YA
U+110B3 KAITHI VOWEL SIGN U

U+1108D KAITHI LETTER KA
U+110B3 KAITHI VOWEL SIGN U
U+1108D KAITHI LETTER KA
U+110B9 KAITHI SIGN VIRAMA
U+110A9 KAITHI LETTER RA
U+110B3 KAITHI VOWEL SIGN U

U+110AE KAITHI LETTER SA
U+110B3 KAITHI VOWEL SIGN U
U+1108D KAITHI LETTER KA
U+110B9 KAITHI SIGN VIRAMA
U+110AE KAITHI LETTER SA
U+110B3 KAITHI VOWEL SIGN U

U+1108E KAITHI LETTER KHA
U+110B3 KAITHI VOWEL SIGN U
U+1108E KAITHI LETTER KHA
U+110B9 KAITHI SIGN VIRAMA
U+110A9 KAITHI LETTER RA
U+110B3 KAITHI VOWEL SIGN U

U+11090 KAITHI LETTER GHA
U+110B3 KAITHI VOWEL SIGN U
U+11090 KAITHI LETTER GHA
U+110B9 KAITHI SIGN VIRAMA
U+110A9 KAITHI LETTER RA
U+110B3 KAITHI VOWEL SIGN U

U+11092 KAITHI LETTER CA
U+110B3 KAITHI VOWEL SIGN U
U+11092 KAITHI LETTER CA
U+110B9 KAITHI SIGN VIRAMA
U+110A9 KAITHI LETTER RA
U+110B3 KAITHI VOWEL SIGN U

U+11094 KAITHI LETTER JA
U+110B3 KAITHI VOWEL SIGN U
U+11094 KAITHI LETTER JA
U+110B9 KAITHI SIGN VIRAMA
U+110A9 KAITHI LETTER RA
U+110B3 KAITHI VOWEL SIGN U

U+1109E KAITHI LETTER TA
U+110B3 KAITHI VOWEL SIGN U
U+1109E KAITHI LETTER TA
U+110B9 KAITHI SIGN VIRAMA
U+110A9 KAITHI LETTER RA
U+110B3 KAITHI VOWEL SIGN U

U+1109F KAITHI LETTER THA
U+110B3 KAITHI VOWEL SIGN U
U+1109F KAITHI LETTER THA
U+110B9 KAITHI SIGN VIRAMA
U+110A9 KAITHI LETTER RA
U+110B3 KAITHI VOWEL SIGN U

U+110A1 KAITHI LETTER DHA
U+110B3 KAITHI VOWEL SIGN U
U+110A1 KAITHI LETTER DHA
U+110B9 KAITHI SIGN VIRAMA
U+110A9 KAITHI LETTER RA
U+110B3 KAITHI VOWEL SIGN U

U+1109E KAITHI LETTER TA
U+110B3 KAITHI VOWEL SIGN U
U+110A3 KAITHI LETTER PA
U+110B9 KAITHI SIGN VIRAMA
U+1109E KAITHI LETTER TA
U+110B3 KAITHI VOWEL SIGN U

U+110A3 KAITHI LETTER PA
U+110B3 KAITHI VOWEL SIGN U
U+110A3 KAITHI LETTER PA
U+110B9 KAITHI SIGN VIRAMA
U+110A9 KAITHI LETTER RA
U+110B3 KAITHI VOWEL SIGN U

U+110A5 KAITHI LETTER BA
U+110B3 KAITHI VOWEL SIGN U
U+110A5 KAITHI LETTER BA
U+110B9 KAITHI SIGN VIRAMA
U+110A9 KAITHI LETTER RA
U+110B3 KAITHI VOWEL SIGN U

U+110A8 KAITHI LETTER YA
U+110B3 KAITHI VOWEL SIGN U
U+110A6 KAITHI LETTER BHA
U+110B9 KAITHI SIGN VIRAMA
U+110A8 KAITHI LETTER YA
U+110B3 KAITHI VOWEL SIGN U

U+110A6 KAITHI LETTER BHA
U+110B3 KAITHI VOWEL SIGN U
U+110A6 KAITHI LETTER BHA
U+110B9 KAITHI SIGN VIRAMA
U+110A9 KAITHI LETTER RA
U+110B3 KAITHI VOWEL SIGN U

U+110A7 KAITHI LETTER MA
U+110B3 KAITHI VOWEL SIGN U
U+110A7 KAITHI LETTER MA
U+110B9 KAITHI SIGN VIRAMA
U+110A9 KAITHI LETTER RA
U+110B3 KAITHI VOWEL SIGN U

U+110AB KAITHI LETTER VA
U+110B3 KAITHI VOWEL SIGN U
U+110AB KAITHI LETTER VA
U+110B9 KAITHI SIGN VIRAMA
U+110A9 KAITHI LETTER RA
U+110B3 KAITHI VOWEL SIGN U

U+110AD KAITHI LETTER SSA
U+110B3 KAITHI VOWEL SIGN U
U+110AD KAITHI LETTER SSA
U+110B9 KAITHI SIGN VIRAMA
U+110A9 KAITHI LETTER RA
U+110B3 KAITHI VOWEL SIGN U

U+110AE KAITHI LETTER SA
U+110B3 KAITHI VOWEL SIGN U
U+110AE KAITHI LETTER SA
U+110B9 KAITHI SIGN VIRAMA
U+110A9 KAITHI LETTER RA
U+110B3 KAITHI VOWEL SIGN U

### Screenshot
![𑂍𑂳𑂍𑂹𑂍𑂳 𑂟𑂳𑂍𑂹𑂟𑂳 𑂧𑂳𑂍𑂹𑂧𑂳 𑂨𑂳𑂍𑂹𑂨𑂳 𑂍𑂳𑂍𑂹𑂩𑂳 𑂮𑂳𑂍𑂹𑂮𑂳 𑂎𑂳𑂎𑂹𑂩𑂳 𑂐𑂳𑂐𑂹𑂩𑂳 𑂒𑂳𑂒𑂹𑂩𑂳 𑂔𑂳𑂔𑂹𑂩𑂳 𑂞𑂳𑂞𑂹𑂩𑂳 𑂟𑂳𑂟𑂹𑂩𑂳 𑂡𑂳𑂡𑂹𑂩𑂳 𑂞𑂳𑂣𑂹𑂞𑂳 𑂣𑂳𑂣𑂹𑂩𑂳 𑂥𑂳𑂥𑂹𑂩𑂳 𑂨𑂳𑂦𑂹𑂨𑂳 𑂦𑂳𑂦𑂹𑂩𑂳 𑂧𑂳𑂧𑂹𑂩𑂳 𑂫𑂳𑂫𑂹𑂩𑂳 𑂭𑂳𑂭𑂹𑂩𑂳 𑂮𑂳𑂮𑂹𑂩𑂳](https://user-images.githubusercontent.com/1124347/52170509-8e811280-2719-11e9-9fcb-43504afc8493.png)

**Comment by marekjez86** [comment]
should be fixed in OTF: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansKaithi and TTF: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansKaithi
