### ISSUE TITLE
Problems with ZWJ in Kaithi

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1433]
### Font
NotoSansKaithi-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/c30307083469f0c05e216ac75216fd454a517858/unhinted/NotoSansKaithi-Regular.ttf
Date: 2019-02-02

### Font version
Version 2.000

### Issue
Noto Sans Kaithi in HarfBuzz has problems with U+200D ZERO WIDTH JOINER. It doesn’t force consonant conjuncts to use half forms, and it interferes with the placement of marks. This is because HarfBuzz clears `F_MANUAL_ZWJ` for 'ccmp' and sets it for 'mark'. The easiest fix is to use 'akhn' or 'cjct' instead of 'ccmp' and 'abvm' or 'blwm' instead of 'mark'.

### Character data
𑂍𑂹‍𑂍𑂀
U+1108D KAITHI LETTER KA
U+110B9 KAITHI SIGN VIRAMA
U+200D ZERO WIDTH JOINER
U+1108D KAITHI LETTER KA
U+11080 KAITHI SIGN CANDRABINDU

### Screenshot
![𑂍𑂹‍𑂍𑂀](https://user-images.githubusercontent.com/1124347/52183123-b7b1a980-27d2-11e9-912a-5b40784a1707.png)
The correct rendering:
![𑂍𑂹‍𑂍𑂀](https://user-images.githubusercontent.com/1124347/52183178-40c8e080-27d3-11e9-9f12-81b499f5c285.png)
Cf. the already accurate rendering without ZWJ:
![𑂍𑂹𑂍𑂀](https://user-images.githubusercontent.com/1124347/52183156-04958000-27d3-11e9-94ec-3b8ab733856e.png)

**Comment by marekjez86** [comment]
should be fixed in OTF: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansKaithi and TTF: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansKaithi
