### ISSUE TITLE
Unaligned integral pieces in Noto Sans Math

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1434]
### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/c30307083469f0c05e216ac75216fd454a517858/hinted/NotoSansMath-Regular.ttf
Date: 2019-02-04

### Font version
Version 2.000

### Issue
U+23AE INTEGRAL EXTENSION doesn’t align with the integral top and bottom.

### Character data
⌠
U+2320 TOP HALF INTEGRAL
⎮
U+23AE INTEGRAL EXTENSION
⌡
U+2321 BOTTOM HALF INTEGRAL

### Screenshot
![⌠⎮⌡](https://user-images.githubusercontent.com/1124347/52231762-c3f83e00-2888-11e9-8576-fc7e487dd3be.png)

**Comment by marekjez86** [comment]
with https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansMath/NotoSansMath-Regular.otf

<img width="851" alt="Screen Shot 2019-05-17 at 19 26 13" src="https://user-images.githubusercontent.com/13322623/57963486-abf97700-78d9-11e9-8e6f-f2bd871202af.png">
