### ISSUE TITLE
Inconsistent spacing of U+2057 QUADRUPLE PRIME

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1435]
### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/c30307083469f0c05e216ac75216fd454a517858/hinted/NotoSansMath-Regular.ttf
Date: 2019-02-04

### Font version
Version 2.000

### Issue
Unlike the other prime symbols, the quadruple prime has a positive right side-bearing.

### Character data
‴ℸ
U+2034 TRIPLE PRIME
U+2138 DALET SYMBOL
⁗ℸ
U+2057 QUADRUPLE PRIME
U+2138 DALET SYMBOL

### Screenshot
![‴ℸ ⁗ℸ](https://user-images.githubusercontent.com/1124347/52283763-1725cb80-2931-11e9-9127-310b5efd7f32.png)

**Comment by marekjez86** [comment]
with https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansMath/NotoSansMath-Regular.otf

<img width="215" alt="Screen Shot 2019-05-17 at 20 22 57" src="https://user-images.githubusercontent.com/13322623/57963958-97b97800-78e1-11e9-9cc9-08ea7ced31f4.png">
