### ISSUE TITLE
Overlapping mathematical script letters

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1437]
### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/c30307083469f0c05e216ac75216fd454a517858/hinted/NotoSansMath-Regular.ttf
Date: 2019-02-04

### Font version
Version 2.000

### Issue
The SMP mathematical script letters overlap subsequent glyphs. When the next glyph is another script letter, they join cursively. This is inappropriate for these symbols, which are for single-character mathematical variables: concatenating them represents some implicit operation like multiplication, not word formation. The BMP script letters are fine.

### Character data
𝓎=𝒶𝓍
U+1D4CE MATHEMATICAL SCRIPT SMALL Y
U+003D EQUALS SIGN
U+1D4B6 MATHEMATICAL SCRIPT SMALL A
U+1D4CD MATHEMATICAL SCRIPT SMALL X

### Screenshot
![𝓎=𝒶𝓍](https://user-images.githubusercontent.com/1124347/52426220-8cc59f00-2acb-11e9-9798-08788fbbd2ff.png)

**Comment by davelab6** [comment]
Looking at this issue on macOS, I see that the character data @dscorbett provided renders in whatever the macOS system font is, and has a non-connecting form:

<img width="624" alt="screen shot 2019-02-13 at 12 46 18 pm" src="https://user-images.githubusercontent.com/261579/52732117-64d3b100-2f8d-11e9-86cd-996289749555.png">

**Comment by marekjez86** [comment]
with https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansMath/NotoSansMath-Regular.otf

<img width="274" alt="Screen Shot 2019-05-17 at 19 20 49" src="https://user-images.githubusercontent.com/13322623/57963456-37bed380-78d9-11e9-941f-b40fa202dbae.png">
