### ISSUE TITLE
Wrong glyphs for U+27CB and U+27CD MATHEMATICAL RISING/FALLING DIAGONAL

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1441]
### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/c30307083469f0c05e216ac75216fd454a517858/hinted/NotoSansMath-Regular.ttf
Date: 2019-02-04

### Font version
Version 2.000

### Issue
U+27CB and U+27CD have the wrong slopes. [UTR #25](https://www.unicode.org/reports/tr25/tr25-15.pdf#page=25) says “Their glyphs are invariably drawn with 45° and 135° slopes, respectively, instead of the more upright slants typical for the solidi operators.”

### Character data
⟋⟍
U+27CB MATHEMATICAL RISING DIAGONAL
U+27CD MATHEMATICAL FALLING DIAGONAL

### Screenshot
![⟋⟍](https://user-images.githubusercontent.com/1124347/52540845-52befc00-2d5c-11e9-80a6-249e4e81233d.png)

**Comment by marekjez86** [comment]
@waksmonskiMT : if the glyphs were drawn at 45° and 135° slopes when adjacent they would create a 90° angle. In the image above they form less than 90° angle (my guess anything between 70 and 85).

**Comment by marekjez86** [comment]
<img width="172" alt="Screen Shot 2019-05-17 at 19 08 36" src="https://user-images.githubusercontent.com/13322623/57963312-47d5b380-78d7-11e9-9eb3-89cbc896dab5.png">
with https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansMath/NotoSansMath-Regular.otf
