### ISSUE TITLE
Wrong glyph for U+2A28 PLUS SIGN WITH BLACK TRIANGLE

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1447]
### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/c30307083469f0c05e216ac75216fd454a517858/hinted/NotoSansMath-Regular.ttf
Date: 2019-02-04

### Font version
Version 2.000

### Issue
U+2A28 PLUS SIGN WITH BLACK TRIANGLE looks like a plus sign with an overlaid circumflex. STIX [originally proposed it (at position CX40)](https://www.unicode.org/L2/L2000/00002-math.pdf#page=9) as FILLED TRIANGLE WITH PLUS, with a glyph that clearly does not have a circumflex, so its Unicode name is not a misnomer, and the glyph should have a triangle.

### Character data
⨨
U+2A28 PLUS SIGN WITH BLACK TRIANGLE

### Screenshot
![⨨](https://user-images.githubusercontent.com/1124347/52873867-068a0800-311e-11e9-9c77-91a6ec72ea14.png)

**Comment by marekjez86** [comment]
with https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansMath/NotoSansMath-Regular.otf

<img width="242" alt="Screen Shot 2019-05-17 at 20 07 38" src="https://user-images.githubusercontent.com/13322623/57963840-748dc900-78df-11e9-8ce8-a7e016862f56.png">
