### ISSUE TITLE
Wrong mirrored glyphs for integrals with curved arrows

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1448]
### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/c30307083469f0c05e216ac75216fd454a517858/hinted/NotoSansMath-Regular.ttf
Date: 2019-02-04

### Font version
Version 2.000

### Issue
The curved arrows of U+2231 through U+2233 should not be mirrored in RTL text. [_The Unicode Standard_, section 4.7](https://www.unicode.org/versions/Unicode11.0.0/ch04.pdf#page=21) says:

>For some mathematical symbols, the “mirrored” form is not an exact mirror image. For example, the direction of the circular arrow in U+2232 CLOCKWISE CONTOUR INTEGRAL reflects the direction of the integration in coordinate space, not the text direction. In a right-to-left context, the integral sign would be mirrored, but the circular arrow would retain its direction. 

### Character data
∱∲∳
U+2231 CLOCKWISE INTEGRAL
U+2232 CLOCKWISE CONTOUR INTEGRAL
U+2233 ANTICLOCKWISE CONTOUR INTEGRAL

### Screenshot
LTR:
![∱∲∳](https://user-images.githubusercontent.com/1124347/52901429-7c02e080-31d1-11e9-9542-1dc2d554bde3.png)
RTL:
![⁧∱∲∳⁩](https://user-images.githubusercontent.com/1124347/52901430-7c02e080-31d1-11e9-9f71-83e65a8f47d4.png)

**Comment by marekjez86** [comment]
per MT fixed
