### ISSUE TITLE
Monospace for all supported scripts in Phase 3

### ISSUE THREAD

**Issue by robert-ross** [googlefonts/noto-fonts#1452]
### Monospace for all supported scripts in Phase 3

According to the FAQ, Phase 3 plans include "a number of widths (condensed to normal)".  Does that include monospace (where widths are some multiple of the cell width)?  If so, that would greatly benefit those of us using terminals and traditional text editors.  Currently, glyphs such as `\u2330` in `NotoSansSymbols-Regular.ttf` are a little too wide while others such as `\u232f` fit nicely.  Something like `NotoSansSymbols-Mono.ttf` would only condense or stretch glyphs as needed.  Currently, commands such as `echo -e '\u0b05M'` and `echo -e '\u0b06M'` produce visually indistinguishable output, but something like `NotoSansOriya-Mono.ttf` would fix that (albeit with a little distortion).

**Comment by marekjez86** [comment]
Unfortunately we have no plans for having Monospace versions beyond what we have right now.
