### ISSUE TITLE
Questionable macron in Noto Serif Devanagari

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1457]
### Font
NotoSerifDevanagari-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/576ccad099c8f92f8c61c01bf3fcfa1de3be50b4/unhinted/NotoSerifDevanagari-Regular.ttf
Date: 2019-02-24

### Font version
Version 1.01 uh

### Issue
U+00AF MACRON should have positive side bearings, but in this font it behaves like U+203E OVERLINE. What’s this character doing in a Devanagari font, anyway?

### Character data
¯¯
U+00AF MACRON
U+00AF MACRON

### Screenshot
![¯¯](https://user-images.githubusercontent.com/1124347/53307794-09959e80-386a-11e9-948e-f775f0be925e.png)

**Comment by JelleBosmaMT** [comment]
My theory is that there was a mix up with hyphen 00AD.

**Comment by marekjez86** [comment]
fixed in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSerifDevanagari
