### ISSUE TITLE
Missing Malayalam conjuncts in 'dflt' language system

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1459]
### Font
NotoSansMalayalam-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/576ccad099c8f92f8c61c01bf3fcfa1de3be50b4/phaseIII_only/unhinted/otf/NotoSansMalayalam/NotoSansMalayalam-Regular.otf
Date: 2019-02-26

### Font version
Version 2.000

### Issue
Noto Sans Malayalam supports various conjuncts. Two of them are only enabled when the language system tag is 'MAL '. There doesn’t seem to be any reason these two should treated differently than the rest.

### Character data
ക്ടഗ്ദ
U+0D15 MALAYALAM LETTER KA
U+0D4D MALAYALAM SIGN VIRAMA
U+0D1F MALAYALAM LETTER TTA
U+0D17 MALAYALAM LETTER GA
U+0D4D MALAYALAM SIGN VIRAMA
U+0D26 MALAYALAM LETTER DA

### Screenshot
'dflt':
![ക്ടഗ്ദ](https://user-images.githubusercontent.com/1124347/53440800-5d6fc700-39d3-11e9-9a10-6b04841aacba.png)
'MAL ':
![ക്ടഗ്ദ](https://user-images.githubusercontent.com/1124347/53440809-62cd1180-39d3-11e9-9a47-a1a791f23838.png)

**Comment by marekjez86** [comment]
@cibu : any advise on this?

**Comment by cibu** [comment]
I am assuming 'MAL' is the opentype script tag for Malayalam in traditional orthography - that is, the writing with with more cursive connections. The MAL ligatures listed above (k-tta, g-da) are correct visuals for that. 

I believe the plan was to add lot more traditional orthography ligature glyphs under MAL. Looks like that didn't materialize. Anyway, the current situation is working as intended. There is no reason to add these two ligatures to MLR or to the 'dflt'. Noto Sans Malayalam is by default a reformed orthography font.
