### ISSUE TITLE
⟨മ്പ്ലൢ⟩ looks like ⟨ത്ത്ലൢ⟩ in 'mlym' in Noto Sans Malayalam

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1460]
### Font
NotoSansMalayalam-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/576ccad099c8f92f8c61c01bf3fcfa1de3be50b4/phaseIII_only/unhinted/otf/NotoSansMalayalam/NotoSansMalayalam-Regular.otf
Date: 2019-02-26

### Font version
Version 2.000

### Issue
With the script tag 'mlym', before the vowel signs <i>l̥</i> and <i>l̥̄</i>, <i>mpl</i> is converted to <i>ttl</i>.

### Character data
മ്പ്ലൢ
U+0D2E MALAYALAM LETTER MA
U+0D4D MALAYALAM SIGN VIRAMA
U+0D2A MALAYALAM LETTER PA
U+0D4D MALAYALAM SIGN VIRAMA
U+0D32 MALAYALAM LETTER LA
U+0D62 MALAYALAM VOWEL SIGN VOCALIC L

### Screenshot
'mlm2':
![മ്പ്ലൢ](https://user-images.githubusercontent.com/1124347/53524762-4e117c00-3aae-11e9-9e28-3c1c7d405667.png)
'mlym':
![മ്പ്ലൢ](https://user-images.githubusercontent.com/1124347/53524761-4e117c00-3aae-11e9-9c2e-3e017f46d1e3.png)

**Comment by marekjez86** [comment]
@cibu : comment on this?

**Comment by cibu** [comment]
The 'mlym' output is obviously incorrect. Needs to be fixed. 'mlm2' output is the correct one as per the character sequence: <MA, VIRAMA, PA, VIRAMA, LA, SIGN VOCALIC L>

**Comment by marekjez86** [comment]
should be fixed in newly released https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSerifMalayalam ; not fixed in Sans though

**Comment by nizarsq** [comment]
Look like this issue fixed, mlym render same as mlm2.
<img width="759" alt="Screen Shot 2020-06-19 at 10 40 29 PM" src="https://user-images.githubusercontent.com/22158882/85193677-a3fbcb80-b27f-11ea-9ad3-9b916c2144ae.png">
<img width="766" alt="Screen Shot 2020-06-19 at 10 40 16 PM" src="https://user-images.githubusercontent.com/22158882/85193679-a5c58f00-b27f-11ea-8fd9-18cf6f73bd35.png">

**Comment by dscorbett** [comment]
It is still broken in [the latest version](https://github.com/googlefonts/noto-fonts/blob/ea9154f9a0947972baa772bc6744f1ec50007575/phaseIII_only/unhinted/otf/NotoSansMalayalam/NotoSansMalayalam-Regular.otf). What is the source code for your 'mlym' test?

**Comment by dscorbett** [comment]
@nizarsq, how did you specify the 'mlym' script tag in your test?
