### ISSUE TITLE
U+115C0 SIDDHAM SIGN NUKTA blocks contextual vowels

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1464]
### Font
NotoSansSiddham-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/c4e94171d04167796d0dd5e7a93e94b54ca29425/phaseIII_only/unhinted/otf/NotoSansSiddham/NotoSansSiddham-Regular.otf
Date: 2019-03-01

### Font version
Version 2.000

### Issue
The presence of U+115C0 SIDDHAM SIGN NUKTA interrupts lookups that contextualize non-below-base vowel signs, so the vowel signs end up having the wrong forms. The nukta, being at the bottom, shouldn’t affect these vowel signs.

### Character data
𑖨𑖿𑖎𑗀𑖱𑖨𑖿𑖎𑗀𑖹
U+115A8 SIDDHAM LETTER RA
U+115BF SIDDHAM SIGN VIRAMA
U+1158E SIDDHAM LETTER KA
U+115C0 SIDDHAM SIGN NUKTA
U+115B1 SIDDHAM VOWEL SIGN II
U+115A8 SIDDHAM LETTER RA
U+115BF SIDDHAM SIGN VIRAMA
U+1158E SIDDHAM LETTER KA
U+115C0 SIDDHAM SIGN NUKTA
U+115B9 SIDDHAM VOWEL SIGN AI
𑖨𑖿𑖎𑖱𑖨𑖿𑖎𑖹
U+115A8 SIDDHAM LETTER RA
U+115BF SIDDHAM SIGN VIRAMA
U+1158E SIDDHAM LETTER KA
U+115B1 SIDDHAM VOWEL SIGN II
U+115A8 SIDDHAM LETTER RA
U+115BF SIDDHAM SIGN VIRAMA
U+1158E SIDDHAM LETTER KA
U+115B9 SIDDHAM VOWEL SIGN AI

### Screenshot
![𑖨𑖿𑖎𑗀𑖱𑖨𑖿𑖎𑗀𑖹 𑖨𑖿𑖎𑖱𑖨𑖿𑖎𑖹](https://user-images.githubusercontent.com/1124347/53668358-ad53c580-3c41-11e9-9cb4-ee77c0c017dd.png)

**Comment by marekjez86** [comment]
@dscorbett : thank you

**Comment by marekjez86** [comment]
opening a test case within a browser yields

![siddham](https://user-images.githubusercontent.com/13322623/53675673-91562100-3c4d-11e9-8009-494729dc5d2e.jpeg)

**Comment by simoncozens** [comment]
Somebody fixed this...
![shape](https://user-images.githubusercontent.com/106728/174039892-5e7b6edd-6478-40e2-a4a5-6fbe9825409a.png)
