### ISSUE TITLE
Georgian mtavruli support

### ISSUE THREAD

**Issue by r12a** [googlefonts/noto-fonts#1470]
What's the outlook for addition of glyphs for the Unicode11 mtravruli code points to the Noto Georgian fonts?

**Comment by marekjez86** [comment]
@davelab6 : upper case letters for georgian

**Comment by marekjez86** [comment]
adding mtavruli will close/invalidate https://github.com/googlei18n/noto-fonts/issues/1261

**Comment by marekjez86** [comment]
@r12a : it's high on our priority list

**Comment by r12a** [comment]
thanks @marekjez86, i'll keep a eye out for it.

**Comment by kmuncie** [comment]
@marekjez86 it appears the Georgian Extended Mtavruli characters have been added to NotoSansGeorgian as-of v2.001 at https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/hinted/ttf/NotoSansGeorgian/NotoSansGeorgian-Regular.ttf. 

Can you confirm if the work to support https://www.unicode.org/charts/PDF/U1C90.pdf is now finished in this latest version?

**Comment by marekjez86** [comment]
My bad... this should be closed since we have updated all Georgian Noto fonts to include Georgian mtavruli support
