### ISSUE TITLE
Ahom i–u ligature is not always formed

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1483]
### Font
NotoSerifAhom-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/4bff97c612daf65d4409c9ebc26dfbd6a3d83a7e/phaseIII_only/unhinted/ttf/NotoSerifAhom/NotoSerifAhom-Regular.ttf
Date: 2019-04-18

### Font version
Version 2.002

### Issue
U+11722 AHOM VOWEL SIGN I and U+11724 AHOM VOWEL SIGN U generally ligate, except after the consonants <i>nga</i>, <i>na</i>, <i>da</i>, and <i>nya</i>, but in Noto Serif Ahom, when a glyph comes between one of the other consonants and those two vowels, the vowels do not ligate.

I have given three example syllables. In the second, the medial <i>-l</i> and the <i>-u</i> overlap cleanly, so it might be intentional; but the Unicode proposal doesn’t say anything about that, so it might not. The third uses a vowel sequence that I don’t know is attested.

### Character data
𑜁𑜟𑜢𑜤
U+11701 AHOM LETTER KHA
U+1171F AHOM CONSONANT SIGN MEDIAL LIGATING RA
U+11722 AHOM VOWEL SIGN I
U+11724 AHOM VOWEL SIGN U
𑜀𑜝𑜢𑜤
U+11700 AHOM LETTER KA
U+1171D AHOM CONSONANT SIGN MEDIAL LA
U+11722 AHOM VOWEL SIGN I
U+11724 AHOM VOWEL SIGN U
𑜀𑜦𑜢𑜤
U+11700 AHOM LETTER KA
U+11726 AHOM VOWEL SIGN E
U+11722 AHOM VOWEL SIGN I
U+11724 AHOM VOWEL SIGN U

### Screenshot
![𑜁𑜟𑜢𑜤 𑜀𑜝𑜢𑜤 𑜀𑜦𑜢𑜤](https://user-images.githubusercontent.com/1124347/56426627-f6f67f00-6286-11e9-980a-9f83db82b8f4.png)

**Comment by nizarsq** [comment]
Look like this issue resolved
<img width="869" alt="Screen Shot 2020-06-25 at 2 16 26 PM" src="https://user-images.githubusercontent.com/22158882/85796250-77680980-b6ee-11ea-96ec-b2a66de8b310.png">
