### ISSUE TITLE
Ahom spacing vowel signs are not always spacing

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1484]
### Font
NotoSerifAhom-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/4bff97c612daf65d4409c9ebc26dfbd6a3d83a7e/phaseIII_only/unhinted/ttf/NotoSerifAhom/NotoSerifAhom-Regular.ttf
Date: 2019-04-18

### Font version
Version 2.002

### Issue
After the glyphs medialLigaRa_ahom, khra_ahom, phra_ahom, and t_ja_ahom, vowel signs that should be spacing are not spacing.

### Character data
𑜀𑜟𑜢𑜂
U+11700 AHOM LETTER KA
U+1171F AHOM CONSONANT SIGN MEDIAL LIGATING RA
U+11722 AHOM VOWEL SIGN I
U+11702 AHOM LETTER NGA
𑜁𑜟𑜢𑜂
U+11701 AHOM LETTER KHA
U+1171F AHOM CONSONANT SIGN MEDIAL LIGATING RA
U+11722 AHOM VOWEL SIGN I
U+11702 AHOM LETTER NGA
𑜇𑜟𑜢𑜂
U+11707 AHOM LETTER PHA
U+1171F AHOM CONSONANT SIGN MEDIAL LIGATING RA
U+11722 AHOM VOWEL SIGN I
U+11702 AHOM LETTER NGA
𑜅𑜊𑜢𑜂
U+11705 AHOM LETTER ALTERNATE TA
U+1170A AHOM LETTER JA
U+11722 AHOM VOWEL SIGN I
U+11702 AHOM LETTER NGA

### Screenshot
![𑜀𑜟𑜢𑜂 𑜁𑜟𑜢𑜂 𑜇𑜟𑜢𑜂 𑜅𑜊𑜢𑜂](https://user-images.githubusercontent.com/1124347/56459919-cdae1f80-6368-11e9-922b-1ab2097fa59d.png)

**Comment by nizarsq** [comment]
Loom like this issue has been resolved 
<img width="769" alt="Screen Shot 2020-06-25 at 2 09 46 PM" src="https://user-images.githubusercontent.com/22158882/85795766-adf15480-b6ed-11ea-94c8-4a221457b9c9.png">
