### ISSUE TITLE
Overlapping Tirhuta nukta and virama

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1489]
### Font
NotoSansTirhuta-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/fadc9ff5dd82c9ae781d3ba40ae4c238310e06e7/phaseIII_only/unhinted/ttf/NotoSansTirhuta/NotoSansTirhuta-Regular.ttf
Date: 2019-04-23

### Font version
Version 2.001

### Issue
Under some Tirhuta consonants, a virama overlaps a nukta.

### Character data
𑒛𑓃𑓂
U+1149B TIRHUTA LETTER DDA
U+114C3 TIRHUTA SIGN NUKTA
U+114C2 TIRHUTA SIGN VIRAMA

### Screenshot
![𑒛𑓃𑓂](https://user-images.githubusercontent.com/1124347/56664784-c04da980-6676-11e9-92d6-58ef2802a96c.png)

**Comment by simoncozens** [comment]
This has been fixed as a side-effect of the recent re-engineering. (version 2.002)
![shape](https://user-images.githubusercontent.com/106728/152119191-cd7d497c-41c5-41bc-a704-6817a5ff563c.png)
