### ISSUE TITLE
Noto-Mono isn't showing, at least, Arrows UP and Arrow Down.

### ISSUE THREAD

**Issue by Kogurex** [googlefonts/noto-fonts#1496]
## Defect Report
Noto-Mono isn't showing, at least, Arrows UP and Arrow Down.

### Title 
  > Noto-Mono isn't showing certain characters, showing... Prepare Yourself... ¡TOFU! (And Noto Sans Mono, too)

### Font 
  > NotoMono-Regular.ttf

### Where the font came from, and when
 > From Noto Font Page (https://www.google.com/get/noto/)

### Font Version
  > 1.00

### OS name and version
  > Was installed downloading the entire package and installed by assistant.

### Application name and version
  > Using this font on NetBeans IDE 8.2 (Build 201609300101)

### Issue
  > Setting the default font to show code on NetBeans and having those characters written into code, it will be converted into 'tofues'.

### Character data
  > The characters issued are these (between the brackets): [↑] and [↓]

### Screenshot
  > If possible, include a screenshot or an image illustrating the issue.
  > Annotations are also helpful.
![image](https://user-images.githubusercontent.com/11504405/56962252-18c3f180-6b24-11e9-9499-a3989d0c1452.png)

## Tools for reporting bugs
  None used.

**Comment by nizarsq** [comment]
NotoMono-Regular.ttf currently have ↑↓. Please use the font in this directory https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSansMono.
<img width="514" alt="Screen Shot 2020-06-29 at 10 54 31 PM" src="https://user-images.githubusercontent.com/22158882/86088597-81299e00-ba5b-11ea-93d6-af130e258ce5.png">
