### ISSUE TITLE
Bolded Latin small capital letters have varying weights

### ISSUE THREAD

**Issue by alercah** [googlefonts/noto-fonts#1499]
### Font 
Noto Sans (Bold) [font not attached because it's publicly available in debian repos]

### Where the font came from, and when
Debian testing distribution, last updated Deceber 27, 2018

### Font Version
2.001;GOOG;noto-source:20181019:f8f3770;ttfautohint (v1.8.2)

### OS name and version
Debian testing

### Application name and version
Observed with Inkscape and Chrome, no reason 

### Issue
View the text in Noto Sans with bold weight anywhere. Note the inconsistent font weight: the E is quite light, for instance, compared to the very heavy B. The character weights are seemingly random.

### Character data
Unicode text (no combining characters or weirdness so copy-paste should work fine)

`ᴛʜᴇ ꞯᴜɪᴄᴋ ʙʀᴏᴡɴ ꜰᴏ ᴊᴜᴍᴘꜱ ᴏᴠᴇʀ ᴛʜᴇ ʟᴀᴢʏ ᴅᴏɢ`

(no X because Unicode has no smallcaps X. still. the Q is recent so may appear as a replacement character on many fonts)

### Screenshot
![image](https://user-images.githubusercontent.com/20842325/57052886-3003fb80-6c58-11e9-8686-5b214f047f21.png)

**Comment by nizarsq** [comment]
Bold weight looks ok in the current version (https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSans). @alercah If you have other thoughts please reopen the issue.
<img width="662" alt="Screen Shot 2020-06-29 at 10 08 59 PM" src="https://user-images.githubusercontent.com/22158882/86085878-242ae980-ba55-11ea-9c43-18a3ad5f5dc6.png">

**Comment by alercah** [comment]
SansMono-Bold appears to be missing the Q? And there is no X in any of
them; is that just because Unicode doesn't have one?

**Comment by alercah** [comment]
Actually, now that I look closely, the SansMono-Bold ones still have
varying weights, for instance the strokes are much thicker on O than on F
or R.
