### ISSUE TITLE
Adlam should add nasalization mark

### ISSUE THREAD

**Issue by sven-oly** [googlefonts/noto-fonts#1501]
## Defect Report
Use this template for filing a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
Adlam should add nasalization mark U+1E94B

### Font 
  > Full file name, for example 'NotoSansAdlam*.ttf'.
 

### Font Version
All

### OS name and version
All
### Application name and version
  > If the issue is observed using a specific app.

### Issue
Unicode 12 added 1E94B 𞥋 ADLAM NASALIZATION MARK, which looks a lot like an apostrophe. It "indicates prenasalization of succeeding consonant letter", according to the standard, similar to what we'd represent in Latin letters with "nj" or "nd" at the start of a word. This should added to our font offering for this script. We should check with our Adlam friends 
regarding the expected shape.

  1. Steps to reproduce:
  2. Observed results: this code point is not in Noto Sans Adlam
  3. Expected results: this shape should be part of the font.
  4. Additional information 
Here's the proposal for this character: https://www.unicode.org/L2/L2018/18282r-adlam.pdf

### Character data
  > Please include real character data to illustrate your issue-- Unicode codepoints are helpful.  This makes it possible for developers who don't know the language or script to copy/paste the text to reproduce the issue.

### Screenshot
  > If possible, include a screenshot or an image illustrating the issue.
  > Annotations are also helpful.

## Tools for reporting bugs
  Useful tools for reporting bugs are available at: https://github.com/googlei18n/
  
### Harfbuzz hb-view and hb-shape
  These are part of the HarfBuzz distribution and can help isolate if an issue is in the app/OS, shaping engine, or font.
  * hb-view renders the text with the exact font (for example, to see how ligatured characters shape) using your installed version of HarfBuzz.

For example:
```
  hb-view --font-file {path to font} --text-file {path to text file} --output-file '{sample}.png'
```

* hb-shape shows glyph selection and positioning

### Fontview
  * Fontview displays the text.

### Fontdiff
  * Fontdiff displays the text using two versions of the font side by side.

**Comment by r12a** [comment]
Any progress on this?  The nasalisation character  𞥋 U+1E94B ADLAM NASALIZATION MARK is used frequently in Adlam text.  

Noto Sans Adlam New supports it, however there is a gap in the baseline. If it appears between two letters that would normally join, the nasalisation character should not break that join.  (This was the reason the code point was added, rather than use other punctuation.)

![Screenshot 2020-08-01 at 12 34 34](https://user-images.githubusercontent.com/4839211/89100972-c858d500-d3f3-11ea-9ed3-d6e7699c3e01.png)

I just downloaded the latest v3 Noto Sans Adlam and Noto Sans Adlam Unjoined and though they now have glyphs for comma punctuation they still don't have a glyph for the nasalisation character.


![Screenshot 2020-08-01 at 12 41 36](https://user-images.githubusercontent.com/4839211/89101069-a4e25a00-d3f4-11ea-8c6e-b64f0f89fa6e.png)

**Comment by marekjez86** [comment]
Please check https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf or https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf ... 

<img width="1059" alt="Screen Shot 2020-09-24 at 22 35 10" src="https://user-images.githubusercontent.com/13322623/94230166-3d0d3480-feb6-11ea-86be-f35512b50c0f.png">

**Comment by r12a** [comment]
@marekjez86 i'm still seeing the problem of the broken baseline in Noto Sans Adlam.  [See the text](https://r12a.github.io/pickers/adlm/?text=%F0%9E%A4%91%F0%9E%A4%B5%F0%9E%A5%85%F0%9E%A4%A4%F0%9E%A4%A2%F0%9E%A4%A4%20%F0%9E%A4%BA%F0%9E%A4%A2%F0%9E%A4%A3%F0%9E%A4%A2%F0%9E%A4%B2%F0%9E%A4%A2%F0%9E%A4%A4%20%F0%9E%A4%8B%F0%9E%A4%B2%F0%9E%A5%86%F0%9E%A4%A2%F0%9E%A4%A5%F0%9E%A4%A2%20%F0%9E%A4%A2%F0%9E%A5%84%F0%9E%A4%A3%F0%9E%A4%AB%F0%9E%A5%85%F0%9E%A4%B6%F0%9E%A4%AD%20%F0%9E%A4%AC%F0%9E%A4%AE%F0%9E%A4%AC%20%F0%9E%A4%A8%F0%9E%A4%AE%F0%9E%A4%BC%F0%9E%A4%AD%D8%8C%20%F0%9E%A4%B2%F0%9E%A5%8B%F0%9E%A4%A3%F0%9E%A4%AD%F0%9E%A4%A5%F0%9E%A4%AF%F0%9E%A4%AD%F0%9E%A4%A3%F0%9E%A4%AD%20%F0%9E%A4%AB%20%F0%9E%A4%B6%F0%9E%A4%AD%F0%9E%A4%A6%F0%9E%A4%AD%F0%9E%A4%B2%F0%9E%A4%A2%F0%9E%A4%B2%F0%9E%A5%86%F0%9E%A4%A3%F0%9E%A4%AB%20%F0%9E%A4%BC%F0%9E%A4%AE%20%F0%9E%A4%A6%F0%9E%A4%A2%F0%9E%A4%B2%F0%9E%A5%86%F0%9E%A4%BA%F0%9E%A4%AB%20%F0%9E%A4%B8%F0%9E%A4%A2%F0%9E%A4%B3%F0%9E%A5%86%F0%9E%A4%AB%F0%9E%A5%85%F0%9E%A4%B6%F0%9E%A4%AD.%20%F0%9E%A4%89%F0%9E%A4%A9%F0%9E%A4%AB%20%F0%9E%A4%B2%F0%9E%A5%8B%F0%9E%A4%BA%F0%9E%A4%AE%F0%9E%A5%85%F0%9E%A4%A3%F0%9E%A4%AD%20%F0%9E%A4%A5%F0%9E%A4%AD%F0%9E%A5%85%F0%9E%A4%B6%F0%9E%A4%AE%20%F0%9E%A4%AB%20%F0%9E%A4%B8%F0%9E%A4%A2%F0%9E%A4%B3%F0%9E%A5%86%F0%9E%A4%AD%F0%9E%A4%A4%F0%9E%A4%A2%F0%9E%A4%B2%F0%9E%A4%BC%F0%9E%A4%A2%F0%9E%A5%84%F0%9E%A4%BA%F0%9E%A4%A2%F0%9E%A4%A4%20%F0%9E%A4%AB%F0%9E%A4%BC%F0%9E%A4%AB%20%F0%9E%A4%AB%F0%9E%A4%A9%F0%9E%A4%AB%20%F0%9E%A4%A8%F0%9E%A4%AE%F0%9E%A4%BC%F0%9E%A4%AD%20%F0%9E%A4%B8%F0%9E%A4%B5%F0%9E%A5%85%F0%9E%A4%AC%F0%9E%A4%AE%20%F0%9E%A4%B2%F0%9E%A5%8B%F0%9E%A4%A3%F0%9E%A4%AD%F0%9E%A4%AA%F0%9E%A4%A3%F0%9E%A4%AB%20%F0%9E%A4%AB%20%F0%9E%A4%B2%F0%9E%A5%8B%F0%9E%A4%A3%F0%9E%A4%AB%F0%9E%A4%AA%20%F0%9E%A4%A9%20%F0%9E%A4%AD%F0%9E%A4%B4%F0%9E%A4%B2%F0%9E%A4%BA%F0%9E%A4%B5%F0%9E%A4%B4%F0%9E%A4%B5%F0%9E%A4%A5%F0%9E%A5%86%F0%9E%A4%A2%F0%9E%A5%84%F0%9E%A4%BA%F0%9E%A4%B5.). (Select the font at lower left.)

![Screenshot 2020-09-25 at 08 07 31](https://user-images.githubusercontent.com/4839211/94237355-a4eb6b80-ff06-11ea-9d3c-cfdd5c4167f8.png)

**Comment by marekjez86** [comment]
Please try font in
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansAdlam/NotoSansAdlam-Regular.ttf

**Comment by r12a** [comment]
Same result, @marekjez86 .  For clarity, i just installed and tested Version 3.000 on Mac OS X 10.14.6 using up to date versions of Firefox and Chrome.  The previous test used the hinted version.
