### ISSUE TITLE
Consider adding Expanded widths (starting from Sans, Serif, and Sans Mono)

### ISSUE THREAD

**Issue by cssobral2013** [googlefonts/noto-fonts#1508]

**Comment by marekjez86** [comment]
What do you mean by expanded styles? For what scripts? Currently we have, NotoSansEgyptianHieroglyphs. Does it mean that you'd like to see NotoSansEgyptianHieroglyphsMono and NotoSerifEgyptianHieroglyphs?

**Comment by jungshik** [comment]
Perhaps, it's about the width. The opposite of condensed.

**Comment by cssobral2013** [comment]
Sorry for the delay in the reply, as I lunch in a popular café at midday and I was unable to reply until now. @jungshik is right, I'll edit the title.
