### ISSUE TITLE
Missing Old Hungarian Monospace font

### ISSUE THREAD

**Issue by Kixidevel** [googlefonts/noto-fonts#1509]
Is it possible make a Mono space font for Old Hungarian Unicode range? (U10c80-10cff)

Another question: what is the difference between hinted, unhinted and phase III only  font version.

**Comment by Kixidevel** [comment]
@marekjez86 
Could you make the required mono space font and answer my question above?
Thanks
Viktor

**Comment by marekjez86** [comment]
The project is open source. Anybody, assuming they know what they are doing, can take the sources located at https://github.com/googlefonts/noto-source/tree/master/src/NotoSansOldHungarian and using glyphs.app create a Mono space font for Old Hungarian Unicode range (U10c80-10cff). The new font needs to have satisfy the the SIL Open Font License, version 1.1. (see section License in https://github.com/googlefonts/noto-source ).

Re hinted, unhinted and phase III - this needs to be cleaned up, but phase III has the newly release fonts.

**Comment by Kixidevel** [comment]
I can't do that.
