### ISSUE TITLE
Update Cyrillic glyph shapes in Noto Serif

### ISSUE THREAD

**Issue by lyvrus** [googlefonts/noto-fonts#1510]
Hello! I love your font, but some lowercase cyrillic letters like н, и, п, ш, щ, ц, ч, etc. look weird and unsuitable. I think they should look like that:
![image](https://user-images.githubusercontent.com/47606856/57689989-5870fa00-7649-11e9-95db-a44ec3874a21.png)

**Comment by lyvrus** [comment]
UPD: Here`s the UFO file with fixed letters: 
https://drive.google.com/file/d/1gEiLhIaLmve7nW_Lci5b9i1R1Qi15t5i/view?usp=sharing

**Comment by marekjez86** [comment]
@lyvrus : what language are you using these with? Russian? Serbian? Macedonian? Mongolian? could you attach some photos of text with the shapes that you like here?

**Comment by marekjez86** [comment]
<img width="778" alt="Screen Shot 2019-06-21 at 12 02 20" src="https://user-images.githubusercontent.com/13322623/59945462-8dc4f080-941c-11e9-8f09-2d14c28021b1.png">

**Comment by marekjez86** [comment]
This is a Noto choice :-)
