### ISSUE TITLE
U+11446 NEWA SIGN NUKTA blocks contextual forms

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1511]
### Font
NotoSansNewa-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/4e004e66581443752669796bec7fdc8b163db493/phaseIII_only/unhinted/ttf/NotoSansNewa/NotoSansNewa-Regular.ttf
Date: 2019-05-16

### Font version
Version 2.001

### Issue
U+11446 NEWA SIGN NUKTA blocks contextual forms of consonants and vowels.

### Character data
𑐐𑑆𑐾𑐰𑑆𑐾
U+11410 NEWA LETTER GA
U+11446 NEWA SIGN NUKTA
U+1143E NEWA VOWEL SIGN E
U+11430 NEWA LETTER WA
U+11446 NEWA SIGN NUKTA
U+1143E NEWA VOWEL SIGN E

### Screenshot
![𑐐𑑆𑐾𑐰𑑆𑐾](https://user-images.githubusercontent.com/1124347/57941846-feb53d80-789d-11e9-98d6-9f10534a384a.png)

**Comment by simoncozens** [comment]
I see to have accidentally this in the re-engineered version (PR coming soon). I think there was a bigger problem with nuktas as they were not attaching do bases. Now they do, but I don't know if the new behaviour is correct or the old was. e.g.

<img width="266" alt="Screenshot 2022-02-18 at 12 15 00" src="https://user-images.githubusercontent.com/106728/154681205-79865d20-92a9-4a2c-9dce-1a3c3aed6bff.png">

What do you think?

**Comment by r12a** [comment]
So besides the position of the nukta dot, the code points in the initial comment should look like:

![Screenshot 2022-02-23 at 11 19 46](https://user-images.githubusercontent.com/4839211/155309780-d3243493-6c4a-4b55-b35f-e3b020615a16.png)

Has that also been fixed?

**Comment by simoncozens** [comment]
Yes, in the current sources, those characters look like:

![shape](https://user-images.githubusercontent.com/106728/155316316-b3826363-6f2e-4c3f-aa9e-b5c657a7e737.png)

So I think this bug is fixed.
