### ISSUE TITLE
U+02C0 "Modifier Letter Glottal Stop" is too small

### ISSUE THREAD

**Issue by Azzert** [googlefonts/noto-fonts#1513]
### Font 
NotoSansMono-ExtraCondensed.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansMono/NotoSansMono-ExtraCondensed.otf
Date: 2019-05-25

### Issue
U+02C0 (modifier letter glottal stop) and U+02C1 (modifier letter reversed glottal stop) don't share the same baseline as similiar superscript characters and look too small. They should look like lower-case versions of U+02E4 (modifier letter small reversed glottal stop).

### Character data
ʲʷʰˀˁˤ
U+02B2 modifier letter small j
U+02B7 modifier letter small w
U+02B0 modifier letter small h
U+02C0 modifier letter glottal stop
U+02C1 modifier letter reversed glottal stop
U+02E4 modifier letter small reversed glottal stop

### Screenshot
![IMG_20190519_182436](https://user-images.githubusercontent.com/29641220/57985181-b6944780-7a64-11e9-972f-dfeb8566d42a.png)

**Comment by dscorbett** [comment]
No change is needed. According to the names list, U+02C0 is a “typographical alternate for 02BC or 02BE” and U+02C1 is a “typographical alternate for 02BF”. They are symbol-like modifier letters, like U+02BE and U+02BF but modified to more resemble glottal stops. There is no need for U+02C0 to be a superscript U+0242 LATIN SMALL LETTER GLOTTAL STOP and share the same baseline as letter-based modifier letters.
