### ISSUE TITLE
Noto Sans Thai UI is not rendered in PowerPoint

### ISSUE THREAD

**Issue by thammarith** [googlefonts/noto-fonts#1514]
### Title

> Cannot use Noto Sans Thai UI with PowerPoint

### Fonts

> Noto Sans Thai UI * (every weight)

### Where the font came from, and when
>   Site: https://www.google.com/get/noto/#sans-thai
>   Date: 2019-05-19

### Font Version
> Version 2.000;GOOG;noto-source:20170915:90ef993387c0; ttfautohint (v1.7)

### OS name and 
> Windows 10 Pro 64-bit 1809 (updated to the latest stable version)

### Application name and version

> Microsoft PowerPoint 365 Version 1904 (Build 11601.20204)

### Issue
  > The default Windows font is used even though _Noto Sans UI Thai_ is selected.

#### To reproduce

1. Create a text using text box or anything will do.
2. Type something in Thai (e.g. ไก่จิกเด็กตายบนปากโอ่ง).
3. Choose _Noto Sans Thai UI_ as the font.

#### Observed results

Even though Noto Sans Thai UI is selected, the text is rendered with system default font

#### Expected results

The text is rendered with Noto Sans Thai UI

### Character data

ทดสอบภาษาไทย ถ้าใช้ได้จะต้องไม่เห็นหัว

#### Expected

![image](https://user-images.githubusercontent.com/8011543/57985200-c759b300-7a8e-11e9-89f0-5811613152e3.png)

#### Observed

![image](https://user-images.githubusercontent.com/8011543/57985209-de000a00-7a8e-11e9-8a98-65297b945bc1.png)

**Comment by thammarith** [comment]
Might related to #931, (#1046 & #902), #1477

**Comment by marekjez86** [comment]
@thammarith : thank you for the issue report.

Could you help us by
1. download and install a font from https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansThaiUI 
2. In your powerpoint select all the text you want in NotoSansThaiUI 
3. choose Noto Sans Thai UI as the font 

Please let me know if the selected text doesn't display in NotoSansThaiUI

**Comment by thammarith** [comment]
@marekjez86

It works! Thank you so much!

It seems like [google.com/get/noto](https://www.google.com/get/noto) hasn't updated the files. The latest release was on 25 October 2017 so I got the outdated files. (Even the [phase II fonts](https://github.com/googlefonts/noto-fonts/blob/master/hinted/NotoSansThaiUI-Regular.ttf) work perfectly.)
