### ISSUE TITLE
phase 3: hinted versions are outdated.

### ISSUE THREAD

**Issue by jungshik** [googlefonts/noto-fonts#1515]
phaseIII_only/hinted has not been updated for a while.  They need to be updated whenever a new version is added to phaseIII.

**Comment by jungshik** [comment]
The last time phaseIII_only/hinted was updated was last October.

{{{
commit 2450790d57da927b2c44c89995310d9ca271496f
Author: Marek Jeziorek <marekj@google.com>
Date:   Wed Oct 17 19:45:33 2018 -0700

    cleaning up a mistaken commit

commit 72c0ac136a4ecceadca7b5157b6ed511327d9ba2
Author: Marek Jeziorek <marekj@google.com>
Date:   Wed Oct 17 19:38:50 2018 -0700

    updated autohinted fonts built by an updated pipeline

commit b20c9c07139b22eb38013b1f80f9a5222c6058c6
Author: Marek Jeziorek <marekj@google.com>
Date:   Thu Oct 4 18:26:26 2018 -0700

    Updated the files that were actually autohinted

commit db5c897c3954ab8dd49bfc3de4f3ef00a7ef6d06
Author: Marek Jeziorek <marekj@google.com>
Date:   Tue Sep 4 21:14:56 2018 -0700

    adding hinted NotoSansModi
}}}

**Comment by jungshik** [comment]
@davelab6  @marekjez86

**Comment by jungshik** [comment]
@marekjez86 , if you don't know how to run freetype autohinter, ask @dougfelt .

**Comment by simoncozens** [comment]
This is now fixed, as hinted versions are being provided in the repository.
