### ISSUE TITLE
Santali fonts

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#152]
```
I am sending herewith the collection of Santali  Fonts to be added in Santali 
Language for enriching. With kind regards. 


```

Original issue reported on code.google.com by `kmurmu918@gmail.com` on 18 Sep 2014 at 5:45
- Merged into: #160

Attachments:
DELETED

**Comment by behdad** [comment]
cc @nyshadhr9

**Comment by behdad** [comment]
cc @davelab6

**Comment by sivamechh** [comment]
@Kuanra Murmu You have to use Unicode Font. The font you have provided is English in the shape of your language. Computer will understand it as English only. You have to create a Unicode Font for your language.

**Comment by bivashsoren** [comment]
OL-CHIKI BIVASH FONT DOWNLOAD HERE
http://netfile.cu.cc/uploads/91527-ol-chiki-bivash-santali-font.zip
