### ISSUE TITLE
Double kerning in Siddham

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1521]
### Font
NotoSansSiddham-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/c4e94171d04167796d0dd5e7a93e94b54ca29425/phaseIII_only/unhinted/otf/NotoSansSiddham/NotoSansSiddham-Regular.otf
Date: 2019-03-01

### Font version
Version 2.000

### Issue
'kern' and 'dist' implement some of the same kerning pairs. By default, both are applied, so the kerning is doubled. Disabling one feature or the other produces the intended rendering. The example below is a particularly exaggerated one; many are more subtle.

### Character data
𑖗𑖿𑖗𑖱
U+11597 SIDDHAM LETTER NYA
U+115BF SIDDHAM SIGN VIRAMA
U+11597 SIDDHAM LETTER NYA
U+115B1 SIDDHAM VOWEL SIGN II

### Screenshot
![𑖗𑖿𑖗𑖱](https://user-images.githubusercontent.com/1124347/58978983-05e3b300-879b-11e9-9467-a5d540b339dd.png)

**Comment by simoncozens** [comment]
This seems to have been fixed (probably by new tooling).
![shape](https://user-images.githubusercontent.com/106728/174050534-a9da00bc-a488-416b-b1f6-3ed503d32ab3.png)
