### ISSUE TITLE
Tamil supp

### ISSUE THREAD

**Issue by jungshik** [googlefonts/noto-fonts#1532]
Tamil supplement block was added in Unicode 12.0.  Total 49 characters. 

https://www.unicode.org/charts/PDF/U11FC0.pdf

Noto does not yet support them. 

@marekjez86

**Comment by marekjez86** [comment]
@jungshik : Noto doesn't support about 60-80 other updates... This one is actually in progress

**Comment by nizarsq** [comment]
@marekjez86 Any update on the supplement block? Look like NotoSerifTamil and NotoSansTamil still don't have them.

**Comment by sridatta1** [comment]
I see Separate Sans font Tamil Supplement block https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansTamilSupplement

**Comment by marekjez86** [comment]
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansTamilSupplement supports it
