### ISSUE TITLE
U+2060 'WORD JOINER' has width setting.

### ISSUE THREAD

**Issue by KazunariTsuboi** [googlefonts/noto-fonts#1533]
Fontfile: NotoSans-Regular.ttf etc...
Version: 2.001; ttfautohint (v1.8.2)

The width of the note font U+2060 (WORD JOINER) is 600.
In many typefaces, this value is set to 0.
I think that it is desirable that the 'WORD JOINER' has no character width.

**Comment by marekjez86** [comment]
test "A⁠B"

**Comment by KazunariTsuboi** [comment]
I report the comparison results of Tahoma and NotoSans.
Tahoma has a U+2060 Widht of 0.

U+2060 is inserted between "AB".
The display on Microsoft Edge 42.17134.1.0 has the following results.
Unwanted spaces appear in NotoSans.

![NotoSans-Report](https://user-images.githubusercontent.com/21096794/59809806-41ef4a00-933d-11e9-86db-29b0d2be6653.PNG)

**Comment by marekjez86** [comment]
@KazunariTsuboi : thank you. I’ll check later today every noto Latin Greek and Cyrillic font. I think all have this issue. Thanks again.

**Comment by kmuncie** [comment]
Thanks for working on this @marekjez86. Below are the results of some of my testing as well when investigating the issue. 

### Font

  'NotoSans-Regular.ttf' 

### Where the font came from, and when

  Site: https://www.google.com/get/noto/#sans-lgc
  Date: 2019-06-19

### Font Version

  Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Application name and version

    * (Windows) Microsoft Edge 44.18362.1.0
    * (Windows) Microsoft Internet Explorer 11.175.18362.0
    * (MacOS) Safari Version 12.1.1 (14607.2.6.1.1)
    * (iOS) Safari iOS Version 12.3.1 (16F203)

### Issue

  In Noto Sans the [unicode character `U+2060`](http://unicode.org/cldr/utility/character.jsp?a=2060) is being rendered incorrectly as white space in some browsers. The character seems to incorrectly have a non-zero width metric assigned to it.

  1. Steps to reproduce
    * Insert `U+2060` character between any two characters in a string using Noto Sans
  2. Observed results
    * The two characters are separated by white space in previously described browsers
  3. Expected results
    * No white space should be present in any browser

  It has been observed that Noto Sans 1.04 which is served by the Google Fonts service does not contain this character at all and falls back to other fonts to render this character.

  Both Noto Sans version 2.000 and 2.001 contain this character with a non-zero width.

  An HTML reduced test case has been created and attached to exercise this bug with Noto Sans versions 1.04, 2.000, 2.001. It also contains an example of Noto Sans 2.000 which has been generated with the width of this character set to 0 which then renders correctly in all tested browsers.

[bug-report.zip](https://github.com/googlefonts/noto-fonts/files/3310532/bug-report.zip)

### Character data

  * Word Joiner `U+2060` - [https://www.fileformat.info/info/unicode/char/2060/index.htm](https://www.fileformat.info/info/unicode/char/2060/index.htm)

### Screenshot

![noto-sans-word-joiner-bug](https://user-images.githubusercontent.com/582755/59851859-a27d8780-933b-11e9-9ac1-f3555dbbb99c.jpg)

**Comment by marekjez86** [comment]
I understand slightly more :-) 

Noto has 9 scripts with U+2060 in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf (might not apply to other versions or locations). They are:
NotoSansDisplay-Italic
NotoSansDisplay
NotoSerif-Italic
NotoSerif
NotoSerifDisplay-Italic
NotoSerifDisplay
NotoSans-Italic
NotoSans
NotoSansMono

As of 2019.06.19 in the most recent versions of Noto Fonts from https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf only NotoSans-Italic, NotoSans and NotoSansMono have U+2060 with a width 0 (last three in the list above). The top six in the list above: NotoSansDisplay-Italic, NotoSansDisplay, NotoSerif-Italic, NotoSerif, NotoSerifDisplay-Italic and NotoSerifDisplay have U+2060 having width of 600 or 1000.

I tested these fonts using notodiff (which in turn uses harfbuzz https://www.freedesktop.org/wiki/Software/HarfBuzz/ ) and to my surprise none of the tests with https://github.com/googlefonts/noto-source/blob/master/test/English/en-1533.html as the test doc, showed the problem. All PDFs were correct for all of the fonts independently of the width set for U+2060. This indicated to me that it was a character that required a special handling by the shaping engine and some shaping/rendering engines performed correctly and some shaping/rendering engines didn't. 

[en-1533-result-PDFs.zip](https://github.com/googlefonts/noto-fonts/files/3311976/en-1533-result-PDFs.zip)

Therefore the handling of U+2060 is browser dependent (e.g., Chrome should be able to handle it no matter what the width value is). Looks that the shaper on some Windows browser combinations has a problem. Possibly other systems also.

Note that, IMHO, U+2060 is defined such that every shaping engine should handle it properly no matter what its width is in a font. However some systems have buggy implementations, therefore some of the fonts provide a workaround to this bug by making U+2060 width to be 0 to "cover" the bug.

We'll make all U+2060 in all Noto fonts consistent width of 0.

**Comment by marekjez86** [comment]
@kmuncie @KazunariTsuboi : modified NotoSansDisplay-Italic, NotoSansDisplay, NotoSerif-Italic, NotoSerif, NotoSerifDisplay-Italic, NotoSerifDisplay to support 0 width workaround for U+2060

see, for example, https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansDisplay or https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansDisplay where you can find NotoSansDisplay-Italic and NotoSansDisplay

**Comment by KazunariTsuboi** [comment]
@marekjez86  : Thank you very much for your prompt response.

NotoSans and Notosans-Italic continue to have problems with U+2060.
Looking at https://github.com/googlefonts/noto-source/blob/master/src/NotoSans-MM.glyphs,  https://github.com/googlefonts/noto-source/blob/master/src/NotoSans-ItalicMM.glyphs, only Regular, SemiBold and Bold instances seem to have a character width of 600.
We hope this issue will be resolved in the future.

**Comment by kmuncie** [comment]
> Noto has 9 scripts with U+2060 in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf (might not apply to other versions or locations). They are:
> NotoSansDisplay-Italic
> NotoSansDisplay
> NotoSerif-Italic
> NotoSerif
> NotoSerifDisplay-Italic
> NotoSerifDisplay
> NotoSans-Italic
> NotoSans
> NotoSansMono
> 
> As of 2019.06.19 in the most recent versions of Noto Fonts from https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf only NotoSans-Italic, NotoSans and NotoSansMono have U+2060 with a width 0 (last three in the list above). The top six in the list above: NotoSansDisplay-Italic, NotoSansDisplay, NotoSerif-Italic, NotoSerif, NotoSerifDisplay-Italic and NotoSerifDisplay have U+2060 with the width of 600 or 1000.

@marekjez86 I have pulled down the latest changes from this repo and still see this issue in many of the fonts you listed above. I just verified the issue still exists in the following files, and likely many more. 

- phaseIII_only/unhinted/ttf/NotoSans-Regular.ttf
- phaseIII_only/unhinted/ttf/NotoSans-Bold.ttf
- phaseIII_only/unhinted/ttf/NotoSans-Italic.ttf
- phaseIII_only/unhinted/ttf/NotoSans-BoldItalic.ttf

You originally did not list Bold or BoldItalic in your findings. Will these and other variants with the problem going to be adjusted to fix this issue as well?

> We'll make all U+2060 in all Noto fonts consistent width of 0.

Is this expected to be a long term project to set a consistent width or will all fonts be adjusted in the near future?

**Comment by marekjez86** [comment]
@kmuncie : in 2-3 days

**Comment by marekjez86** [comment]
@kmuncie @KazunariTsuboi : U+2060 should have width 0 for all widths/weights/versions which can be found in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted for all:

- NotoSansDisplay-Italic
- NotoSansDisplay
- NotoSerif-Italic
- NotoSerif
- NotoSerifDisplay-Italic
- NotoSerifDisplay
- NotoSans-Italic
- NotoSans
- NotoSansMono
-

**Comment by KazunariTsuboi** [comment]
@marekjez86 I was able to learn some of the ways in which issues are handled.  I want to contribute more to Noto project in some way. 
Thank you again for your huge work!
