### ISSUE TITLE
NotoSans GujaratiUI ⟨દ્વ⟩ Decompose against the intuition

### ISSUE THREAD

**Issue by KazunariTsuboi** [googlefonts/noto-fonts#1537]
When I used NotoSans GujaratiUI, I noticed a combination that causes unnatural decomposition.
Unnatural decomposition is displayed by the combination marked yellow.
The string used is as follows.
દ્ઘ દ્ઘ્ દ્ઘુ દ્ઘૂ દ્ઘૃ
દ્વ દ્વ્ દ્વુ દ્વૂ દ્વૃ

![グジャラティUIバグ報告](https://user-images.githubusercontent.com/21096794/60059997-bf460080-9729-11e9-8503-abdaf12d3bb9.png)

I understand that UI fonts are subject to vertical width constraints, but I do not think that it is desirable that only these combinations be decomposed.
It is desirable to be displayed in combination synthesized like NotoSansGujarati which is not UI.

Display result of NotoSansGujarati
![Gujarati](https://user-images.githubusercontent.com/21096794/60060005-c5d47800-9729-11e9-8b87-2ffcba424cf6.PNG)

**Comment by JelleBosmaMT** [comment]
The height restriction of the UI font requires a special squished variant of these ligatures, if they are combined with one of the low marks. It did not seem worth the effort to draw a variant if it is just for a theoretical combination, for which we didn't find a real world use case.

**Comment by marekjez86** [comment]
@KazunariTsuboi : per Jelle's comment closing the issue. However, if you find real life words, please attach them here and we'll consider reopening the issue. Thanks for pointing it out.
