### ISSUE TITLE
Tibetan sans and serif look identical

### ISSUE THREAD

**Issue by KazunariTsuboi** [googlefonts/noto-fonts#1540]
I noticed that Noto**Serif**Tibetan and Noto**Sans**Tibetan exist.
Noto**Sans**Tibetan has not been updated since 2015.
On the other hand, Noto**Serif**Tibetan is still actively maintained.
What I wonder is that the design of Noto**Sans**Tibetan is almost identical to Serif.

Noto**Sans**Tibetan
![image](https://user-images.githubusercontent.com/21096794/60309607-9459e780-9989-11e9-98e2-c5b6e6953917.png)

Noto**Serif**Tibetan
![image](https://user-images.githubusercontent.com/21096794/60309579-78564600-9989-11e9-9895-436c827dec7c.png)

Is Noto**Sans**Tibetan expected to be updated in the future?
Or will it be maintained as NotoSerifTibetan?

**Comment by marekjez86** [comment]
we just decided to rename NotoSansTibetan as NotoSerifTibetan. This will be the only designation as we move forward. I'll keep this issue open until all places are consistent

**Comment by marekjez86** [comment]
NotoSerifTibetan should be the ONLY font available.

**Comment by Kanjilearner817** [comment]
Would you consider commissioning an _actual_ sans-serif Tibetan font, similar to the commercially available "Pema"?
https://designpiraten.com/portfolio/pema-tibetan-sans-serif/
