### ISSUE TITLE
Noto sans Arabic not working on PowerPoint

### ISSUE THREAD

**Issue by MDCR55** [googlefonts/noto-fonts#1542]
### Font 
  > Noto Sans Arabic'.

### Where the font came from, and when
![WINWORD_QPIZZGHuAN](https://user-images.githubusercontent.com/16103729/60381676-31d41a80-9a61-11e9-9dbf-015bc3d3a6f5.png)

### OS name and version
  > Windows 10

### Application name and version
  > Microsoft PowerPoint 365. v16.0.11629.20238

### Issue
  > The font "Noto Sans Arabic" not working while the it is working correctly on Microsoft Word.. same problem with the font 'Noto Kufi Arabic'

**Comment by MDCR55** [comment]
#1599

**Comment by nizarsq** [comment]
Tested the reported issue on Powerpoint 16.0.11929.20392 and the issue not reproducible, I'm assuming the issue fixed. I used NotoSansArabic in this directory https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansArabic. Closing the bug for now.
![NotoSansArabic-1542](https://user-images.githubusercontent.com/22158882/84462065-dde72500-ac22-11ea-9d10-2a909139c522.png)

**Comment by MDCR55** [comment]
> Tested the reported issue on Powerpoint 16.0.11929.20392 and the issue not reproducible, I'm assuming the issue fixed. I used NotoSansArabic in this directory https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansArabic. Closing the bug for now.
> ![NotoSansArabic-1542](https://user-images.githubusercontent.com/22158882/84462065-dde72500-ac22-11ea-9d10-2a909139c522.png)

Thanks! I have tested the fonts and it worked with Arabic, yet there another problem when writing in English, it shows blank rectangles.. could you try to re-produce the problem at your side to verify it ?

Thanks again Nizar, 
Your efforts are much appreciated

**Comment by nizarsq** [comment]
> > Tested the reported issue on Powerpoint 16.0.11929.20392 and the issue not reproducible, I'm assuming the issue fixed. I used NotoSansArabic in this directory https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansArabic. Closing the bug for now.
> 
> Thanks! I have tested the fonts and it worked with Arabic, yet there another problem when writing in English, it shows blank rectangles.. could you try to re-produce the problem at your side to verify it ?
> 
> Thanks again Nizar,
> Your efforts are much appreciated

Mohammad, you are very welcome, I'm glad the issue solved. Please file separate bug for the issue you are seeing now, separate bug will make it easier to track issues. Thanks again

**Comment by RehngruppenEF** [comment]
It seems like there is an older version published at https://www.google.com/get/noto/ that does not currently work in PowerPoint. The ones on github 
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansArabic
https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf/NotoSansArabic 
(updated links) does work though.

**Comment by mdqara** [comment]
There is a problem with the english letters appears as blank rectangles .. but the Arabic works well in PowerPoint
P.S. I have tested both hinted and unhinted.

see the screenshot
!(https://i.imgur.com/RPnE812.png)[]

**Comment by RehngruppenEF** [comment]
> There is a problem with the english letters appears as blank rectangles .. but the Arabic works well in PowerPoint
> P.S. I have tested both hinted and unhinted.

Latin glyphs are note included in Noto Sans Arabic.

**Comment by mdqara** [comment]
> > There is a problem with the english letters appears as blank rectangles .. but the Arabic works well in PowerPoint
> > P.S. I have tested both hinted and unhinted.
> 
> Latin glyphs are note included in Noto Sans Arabic.

Is there any way to merge the english font with the arabic font to have both language in one font ?

**Comment by RehngruppenEF** [comment]
> Is there any way to merge the english font with the arabic font to have both language in one font ?

I have never tried this, but you should be able to in FontForge (win/mac/linux)
https://fontforge.org/en-US/downloads/
https://linuxhint.com/merge_two_fonts_linux/

**Comment by RehngruppenEF** [comment]
> > > There is a problem with the english letters appears as blank rectangles .. but the Arabic works well in PowerPoint
> > > P.S. I have tested both hinted and unhinted.
> > 
> > 
> > Latin glyphs are note included in Noto Sans Arabic.
> 
> Is there any way to merge the english font with the arabic font to have both language in one font ?

I've revisited this and if you want Noto Sans Arabic for arabic text and for example Arial for latin text in PowerPoint (or any other Office application) you can set it up by editing the font theme (located in %appdata%\Microsoft\Templates\Document Themes\Theme Fonts) to look like the following:

cs = complex script and is used for the arabic glyphs.

<a:fontScheme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="Arabic">
	<a:majorFont>
		<a:latin typeface="Arial"/>
		<a:ea typeface=""/>
		<a:cs typeface="Noto Sans Arabic"/>
	</a:majorFont>
	<a:minorFont>
		<a:latin typeface="Arial"/>
		<a:ea typeface=""/>
		<a:cs typeface="Noto Sans Arabic"/>
	</a:minorFont>
</a:fontScheme>
