### ISSUE TITLE
NotoSerifTibetan-Regular.ttf has many unused glyph names in "post" table

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/noto-fonts#1543]
### Font 
NotoSerifTibetan-Regular.ttf

### Where the font came from, and when
https://github.com/googlefonts/noto-fonts/blob/2a41389346abdb6b83f5e0c4efe598bcb8abbb42/phaseIII_only/unhinted/ttf/NotoSerifTibetan/NotoSerifTibetan-Regular.ttf

### Issue
While debugging https://github.com/fontforge/fontforge/issues/3740, I noticed that the fonts has many glyph names in the `post` table that are not used.

The font has 1891 glyphs, while there are 3772 names in the `post` table (as seen in the ttx dump).

While this is not strictly a bug, it seems wasteful to include such unused data. It might also indicate an issue in the sources or the font generation pipelines.

**Comment by punchcutter** [comment]
It has the production names AND the non-production names in there. That sounds like an issue with the fontmake pipeline because it should be either `--no-production-names` or it uses them. That post table looks like a mix.

**Comment by khaledhosny** [comment]
Bug in ufo2ft, will fix there.
