### ISSUE TITLE
Subjoined consonants block contextual U+1112D CHAKMA VOWEL SIGN AI

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1546]
### Font
NotoSansChakma-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/dbfc8a1858732279842454cac5da2ea1ff691a24/hinted/NotoSansChakma-Regular.ttf
Date: 2018-10-23

### Font version
Version 2.001;GOOG;noto-source:20181019:f8f3770;ttfautohint (v1.8.2)

### Issue
Some marks above get shorter forms above certain consonants, but that substitution is blocked when the consonant has a subjoined consonant.

### Character data
𑄉𑄳𑄉𑄭
U+11109 CHAKMA LETTER GAA
U+11133 CHAKMA VIRAMA
U+11109 CHAKMA LETTER GAA
U+1112D CHAKMA VOWEL SIGN AI
𑄉𑄭
U+11109 CHAKMA LETTER GAA
U+1112D CHAKMA VOWEL SIGN AI

### Screenshot
![𑄉𑄳𑄉𑄭 𑄉𑄭](https://user-images.githubusercontent.com/1124347/60530442-ba072980-9cc6-11e9-85bd-df8c34a72848.png)

**Comment by punchcutter** [comment]
Addressed in latest update

<img width="59" alt="chakma1546" src="https://user-images.githubusercontent.com/11257204/132978471-970614f7-7b58-4723-96dc-a3bd814aae2e.png">

**Comment by marekjez86** [comment]
Source code change https://github.com/googlefonts/noto-source/pull/402 fixed the issue. Please see hinted font at https://github.com/googlefonts/noto-fonts/tree/main/hinted/ttf/NotoSansChakma or unhinted at https://github.com/googlefonts/noto-fonts/tree/main/unhinted/ttf/NotoSansChakma . Thank you @punchcutter
