### ISSUE TITLE
NotoSerifGujarati Unfamiliar combination (શ્લ)

### ISSUE THREAD

**Issue by KazunariTsuboi** [googlefonts/noto-fonts#1548]
### Font 
NotoSerifGujarati-Regular.ttf

### Font Version
Version 2.000; ttfautohint (v1.8.2)

### Character data
શ્લ(0AB6, 0ACD, 0AB2)

### Issue
This glyph is different from the NotoSansGujarati and some other fonts.
The form that I am familiar with is NotoSansGujarati.
On Windows 10, Shruti is installed by Gujarati LanguagePack.
The shape of Shruti is similar to NotoSans.

NotoSansGujarati
![image](https://user-images.githubusercontent.com/21096794/60635592-48f27e00-9e4e-11e9-8933-e4c52167c440.png)

NotoSerifGujarati
![image](https://user-images.githubusercontent.com/21096794/60635605-514ab900-9e4e-11e9-90b8-1157d4a0fa89.png)

Shruti
![image](https://user-images.githubusercontent.com/21096794/60635617-5a3b8a80-9e4e-11e9-840c-2dec662d708a.png)

It's great that Notofont is united as a family.
Of course I understand that there is a difference in design between Sans and Serif, but I think it is desirable that the arrangement be uniform to some extent.

**Comment by marekjez86** [comment]
fixed in https://github.com/googlefonts/get-noto/tree/master/unhinted/Gujarati
