### ISSUE TITLE
Chakma ligatures use 'liga' instead of 'rlig'

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1552]
### Font
NotoSansChakma-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/7cc126f6c0ebfe750dc911dae951f9167d36213e/phaseIII_only/unhinted/ttf/NotoSansChakma/NotoSansChakma-Regular.ttf
Date: 2019-07-07

### Font version
Version 2.001

### Issue
Noto Sans Chakma uses 'liga' for required ligatures where it should use 'rlig'. 'liga' is for ligatures that should be on by default but may be disabled by the user.

### Character data
𑄑𑅆
U+11111 CHAKMA LETTER TTAA
U+11146 CHAKMA VOWEL SIGN EI

### Screenshot
Default:
![𑄑𑅆](https://user-images.githubusercontent.com/1124347/60768127-4d59a980-a08f-11e9-9909-2fb4559cdd0c.png)
With 'liga' turned off:
![𑄑𑅆](https://user-images.githubusercontent.com/1124347/60768128-4d59a980-a08f-11e9-9450-def07a33a6fb.png)

**Comment by punchcutter** [comment]
Removed `liga` entirely because it's not really the right one to use as shown here. Moved these substitutions to `psts` instead since that's what they actually are.

**Comment by marekjez86** [comment]
Source code change https://github.com/googlefonts/noto-source/pull/402 fixed the issue. Please see hinted font at https://github.com/googlefonts/noto-fonts/tree/main/hinted/ttf/NotoSansChakma or unhinted at https://github.com/googlefonts/noto-fonts/tree/main/unhinted/ttf/NotoSansChakma . Thank you @punchcutter
