### ISSUE TITLE
In NotoSans-Regular package has below fonts has 2048 UPM so problem in merge.

### ISSUE THREAD

**Issue by ashakoshti1988** [googlefonts/noto-fonts#1560]
All the below fonts are having 2048 UPM instead of 1000,so i am not able to merge this fonts with others,please help on this.
'NotoSansJavanese-Regular.ttf',
'NotoSansKaithi-Regular.ttf',
'NotoSansKharoshthi-Regular.ttf',
'NotoSansLepcha-Regular.ttf',
'NotoSansLimbu-Regular.ttf',
'NotoSansMeeteiMayek-Regular.ttf',
'NotoSansMongolian-Regular.ttf',
'NotoSansPhagsPa-Regular.ttf',
'NotoSansRejang-Regular.ttf',
'NotoSansSaurashtra-Regular.ttf',
'NotoSansSundanese-Regular.ttf',
'NotoSansSylotiNagri-Regular.ttf',
'NotoSansSyriacEastern-Regular.ttf',
'NotoSansTagalog-Regular.ttf',
'NotoSansTagbanwa-Regular.ttf',
'NotoSansTaiLe-Regular.ttf',
'NotoSansTaiTham-Regular.ttf',
'NotoSansTaiViet-Regular.ttf',
'NotoSansThaana-Regular.ttf',

**Comment by marekjez86** [comment]
for the following files please get them from a corresponding directory in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf 

- NotoSansJavanese-Regular.ttf
- NotoSansKaithi-Regular.ttf
- NotoSansKharoshthi-Regular.ttf
- NotoSansLepcha-Regular.ttf
- NotoSansLimbu-Regular.ttf
- NotoSansMeeteiMayek-Regular.ttf
- NotoSansMongolian-Regular.ttf
- NotoSansPhagsPa-Regular.ttf
- NotoSansRejang-Regular.ttf
- NotoSansSaurashtra-Regular.ttf
- NotoSansSundanese-Regular.ttf
- NotoSansSylotiNagri-Regular.ttf
- NotoSansTagalog-Regular.ttf
- NotoSansTagbanwa-Regular.ttf
- NotoSansTaiLe-Regular.ttf
- NotoSansTaiViet-Regular.ttf
- NotoSansThaana-Regular.ttf
-

For NotoSansSyriacEastern-Regular.ttf see https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansSyriac/NotoSansSyriac-Regular.ttf ... 

I don't have a solution and a date for NotoSansTaiTham-Regular.ttf , but we are working on it
