### ISSUE TITLE
Too many files in directories

### ISSUE THREAD

**Issue by verdy-p** [googlefonts/noto-fonts#1561]
There are really too many files in the directory of fonts (notably the hinted and unhinted ones, possibly as well for some staged versions)

I really suggest using one directory by font family, or by ISO 15924 script code (like "Latn" for the base fonts, "Zsym" for symbols, "Szye" for emojis), and put in them all related font variants (bold, italic, various weights, cursive/unjoined).

This would limit the number of directories to less than 300 instead of having more than 1800 files (in hinted fonts) that are hard to find and nearly one half fonts hidden to users.

And this would allow working on fonts having common properties, related to the script they support.

----
Note that Noto font names are not always consistant, some of them using abbreviations, some of them using spaces between words, some not: why don't you use the "Unicode Alias" (as displayed in the ISO 15924 RA site and defined in Unicode), just replacing the underscore separator by a space, so that these names (except Latin which is ommited) are directly predictable from Unicode properties, and just trying to prefix "Noto Sans" or "Noto Serif" before these names, without having to constantly check the long list of Noto fonts to define the CSS stylesheets ?

Also I suggest that ALL fonts include in their internal list of names a short synonym/alias based on the 4-letter ISO 15924 script code like "Noto Sans ISOLatn", "Noto Sans ISOCyrl", "Noto Sans ISOHans", "Noto Sans ISOArab", ISO Sans ISOAran", ...

* For CJK fonts, the ISO15924 codes to use should be: Hans, Hant, Jpan, Kore (rather than "CJK CN/TW/JP/KR"); the "Jpan" font containing also Hiragana and Katakana, the "Kore" font containing also Hangul and Jamos, the "Hans" and Hant" possibly both containing Bopomofo (or only one in "Hanb" ?); but you may want to separate "Hrkt" and "Bpmf". The "Hani" code would not be used. A new ISO 15924 code ("Hanv") could be requested for Vietnamese Chu Nôm if it must differ significantly from "Hant" (my opinion is that those differences are small, and could be handled in the "Hant" font as language variant).

* For the two variants of Arabic, the ISO 15924 code is Arab for the simpler Western style (joining horizontally), Aran for the Eastern/Persian/Urdu/Nastaliq style (joining diagonally, so that it's much more complex to design for positioning/styling and managing more kinds of junctions).

* For Latin, the "Latf" and "Latg" codes could be used in font names for these wellknown style variants, 

* Another ISO 15924 code ("Latj" ?) should be requested for the Latin cursive/joining style (and in my opinion, for Latin, we should request to Unicode the allocation of an explicit "cursive joiner" character like the one that exists in Unicode for Arabic (it could be used as well for Devanagari and all other LTR scripts, the cursive joiner defined for Arabic could be used for any other RTL script if they need it for their own cursive style :  it would be convenient to allow better presentation of joining scripts with justified text, where a renderer cannot simply increase the gap between letters without inserting visible joiner glyphs; however the joiner glyphs must be mapped in fonts and there's currently no simple way to do that cleanly like we can do that for Arabic). If there's a joiner glyph defined in the font, its default metric should be the average width of one letter in the script (so this is a visible character, and by default in non-cursive styles, it should be a stroke on the default baseline, not above it, not below it; in cursive styles, the stroke will be adapted to the joining location of letters on both sides and the font will remap some glyph variants for various heights, the renderer will then insert as many glyphs as needed to fil lthe gap; this glyph can also be implicitly divided by the renderer in three parts (left/central/right) to compose what is needed. OpenType however could allow defining metrics for each letters so that they indicate which part on the left or right is a joiner to the next letter, so that this part can be replaced, or these lateral subglyphs could be references to a joining type; the renderer will then compute the matrix of joining types to infer the accurate joiner to use between them, while rendering only the central part of the glyph. the other parts being drawn by the rules on joining types (exactly like for Arabic)

**Comment by verdy-p** [comment]
Note that the naming scheme for directories currently used in "Phase_III" is almost fine (except that it uses the unnecessary "ttf" parent folder for "hinted" fonts, but not for the "unhinted" fonts) and could be used as well for the base "hinted" and "unhinted" directories (that are really overpopulated now, making the repository difficult to navigate to find relevant fonts).

If necessary replace these fonts in "hinted" and "unhinted" folders by symbolic links into subdirectories that will be listed first before the long list of symbolic links (that may be truncated in navigation)

Or create a new parent "/supported" for "hinted/*" and unhinted/*" fonts by creating directories per family in "/supported/hinted/" and "/supported/unhinted/". The legacy folders "/hinted" and "/unhinted" will then remain overpopulated but will only contain symbolic links for compatibility.

**Comment by marekjez86** [comment]
@verdy-p : thanks for the feedback... I restructured some but this needs further thinking... Thanks

**Comment by verdy-p** [comment]
OK, so you applied the to the "hinted/" folder naming scheme that was used in Phase_III, but it should be used as well for "unhinted/".
And there's still "Phase_III/ttf" instead of just "Phase_III" (I don't see the interest of the "ttf" subfolder, unless you intend to provide other unhinted formats, like SVG fonts).

**Comment by marekjez86** [comment]
@verdy-p : do you still think that "/supported/hinted/family/anyfont" and "/supported/unhinted/family/anyfont" (my understanding is that anyfont would include OTF, TTF and Variable fonts) is the right way to go?  Sorry it took me that long to consider this...

**Comment by verdy-p** [comment]
"hinted" vs. "unhinted" is a correct status for such support phases.

I don't see any useful case for "family".

I have no opinion about "anyfont" (OTF is a superset of TTF with more feature, TTF being considers a level with lower support could be useful for phases; "variable font" is an advanced feature, just like colored fonts notably for emojis, that require advanced support in renderers)

Now there are other competing distribution formats for embedding, or web hosting, some fonts are any available as webfonts (to be cached on the redering host but requiring a transaction to get a licence for use, and being updated automatically via requests to the web or a licencing server); as well there are fonts only in SVG format (whose support of more advanced features is growing, even if it's still far below the coverage of OTF, it has in practice almost everything from TTF and may be already useful for simple scripts that don't require GPOS/GSUB features for proper composition and full Unicode compliance for composition features required by the script in the standard)

**Comment by verdy-p** [comment]
I consider my bufg report being solved now; the directories are now coherently names and populated and are easily navigatable. Thanks for the reorganization work that will help many.
