### ISSUE TITLE
Siddham character U+0115A1 (na) looks different

### ISSUE THREAD

**Issue by Sagir8453** [googlefonts/noto-fonts#1563]
## Defect Report
The Siddham character na in the noto font looks different from that in other fonts, unicode block pdf and manuscripts. Is it unique to the Noto Sans Siddham font or taken from somewhere?

### Font 
  > NotoSansSiddham-regular.otf

### Where the font came from, and when
  >   Site: https://github.com/googlei18n/noto-fonts/blob/c4e94171d04167796d0dd5e7a93e94b54ca29425/phaseIII_only/unhinted/otf/NotoSansSiddham/NotoSansSiddham-Regular.otf
  >   Date: 2019-07-22 (preferred format)

### Font Version
  Current version of 2019-07-22

### Issue
  >

### Character data
U+0115A1

### Screenshot
![text (96)](https://user-images.githubusercontent.com/22221772/61653813-c3d5e880-acd8-11e9-9673-791c1d3b5ac5.png)
NotoSansSiddham
![text (97)](https://user-images.githubusercontent.com/22221772/61653835-d2bc9b00-acd8-11e9-9ead-e32db381b52d.png)
MuktamSiddham
![text (98)](https://user-images.githubusercontent.com/22221772/61653860-df40f380-acd8-11e9-9ec5-b73b640a8c85.png)
ApDevSiddham
![Screenshot_20190722-233313](https://user-images.githubusercontent.com/22221772/61654036-3c3ca980-acd9-11e9-8d58-7cc36f02d800.png)
From its unicode pdf

**Comment by Sagir8453** [comment]
Apparently it's used in a variation which seems rare. It seems more people use the variation used in other fonts, I guess it'd be better to use the more common variation and moving the current to an alternative form cell.

**Comment by nizarsq** [comment]
@marekjez86 for design opinion 
https://unicode.org/charts/PDF/U11580.pdf
<img width="755" alt="Screen Shot 2020-09-18 at 5 48 15 PM" src="https://user-images.githubusercontent.com/22158882/93655236-2444e080-f9d7-11ea-8c4f-af20aa5d0711.png">
<img width="1326" alt="Screen Shot 2020-09-18 at 5 49 47 PM" src="https://user-images.githubusercontent.com/22158882/93655299-5b1af680-f9d7-11ea-9c23-bfff97d22c3f.png">

**Comment by Tosche** [comment]
This is a valid form as you can see (taken from 梵字大鑑). Noto Siddham's style is based on flat-nib style which is older and considered more authentic. Japanese monks developed brush styles over the centuries which became less-defined, abbreviated, and sometimes far removed from the earlier forms. Some letters may therefore look different in modern expectation, but they are all older forms and more appropriate in the chosen style.
![IMG_1900](https://user-images.githubusercontent.com/5482424/109802493-cb30d800-7c17-11eb-8433-78fd3ddc182b.jpg)
