### ISSUE TITLE
incorrect link to GitHub repository from https://www.google.com/get/noto/

### ISSUE THREAD

**Issue by verdy-p** [googlefonts/noto-fonts#1568]
The Google website for "Get Noto" (https://www.google.com/get/noto/) has a link to a defunct repository. It points to the Google's Internationlization repository (https://github.com/googlei18n?query=noto) which is now empty instead of pointing to this repository (https://github.com/googlefonts).

Note that to find this repository, you have to use the links further down pointing to the release note and then navigate in GitHub to get to the root.

Can this be fixed on the "Get Noto" website (this is the first link indicated in the site description under "GitHub Repositories") ?

i.e. replace `href="https://github.com/googlei18n?query=noto"` by `href="https://github.com/googlefonts/noto-fonts"`.

Thanks.

**Comment by simoncozens** [comment]
The Noto website has now been redesigned and correct links to the repository are available at https://fonts.google.com/noto/contribute#propose-changes

**Comment by verdy-p** [comment]
Your reply is not accurate: I'm not speaking about the "Noto font distribution site (which has also changed) but the link to the development repository in GitHub which was displayed on the "Get Noto" distribution sites. There are still incorrect links there pointing to the wrong place (and in fact there are also multiple repositories: one open for incoming proposals that are in alpha/beta stages for later inclusion, and with many forks, and another which integrates fonts finally selected for the final Noto bundle to be supported and made finally available for distribution with the "Get Noto" website, or for other distribution sites like Noto "packages" prepared by each OS vender for specific OSes, like Android or Linux distribs

(There used to be a Windows distribution site with Noto bundles maintained in sync with a specific installable Windows app, but apparently it is no longer available, deprecated in favor of the "Get Noto" website. Unfortunately, when we use the "Get Noto" website to install fonts on Windows, the Windows Update will silently discard their installation at EACH installation of a new Windows build: these Noto fonts have to be reinstalled once again on the system, and there's now no way to resynchronize them automatically after every Windows build upgrade: this is a pain for those that upgrade Windows often, like "Windows Insiders" but even for regular Windows users that are forced to install a new build every 6 months: all their installed fonts disappear... We really need now a tool to resynchronize and update these Noto fonts on Windows, if we don't want to resort to using Google Webfonts only in web browsers for their use online: webfonts are too slow for daily use and unusable offline or for users with slow internet accesses, or too costly for those with mobile accesses with metered data volumes and with limited capacity of storage for the web caches of each local user and each web browser or web app).

**Comment by twardoch** [comment]
I’m not sure I understand: are you reporting the issue about the »get Noto« website, which no longer exists, and are you saying that when the website existed, it had a link to a Github repo, which now also no longer exists? 

The URL for the website that no longer exists now redirects to a new website. The new website points to the new Github repo. 

AFAIK, when a Github repo gets deleted, there is no way to set up redirects. So I guess you’ll need to update the URLs in the places that refer to the repo that no longer exists.

**Comment by twardoch** [comment]
I think the Noto fonts would benefit from a better structure of the released fonts, with labeled Github releases and a clarified relationship between the static and variable fonts. There is interest in developing a better structure. But if this happens, I don’t think it will happen in a way which could also ensure that links pointing to a nonexistent repo continue to work.
