### ISSUE TITLE
Greek letters with multiple diacritics cannot be displayed correctly

### ISSUE THREAD

**Issue by mkpoli** [googlefonts/noto-fonts#1573]
## Defect Report
Use this template for filing a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
  > Should be brief but contain essential information.

### Font 
  > NotoSans-Regular.ttf and all related fonts. Except Noto Sans Mono.

### Where the font came from, and when
  >   Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-hinted.zip
  >   Date: 2019-09-09

### Font Version
  > Version 1.06

### OS name and version
  > Windows 10 1803

### Application name and version
  > Chrome 76.0.3809.132

### Issue
  1. Steps to reproduce: Trying to display any greek letter with macron and acute accent at the same time.
  2. Observed Results: As image (using Noto Sans):
![Noto Sans](https://user-images.githubusercontent.com/3502597/64529091-0dd86380-d345-11e9-9c21-ffd334801d2c.png)
  3. Expected Results: As image (using Noto Sans Mono):
![Noto Sans Mono](https://user-images.githubusercontent.com/3502597/64529112-1a5cbc00-d345-11e9-9308-823845d0e011.png)

HTML file for testing: 

`<html>

<head>
    <style>
        .font {
            font-family: 'Noto Sans';
        }
    </style>
</head>

<body>
    <p>
        <h1>Greek</h1>
        <span lang="grc" class="font">alphabet + macron + accent: NFC ᾱ́ῑ́ῡ́ NFD ᾱ́ῑ́ῡ́</span>
        <br/>
        <span lang="grc" class="font">alphabet + accent + macron: NFC ά̄ί̄ύ̄ NFD ά̄ί̄ύ̄</span>
    </p>

    <p>
        <h1>Latin</h1>
        <span lang="lat" class="font">alphabet + macron + accent: NFC ā́ī́ū́ NFD ā́ī́ū́</span>
        <br/>
        <span lang="lat" class="font">alphabet + accent + macron: NFC á̄í̄ú̄ NFD á̄í̄ú̄</span>
    </p>

</body>

</html>`

**Comment by nizarsq** [comment]
I believe this issue has been resolved using  fonts in this directory:
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSans
and
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSerif
Closing the bug for now, please reopen if you have other thoughts.
<img width="499" alt="Screen Shot 2020-06-28 at 9 45 32 PM" src="https://user-images.githubusercontent.com/22158882/85973899-fed0a980-b988-11ea-827f-50a38efa6f04.png">
