### ISSUE TITLE
Shape of U+0600 ARABIC NUMBER SIGN in Noto Nastaliq Urdu

### ISSUE THREAD

**Issue by saadatm** [googlefonts/noto-fonts#1574]
### Fonts
**NotoNastaliqUrdu-Regular.ttf**
Version 1.02uh
 _Came from:_ https://noto-website-2.storage.googleapis.com/pkgs/NotoNastaliqUrdu-unhinted.zip
_Date:_ 2019-09-14
_README says this:_
> Built on 2017-10-24 from the following noto repository:
> 
> Repo: noto-fonts
> Tag: v2017-10-24-phase3-second-cleanup
> Date: 2017-10-24 12:10:34 GMT
> Commit: 8ef14e6c606a7a0ef3943b9ca01fd49445620d79

**NotoNastaliqUrdu-Regular.ttf**
Version 2.000
_Came from:_ https://github.com/googlefonts/noto-fonts/blob/master/unhinted/NotoNastaliqUrdu/NotoNastaliqUrdu-Regular.ttf
_Date:_ 2019-09-14

### Issue
In v1.02uh, `U+0600 ARABIC NUMBER SIGN` has two shapes:
* Shape 1: when it is isolated, or followed by a single digit
* Shape 2: when it is followed by two or more digits
![noto-1 02uh-number-sign](https://user-images.githubusercontent.com/6615143/64906400-a123e700-d6ff-11e9-87b6-c3f1f0064a2b.png)

<hr>

In v2.000, this is corrected and `U+0600` has a single shape (Shape 2), no matter the context of its usage:
![noto-2 000-number-sign](https://user-images.githubusercontent.com/6615143/64906405-ad0fa900-d6ff-11e9-90b8-5299af5e9b66.png)

<hr>

I personally prefer Shape 1, and think that it matches the rest of the font design better than Shape 2. Shape 1 also closely resembles the words `نمره ` or `نمبر` (from which `U+0600` was [most probably derived](https://twitter.com/tntype/status/917318052571688962).)

So here's my request: can we please bring Shape 1 back for `U+0600`? If Shape 2 must be the default, then maybe Shape 1 can be made available under a stylistic set or as a character variant?

**Comment by saadatm** [comment]
Forgot to add the test strings:
```
؀
؀۱
؀۱۲
؀۱۲۳
```

And an example with `hb-view`:
```
$ hb-view NotoNastaliqUrdu-Regular.ttf -u "0600;0020;0600;06f1;0020;0600;06f1;06f2;0020;0600;06f1;06f2;06f3" -o output.png
```

**Comment by nizarsq** [comment]
I agree with @saadatm point regarding U+0600 shape. U+0600 (ARABIC NUMBER SIGN) shape should look like the first 2 letters of the word number in Arabic (نمــــ) with tatweel U+0640. Current shape in hb still as reported and look like عــــ  which it has no meaning when it come to U+0600. @marekjez86 are you aware of the reason why it look different/changed?
Unrelated to the shaping issue,  look like the U+0600 ligature has some issues in browsers second screenshot.
![output](https://user-images.githubusercontent.com/22158882/93294412-46ecb480-f79f-11ea-8998-ddafbe494c37.png)

<img width="1222" alt="Screen Shot 2020-09-15 at 9 59 34 PM" src="https://user-images.githubusercontent.com/22158882/93294209-c037d780-f79e-11ea-9597-bcd27b0ed4ec.png">

**Comment by simoncozens** [comment]
All number signs now have the نمــــ shape, at least as of 2.001.
