### ISSUE TITLE
Kannada Letter U properly in Android 6 for small size

### ISSUE THREAD

**Issue by rali20** [googlefonts/noto-fonts#1576]
## Defect Report
Use this template for filing a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
  > Should be brief but contain essential information.

NotoSansKannada-Regular not showing KANNADA LETTER U with proper thickness, it is uneven. It has to be uniform. 

### Font 
  > Full file name, for example 'NotoSansArmenian-Regular.ttf'.
  > You can upload the problem font here unless it is a Chinese, Japanese or Korean font (these are large).

NotoSansKannada-Regular.ttf

### Where the font came from, and when
  > For example:
  >   Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArmenian-hinted.zip
  >   Date: 2017-04-10 (preferred format)

### Font Version
  > * Mac - right mouse click on a font and try Preview to see version info.
  > * Win -- right mouse click on a font (Local Disc > Windows > Fonts) and see version info on Properties.
  > * Linux -- use (Gnome) Font Viewer: open a font and click on Info tab.

### OS name and version
  > This is especially important if the font came pre-installed.

Android 6.1 MIUI 10 in Xiaomi Redmi Note 3 

### Application name and version
  > If the issue is observed using a specific app. 

While using Chrome browser KANNADA LETTER U not properly rendered its thickness is uneven

### Issue
  > Summarize the issue briefly -- one paragraph preferred

  1. Steps to reproduce
  2. Observed results
  3. Expected results
  4. Additional information 
  > Unicode chart, technical specs, shaping info, comparison with non-Noto fonts, comparison with earlier version of the same font (regression cases)

![Screenshot_2019-09-21-16-02-06-985_com brave browser](https://user-images.githubusercontent.com/25438816/65372949-28c0a700-dc66-11e9-8355-c08e6058f16b.png)

### Character data
  > Please include real character data to illustrate your issue-- Unicode codepoints are helpful.  This makes it possible for developers who don't know the language or script to copy/paste the text to reproduce the issue.

### Screenshot
  > If possible, include a screenshot or an image illustrating the issue.
  > Annotations are also helpful.

## Tools for reporting bugs
  Useful tools for reporting bugs are available at: https://github.com/googlei18n/
  
### Harfbuzz hb-view and hb-shape
  These are part of the HarfBuzz distribution and can help isolate if an issue is in the app/OS, shaping engine, or font.
  * hb-view renders the text with the exact font (for example, to see how ligatured characters shape) using your installed version of HarfBuzz.

For example:
```
  hb-view --font-file {path to font} --text-file {path to text file} --output-file '{sample}.png'
```

* hb-shape shows glyph selection and positioning

### Fontview
  * Fontview displays the text.

### Fontdiff
  * Fontdiff displays the text using two versions of the font side by side.

**Comment by ChiefMikeK** [comment]
🤓  FYI: 
- `hb-view` is available in the Termux repositories
- $`pkg install harfbuzz-utils` 
- its a command line program that outputs an .png image file :neckbeard:

**Comment by JelleBosmaMT** [comment]
I am not quite sure how this screen image has been produced. But I see several distortions that one would expect of TTF auto-hinting going wrong. It looks like outlines with grid fitting at a small ppem, scaled up to a large size. This is the old font, evidently used at an equally old version of Android. I remember old Android doing some strange font scaling when zooming in or out.

**Comment by nizarsq** [comment]
This issue has been fixed, please use the font in this directory https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansKannada/NotoSansKannada-Regular.ttf
<img width="1348" alt="Screen Shot 2020-06-16 at 9 55 46 PM" src="https://user-images.githubusercontent.com/22158882/84856705-41ef5c00-b01c-11ea-9f12-1f8b267f7f8a.png">
