### ISSUE TITLE
Warang Citi looks very crude

### ISSUE THREAD

**Issue by Singkiring57** [googlefonts/noto-fonts#1577]
### Overview
 > The overall look of the font is a bit crude, it seems many of the existing Warang Citi fonts have not been taken into consideration. I have listed some of the changes that can be made. I am a native Ho language speaker from Jharkhand, currently working on Ho Wikipedia project using Warang Citi. I have also designed some Warang Citi fonts myself.

### Font 
  > 'NotoSansWarangCiti-Regular.ttf'.

### Where the font came from, and when
  >   https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansWarangCiti
  >   Date: 2018-09-24

### Issue

U+118C4 is missing the loop:
![Capture-q](https://user-images.githubusercontent.com/22601820/65379768-6adffc00-dceb-11e9-9a7d-ee262a1deca4.PNG)

It could be drawn like:
![Capture-q2](https://user-images.githubusercontent.com/22601820/65379763-3e2be480-dceb-11e9-8c3e-e0777fc071d4.PNG)

U+118D2 is awkward:
![Capture-t](https://user-images.githubusercontent.com/22601820/65379769-91059c00-dceb-11e9-8b16-d4eca298818f.PNG)

It could be more like this:
![Capture-t2](https://user-images.githubusercontent.com/22601820/65379772-9bc03100-dceb-11e9-8869-8f636d3d0159.PNG)

U+118C1 is too tilted:
![Capture-a](https://user-images.githubusercontent.com/22601820/65379657-20f61680-dce9-11e9-91c8-f71cc9362dfe.PNG)

Better form ( from DisumSans.ttf )
![Capture-a2](https://user-images.githubusercontent.com/22601820/65379671-51d64b80-dce9-11e9-88e8-7b6d30abf165.PNG)

U+118D9 is not balanced
![Capture-h](https://user-images.githubusercontent.com/22601820/65379711-0ff9d500-dcea-11e9-8757-ee03390f5ed3.PNG)

Better form:
![Capture-h2](https://user-images.githubusercontent.com/22601820/65379712-1c7e2d80-dcea-11e9-9b84-80c52dbdedf8.PNG)

U+118CB can be even better
![Capture-g](https://user-images.githubusercontent.com/22601820/65379732-96161b80-dcea-11e9-8755-93cce2bddb74.PNG)

Something like this:
![Capture-g2](https://user-images.githubusercontent.com/22601820/65379744-d2e21280-dcea-11e9-9afb-90a452db4ba0.PNG)

U+118D8 is not proportional:
![Capture-p](https://user-images.githubusercontent.com/22601820/65379752-f9a04900-dcea-11e9-8d15-08883bffc5a7.PNG)

It could be like this:
![Capture-p2](https://user-images.githubusercontent.com/22601820/65379756-0886fb80-dceb-11e9-8bec-5e93c3bd6770.PNG)

**Comment by Singkiring57** [comment]
I can provide more material on Warang Citi if required.

**Comment by punchcutter** [comment]
Thanks @Singkiring57. This is very helpful. Any other information you can provide or links to resources would also be great. Also, if you know any Unicode encoded text to test Warang Citi fonts with that's also very helpful. There is a converter at http://aksharamukha.appspot.com that can convert to Warang Citi from Latin or Devanagari or anything else, but it's important to have real Ho language text to use.

**Comment by Singkiring57** [comment]
Ho language Wikipedia, which is currently in Wikimedia Incubator has some Ho language articles, most of which are short, but there are some long ones as well:

https://incubator.wikimedia.org/wiki/Wp/hoc/%F0%91%A2%B9%F0%91%A3%9C%F0%91%A3%95%F0%91%A3%99%F0%91%A3%9E%F0%91%A3%81

**Comment by Singkiring57** [comment]
Here's another text:
https://incubator.wikimedia.org/wiki/Wp/hoc/%F0%91%A2%BA%F0%91%A3%8C%F0%91%A3%89_%F0%91%A2%B7%F0%91%A3%89%F0%91%A3%94%F0%91%A3%9C%F0%91%A3%81

**Comment by Singkiring57** [comment]
![WC](https://user-images.githubusercontent.com/22601820/65969306-2c340980-e482-11e9-9dd6-32cb93bdfb69.jpg)

![bodrall](https://user-images.githubusercontent.com/22601820/65969614-b5e3d700-e482-11e9-829a-f3cd97056675.jpg)
![unurum](https://user-images.githubusercontent.com/22601820/65969644-c5632000-e482-11e9-9f0d-9bf4bbe8409b.jpg)

**Comment by Singkiring57** [comment]
A comparison:
![n vs d](https://user-images.githubusercontent.com/22601820/67156544-6f74f000-f33d-11e9-9b5e-8e8cf50cf2a7.png)

**Comment by Singkiring57** [comment]
![fontvs1](https://user-images.githubusercontent.com/22601820/67156592-3c7f2c00-f33e-11e9-8fdd-829fc07af00e.png)

**Comment by nizarsq** [comment]
@punchcutter what is the version of NotoSansWarangCiti that has design changed? look like the current font in the repository still has the old design at least for those characters I tried ----> 𑣒 𑣁 𑣙 𑣋 𑣘.
<img width="1395" alt="Screen Shot 2020-09-18 at 5 29 04 PM" src="https://user-images.githubusercontent.com/22158882/93654805-75070a00-f9d4-11ea-9966-68765c8e109b.png">

**Comment by punchcutter** [comment]
Once again this whole system has failed. The source files were updated on June 1, but the fonts were not regenerated and updated.

**Comment by dscorbett** [comment]
Why are there even separate repositories for sources and artifacts, and why is deployment a manual process?

**Comment by punchcutter** [comment]
I know, the whole setup is insane. At least https://github.com/notofonts is a little better? So now we have more than one place with sources and also more than 4 or 5 places with generated fonts.

**Comment by davelab6** [comment]
Is this because Monotype delivers work via a proprietary "portal" instead
of directly on GitHub? Or because Google ought to arrange the way we used
GitHub differently?

**Comment by punchcutter** [comment]
Not at all related to Monotype. I've submitted PRs that Marek accepts and then the fonts never get generated and updated so what's on noto-fonts does not match the sources on noto-source. This is pretty basic stuff to automate the builds, but at this point I'm not sure if it's worth messing with noto-source anymore or if it's better to just get everything moved to https://github.com/notofonts and having that set up with automated builds.

**Comment by marekjez86** [comment]
It was my failure to build the font (after ZQS created PR and I accepted). @punchcutter: To verify the correct version is 3.0 with Mangu Purty as the designer. Is this correct?

 https://github.com/notofonts is still work in progress -- that's where the automation is allegedly implemented (BUT ONLY NotoSerif has the latest version that allegedly works, the rest has the older automation that I put in place). The new automation in NotoSerif needs to be verified and populated to the other 190+ script repositories in   https://github.com/notofonts

**Comment by punchcutter** [comment]
Yes, 3.0 from Mangu Purty is the new version that addresses this current issue. Thanks!

**Comment by marekjez86** [comment]
The mystery is somewhat deeper. I have my personal computer with a clone of noto-fonts as of July 4 or so and NotoSansWarangCiti there is V3 so I actually built it and published where I was publishing fonts... however, somehow between  July 4 or so and Sep/17 it was swapped for the old version...

**Comment by nizarsq** [comment]
Thank you everyone. I was able to  see the fixes. I believe we can close this bug now.

<img width="1384" alt="Screen Shot 2020-09-18 at 10 52 35 PM" src="https://user-images.githubusercontent.com/22158882/93660253-a944ef80-fa01-11ea-902a-a2cc947ec223.png">
