### ISSUE TITLE
Telugu Noto sans and serif consonant conjuncts and vowel sign rendering issue

### ISSUE THREAD

**Issue by vsayikiran** [googlefonts/noto-fonts#1579]
Hi,
I am running Debian v10(codename buster). I am attaching snapshot of installed noto-core family of fonts.

![Screenshot at 2019-09-25 16-44-12](https://user-images.githubusercontent.com/55789717/65596084-bfb59800-dfb3-11e9-9fbf-d482c1a8afe3.png)

I have observed following defects in font rendering while using noto-sans(regular and UI) and noto-serif(regular and UI) as explained below:

1) Noto Sans Telugu font

a) In the consonant conjunct of letter r (ర) and ksha (క్ష), the symbol is currently displayed as
image
![image](https://user-images.githubusercontent.com/55789717/65598135-5d12cb00-dfb8-11e9-8059-3d5a79ad31a3.png)

instead the correct rendering should be (Note the snapshot taken while Noto serif regular is selected in pluma editor, hence issue is only with Noto sans font)
![image](https://user-images.githubusercontent.com/55789717/65598247-9f3c0c80-dfb8-11e9-93f9-262972cbedec.png)

This happens in both pluma text editor and libre office. While this does not recur when I directly type in github issue editor eg. ర్క్ష It is displayed correctly

version of pluma editor is
![image](https://user-images.githubusercontent.com/55789717/65598442-0eb1fc00-dfb9-11e9-89dc-8cda8e629ba8.png)
version of libre office is
![image](https://user-images.githubusercontent.com/55789717/65598585-63557700-dfb9-11e9-951c-bc50ebbd85ec.png)

b) The conjunct of letter r (ర) and letter jna (జ్ఞ) also not rendered correctly.
Snapshot taken from pluma editor
![image](https://user-images.githubusercontent.com/55789717/65599114-baa81700-dfba-11e9-9051-c596c48b148c.png)

Instead the correct rendering should be letter jna (జ్ఞ) should be exactly placed below letter r, similar to how ksha is placed below letter r as explained above.
eg.
![rksha](https://user-images.githubusercontent.com/55789717/65604148-905b5700-dfc4-11e9-8885-dea64385c1a5.PNG)

2) Noto serif Telugu
    a) The conjunct of consonant letters gh(ఘ), jh(ఝ), ya(య) and ma(మ) and vowel sign for long O (   ో ) is currently rendered as

    ![image](https://user-images.githubusercontent.com/55789717/65604791-a6b5e280-dfc5-11e9-80d2-140656b7e076.png)

Please note on letter gh and jh, long vowel O sign is rendered correctly whereas it is different for letter ya and ma. Later two letters have an extra curve which should not be there.
Correct rendering as per Noto sans font is

![image](https://user-images.githubusercontent.com/55789717/65605078-1b891c80-dfc6-11e9-901d-3d8646743074.png)

Hence this issue exists only with Noto-serif fonts.

I request the font designers to review this feedback and kindly incorporate the new design in upcoming updates across all platforms ie windows or linux etc.

V. Sayikiran

**Comment by vsayikiran** [comment]
Hi is there any update on this issue

**Comment by marekjez86** [comment]
Fixed in https://github.com/googlefonts/get-noto/tree/master/unhinted/Telugu
