### ISSUE TITLE
Wrong glyph for lone U+11A3A ZANABAZAR SQUARE CLUSTER-INITIAL LETTER RA

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1585]
### Font
NotoSansZanabazarSquare-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/6287e8bebe8d96e2b822409b2b9917b73cbd4bb7/phaseIII_only/unhinted/otf/NotoSansZanabazarSquare/NotoSansZanabazarSquare-Regular.otf
Date: 2019-09-26

### Font version
Version 2.000

### Issue
U+11A3A ZANABAZAR SQUARE CLUSTER-INITIAL LETTER RA by itself includes an extra subjoiner glyph.

### Character data
𑨺
U+11A3A ZANABAZAR SQUARE CLUSTER-INITIAL LETTER RA

### Screenshot
![𑨺](https://user-images.githubusercontent.com/1124347/66269683-5aff0680-e819-11e9-9a5e-6a2edf2db205.png)

**Comment by punchcutter** [comment]
Fixed. 
![1585](https://user-images.githubusercontent.com/11257204/73329647-448b1980-4213-11ea-8db9-e870b5a8bada.png)

**Comment by nizarsq** [comment]
Fix verified. Thank you @punchcutter @dscorbett  
<img width="1284" alt="Screen Shot 2020-10-07 at 12 12 50 PM" src="https://user-images.githubusercontent.com/22158882/95376762-6d7da700-0896-11eb-8078-4861181665a4.png">
