### ISSUE TITLE
Swapped anchor points on Nastaliq gaf

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1587]
### Font
NotoNastaliqUrdu-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/764c62e79c71e7b1d4a6363000af5bf71df8e1ad/phaseIII_only/unhinted/ttf/NotoNastaliqUrdu/NotoNastaliqUrdu-Regular.ttf
Date: 2019-10-10

### Font version
Version 2.000

### Issue
The anchor points of `GafIni.HRoutD2` for i‘jam above and below are swapped.

### Character data
ڰھاڱھا
U+06B0 ARABIC LETTER GAF WITH RING
U+06BE ARABIC LETTER HEH DOACHASHMEE
U+0627 ARABIC LETTER ALEF
U+06B1 ARABIC LETTER NGOEH
U+06BE ARABIC LETTER HEH DOACHASHMEE
U+0627 ARABIC LETTER ALEF

### Screenshot
![ڰھاڱھا](https://user-images.githubusercontent.com/1124347/66664801-3e990a80-ec1b-11e9-90cd-6b57620c6c93.png)

**Comment by nizarsq** [comment]
This issues still reproducible
<img width="614" alt="Screen Shot 2020-05-21 at 3 19 07 PM" src="https://user-images.githubusercontent.com/22158882/82611944-8b13d380-9b76-11ea-9467-0529f87224b8.png">
