### ISSUE TITLE
Overlapping above-base marks in Kufi

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1589]
### Font
NotoKufiArabic-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/e87ac4b84ac38f7cff7fd6d87918d45785c0e9ea/phaseIII_only/unhinted/otf/NotoKufiArabic/NotoKufiArabic-Regular.otf
Date: 2019-10-11

### Font Version
Version 2.000

### Issue
Above-base marks overlap the dots above some letters.

### Character data
ݫَݣَݜَݝَݭَ
U+076B ARABIC LETTER REH WITH TWO DOTS VERTICALLY ABOVE
U+064E ARABIC FATHA
U+0763 ARABIC LETTER KEHEH WITH THREE DOTS ABOVE
U+064E ARABIC FATHA
U+075C ARABIC LETTER SEEN WITH FOUR DOTS ABOVE
U+064E ARABIC FATHA
U+075D ARABIC LETTER AIN WITH TWO DOTS ABOVE
U+064E ARABIC FATHA
U+076D ARABIC LETTER SEEN WITH TWO DOTS VERTICALLY ABOVE
U+064E ARABIC FATHA

### Screenshot
![ݫَݣَݜَݝَݭَ](https://user-images.githubusercontent.com/1124347/66721916-bca11100-edd5-11e9-8f5b-c22889268e40.png)

**Comment by nizarsq** [comment]
This issue reproducible on Version 2.101
<img width="824" alt="Screen Shot 2020-05-19 at 11 29 18 PM" src="https://user-images.githubusercontent.com/22158882/82412599-c4d6c400-9a28-11ea-83f0-ffe770339f4c.png">

**Comment by nizarsq** [comment]
<img width="1178" alt="Screen Shot 2020-10-20 at 8 16 06 PM" src="https://user-images.githubusercontent.com/22158882/96668935-173a4a80-1311-11eb-873c-d30c9a537e2e.png">
<img width="1172" alt="Screen Shot 2020-10-20 at 8 16 30 PM" src="https://user-images.githubusercontent.com/22158882/96668963-25886680-1311-11eb-877e-547457bf3187.png">
<img width="1171" alt="Screen Shot 2020-10-20 at 8 16 48 PM" src="https://user-images.githubusercontent.com/22158882/96668983-31742880-1311-11eb-9f10-d14755af6500.png">

**Comment by nizarsq** [comment]
This issue fixed
