### ISSUE TITLE
Overlapping below-base marks and vattu ra in Devanagari

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1592]
### Font
NotoSerifDevanagari-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/46eb8fa0c46d16a87eee3e763baa3efb7423a8b4/phaseIII_only/unhinted/ttf/NotoSerifDevanagari/NotoSerifDevanagari-Regular.ttf
Date: 2019-10-20

### Font version
Version 2.000

### Issue
On glyphs representing clusters with the circumflex-shaped below-base <i>ra</i>, the below-base anchor point is too high.

### Character data
ङ्रॖछ्र᳘
U+0919 DEVANAGARI LETTER NGA
U+094D DEVANAGARI SIGN VIRAMA
U+0930 DEVANAGARI LETTER RA
U+0956 DEVANAGARI VOWEL SIGN UE
U+091B DEVANAGARI LETTER CHA
U+094D DEVANAGARI SIGN VIRAMA
U+0930 DEVANAGARI LETTER RA
U+1CD8 VEDIC TONE CANDRA BELOW

### Screenshot
![ङ्रॖछ्र᳘](https://user-images.githubusercontent.com/1124347/67220212-5df01e80-f3f7-11e9-81d2-28334905c13b.png)

**Comment by JelleBosmaMT** [comment]
The font files are generated from source files in Glyphs format. I know that in Summer 2019 the tools used by Google needed to be updated to correctly handle the anchors that composites are expected to inherit from base glyphs. The font file from the link is from 26 September 2019. I can reproduce the bug with the downloaded font file, but not with a font generated by Glyphs from the same source file.

![image](https://user-images.githubusercontent.com/12729011/76649254-91774500-6560-11ea-9c41-768da41c7e02.png)

It is possible that the software has improved in the mean time and the issue goes away when re-generating the fonts.

**Comment by JelleBosmaMT** [comment]
@marekjez86 
We tried running the old source file through the current pipeline and it does not look good. For the GPOS mark to base lookup that deals with these low marks I compared the decompiled data of Glyphs.app and pipeline. Nine composite marks are missing. There are 124 fewer anchors, for composite glyphs. And where the number of anchors matches, they might be from the wrong component (I haven't tried to count them).
It is unlikely an issue for Devanagari Serif only.

**Comment by nizarsq** [comment]
Tested the current font in this [directory](https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSerifDevanagari/NotoSerifDevanagari-Regular.ttf) and anchor point lgtm in this font.
<img width="1251" alt="Screen Shot 2020-06-06 at 12 12 27 AM" src="https://user-images.githubusercontent.com/22158882/83938656-4e0d2b00-a78b-11ea-9033-3c9d9a2d83c3.png">

**Comment by simoncozens** [comment]
Yes, this is now fixed.
