### ISSUE TITLE
Noto Sansa Arabic is broken in PowerPoint

### ISSUE THREAD

**Issue by MDCR55** [googlefonts/noto-fonts#1599]
### Title 
  > Broken Arabic writing on Noto Sans Arabic font on PowerPoint

### Font 
  > 'NotoSansArabic-Regular.ttf'.

### OS name and version
  > Windows 10

### Application name and version
  > PowetPoint Office 365, Vesrion 16.0.12026.20344

### Issue
  > Issue comes when I download the font **Noto Sans Arabic** from https://www.google.com/get/noto/ and after installing the font, I would not work on PowerPoint and show the Arabic characters as broken and unlinked characters, while on MS Word, the font is perfectly works fine.

### Screenshot
<img src="https://i.imgur.com/oR9OsDv.png">

### Text used on previous screenshot to reproduce the problem
يولد جميع الناس أحراراً ومتساوين في الكرامة والحقوق. وهم قد وهبوا العقل والوجدان وعليهم أن يعاملوا بعضهم بعضاً بروح الإخاء.

**Comment by nizarsq** [comment]
Tested the reported issue on Powerpoint 16.0.11929.20392 and the issue not reproducible, I'm assuming the issue fixed. I used NotoSansArabic in this directory https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansArabic. Closing the bug for now.
![NotoSansArabic-1542](https://user-images.githubusercontent.com/22158882/84462187-38808100-ac23-11ea-850d-a2ab53016b8d.png)
