### ISSUE TITLE
Noto Nastaliq Urdu: Incorrect glyphs for digits 4 and 7 in Sindhi

### ISSUE THREAD

**Issue by Etewilak** [googlefonts/noto-fonts#1607]
In Noto Nastaliq Urdu, when text is set in Sindhi, the digits 4 and 7 are incorrectly shaped. The following is a screenshot of numerals in Noto Nastaliq Urdu:
![Noto Nastaliq Urdu Sindhi Numerals Bug (2)](https://user-images.githubusercontent.com/55674356/68095342-7ece6e80-fee3-11e9-94f7-1eedb9da8c4e.PNG)
Numerals in Sindhi must look like the following: 
![Amiri Sindhi Numerals (2)](https://user-images.githubusercontent.com/55674356/68095352-af160d00-fee3-11e9-99a6-0a246810159a.PNG)

**Comment by nizarsq** [comment]
This issue producible. http://www.unicode.org/versions/Unicode13.0.0/ch09.pdf Page 370
<img width="1082" alt="Screen Shot 2020-09-18 at 1 35 52 PM" src="https://user-images.githubusercontent.com/22158882/93642971-e08caf80-f9b3-11ea-8a54-d7b068ba44ee.png">

<img width="525" alt="Screen Shot 2020-09-18 at 1 38 11 PM" src="https://user-images.githubusercontent.com/22158882/93643125-32cdd080-f9b4-11ea-8ac1-63e0806217fd.png">

**Comment by simoncozens** [comment]
This appears to have been fixed, at least in 2.001.

**Comment by Etewilak** [comment]
The issue has been fixed in Noto Nastaliq Urdu Bold:
![image](https://user-images.githubusercontent.com/55674356/152522437-ab458a68-f617-4466-88c7-1e0c656a7cb4.png)
However, it has not yet been fixed in Noto Nastaliq Urdu Regular:
![image](https://user-images.githubusercontent.com/55674356/152522553-58141083-0475-4e1c-8b05-c4085a5641f8.png)
