### ISSUE TITLE
Font for "Sogdian" is missing.

### ISSUE THREAD

**Issue by SalviaSage** [googlefonts/noto-fonts#1609]
I want to bring to your attention that the font for "Sogdian",
Unicode plane: U+10F30 - U+10F6F is missing.

I saw that "Old Sogdian" which was also missing has been recently uploaded to this repository, which is good. But, "Sogdian" is still missing.

https://en.wikipedia.org/wiki/Sogdian_(Unicode_block)

Please upload this font here if possible.

Thank you.

**Comment by marekjez86** [comment]
This was work in progress ... not done when you entered this issue...
please check https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansSogdian or https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansSogdian
