### ISSUE TITLE
Open corner on U+11A54 SOYOMBO VOWEL SIGN E

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1614]
### Font
NotoSansSoyombo-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/a62069cb3ba3081122e6f9d700eb348d3eaf9e1b/unhinted/NotoSansSoyombo/NotoSansSoyombo-Regular.ttf
Date: 2019-11-12

### Font version
Version 2.000

### Issue
U+11A54 SOYOMBO VOWEL SIGN E has a little triangle at its bottom right corner.

### Character data
𑩜𑩔
U+11A5C SOYOMBO LETTER KA
U+11A54 SOYOMBO VOWEL SIGN E

### Screenshot
![𑩜𑩔](https://user-images.githubusercontent.com/1124347/68782599-aa4e0900-0607-11ea-88d8-84c0683cc249.png)

**Comment by nizarsq** [comment]
Was able to reproduce the issue. According to https://unicode.org/charts/PDF/U11A50.pdf there is no corner.
<img width="1255" alt="Screen Shot 2020-10-07 at 12 08 52 PM" src="https://user-images.githubusercontent.com/22158882/95376388-dfa1bc00-0895-11eb-92ae-8a9a512bfe34.png">

**Comment by punchcutter** [comment]
It has nothing to do with Unicode. It's a feature in Glyphs app that is not supported by fontmake so the source needs to be fixed.

**Comment by czywuqing** [comment]
Yes, Is fix in U+11A54 SOYOMBO VOWEL SIGN E!

**Comment by simoncozens** [comment]
Yes, glyphsLib now supports open corners so this should now be fixed.

**Comment by czywuqing** [comment]
OK, fix Noto Sans Soyombo https://github.com/googlefonts/noto-source/tree/main/src
