### ISSUE TITLE
Noto Sans Arabic uni06D5 problem

### ISSUE THREAD

**Issue by visionario2** [googlefonts/noto-fonts#1617]
## Defect Report
Character problem in Noto Sans Arabic

### Title 
  The Arabic letter AE, uni06D5, does not form correctly. It should be right-joining.

### Font 
  NotoSansArabic-Regular.ttf

### Where the font came from, and when

  Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
  Date: 2019-11-21

### Font Version
  2

### Application name and version
  Indesign

### Issue
 The Arabic letter AE, uni06D5, does not form correctly. It should be right-joining.
  1. Get some text containing uni06D5 preceded by a left-joining letter, eg ئە
  2. Observed results: the letters do not join
  3. Expected results: the letters should join
  4. Additional information 
  Compare with eg Adobe Arabic

**Comment by nizarsq** [comment]
Reported issue reproducible, uni06D5 does not form correctly. Tested on .[otf](https://github.com/googlefonts/noto-fonts/blob/115d38430d957d38307457c036302b7bdbe0bbc4/phaseIII_only/unhinted/otf/NotoSansArabic/NotoSansArabic-Regular.otf) and  uni06D5 form correctly.

**Comment by nizarsq** [comment]
Please try the font from https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf. This is version 2.5. The one you are using is version 2.0.

**Comment by nizarsq** [comment]
Issue fixed on version 2.5

**Comment by nizarsq** [comment]
https://github.com/googlefonts/noto-fonts/issues/1039

**Comment by nizarsq** [comment]
Version 2.5 revised reopening this issue.

**Comment by nizarsq** [comment]
This issue appear in NotoSansArabic and NotoKufiArabic.

**Comment by nizarsq** [comment]
Issue fixed
