### ISSUE TITLE
Add ꞽ = U+A7BD (Latin small letter glottal I) and Ꞽ = U+A7BC (Latin capital letter glottal I)

### ISSUE THREAD

**Issue by ailintom** [googlefonts/noto-fonts#1621]
### Title 
Please add Latin letter glottal I 
### Font 
  Noto Sans 2.003, Noto Serif 2.003
NotoSerif-Regular.ttf
NotoSans-Regular.ttf

### Where the font came from, and when
https://github.com/googlefonts/noto-fonts (branch: master, 02.12.2019)

### Font Version
2.003

### Character data
Please add signs ꞽ = U+A7BD (Latin small letter glottal I) and Ꞽ = U+A7BC (Latin capital letter glottal I) to Latin Extended D. These are part of Unicode 12 and are used in Egyptology. They are not found in Noto as of 02.12.2019

**Comment by ailintom** [comment]
Here is an example of how these letters look like (small and capital glottal I as the first letter of italicized words in the passage from A. H. Gardiner, Egyptian Grammar
![Glottal i](https://user-images.githubusercontent.com/24455000/72254192-9a50a680-3603-11ea-9fe7-fa7e279b2979.png)

**Comment by nizarsq** [comment]
U+A7BD and  U+A7BC currently in NotoSans NotoSerif.  Please use the fonts in the following directories https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSans 
and 
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSerif

**Comment by moyogo** [comment]
See Latin U+A7BA-A7BF (ꞺꞻꞼꞽꞾꞿ) should not be italic in roman styles #1779 .
