### ISSUE TITLE
Broken Text with Noto Sans Kannada in iOS

### ISSUE THREAD

**Issue by MayuraVerma** [googlefonts/noto-fonts#1622]
### Title 
  > Broken Text with Noto Sans Kannada in iOS

### Font 
  > 'NotoSansKannada-Bold.otf'.

### Where the font came from, and when
  > iOS 13.2.3

### Font Version
  > Part of iOS 13.2.3

### OS name and version
  > iOS 13.2.3

### Application name and version
  > Safari

### Issue
  > Open the below URL in iOS device
https://www.prajavani.net/stories/national/giraffe-was-brought-to-assam-state-zoo-686628.html

Observe the Title "ಅಸ್ಸಾಂ ಪ್ರಾಣಿಸಂಗ್ರಹಾಲಯಕ್ಕೆ ನೂತನ ಅತಿಥಿ !"
Closes at "ಹಾ"
ಹ and  ಾ are broken.

Same problem in "ಸಾ" in the word "ಅಸ್ಸಾಂ"

### Character data
  > U+0CB9 U+0CBE

### Screenshot
![IMG_3196](https://user-images.githubusercontent.com/14062593/70019799-3476f680-1550-11ea-80e3-ca0b4a5c6ab4.PNG)
 
![IMG_3195](https://user-images.githubusercontent.com/14062593/70019790-304ad900-1550-11ea-9070-61a2e6dba952.PNG)

**Comment by MayuraVerma** [comment]
Same pattern in found in mac OS catalina 10.15.1 (19B88)
Safari 13.0.3 (15608.3.10.1.4)

Seems like it is an issue in "NotoSansKannada-Bold" while rendering U+0CBE with all Kannada consonants.


![Screen Shot 2019-12-02 at 10 12 42 PM](https://user-images.githubusercontent.com/14062593/70020071-25447880-1551-11ea-8b6e-401b424dc748.png)

**Comment by MayuraVerma** [comment]
Perhaps this is due to old version of NotoSansKannada webfont used by the website.

**Comment by JelleBosmaMT** [comment]
I can reproduce the issue in iOS. It is a bit confusing, because Noto Sans Kannada ships as part of iOS 13. But that is the version from 2018, while the font on prajavani.net is the 2014 version. So that must be a web-font. Some of the captions are spaced wider. Ideally for Kannada and Telugu making the spacing wider is done by putting extra white between syllable clusters only, to keep connecting items in place. I can make the overlaps in the vowel signs AA and AU longer in the 2020 version, so that they can spaced more as they can now, before the headlines open up.

**Comment by MayuraVerma** [comment]
Overlap glyphs shows in coloring with border as well.

It would be better non-overlapping combined glyph for consonants with AA, I, U, UU, E, O, AU

It could mean file size is slightly bigger, but it would solve a lot a issues.

such as this:
Type this text in Notes app of iOS
ಅಕ್ಟ್ಬೋಬರ್‌
ಆಸ್ಟ್ರೋಯಾದಲ್ಲಿ 

You will see this text broken
![5A31A974-1A46-4B81-A5D8-4C4FCAF8892B](https://user-images.githubusercontent.com/14062593/75047649-beb66300-548c-11ea-8fed-af9224ab93ed.jpeg)

Tiro Kannada font uses all combined glyphs. You may want to review that font.

**Comment by JelleBosmaMT** [comment]
I can reproduce the error in iOS Notes: if the OO follows a subscript consonant, then subscripts and the parts that make up the OO end up in strange places. In iOS pages it is OK. 
The font doesn't do anything with the OO vowel sign. The shaper software will replace it with E, UU and the length mark. If there are subscript consonants, the software has to put the E and UU right after the full consonant, then the subscript(s) then the length mark. Something goes wrong in iOS Notes that does not go wrong elsewhere. In combination with II, EE, AI and O, vowels and subscript consonant are re-ordered too and that is OK. The software seems to loose track of where it is supposed to put things. If I continue typing, with every new character vowel signs and subscripts are repositioned somewhere else. 

Interesting to see it going wrong in the body of the note, but the same text and same font OK in the sidebar:
![image](https://user-images.githubusercontent.com/12729011/75052179-75d3ce00-54cf-11ea-988b-9e5cf7f216c1.png)

(I guess you can see from the image that I am not exactly a frequent user of the Notes app.)

**Comment by MayuraVerma** [comment]
This happens throughout the iOS in the fields that uses NSTEXTFIELD.
examples:
mail subject line while composing
contacts while editing
Safari Search bar
Youtube comments window
....

PAGES use NSTEXTVIEW
if you create a contact with this text, you will notice the error while creating/editing
Text will be properly rendered when done creating/editing and you are viewing the contact, at this point Contacts app uses NSTEXTVIEW.

If you can please report this to Apple, it would be great.

**Comment by MayuraVerma** [comment]
also in the example you have shown,
left side of notes app is NSTEXTVIEW, right side NSTEXTFIELD

**Comment by MayuraVerma** [comment]
Please report it to Apple.
This issue is lingering for many years.

**Comment by nizarsq** [comment]
This issue has been resolved, please use the font in this directory https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansKannada/NotoSansKannada-Bold.ttf. If you have other thoughts, please reopen the bug.
<img width="1165" alt="Screen Shot 2020-06-15 at 10 59 01 PM" src="https://user-images.githubusercontent.com/22158882/84737370-a34ff600-af5c-11ea-9b10-926e29b6bdb6.png">
