### ISSUE TITLE
Wrong glyphs for Sindhi particles

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1624]
### Font
NotoKufiArabic-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/fd292544c1bb394d6004c57108c62d028a656bab/phaseIII_only/unhinted/otf/NotoKufiArabic/NotoKufiArabic-Regular.otf
Date: 2019-12-04

### Font version
Version 2.101

### Issue
The double vertical lines of U+06FD and U+06FE should be next to each other, not one above the other.

### Character data
۽۾
U+06FD ARABIC SIGN SINDHI AMPERSAND
U+06FE ARABIC SIGN SINDHI POSTPOSITION MEN

### Screenshot
![۽۾](https://user-images.githubusercontent.com/1124347/70183362-a3b92b80-16b3-11ea-8eca-d7e1dd83df00.png)

**Comment by nizarsq** [comment]
This issue reproducible on version 2.101 and version 2.100.

**Comment by nizarsq** [comment]
<img width="1284" alt="Screen Shot 2020-09-28 at 9 58 36 PM" src="https://user-images.githubusercontent.com/22158882/94514328-c3d35180-01d5-11eb-8fc1-1c8971fe5f83.png">

**Comment by nizarsq** [comment]
This issue fixed.
