### ISSUE TITLE
Kannada missing letter U+0C84

### ISSUE THREAD

**Issue by SalviaSage** [googlefonts/noto-fonts#1626]
This letter was added in Unicode version 11 and is simply missing from the NoTo Kannada font.

Code point: U+0C84
Name:  KANNADA SIGN SIDDHAM

It is the only symbol missing from the font.
Please add this character into this font.

Thank you.

**Comment by nizarsq** [comment]
Look like this issue resolved. Please check the font in this directory: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansKannada/NotoSansKannada-Regular.ttf
<img width="1022" alt="Screen Shot 2020-06-15 at 10 46 54 PM" src="https://user-images.githubusercontent.com/22158882/84736220-39365180-af5a-11ea-909c-28eeee396005.png">
