### ISSUE TITLE
Gujarati font missing U+0AF9 - U+0AFF

### ISSUE THREAD

**Issue by SalviaSage** [googlefonts/noto-fonts#1627]
Gujarati font is missing U+0AF9 - U+0AFF

They are basically the last part of the block.
1 letter and 6 signs.

Please update this font if possible.

Thank you.

**Comment by marekjez86** [comment]
fixed in https://github.com/googlefonts/get-noto/tree/master/unhinted/Gujarati

**Comment by SalviaSage** [comment]
Thank you.
Any chance this script will be added in here?
https://github.com/googlefonts/noto-fonts/issues/1625
