### ISSUE TITLE
U+23BA and related symbols recently dropped

### ISSUE THREAD

**Issue by vapier** [googlefonts/noto-fonts#1629]
## Title 
Commit 0fa1dfabd6e3746bb7463399e2813f60d3f1b256 dropped U+23BA-U+23BD from all noto fonts.

### Font 
NotoSansMono-Regular.ttf (and related monospace fonts) used to provide these symbols.

### Where the font came from, and when

Working font:
https://github.com/googlefonts/noto-fonts/blob/50eafdece28ffa16d756590aa452e653eb27d194/unhinted/NotoSansMono/NotoSansMono-Regular.ttf

Broken font:
https://github.com/googlefonts/noto-fonts/blob/0fa1dfabd6e3746bb7463399e2813f60d3f1b256/unhinted/NotoSansMono/NotoSansMono-Regular.ttf

**Comment by nizarsq** [comment]
23BA 23BB 23BC 23BD In NotoSansMono
<img width="1102" alt="Screen Shot 2020-09-17 at 9 33 22 PM" src="https://user-images.githubusercontent.com/22158882/93556359-6ade0080-f92d-11ea-9ab5-19a839259e5c.png">
