### ISSUE TITLE
Misplaced shin and sin dots in Noto Rashi Hebrew

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1636]
### Font
NotoRashiHebrew-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/4f0db8f7a3424b2e97bce246a9ca7d551f76396c/phaseIII_only/unhinted/otf/NotoRashiHebrew/NotoRashiHebrew-Regular.otf
Date: 2019-12-24

### Font version
Version 1.000

### Issue
The shin dot and sin dot are too far to the right.

### Character data
שׁשׂ
U+05E9 HEBREW LETTER SHIN
U+05C1 HEBREW POINT SHIN DOT
U+05E9 HEBREW LETTER SHIN
U+05C2 HEBREW POINT SIN DOT

### Screenshot
![שׁשׂ](https://user-images.githubusercontent.com/1124347/71446975-5b5fbd00-26f7-11ea-8f81-9180b09024e6.png)

**Comment by nizarsq** [comment]
Issue fixed.
<img width="1085" alt="Screen Shot 2020-08-04 at 1 37 09 PM" src="https://user-images.githubusercontent.com/22158882/89342408-99db3400-d657-11ea-98d2-bf0b4388552f.png">

**Comment by dscorbett** [comment]
Sin dot looks good now, but shin dot is still too far to the right.
