### ISSUE TITLE
Misshapen bold Rashi U+05E2 HEBREW LETTER AYIN

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1637]
### Font
NotoRashiHebrew-Bold.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/4f0db8f7a3424b2e97bce246a9ca7d551f76396c/phaseIII_only/unhinted/otf/NotoRashiHebrew/NotoRashiHebrew-Bold.otf
Date: 2019-12-24

### Font version
Version 1.000

### Issue
The bold glyph for ayin is badly corrupted.

### Character data
ע
U+05E2 HEBREW LETTER AYIN

### Screenshot
![ע](https://user-images.githubusercontent.com/1124347/71478895-ec01d000-27bf-11ea-8e00-00cc561fe243.png)

**Comment by marekjez86** [comment]
I caught it on the variable font (it transitions through weight axis in a strange way). The font developer will correct it soon. Thank you for filing this bug.

**Comment by nizarsq** [comment]
This issue fixed.
<img width="781" alt="Screen Shot 2020-08-04 at 1 26 01 PM" src="https://user-images.githubusercontent.com/22158882/89341366-0b19e780-d656-11ea-9f62-51e38ebedaac.png">
