### ISSUE TITLE
Overlapping Rashi ⟨צן⟩

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1638]
### Font
NotoRashiHebrew-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/4f0db8f7a3424b2e97bce246a9ca7d551f76396c/phaseIII_only/unhinted/otf/NotoRashiHebrew/NotoRashiHebrew-Regular.otf
Date: 2019-12-24

### Font version
Version 1.000

### Issue
The glyphs in ⟨צן⟩ aren’t kerned apart.

### Character data
צן
U+05E6 HEBREW LETTER TSADI
U+05DF HEBREW LETTER FINAL NUN

### Screenshot
![צן](https://user-images.githubusercontent.com/1124347/71532577-015f2300-28c2-11ea-8fa3-b5daa9f16497.png)

**Comment by nizarsq** [comment]
Issue reproducible in the current NotoRashiHebrew.
<img width="1043" alt="Screen Shot 2020-08-04 at 1 21 46 PM" src="https://user-images.githubusercontent.com/22158882/89340984-744d2b00-d655-11ea-9041-0a88697aa481.png">
