### ISSUE TITLE
Noto Serif Tibetan variable font gives different results than static fonts (this could be a source or a fontmake issue)

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#1642]
### Font 
 Problem font: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/variable-ttf/NotoSerifTibetan-VF.ttf
 Reference font (looks correct): https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSerifTibetan/NotoSerifTibetan-Regular.ttf

### Where the font came from, and when
  2019-12-30

https://github.com/googlefonts/fontdiff was used to produce the differences visible in PDFs below using my MacOS system

1. the second line line last character (generated from https://github.com/googlefonts/noto-source/blob/master/test/Tibetan/specimen-tib.html )
<img width="310" alt="Screen Shot 2019-12-31 at 07 14 38" src="https://user-images.githubusercontent.com/13322623/71625554-54c0c200-2b9d-11ea-903a-56e89f1d8d66.png">

[Tibetan-specimen-tib-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/4012877/Tibetan-specimen-tib-Serif.pdf)
2. the fourth line last char (generated from https://github.com/googlefonts/noto-source/blob/master/test/Tibetan/tib-0F83.html )
[Tibetan-tib-0F83-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/4012893/Tibetan-tib-0F83-Serif.pdf)
3. the fourth line and following (generated from https://github.com/googlefonts/noto-source/blob/master/test/Tibetan/tib-0F84.html )
[Tibetan-tib-0F84-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/4012896/Tibetan-tib-0F84-Serif.pdf)
4. the second line line (generated from https://github.com/googlefonts/noto-source/blob/master/test/Tibetan/tib-637.html )
[Tibetan-tib-637-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/4012900/Tibetan-tib-637-Serif.pdf)
5. many lines (generated from https://github.com/googlefonts/noto-source/blob/master/test/Tibetan/tib-658.html )
[Tibetan-tib-658-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/4012927/Tibetan-tib-658-Serif.pdf)
6. the second line line (generated from https://github.com/googlefonts/noto-source/blob/master/test/Tibetan/tib-838.html )
[Tibetan-tib-838-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/4012932/Tibetan-tib-838-Serif.pdf)
7. the second line line (generated from https://github.com/googlefonts/noto-source/blob/master/test/Tibetan/tib-1103.html )
[Tibetan-tib-1103-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/4012935/Tibetan-tib-1103-Serif.pdf)
8. the second line line (generated from https://github.com/googlefonts/noto-source/blob/master/test/Tibetan/tib-1337.html )
[Tibetan-tib-1337-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/4012940/Tibetan-tib-1337-Serif.pdf)

**Comment by marekjez86** [comment]
I realized that fontdiff might be using  HarfBuzz 1.7.4, so this might be an issue. I may need to rebuild the tool itself.

**Comment by nizarsq** [comment]
I was curious to see  if there is difference between variable and static font. Below the result on chrome, not sure if this is expected or I'm doing something wrong.
<img width="1414" alt="Screen Shot 2020-09-18 at 11 29 56 PM" src="https://user-images.githubusercontent.com/22158882/93660748-dfd13900-fa06-11ea-8993-bb83f71abce7.png">

**Comment by punchcutter** [comment]
That's not using the variable font. It's falling back to system font.

**Comment by nizarsq** [comment]
@punchcutter you are 100% correct. The parenthesis in the font-face rule caused the issue. Thanks. 
<img width="1415" alt="Screen Shot 2020-09-19 at 1 28 50 AM" src="https://user-images.githubusercontent.com/22158882/93662784-7b6aa580-fa17-11ea-881a-2047491881cd.png">

**Comment by nizarsq** [comment]
VF fonts looks good to me  @marekjez86  for opinion/closing.

**Comment by marekjez86** [comment]
corrected
[Prod-report_NotoSerifTibetan_857328.pdf](https://github.com/googlefonts/noto-fonts/files/8157214/Prod-report_NotoSerifTibetan_857328.pdf)
