### ISSUE TITLE
Inappropriate head form of Tibetan ra with multiple subjoined letters

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1645]
### Font
NotoSerifTibetan-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/96e3d51ab4ad78e74a4cb0752dc25d010d6946de/unhinted/NotoSerifTibetan/NotoSerifTibetan-Regular.ttf
Date: 2020-01-02

### Font version
Version 2.001

### Issue
Before five subjoined consonants, U+0F62 TIBETAN LETTER RA keeps its full form, instead of its abbreviated head form (<i>ra mgo</i>). In this font, it becomes <i>ra mgo</i> when there is a second subjoined consonant.

### Character data
རྙརྙྐ
U+0F62 TIBETAN LETTER RA
U+0F99 TIBETAN SUBJOINED LETTER NYA
U+0F62 TIBETAN LETTER RA
U+0F99 TIBETAN SUBJOINED LETTER NYA
U+0F90 TIBETAN SUBJOINED LETTER KA
རྭརྭྐ
U+0F62 TIBETAN LETTER RA
U+0FAD TIBETAN SUBJOINED LETTER WA
U+0F62 TIBETAN LETTER RA
U+0FAD TIBETAN SUBJOINED LETTER WA
U+0F90 TIBETAN SUBJOINED LETTER KA
རྱརྱྐ
U+0F62 TIBETAN LETTER RA
U+0FB1 TIBETAN SUBJOINED LETTER YA
U+0F62 TIBETAN LETTER RA
U+0FB1 TIBETAN SUBJOINED LETTER YA
U+0F90 TIBETAN SUBJOINED LETTER KA
རྲརྲྐ
U+0F62 TIBETAN LETTER RA
U+0FB2 TIBETAN SUBJOINED LETTER RA
U+0F62 TIBETAN LETTER RA
U+0FB2 TIBETAN SUBJOINED LETTER RA
U+0F90 TIBETAN SUBJOINED LETTER KA
རླརླྐ
U+0F62 TIBETAN LETTER RA
U+0FB3 TIBETAN SUBJOINED LETTER LA
U+0F62 TIBETAN LETTER RA
U+0FB3 TIBETAN SUBJOINED LETTER LA
U+0F90 TIBETAN SUBJOINED LETTER KA

### Screenshot
![རྙརྙྐ རྭརྭྐ རྱརྱྐ རྲརྲྐ རླརླྐ](https://user-images.githubusercontent.com/1124347/71706029-7940b800-2db0-11ea-8aa3-fad78d8a97b7.png)

**Comment by marekjez86** [comment]
corrected
[Prod-report_NotoSerifTibetan_857328.pdf](https://github.com/googlefonts/noto-fonts/files/8157190/Prod-report_NotoSerifTibetan_857328.pdf)
