### ISSUE TITLE
Tibetan anti-overlap lookup overapplies

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1648]
### Font
NotoSerifTibetan-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/96e3d51ab4ad78e74a4cb0752dc25d010d6946de/unhinted/NotoSerifTibetan/NotoSerifTibetan-Regular.ttf
Date: 2020-01-02

### Font version
Version 2.001

### Issue
Above-base marks get narrow forms in Noto Serif Tibetan when previous clusters would otherwise overlap them. This check is not restricted to the immediately previous cluster, making marks narrow even when there would be no overlap. In the examples below, the third cluster’s <i>i</i> is narrow because of the first cluster’s tsa ’phru or <i>o</i>, which are nowhere near it.

### Character data
ཙཀཀི
U+0F59 TIBETAN LETTER TSA
U+0F40 TIBETAN LETTER KA
U+0F40 TIBETAN LETTER KA
U+0F72 TIBETAN VOWEL SIGN I
ཀོཀཀི
U+0F40 TIBETAN LETTER KA
U+0F7C TIBETAN VOWEL SIGN O
U+0F40 TIBETAN LETTER KA
U+0F40 TIBETAN LETTER KA
U+0F72 TIBETAN VOWEL SIGN I

### Screenshot
![ཙཀཀི ཀོཀཀི](https://user-images.githubusercontent.com/1124347/71769104-86fa5880-2eea-11ea-88b3-347839308cdd.png)

**Comment by marekjez86** [comment]
corrected
[Prod-report_NotoSerifTibetan_857328.pdf](https://github.com/googlefonts/noto-fonts/files/8157187/Prod-report_NotoSerifTibetan_857328.pdf)
