### ISSUE TITLE
Unknown -> unreadable ligatures in Old Hungarian font

### ISSUE THREAD

**Issue by Kixidevel** [googlefonts/noto-fonts#1652]
Old Hungarian font has ligatures (without any UNICODE code points) which are unknown and unreadable. These ligatures maybe planned by a small group.
Unknown ligatures must to be removed from the font:
https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.otf
font  NotoSansOldHungarian-Regular.otf
 
Several of the unknown ligatures:
![unknown](https://user-images.githubusercontent.com/32356899/71802848-60116300-305f-11ea-9053-d82983e168ce.jpg)
![unknown2](https://user-images.githubusercontent.com/32356899/71802852-630c5380-305f-11ea-85ad-4b8b8f32dd52.jpg)

**Comment by Kixidevel** [comment]
@marekjez86 or another contributor,
Please remove ligatures, with conversation another Old Hungarian user groups.

**Comment by Kixidevel** [comment]
I just dropped an e-mail to a member of another Old Hungarian fan users, sent him the first one screenshot. He answered, that he never seen that kind of "ligature".

**Comment by Kixidevel** [comment]
@marekjez86  
There are another Old Hungarian homepages:
http://rovas.info/
They don't use ligatures. They don't use acute symbol for long vowels.
Another one:
http://www.old-hungarian.oldalunk.hu
They uses ligatures, but it works with special keyboard. The element of the ligatures have code points.
They don't use acute symbol for long vowels.

**Comment by Kixidevel** [comment]
@marekjez86 It will be merged sometimes, or I worked unecessarily

**Comment by Kixidevel** [comment]
@google-admin The Old Hungarian is already developed, but added some unknown ligatures, without UNICODE entrypoint, because of that never will work. 
These letters aren't part of UNICODE standard, and most of them never was used or not proved.
Before the standardization of Old Hungarian symbols had been an congress in Hungary, where decided wich symbols need to encode to the standard.
The standard table is:
https://unicode.org/charts/PDF/U10C80.pdf
The Old Hungarian letters are historic letters, nowadays some small groups try to modernize it.
The second thing, during the History never used these letters with acute, and another symbols.
Acute, and other symbols required only Latin based Hungarian texts, because the origin latin letters isn't  enought for writing Hungarian texts. Latin based texts as phonetic as it possible.
These are: 
á (long open a), é (long open e), í (long i),ó (long o), ö (same as German ö), ő (long ö),ú(long u), ü (special Hungarian sound), ű (long ü). 
The other vowels, with any kind of combining with modifier signs used only when must to write foreign names or expressions.
There are several consonant combination in latin based Hungarian text, too (for examle ny as soft n).
Unfortunatelly the explamation of Old Hungarian letters is written "telegraphy" style letters in UNICODE, describing readable for Hungarian users. 
For example:  
aa ->á
oe -> ö
oee ->ő
etc.
Hovewer the symbols was used RTL, LTR and Top-to-down forms during the history, the widelly accepted is RTL form. Old Hungarian symbols encoded the UNICODE RTL area.
In my opinion need clear these unnnecessary ligatures and combining marks, and close all open Issues about these modifications. 
The another thing,in my opinion LTR form of Old Hungarian font must be removed, following the strict standard.

**Comment by Kixidevel** [comment]
@google-admin following document describe Old Hungarian as rtl script:
http://www.unicode.org/roadmaps/smp/

**Comment by Kixidevel** [comment]
@google-admin 
Documents about UNICODE areas:
http://www.unicode.org/roadmaps/bmp/
http://www.unicode.org/roadmaps/smp/

**Comment by sztamasr** [comment]
@google-admin 
Kixidevel write the truth. No acute like chars required for the Old Hungarian font. There are unknown ligatures inside the font, without any UNICODE codepoints, which never wil be appear. These characters aren't part of the UNICODE standard called Old Hungarian.
There are Issues must to close. Issue #1374 and #1364. Must be close #1662 pull request, too.

**Comment by sztamasr** [comment]
@google-admin 
When the Issues and pull reguest closed above, and the hidden ligatures removed, the Old Hungarian font  will be made. No more changes required.

**Comment by Kixidevel** [comment]
@marekjez86 
@google-admin 
First I apologize for the critics, I didn't know, how the ligatures works.
The left-to-right part of font works correctly.
BUT:
the ligature definitions are caotical.
![Képernyőkép erről: 2020-04-05 10-56-13](https://user-images.githubusercontent.com/32356899/78471082-b5c4dc80-772e-11ea-9105-ed9130311eeb.png)
For example ligature above defined as "ab" ligature, but this form of ligature must be "szb", as it You look clearly.
May I resolve these problem? 
BUT:
Unfortunately it never will be works on Windows, because they didn't follow the standards, and the Old Hungarian keyboard developers must to add to all keys on their layout prefix or postfix Right-to-Left Marks.
AND:
Never used above acute and double above dots and that kind of signs in the Old Hungarian script.
AND:
HOWEVER the font has good form of ligatures, BUT has unreadable ligatures, too.

**Comment by Kixidevel** [comment]
@marekjez86 @google-admin
I am resolving ligature forms' problems, i am making capital ligatures. But I never will add acutes, and its "friends", because thats was burned in 21th century, not during history.

**Comment by Kixidevel** [comment]
@marekjez86 @google-admin 
Following document I wrote the critical letters.
![art](https://user-images.githubusercontent.com/32356899/84255530-0849bd00-ab13-11ea-85ad-0fac615b0cae.jpg)
Letters in first section must be remove. Those could be not prepared.
Others I will prepare for readable, or keep him.
The automatic ligature method could be miss. For example v+v produce the form of widely accepted w, but vv is not the same with w in Hungarian spelling.
I am working on it.

**Comment by Kixidevel** [comment]
@marekjez86:
I close It.
