### ISSUE TITLE
Noto Sans Adlam is unjoined

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1653]
### Font
NotoSansAdlam-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/453c5c12489fe8276c6f3a945ded8e73d4a8a837/phaseIII_only/unhinted/otf/NotoSansAdlam/NotoSansAdlam-Regular.otf
Date: 2020-01-05

### Font version
Version 3.000

### Issue
The topographical features 'init', 'medi', and 'fina' are not applied, because this font uses the script tag DFLT instead of 'adlm'.

### Character data
𞤰𞤰𞤰
U+1E930 ADLAM SMALL LETTER YHE
U+1E930 ADLAM SMALL LETTER YHE
U+1E930 ADLAM SMALL LETTER YHE

### Screenshot
![𞤰𞤰𞤰](https://user-images.githubusercontent.com/1124347/71829630-10d52d80-3073-11ea-8c33-88953b5a3217.png)

**Comment by marekjez86** [comment]
please try https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansAdlam/NotoSansAdlam-Regular.ttf or a corresponding otf

**Comment by dscorbett** [comment]
I confirm that everything but U+1E94B ADLAM NASALIZATION MARK joins correctly.
