### ISSUE TITLE
Overlapping vowel signs across U+0F0B TIBETAN MARK INTERSYLLABIC TSHEG

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1655]
### Font
NotoSerifTibetan-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/96e3d51ab4ad78e74a4cb0752dc25d010d6946de/unhinted/NotoSerifTibetan/NotoSerifTibetan-Regular.ttf
Date: 2020-01-02

### Font version
Version 2.001

### Issue
Kerning a cluster with a tsheg can make the cluster’s above-base vowel sign overlap the following cluster’s vowel sign. Without the tsheg, the vowel signs take their narrow forms, so there is no overlap.

### Character data
རྡོ་རྗེ
U+0F62 TIBETAN LETTER RA
U+0FA1 TIBETAN SUBJOINED LETTER DA
U+0F7C TIBETAN VOWEL SIGN O
U+0F0B TIBETAN MARK INTERSYLLABIC TSHEG
U+0F62 TIBETAN LETTER RA
U+0F97 TIBETAN SUBJOINED LETTER JA
U+0F7A TIBETAN VOWEL SIGN E

### Screenshot
![རྡོ་རྗེ](https://user-images.githubusercontent.com/1124347/72028396-5e5ac180-3250-11ea-8128-db10c809ec32.png)

**Comment by marekjez86** [comment]
corrected
[Prod-report_NotoSerifTibetan_857328.pdf](https://github.com/googlefonts/noto-fonts/files/8157183/Prod-report_NotoSerifTibetan_857328.pdf)
