### ISSUE TITLE
Inconsistent positioning of Tibetan ra above fixed-form wa

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1658]
### Font
NotoSerifTibetan-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/96e3d51ab4ad78e74a4cb0752dc25d010d6946de/unhinted/NotoSerifTibetan/NotoSerifTibetan-Regular.ttf
Date: 2020-01-02

### Font version
Version 2.001

### Issue
U+0F62 TIBETAN LETTER RA is shifted left above U+0FBA TIBETAN SUBJOINED LETTER FIXED-FORM WA only when there are other subjoined letters below it.

### Character data
རྺརྺྐ
U+0F62 TIBETAN LETTER RA
U+0FBA TIBETAN SUBJOINED LETTER FIXED-FORM WA
U+0F62 TIBETAN LETTER RA
U+0FBA TIBETAN SUBJOINED LETTER FIXED-FORM WA
U+0F90 TIBETAN SUBJOINED LETTER KA

### Screenshot
![རྺརྺྐ](https://user-images.githubusercontent.com/1124347/72210520-e62c1000-348a-11ea-9c9b-949f74f3e192.png)

**Comment by marekjez86** [comment]
corrected
[Prod-report_NotoSerifTibetan_857328.pdf](https://github.com/googlefonts/noto-fonts/files/8157180/Prod-report_NotoSerifTibetan_857328.pdf)
