### ISSUE TITLE
Inconsistent positioning of Tibetan wa below kha

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1659]
### Font
NotoSerifTibetan-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/96e3d51ab4ad78e74a4cb0752dc25d010d6946de/unhinted/NotoSerifTibetan/NotoSerifTibetan-Regular.ttf
Date: 2020-01-02

### Font version
Version 2.001

### Issue
<i>Wa</i> is subjoined on the right side of cluster-initial <i>kha</i> except when there are more subjoined letters below it.

### Character data
ཁྭཁྭྱ
U+0F41 TIBETAN LETTER KHA
U+0FAD TIBETAN SUBJOINED LETTER WA
U+0F41 TIBETAN LETTER KHA
U+0FAD TIBETAN SUBJOINED LETTER WA
U+0FB1 TIBETAN SUBJOINED LETTER YA

### Screenshot
![ཁྭཁྭྱ](https://user-images.githubusercontent.com/1124347/72223784-afb0cc80-3540-11ea-8fd7-c6939a4f6065.png)

**Comment by marekjez86** [comment]
This report was deemed as invalid. The left side rendering is
applied as a contextual alternate to avoid collisions between the base
glyph and its subjoined forms. This was the typeface designers intention.
