### ISSUE TITLE
Santali Font and its meaning

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#166]
```
What steps will reproduce the problem?
1. Nato Sans and Nato sarif has a English font in Santali Language.
2.
3.

What is the expected output? What do you see instead?
Output should be as attached Draft.

What version of the product are you using? On what operating system?
Chrome Os

Please provide any additional information below.
Million of people loving this Santali Language.

```

Original issue reported on code.google.com by `kmurmu918@gmail.com` on 27 Sep 2014 at 6:28
- Merged into: #160

Attachments:
- [SANTALI FONT.pdf](https://storage.googleapis.com/google-code-attachments/noto/issue-166/comment-0/SANTALI FONT.pdf)

**Comment by sivamechh** [comment]
Please create UNICODE FONT This fonts above provided are actually English. But in the shape of your Language. Unicode space allocated to Santali language and to my surprise till now santali don't have Unicode font to write it. First create a Unicode Font and then you can do it 
@Murmu contact me Facebook.com/nglsiva

**Comment by brawer** [comment]
Hello @sivamechh, how about this font?
http://www.google.com/get/noto/#sans-olck
https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSansOlChiki-Regular.ttf?raw=true
