### ISSUE TITLE
Pashto Letters with Ring

### ISSUE THREAD

**Issue by schwantuschke** [googlefonts/noto-fonts#1668]
I use on mac the unhinted font Noto Naskh Arabic Regular version 1.08 uh with pashto letters with Rings like: ړ ټ ڼ ډ

The font looks like this:
<img width="166" alt="Bildschirmfoto 2020-01-21 um 12 49 59" src="https://user-images.githubusercontent.com/4090141/72802672-98fb2b80-3c4c-11ea-9cf7-8de33c226aaf.png">

But the rings must be connected to the letter. Here a sceenshot from the font Noto Naskh Arabic UI Regular version 1.07 uh. I think this is correct.
<img width="173" alt="Bildschirmfoto 2020-01-21 um 12 52 16" src="https://user-images.githubusercontent.com/4090141/72802834-f1cac400-3c4c-11ea-8e1b-0d664a673cb8.png">

Is this a bug in Noto Naskh Arabic Regular?

**Comment by nizarsq** [comment]
@schwantuschke could you add the URLs for version 1.08 and version 1.07 Thanks

**Comment by schwantuschke** [comment]
@nizarsq I downloaded this font from google.com/get/noto
Directly: https://noto-website-2.storage.googleapis.com/pkgs/NotoNaskhArabic-unhinted.zip
I see the Noto Naskh Arabic Regular is in version 1.07 uh. But have the same problem too.

**Comment by nizarsq** [comment]
@schwantuschke thank you for the information. Please try the font in this repository [https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf](url). Tested and it looks good to me. Feel free to reopen the bug if you have other observations.
<img width="444" alt="Screen Shot 2020-05-20 at 4 44 14 PM" src="https://user-images.githubusercontent.com/22158882/82508372-b5538b80-9ab9-11ea-87c7-f486890bd40f.png">

**Comment by schwantuschke** [comment]
@nizarsq Thank, this file works fine. This Fonts have version 2.0. From https://www.google.com/get/noto/ I get only version 1. There are this files from github Phase III final files?
