### ISSUE TITLE
How to combine two or more fonts?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#167]
```
What steps will reproduce the problem?
1. an application to combine two or more fonts
2. unified font already
3. other reasonable way to solve this problem


What is the expected output? What do you see instead?

First of all, I always appreciate to google about amazing and invaluable this 
innovation to unify fonts, sincerely.

I am a Korean and I’m working in China.

Because of this circumstance and situation, I usually must use Korean, Chinese 
and English.

This time, you provide very amazing service for us, I hope to need something 
which combine both or more fonts.

Specially, I’d like to combine Korean, Chinese simplified.

Actually, I love this font but it have big inconvenient.

I want to use both language on same time, for that if it really work, I must to 
try to adjust finely again and again.

I have wasted a lot of time for internet searching, book and asking, I 
haven’t success and still try it work.

So I really hope an alternative to combine two or more fonts for different 
language.

I think, for Noto fonts, it’s the best thinking that you will provide an 
application to combine fonts.

There is amazingly many people like not only me but also my colleagues.

I will always wait for your positive answer.

```

Original issue reported on code.google.com by `kabei...@gmail.com` on 29 Sep 2014 at 8:22
- Merged into: #97

**Comment by comfytoday** [comment]
Is there any way of combining multiple Noto fonts into a single Universal family?

Noto Sans CJK
Noto Sans
Noto Sans Thai
Noto Sans Arabic

**Comment by punchcutter** [comment]
pyftmerge from fontTools can merge TTF fonts, but in your example there are a couple problems. The Pan CJK fonts have the maximum number of glyphs possible so there's no room to add anything else. If you used a language specific CJK font like NotoSansJP-Regular.otf then there is still room for more glyphs, but all the CJK fonts are currently OTF which doesn't work with pyftmerge. And as stated above there are no plans for TTF. Doing a merge of the other 3 is fairly simple with pyftmerge.

**Comment by comfytoday** [comment]
So the real issue is that there is a technical limit to number of glyphs we can include in a single font file? Is that limit imposed by the UTF encoding?

Is that why there is no 'universal' Noto Sans?

**Comment by punchcutter** [comment]
The technical limit is in the font format. That's one reason there isn't a single font with everything, but another reason is that it would be a very big file which would be slow to work with. And most people only need a couple of these fonts so it makes more sense to keep them separate from a design/production standpoint as well as a delivery/use standpoint.

**Comment by comfytoday** [comment]
Got it. Thanks.
I'll play around with pyftmerge and see if we can come up with a compromise. 
Our use case is definitely unusual.
