### ISSUE TITLE
Characters infinity, lessequal, greaterequal from NotoSans-Regular.ttf not shown

### ISSUE THREAD

**Issue by vk-github18** [googlefonts/noto-fonts#1672]
### Title 
  Characters infinity, lessequal, greaterequal from NotoSans-Regular.ttf not shown

### Font 
 NotoSans-Regular.ttf

### Where the font came from, and when
  Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-hinted.zip
  Date: 2020-02-28

### Font Version
 2.000;GOOG;noto-source...

### OS name and version
  Microsoft Windows 10

### Application name and version
  hb_view.exe (HarfBuzz) 2.6.4

### Issue
  > Summarize the issue briefly -- one paragraph preferred

      The characters infinity, less than, greater than  (U+221e, U+2264, U+2265) are not shown.

  1. Steps to reproduce

	harfbuzz-2.6.4-win32\hb-view.exe fonts\NotoSans-Regular.ttf --text-file fonts\latin_inf_le_ge.txt -O pdf -o NotoSans-Regular-inf-le-ge.pdf

[latin_inf_le_ge.txt](https://github.com/googlefonts/noto-fonts/files/4276330/latin_inf_le_ge.txt)

 2. Observed results
    Characters are not shown
![NotoSans-Regular-inf-le-ge](https://user-images.githubusercontent.com/39316085/75693484-48450c80-5ca7-11ea-9e62-cd8ef4befc4e.png)

3. Expected results
   Characters inf, le, ge are shown
![latin_inf_le_ge-expected](https://user-images.githubusercontent.com/39316085/75693565-6874cb80-5ca7-11ea-99d6-17f401d2a861.png)

### Character data

U+221e ∞ INFINITY  
U+2264 ≤ LESS-THAN OR EQUAL TO  
U+2265 ≥ GREATER-THAN OR EQUAL TO  

### Remark
These characters are also not shown with the java library iText 2.1.7 or Apache FOP 2.4

**Comment by nizarsq** [comment]
@marekjez86 look like 221e 2264 and 2265 are missing in NotoSans and NotoSerif but NotoSansMono, can you double check?
<img width="423" alt="Screen Shot 2020-06-27 at 10 10 28 AM" src="https://user-images.githubusercontent.com/22158882/85928024-ce8cec00-b85e-11ea-9d28-9c0e2b837134.png">
221e 2264 2265 not exist in NotoSans or NotoSerif but NotoSansMono, can you double check.

**Comment by marekjez86** [comment]
Correct. This is as expected. These characters are part of [NotoSansMath](https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansMath) . They are in Mono because we wanted to have fixed width version of these there.

**Comment by nizarsq** [comment]
Make sense. Thanks!
