### ISSUE TITLE
Overlapping above-base marks in Noto Sans Arabic

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1686]
### Font
NotoSansArabic-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/115d38430d957d38307457c036302b7bdbe0bbc4/phaseIII_only/unhinted/otf/NotoSansArabic/NotoSansArabic-Regular.otf
Date: 2020-03-30

### Font Version
Version 2.500

### Issue
Above-base marks overlap the ijam above some letters.

### Character data
ݸٝݹٝݳٝݴٝݵٝݶٝݺٝݻٝݽٝۼٝ
U+0778 ARABIC LETTER WAW WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE
U+065D ARABIC REVERSED DAMMA
U+0779 ARABIC LETTER WAW WITH EXTENDED ARABIC-INDIC DIGIT THREE ABOVE
U+065D ARABIC REVERSED DAMMA
U+0773 ARABIC LETTER ALEF WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE
U+065D ARABIC REVERSED DAMMA
U+0774 ARABIC LETTER ALEF WITH EXTENDED ARABIC-INDIC DIGIT THREE ABOVE
U+065D ARABIC REVERSED DAMMA
U+0775 ARABIC LETTER FARSI YEH WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE
U+065D ARABIC REVERSED DAMMA
U+0776 ARABIC LETTER FARSI YEH WITH EXTENDED ARABIC-INDIC DIGIT THREE ABOVE
U+065D ARABIC REVERSED DAMMA
U+077A ARABIC LETTER YEH BARREE WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE
U+065D ARABIC REVERSED DAMMA
U+077B ARABIC LETTER YEH BARREE WITH EXTENDED ARABIC-INDIC DIGIT THREE ABOVE
U+065D ARABIC REVERSED DAMMA
U+077D ARABIC LETTER SEEN WITH EXTENDED ARABIC-INDIC DIGIT FOUR ABOVE
U+065D ARABIC REVERSED DAMMA
U+06FC ARABIC LETTER GHAIN WITH DOT BELOW
U+065D ARABIC REVERSED DAMMA

### Screenshot
![ݸٝݹٝݳٝݴٝݵٝݶٝݺٝݻٝݽٝۼٝ](https://user-images.githubusercontent.com/1124347/77934947-c84a9c00-727e-11ea-9f01-2ef84d7d106b.png)

**Comment by nizarsq** [comment]
This issue reproducible on otf and ttf fonts.
<img width="674" alt="Screen Shot 2020-05-20 at 12 30 13 AM" src="https://user-images.githubusercontent.com/22158882/82417898-1a16d380-9a31-11ea-9f2c-8ef1d202a245.png">

**Comment by nizarsq** [comment]
dup https://github.com/googlefonts/noto-fonts/issues/1197. Anchor points are missing

**Comment by marekjez86** [comment]
@nizarsq : I'd like to fix it also in the UI font. If it never comes up in the UI font then we do not need to worry about the truncation :-)

**Comment by nizarsq** [comment]
> @nizarsq : I'd like to fix it also in the UI font. If it never comes up in the UI font then we do not need to worry about the truncation :-)

Sure. I'll fix it on UI too. Thanks
