### ISSUE TITLE
៉ khmer sign muusikatoan incorrect on ម khmer letter mo when followed by ិ khmer vowel sign i

### ISSUE THREAD

**Issue by kmuncie** [googlefonts/noto-fonts#1688]
### Font 
`NotoSansKhmer-Regular.ttf`

Note: this issue has also been observer on the Bold variant and so may exist for all NotoSansKhmer variants. 

### Where the font came from, and when
Site: [https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/hinted/ttf/NotoSansKhmer/NotoSansKhmer-Regular.ttf](https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/hinted/ttf/NotoSansKhmer/NotoSansKhmer-Regular.ttf)

### Font Version
Version 2.001; ttfautohint (v1.8.2)

### Issue
![noto-khmer-bug](https://user-images.githubusercontent.com/582755/78084118-4173ed00-736c-11ea-8c0c-c21ffc12c379.jpg)

The diacritic khmer sign muusikatoan is incorrectly appearing below the khmer letter mo when it is followed by a character carrying the khmer vowel sign i. This issue is seen when any consonant with the vowel modifier ៉ plus vowel sign េ and then followed by រ with either  ិ, ី, ឹ or ឺ.

Expected result is displayed in screenshot above. The first the examples are shown in DaunPenh, Khmer MN, and Arial Unicode MS fonts. All of those examples render this correctly. 

### Character data

Sample string: `ម៉េរិ`

|   |Unicode character  |Oct                     |Dec     |Hex   |HTML    |
|---|-------------------|------------------------|--------|------|--------|
|ម  |khmer letter mo    |013630                  |6040    |0x1798|&#6040; |
|៉  |khmer sign muusikatoan|013711                  |6089    |0x17C9|&#6089; |
|េ  |khmer vowel sign e |013701                  |6081    |0x17C1|&#6081; |
|រ  |khmer letter ro    |013632                  |6042    |0x179A|&#6042; |
|ិ  |khmer vowel sign i |013667                  |6071    |0x17B7|&#6071; |

**Comment by nizarsq** [comment]
<img width="1096" alt="Screen Shot 2020-09-13 at 4 07 03 PM" src="https://user-images.githubusercontent.com/22158882/93030867-2bd14780-f5db-11ea-8b16-159036fd9d56.png">

**Comment by marekjez86** [comment]
https://github.com/googlefonts/noto-fonts/blob/master/hinted/ttf/NotoSansKhmer/NotoSansKhmer-Regular.ttf , 
https://github.com/googlefonts/noto-fonts/blob/master/hinted/ttf/NotoSansKhmerUI/NotoSansKhmerUI-Regular.ttf ,
https://github.com/googlefonts/noto-fonts/blob/master/hinted/ttf/NotoSerifKhmer/NotoSerifKhmer-Regular.ttf should have the fixes

**Comment by kmuncie** [comment]
> https://github.com/googlefonts/noto-fonts/blob/master/hinted/ttf/NotoSansKhmer/NotoSansKhmer-Regular.ttf ,
> https://github.com/googlefonts/noto-fonts/blob/master/hinted/ttf/NotoSansKhmerUI/NotoSansKhmerUI-Regular.ttf ,
> https://github.com/googlefonts/noto-fonts/blob/master/hinted/ttf/NotoSerifKhmer/NotoSerifKhmer-Regular.ttf (and all other members of the font family) should have the fixes

@marekjez86 in using these updated fonts I find that the version number was not changed so these fonts with the merged fix are the same 2.001 version as before. Is that expected for a bug fix like this? Thanks
