### ISSUE TITLE
glyphs for chess symbols mismatched in NotoSansSymbols2

### ISSUE THREAD

**Issue by yn0793** [googlefonts/noto-fonts#1691]
### Font 
NotoSansSymbols2-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/ttf/NotoSansSymbols2/NotoSansSymbols2-Regular.ttf
Date: 2020-04-03

### Font Version
Version 2.002

### Issue
2 Xiangqi chess symbol glyphs does not match code point.

### Character data
🩪🩫
U+1FA6A XIANGQI BLACK HORSE
U+1FA6B XIANGQI BLACK CHARIOT

### Screenshot
NotoSansSymbols2
![批注 2020-04-03 200140](https://user-images.githubusercontent.com/32827924/78358617-11378300-75e6-11ea-8a6a-77c6b67bb17d.png)
Unicode CodeCharts
![批注 2020-04-03 200217](https://user-images.githubusercontent.com/32827924/78358628-17c5fa80-75e6-11ea-8c86-dc748c9ba431.png)

**Comment by nizarsq** [comment]
Issue reproducible using the current NotoSansSymbols2
<img width="1047" alt="Screen Shot 2020-07-24 at 10 09 01 PM" src="https://user-images.githubusercontent.com/22158882/88449261-47e61300-cdfa-11ea-8ddc-fc7e4ecc4a1a.png">

**Comment by nizarsq** [comment]
This issue fixed. Please let me know if they look ok now. Thank you for filing this issue.
