### ISSUE TITLE
U+116B7 TAKRI SIGN NUKTA blocks kerning

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1693]
### Font
NotoSansTakri-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/115d38430d957d38307457c036302b7bdbe0bbc4/phaseIII_only/unhinted/otf/NotoSansTakri/NotoSansTakri-Regular.otf
Date: 2020-04-04

### Font version
Version 2.001

### Issue
U+116B7 TAKRI SIGN NUKTA blocks the kerning between consonants and U+116AF TAKRI VOWEL SIGN II.

### Character data
𑚖𑚷𑚯
U+11696 TAKRI LETTER DDA
U+116B7 TAKRI SIGN NUKTA
U+116AF TAKRI VOWEL SIGN II
𑚖𑚯
U+11696 TAKRI LETTER DDA
U+116AF TAKRI VOWEL SIGN II

### Screenshot
![𑚖𑚷𑚯 𑚖𑚯](https://user-images.githubusercontent.com/1124347/78454201-9f524e80-7664-11ea-9b55-4360f2096243.png)

**Comment by punchcutter** [comment]
Fixed in https://github.com/googlefonts/noto-source/pull/202
<img width="224" alt="1693fix" src="https://user-images.githubusercontent.com/11257204/82133870-b4fb7d80-97a5-11ea-8c8e-4d27e412749f.png">

**Comment by marekjez86** [comment]
fixed in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansTakri and https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansTakri
