### ISSUE TITLE
No pre-base reordering in 'mlym'

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1697]
### Font
NotoSansMalayalam-Regular.otf
NotoSerifMalayalam-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/115d38430d957d38307457c036302b7bdbe0bbc4/phaseIII_only/unhinted/otf/NotoSansMalayalam/NotoSansMalayalam-Regular.otf
Site: https://github.com/googlefonts/noto-fonts/blob/115d38430d957d38307457c036302b7bdbe0bbc4/phaseIII_only/unhinted/otf/NotoSerifMalayalam/NotoSerifMalayalam-Regular.otf
Date: 2020-04-07

### Font version
Version 2.000

### Issue
With the script tag 'mlym', the pre-base cluster-final <i>ra</i> is not reordered to the beginning of the cluster. (It works with the script tag 'mlm2'.)

### Character data
ഖ്ര
U+0D16 MALAYALAM LETTER KHA
U+0D4D MALAYALAM SIGN VIRAMA
U+0D30 MALAYALAM LETTER RA

### Screenshot
![ഖ്ര](https://user-images.githubusercontent.com/1124347/78737285-292c4100-791d-11ea-812e-c21b06236807.png)
![ഖ്ര](https://user-images.githubusercontent.com/1124347/78737286-292c4100-791d-11ea-9884-5187b3d04bac.png)

**Comment by nizarsq** [comment]
I couldn't reproduce this issue using otf or ttf.  Fonts used:
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansMalayalam/NotoSansMalayalam-Regular.ttf
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansMalayalam/NotoSansMalayalam-Regular.otf
<img width="928" alt="Screen Shot 2020-06-19 at 3 51 48 PM" src="https://user-images.githubusercontent.com/22158882/85184532-e9e76e00-b244-11ea-9e29-22a541d6c49d.png">

**Comment by dscorbett** [comment]
When I shape the latest fonts with HarfBuzz, they still fail to reorder with 'mlym'. @nizarsq, are you sure your test used 'mlym' instead of 'mlm2'?

**Comment by simoncozens** [comment]
We’re no longer supporting old style shapers.
