### ISSUE TITLE
Missing basic characters such as numerals and punctuation marks in Grantha

### ISSUE THREAD

**Issue by karthikraman** [googlefonts/noto-fonts#1705]
### Font 
`NotoSansGrantha-Regular.ttf` and also `NotoSerifGrantha-Regular.ttf`

### Font Version
2.0.0

### Issue
The font is amazing, but it does contain only the Grantha blocks apparently. Therefore, while using the font in processors such as TeX, many standard characters do not render, e.g. brackets, punctuation (comma, semi-colon, em-dash, en-dash, hyphen etc.) and normal Hindu-Arabic numerals. It would be highly helpful if these characters are integrated into the font, perhaps from the corresponding blocks in NotoSerif or NotoSans.

**Comment by punchcutter** [comment]
@karthikraman Unfortunately, all of the Noto fonts are like this and do not always contain punctuation or numerals that are part of the Latin font. It's possible to merge the TTFs using pyftmerge from https://github.com/fonttools/fonttools, but I just tried it with Noto Sans and Noto Sans Grantha and there are a lot of problems with the merge. If you'd like something soon let me know and I can make something that works for you. I also just updated both Sans and Serif Grantha with some fixes, but they aren't ready for download yet.

**Comment by karthikraman** [comment]
No problem. @jamadagni made these edits and shared with me --- perhaps, others will find them useful too.
[NotoGrantha.zip](https://github.com/googlefonts/noto-fonts/files/4680795/NotoGrantha.zip)

**Comment by punchcutter** [comment]
Ok, that's good. @jamadagni should update with the latest files once they are ready.

**Comment by nizarsq** [comment]
Closing this bug as WAI.

**Comment by jamadagni** [comment]
I am not sure what WAI is and why this is closed.  @punchcutter had asked for the files but @karthikraman had already posted the files. Why is this closed?
