### ISSUE TITLE
Noto Serif Tibetan Rendering Issue in OSX

### ISSUE THREAD

**Issue by toddbeeby** [googlefonts/noto-fonts#1726]
## Defect Report
Use this template for filing a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
Noto Serif Tibetan Rendering Issue in OSX

### Font 
NotoSerifTibetan-Regular.ttf
[regooglefontstibetanfontissue.zip](https://github.com/googlefonts/noto-fonts/files/4549710/regooglefontstibetanfontissue.zip)

### Where the font came from, and when
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf
Date: 2020-04-27

### Font Version
2.001

### OS name and version
Mojave 10.14.3 (18D42)

### Application name and version
Adobe Indesign version 15.0.2
Apple Pages version 7.3 (5989)
Apple Text Edit version 1.14 (341)

### Issue
InDesign: Tibetan text copied from a google doc (unknown font) and pasted into InDesign. Order of Tibetan characters messing up (stacking in strange places). 
Apple Pages: Cannot choose NotoSerif-Tibetan from font drop-down menu
Apple Text Edit: Cannot choose NotoSerif-Tibetan from font drop-down menu

Expect to behave as any other font and appear in drop-down menu for native Apple apps. Expect to appear correctly in InDesign. 

The font "Qomolangma-Uchen Sarchung" renders correctly in InDesign. This is not an Open Source font. You can find it here: http://www.yalasoo.com/English/docs/yalasoo_en_qomolangma_fonts.html

Other Tibetan fonts have worse rendering issues than NotoSerif-Tibetan

### Character data

༄༄ །། སྐྱོན་གྱིས་མ་གོས་སྐུ་མདོག་དཀར།།
རྫོགས་སངས་རྒྱས་ཀྱིས་དབུ་ལ་བརྒྱན།།
ཐུགས་རྗེའི་སྤྱན་གྱིས་འགྲོ་ལ་གཟིགས།།
སྤྱན་རས་གཟིགས་ལ་ཕྱག་འཚལ་ལོ།། །།

༄༄ །། སངས་རྒྱས་ཀུན་གྱིས་རབ་ཏུ་བསྔགས།།

ཡོན་ཏན་དམ་པ་ཀུན་བསགས་པ།།
སྤྱན་རས་གཟིགས་ཞེས་མཚན་གསོལ་པ།།
རྟག་པར་བརྩེ་ལ་ཕྱག་འཚལ་ལོ།། །།

ཨོཾ་མ་ཎི་པདྨེ་ཧཱུྃ།

### Screenshot
![Screen Shot 2020-04-29 at 3 37 58 PM](https://user-images.githubusercontent.com/64512179/80559564-0a0f6380-8a32-11ea-9132-77cfb9efeb1f.png)
![Screen Shot 2020-04-29 at 3 40 50 PM](https://user-images.githubusercontent.com/64512179/80559575-0ed41780-8a32-11ea-9df5-90f0c02a57b2.png)

## Tools for reporting bugs
  Useful tools for reporting bugs are available at: https://github.com/googlei18n/
  
### Harfbuzz hb-view and hb-shape
  These are part of the HarfBuzz distribution and can help isolate if an issue is in the app/OS, shaping engine, or font.
  * hb-view renders the text with the exact font (for example, to see how ligatured characters shape) using your installed version of HarfBuzz.

For example:
```
  hb-view --font-file {path to font} --text-file {path to text file} --output-file '{sample}.png'
```

* hb-shape shows glyph selection and positioning

### Fontview
  * Fontview displays the text.

### Fontdiff
  * Fontdiff displays the text using two versions of the font side by side.

**Comment by nizarsq** [comment]
@toddbeeby Thank you for reporting this issue. I looked at (རྫོ , རྩེ་ལ , ཧཱུྃ།).  All of them looks good to me on Chrome, TextEdit,  Safari and Firefox. I believe this is rendering issue in Indesign. See attached. Could you install NotoSerifTibetan on your machine and retest using maybe Textedit? @marekjez86 for second opinion/closing if needed.

Chrome:
<img width="1073" alt="Screen Shot 2020-09-08 at 9 24 00 PM" src="https://user-images.githubusercontent.com/22158882/92554204-9f5d0880-f219-11ea-9f89-157f6ce4d24b.png">

Safari:
<img width="1087" alt="Screen Shot 2020-09-08 at 9 25 12 PM" src="https://user-images.githubusercontent.com/22158882/92554276-cb788980-f219-11ea-9928-7b700c712aaf.png">

Firefox:
<img width="669" alt="Screen Shot 2020-09-08 at 9 26 02 PM" src="https://user-images.githubusercontent.com/22158882/92554316-e6e39480-f219-11ea-87f5-eae4d472f5ea.png">

TextEdit:
<img width="549" alt="Screen Shot 2020-09-08 at 9 22 39 PM" src="https://user-images.githubusercontent.com/22158882/92554113-6d4ba680-f219-11ea-8aed-d10c3844e0cd.png">

**Comment by nizarsq** [comment]
@toddbeeby Please file this issue with Indesign. Thank you

**Comment by toddbeeby** [comment]
@nizarsq Thanks for checking this out. It turned out to be my own error (which I'm sure you would have guessed already, doh!) and a setting change in InDesign fixed the rendering issue. Being my first time using a non-English typeface It took me a while to find the setting but thanks for the confirmation.
