### ISSUE TITLE
Narrow Tibetan vowels are still too wide for ang khang

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1727]
### Font
NotoSerifTibetan-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/7f12f3e70af9d2507206093d903eb9945d7e4622/phaseIII_only/unhinted/otf/NotoSerifTibetan/NotoSerifTibetan-Regular.otf
Date: 2020-04-28

### Font version
Version 2.001

### Issue
Above-base vowel signs take their narrow forms next to U+0F3C and U+0F3D. However, they still overlap them, just in a different way. (In my screenshot below, the right example is with narrow forms disabled.) If the point is to avoid overlap, another solution is needed.

### Character data
༼ངོ༽
U+0F3C TIBETAN MARK ANG KHANG GYON
U+0F44 TIBETAN LETTER NGA
U+0F7C TIBETAN VOWEL SIGN O
U+0F3D TIBETAN MARK ANG KHANG GYAS

### Screenshot
![༼ངོ༽༼ངོ༽](https://user-images.githubusercontent.com/1124347/80602527-3eb4f800-89fd-11ea-9407-a78867bd480b.png)

**Comment by nizarsq** [comment]
<img width="1030" alt="Screen Shot 2020-09-08 at 9 43 51 PM" src="https://user-images.githubusercontent.com/22158882/92555386-64100900-f21c-11ea-9a1c-531329af2806.png">
