### ISSUE TITLE
Inconsistent truncation of U+1A2C TAI THAM LETTER NYA

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1739]
### Font
NotoSansTaiTham-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/7a9a8dbf7c9193298a1b11ad2e9acf5e039fc530/phaseIII_only/unhinted/otf/NotoSansTaiTham/NotoSansTaiTham-Regular.otf
Date: 2020-05-07

### Font version
Version 2.000

### Issue
U+1A2C TAI THAM LETTER NYA gets a truncated form when there is a mark below, unless it happens to have already been ligated with another glyph.

### Character data
ᨬᩬᨬᩕᩬᨬ᩠ᨬᩬᨬ᩠ᨬᩕᩬ
U+1A2C TAI THAM LETTER NYA
U+1A6C TAI THAM VOWEL SIGN OA BELOW
U+1A2C TAI THAM LETTER NYA
U+1A55 TAI THAM CONSONANT SIGN MEDIAL RA
U+1A6C TAI THAM VOWEL SIGN OA BELOW
U+1A2C TAI THAM LETTER NYA
U+1A60 TAI THAM SIGN SAKOT
U+1A2C TAI THAM LETTER NYA
U+1A6C TAI THAM VOWEL SIGN OA BELOW
U+1A2C TAI THAM LETTER NYA
U+1A60 TAI THAM SIGN SAKOT
U+1A2C TAI THAM LETTER NYA
U+1A55 TAI THAM CONSONANT SIGN MEDIAL RA
U+1A6C TAI THAM VOWEL SIGN OA BELOW
ᨬᩭᨬᩕᩭᨬ᩠ᨬᩭᨬ᩠ᨬᩕᩭ
U+1A2C TAI THAM LETTER NYA
U+1A6D TAI THAM VOWEL SIGN OY
U+1A2C TAI THAM LETTER NYA
U+1A55 TAI THAM CONSONANT SIGN MEDIAL RA
U+1A6D TAI THAM VOWEL SIGN OY
U+1A2C TAI THAM LETTER NYA
U+1A60 TAI THAM SIGN SAKOT
U+1A2C TAI THAM LETTER NYA
U+1A6D TAI THAM VOWEL SIGN OY
U+1A2C TAI THAM LETTER NYA
U+1A60 TAI THAM SIGN SAKOT
U+1A2C TAI THAM LETTER NYA
U+1A55 TAI THAM CONSONANT SIGN MEDIAL RA
U+1A6D TAI THAM VOWEL SIGN OY

### Screenshots
![ᨬᩬᨬᩕᩬᨬ᩠ᨬᩬᨬ᩠ᨬᩕᩬ](https://user-images.githubusercontent.com/1124347/81477258-cb716a00-91e4-11ea-9605-999c82d33e6b.png)
![ᨬᩭᨬᩕᩭᨬ᩠ᨬᩭᨬ᩠ᨬᩕᩭ](https://user-images.githubusercontent.com/1124347/81477170-530aa900-91e4-11ea-8b38-6dd0e243b9af.png)

**Comment by Arloka** [comment]
uni1A2C used with other consonants as has been shown above is not exist in real word. It is considered in a group of ᨧ (ᨧ ᨨ ᨩ ᨫ ᨬ) only subs of ᨧ ᨨ ᨩ ᨫ can be come after ᨬ such as ᨷᨬ᩠ᨧ ᨷᨬ᩠ᨩᩦ ᨠᩥᨬ᩠ᨧᩥ 
![Screen Shot 2020-05-22 at 1 22 51 PM](https://user-images.githubusercontent.com/17794142/82645624-cecb1380-9c30-11ea-83ae-cad5251fa417.png)
