### ISSUE TITLE
U+116AB TAKRI SIGN ANUSVARA overlaps with other signs of the script.

### ISSUE THREAD

**Issue by nik9hil** [googlefonts/noto-fonts#1741]
### Font 
 NotoSansTakri-Regular.otf
  
### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/115d38430d957d38307457c036302b7bdbe0bbc4/phaseIII_only/unhinted/otf/NotoSansTakri/NotoSansTakri-Regular.otf
 
Date: 2020-05-10

### Font Version
 Version 2.001

### Issue
 U+116AB TAKRI SIGN ANUSVARA overlaps with other signs of the script. The problem is irrespective of the letter being used.

### Character data
Image 1
U+116A2 TAKRI LETTER MA   𑚢
U+116B2 TAKRI VOWEL SIGN E    𑚲
U+116AB TAKRI SIGN ANUSVARA   𑚫

Image 2
U+1168A TAKRI LETTER KA   𑚊 
U+116B3 TAKRI VOWEL SIGN AI   𑚳
U+116AB TAKRI SIGN ANUSVARA   𑚫

Image 3
U+11699 TAKRI LETTER TA   𑚙 
U+116B5 TAKRI VOWEL SIGN AU  𑚵   
U+116AB TAKRI SIGN ANUSVARA  𑚫

Image 4
U+116A0 TAKRI LETTER BA   𑚠 
U+116B4 TAKRI VOWEL SIGN O   𑚴  
U+116AB TAKRI SIGN ANUSVARA  𑚫
 
### Screenshot
![image](https://user-images.githubusercontent.com/32241740/81501226-d4516100-92f4-11ea-8736-377f85a11426.png)
![image](https://user-images.githubusercontent.com/32241740/81501291-41fd8d00-92f5-11ea-871f-edd41061fe1e.png)
![image](https://user-images.githubusercontent.com/32241740/81501575-d3b9ca00-92f6-11ea-967b-ae458e4bb24d.png)
![image](https://user-images.githubusercontent.com/32241740/81501519-70c83300-92f6-11ea-9be5-2b07f46595d5.png)

**Comment by punchcutter** [comment]
Fixed in https://github.com/googlefonts/noto-source/pull/202
<img width="364" alt="1741fix" src="https://user-images.githubusercontent.com/11257204/82133785-bed0b100-97a4-11ea-8423-301b6738774d.png">

**Comment by marekjez86** [comment]
fixed in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansTakri and https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansTakri
