### ISSUE TITLE
Wrong placement of U+116AB TAKRI SIGN ANUSVARA

### ISSUE THREAD

**Issue by nik9hil** [googlefonts/noto-fonts#1742]
### Font 
NotoSansTakri-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/115d38430d957d38307457c036302b7bdbe0bbc4/phaseIII_only/unhinted/otf/NotoSansTakri/NotoSansTakri-Regular.otf 

Date: 2020-05-10

### Font Version
Version 2.001

### Issue
The placement of U+116AB TAKRI SIGN ANUSVARA, with U+116AF TAKRI VOWEL SIGN II and U+116AD TAKRI VOWEL SIGN AA is wrong. The placement of ANUSVARA, for these two vowel signs, should be after the cluster word, not within the vowel or above the base. The problem exists irrespective of base letter used. 

### Character data
Image1 (Incorrect placement because anusvara is within vowel EE)
U+1168C TAKRI LETTER GA  𑚌 
U+116AF TAKRI VOWEL SIGN II  𑚯
U+116AB TAKRI SIGN ANUSVARA 𑚫 

Image2 (Incorrect placement because anusvara is above the base)
U+116A8 TAKRI LETTER SA  𑚨 
U+116AD TAKRI VOWEL SIGN AA   𑚭
U+116AB TAKRI SIGN ANUSVARA  𑚫  

Anusvara with these two vowels should be placed after the vowel 

Image3(EXAMPLE OF CORRECT PLACEMENT, TAKEN FROM LOCAL SOURCE NOT FROM NOTO SANS TAKRI REGULAR, SEE ONLY WITHIN MARKED AREA)
U+116A8 TAKRI LETTER SA  𑚨 
U+116AD TAKRI VOWEL SIGN AA   𑚭
U+116AB TAKRI SIGN ANUSVARA 𑚫 

### Screenshot
![image](https://user-images.githubusercontent.com/32241740/81501986-cef61580-92f8-11ea-9948-fc3e6e72f5d0.png)
![image](https://user-images.githubusercontent.com/32241740/81502458-be936a00-92fb-11ea-935a-182711ebd19a.png)
![image](https://user-images.githubusercontent.com/32241740/81502512-04503280-92fc-11ea-9331-2a584cdffd2c.png)

**Comment by punchcutter** [comment]
Fixed in https://github.com/googlefonts/noto-source/pull/202
<img width="255" alt="1742fix" src="https://user-images.githubusercontent.com/11257204/82133699-f68b2900-97a3-11ea-871b-3891f0bd2847.png">

**Comment by marekjez86** [comment]
fixed in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansTakri and https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansTakri
