### ISSUE TITLE
Absence of U+116B8 TAKRI LETTER ARCHAIC KHA 

### ISSUE THREAD

**Issue by nik9hil** [googlefonts/noto-fonts#1743]
### Font 
NotoSansTakri-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/115d38430d957d38307457c036302b7bdbe0bbc4/phaseIII_only/unhinted/otf/NotoSansTakri/NotoSansTakri-Regular.otf 

Date: 2020-05-10

### Font Version
Version 2.001

### Issue
The archaic kha is missing from the font package, even though it is included in Unicode for Takri. The letter is useful as it is also used to denote TAKRI LETTER SSA which is currently been denoted by 𑚨𑚶𑚨. 

### Character data
U+116B8 TAKRI LETTER ARCHAIC KHA 𑚸

**Comment by punchcutter** [comment]
This letter is already in the font and has been for a long time.

**Comment by nik9hil** [comment]
I couldn't get it, sorry for wasting the time. May you explain how to get it?

**Comment by punchcutter** [comment]
𑚸
You can copy that to see, but how are you inputting other letters? Do you have a keyboard? Maybe the keyboard needs to add this letter. Or it might be because this letter was added later and the software you are using doesn’t support it yet. Which software and operating system are you using?

**Comment by nik9hil** [comment]
I had installed it in Windows 10 and tried using it in Microsoft Office 2016 and also in Ubuntu with LibreOffice. It didn't work in either of them i.e. it didn't type in Takri script. It always switched to English fonts. For the Takri keyboard, I don't have it. Since I had installed it in my system, I was able to see it in the browser. All of the issues opened by me uses letters from Aksharamukha, which is an online script converter app. The website claimed to be using the .otf mentioned in the issue. It also claimed that the archaic character 'kha' is not "widely available". 
It would be helpful if you can tell me how I can make it work in my system.

**Comment by punchcutter** [comment]
Ok, I see. I don't see any way Aksharamukha can show this letter right now. I think you should open an issue at https://github.com/virtualvinodh/aksharamukha/issues to ask Vinodh to add support for this character. He can also update the font to use the latest version.

**Comment by nizarsq** [comment]
I was able to see the character U+116B8 in Version 2.002. Please download the font from [Here](https://cdn.jsdelivr.net/gh/googlefonts/noto-fonts@master/phaseIII_only/unhinted/otf/NotoSansTakri/NotoSansTakri-Regular.otf). you can use this test case to verify. Closing this bug for now.
<img width="1074" alt="Screen Shot 2020-05-23 at 2 36 19 AM" src="https://user-images.githubusercontent.com/22158882/82727255-38cdd200-9c9e-11ea-8751-03e01b24ecc5.png">

 
<img width="499" alt="Screen Shot 2020-05-23 at 2 28 09 AM" src="https://user-images.githubusercontent.com/22158882/82727155-96155380-9c9d-11ea-9dc8-2b337265a3d3.png">
