### ISSUE TITLE
Overlapping Zanabazar Square cluster-final letters

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1744]
### Font
NotoSansZanabazarSquare-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/7a9a8dbf7c9193298a1b11ad2e9acf5e039fc530/phaseIII_only/unhinted/otf/NotoSansZanabazarSquare/NotoSansZanabazarSquare-Regular.otf
Date: 2020-05-11

### Font version
Version 2.001

### Issue
Cluster-final letters overlap each other.

### Character data
𑨍𑨻𑨾
U+11A0D ZANABAZAR SQUARE LETTER GA
U+11A3B ZANABAZAR SQUARE CLUSTER-FINAL LETTER YA
U+11A3E ZANABAZAR SQUARE CLUSTER-FINAL LETTER VA

### Screenshot
![𑨍𑨻𑨾
](https://user-images.githubusercontent.com/1124347/81611321-daa11500-93a8-11ea-9d25-b677dd1bb097.png)

**Comment by punchcutter** [comment]
Fixed missing anchors.
<img width="56" alt="1744fix" src="https://user-images.githubusercontent.com/11257204/82762221-a4a25e80-9db4-11ea-88a9-1a9c8afdae88.png">
