### ISSUE TITLE
U+116B6 TAKRI SIGN VIRAMA with U+116A4 TAKRI LETTER RA and U+116A3 TAKRI LETTER YA, overlaps with other vowel signs of the script.

### ISSUE THREAD

**Issue by nik9hil** [googlefonts/noto-fonts#1751]
### Font 
 NotoSansTakri-Regular.otf
  
### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/115d38430d957d38307457c036302b7bdbe0bbc4/phaseIII_only/unhinted/otf/NotoSansTakri/NotoSansTakri-Regular.otf
 
Date: 2020-05-15

### Font Version
 Version 2.001

### Issue
U+116B6 TAKRI SIGN VIRAMA with U+116A4 TAKRI LETTER RA and U+116A3 TAKRI LETTER YA, overlaps with other vowel signs of the script. The vowel signs should be relatively below the cobination of VIRAMA with RA or YA 

### Character data
Image 1
U+116A2 TAKRI LETTER MA   𑚢
U+116A3 TAKRI LETTER YA  𑚣 
U+116B6 TAKRI SIGN VIRAMA    𑚶
U+116B0 TAKRI VOWEL SIGN U    𑚰 

Image 2
U+1168A TAKRI LETTER KA   𑚊
U+116A4 TAKRI LETTER RA 𑚤 
U+116B6 TAKRI SIGN VIRAMA    𑚶
U+116B1 TAKRI VOWEL SIGN UU    𑚰𑚱 
 
### Screenshot
![image](https://user-images.githubusercontent.com/32241740/82054373-7b127480-96dc-11ea-80d4-ef09d2128a36.png)
![image](https://user-images.githubusercontent.com/32241740/82054584-ca58a500-96dc-11ea-9fa0-cc2670459a10.png)

**Comment by punchcutter** [comment]
Fixed in https://github.com/googlefonts/noto-source/pull/202
<img width="176" alt="1751fix" src="https://user-images.githubusercontent.com/11257204/82133668-b0ce6080-97a3-11ea-9635-e2a1addfd786.png">

**Comment by marekjez86** [comment]
fixed fonts in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansTakri and https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansTakri
