### ISSUE TITLE
Brahmi with vedic accents results in tofus.

### ISSUE THREAD

**Issue by vvasuki** [googlefonts/noto-fonts#1754]
### Font 
NotoSansBrahmi-Regular from [hinted directory of this repo](https://github.com/googlefonts/noto-fonts/tree/master/hinted) as of this date.

### OS name and Application
Chrome (Version 81.0.4044.92 (Official Build) (64-bit) on Arch Linux)

### Issue

Open https://vvasuki.github.io/saMskAra/mantraH/indraH/Rk/apratiratham/?&transliteration_target=brahmi on Chrome version described above vs firefox.

You get bad rendering (Tofus) as shown below:

![image](https://user-images.githubusercontent.com/2664797/82746402-e5967500-9dac-11ea-9a9f-35bbc60de5d8.png)

### Additional info
- Please note that the problem does not appear on Firefox
- Further, note that analogous problems existed on some older versions of NotoSansKannada-Regular, NotoSansTelugu-Regular, NotoSansMalayalam-Regular, NotoSansTamil-Regular etc.., but were solved when the latest fonts from this repository were used. Also see https://github.com/googlefonts/noto-fonts/issues/1752
- Please see https://github.com/sanskrit-coders/sanskrit-documentation-theme-hugo/issues/7 for related discussion.

**Comment by nizarsq** [comment]
Please include the font details like font source directory, ttf/otf hitnted/unhinted. Thank you.

**Comment by simoncozens** [comment]
Duplicated in #2256.
