### ISSUE TITLE
Modi with vedic accents results in tofus.

### ISSUE THREAD

**Issue by vvasuki** [googlefonts/noto-fonts#1755]
### Font 
NotoSansModi-Regular from this repo as of this date.

### OS name and Application
Chrome (Version 81.0.4044.92 (Official Build) (64-bit) on Arch Linux)

### Issue

Open https://vvasuki.github.io/saMskAra/mantraH/indraH/Rk/apratiratham/?&transliteration_target=modi on Chrome version described above vs firefox.

You get bad rendering (Tofus) as shown below:

![image](https://user-images.githubusercontent.com/2664797/82746570-f5af5400-9dae-11ea-8593-7093efc931ef.png)

### Additional info
- Please note that the problem does not appear on Firefox
- Further, note that analogous problems existed on some older versions of NotoSansKannada-Regular, NotoSansTelugu-Regular, NotoSansMalayalam-Regular, NotoSansTamil-Regular etc.., but were solved when the latest fonts from this repository were used. Also see https://github.com/googlefonts/noto-fonts/issues/1752
- Please see https://github.com/sanskrit-coders/sanskrit-documentation-theme-hugo/issues/7 for related discussion.

**Comment by nizarsq** [comment]
Issue reported is reproducible .
<img width="1430" alt="Screen Shot 2020-05-27 at 11 52 15 PM" src="https://user-images.githubusercontent.com/22158882/83108913-553e8580-a075-11ea-90f3-275b992f0404.png">
