### ISSUE TITLE
Two pairs of Nushu characters got their cmap mistakenly swapped

### ISSUE THREAD

**Issue by lianghai** [googlefonts/noto-fonts#1762]
### Title 

Two pairs of Nushu characters got their cmap mistakenly swapped

### Font 

NotoSansNushu-Regular.otf

### Where the font came from, and when

Site: https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansNushu/NotoSansNushu-Regular.otf
Date: 2020-06-02

### Font Version

1.001

### OS name and version

macOS Catalina 10.15.5 (19F96) —However, the font was tested in a HarfBuzz environment. See the next section.

### Application name and version

[FontGoggles 1.1.15](https://github.com/justvanrossum/fontgoggles/releases/tag/v1.1.15)

### Issue

Two pairs of characters—

- U+1B22A and U+1B23B
- U+1B24B and U+1B268

— got their cmap (character-to-glyph mapping) swapped due to a misunderstanding of the recent document [L2/20-075](https://www.unicode.org/L2/L2020/20075-nushu-prop-upd.pdf), _Updates for 8 values for 4 Nushu characters in UCD_, of which the proposal has been [accepted by the UTC](https://www.unicode.org/L2/L2020/20102.htm#163-A58). The L2/20-075 proposed for changes of character property values (phonetic information, in this case), **not** glyphs or identities of the four characters.

  1. Steps to reproduce: Shape the sample string (provided in the section “Character data”) with the font.
  2. Observed results: The two pairs of characters are rendered with swapped glyphs. See the section “Screenshot”.
  3. Expected results: Glyphs consistent with the code chart, as respected by [an earlier version (1.000) of the font](https://github.com/googlefonts/noto-fonts/blob/da636d8d8c6654fe3199aba049a1a278859a892b/phaseIII_only/unhinted/otf/NotoSansNushu/NotoSansNushu-Regular.otf). See the section “Screenshot”.

I have personally communicated with the designer @LisaHuang2017 about this regression.

The following are portions of the current code chart, which is not affected by the proposal of L2/20-075.

<img width="205" alt="Screen Shot 2020-06-02 at 09 28 06" src="https://user-images.githubusercontent.com/343259/83469943-88d54180-a4b3-11ea-87f4-085e40733c7c.png">

<img width="300" alt="Screen Shot 2020-06-02 at 09 28 52" src="https://user-images.githubusercontent.com/343259/83469956-8a9f0500-a4b3-11ea-96c4-e41bed3dab79.png">

### Character data

𛈪𛈻 𛉋𛉨

See the section “Screenshot” for code points and character names.

### Screenshot

- The highlighted first line shows the current version (1.001) that is affected by this regression.
- The second line shows a previous version (1.000) that works fine.
- The third line shows an additional Nushu font somehow [available in the repo (commit 39b236c)](https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoTraditionalNushu/NotoTraditionalNushu-Regular.otf), just to confirm it’s not affected by the regression.

<img width="770" alt="Screen Shot 2020-06-02 at 08 53 41" src="https://user-images.githubusercontent.com/343259/83468877-ab199000-a4b0-11ea-9229-d446ca57183a.png">

**Comment by LisaHuang2017** [comment]
This issue has been fixed on the last two commits made on June 9th, 2020. 
viewable [here](https://github.com/LisaHuang2017/noto-sans-nushu/commits/master)
The .glyphs and .ttf files have been changed back to version 1.000 with the correct Unicode values. Thanks @lianghai for this!

**Comment by marekjez86** [comment]
@lianghai : 谢谢你🙏！ This should be fixed with today's version of  https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansNushu/NotoSansNushu-Regular.otf
