### ISSUE TITLE
Noto Serif Devanagari improperly formatted matra with za+u ( ज़ + ु )

### ISSUE THREAD

**Issue by nik-suri** [googlefonts/noto-fonts#1766]
### Font 
NotoSerifDevanagari-Regular.ttf
NotoSerifDevanagari-Bold.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifDevanagari-unhinted.zip
Date: 2017-09-20

### Font Version
1.01

### OS name and version
macOS Catalina 10.15.4

### Application name and version
Microsoft Word for Mac 16.16.22

### Issue
Devanagari characters za + vowel sign u (U+095B + U+0941) appear as below in font Noto Serif Devanagari. The order of characters is za (U+095B) and za + u (U+095B + U+0941) shown first in regular and then in italicized. Notice how the vowel sign conflicts with the dot, which causes the dot to be barely visible:
![Screen Shot 2020-06-16 at 1 45 12 PM](https://user-images.githubusercontent.com/21992945/84826348-adfba100-afd7-11ea-8a70-63f51323ad68.png)
Compare to the same characters when printed in the Noto Sans Devanagari font:
![Screen Shot 2020-06-16 at 1 48 41 PM](https://user-images.githubusercontent.com/21992945/84826662-1ea2bd80-afd8-11ea-9226-576b57b96c5b.png)
The placement of the dot in Noto Serif Devanagari should be updated to be similar to that of the dot in Noto Sans Devanagari.

**Comment by nizarsq** [comment]
@nik-suri can you test if this issue reproducible on the latest NotoSerifDevanagari (Version 2.001), can be found here https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSerifDevanagari. Let me know if this issue still reproducible on this font. (Please uninstall the older version to make sure you are using the latest font).

**Comment by nik-suri** [comment]
Thank you! The issue seems to have been fixed with NotoSerifDevanagari-Regular.ttf. The screenshots below display what it looks like on my computer (normal and italicized):
![font](https://user-images.githubusercontent.com/21992945/85190343-54f86b00-b26c-11ea-9ce1-3dad2c9c6f68.png)

**Comment by nizarsq** [comment]
Amazing! Thank you.
