### ISSUE TITLE
Font files for variable NotoSansDevanagari, NotoSansMyanmar, and NotoSerifMyanmar are empty

### ISSUE THREAD

**Issue by iwsfutcmd** [googlefonts/noto-fonts#1767]
### Font 
* `phaseIII_only/unhinted/variable-ttf/NotoSansDevanagari-VF.ttf`
* `phaseIII_only/unhinted/variable-ttf/NotoSansDevanagariUI-VF.ttf`
* `phaseIII_only/unhinted/variable-ttf/NotoSansMyanmar-VF.ttf`
* `phaseIII_only/unhinted/variable-ttf/NotoSansMyanmarUI-VF.ttf`
* `phaseIII_only/unhinted/variable-ttf/NotoSerifMyanmar-VF.ttf`

### Where the font came from, and when
`noto-fonts` git repo, master branch, 2020-06-16

### Font Version
n/a (file contents are missing)

### OS name and version
n/a

### Application name and version
n/a

### Issue
Contents of Noto Sans Devanagari, Noto Sans Myanmar, and Noto Serif Myanmar variable font files are missing (0 bytes). I imagine it's related to the general variable font build problems listed in the `noto-source` repository issues.

### Character data
n/a

### Screenshot
n/a

**Comment by marekjez86** [comment]
my bad... I pushed results of failed builds. Removed
