### ISSUE TITLE
'GUJARATI DIGIT SIX' (U+0AEC) Noto Sans and Serif Gujarati need a more common shape

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#1768]
Here are the shapes of 'GUJARATI DIGIT SIX' (U+0AEC) in some of the fonts
<img width="851" alt="Screen Shot 2020-04-08 at 7 28 46 PM (1)" src="https://user-images.githubusercontent.com/13322623/85087845-73d6fe80-b193-11ea-988a-8e5ddf082a48.png">

During the Beureau of Indian Standard meeting it was raised that the shape (half/incomplete bottom hook) of 'GUJARATI DIGIT SIX' (U+0AEC) in Noto Gujarati fonts is not acceptable. It needs to be a full hook (less popular) or a full hook alternative (first top three in the table above; much more popular).

Our design of GUJARATI DIGIT SIX' (U+0AEC) ought to conform to the more common shape

**Comment by marekjez86** [comment]
Serif Masters: Light, Regular, Semi-Bold, Bold
Sans Masters: Light, Regular, Semi-Bold, Bold, Light Condensed, Condensed, Bold Condensed

**Comment by nizarsq** [comment]
<img width="730" alt="Screen Shot 2020-08-18 at 2 14 34 PM" src="https://user-images.githubusercontent.com/22158882/90566337-265c1b00-e15d-11ea-8eb9-0b1b18cf3cf2.png">

**Comment by nizarsq** [comment]
<img width="1257" alt="Screen Shot 2020-10-24 at 1 40 24 PM" src="https://user-images.githubusercontent.com/22158882/97093155-798b9780-15fe-11eb-9d18-3442ce30c489.png">

**Comment by nizarsq** [comment]
This issue fixed.
