### ISSUE TITLE
add Unicode Character 'INDIAN RUPEE SIGN' (U+20B9) to NotoSansOlChiki.glyphs

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#1769]
add Unicode Character 'INDIAN RUPEE SIGN' (U+20B9) to NotoSansOlChiki.glyphs

**Comment by marekjez86** [comment]
Masters: Regular, Medium, Semi-Bold, Bold

**Comment by nizarsq** [comment]
Unicode added. Closing this bug.
