### ISSUE TITLE
The unicode character “ڨ” Arabic Letter Qaf with Three Dots Above (U+06A8) is always displayed in isolated form when using Noto Sans Arabic or Noto Kufi Arabic

### ISSUE THREAD

**Issue by The-neophyte** [googlefonts/noto-fonts#1775]
### Font 
Noto Sans Arabic and Noto Kufi Arabic

### Where the font came from, and when
Came preinstalled in Manjaro Linux. 

### Font Version
2.0

### OS name and version
Manjaro Linux

### Issue
The unicode character “ڨ” Arabic Letter Qaf with Three Dots Above (U+06A8) is always displayed in isolated form when using Noto Sans Arabic or Noto Kufi Arabic. This is not the case when using Noto Sans Arabic UI, Noto Naskh Arabic, Noto Naskh Arabic UI or other, non-Noto Arabic fonts. While this letter is not used in modern standard Arabic, it is heavily used in various Arabic dialects and possibly other languages that use the Arabic script.

  1. Steps to reproduce
Render sample text containing the letter “ڨ” with Noto Sans Arabic or Noto Kufi Arabic.

  2. Observed results
The letter is displayed in isolated form.

  3. Expected results
The letter is connected with the surrounding letters.

### Character data
The character is “ڨ” (U+06A8).
Here's a text sample to test whether it is connected. “الڨار”

### Screenshot
![Screenshot comparing how the sample text displays in the various Noto Arabic fonts](https://user-images.githubusercontent.com/40165967/85344854-bd538080-b4e8-11ea-83e5-34c992d95060.png)

**Comment by nizarsq** [comment]
I can reproducible this issue on NotoKufiArabic but NotoSansArabic. I believe this issue resolved in the current NotoSansArabic.
I used NotoSansArabic from this directory https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf
<img width="1102" alt="Screen Shot 2020-06-29 at 11 06 12 PM" src="https://user-images.githubusercontent.com/22158882/86089472-22fdba80-ba5d-11ea-8737-6280dcbbc8e5.png">

**Comment by The-neophyte** [comment]
I can confirm this  issue does not exist on the version you linked of Noto Sans Arabic.
Have a good day!

**Comment by nizarsq** [comment]
Apparently U+06A8 initial and medial form/data missing from NotoKufiArabic. U+06A8 used in Tunisian, Algerian, Central Kurdish, Comoro, Wakhi and some other Arabic regions.

**Comment by nizarsq** [comment]
https://github.com/googlefonts/noto-fonts/issues/1177

**Comment by nizarsq** [comment]
This issue fixed. Thank you for filing the issue @The-neophyte 
<img width="635" alt="Screen Shot 2020-10-22 at 11 29 06 PM" src="https://user-images.githubusercontent.com/22158882/96964028-90c36b80-14be-11eb-9af8-ad9af0a4788f.png">

**Comment by nizarsq** [comment]
Fix will be applied to Noto Kufi Arabic.
