### ISSUE TITLE
Old Hungarian Font can made several spelling problems with automated ligatures.

### ISSUE THREAD

**Issue by Kixidevel** [googlefonts/noto-fonts#1776]
## Defect Report
Using automated ligatures can made spelling problems .
### Font 
 Full name 'NotoSansOldHungarian-Regular.ttf'.

### Where the font came from, and when
 https://github.com/googlefonts/noto-fonts/blob/0fa1dfabd6e3746bb7463399e2813f60d3f1b256/hinted/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf
September 26. 2019

**Comment by Kixidevel** [comment]
@marekjez86 
The automated ligatures could made spelling problems.
For examples: text "evvel" ("with this") translate as "ewel" (has no meaning in Hungarian language)
"keksz" ("biscuit") translate "kex" (has no meaning in Hungarian language)
But "szex" ("sex") translate correctly.
Ligature automation works hesitated, so, in my opinion, must be remove this capability
Using ZWJ macro more useful.

**Comment by Kixidevel** [comment]
@marekjez86 
I working on it.

**Comment by Kixidevel** [comment]
The visual explaining:
[exclaim_dlig.pdf](https://github.com/googlefonts/noto-fonts/files/4844605/exclaim_dlig.pdf)

**Comment by dscorbett** [comment]
Why is this a problem? 'dlig' means discretionary ligatures: they are not formed by default. If you don’t like them, don’t enable 'dlig'.

**Comment by Kixidevel** [comment]
@dscorbett 
Listen!
The problem isn't the "dlig" abstract definition. The problem is that, how and what it is defined inside the Old Hungarian font. "x" letter doesn't a part of basic UNICODE standard, so You, or another developer defined "x" as ligature, that's all right. It work without ZWJ macro in "dlig" ligatures, with ZWJ macro in "liga" ligatures. 
If I want to type "x" ligature I must to type with an Old Hungarian keyboard layout Old Hungarian "ek" and "esz", with "dlig" definition. When I want type szex word (in English spelling "sex"), the ligature work right, but when I want to type Hungarian  word "keksz", because of the "dlig" definition, it transformed "k-sz" sequence to ligature "x", and the user, who want to type correct spelling word "keksz", need to switch out "dlig" capabilities in a dialog box, and then type word "keksz". The problem is not only in this case. I don't know examine the full spelling system of Hungarian language in a message. Hungarian language the most difficult language in Europe.
Consequence: 1. the users must to switch on and off "dlig" capability, when type with Old Hungarian script. Once try it will hate it.
If You tell me, that Old Hungarian keyboard layout doesn't exist, I can send You links on the web, where can download keyboard layout installers for Windows. The Linux distros already have Old Hungarian layout between the extras.
2. Much more easier plan and compile Old Hungarian layout with ZWJ-key for Windows. I will it to do, I promise.
Xkeyboard-config version 2.29 already specify additional layout for ligatures.
We, with an another developer would like build in Old Hungarian Noto-font into an Office package, and we don't like, if we would be named "stupids", and we don't like the Hungarian users drop into the "dlig" capability problems (You don't know, how Hungarians think)
That's enough?

**Comment by Kixidevel** [comment]
On wednesday I will send another examples.

**Comment by Kixidevel** [comment]
@dscorbett @marekjez86 @google-admin 
See the following testcase:
![testcase_dlig](https://user-images.githubusercontent.com/32356899/86220888-80405b80-bb84-11ea-89d0-7a02c9b25150.jpg)
Old Hungarian spelling follow Hungarian spelling.
As You see, with using direct ligatures defined in "dlig",  We HAVE NOT CHOICE between CORRECT SPELLING and INCORRECT SPELLING.
I don't tell now, that using ligatures is a wrong thing, but when it automatised, makes spelling check errors, that's the wrong thing.
'liga' settings with ZWJ macros are enough.

Please pull my request.

@dscorbett 
If you really think, that ligatures are useful, please make the capital ligatures, specifying without direct automated ligatures. Specify only 'liga' with ZWJ macros.
There is one thing, that I would ask for you: please forget theme Old Hungarian script with acute, above dots and that kind of symbols.
Old Hungarian script is a Historic script. Version with acute and the others are imagined by a small group in the 21th country, after standardisation.
Thanks:
Kixidevel

**Comment by Kixidevel** [comment]
@marekjez86 
When will be my pull request done?
I prepared a small misstake, too. Ligature "ba" had wrong form, it looked like "szb". I resolved with mirrored ligature "ab".

**Comment by Kixidevel** [comment]
@dscorbett 
Are the given cases about spelling problems enought for you?

**Comment by dscorbett** [comment]
Let me see if I’ve understood your point: the k+v ligature (for example) is sometimes appropriate and sometimes inappropriate, depending on the word, and Old Hungarian ligatures should only ever be formed explicitly with ZWJ, not as discretionary ligatures.

**Comment by Kixidevel** [comment]
@marekjez86 
I already prepared source code removing dlig tags. Ligature "ab" form is  not resolved yet. 
May I ask You to test and merge the pull reqest.

**Comment by Kixidevel** [comment]
@dscorbett 
You're right.
Using discrete ligatures, the critical ligatures could be preared with keyboard layout which have ZWNJ key. I will add this key to the xkeyboard-config's layout named "Old Hungarian ( for ligatures)"

**Comment by Kixidevel** [comment]
@dscorbett @marekjez86 
I close this issue.

**Comment by Kixidevel** [comment]
@dscorbett @marekjez86 @google-admin 
I reopen this Issue, because ligatures "X", "Q" "W" might be useful, but not in discrete version, the other ligatures might be useful in discrete version, too. Just only "X" "Q" and "W" ligatures make spelling problems, the others don't do spelling problems. So only "X" "Q" and "W" ligatures must be remove from discrete ligatures. I can do that.

**Comment by Kixidevel** [comment]
@dscorbett 
I think, this compromise is acceptable.

**Comment by Kixidevel** [comment]
@dscorbett @marekjez86 @google-admin 
I close it, because it resolved, already.
