### ISSUE TITLE
Noto Sans Nushu vs Noto Traditional Nushu

### ISSUE THREAD

**Issue by stone-zeng** [googlefonts/noto-fonts#1784]
I have noticed that there are two Nüshu fonts recently updated in these project: Noto Sans Nushu and Noto Traditional Nushu. But actually they looks very similar. So what's the difference of them? Are they for different style (sans/serif, I think it's not the case), or for different usage (print/UI)?

**Comment by marekjez86** [comment]
These two fonts were developed independently. Both were contributed to Noto. 
If you look at https://github.com/notofonts/NotoTraditionalNushu/tree/master/fonts/ttf/unhinted/instance_ttf Traditional comes in three weights (Light, Regular, Bold) whereas Sans just in Regular. Traditional is still work in progress (in terms of file naming, not in contents) so I haven't published it widely yet.
