### ISSUE TITLE
Noto Nastaliq Urdu: Incorrect anchor placement in SeenMed.SWinDoutT2

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/noto-fonts#1786]
### Font 

Name: Noto Nastaliq Urdu
Version: Version 2.000
Glyph count: 1138

### Issue

Anchor placement in SeenMed.SWinDoutT2 leads to incorrect shaping:

```
$ shape NotoNastaliqUrdu-Regular.ttf -u '6be 633 633 633'
[SeenFin=3+1040|SeenMed.SWinDoutT2=2@0,455+182|SeenMed.inT2outD1=1@0,461+897|sp0=0+0|HehDoIni.outT2=0@0,713+557]
```
![shape](https://user-images.githubusercontent.com/106728/87218826-373f9280-c34e-11ea-962b-d740aa9f0599.png)

It's not entirely clear where the correct placement for that anchor is; in fact, I'm not sure the thicknesses actually match anywhere, which makes me suspect that the problem might be with the connected shaping rules.

**Comment by nizarsq** [comment]
https://github.com/googlefonts/noto-fonts/issues/1773 is related to this issue, it has some shaping issues when multiple U+0633 (س) or U+0634(ش) come together.
I noticed this issue reproducible when there is 3x U+0633 (س) or more (same thing apply to U+0634(ش)). I'm wondering if Urdu has real words that has 3x U+0633 (س) in a row. I'm confident Arabic don't have that but not sure about Urdu. @simoncozens could you provide some examples where this issue appear?

<img width="845" alt="Screen Shot 2020-09-07 at 6 44 47 PM" src="https://user-images.githubusercontent.com/22158882/92424823-36529380-f13a-11ea-9d55-741e746f84e4.png">
