### ISSUE TITLE
What Versions of Unicode Are Completely Covered By Noto?

### ISSUE THREAD

**Issue by aaabbbcccddd00001111** [googlefonts/noto-fonts#1792]
What versions of Unicode are completely covered by Noto?

I need to cover Unicode with fonts in an app. For the app to be useful, the Unicode versions that are completely covered cannot be too outdated.

**Comment by marekjez86** [comment]
I think up to Unicode 9 most but many up to Unicode 12. We DO NOT COVER Unicode completely. For example, we do not and we will not cover

- A set of 285 Hentaigana characters used in Japan (historic variants of Hiragana characters)
- CJK Extension F (7,473 Han characters)
which appeared in Unicode 10. There are some other examples.
