### ISSUE TITLE
Bottom and top half brackets (U+2E22 … U+2E25) are swapped in Noto Sans Mono

### ISSUE THREAD

**Issue by jcrippen** [googlefonts/noto-fonts#1794]
### Title 
Bottom and top half brackets (U+2E22 … U+2E25) are swapped in Noto Sans Mono

### Font 
NotoSansMono-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/tree/master/hinted/NotoSansMono

Date: 2020-07-23

### Font Version
Version 2.002; ttfautohint (v1.8.2)

### OS name and version
macOS Mojave 10.14.6 (18G3020)

### Application name and version
Verified in iTerm2, Emacs, TeXShop, PopChar, and FontBook.

### Issue
The top half and bottom half brackets are swapped. The characters ⸢ U+2E22 Top Left Half Bracket and ⸣ U+2E23 Top Right Half Bracket have their 90° angles at the baseline. The characters ⸤ U+2E24 Bottom Left Half Bracket and ⸥ U+2E25 Bottom Right Half Bracket have their 90° angles above the cap height. Both pairs should be vertically flipped.

### Character data
* ⸢ U+2E22 Top Left Half Bracket
* ⸣ U+2E23 Top Right Half Bracket
* ⸤ U+2E24 Bottom Left Half Bracket
* ⸥ U+2E25 Bottom Right Half Bracket

### Screenshot
Image of Noto Sans Mono (Version 2.002) using PopChar:
<img width="371" alt="Screen Shot 2020-07-24 at 11 03 50" src="https://user-images.githubusercontent.com/4962948/88421930-3ff88580-cd9e-11ea-83f5-0bae3cebd500.png">

Image of Times New Roman (Version 7.00;O365) using PopChar:
<img width="371" alt="Screen Shot 2020-07-24 at 11 10 07" src="https://user-images.githubusercontent.com/4962948/88421938-4424a300-cd9e-11ea-9e95-b21a531030a5.png">

**Comment by marekjez86** [comment]
@jcrippen : please check https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoMono or https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoMono or https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/variable-ttf/NotoMono-VF.ttf

**Comment by jcrippen** [comment]
Checked the fonts at https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoMono and all appear to have the correct glyphs.

I note that this set of fonts is named “Noto Mono” rather than “Noto Sans Mono”. Should I expect to use this new name instead?

**Comment by marekjez86** [comment]
@jcrippen : Thank you and yes, please from now on please use “Noto Mono”
