### ISSUE TITLE
Need U+A7B9 'LATIN SMALL LETTER U WITH STROKE' and U+A7B8 'LATIN CAPITAL LETTER U WITH STROKE'

### ISSUE THREAD

**Issue by KazunariTsuboi** [googlefonts/noto-fonts#1796]
Unicode 11.0 newly defined U+A7B8 and U+A7B9 to support Mazahua. 
We would like to have these two new characters in Noto fonts.

![img2](https://user-images.githubusercontent.com/21096794/88865111-e2eb4c80-d241-11ea-8438-eb988c691141.png)

**Comment by marekjez86** [comment]
Please look at https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf directory
NotoMono
NotoSans
NotoSansDisplay
NotoSerif
NotoSerifDisplay
and corresponding -Italic fonts
all support U+A7B8 and U+A7B9 for Mazahua.

**Comment by KazunariTsuboi** [comment]
Really sorry. I could not confirm the latest repository. 
I am happy that the characters have been added. Thank you for all your work.

**Comment by marekjez86** [comment]
@KazunariTsuboi : no reason to be sorry. thank you for all the issues you brought up to our attention.
