### ISSUE TITLE
U+FF3E (fullwidth circumflex) and U+FF40 (fullwidth grave) are too high in vertical text

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#182]
```
They are too close to the character before them.

Compare the screenshots, between SimSun and Noto Sans CJK SC.
```

Original issue reported on code.google.com by `roozbeh@google.com` on 24 Oct 2014 at 2:06

Attachments:
- [noto.png](https://storage.googleapis.com/google-code-attachments/noto/issue-182/comment-0/noto.png)
- [simsun.png](https://storage.googleapis.com/google-code-attachments/noto/issue-182/comment-0/simsun.png)

**Comment by behdad** [comment]
cc @roozbehp @xiangyexiao
