### ISSUE TITLE
Negative side bearings on U+2E0E EDITORIAL CORONIS

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1821]
### Font
NotoMono-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/bf20559450ec75aec7a646b208343540a4496262/phaseIII_only/unhinted/otf/NotoMono/NotoMono-Regular.otf
Date: 2020-08-01

### Font version
Version 2.004

### Issue
U+2E0E EDITORIAL CORONIS has negative side bearings.

### Character data
«⸎»
U+00AB LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
U+2E0E EDITORIAL CORONIS
U+00BB RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK

### Screenshot
![«⸎»](https://user-images.githubusercontent.com/1124347/90671906-58d04b80-e223-11ea-9937-3e2654c1be10.png)

**Comment by nizarsq** [comment]
<img width="669" alt="Screen Shot 2020-08-20 at 1 44 52 PM" src="https://user-images.githubusercontent.com/22158882/90823819-5507fc00-e2eb-11ea-8bf5-fee13eef0e9a.png">

**Comment by nizarsq** [comment]
This issue fixed. Thank you

**Comment by marekjez86** [comment]
@nizarsq : what's the new width of U+2E0E EDITORIAL CORONIS? I'm asking because  U+2E0E EDITORIAL CORONIS might need to occupy fixed width (but maybe my question doesn't make sense :-))

**Comment by nizarsq** [comment]
> @nizarsq : what's the new width of U+2E0E EDITORIAL CORONIS? I'm asking because U+2E0E EDITORIAL CORONIS might need to occupy fixed width (but maybe my question doesn't make sense :-))

I changed the side bearings to 15, previously they were something in range of -200 (I don't remember the exact number). Spacing was way less what Mono spacing is. Currently U+2E0E look like the screenshot attached (Before and After). Let me know if you want me do any changes

<img width="804" alt="Screen Shot 2020-10-25 at 9 08 42 PM" src="https://user-images.githubusercontent.com/22158882/97133167-45030300-1706-11eb-9e7b-84c672a1c6e8.png">

**Comment by marekjez86** [comment]
No changes are needed at this point.
Thanks
Published

**Comment by nizarsq** [comment]
Sounds good. Closing this bug for now.
