### ISSUE TITLE
Will you make Noto Sans CJK fixed width?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#184]
```
Thanks for making beautiful CJK fonts,
but I want use this font full fixed width version.

Korean glyphs are not square, maybe 90% horizontal.
so I can't use this in text editor.

Noto Sans's Alphabet glyphs are not fixed too,
I wish these glyphs to half width fixed size like Droid Sans Mono.

```

Original issue reported on code.google.com by `basic2...@gmail.com` on 27 Oct 2014 at 5:39
- Merged into: #136

**Comment by Dorian** [comment]
I want to consistently use Google Noto everywhere as my go to font and it's too bad there is no fixed width version of it, I can't use it as my terminal font. Maybe Roboto is the actual universal font.
