### ISSUE TITLE
Bad serif on italic U+A655 CYRILLIC SMALL LETTER REVERSED YU

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1845]
### Font
NotoSerif-Italic.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/bf20559450ec75aec7a646b208343540a4496262/phaseIII_only/hinted/ttf/NotoSerif/NotoSerif-Italic.ttf
Date: 2020-08-01

### Font version
Version 2.003; ttfautohint (v1.8.2)

### Issue
U+A655 CYRILLIC SMALL LETTER REVERSED YU does not match how this font does serifs. There should be no top right serif, for consistency with letters like U+043D CYRILLIC SMALL LETTER EN.

### Character data
ꙕн
U+A655 CYRILLIC SMALL LETTER REVERSED YU
U+043D CYRILLIC SMALL LETTER EN

### Screenshot
![ꙕн](https://user-images.githubusercontent.com/1124347/92533112-c60e4580-f1ff-11ea-9856-60832fd72a97.png)

**Comment by nizarsq** [comment]
<img width="1090" alt="Screen Shot 2020-09-12 at 6 32 42 PM" src="https://user-images.githubusercontent.com/22158882/93008149-59a88480-f526-11ea-929c-2fca03a2df6a.png">
