### ISSUE TITLE
Mongolian medial DA glyphs unexpectedly swapped in some simple contexts

### ISSUE THREAD

**Issue by r12a** [googlefonts/noto-fonts#1848]
#1726 # Font 
  > NotoSansMongolian-Regular.ttf

### Where the font came from, and when
  >   Site: https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSansMongolian

### Font Version
  > Mac - Version 1.04 uh

### OS name and version
  > macOS Mojave 10.14.6

### Application name and version
  > Firefox, Chrome.

### Issue
  > The table shows medial forms of DA in various fonts, with the Noto font highlighted in orange (ignore the 'isolate' row). The shapes are produced using ZWJ and FVS1, but no other contextual influences.  The glyphs shown in orange are the reverse of those shown for other fonts.  

![Screenshot 2020-09-10 at 10 44 07](https://user-images.githubusercontent.com/4839211/92714896-b0f6fb00-f354-11ea-9bfa-d40ea21f60d6.png)

I'm really not clear what's going on here.  You get different results if normal characters are used, rather than ZWJ, to create the medial form. So maybe it's something to do with the rules in the font for interaction with ZWJ (?) 

### Character data
[You can play with the results here](https://r12a.github.io/pickers/mongolian/?text=%E2%80%8D%E1%A0%B3%E2%80%8D%20%20%20%E2%80%8D%E1%A0%B3%E1%A0%8B%E2%80%8D%20%20%20%E1%A0%B9%E1%A0%B3%E1%A0%B9%20%E1%A0%B9%E1%A0%B3%E1%A0%8B%E1%A0%B9) Here's a screen grab for Firefox:

![Screenshot 2020-09-10 at 11 14 01](https://user-images.githubusercontent.com/4839211/92716638-fcaaa400-f356-11ea-93bd-169fde4a5799.png)

**Comment by nizarsq** [comment]
@r12a I believe you are using old version font, current NotoSansMongolian version is 2.001.  According to @marekjez86 comment in https://github.com/googlefonts/noto-fonts/issues/924#issuecomment-448545858 this issue fixed. Please use the fonts in:
https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansMongolian
or
https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansMongolian.
Please reopen the issue if you have other thoughts
