### ISSUE TITLE
Noto Naskh Arabic wrong GPOS Anchor0 for letter GHAH unicode: uni063A

### ISSUE THREAD

**Issue by Assiraj** [googlefonts/noto-fonts#1850]
### Title 
  >  Noto Naskh Arabic wrong GPOS Anchor0 for letter GHAH unicode: uni063A

### Font 
  >  NotoNaskhArabic-Regular.ttf and maybe all other series

### OS name and version
  >  all

### Application name and version
  > Assiraj application

### Issue
  > Noto Naskh Arabic wrong GPOS Anchor0 for letter GHAH unicode: uni063A, the value for marker0.y0 = 1051 but it should be 1394
Impacted glyphs:
'uni063A'
'uni063A.fina'
'uni063A.init'
'uni063A.medi'

![gha](https://user-images.githubusercontent.com/49025162/92993857-76789400-f4f5-11ea-846a-45251a62ca67.png)

**Comment by nizarsq** [comment]
@Assiraj what is the font version you are using? I believe this issue fixed some time ago. The version in this [directory](https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoNaskhArabic/NotoNaskhArabic-Regular.ttf) is ok (Version 2.000).  BTW NotoSansArabic has similar issue and we are aware of it. 

Tested script:
إِنَّمَا حَرَّمَ عَلَيْكُمُ الْمَيْتَةَ وَالدَّمَ وَلَحْمَ الْخِنزِيرِ وَمَا أُهِلَّ بِهِ لِغَيْرِ اللَّهِ فَمَنِ اضْطُرَّ غَيْرَ بَاغٍ وَلاَ عَادٍ فَلا إِثْمَ عَلَيْهِ إِنَّ اللَّهَ غَفُورٌ رَّحِيمٌ
وَإِمَّا يَنزَغَنَّكَ مِنَ الشَّيْطَانِ نَزْغٌ فَاسْتَعِذْ بِاللَّهِ ۚ إِنَّهُ سَمِيعٌ عَلِيمٌ
<img width="1432" alt="Screen Shot 2020-09-12 at 6 17 46 PM" src="https://user-images.githubusercontent.com/22158882/93007982-44325b00-f524-11ea-89b8-9ef79067d8d9.png">

**Comment by Assiraj** [comment]
I confirm that it's corrected in the version in the given directory.
I use and old version: 1.06
