### ISSUE TITLE
U+11CA9 MARCHEN SUBJOINED LETTER YA sometimes overlaps the next glyph

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1851]
### Font
NotoSansMarchen-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/9d7cfbd1c19662dee3d82d8a66f67e8b7f29dfab/phaseIII_only/hinted/ttf/NotoSansMarchen/NotoSansMarchen-Regular.ttf
Date: 2020-09-13

### Font version
Version 3.000

### Issue
The 'dist' lookup that adds width for U+11CA9 MARCHEN SUBJOINED LETTER YA only applies after glyphs for single consonants. After any other base, it has no width added and overlaps the following glyph. The 'dist' lookup need not be contextual: the glyph for U+11CA9 should never overlap the following glyph.

### Character data
U+11C7A MARCHEN LETTER TA
U+11CA9 MARCHEN SUBJOINED LETTER YA
U+11CB1 MARCHEN VOWEL SIGN I
U+11C71 MARCHEN MARK SHAD

### Screenshot
![𑱺𑲩𑲱𑱱](https://user-images.githubusercontent.com/1124347/93033363-effea800-f603-11ea-8794-165cb901ce0b.png)

**Comment by nizarsq** [comment]
Looks good to me in the latest build. Thanks
<img width="1377" alt="Screen Shot 2020-09-19 at 5 24 10 PM" src="https://user-images.githubusercontent.com/22158882/93691652-f0cc8980-fa9c-11ea-9e06-89e66687bedd.png">
