### ISSUE TITLE
Correction in the letter ZA

### ISSUE THREAD

**Issue by RohingyaProject** [googlefonts/noto-fonts#1853]
I would like to highlight in Noto Sans Rohingya Unicode font the letter Za is not readable it could be misread with Aa. It Should be curved slightly up right as demonstrated in the pic attached. I am Forwarding this request on behalf of Rohingya Language Committee.

![Za-Correction](https://user-images.githubusercontent.com/67902548/93375462-9ef3eb80-f871-11ea-92e0-6759ae6a80a3.jpg)

**Comment by nizarsq** [comment]
@RohingyaProject  Thank you for filing this bug. Could you include where is the font came from and the characters data you used in the screenshot . Thanks

**Comment by RohingyaProject** [comment]
We have got the font from this source http://languagetools-153419.appspot.com/rhg/downloads/ 
Character Data: 10D0E; HANIFI ROHINGYA LETTER ZA; Lo;0; AL;;;;;N;;;;;
Thank you

**Comment by nizarsq** [comment]
Please use the font in this directory https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansHanifiRohingya/NotoSansHanifiRohingya-Regular.otf. The issue you are reporting is not reproducible in the official font. Thank you
<img width="1211" alt="Screen Shot 2020-09-17 at 11 31 05 AM" src="https://user-images.githubusercontent.com/22158882/93512529-47896600-f8d9-11ea-9e16-b4369cad5e98.png">

**Comment by RohingyaProject** [comment]
Thank you, I have also seen couple of other issues been discussed such as the ending of Ma and stretching the letter with dash are there any progress on those issues

**Comment by nizarsq** [comment]
@RohingyaProject please file separate bugs for remaining issues (if you didn't). Thank you.

**Comment by mdnoorna** [comment]
I guess we also need to add some of the additional punctuation marks in the font, people are facing difficulty in typing complex text with ( ) : ; _ +-  etc.. 

keyboard layout is attached you may refer some the punctuation marks 

![Rohingya-Keyboard](https://user-images.githubusercontent.com/3914922/106718053-52435e00-6622-11eb-8e20-1782dc49450d.jpg)
  
Thank you
