### ISSUE TITLE
Noto Sans Arabic fonts are somewhat broken

### ISSUE THREAD

**Issue by punchcutter** [googlefonts/noto-fonts#1854]
As mentioned in https://github.com/googlefonts/noto-fonts/issues/1559#issuecomment-696389716 the current fonts have some problems. Some of the Condensed fonts still have the problem described in https://github.com/googlefonts/noto-fonts/issues/1559. Also U+0030 has inconsistent start nodes so the interpolations are messed up.

**Comment by marekjez86** [comment]
@punchcutter : I realized that since this change instead of NotoSansArabic-Condensed.ttf I make using fontmake NotoSansArabic-CondensedRegular.ttf. Same for NotoSansArabic-SemiCondensed.ttf and NotoSansArabic-ExtraCondensed.ttf .. Is it intentional?

**Comment by punchcutter** [comment]
That seems to be a mistake in the source that apparently was fixed on March 5, but was undone on March 24. So the latest source had the mistake reintroduced.

**Comment by marekjez86** [comment]
Oh OK... I'll fix it.... Thanks

**Comment by marekjez86** [comment]
published in both https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf and https://github.com/googlefonts/noto-fonts/tree/master/unhinted
