### ISSUE TITLE
NotoSansArabic 2.02 missing glyphs

### ISSUE THREAD

**Issue by nizarsq** [googlefonts/noto-fonts#1856]
NotoSansArabic 2.02 missing some glyphs

Font source:
https://github.com/googlefonts/noto-fonts/blob/master/hinted/ttf/NotoSansArabic/NotoSansArabic
version: 2.002

Following glyphs not exist in NotoSansArabic:
U+06A8 initial medial final
U+06A7 initial medial final
U+06BA initial medial final
U+06BD initial medial final
U+069C initial medial final
U+06BA initial medial

characters data:
ڨ ڨل لڨل لڨ
ڧ ڧل لڧل لڧ
ں ںل لںل لں
ڽ ڽل لڽل لڽ
<img width="1346" alt="Screen Shot 2020-09-25 at 8 44 00 PM" src="https://user-images.githubusercontent.com/22158882/94329434-d9474200-ff6f-11ea-8084-e283994605c4.png">

**Comment by simoncozens** [comment]
All glyphs mentioned are present in Noto Sans Arabic 2.009.
