### ISSUE TITLE
Number "7" is too thin (especially in bold)

### ISSUE THREAD

**Issue by Jellby** [googlefonts/noto-fonts#1857]
### Font
NotoSerif-Bold.ttf

### Where the font came from, and when
https://github.com/googlefonts/noto-fonts/blob/master/hinted/ttf/NotoSerif/NotoSerif-Bold.ttf
2020-09-26

### Font Version
2.003

### OS name and version
Kubuntu 18.04

### Issue
The number "7" in the bold NotoSerif font (and probably others) looks too thin, almost like not bold. Even in the regular font it may be too thin. I realize that it follows the general style for oblique strokes, but surely there could be exceptions? This is especially noticeable when the 7 is next to characters with strong vertical strokes.

### Screenshot
![Screenshot_2020-09-26 Test](https://user-images.githubusercontent.com/7943459/94335543-8f487580-ffdc-11ea-92f0-cc4b179a0343.png)

**Comment by nizarsq** [comment]
I fixed this issue on italic as well.
