### ISSUE TITLE
Three dots in U+08AE ࢮ  are flipped

### ISSUE THREAD

**Issue by nizarsq** [googlefonts/noto-fonts#1859]
<b>Font tested:</b>
NotoSansArabic 2.02
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf
NotoSansArabicUI 2.02
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansArabicUI/NotoSansArabicUI-Regular.ttf

<b>Characters data:</b>
U+ 08AE 
ࢮ 

<b>Observed issue:</b>
Three Dots below in U+ 08AE ࢮ are flipped.

<b>Expected:</b>
Three Dots below should be flipped, two dots should be on the top of the one dot.

See https://unicode.org/charts/PDF/U08A0.pdf
Note: NotoNaskhArabic and NotoKufiArabic missing this letter

<b>Screenshot:</b>
<img width="1027" alt="Screen Shot 2020-09-27 at 2 59 30 PM" src="https://user-images.githubusercontent.com/22158882/94376850-0f043c00-00d2-11eb-9b4d-90cc984d2fc2.png">

**Comment by dscorbett** [comment]
This was originally fixed a few months ago for #1041. How did this regression happen? Would it be worth checking all the closed Arabic bug reports for other regressions?

**Comment by marekjez86** [comment]
@dscorbett : I rolled back the update to Noto Sans Arabic * because it introduced issues. Hence we started doing audit of Noto Sans Arabic * (and all other Arabic at the same time)

**Comment by nizarsq** [comment]
This issue fixed
