### ISSUE TITLE
Reposition SUPERSCRIPT ALEF in U+FC5B 

### ISSUE THREAD

**Issue by nizarsq** [googlefonts/noto-fonts#1862]
SUPERSCRIPT ALEF in U+FC5B is misplaced; it should be above the dot. See https://unicode.org/charts/PDF/UFB50.pdf

<b>Fonts tested: </b> 
NotoSansArabic 2.02 
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf 
NotoSansArabicUI 2.02
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansArabicUI/NotoSansArabicUI-Regular.ttf

<b>Characters data:</b> 
U+FC5B  ARABIC LIGATURE THAL WITH SUPERSCRIPT ALEF ISOLATED FORM

Note: NotoNaskhArabic and NotoNaskhArabicUI have the same issue. NotoKufiArabic, NotoNastaliqUrdu missing this letter

<b>Screenshot:</b>
<img width="1293" alt="Screen Shot 2020-09-27 at 9 23 44 PM" src="https://user-images.githubusercontent.com/22158882/94390507-bc457700-0107-11eb-8c9d-b43f427886f1.png">

**Comment by dscorbett** [comment]
This is a regression of #1032.

**Comment by nizarsq** [comment]
We still need to fix this issue in NotoNaskhArabic and NotoNaskhArabicUl

**Comment by nizarsq** [comment]
This issue fixed NotoNaskhArabic and NotoNaskhArabicUl
