### ISSUE TITLE
Inappropriate stylistic sets for Medefaidrin digits

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1865]
### Font
NotoSansMedefaidrin-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/c196acb783a756549eb531f5156527c27c39a4f9/unhinted/otf/NotoSansMedefaidrin/NotoSansMedefaidrin-Regular.otf
Date: 2020-09-28

### Font version
Version 1.000

### Issue
The Medefaidrin digits 1, 2, and 3 (U+16E81..U+16E83) have alternative forms. In Unicode, these alternative forms are encoded separately (U+16E94..U+16E96). They are not meant to be represented using the same code points as the basic forms. In Noto Sans Medefaidrin, the stylistic sets 'ss01', 'ss02', and 'ss03' substitute the basic forms with the alternative forms. These three lookups should be deleted.

### Character data
𖺁𖺂𖺃
U+16E81 MEDEFAIDRIN DIGIT ONE
U+16E82 MEDEFAIDRIN DIGIT TWO
U+16E83 MEDEFAIDRIN DIGIT THREE

### Screenshot
With all three stylistic sets enabled:
![𖺁𖺂𖺃](https://user-images.githubusercontent.com/1124347/94498269-ba42ed00-01c7-11eb-9055-82e8b5f4b78a.png)
The correct rendering:
![𖺁𖺂𖺃](https://user-images.githubusercontent.com/1124347/94498307-cfb81700-01c7-11eb-82e7-85e96d582e5c.png)

**Comment by marekjez86** [comment]
fixed in the new font release
