### ISSUE TITLE
MADDA size in NotoNastaliqUrdu is inconsistent with other diacritics and letters

### ISSUE THREAD

**Issue by nizarsq** [googlefonts/noto-fonts#1877]
In NotoNastaliqUrdu U+0653 ARABIC MADDAH ABOVE is much larger than all other diacritics, this is also true when it come on the the top of alef in U+FEF5 ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE. having this size make the MADDAH inconsistent with other diacritics and letters

<b>Issue found in: </b> 
NotoNastaliqUrdu Version 2.000
 https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoNastaliqUrdu/NotoNastaliqUrdu-Regular.ttf

<b>Characters data:</b>
آ أ اَ اّ اُ آٌ آُ لآ يآمه آما آٌ آُ ٓ ُ ْ ّ َ
<b>Screenshot:</b>
<img width="1228" alt="Screen Shot 2020-10-01 at 9 55 05 PM" src="https://user-images.githubusercontent.com/22158882/94889371-c7164980-0430-11eb-9123-e0838ede27c1.png">

**Comment by khaledhosny** [comment]
That is right shape and size of madda, the size in the other fonts is too small.

**Comment by simoncozens** [comment]
Yes, especially for Urdu a large madda is preferable.
