### ISSUE TITLE
(U+FDF2) “ﷲ” ARABIC LIGATURE ALLAH ligature forming

### ISSUE THREAD

**Issue by nizarsq** [googlefonts/noto-fonts#1879]
(U+FDF2) “ﷲ” ARABIC LIGATURE ALLAH ISOLATED FORM  is a very common ligature, used to display the name of God FDF2 = (0627 0644 0644 <b>0651</b> <b>0670</b> 0647). Currently NotoSansArabic, NotoSansArabicUI and NotoKufiArabic will form the ligature FDF2 at least in the following combinations:

1- 0627 0644 0644 0647 —> FDF2
2- 0627 0644 0644 <b>0651</b>  0647 —> FDF2
3- 0627 0644 0644 <b>0651</b> <b>0670</b> 0647 —> FDF2

The issue appears in the second and the third combination; 
<b>Second combaniation:</b> When 0651 ARABIC SHADDA (ّ) exist in the original combaniation. The sequence will form the ligature FDF2 and add the original 0651 ARABIC SHADDA to FDF2, this will show duplicate 0651 SHADDA and misplace the original SHADDA

<b>Third combaniation:</b> Acts same as the second combination but also will duplicate 0670 (ٰ)ARABIC LETTER SUPERSCRIPT ALEF exist in the original combaniation and misplace both SUPERSCRIPT ALEF and the SHADDA

90% the Arabic text has the SHADDA in the original text. Adding another SHADDA and SUPERSCRIPT ALEF will make a serious issue. We should generally be conservative in those ligatures. 
My suggestions are:
1- Form combination only if SHADDA <b>or</b> SHADDA and SUPERSCRIPT ALEF exist in the original text and the very important part is dropping SHADDA and SUPERSCRIPT ALEF to avoid duplication
2- All Google Arabic fonts should act the same to maintain consistency to give users the flexibility to use all fonts without any issues

<b>Issue found in:</b>
NotoSansArabic 2.002
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf
NotoSansArabicUI 2.002
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansArabicUI/NotoSansArabicUI-Regular.ttf
NotoKufiArabic Version 2.101
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoKufiArabic/NotoKufiArabic.ttf

<b>Characters data used in the test below:</b>
0627 0644 0644 0647 (No SHADDA or SUPERSCRIPT ALEF)
0627 0644 0644 0651 0647 (With SHADDA)
0627 0644 0644 0651 0670 0647 (With SHADDA and SUPERSCRIPT ALEF)

<img width="1392" alt="Screen Shot 2020-10-02 at 11 19 28 PM" src="https://user-images.githubusercontent.com/22158882/94984875-baaff080-0505-11eb-8a84-b766e045de0a.png">

**Comment by nizarsq** [comment]
http://www.unicode.org/versions/Unicode13.0.0/ch09.pdf

**Comment by mahalisyarifuddin** [comment]
This issue really reminds me of [the same issue in IBM's Plex Arabic](https://github.com/IBM/plex/issues/243). 

[This tool ](https://w3c.github.io/alreq/gap-analysis/tests/ligation/ligation_000.html) might be helpful.

**Comment by nizarsq** [comment]
This issue fixed for NotoSansArabic NotoSansArabicUI.

**Comment by nizarsq** [comment]
Applying fixing to NotoKufiArabic
