### ISSUE TITLE
Design review for dots/diacritics positioning in NotoNastaliqUrdu

### ISSUE THREAD

**Issue by nizarsq** [googlefonts/noto-fonts#1881]
Dots and dictrics may need some review. In some combinations dots and diacritics could overlap or touch each other. the word "اسْتَوَى" in :هُوَ الَّذِي خَلَقَ لَكُم مَّا فِي الأَرْضِ جَمِيعًا <b>اسْتَوَى</b> ثُمَّ إِلَى السَّمَاء فَسَوَّاهُنَّ سَبْعَ سَمَاوَاتٍ وَهُوَ بِكُلِّ شَيْءٍ shows this behavior. Since Arabic heavily depends on dielectrics on daily use and there extensive use in Quran I would think this is one of the issues we should look into.

<b>Issue found in: </b> 
NotoNastaliqUrdu Version 2.000
 https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoNastaliqUrdu/NotoNastaliqUrdu-Regular.ttf

<b>Characters data:</b>
تتَوَ تثَوَ تثَوَتغَؤَ اسْتَوَى تتَوُ تثَوُ تثَوَتغَؤُ اسْتَوُ تتَوٌ تثَوٌ تثَوَتغَؤٌ اسْتَوٌى تتَمٌو تثَمٌو تثَمَتغَؤٌ اسْتَمٌو

<b>Screenshot:</b>
<img width="1390" alt="Screen Shot 2020-10-04 at 8 51 05 PM" src="https://user-images.githubusercontent.com/22158882/95039041-8747a000-0684-11eb-96dd-3f878d3f1a34.png">

**Comment by simoncozens** [comment]
Thanks for this. This isn't a design issue but an engineering one, and I'm afraid to say that realistically this is unlikely to be fixed without a complete re-engineering of the font. The dot collision issue is very complex and difficult to resolve in OpenType fonts, and the current way it is implemented in Noto Nastaliq Urdu is quite limited and hard to change. 

Typesetting Quranic Arabic correctly still requires specialist software, and this will continue to be the case for a long time; I don't think it will ever really be possible with OpenType.
