### ISSUE TITLE
[NotoNaskhArabic] Some symbols are not placed correctly on Hamza

### ISSUE THREAD

**Issue by KazunariTsuboi** [googlefonts/noto-fonts#1885]
### Font 
NotoNaskhArabic-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/master/hinted/ttf/NotoNaskhArabic/NotoNaskhArabic-Regular.ttf
Date: 2020-9-13 07:08:36 (head table/modified)

### Font Version
Version 2.000; ttfautohint (v1.8.2)

### OS name and version
Windows 10, 1909

### Application name and version
Google Chrome 85.0.4183.102（Official Build） (64 bit)

### Issue
It is not possible to display the word سيملأُ 　correctly in NotoNaskhArabic.
The Hamza overlaps with the symbol. 
![1](https://user-images.githubusercontent.com/21096794/95403505-5fd72880-094d-11eb-8b14-935704a09e59.png)

The problem and related characters are the following:
It is confirmed that the Hamza overlaps consistently.
![2](https://user-images.githubusercontent.com/21096794/95403526-72516200-094d-11eb-8a3c-862652b52ec0.png)

It is the same with the inferior Hamza.
![3](https://user-images.githubusercontent.com/21096794/95403543-7e3d2400-094d-11eb-8fb2-253e3af878fd.png)

This cannot be found when the Lam+alif+hamza Isolated ligature is used. 
Also, it only appears in the final form. 
![4](https://user-images.githubusercontent.com/21096794/95403552-84cb9b80-094d-11eb-8d47-d816c9cccbe2.png)
![5](https://user-images.githubusercontent.com/21096794/95403562-8bf2a980-094d-11eb-930a-1c34bd5315d9.png)

### Character data
ملأَ ملأً ملأُ ملأٌ ملإِ ملإٍ
U+0645 U+0644 U+0623 U+064E ملأَ 
U+0645 U+0644 U+0623 U+064B ملأً 
U+0645 U+0644 U+0623 U+064F ملأُ 
U+0645 U+0644 U+0623 U+064C ملأٌ 
U+0645 U+0644 U+0625 U+0650 ملإِ 
U+0645 U+0644 U+0625 U+064D ملإٍ

**Comment by nizarsq** [comment]
@KazunariTsuboi Thank you for filing this issue. We definitely need this issue to be fixed. This issue reproducible on NotoNaskhArabicUI too. 

Note: There is a similar issue with NotoSansArabic, but that is a shaping engine issue if i'm not mistaken.
Chrome:
<img width="592" alt="Screen Shot 2020-10-07 at 8 02 03 PM" src="https://user-images.githubusercontent.com/22158882/95410118-fa952000-08d7-11eb-9e41-b02cc03245fa.png">

Safari:
<img width="651" alt="Screen Shot 2020-10-07 at 8 02 28 PM" src="https://user-images.githubusercontent.com/22158882/95410163-0a146900-08d8-11eb-87da-a064e69b81a4.png">
