### ISSUE TITLE
Missing superscripts  in NotoNastaliqUrdu will make subscripts fallback to another font

### ISSUE THREAD

**Issue by nizarsq** [googlefonts/noto-fonts#1890]
U+06DA ARABIC SMALL HIGH JEEM (used in Quran which means readers can stop reading at this point) and other superscripts like U+0615 are missing from NotoNastaliqUrdu. The missing codespoints issue filed in https://github.com/googlefonts/noto-fonts/issues/1873. The issue I'm reporting here is wherever there's missing superscript in the text the subscript will fallback to another font (Not only the superscript), this causes a broken ligature. Below a screenshot of how the text looks when a missing superscript appears. Not sure why the font fallback for subscripts when the font has them.

<b>Issue found in:</b>
NotoNastaliqUrdu Version 2.000 
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoNastaliqUrdu/NotoNastaliqUrdu-Regular.ttf

<b>Characters data used in the test:</b>
الٓزۚ الٓز الٓرۚ  الٓر الوۚ الو دۚ  د عۚ ع عؕ

<b>Screenshot:</b>
<img width="1073" alt="Screen Shot 2020-10-08 at 8 39 23 PM" src="https://user-images.githubusercontent.com/22158882/95540804-92613f80-09a6-11eb-9f47-b84c99f76f70.png">

<img width="960" alt="Screen Shot 2020-10-08 at 8 46 04 PM" src="https://user-images.githubusercontent.com/22158882/95541155-74e0a580-09a7-11eb-9d9b-31b3140adc75.png">

**Comment by simoncozens** [comment]
The fallback issue is a result of the rendering environment. (For example, InDesign will not do any fallback at all.) The underlying problem is the missing codepoints, so I am closing this and moving discussion to #1873.
