### ISSUE TITLE
NotoNaskhArabic dlig feature should be removed

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/noto-fonts#1894]
Noto Naskh Arabic fonts have a `dlig` feature that combines symbols from U+FBB2–FBC1 with dotless glyphs to make dotted forms.

This is wrong because these symbols are not combining marks and should not combine with base glyphs. From [TUS](https://www.unicode.org/versions/Unicode13.0.0/ch09.pdf#G45378):
> In the Unicode  Standard,  extended  Arabic  characters  with  nuktas  are  simply  encoded  as  fully-formed  base  characters.  However,  there  is  an  occasional  need  in  pedagogical  materials about the Arabic script to exhibit the various nuktas in isolation. The range of characters U+FBB2..U+FBC1 provides a set of symbols for this purpose. These are ordinary, spacing symbols  with  right-to-left  directionality.  They  are  not  combining  marks,  and  are  not intended  for  the  construction  of  new  Arabic  letters  by  use  in  combining  character sequences.

### Character data
For example the sequence U+FB9F, U+FBB3, U+FBB2 should show a final _noon_ then a dot below then a dot above, not final _noon with dot above and below_.

### Screenshot
Expected output:
> hb-view NotoNaskhArabic-Regular.otf -u "FB9F FBB3 FBB2"

![correct](https://user-images.githubusercontent.com/93914/95655645-1af7f100-0b09-11eb-931b-74d4e69ee133.png)

Wrong output:
> hb-view NotoNaskhArabic-Regular.otf -u "FB9F FBB3 FBB2" --features="dlig"

![wrong](https://user-images.githubusercontent.com/93914/95655654-277c4980-0b09-11eb-9981-42414978737b.png)

**Comment by khaledhosny** [comment]
This is a regression introduced in version 2.0

**Comment by nizarsq** [comment]
Issue not reproducible in the current version (2.001).

**Comment by khaledhosny** [comment]
Still reproducible for me:
```
$ hb-view unhinted/otf/NotoNaskhArabic/NotoNaskhArabic-Regular.otf -u "FB9F FBB3 FBB2" --features="dlig"
```
![a](https://user-images.githubusercontent.com/93914/102338460-8bedd600-3f9c-11eb-8dc9-f4ba24fe2230.png)
