### ISSUE TITLE
Quranic annotation signs (U+06D7  U+06D6) misplaced in Noto fonts

### ISSUE THREAD

**Issue by nizarsq** [googlefonts/noto-fonts#1895]
Quranic annotation signs (signs of endowment) U+06D7 (pause reading is preferred) and  U+06D6 (continue reading is preferred) should positioned on the last portion of the letter. Currently Noto fonts align them on the beginning of wide letters. 

<b>Issue found in: </b> 
NotoNaskhArabic Version 2.000
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoNaskhArabic/NotoNaskhArabic-Regular.ttf
NotoNaskhArabicUI Version 2.000
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoNaskhArabicUI/NotoNaskhArabicUI-Regular.ttf
NotoSansArabicUI Version 2.02
 https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansArabicUI/NotoSansArabicUI-Regular.ttf
NotoSansArabic Version 2.02
 https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf
NotoKufiArabic Version 2.101
 https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoKufiArabic/NotoKufiArabic-Regular.ttf

<b>Characters data used in the test:</b>
وَٱلۡأَرۡضِۖ ٱلنَّاسِۖ ٱلۡأَرۡضِۗ أَوْلَى سسسۗ لللۗ

<img width="694" alt="Screen Shot 2020-10-12 at 11 54 01 AM" src="https://user-images.githubusercontent.com/22158882/95781116-02f7ad00-0c82-11eb-80a9-f324a7f5bc47.png">

![screen-3](https://user-images.githubusercontent.com/22158882/95780829-7e0c9380-0c81-11eb-96b7-2adf5dab9d39.jpg)
![screen-1](https://user-images.githubusercontent.com/22158882/95780833-7fd65700-0c81-11eb-9769-08f9179fedea.jpg)

Here more screenshots:
https://ar.wikipedia.org/wiki/%D8%B9%D9%84%D8%A7%D9%85%D8%A7%D8%AA_%D8%A7%D9%84%D8%B6%D8%A8%D8%B7_%D9%88%D8%A7%D9%84%D9%88%D9%82%D9%81_%D9%81%D9%8A_%D8%A7%D9%84%D9%85%D8%B5%D8%AD%D9%81#%D8%B9%D9%84%D8%A7%D9%85%D8%A7%D8%AA_%D8%A7%D9%84%D9%88%D9%82%D9%81_%D9%88%D8%A7%D9%84%D9%85%D8%AF_%D9%81%D9%8A_%D8%A7%D9%84%D9%85%D8%B5%D8%AD%D9%81_%D8%A7%D9%84%D8%B4%D8%B1%D9%8A%D9%81

**Comment by atuvhnynv145** [comment]
<img width="1077" alt="截圖 2020-10-12 20 57 05" src="https://user-images.githubusercontent.com/63421702/95785353-7f63ad80-0ccd-11eb-8f67-961a87c69a07.png">

**Comment by dscorbett** [comment]
This affects all the waqf signs, not just U+06D6 and U+06D7.

Another positioning quirk of these signs is that they appear at a certain minimum height. They can be raised to make room for other marks but not lowered below that height. See [“AlQalam for typesetting traditional Arabic texts”, section 5.1](http://www.tug.org/tugboat/tb27-2/tb87fahmy.pdf#page=5). For example, U+06D6 should be at the same height in both <U+0631, U+06D6> and <U+0631, U+064E, U+06D6>.
![رۖرَۖ](https://user-images.githubusercontent.com/1124347/95785548-f7b57900-0ca3-11eb-87ef-556d31f59c3f.png)

For the UI fonts with their restricted line height, this minimum height might be too high. I have found an alternative positioning strategy: in [surah 2, ayah 26 of this Quran](https://app.quranflash.com/book/NaskhTaleek?en#/reader/chapter/7) there are examples of U+0615 ARABIC SMALL HIGH TAH, U+06DA ARABIC SMALL HIGH JEEM, and U+06D8 ARABIC SMALL HIGH MEEM INITIAL FORM. They are rendered as spacing marks to the left of their bases and are only somewhat raised above the baseline. Something like this (at least the use of spacing marks) may be appropriate for the UI fonts.

**Comment by marekjez86** [comment]
@atuvhnynv145 : what does your screen shot mean? what is the issue that you'd like to report?

**Comment by nizarsq** [comment]
@dscorbett Thanks for your comment.  I didn't see issues with other waqf signs in terms of sitting on the beginning of the letter . 
At this stage I'm trying to focus on higher priority Arabic issues (Issues affect daily users). If you have anything that I didn't catch please feel free to update the bug or file other bugs.

06D6 " ۖ " appears in 1294 verse(s) in Quran ---> Misplaced 
06D7 " ۗ " appears in 517 verse(s) in Quran --->  Misplaced
06DA " ۚ " appears in 5617 verse(s) in Quran ---> Looks good  دَرَجَاتٍ ۚ وَآتَيْنَا, كَفَرَ ۚ وَلَوْ, وَالْعُدْوَانِ ۚ وَاتَّقُوا, بَعْضٍ ۚ وَمَن
06DC " ۜ " appears in 5 verse(s) in Quran ---> Looks good  لَّهُمْ مَنْ ۜ بَلْ ۜ رَانَ
06D8 " ۘ " appears in 22 verse(s) in Quran ---> Looks good  مَثَلًا ۘ يُضِلُّ, قَوْلِهِمْ ۘ تَشَابَهَتْ, الَّذِينَ آمَنُوا ۘ وَالَّذِينَ, بَعْضٍ ۘ مِّنْهُم
06DB " ۛ " appears in 6 verse(s) in Quran ---> Looks good  إِلَى التَّهْلُكَةِ ۛ وَأَحْسِنُوا ۛ ,  لَا رَيْبَ ۛ فِيهِ ۛ هُدًى, عَلَيْهِمْ ۛ أَرْبَعِينَ سَنَةً ۛ 
06D9 " ۙ " appears in 64 verse(s) in Quran ---> Looks good  الْكِتَابِ ۙ أُولَـٰئِكَ قَلِيلًا ۙ أُولَـٰئِكَ

<img width="1156" alt="Screen Shot 2020-10-13 at 9 28 48 PM" src="https://user-images.githubusercontent.com/22158882/95944556-4a269080-0d9d-11eb-8936-bac06a3cfbae.png">

**Comment by dscorbett** [comment]
It only looks good in your test file because a space comes between the letter and the annotation sign. If you remove the space, the problem appears.
![دَرَجَاتٍۚ](https://user-images.githubusercontent.com/1124347/95999040-7e349c80-0e03-11eb-924f-e13a4ad90242.png)

**Comment by fawazahmed0** [comment]
**Font Details:**
NotoNaskhArabic Version 2.000
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoNaskhArabic/NotoNaskhArabic-Regular.ttf
NotoSansArabic Version 2.002
 https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf
NotoKufiArabic Version 2.101
 https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoKufiArabic/NotoKufiArabic-Regular.ttf

Few examples where two quranic annotations are together:

**Character Data:**
وَمَا كَانَ لَنَا عَلَيۡكُم مِّن سُلۡطَٰنِۭۖ بَلۡ كُنتُمۡ قَوۡم ࣰ ا طَٰغِينَ

Noto Sans Arabic:
![image](https://user-images.githubusercontent.com/20347013/96533978-8467c480-12ac-11eb-94d4-9c3fa84b732a.png)

Noto Naskh:
![image](https://user-images.githubusercontent.com/20347013/96534144-c8f36000-12ac-11eb-849a-5e4769c4ab58.png)

Noto Kufi:
![image](https://user-images.githubusercontent.com/20347013/96534201-e45e6b00-12ac-11eb-86f6-1b0a655389e5.png)

**Character Data2:**
فَإِذَا مَسَّ ٱلۡإِنسَٰنَ ضُرّ ࣱ دَعَانَا ثُمَّ إِذَا خَوَّلۡنَٰهُ نِعۡمَة ࣰ مِّنَّا قَالَ إِنَّمَآ أُوتِيتُهُۥ عَلَىٰ عِلۡمِۭۚ بَلۡ هِيَ فِتۡنَة ࣱ وَلَٰكِنَّ أَكۡثَرَهُمۡ لَا يَعۡلَمُونَ

Noto Sans Arabic:
![image](https://user-images.githubusercontent.com/20347013/96534668-d4935680-12ad-11eb-948c-5a8a42453bb7.png)

Noto Naskh:
![image](https://user-images.githubusercontent.com/20347013/96534791-115f4d80-12ae-11eb-8a01-f9bd0d9a7cb2.png)

Noto Kufi:
![image](https://user-images.githubusercontent.com/20347013/96534892-44a1dc80-12ae-11eb-86b0-1b99ae986186.png)

**Character Data3:**
ٱلۡعَزۡمِ مِنَ ٱلرُّسُلِ وَلَا تَسۡتَعۡجِل لَّهُمۡۚ كَأَنَّهُمۡ يَوۡمَ يَرَوۡنَ مَا يُوعَدُونَ لَمۡ يَلۡبَثُوٓاْ إِلَّا سَاعَة ࣰ مِّن نَّهَارِۭۚ بَلَٰغ ࣱ ۚ فَهَلۡ يُهۡلَكُ إِلَّا ٱلۡقَوۡمُ ٱلۡفَٰسِقُونَ

Noto Sans Arabic:
![image](https://user-images.githubusercontent.com/20347013/96535204-ecb7a580-12ae-11eb-9994-0002917589ab.png)

Noto Naskh:
![image](https://user-images.githubusercontent.com/20347013/96535405-5f288580-12af-11eb-9399-38d146f04965.png)

Noto Kufi:
![image](https://user-images.githubusercontent.com/20347013/96535457-7b2c2700-12af-11eb-9f36-c405d21c6cd6.png)

There are many more examples, a regex search `[\u0610-\u061f\u06d6-\u06e0\u06e2\u06ed\u08d3-\u08ff]{2,}` will bring many more of these depending on quran data you have.

You might want to consider adding support for quranic annotations in [Arabic Extended-A Block](https://www.unicode.org/charts/PDF/U08A0.pdf) to add support for different quranic variants.

Example from Quran Naskh/IndoPak Variant:

Character Data:
صِرَاطَ الَّذِيۡنَ اَنۡعَمۡتَ عَلَيۡهِمۡ ࣢ۙ غَيۡرِ الۡمَغۡضُوۡبِ عَلَيۡهِمۡ وَلَا الضَّآلِّيۡنَ ࣖ‏

Noto Sans Arabic:
![image](https://user-images.githubusercontent.com/20347013/96535942-964b6680-12b0-11eb-9274-25435c954061.png)

Noto Naskh:
![image](https://user-images.githubusercontent.com/20347013/96535987-af541780-12b0-11eb-986b-6a578bf1a451.png)

Noto Kufi:
![image](https://user-images.githubusercontent.com/20347013/96536049-d4e12100-12b0-11eb-9464-73b0974fba8c.png)

Many more  quranic annotations will be added to new Arabic Extended-B Block in coming Unicode v14 to add support for qaloon, Warsh etc variants of quran. See [this](http://www.unicode.org/L2/L2019/19306-quranic-additions.pdf) and [http://www.unicode.org/alloc/Pipeline.html] for more info.

Thanks

**Comment by nizarsq** [comment]
I believe this looks much better
<img width="718" alt="Screen Shot 2020-11-26 at 8 33 41 PM" src="https://user-images.githubusercontent.com/22158882/100411450-acbead80-3026-11eb-829e-3a764656940e.png">

**Comment by nizarsq** [comment]
Issue fixed
