### ISSUE TITLE
Spacing issue between words in NotoNastaliqUrdu

### ISSUE THREAD

**Issue by nizarsq** [googlefonts/noto-fonts#1896]
I have little concern about the spacing between words in NotoNastaliqUrdu. I have attached a screenshot with some text that shows inconsistent spacing between words.

<b>Issue found in:</b>
NotoNastaliqUrdu Version 2.000 
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoNastaliqUrdu/NotoNastaliqUrdu-Regular.ttf

<b>Characters data used in the test:</b>
أَنفُسِكُمْ أَوْ تُخْفُوهُ يُحَاسِبْكُم بِهِ
رَبَّنَا وَلاَ تَحْمِلْ عَلَيْنَا

<b>Screenshot:</b>
<img width="548" alt="Screen Shot 2020-10-12 at 8 43 10 PM" src="https://user-images.githubusercontent.com/22158882/95813086-e4b69f00-0ccb-11eb-8dbe-05e34249a007.png">
<img width="953" alt="Screen Shot 2020-10-12 at 8 54 30 PM" src="https://user-images.githubusercontent.com/22158882/95813669-41ff2000-0ccd-11eb-80c8-2e636641a7c5.png">

**Comment by nizarsq** [comment]
Here another screenshot that shows spacing issue, words very close to each other.
<img width="704" alt="Screen Shot 2020-10-13 at 10 09 53 AM" src="https://user-images.githubusercontent.com/22158882/95893023-3dbe1b80-0d3c-11eb-9592-884e53b05baf.png">

**Comment by khaledhosny** [comment]
> words very close to each other.

That is expected for Nastaliq (and most traditional Arabic calligraphic styles in general), there is usually no distinction between internal and inter word spacing. Wider space between words is a typographic novelty as far as Arabic script is concerned.

**Comment by nizarsq** [comment]
Thanks. I still believe NotoNastaliqUrdu may need some review, see below the dots below touching letter dal. <img width="501" alt="Screen Shot 2020-12-14 at 1 00 01 PM" src="https://user-images.githubusercontent.com/22158882/102135081-49958f00-3e0c-11eb-9f74-411feb00f499.png">

**Comment by simoncozens** [comment]
This was addressed in https://github.com/googlefonts/noto-source/pull/488, and so will be fixed in the next update to Noto Nastaliq:

![shape](https://user-images.githubusercontent.com/106728/151341500-1c5e3be6-e4d3-4b3c-8897-97363053d4fb.png)
