### ISSUE TITLE
U+06E4 in NotoKufiArabic design may need review in NotoKufiArabic

### ISSUE THREAD

**Issue by nizarsq** [googlefonts/noto-fonts#1899]
U+06E4 ARABIC SMALL HIGH MADDA supposed to be small madda but in NotoKufiArabic it is too small, a design review maybe needed for U+06E4

<b>Issue found in: </b> 
NotoKufiArabic Version 2.101
 https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoKufiArabic/NotoKufiArabic-Regular.ttf

<b>Characters data used in the test:</b>
بۤ بٓ

<b>Screenshot:</b>
<img width="1211" alt="Screen Shot 2020-10-13 at 3 57 47 PM" src="https://user-images.githubusercontent.com/22158882/95924666-e2585180-0d6c-11eb-9e80-747d5e0b9af2.png">

**Comment by khaledhosny** [comment]
Small part in the name is a misnomer, this mark is used in Quranic notation to denote extra long vowels and it is essentially the same size and shape as regular madda (the only real distinction is that it does not have canonical composition with alef, so آ is not the same as alef with small madda above it).

**Comment by nizarsq** [comment]
> Small part in the name is a misnomer, this mark is used in Quranic notation to denote extra long vowels and it is essentially the same size and shape as regular madda (the only real distinction is that it does not have canonical composition with alef, so آ is not the same as alef with small madda above it).

I  believe it's still too small relative to the font glyphs.
<img width="508" alt="Screen Shot 2020-12-14 at 12 43 25 PM" src="https://user-images.githubusercontent.com/22158882/102133448-f7ec0500-3e09-11eb-991f-3c7fdfb68791.png">

**Comment by khaledhosny** [comment]
I agree. My suggestion is to make it use regular mark as a component in all fonts.

**Comment by nizarsq** [comment]
Issue fixed
