### ISSUE TITLE
Miao is not supported yet.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#190]
```
Lisu is support for now. But I'm curious about why Miao has not been supported 
yet. 

http://phjamr.github.io/miao.html 
```

Original issue reported on code.google.com by `jinntra...@gmail.com` on 1 Nov 2014 at 5:15

**Comment by jungshik** [comment]
Assign to @marekjez86 to track the progress of Miao script.

**Comment by tearsofphoenix** [comment]
So, is miao supported now?
@GoogleCodeExporter 
@marekjez86 
@xiangyexiao

**Comment by dougfelt** [comment]
Miao is scheduled as part of the phase III work but has not been started yet.

**Comment by nizarsq** [comment]
Miao supported now.
<img width="660" alt="Screen Shot 2020-08-01 at 1 18 34 PM" src="https://user-images.githubusercontent.com/22158882/89109823-82067480-d3f9-11ea-8ccd-34b14f42e31d.png">
