### ISSUE TITLE
Word  اللّٰه (Allah) shows incorrectly

### ISSUE THREAD

**Issue by fawazahmed0** [googlefonts/noto-fonts#1902]
## Defect Report
The word Allah shows improperly in noto sans arabic

### Font 
NotoSansArabic-Regular.ttf
version 2.000

### Where the font came from, and when 
https://www.google.com/get/noto/#sans-arab
Date: 2020-10-16

### Font Version
2.000

### OS name and version
Windows 7

### Character data
شَآءَ اللّٰهُ لَذَهَبَ بِسَمۡعِهِمۡ وَاَبۡصَارِهِمۡ ؕ اِنَّ اللّٰهَ عَلٰي كُلِّ

### Noto Sans Arabic Font(shows incorrectly):
![image](https://user-images.githubusercontent.com/20347013/96206237-207c8d80-0f86-11eb-9953-a870926daef1.png)

### Noto Kufi Arabic(shows correctly):
![image](https://user-images.githubusercontent.com/20347013/96206274-30946d00-0f86-11eb-8bf1-a66a1a9e5eba.png)

Thanks

**Comment by nizarsq** [comment]
I belive this is dup of https://github.com/googlefonts/noto-fonts/issues/1879
