### ISSUE TITLE
\u06E0 should look like oval shaped zero

### ISSUE THREAD

**Issue by fawazahmed0** [googlefonts/noto-fonts#1903]
\u06E0 should look like oval shaped zero
### Font 
NotoKufiArabic-Regular.ttf

### Where the font came from, and when
https://www.google.com/get/noto/#kufi-arab
Date: 2020-10-16

### Font Version
1.04

### OS name and version
Windows 7

### Issue
The [unicode doc](https://www.unicode.org/charts/PDF/U0600.pdf) describes the \u06E0 incorrectly as ARABIC SMALL HIGH UPRIGHT RECTANGULAR ZERO, rather it should be described as oval shaped zero and I have send a request to unicode to correct the description. Just explaining this so that you guys don't get confused due to wrong description in unicode doc.

### Character data
قَبۡلِهِ الرُّسُلُ ؕ اَفَا۠ئِنۡ مَّاتَ اَوۡ قُتِلَ انۡقَلَبۡتُمۡ 

### Noto Kufi Arabic(Shows incorrectly):
![image](https://user-images.githubusercontent.com/20347013/96207848-da292d80-0f89-11eb-95d7-1c3a45daaec0.png)

### Noto Sans Arabic(Shows correctly):
![image](https://user-images.githubusercontent.com/20347013/96207805-bcf45f00-0f89-11eb-9418-e9344fed3c3b.png)

Thanks

**Comment by dscorbett** [comment]
The substance of this bug report is true, but I want to point out that the name ARABIC SMALL HIGH UPRIGHT RECTANGULAR ZERO isn’t incorrect: this mark is apparently known in Arabic as “<span lang=ar>الصفر المستطيل القائم</span>”.

**Comment by fawazahmed0** [comment]
> 
> 
> The substance of this bug report is true, but I want to point out that the name ARABIC SMALL HIGH UPRIGHT RECTANGULAR ZERO isn’t incorrect: this mark is apparently known in Arabic as “الصفر المستطيل القائم”.

Thanks, for pointing that out, it seems they have chosen very ambiguous name for that mark

**Comment by khaledhosny** [comment]
The name in Arabic refers to the shape of 0, not the Eastern-Arabic ٠.

**Comment by nizarsq** [comment]
<img width="1319" alt="Screen Shot 2020-10-24 at 10 58 13 PM" src="https://user-images.githubusercontent.com/22158882/97099997-67d0e100-164c-11eb-9b5c-9bf6025a745b.png">

**Comment by nizarsq** [comment]
This issue fixed.
