### ISSUE TITLE
Outline glitch in Noto Sans Lao

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#1904]
The Black ExtraCondensed master of Lao letter oO (uni0EAD) contains an outline glitch (this is a copy of issue https://github.com/googlefonts/noto-source/issues/245 )

**Comment by nizarsq** [comment]
<img width="1163" alt="Screen Shot 2020-10-19 at 6 41 46 PM" src="https://user-images.githubusercontent.com/22158882/96529928-2b137d00-123b-11eb-848e-035f73f39d07.png">

**Comment by nizarsq** [comment]
This issue fixed.
