### ISSUE TITLE
Some codepoints missing/mispositioned anchors in NotoNaskhArabic NotoNaskhArabicUI and NotoNastaliqUrdu

### ISSUE THREAD

**Issue by nizarsq** [googlefonts/noto-fonts#1908]
Below codepoints missing/mispositioned anchors:
076B 0631 075C 076D 0633 075D 0639 0763 0643 0762. 
This behaviour can be seen in NotoNaskhArabic NotoNaskhArabicUI and NotoNastaliqUrdu (All weights)

<b>Issue found in: </b> 
NotoNaskhArabic Version 2.000
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoNaskhArabic
NotoNaskhArabicUI Version 2.000
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoNaskhArabicUI
NotoNastaliqUrdu Version 2.000 
https://github.com/googlefonts/notofonts/tree/master/unhinted/ttf/NotoNastaliqUrdu

<b>Characters used in the test:</b>
تݫُݫُ ترُرُ ݜُ ݜُݜُݜُ ݭُ ݭُݭُݭُ سُ سُسُسُ ݝُ ݝُݝُݝُ عُ عُعُعُ ݣُ ݣُݣُݣُ كُ كُكُكُ ݢُ ݢُݢُݢُ

<b>Screenshot:</b>
<img width="1013" alt="Screen Shot 2020-10-22 at 8 00 41 PM" src="https://user-images.githubusercontent.com/22158882/96951781-1a187500-14a2-11eb-9fa1-920b98a14b64.png">

**Comment by nizarsq** [comment]
This issue fixed for NotoNaskhArabic and NotoNaskhArabicUI

**Comment by nizarsq** [comment]
Removing Naskh label since the issue fixed for this font. Will keep the issue open to keep track of this issue since it is reproducible in NotoNastaliqUrdu

**Comment by simoncozens** [comment]
I'm not convinced that the anchor positioning for 0763 in Nastaliq is wrong. All fonts I have seen have it at the corner of the top stroke and the vertical stroke:

![shape](https://user-images.githubusercontent.com/106728/151340644-2e9dc68d-ddce-4a03-88d5-38339bae1baa.png)  ![shape](https://user-images.githubusercontent.com/106728/151340952-08906804-2ded-42dd-a9ee-2595fbb7e56a.png) ![shape](https://user-images.githubusercontent.com/106728/151340697-6f2b1416-4855-441c-a6cb-8241494ec026.png) ![shape](https://user-images.githubusercontent.com/106728/151341185-dc4a44fe-5d9b-4128-88d3-58fa37827046.png)

**Comment by khaledhosny** [comment]
Yes, that is the expected position. The one in Naskh and Sans fonts in the first screenshot is the wrong one.
