### ISSUE TITLE
sources ought to include appropriate whitespaces 

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#1909]
Update the following sources to include appropriate whitespaces (see below for details). Note that both 0x0020 and 0x00A0 need to have the same width within a single source/script.

NotoKufiArabic
NotoSansElymaic
NotoSansGunjalaGondi
NotoSansMasaramGondi
NotoSansMedefaidrin
NotoSerifDogra
NotoSerifNyiakengPuachueHmong
NotoSerifYezidi
NotoTraditionalNushu

fontbakery-NotoKufiArabic-Regular-out.txt:    * FAIL: Whitespace glyph missing for codepoint 0x00A0. [code: missing-whitespace-glyph-0x00A0]
fontbakery-NotoSansElymaic-Regular-out.txt:    * FAIL: Whitespace glyph missing for codepoint 0x00A0. [code: missing-whitespace-glyph-0x00A0]
fontbakery-NotoSansGunjalaGondi-Regular-out.txt:    * FAIL: Whitespace glyph missing for codepoint 0x00A0. [code: missing-whitespace-glyph-0x00A0]
fontbakery-NotoSansMasaramGondi-Regular-out.txt:    * FAIL: Whitespace glyph missing for codepoint 0x00A0. [code: missing-whitespace-glyph-0x00A0]
fontbakery-NotoSansMedefaidrin-Regular-out.txt:    * FAIL: Whitespace glyph missing for codepoint 0x00A0. [code: missing-whitespace-glyph-0x00A0]
fontbakery-NotoSansTamilSupplement-Regular-out.txt:    * FAIL: Whitespace glyph missing for codepoint 0x0020. [code: missing-whitespace-glyph-0x0020]
fontbakery-NotoSansTamilSupplement-Regular-out.txt:    * FAIL: Whitespace glyph missing for codepoint 0x00A0. [code: missing-whitespace-glyph-0x00A0]
fontbakery-NotoSerifDogra-Regular-out.txt:    * FAIL: Whitespace glyph missing for codepoint 0x00A0. [code: missing-whitespace-glyph-0x00A0]
fontbakery-NotoSerifNyiakengPuachueHmong-Regular-out.txt:    * FAIL: Whitespace glyph missing for codepoint 0x00A0. [code: missing-whitespace-glyph-0x00A0]
fontbakery-NotoSerifYezidi-Regular-out.txt:    * FAIL: Whitespace glyph missing for codepoint 0x00A0. [code: missing-whitespace-glyph-0x00A0]
fontbakery-NotoTraditionalNushu-Regular-out.txt:    * FAIL: Whitespace glyph missing for codepoint 0x00A0. [code: missing-whitespace-glyph-0x00A0]

**Comment by nizarsq** [comment]
0x00A0  added.
