### ISSUE TITLE
NotoSansOldHungarian font require at least capital ligatures "Qu", "X", "W" (with ZWJ only)

### ISSUE THREAD

**Issue by Kixidevel** [googlefonts/noto-fonts#1913]
## Defect Report
Noto Sans Old Hungarian regular font doesn't have Capital ligatures. At least Qu, X and W (forms these ligatures see below) required
### Font 
NotoSansOldHungarian-Regular.ttf and otf versions, too.
### Reasons:
There are in latin based Hungarian script several times uses letters:
"W" frequently used in noble names like "Wass Albert", "Wesselényi Miklós" or in foreign names.
"X" used in foreign names like Xerxes
"Q" used in foreign names like Quasimodo
My suggestion is the following: Don't use it as discrete ligatures, because automations may make spelling problems, as already described in "noto-source" project issue #215. Use it only "liga" section.
### Screenshot
![q_w_x_for_noto](https://user-images.githubusercontent.com/32356899/98923148-94517d80-24d3-11eb-8e5e-462018cdb739.jpg)
I suggested two kind of key combinations, all required, because might be pressed with Caps-lock or without Caps-lock

**Comment by Kixidevel** [comment]
Spelling problems explained in Issue #1776 , too

**Comment by Kixidevel** [comment]
@marekjez86 : Could you do this modification? I don't understand the drawing philosophy of noto-sources. I just only understand the ligature specifications.

**Comment by Kixidevel** [comment]
@marekjez86 Marek, it seems, You've got a lot of work. I with one of the colleague working on LO Old-Hungarian capabilities. Without this tree capital ligatures is meaningless talking about ligatures in a text editor at all.
Is there anybody else, who could do this small modification?

**Comment by Kixidevel** [comment]
@marekjez86 @google-admin We hardly need this tree capital ligatures, which are frequently used in texts transformed from Latin based Hungarian texts. (X, Qu and W letters)

**Comment by Kixidevel** [comment]
@marekjez86 : Marek, may I try it? If I couldn't do this, I will drop a comment. If I could, I open an issue in the noto-source project, and a Pull Request.

**Comment by marekjez86** [comment]
@Kixidevel : go ahead, please try

**Comment by marekjez86** [comment]
@nizarsq @Kixidevel : Nizar, could you help with this... it might be easier if you fo it :-)

**Comment by nizarsq** [comment]
> @nizarsq @Kixidevel : Nizar, could you help with this?... it might be easier if you fo it :-)

I'll look at it tonight.  Thanks

**Comment by Kixidevel** [comment]
@nizarsq : Nizar, thank you! 
Be careful, "Qu", "W", "X" ligatures MUST NOT to be defined in "discrete ligature" (dlig) section, MUST NOT to be used without ZWJ! 
If you implement the other capital ligatures, that might to be discrete ligatures (without ZWJ), too.
Thanks!

**Comment by Kixidevel** [comment]
@nizarsq Nizar, you don't need to do anything. One of my friends working on it!
He can work quickly.

**Comment by Kixidevel** [comment]
@marekjez86 I close this Issue. It's only a subset of issue #1364 , and one of my friends already working on it. He can work quickly. Not this work his first work.
