### ISSUE TITLE
NotoSansArabicUI centering baseline

### ISSUE THREAD

**Issue by nizarsq** [googlefonts/noto-fonts#1914]
NotoSansArabicUI descender currently set to -240 and Ascender is set to 760. This causes clipping to low letters and or dots/diacritics. Currently I’m able to display above diacritics mostly without clipping but the below diacritics always clipped.

If we lower above diacritics/superscript and make diacritics a little smaller (Currently oversized relative to the base glyph size) this will leave us with more white space to be able to center the baseline to reduce clipping in the bottom. Something like NotoNaskhArabic. See Attached.

Characters data used in the test:  أَ إِ  ڕ بڕ  غِ غَ
<img width="1301" alt="Screen Shot 2020-11-13 at 4 06 26 PM" src="https://user-images.githubusercontent.com/22158882/99132196-30f64700-25ca-11eb-89aa-7ecddcecb5b0.png">

**Comment by nizarsq** [comment]
@marekjez86 for opinion/decision.

**Comment by marekjez86** [comment]
Let's do it :-)

**Comment by nizarsq** [comment]
Great! I'll start work on it. Thanks

**Comment by nizarsq** [comment]
Will lower and/or resize diacritics slightly and then evaluate the font and we will go from there.

**Comment by nizarsq** [comment]
This issue relatedd to https://github.com/googlefonts/noto-fonts/issues/1935. Will close this bug.
