### ISSUE TITLE
wrong glyph in NotoSansGrantha-regular

### ISSUE THREAD

**Issue by frpatte2** [googlefonts/noto-fonts#1916]
## Defect Report
> Noto fonts can be obtained from https://github.com/googlefonts/noto-fonts/tree/master/unhinted/otf/ (unhinted OTF) or https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf/ (hinted TTF). If you find a problem with either of these then please use this template to file a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
  > wrong glyph in NotoSansGrantha-regular

### Font 
  > NotoSansGrantha-regular.ttf

### Where the font came from and when
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSansGrantha
2020-06

### Font Version
2.1

### OS name and version
Linux fedora 32

### Application name and version
xelatex

### Issue
1- type any consonnant followed by au e.g. tau, dau, gau...
2- As designed in the font, the au glyph has two parts: one before (eeMatra_gran) the consonnant and one after (auLengthMark_gran)
3- The part before the consonnant should not be there. 
4- au-matra glyph: U+1134C
 
### Character data
  > Please include real character data to illustrate your issue-- Unicode codepoints are helpful.  This makes it possible for developers who don't know the language or script to copy/paste the text to reproduce the issue.

### Screenshot
  > If possible, include a screenshot or an image illustrating the issue.
  > Annotations are also helpful.

## Tools for reporting bugs
  Useful tools for reporting bugs are available at: https://github.com/googlei18n/
  
### Harfbuzz hb-view and hb-shape
  These are part of the HarfBuzz distribution and can help isolate if an issue is in the app/OS, shaping engine, or font.
  * hb-view renders the text with the exact font (for example, to see how ligatured characters shape) using your installed version of HarfBuzz.

For example:
```
  hb-view --font-file {path to font} --text-file {path to text file} --output-file '{sample}.png'
```

* hb-shape shows glyph selection and positioning

### Fontview
  * Fontview displays the text.

### Fontdiff
  * Fontdiff displays the text using two versions of the font side by side.

**Comment by punchcutter** [comment]
The font is correct based on the decisions made in Unicode encoding. U+1134C is a two-part glyph based on old style orthography as explained at https://unicode.org/L2/L2009/09372-grantha.pdf#page=9
If you only want the single glyph it's encoded as U+11357.
