### ISSUE TITLE
Inconsistent spacing of the consonant-medial-ra ligature + vowel-sign-a on Noto Sans Balinese

### ISSUE THREAD

**Issue by mahalisyarifuddin** [googlefonts/noto-fonts#1917]
### Font 
NotoSansBalinese-Regular.ttf, also the other weights of the family

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/master/hinted/ttf/NotoSansBalinese
Date: 2020-11-06, downloaded 2020-11-16

### Font Version
2.001

### OS name and version
Windows 7

### Application name and version
Screenshot below created using Inkscape 1.0. The problems are also found on other programs.

### Issue
Got myself the brand new font, gave it a try, and I found this issue. The spacing of the consonant-medial-ra ligature + vowel-sign-a is inconsistent, and this problem is more pronounced in the lighter weight of the font set. Such spacing is somewhat okay in the bolder weight.

### Character data
Text used on the screenshot below:
A sentence from "Geguritan Aji Sasana" palmleaf manuscript, leaf 24A (https://palmleaf.org/wiki/aji-sasana-gaguritan):
ᬫᬶᬯᬄᬓ᭄ᬭᭀᬥᬚ᭄ᬭᭀᬦᬶᬂᬳᬢᬶ᭞

Examples of consonant-medial-ra ligature + vowel-sign-a:
ᬳ᭄ᬭᬵ ᬦ᭄ᬭᬵ ᬘ᭄ᬭᬵ ᬭ᭄ᬭᬵ ᬓ᭄ᬭᬵ
ᬤ᭄ᬭᬵ ᬢ᭄ᬭᬵ ᬲ᭄ᬭᬵ ᬯ᭄ᬭᬵ ᬮ᭄ᬭᬵ
ᬧ᭄ᬭᬵ ᬚ᭄ᬭᬵ ᬬ᭄ᬭᬵ ᬜ᭄ᬭᬵ
ᬫ᭄ᬭᬵ ᬕ᭄ᬭᬵ ᬩ᭄ᬭᬵ ᬗ᭄ᬭᬵ

### Screenshot
NotoSansBalinese-Regular.ttf:
![nsbregular](https://user-images.githubusercontent.com/42148566/99256379-e5e96780-2847-11eb-88cd-f38dffafcd4c.png)

NotoSansBalinese-Bold.ttf:
![nsbbold](https://user-images.githubusercontent.com/42148566/99256413-f4d01a00-2847-11eb-8d0d-1970e2eaac5b.png)

**Comment by nizarsq** [comment]
<img width="871" alt="Screen Shot 2020-11-17 at 9 16 46 PM" src="https://user-images.githubusercontent.com/22158882/99486998-3630fa00-291a-11eb-879c-ca3e20b07a7c.png">

**Comment by marekjez86** [comment]
@mahalisyarifuddin : please check out https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf/NotoSansBalinese ...
