### ISSUE TITLE
Wrong positioning of conjunct-sa + vowel-sign-e on Noto Sans Balinese

### ISSUE THREAD

**Issue by mahalisyarifuddin** [googlefonts/noto-fonts#1918]
### Font 
NotoSansBalinese-Regular.ttf, also all the other weights of the family

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/master/hinted/ttf/NotoSansBalinese
Date: 2020-11-06, downloaded 2020-11-16

### Font Version
2.001

### OS name and version
Windows 7

### Application name and version
Screenshot below created using Inkscape 1.0. The problems are also found on other programs.

### Issue
There is wrong shaping on conjunct-sa + vowel-sign-e. I can't really explain it, but the screenshot below might help.

### Character data
Text used on the screenshot below:
A sentence from "Geguritan Aji Sasana" palmleaf manuscript, leaf 3B (https://palmleaf.org/wiki/aji-sasana-gaguritan):
ᬳᭂᬜᬾᬦ᭄ᬲᬾᬡ᭄ᬥᭂᬫ᭄ᬧᬘᬂᬢᭂᬓᬵ᭞

### Screenshot
![nsb2](https://user-images.githubusercontent.com/42148566/99267298-58614400-2856-11eb-8566-317dfcd4d36b.png)

**Comment by marekjez86** [comment]
On my Mac when I paste "ᬳᭂᬜᬾᬦ᭄ᬲᬾᬡ᭄ᬥᭂᬫ᭄ᬧᬘᬂᬢᭂᬓᬵ᭞" into TexEdit and use NotoSansBalinese as a font I get 

<img width="809" alt="Screen Shot 2020-11-16 at 11 54 15" src="https://user-images.githubusercontent.com/13322623/99301948-8f5a3a00-2803-11eb-9eba-8d538ccb3656.png">

I'm confused, because Mac result appears to be correct (like the top line). If Windows with the text ᬳᭂᬜᬾᬦ᭄ᬲᬾᬡ᭄ᬥᭂᬫ᭄ᬧᬘᬂᬢᭂᬓᬵ᭞ appears like the bottom line then, in my opinion, this is a Windows shaping problem and not the font problem.

@mahalisyarifuddin : could help me understand?

**Comment by mahalisyarifuddin** [comment]
Weird. 🤔

In my Windows, Vimala got it right.
![nsb4](https://user-images.githubusercontent.com/42148566/99342708-0dc7e200-28bf-11eb-9fd7-de754ea43a59.png)

**Comment by r12a** [comment]
fwiw, I get the same problematic result with NSB in Chrome on my Mac.

NSansB:
![Screenshot 2020-11-17 at 11 30 54](https://user-images.githubusercontent.com/4839211/99385164-7b2c4080-28c8-11eb-9847-15bb6528da77.png)

NSerifB:
![Screenshot 2020-11-17 at 11 31 15](https://user-images.githubusercontent.com/4839211/99385196-88492f80-28c8-11eb-8c41-664f25d72585.png)

Vimala:
![Screenshot 2020-11-17 at 11 32 36](https://user-images.githubusercontent.com/4839211/99385251-9c8d2c80-28c8-11eb-964d-e5646afadb3a.png)

So it doesn't appear to be a Windows shaping problem.

**Comment by nizarsq** [comment]
<img width="895" alt="Screen Shot 2020-11-17 at 9 12 03 PM" src="https://user-images.githubusercontent.com/22158882/99486695-8cea0400-2919-11eb-84bf-7781ac6d2224.png">

**Comment by marekjez86** [comment]
@mahalisyarifuddin : please check out https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf/NotoSansBalinese ... should be fixed
