### ISSUE TITLE
Wrong positioning of final consonants on Noto Sans Balinese

### ISSUE THREAD

**Issue by mahalisyarifuddin** [googlefonts/noto-fonts#1919]
### Font 
NotoSansBalinese-Regular.ttf, also all the other weights of the family

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/master/hinted/ttf/NotoSansBalinese
Date: 2020-11-06, downloaded 2020-11-16

### Font Version
2.001

### OS name and version
Windows 7

### Application name and version
Screenshot below created using Inkscape 1.0. The problems are also found on other programs.

### Issue
There is wrong shaping on final consonants. I can't really explain it, but the screenshot below might help. This problem is similar to issue #1474

### Character data
Text used on the screenshot below:
A sentence from "Geguritan Aji Sasana" palmleaf manuscript, leaf 3B (https://palmleaf.org/wiki/aji-sasana-gaguritan):
ᬤᬾᬦᬶᬂᬢᬸᬢᬸᬕ᭄‌ᬭᬾᬗ᭄ᬕᬂᬭᬾᬗ᭄ᬕᭀᬂ᭞

### Screenshot
Also featuring Balinese font "Vimala" by Aditya Bayu Perdana x PanLex (https://github.com/longnow/bali-fonts) as correct rendering.

![nsb3](https://user-images.githubusercontent.com/42148566/99273763-09b6a880-285c-11eb-9481-bf60efbd28b4.png)

**Comment by marekjez86** [comment]
<img width="833" alt="Screen Shot 2020-11-16 at 11 45 31" src="https://user-images.githubusercontent.com/13322623/99300375-5d47d880-2801-11eb-899c-4e3a8e896951.png">

**Comment by marekjez86** [comment]
On my Mac using TextEdit, I obtain the same results, so this appears to be a font issue:
<img width="833" alt="Screen Shot 2020-11-16 at 11 48 05" src="https://user-images.githubusercontent.com/13322623/99300587-ab5cdc00-2801-11eb-953a-a19f974f3fef.png">

**Comment by adtbayuperdana** [comment]
it seems that the main problem is ulu ricem (uni1B01) cecak (uni1B02) or layar (uni1B03) sits above tedong (uni1B35). Correct rendering should have put those diacritics above the main aksara, not the tedong itself

this seems seems to be correct in the common holy syllable om ᬒᬁ. so 
however indeed, this reordering does not seem to be applied to other aksaras. Common examples include tong agöng ᬅᬕᭃᬂ and jöng  ᬚᭃᬂ

**Comment by r12a** [comment]
fwiw, i'm seeing the same problem with Noto Serif Balinese.

![Screenshot 2020-11-17 at 14 56 13](https://user-images.githubusercontent.com/4839211/99405811-129f8c80-28e5-11eb-84ea-4e528d82e8be.png)

**Comment by nizarsq** [comment]
<img width="857" alt="Screen Shot 2020-11-17 at 9 08 49 PM" src="https://user-images.githubusercontent.com/22158882/99486473-18af6080-2919-11eb-91c0-12d9501e45cb.png">

**Comment by marekjez86** [comment]
@mahalisyarifuddin : please check out https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf/NotoSansBalinese ... should be fixed

**Comment by mahalisyarifuddin** [comment]
It's fixed now. Thank you!

I'm closing the issues.
