### ISSUE TITLE
Noto Sans KR Can not render ellipsis in IE11

### ISSUE THREAD

**Issue by fullmetal2000** [googlefonts/noto-fonts#1920]
### Title
   Noto Sans KR Can not render ellipsis in IE11
### Font 
  Noto Sans KR
  
### Font Version
Version 1.004;PS 1.004;hotconv 1.0.82;makeotf.lib2.5.63406

### Issue
  In IE11, when we add below CSS code, we found when the text is overflowed, the text can be truncated, however the ellipsis not showing, this issue only happens in IE11, Chrome and FireFox are ok.
{
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
 Expected result: the ellipsis (...) should be shown when text is overflowed.

### Screenshot
![image](https://user-images.githubusercontent.com/2509104/99740832-9b086380-2a84-11eb-8326-4aaeb7d2b37c.png)

**Comment by nizarsq** [comment]
I don't think this is a font issue. It could be placeholder issue/feature not exist. How about other fonys? Will you see the ellipsis?

**Comment by fullmetal2000** [comment]
Yes if I change to other fonts it will work, like Roboto, only Noto Sans KR
has this issue.

**Comment by fullmetal2000** [comment]
Can u help to reproduce in your end? It’s very easy, just use Noto Sans KR
render in IE 11, then do the text overflow : ellipsis.

**Comment by fullmetal2000** [comment]
The Noto Sans KR version we are using is from 1985, btw. I saw latest version is from 2018, is there any big difference?

**Comment by nizarsq** [comment]
Please use latest version. Fonts can be found here 
https://github.com/googlefonts/noto-fonts

**Comment by fullmetal2000** [comment]
Thank you @nizarsq  we will try and let u know.

**Comment by fullmetal2000** [comment]
It turns out to be the segments issue, we split the woff files into 91 small segments to improve download performance, and each one in charge of a certain range of unicode, and the ellipsis note (dot dot dot)  whose uni code is U+2026 is in one of the segment, but not the first segment, after we move it to the first segment, the issue resolved. But we still don't know why the segments break this.

**Comment by nizarsq** [comment]
@fullmetal2000 do we need to keep this issue open?

**Comment by fullmetal2000** [comment]
no, pls close this issue, thank you so much!

**Comment by nizarsq** [comment]
Thank you
