### ISSUE TITLE
We hardly need a compact Old Hungarian font for ui, according the standard form (downloadable from http://unicode.org/charts)

### ISSUE THREAD

**Issue by Kixidevel** [googlefonts/noto-fonts#1921]
We hardly need a compact Old Hungarian font for UI, without any ligatures. Ligatures are useful for text editors only.  Must to follow and only follow  the unicode standard form. Document about it downloadable from page 
http://unicode.org/charts
This ui font might to include ltr version of the glyphs, because of that, it signed as, unfortunatelly, right-to-left "dominant" script.
I attach the copy of the document, which must to follow,  and downloaded from page 
http://unicode.org/charts
Here is the doc.:
[U10C80.pdf](https://github.com/googlefonts/noto-fonts/files/5592974/U10C80.pdf)

**Comment by Kixidevel** [comment]
@marekjez86 
May I ask you to sign it as "new features" and "Old Hungarian script"?

**Comment by Kixidevel** [comment]
@marekjez86 
The full path of the document, which we need follow only, is http://unicode.org/charts/PDF/U10C80.pdf

**Comment by Kixidevel** [comment]
@google-admin @marekjez86 I already made the font and uploaded to noto-source project, and  I created a PR.
In the future, font source named NotoOldHungarianUI.glyphs and its binary compilation nobody change, please (I think about, for example, David Corbett request, which is doesn't follow the UNICODE standard), except the standard forms changed (now the document downloadable from page http://unicode.org/charts/PDF/U10C80.pdf )
Because of that the NotoOldHungarianUI font was developed for UI, and simple UI doesn't use ligatures, (for example terminals) nobody add ligatures to it. It made for UI only with compact size. 
If someone want to use ligatures, use the NotoSansOldHungarian-Regular font: 
https://github.com/googlefonts/noto-fonts/blob/4900c576b35342f5d4a8ff109c7efb80fb3b8fb9/unhinted/ttf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf 
Pointless to extending with ligatures the UI font, because of that, NotoOldHungarianUI font source derived from 
https://github.com/googlefonts/noto-fonts/blob/4900c576b35342f5d4a8ff109c7efb80fb3b8fb9/unhinted/ttf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf  font, except the Old Hungarian numbers' size is capital-like. ZWJ and ligatures where removed.
Thank You!

**Comment by acszoltan** [comment]
@marekjez86 Marek, I think, it's real demand. There are another native script's for UI in compact form.

**Comment by marekjez86** [comment]
Feel free to post the font anywhere you want to (e.g., on your own github) as long as it is licensed properly (see https://github.com/googlefonts/noto-fonts/blob/master/LICENSE ) and NOT named Noto <something>... 
Noto will not use this pull request.

**Comment by Kixidevel** [comment]
@marekjez86 Marek, only the license text wrong? I will resolve it, and as you ask, rename it!

**Comment by Kixidevel** [comment]
@marekjez86 Marek, we still have a need!

**Comment by Kixidevel** [comment]
@marekjez86 Marek, the Old Hungarian script doesn't need ligatures. The lugatures are only possibilities
