### ISSUE TITLE
Noto Sans Chakma font needs to include U+011147

### ISSUE THREAD

**Issue by sven-oly** [googlefonts/noto-fonts#1922]
### Title 
Noto Sans Chakma font needs to include U+011147
### Font 
NotoSansChakma-Regular.ttf

### Where the font came from, and when
https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf/NotoSansChakma
Downloaded today 26-Nov-2020. I verified that the font does not include this character which has been added to Unicode

### Font Version
2.001; ttfautohint (v1.8.2)
2.00101

### OS name and version
The font in this repository does not yet have this character.

### Application name and version
FontForge 
### Issue
 Noto Sans Chakma font does not include U+011147, which was added to the Unicode standard. This is CHAKMA LETTER VAA used in Pali text. This was downloaded from
[Google noto-fonts Chakma](https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf/NotoSansChakma). I verified that this version of font does not include this character.

  1. Steps to reproduce
* Down load the font
* Open the font in FontForge
  2. Observed results
* Note that code point 11147 is empty
  3. Expected results
I expect that the font will contain the character, similar to that shown in the attached image.
  4. Additional information 
http://unicode.org/charts/PDF/U11100.pdf
![image](https://user-images.githubusercontent.com/10751250/100389726-000f0c80-2fe3-11eb-94ef-46f6e30cf524.png)

### Character data
𑄠𑄓𑄛𑅇
011120 011113 01111B 011147

### Screenshot
The second image below includes the character as shown in Ribeng Uni font from 2020.

## Tools for reporting bugs
  Useful tools for reporting bugs are available at: https://github.com/googlei18n/

This is the image in the Unicode standard for this codepoint.
![image](https://user-images.githubusercontent.com/10751250/100389447-39934800-2fe2-11eb-95c3-55628f9f998c.png)

![image](https://user-images.githubusercontent.com/10751250/100389736-08674780-2fe3-11eb-81c4-05f667e70d37.png)

**Comment by nizarsq** [comment]
![Screenshot_20201126-133938_Chrome](https://user-images.githubusercontent.com/22158882/100393137-80d30600-2fed-11eb-8405-984b368d7865.jpg)

**Comment by sven-oly** [comment]
The shape should probably be just like BAA (U+1111D) but with the bar across.

Here's the Ribeng Uni font as shown here: http://languagetools-153419.appspot.com/ccp/
for code points: 01110B 011121 011147 01111B 01111D 

![image](https://user-images.githubusercontent.com/10751250/100396873-c8608e80-2ffb-11eb-8d13-3071b3af227d.png)

And for comparison  with Noto Sans Chakma:
![image](https://user-images.githubusercontent.com/10751250/100396890-ec23d480-2ffb-11eb-9b19-f42665bb8d2c.png)

**Comment by punchcutter** [comment]
I added it to Noto about two years ago since I'm the one who got it added to Unicode, but I guess never got it into the release version. I have other fixes also so I'll send a PR soon.

**Comment by sven-oly** [comment]
Thank you. It would be great to get this into release!

**Comment by Bivuti** [comment]
@sven-oly Thanks for open this issue for Chakma character of VAA! My RibengUni font well rendering as shown in screenshot.
![Screenshot_20201211-140615](https://user-images.githubusercontent.com/13092086/101880607-66885300-3bbd-11eb-895d-576889d7731f.png)

@punchcutter I hope you are aware about the issues specially character shaping of this script.

**Comment by punchcutter** [comment]
Addressed in latest update

<img width="101" alt="chakma1922" src="https://user-images.githubusercontent.com/11257204/132978840-a1f70b82-f6fd-4e64-838b-e0200cf485b7.png">

**Comment by marekjez86** [comment]
Source code change https://github.com/googlefonts/noto-source/pull/402 fixed the issue. Please see hinted font at https://github.com/googlefonts/noto-fonts/tree/main/hinted/ttf/NotoSansChakma or unhinted at https://github.com/googlefonts/noto-fonts/tree/main/unhinted/ttf/NotoSansChakma . Thank you @punchcutter
