### ISSUE TITLE
Arabic Presentation Forms-A will not render initial, medial or final forms

### ISSUE THREAD

**Issue by nizarsq** [googlefonts/noto-fonts#1927]
NotoSansArabic, NotoSansArabicUI, NotoNaskhArabic and NotoNaskhArabicUI will render only isolated form for letters that have two or more forms in [Arabic Presentation Forms-A](https://unicode.org/charts/PDF/UFB50.pdf)

Note: NotoKufiArabic and NotoNastaliqUrdu does not have Arabic Presentation Forms-A glyphs in the font.

List of codepoints that have two or more forms (INITIAL,MEDIAL,ISOLATED,FINAL):
FB50 FB52 FB56 FB5A FB5E FB62 FB66 FB6A FB6E FB72 FB76 FB7A FB7E FB88 FB8A FB8C FB8E FB92 FB96 FB9A FB9E FBA0 FBA4 FBA6 FBAA FBAE FBB0 FBD3 FBD7 FBD9 FBDB FBE0 FBE2 FBE4 FBEA FBEE FBF0 FBF4 FBF6 FBF9 FBFC FC0F FC1F FC00 FC01 FC02 FC03 FC04 FC05 FC06 FC07 FC08 FC09 FC0A FC0B FC0C FC0D FC0E FC0F FC10 FC11 FC12 FC13 FC14 FC15 FC16 FC17 FC18 FC19 FC1A FC1B FC1C FC1D FC1E FC1F FC20 FC21 FC22 FC23 FC24 FC25 FC26 FC27 FC28 FC29 FC2A FC2B FC2C FC2D FC2E FC2F FC30 FC31 FC32 FC33 FC34 FC35 FC36 FC37 FC38 FC39 FC3A FC3B FC3C FC3D FC3E FC3F FC40 FC41 FC42 FC43 FC44 FC45 FC46 FC47 FC48 FC49 FC4A FC4B FC4C FC4D FC4E FC4F FC50 FC51 FC52 FC53 FC54 FC55 FC56 FC57 FC58 FC59 FC5A FC5B FC5C FC5D FCF5 FCF6 FCF7 FCF8 FCF9 FCFA FCFB FCFC FCFD FCFE FCFF FD00 FD01 FD02 FD03 FD04 FD05 FD06 FD07 FD08 FD09 FD0A FD0B FD0C FD0D FD0E FD0F FD10 FD3D

ﭐ ﭒ ﭖ ﭚ ﭞ ﭢ ﭦ ﭪ ﭮ ﭲ ﭶ ﭺ ﭾ ﮈ ﮊ ﮌ ﮎ ﮒ ﮖ ﮚ ﮞ ﮠ ﮤ ﮦ ﮪ ﮮ ﮰ ﯓ ﯗ ﯙ ﯛ ﯠ ﯢ ﯤ ﯪ ﯮ ﯰ ﯴ ﯶ ﯹ ﯼ ﰏ ﰟ ﰀ ﰁ ﰂ ﰃ ﰄ ﰅ ﰆ ﰇ ﰈ ﰉ ﰊ ﰋ ﰌ ﰍ ﰎ ﰏ ﰐ ﰑ ﰒ ﰓ ﰔ ﰕ ﰖ ﰗ ﰘ ﰙ ﰚ ﰛ ﰜ ﰝ ﰞ ﰟ ﰠ ﰡ ﰢ ﰣ ﰤ ﰥ ﰦ ﰧ ﰨ ﰩ ﰪ ﰫ ﰬ ﰭ ﰮ ﰯ ﰰ ﰱ ﰲ ﰳ ﰴ ﰵ ﰶ ﰷ ﰸ ﰹ ﰺ ﰻ ﰼ ﰽ ﰾ ﰿ ﱀ ﱁ ﱂ ﱃ ﱄ ﱅ ﱆ ﱇ ﱈ ﱉ ﱊ ﱋ ﱌ ﱍ ﱎ ﱏ ﱐ ﱑ ﱒ ﱓ ﱔ ﱕ ﱖ ﱗ ﱘ ﱙ ﱚ ﱛ ﱜ ﱝ ﳵ ﳶ ﳷ ﳸ ﳹ ﳺ ﳻ ﳼ ﳽ ﳾ ﳿ ﴀ ﴁ ﴂ ﴃ ﴄ ﴅ ﴆ ﴇ ﴈ ﴉ ﴊ ﴋ ﴌ ﴍ ﴎ ﴏ ﴐ ﴽ

**Comment by khaledhosny** [comment]
This is expected, Arabic Presentation Forms are not shaped by OpenType layout engines and any one using them is expected to shape (select the positional forms) on its own.

**Comment by khaledhosny** [comment]
(That is of course because they are a legacy thing, modern fonts should not support these code points at all)

**Comment by nizarsq** [comment]
> This is expected, Arabic Presentation Forms are not shaped by OpenType layout engines and any one using them is expected to shape (select the positional forms) on its own.

That's something will surprise me. I looked at some other 3rd parties fonts and they shape mentioned codepoints.
<img width="1004" alt="Screen Shot 2020-12-14 at 12 31 32 PM" src="https://user-images.githubusercontent.com/22158882/102132309-4f897100-3e08-11eb-894c-7e6a7023db9a.png">

**Comment by khaledhosny** [comment]
What is the input string and the fonts you are checking?

**Comment by nizarsq** [comment]
> What is the input string and the fonts you are checking?
FB52 FB56 FB5A FB5E (ﭒ ﭒﭒﭒ ﭖ ﭖﭖﭖ ﭚ ﭚﭚﭚ ﭞ ﭞﭞﭞ)
Arial and Courier New

**Comment by khaledhosny** [comment]
I can’t reproduce your result with any versions I have of these fonts. I can’t actually find any Arabic font that gives a similar result, including fonts shipped with macOS and Windows.

**Comment by nizarsq** [comment]
<img width="1077" alt="Screen Shot 2020-12-15 at 6 05 52 PM" src="https://user-images.githubusercontent.com/22158882/102295442-2d731a00-3f00-11eb-85b0-a7dc7f4f887e.png">
<img width="1081" alt="Screen Shot 2020-12-15 at 6 06 32 PM" src="https://user-images.githubusercontent.com/22158882/102295489-45e33480-3f00-11eb-9323-45de227478a3.png">

**Comment by khaledhosny** [comment]
I still can’t get the results you are getting:
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/93914/102354255-fdd11a00-3fb2-11eb-832b-ffe71cc1fbc4.png">

**Comment by marekjez86** [comment]
My Mac is 10.15.7... I seem to get the same results as Nizar ..

Arial using text edit on my Mac
<img width="999" alt="Screen Shot 2020-12-16 at 06 02 00" src="https://user-images.githubusercontent.com/13322623/102358863-dfdcc880-3f64-11eb-8a33-2c3a9f83c454.png">

Courier New using text edit
<img width="1363" alt="Screen Shot 2020-12-16 at 06 05 03" src="https://user-images.githubusercontent.com/13322623/102358844-d9e6e780-3f64-11eb-93d4-c7eb9ca2b2dd.png">

**Comment by khaledhosny** [comment]
No idea what is going on this, either the fonts you have are different or the text get normalized somewhere.

**Comment by marekjez86** [comment]
@khaledhosny @nizarsq : Khaled you might be right... I think text edit is doing something...
when I execute hb-view itself on the same Arial font
hb-view --output-file=ara.png /System/Library/Fonts/Supplemental/Arial.ttf "ﭒ ﭒﭒﭒ ﭖ ﭖﭖﭖ "
I obtain

![ara](https://user-images.githubusercontent.com/13322623/102385983-5a1c4580-3f83-11eb-96ab-24a7353de66a.png)

which is the same as you did

**Comment by nizarsq** [comment]
Closing as WAI at this point.
