### ISSUE TITLE
ⱥ (U+2C65) and ɇ (U+0247) slashes are too long

### ISSUE THREAD

**Issue by KazunariTsuboi** [googlefonts/noto-fonts#1934]
### Font 
Noto {Sans,Serif,SansMono}

### Where the font came from, and when
NotoSans-Regular.ttf 2020/11/3 9:59:44 dfce577e728ad17923d9a29aa74504dddf0e0850
NotoSerif-Regular.ttf 2020/11/3 10:01:24 6ba677cc02c344448ad3244c59e699de651d978c
NotoSansMono-Regular.ttf 2020/11/6 8:57:35 382aab650a8f15715cd1723237a5dfd87078e11b

### OS name and version
Windows 10, 1909

### Application name and version
Google Chrome 87.0.4280.66 (Official Build) (64 bit)

### Issue
A friend of mine, who is a Mazahua native, states that the design of the slash in ⱥ (U+2C65) and ɇ (U+0247) is not desirable. 
The Mazahua language also uses ꞹ (U+A7B9). In Noto, the slash for ꞹ (U+A7B9) is adjusted and very easy to distinguish.
Please refer to the following screenshot, comparing each length of slashes.
![image](https://user-images.githubusercontent.com/21096794/101450774-66dedf00-396e-11eb-9a13-e9d4b89b13d4.png)

It is hoped that the length of slash for ⱥ (U+2C65) and ɇ (U+0247) could be the same as the length of the slash for ø (U+00F8) and ꞹ (U+A7B9)

### Character data
U+2C65　ⱥ
U+0247　ɇ

### Screenshot
![image](https://user-images.githubusercontent.com/21096794/101451575-b245bd00-396f-11eb-8bf6-b1c24bdaacb0.png)

**Comment by fitojb** [comment]
These letters need to be designed as a single set. I can see that ⟨ȺⱥɆɇ⟩ have their slash at one angle, ⟨Øø⟩ has it at another angle and ⟨Ꞹꞹ⟩ at yet another one.

**Comment by nizarsq** [comment]
@KazunariTsuboi this should be quick fix. Any concern about the capital letters slashes slanting? Looks to me they need to be consistent. @marekjez86 for opinion.

**Comment by fitojb** [comment]
@nizarsq I’m not @KazunariTsuboi so sorry for jumping in, but yes, the capital letters should also be amended to have harmonized slashes.

**Comment by KazunariTsuboi** [comment]
@nizarsq @fitojb   I'm sorry for the late reply. I think too,  I also need consistency.

I asked a type designer near me who is design about Mazahua fonts. He said too, "It is good that the slashes are in harmony."
