### ISSUE TITLE
Lam and alef presentation forms should not ligate

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1941]
### Fonts
NotoNaskhArabic-Regular.otf
NotoSansArabic-Regular.ttf

### Where the fonts came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/c4d511aa5c09a1d17b8fb809be4a7f07817ea35c/unhinted/otf/NotoNaskhArabic/NotoNaskhArabic-Regular.otf
Site: https://github.com/googlefonts/noto-fonts/blob/c4d511aa5c09a1d17b8fb809be4a7f07817ea35c/hinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf
Date: 2020-12-15

### Font versions
Noto Naskh Arabic: Version 2.003
Noto Sans Arabic: Version 2.004

### Issue
Arabic presentation forms represent specific glyphs that are immune to contextual shaping. When a lam presentation form precedes an alef presentation form, they should not be ligated. To get a lam–alef ligature using presentation forms, you should use a character like U+FEFB ARABIC LIGATURE LAM WITH ALEF ISOLATED FORM.

### Character data
U+FEDF ARABIC LETTER LAM INITIAL FORM
U+FB51 ARABIC LETTER ALEF WASLA FINAL FORM
U+FEDF ARABIC LETTER LAM INITIAL FORM
U+FE82 ARABIC LETTER ALEF WITH MADDA ABOVE FINAL FORM
U+FEDF ARABIC LETTER LAM INITIAL FORM
U+FE84 ARABIC LETTER ALEF WITH HAMZA ABOVE FINAL FORM
U+FEDF ARABIC LETTER LAM INITIAL FORM
U+FE88 ARABIC LETTER ALEF WITH HAMZA BELOW FINAL FORM
U+FEDF ARABIC LETTER LAM INITIAL FORM
U+FE8E ARABIC LETTER ALEF FINAL FORM
U+FEE0 ARABIC LETTER LAM MEDIAL FORM
U+FB51 ARABIC LETTER ALEF WASLA FINAL FORM
U+FEE0 ARABIC LETTER LAM MEDIAL FORM
U+FE82 ARABIC LETTER ALEF WITH MADDA ABOVE FINAL FORM
U+FEE0 ARABIC LETTER LAM MEDIAL FORM
U+FE84 ARABIC LETTER ALEF WITH HAMZA ABOVE FINAL FORM
U+FEE0 ARABIC LETTER LAM MEDIAL FORM
U+FE88 ARABIC LETTER ALEF WITH HAMZA BELOW FINAL FORM
U+FEE0 ARABIC LETTER LAM MEDIAL FORM
U+FE8E ARABIC LETTER ALEF FINAL FORM

### Screenshot
![ﻟﭑﻟﺂﻟﺄﻟﺈﻟﺎﻠﭑﻠﺂﻠﺄﻠﺈﻠﺎ](https://user-images.githubusercontent.com/1124347/102230622-1eb64400-3ebb-11eb-9f58-41489c5b69e0.png)
![ﻟﭑﻟﺂﻟﺄﻟﺈﻟﺎﻠﭑﻠﺂﻠﺄﻠﺈﻠﺎ](https://user-images.githubusercontent.com/1124347/102232343-fcbdc100-3ebc-11eb-9549-9010e21093d0.png)

**Comment by nizarsq** [comment]
NotoNaskhArabic still need fix

**Comment by dscorbett** [comment]
With 'dlig' enabled, there are still two erroneous ligatures left in [Noto Naskh Arabic 2.007](https://github.com/googlefonts/noto-fonts/blob/ef77d955940fee12787528ad5460e75db6dd801b/unhinted/otf/NotoNaskhArabic/NotoNaskhArabic-Regular.otf): <U+FEDF, U+FB51> and <U+FEE0, U+FB51>.

**Comment by nizarsq** [comment]
> FB51

I have no I idea why 'dlig' enabled for those 2 combinations. Issue fixed in Version 2.008
