### ISSUE TITLE
Muddled masters for Rashi U+05B5 HEBREW POINT TSERE

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1942]
### Fonts
NotoRashiHebrew-Regular.ttf

### Where the fonts came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/c4d511aa5c09a1d17b8fb809be4a7f07817ea35c/hinted/ttf/NotoRashiHebrew/NotoRashiHebrew-Regular.ttf
Date: 2020-12-16

### Font versions
Version 1.001; ttfautohint (v1.8.2)

### Issue
The left dot of U+05B5 HEBREW POINT TSERE in the lightest master corresponds to the right dot of U+05B5 HEBREW POINT TSERE in the heaviest master, so intermediate interpolated instances have the two dots too close together or overlapping.

### Character data
עֵ
U+05E2 HEBREW LETTER AYIN
U+05B5 HEBREW POINT TSERE

### Screenshot
![עֵ](https://user-images.githubusercontent.com/1124347/102413179-8a370900-3fc2-11eb-9749-4b4e3b58f0bd.png)

**Comment by nizarsq** [comment]
Issue reproducible
<img width="638" alt="Screen Shot 2020-12-19 at 7 06 18 PM" src="https://user-images.githubusercontent.com/22158882/102704212-47c53480-422d-11eb-9c20-5a61f767fdac.png">
