### ISSUE TITLE
NotoSansOldHungarian-Regular font has a developer-know-what-is-it form of ligature "szt"

### ISSUE THREAD

**Issue by tamasbartos** [googlefonts/noto-fonts#1945]
## Defect Report
https://github.com/googlefonts/noto-fonts/blob/master/unhinted/ttf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf font, version 2.002 have a ligature "szt" with non-known form.
### Font 
'NotoSanOldHungarian-Regular.ttf'.

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/master/unhinted/ttf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf font, version 2.002    
 Date: 2020-12-18
### Application name and version
  LibreOffice 6.4.6.2 (Known bug: CTL language must be set as "none") with keyboard layout named "Old-Hungarian"
 (within the extras)
### Issue
  The form of ligature "szt" unknown, unreadable. It looks like that it would be ligature "tj"
The problem is given LTR form of ligature "szt" , too. 
  Please:
Remove it completely or
Reuse as ligature "tj" (uni10CE6 + uni10CD2)
### Character data
Unicode codepoints: uni10CE5 + uni10CE6 (named :uni10CE5_10CE6)
### Screenshot
(the screenshot use RTL form of ligature, as usual) 
![unknown, unreadable ligature "sz"](https://user-images.githubusercontent.com/75836867/102593467-35f06e00-4115-11eb-884f-a0a89a3ed116.jpg)

**Comment by tamasbartos** [comment]
@marekjez86 This ligature does not comply with any Old Hungarian ligature displaying rules, and  it isn't possible to make another form of "szt".
Only in this case I suggest, let's remove this "ligature"! 
@marekjez86 Marek, I work on UI version of Old Hungarian font. After that I would be working on the ligatured version, but I can't work with original type of source code. I must to transform to ufo+ designspace form from the original NotoSansOldHungarian font's source code.
May I?

**Comment by tamasbartos** [comment]
@marekjez86 There are several infos and attempts to resolve problems.
The implemented "szt" ligature looks like as the first letter would be Old Hungarian letter "t", and the second unknown:
![Implemented "szt" looks like as the first letter would be "t"](https://user-images.githubusercontent.com/75836867/103167040-0550b880-4828-11eb-9bd3-1b578f26e98c.jpg)
I tried to resolve the problem, with mirrored form of "t": (It's allowed by Old Hungarian ligature form rules)
![First attempt to resolve problem](https://user-images.githubusercontent.com/75836867/103167114-89a33b80-4828-11eb-9d4f-3372d549602c.jpg)
As you see, it wasn't better.
I tried again, with mirrored form of "t":
![Second attempt to resolve problem](https://user-images.githubusercontent.com/75836867/103167180-354c8b80-4829-11eb-8d8b-9d550b23fac2.jpg)
As you see, it wasn't better, too.
Conclusion: The ligature Old Hungarian "szt" is unimplementable with normal "t" and mirrored "t", too.
My suggestion: This ligature must be removed, because of that it's unimplementable as clearly readable ligature, has no meanings and it isn't a syllable like ligature, just an experimental ligature.

**Comment by tamasbartos** [comment]
@marekjez86 I left and never go back!

**Comment by rovasinfo** [comment]
This ligature is on the (wish)list of the 2009 agreement. @tamasbartos has created correct glyph.
![agreement 2009p2](https://user-images.githubusercontent.com/81823602/113519148-c0f15900-958a-11eb-85db-a5e34d1d7e3a.jpg)

Source:
![szt](https://user-images.githubusercontent.com/81823602/113519263-5987d900-958b-11eb-8a0a-08070306ff9e.JPG)
