### ISSUE TITLE
Understanding font versioning and updates in the last 6 months

### ISSUE THREAD

**Issue by kmuncie** [googlefonts/noto-fonts#1948]
@marekjez86 thank you and the team for all the hard work the last few months! It is clear good things are happening and progress is being made on the the processes to update fonts more easily. 

It would be helpful if I could get some clarification on the work going on right now and releases happening to Noto Sans since the restructure of phaseIII_only directory. I will focus solely on the [hinted NotoSans-Regular.ttf font](https://github.com/googlefonts/noto-fonts/commits/26d1e1e7f7845761440835096db8a6b1b92fc1ad/phaseIII_only/hinted/ttf/NotoSans/NotoSans-Regular.ttf).

Font metadata reported the following as of June 11th, 2020 ([012fbeb01b80f862b2167ac8fe36aaed11ce5573](https://github.com/googlefonts/noto-fonts/blob/012fbeb01b80f862b2167ac8fe36aaed11ce5573/phaseIII_only/hinted/ttf/NotoSans/NotoSans-Regular.ttf))

```
Family:              Noto Sans
Subfamily:           Regular
Full name:           Noto Sans Regular
PostScript name:     NotoSans-Regular
Version:             Version 2.003; ttfautohint (v1.8.2)
Unique ID:           2.003;GOOG;NotoSans-Regular
Description:         Designed by Monotype design team.
Designer:            Monotype Design Team
Designer URL:        http://www.monotype.com/studio
Manufacturer:        Monotype Imaging Inc.
Vendor URL:          http://www.google.com/get/noto/
Trademark:           Noto is a trademark of Google LLC
Copyright:           Copyright 2019 Google LLC. All Rights Reserved.
License URL:         http://scripts.sil.org/OFL
License Description: This Font Software is licensed under the SIL Open Font License, Version 1.1. This Font Software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the SIL Open Font License for the specific language, permissions and limitations governing your use of this Font Software.
Vendor ID:           GOOG
```

The next time NotoSans-Regular.ttf was changed was on June 25, 2020 ([b7086582d72f537474b61285a81e0d30a250bcfa](https://github.com/googlefonts/noto-fonts/blob/b7086582d72f537474b61285a81e0d30a250bcfa/phaseIII_only/hinted/ttf/NotoSans/NotoSans-Regular.ttf)) and the metadata changed to the following (note the change to Copyright and ttfautohint version)

```
Family:              Noto Sans
Subfamily:           Regular
Full name:           Noto Sans Regular
PostScript name:     NotoSans-Regular
Version:             Version 2.003; ttfautohint (v1.8.3)
Unique ID:           2.003;GOOG;NotoSans-Regular
Description:         Designed by Monotype design team.
Designer:            Monotype Design Team
Designer URL:        http://www.monotype.com/studio
Manufacturer:        Monotype Imaging Inc.
Vendor URL:          http://www.google.com/get/noto/
Trademark:           Noto is a trademark of Google Inc.
Copyright:           Copyright 2015 Google Inc. All Rights Reserved.
License URL:         http://scripts.sil.org/OFL
License Description: This Font Software is licensed under the SIL Open Font License, Version 1.1. This Font Software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the SIL Open Font License for the specific language, permissions and limitations governing your use of this Font Software.
Vendor ID:           GOOG
```

The [latest tagged release published on Dec 6th, 2020](https://github.com/googlefonts/noto-fonts/releases/tag/v20201206-phase3) reports the following (note the version number is the same but lacks the ttfautohint inclusion)

```
Family:              Noto Sans
Subfamily:           Regular
Full name:           Noto Sans Regular
PostScript name:     NotoSans-Regular
Version:             Version 2.003
Unique ID:           2.003;GOOG;NotoSans-Regular
Description:         Designed by Monotype design team.
Designer:            Monotype Design Team
Designer URL:        http://www.monotype.com/studio
Manufacturer:        Monotype Imaging Inc.
Vendor URL:          http://www.google.com/get/noto/
Trademark:           Noto is a trademark of Google Inc.
Copyright:           Copyright 2015 Google Inc. All Rights Reserved.
License URL:         http://scripts.sil.org/OFL
License Description: This Font Software is licensed under the SIL Open Font License, Version 1.1. This Font Software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the SIL Open Font License for the specific language, permissions and limitations governing your use of this Font Software.
Vendor ID:           GOOG
```
I want to get the latest font which contains fixes such as https://github.com/googlefonts/noto-fonts/issues/1051#issuecomment-720817327. However, the older copyright date makes me worried that the latest font could contain regressions.

**Is the latest tagged release on Dec 6th, 2020 an upgraded version of what was in phaseIII_only hinted directory on June 11th, 2020?**

Any clarification to when font version numbers are changed would be helpful so that I can version updates in my system even if the font does not report a version number change.

**Comment by marekjez86** [comment]
@kmuncie : related issue: https://github.com/googlefonts/noto-fonts/issues/1956 (I had problem with the updating scripts for a while and I didn't notice it)... version should be updated when there's a source change (we might have been lax with it because of the "people transition"), but it will be corrected. Note that if a font is just recompiled with no source change then we will not update the font version.
