### ISSUE TITLE
Inverted three dots on many Arabic letters

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1957]
### Font
NotoSansArabic-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/3599b1bb31ae94e7091f270b60c5f7c1c00f8ad5/unhinted/otf/NotoSansArabic/NotoSansArabic-Regular.otf
Date: 2020-12-25

### Font version
Version 2.005

### Issue
On many Arabic letters with three dots below, the dots point upwards, but they should point downwards.

### Character data
ؼپڛڜڮڸۑࢷ
U+063C ARABIC LETTER KEHEH WITH THREE DOTS BELOW
U+067E ARABIC LETTER PEH
U+069B ARABIC LETTER SEEN WITH THREE DOTS BELOW
U+069C ARABIC LETTER SEEN WITH THREE DOTS BELOW AND THREE DOTS ABOVE
U+06AE ARABIC LETTER KAF WITH THREE DOTS BELOW
U+06B8 ARABIC LETTER LAM WITH THREE DOTS BELOW
U+06D1 ARABIC LETTER YEH WITH THREE DOTS BELOW
U+08B7 ARABIC LETTER PEH WITH SMALL MEEM ABOVE

### Screenshot
![ؼؼؼ ؼ پپپ پ ڛڛڛ ڛ ڜڜڜ ڜ ڮڮڮ ڮ ڸڸڸ ڸ ۑۑۑ ۑ ࢷࢷࢷ ࢷ](https://user-images.githubusercontent.com/1124347/103137311-e6222180-4695-11eb-926a-62832fcc9fbb.png)

**Comment by nizarsq** [comment]
This issue ntreduced after fixing https://github.com/googlefonts/noto-fonts/issues/1192. Apparently they used 
U+FBB7 ARABIC SYMBOL THREE DOTS BELOW and U+FBB9 ARABIC SYMBOL THREE DOTS POINTING DOWNWARDS BELOW  when they were swapped.

**Comment by mhf-ir** [comment]
seems all characters like `پ`, `چ`.
 its very common character for example in persian `پرچم` means Flag:

**Comment by ahangarha** [comment]
This is a big issue. When we would get new release? The latest release is dated as 2020-12-26.

**Comment by simoncozens** [comment]
Noto Sans Arabic 2.009 (dated November 2021) is available at https://github.com/googlefonts/noto-fonts/tree/main/hinted/ttf/NotoSansArabic
