### ISSUE TITLE
Diacritics/marks in NotoNaskhArabic fonts are regular weight when Bold weight used

### ISSUE THREAD

**Issue by nizarsq** [googlefonts/noto-fonts#1958]
Most Diacritics/marks in NotoNaskhArabic fonts are regular weight when using Bold weight. Below some of the Diacritics/marks that has only regular weight

<b>Characters used in the test:</b>
بُِ بٌ بٍّ بَْ بٞ بٝ بۤ بؗ بࣻ بۨ بۭ

<b>Screenshot:</b>
<img width="1344" alt="Screen Shot 2020-12-24 at 12 33 23 PM" src="https://user-images.githubusercontent.com/22158882/103105697-393b9c00-45e4-11eb-8c33-81cae8f0a8c9.png">

**Comment by nizarsq** [comment]
Adding to this list waqf signs

**Comment by nizarsq** [comment]
@marekjez86 for opinion

**Comment by marekjez86** [comment]
@khaledhosny  @moyogo : your advice would be very very welcome... We have discovered that diacritics and marks in Noto Naskh Arabic have only a single weight (Regular)... For contrast, Amiri or Noto Sans Arabic have diacritics and marks  that correspond to the weight. There are about 108 of these in Naskh that would need to get a Bold master. Should we do it? Please advise... I'm leaning toward asking Nizar to start working on these, but your advice if these should have multiple weights would be very very welcome

**Comment by moyogo** [comment]
DroidNaskh-Bold has bolder marks than DroidNaskh-Regular, so this was modified at some point since then.
I can't find a version of NotoNaskArabic-Bold with bolder marks.

We should be able to replace the NotoNaskArabic-Bold marks with those of DroidNaskh-Bold. Both are copyright of Google.

**Comment by khaledhosny** [comment]
If Droid Naskh has bold marks and Noto Naskh doesn't then the change might have been intentional (bolder marks being more crowded or requiring different font metrics), so it might be a good idea to try to track down someone who might know. Other than that, copying from Droid Naskh should be fine (I think some Quranic marks were wrong in Droid fonts and might have to be drawn again).

**Comment by twardoch** [comment]
I think Pascal Zoghbi worked on both Droid Naskh and Noto Naskh, perhaps he might know why this is so? 

https://www.29lt.com/bespoke-type/

**Comment by moyogo** [comment]
Indeed @29lt worked on Droid Naskh which became Noto Naskh which later became Noto Naskh Arabic. Maybe he knows why the marks from Droid Naskh Bold were replaced by the ones from Regular when Noto Naskh was created.

**Comment by 29LT** [comment]
Dear all, I have worked on the Droid Naskh font in 2010 and 2011. I worked on it with Ascenders Corp back then before they were owned by Monotype. Since then, I was not involved in the future developments of Noto. I do not have answers for the current Noto Arabic Naskh.

**Comment by moyogo** [comment]
Thanks for the quick reply @29LT !

**Comment by nizarsq** [comment]
Accidentally closed.

**Comment by nizarsq** [comment]
Hello everyone, Marks in NotoNaskhArabic/NotoNaskhArabicUI 2.012 are in bold weight. If there's any issue/issues please file individual bugs.
Thanks

**Comment by nizarsq** [comment]
Here test data:
 ــﹾــﹼــﹺــﹸــﹶــﹴــﹲــﹰــﱣــﱢــﱡــﱠــﱟــﱞــࣾــࣽــࣼــࣻــࣺــࣹــࣸــࣷــࣶــࣵــࣴــࣳــࣲــࣱــࣰــ࣯ــ࣮ــ࣭ــ࣬ــ࣫ــ࣪ــࣩــࣨــࣧـ
ـࣦــࣥــࣤــۭــ۬ــ۫ــ۪ــۨــۧــۤــۣــۢــۡــ۠ــ۟ــۜــۛــۚــۙــۘــۗــۖــٰــٟــٞــٝــٜــٛــٚــٙــ٘ــٗــٖــٕــٔــٓــْــّــِــُــَــٍــٌــًــؚــؙــؘـ
ـؗــؖــؕــؔــؓــؒــؑــؐــْٔــّٰــِٕــِّــُٔــُّــَٔــَّــٍٕــٍّــٌٔــٌّــًٔــًّ
