### ISSUE TITLE
Misplaced ijam in Noto Sans Arabic

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1959]
### Font
NotoSansArabic-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/3599b1bb31ae94e7091f270b60c5f7c1c00f8ad5/unhinted/otf/NotoSansArabic/NotoSansArabic-Regular.otf
Date: 2020-12-25

### Font version
Version 2.005

### Issue
The ijam above U+08A7, U+08B6, and U+08B7 are too high. The ijam below U+08B7 is too low and too far right.

### Character data
ࢧࢶࢷ
U+08A7 ARABIC LETTER MEEM WITH THREE DOTS ABOVE
U+08B6 ARABIC LETTER BEH WITH SMALL MEEM ABOVE
U+08B7 ARABIC LETTER PEH WITH SMALL MEEM ABOVE

### Screenshot
![ࢧࢶࢷ](https://user-images.githubusercontent.com/1124347/103137624-6f3a5800-4698-11eb-8213-c50edd8ce635.png)

**Comment by nizarsq** [comment]
<img width="1393" alt="Screen Shot 2020-12-26 at 9 18 45 PM" src="https://user-images.githubusercontent.com/22158882/103164426-f2a29900-47bf-11eb-82f0-098a5422576e.png">
