### ISSUE TITLE
NotoSans Regular Misaligned in new update

### ISSUE THREAD

**Issue by TheBabu** [googlefonts/noto-fonts#1960]
Font: NotoSans Regular
Arch Linux: noto-fonts 20201206-1
Application: Polybar

### Issue
I noticed I believe the newest update of noto-fonts created a small bug where the alignment of the font seems to be off. I thought it might've been the application at first, but when I downgraded noto-fonts to 20190926-4 to seems to look fine.

### Screenshot
What it should look like: 20190926-4
![Screenshot_2020-12-25_16-47-00](https://user-images.githubusercontent.com/24832107/103143375-f657f200-46d1-11eb-8a2e-a2e6ec95f477.png)

What it looks like now: 20201206-1
![Screenshot_2020-12-24_16-15-15](https://user-images.githubusercontent.com/24832107/103143373-ef30e400-46d1-11eb-8840-fa56ee96adf8.png)

Notice that the colon in the time is misaligned, and the "/" in the date is also misaligned. Additionally the percent sign looks fairly weird.

**Comment by marekjez86** [comment]
@TheBabu : 1. where did you get the Noto font(s) from? what were the file names? 2. does your system has a text edit like application or a note pad (where you can enter text and apply the font selection)? I wanted to ask you to copy the text in the above line (below is my attempt but I didn't have "o-slash") and apply the new Noto font to it and see how it looks like in your text edit-like app.

CATACOMBS by NOCTRIS 20% MARSwifi 192.168.86.32 56% 12/24/2020 04:15 PM

I suspect that your font stack is somewhat different after you install new Noto...

Why I feel this way?
percentage sign was never changed within the last 2-4 years and in Noto (recent and few years ago) it looks like this ... I don't see any issue with a percentage sign.

![Uploading Screen Shot 2020-12-25 at 8.25.40 PM.png…]()

**Comment by nizarsq** [comment]
I checked (/) SOLIDUS U+002F  and   (:) COLON U+003A and both looks ok in the latest NotoSans [Version 2.004](https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSans/NotoSans-Regular.ttf). I Couldn't reproduce the issue on either Linux/MAC using fontdiff or Chrome. I don't see these codepoints touched for sometime.

 <img width="818" alt="Screen Shot 2020-12-25 at 9 15 28 PM" src="https://user-images.githubusercontent.com/22158882/103145921-52347200-46f6-11eb-913c-69d2a7ca13ca.png">

**Comment by nizarsq** [comment]
I agree with @marekjez86. It look like there's another font involved in the second screenshot. (Notice the serif in the letter I) in NOCTRIS

**Comment by TheBabu** [comment]
Wait sorry, I didn't make that clear. There are other fonts going on here. I believe there is these fonts:
```
font-0 = NotoSans-Regular:size=10;1
font-1 = MaterialIcons:size=12;2
font-2 = Termsynu:size=10:antialias=false;0
font-3 = FontAwesome:size=12;2
```
From my polybar config (https://github.com/TheBabu/Config/blob/master/.config/polybar/config)

The reason why I know it using Notosans is that again when I downgraded Notosans it fixed the problem, additionally when I increase the font size fro Notosans it increases the size of the font that had the misaligned letters.

**Comment by TheBabu** [comment]
I went on another application called Mousepad, a text editor and changed the font to NotoSans Regular and it seems to have the same problem.

This is what the latest noto-fonts looks like:
![image](https://user-images.githubusercontent.com/24832107/103157807-3c659200-4774-11eb-9191-8cc85c29779b.png)

And this is how it looks like downgraded:
![image](https://user-images.githubusercontent.com/24832107/103157853-92d2d080-4774-11eb-870d-80ce272ebdb9.png)

**Comment by nizarsq** [comment]
Could be shaping engine issue. There's new build published on Dec 24 https://archlinux.org/packages/extra/x86_64/harfbuzz/

**Comment by TheBabu** [comment]
From what I can tell, downgraded harfbuzz does not seem to affect the issue at all. The font seems to be still misaligned. If the font themselves didn't change, did any other type of configuration happen in the newest update that could cause this?

**Comment by nizarsq** [comment]
Can you download this html test case https://drive.google.com/file/d/1H6L5ZsLR2F5ALAABJzDdnoSx204cHv-B/view?usp=sharing  and share a screenshot how it looks?

**Comment by TheBabu** [comment]
![image](https://user-images.githubusercontent.com/24832107/103161630-e7407500-47a1-11eb-84b1-b32d56c95182.png)

This is quite unusual, now I am thinking this might be an issue with the polybar application.

**Comment by nizarsq** [comment]
> ![image](https://user-images.githubusercontent.com/24832107/103161630-e7407500-47a1-11eb-84b1-b32d56c95182.png)
> 
> This is quite unusual, now I am thinking this might be an issue with the polybar application.
> 
> But now this begs the question, why does it only affect the notosans font? And why does downgrading it seem to fix the issue?

Could you download and install NotoSans using the github link (Link can be found in the test case) and if possible clear the app cache.

Thanks

**Comment by TheBabu** [comment]
It seems when installing the fonts provided by the links in the test cases that it seems to pass:
![image](https://user-images.githubusercontent.com/24832107/103176179-d4bf4d80-482c-11eb-9ee5-e1cbec9c3a73.png)

But one thing to note that is even though that the test case seems to work, the application does not seem to be affected in any way:
![image](https://user-images.githubusercontent.com/24832107/103176191-f4567600-482c-11eb-8d54-2e0293fd093e.png)
The ":" seems to be still misaligned.

One interesting thing to note is that before installing the fonts, I did the differences in the files and it seems that there seems latest Arch release of `noto-fonts` does not correlate to the release on github. This might be one cause for the issue. Additionally, another cause could be the issue of the polybar application itself.
![Screenshot_2020-12-27_10-15-16](https://user-images.githubusercontent.com/24832107/103176219-2ff14000-482d-11eb-94b3-1786c49b3569.png)

**Comment by bryanjhv** [comment]
Arch changes from 20190926-4 to 20201206-1: https://github.com/archlinux/svntogit-packages/commit/0c20ccf9f4209cdf73a991051a6d0210980d2476.

As you can see, they are using 20bc5918912503bc1537a407a694738c33c048aa (Dec 4, 2020, 7:56 PM GMT), maybe master fixes it?

**Comment by Athantor** [comment]
Yeah, it's application dependent. It's particularly annoying on firefox, where characters move around:

https://bugs.archlinux.org/task/68968 → see attached videos.

Which is „worked around” also by downgrading to `20190926-4`. 
Chromium seems to be unaffected.

> We are simply repackaging upstream provided TTFs. Please report any issues upstream.
:unamused: 

I've also noticed, that changing hinting level in plasma settings from „full” to „medium” makes it less visible.

**Comment by TheBabu** [comment]
Closing issue because a newest update of Arch Linux notosans fixed it?
