### ISSUE TITLE
Mispositioned U+06ED ARABIC SMALL LOW MEEM

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1961]
### Font
NotoSansArabic-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/2b1fbc36600ccd8becb9f894922f644bff2cbc9b/unhinted/otf/NotoSansArabic/NotoSansArabic-Regular.otf
Date: 2020-12-26

### Font version
Version 2.005

### Issue
U+06ED ARABIC SMALL LOW MEEM should go below the base, but in this font it goes above the base.

### Character data
لۭ
U+0644 ARABIC LETTER LAM
U+06ED ARABIC SMALL LOW MEEM

### Screenshot
![لۭ](https://user-images.githubusercontent.com/1124347/103156623-5e611380-4778-11eb-8b29-1bd87d242799.png)

**Comment by nizarsq** [comment]
<img width="1393" alt="Screen Shot 2020-12-26 at 9 10 47 PM" src="https://user-images.githubusercontent.com/22158882/103164338-d5b99600-47be-11eb-87e2-060747a67087.png">

**Comment by nizarsq** [comment]
Initial and medial need fix too <img width="1388" alt="Screen Shot 2021-01-03 at 1 45 05 PM" src="https://user-images.githubusercontent.com/22158882/103489517-e626cd80-4dc9-11eb-95e9-abe433df8e61.png">
