### ISSUE TITLE
Spacing ijam and tashkil are combining in Noto Sans Arabic

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1963]
### Font
NotoSansArabic-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/2b1fbc36600ccd8becb9f894922f644bff2cbc9b/unhinted/otf/NotoSansArabic/NotoSansArabic-Regular.otf
Date: 2020-12-26

### Font version
Version 2.005

### Issue
Some spacing ijam and tashkil have mark glyphs.

### Character data
ا﮼ا ا﯀ا اﱞا اﱟا اﱠا اﱡا اﱢا اﱣا
U+FBBC ARABIC SYMBOL DOUBLE VERTICAL BAR BELOW
U+FBC0 ARABIC SYMBOL SMALL TAH ABOVE
U+FC5E ARABIC LIGATURE SHADDA WITH DAMMATAN ISOLATED FORM
U+FC5F ARABIC LIGATURE SHADDA WITH KASRATAN ISOLATED FORM
U+FC60 ARABIC LIGATURE SHADDA WITH FATHA ISOLATED FORM
U+FC61 ARABIC LIGATURE SHADDA WITH DAMMA ISOLATED FORM
U+FC62 ARABIC LIGATURE SHADDA WITH KASRA ISOLATED FORM
U+FC63 ARABIC LIGATURE SHADDA WITH SUPERSCRIPT ALEF ISOLATED FORM

### Screenshot
Each character appears between two alefs to demonstrate the problem.
![ا﮼ا ا﯀ا اﱞا اﱟا اﱠا اﱡا اﱢا اﱣا](https://user-images.githubusercontent.com/1124347/103174518-d9860080-4830-11eb-8957-009f24d86b95.png)

**Comment by nizarsq** [comment]
@dscorbett are you referring to all codepoints you mentioned or U+FBBC and U+FBC0?

**Comment by dscorbett** [comment]
All of the code points I mentioned are rendered wrong. They should all be spacing.

**Comment by nizarsq** [comment]
Thanks. I agree they should be all spacing.  According to what I'm seeing at least NotoSansArabic fonts combining Nonspacing marks as components to create those glyphs( with exception to FBBC and FBC). Naskh fonts seems to have same issue.

**Comment by nizarsq** [comment]
This look better. NotoNaskhArabic not fixed yet
<img width="579" alt="Screen Shot 2021-01-10 at 9 05 53 PM" src="https://user-images.githubusercontent.com/22158882/104148576-a478c280-5387-11eb-87fb-75d17a435e6d.png">

**Comment by nizarsq** [comment]
NotoNaskhArabic still need fix
