### ISSUE TITLE
Noto Sans Arabic - problem when ya' plus Shadda plus Aleph plus Tanween

### ISSUE THREAD

**Issue by gerald-drissner** [googlefonts/noto-fonts#1965]
All Noto-Sans Arabic fonts:

![mistake_tashkeel](https://user-images.githubusercontent.com/16115672/103215901-f7c52c80-4914-11eb-8211-4bacf8051a59.png)

In the combination of certain letters, a space is added. This happens, for example, in the word شَهِيًّا - when ya' plus Shadda plus Aleph plus Tanween is added (and the Tanween is put before the Aleph as it is common in Egypt).

**Comment by nizarsq** [comment]
Thank you @gerald-drissner for filing this bug. I'm not able to reproduce the issue. Where did you get the font from? I belive this issue fixed some time ago. Could you try the font in this directory https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansArabic/.



<img width="1394" alt="Screen Shot 2020-12-28 at 10 54 34 AM" src="https://user-images.githubusercontent.com/22158882/103236933-14546b00-48fb-11eb-8a72-12343afc0d2d.png">

<img width="1062" alt="Screen Shot 2020-12-28 at 10 57 59 AM" src="https://user-images.githubusercontent.com/22158882/103237116-904eb300-48fb-11eb-911a-da59be26bc10.png">

**Comment by nizarsq** [comment]
I belive this related to https://github.com/googlefonts/noto-fonts/issues/1555

**Comment by gerald-drissner** [comment]
Thank you so much for your answer and work! Yes, it now works! I had installed the Noto Sans package delivered with OpenSuse Tumbleweed; it seems that the repo was not updated.
