### ISSUE TITLE
Add support for Kashmiri e to Urdu Nastaliq font

### ISSUE THREAD

**Issue by r12a** [googlefonts/noto-fonts#1970]
### Font 
  > NotoNastaliqUrdu-Regular.ttf
  > Version 2.000; ttfautohint (v1.8.3) -l 8 -r 50 -G 200 -x 14 -D arab -f none -a qsq -X ""
  >   Site: https://github.com/googlefonts/noto-fonts/hinted/ttf/NotoNastaliqUrdu/
  >   Date: 2020-12-31

### OS name and version
  > macOS Mojave (same in Big Sur)

### Application name and version
  > Firefox, Chrome

### Issue
<span class="codepoint" translate="no"><span lang="ks" dir="rtl">&#x06CE;</span> [<span class="uname">U+06CE ARABIC LETTER YEH WITH SMALL V</span>]</span> and <span class="codepoint" translate="no"><span lang="ks" dir="rtl">&#x065A;</span> [<span class="uname">U+065A ARABIC VOWEL SIGN SMALL V ABOVE</span>]</span> are used to write the sound 'e' in Kashmiri, but they cause joining problems in the Nastaliq Urdu font.

Examples (beb and babe):

![Screenshot 2020-12-31 at 14 06 49](https://user-images.githubusercontent.com/4839211/103413489-b1b8d480-4b71-11eb-966a-33df11e14b6b.png)

In position 1 in the image the YEH WITH V should be a medial shaped YEH with V above.
In position 2 the second BEH should join with the YEH BARREE and the V should appear above the BEH.

Codepoints:
ب U+0628 ARABIC LETTER BEH
ێ U+06CE ARABIC LETTER YEH WITH SMALL V
ب U+0628 ARABIC LETTER BEH
U+0020 SPACE
ب U+0628 ARABIC LETTER BEH
ب U+0628 ARABIC LETTER BEH
ٚ U+065A ARABIC VOWEL SIGN SMALL V ABOVE
ے U+06D2 ARABIC LETTER YEH BARREE

Live test: https://r12a.github.io/pickers/arab-ks/?text=%D8%A8%DB%8E%D8%A8%20%D8%A8%D8%A8%D9%9A%DB%92

Same results on both Chrome, Edge, and Firefox.  (Safari font support has fundamental problems, so not considering it here.)
 
### Rationale
I'm aware of https://github.com/googlefonts/noto-fonts/issues/652 but would like to argue Noto should support the Kashmiri language as a high priority, since Kashmiri is spoken by around 7 million people, and as of this year is an official language of Jammu and Kashmir, and it is among the 22 scheduled languages of India. The predominantly muslim population uses the nastaliq orthography. 

SIL has the Awami nastaliq font, but although it covers around 25 Pakistani languages it doesn't appear to support this Kashmiri letter either.

It may be that this is a rendering issue rather than a font issue.

### PS
There is also an occasional problem with ۆ U+06C6 ARABIC LETTER OE joining. See https://github.com/googlefonts/noto-fonts/issues/1353

**Comment by simoncozens** [comment]
This appears to be fixed, at least as of 2.001:
![shape](https://user-images.githubusercontent.com/106728/151338480-eee16cab-fde3-4eed-ae23-7e5047fa42a5.png)
