### ISSUE TITLE
noto-fonts hinting looks different; manjaro linux or arch linux

### ISSUE THREAD

**Issue by pheiduck** [googlefonts/noto-fonts#1974]
> OK result as expected: noto-fonts 20190926-4 noto-fonts-cjk 20190409-2 noto-fonts-extra 20190926-4
  > Not OK: noto-fonts 20201206-1 noto-fonts-cjk 20201206-1 noto-fonts-extra 20201206-1

### Font 
  > Full file name, for example 'NotoSansRegular.ttf'.
  > Size 10
  > Hiniting: strong

### Where the font came from, and when
  >   https://archlinux.org/packages/extra/any/noto-fonts/
  >   Date: 2020-12-07

### Font Version
  > noto-fonts 20201206-1 noto-fonts-cjk 20201206-1 noto-fonts-extra 20201206-1

### OS name and version
  > Manjaro Linux x86_64

### Issue
  > Summarize the issue briefly -- one paragraph preferred

  1. install or update to latest versions
  2. Not Expected: https://forum.manjaro.org/uploads/default/original/2X/5/5983489b40e49660afc15e505effb377e5c0771d.jpeg
  3. Expected: https://forum.manjaro.org/uploads/default/original/2X/2/2858c0a679a38cefd5838fe1e844e0437c92d0e1.jpeg
  4. Additional information 
  > Size 10; Hiniting: strong

### Screenshot
https://forum.manjaro.org/uploads/default/original/2X/5/5983489b40e49660afc15e505effb377e5c0771d.jpeg
https://forum.manjaro.org/uploads/default/original/2X/2/2858c0a679a38cefd5838fe1e844e0437c92d0e1.jpeg

**Comment by nizarsq** [comment]
Is this issue related to https://github.com/googlefonts/noto-fonts/issues/1960

**Comment by pheiduck** [comment]
> Is this issue related to #1960 ?

Yes

**Comment by nizarsq** [comment]
I believe this not font issue.

**Comment by nizarsq** [comment]
Duplicate of https://github.com/googlefonts/noto-fonts/issues/1960

**Comment by pheiduck** [comment]
hm, I think it is, Arch Linux and Manjaro Linux said it is an upstream bug

**Comment by pheiduck** [comment]
latest version noto-fonts 20201226-1 is fine so closed
