### ISSUE TITLE
Noto Sans Khmer displaying some characters in boxes

### ISSUE THREAD

**Issue by SurbhiAtal** [googlefonts/noto-fonts#1976]
### Title 
  > Some characters are displaying in boxes especially digits.

### Font 
  > Font Used NotoSansKhmer-Regular.ttf.

### Where the font came from, and when
  >   Site: https://www.google.com/get/noto/#sans-khmr

### Font Version
  > Version 2.000
   
### OS name and version
  >Microsoft Windows Server Version 10.0.14393
  >Font was not preinstalled.

### Issue
  > Using Noto Sans Khmer font to render the khmer language. Passing JSON data to RML and then printing the document either in Image/PDF both are not working.
The original text is លេបថ្នាំនេះតាមមាត់មួយដងក្នុងមួយថ្ងៃ។ លេបថ្នាំមួយ (1) គ្រាប់ក្នុងមួយដង។
and the output is attached as image.

![image](https://user-images.githubusercontent.com/28348868/103655381-27b3a600-4f8d-11eb-8955-ad6dd87539ae.png)

**Comment by punchcutter** [comment]
The font in the image is not Noto Sans Khmer, but even if it were it won't display numbers like 0-9 which are found in Noto Sans.

**Comment by ohbendy** [comment]
I believe that image shows Microsoft's (awful) Leelawadee UI font

**Comment by SurbhiAtal** [comment]
Leewadee UI font is working it displays all characters,
Well we merged the Noto fonts and now it shows all the characters. Thank you !
