### ISSUE TITLE
Noto serif kannada issue with kShNa

### ISSUE THREAD

**Issue by kidasund** [googlefonts/noto-fonts#1978]
Greetings. I am having an issue with kShNa (itrans) using Noto Serif Kannada.
Here is what I get
![image](https://user-images.githubusercontent.com/77251997/104138882-f9f3a600-536c-11eb-8aa9-17abcb5a0203.png)

I use xelatex.
Thank you.

**Comment by sridatta1** [comment]
This issue can be closed
![image](https://user-images.githubusercontent.com/23263723/171997302-55db4d1b-b046-4e62-9ab5-ef68216691d0.png)

https://fonts.google.com/noto/specimen/Noto+Serif+Kannada?subset=kannada&preview.text=%E0%B2%95%E0%B3%8D%E0%B2%B7%E0%B3%8D%E0%B2%A3&preview.text_type=custom
Test string: ಕ್ಷ್ಣ

**Comment by simoncozens** [comment]
Yes, the latest versions have this fixed. Thanks!
