### ISSUE TITLE
Non-serif uppercase I and non-descending uppercase J for Noto Sans and Sans Display (Latin/Greek/Cyrillic)

### ISSUE THREAD

**Issue by MattMayuga** [googlefonts/noto-fonts#1982]
Here is something that I would like to look forward to for Noto Sans LGC (including Display): Having a non-serif I and non-descending J would be something to have in these fonts. I know some have their own preferences for these letters, so here are two possible solutions to this.

**1.** Add the non-serif I and non-descending J as default glyphs, and have the serif I and descending J as alternates for these letters.
**2.** Add the non-serif I and non-descending J as alternate glyphs and keep everything else as it is.

Here is an illustration of what it would look like with these changes:

![NotoSansLGC_IandJ_Suggestion](https://user-images.githubusercontent.com/26103475/104732858-c81d7d80-5778-11eb-9ec9-410f1b515aab.png)

**Comment by moyogo** [comment]
>  2. Add the non-serif I and non-descending J as alternate glyphs and keep everything else as it is.

This is already implemented in Noto Sans and Noto Sans Display fonts.
The ss04 feature substitutes I and J for the the titling alternates which are the non-serif I and the non-desceding J.

**Comment by MattMayuga** [comment]
![LibreOffice Writer on Windows 8.1 with Noto Sans the :ss04 feature](https://i.postimg.cc/ZKgWJCkJ/image.png)
I tested the font with the `ss04` feature on LibreOffice Writer version 7.0.3.1, and these titling alternates are shown as moyogo said. Personally, I would have these by default and can always replace the normal I and J with the ss04 ones with a font editor like FontForge.

**Comment by moyogo** [comment]
Related to #1113.

I'll close the issue since option 2. is already implemented.
