### ISSUE TITLE
Old Hungarian Capital and small letters aren't on the same baseline

### ISSUE THREAD

**Issue by tamasbartos** [googlefonts/noto-fonts#1984]
## Defect Report
In https://github.com/googlefonts/noto-fonts/blob/master/unhinted/ttf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf
the small and the capital letters haven't got the same baseline.
### Font 
  Full file name: 'NotoSansOldHungarian-Regular.ttf'.
 ### Where the font came from, and when
 https://github.com/googlefonts/noto-fonts/blob/master/unhinted/ttf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf
2021-01-18
version 2.00.2
### Application name and version
Tester app: LibreOffice 6.4.6.2 
### Character data
https://unicode.org/charts/PDF/U10C80.pdf
### Screenshot
![Old Hungarian uppercase and lowercase lettres](https://user-images.githubusercontent.com/75836867/104886277-bf3fce00-5969-11eb-9078-67d901236581.jpg)

**Comment by tamasbartos** [comment]
@marekjez86 Thi is the only one issue, that I wont close. I left, and never go back!

**Comment by rovasinfo** [comment]
_'the small and the capital letters haven't got the same baseline'_
We would keep the current center aligned version, all the books we published use this alignment. Our readers like this design.

![ECSreszlet1](https://user-images.githubusercontent.com/81823602/114305418-7155e480-9ad8-11eb-84fb-a92f5516de9d.JPG)
Screenshot form _Egri csillagok_ second edition, 2010. ISBN 978-963-06-7107-1

**Comment by tamasbartos** [comment]
@marekjez86  @rovasinfo  same baseline for small and capital letters useful  for underlined texts.

**Comment by tamasbartos** [comment]
> _'the small and the capital letters haven't got the same baseline'_
> We would keep the current center aligned version, all the books we published use this alignment. Our readers like this design.
> 
> ![ECSreszlet1](https://user-images.githubusercontent.com/81823602/114305418-7155e480-9ad8-11eb-84fb-a92f5516de9d.JPG)
> Screenshot form _Egri csillagok_ second edition, 2010. ISBN 978-963-06-7107-1

I buy your book "Egri csillagok", (Eclipse of the moon),:but the letterforms of your book made me nervous.

**Comment by tamasbartos** [comment]
> _'the small and the capital letters haven't got the same baseline'_
> We would keep the current center aligned version, all the books we published use this alignment. Our readers like this design.
> 
> ![ECSreszlet1](https://user-images.githubusercontent.com/81823602/114305418-7155e480-9ad8-11eb-84fb-a92f5516de9d.JPG)
> Screenshot form _Egri csillagok_ second edition, 2010. ISBN 978-963-06-7107-1

I already see, why you want  to change the letterform of ë. You published the book, before you three have completed the standardization. Standardization, which you three forgot  coordinate whith oters, tried to drag the time, smuggle Khazar letters, etc.

**Comment by rovasinfo** [comment]
_I already see, why you want to change the letterform of ë. You published the book, before you three have completed the standardization. Standardization, which you three forgot coordinate whith oters, tried to drag the time, smuggle Khazar letters, etc._

You  @tamasbartos simply do not know, that we had coordinated with others, we have an agreement with full character repertoire based on a conference held in 2008. See conference book. 
ISBN 978-963-87967-5-2

![agreement 2009p0 p257](https://user-images.githubusercontent.com/81823602/114350246-3d76cf80-9b69-11eb-8793-0bbb8cef4295.jpg)
![agreement 2009p1](https://user-images.githubusercontent.com/81823602/114350269-45cf0a80-9b69-11eb-93cb-0ab0a7847e96.jpg)
![agreement 2009p2](https://user-images.githubusercontent.com/81823602/114350317-58494400-9b69-11eb-9bf3-9b2144e8108a.jpg)
