### ISSUE TITLE
There are nonstandard elements in Old Hungarian font.

### ISSUE THREAD

**Issue by robihorvath** [googlefonts/noto-fonts#2008]
#### There are in the fonts ligatures, which do not follow the ligature-rules, there are ligatures with wrong forms. They are only randomly choosen. The ISO/IEC and UNICODE standards do not prescribe ligatures in Old Hungarian script, do not contain ligatures. The use of accents is also not specified.
Issues, which are opened:
#2001 : That is all right, that is a part of this problem.
#1989  : That is all right, that is a part of this problem.
#1985  : That is all right, that is a part of this problem.
#1984 : That s is all right, that is an another problem of the font.
#1983 : Ligature "w"? "w" is a letter in Latin script. Old Hungarian script does not contain "w" letter. "Letter" and "Ligature" are not the same things.
#1947 : That is all right, that is a part of this problem.
#1946 :  That is all right, that is a part of this problem.
#1945 : That is a huge problem.
#1944 : Using "x" ligature just a Latinization.
#1930 : This Issue unnecessary, if ligatures will be removed, followed by standards.
#1924 : We talk about same thing.
#1374 : As I wrote before, the Unicode and ISO/IEC standards do not contain diacritics. There is a must to close.
#1364 : If the developers follow the Unicode and ISO/IEC standards and remove all ligatures, this Issue must be close.
### Font 
 Full file name: 'NotoSansOldHungarian-Regular.ttf'.  
### Where the font came from, and when
  Site1: https://github.com/googlefonts/noto-fonts/blob/master/unhinted/ttf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf
 Site2: https://github.com/googlefonts/noto-fonts/blob/master/unhinted/otf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.otf
Date: 2021-02-19

### Font Version
2.002, GOOG

### Application name and version
LibreOffice 6.4.6.2

### Issue
1. Steps to reproduce
Remove all ligatures, and close all opened issues, which do not follow the standards.  
2. Expected results
Purely standard Old Hungarian script, with standard symbols only:
[Unicode symbols](https://www.unicode.org/charts/PDF/U10C80.pdf)

### An another wrong formed ligature:
![An example of a malformed ligature](https://user-images.githubusercontent.com/79311782/108526371-57b2d080-72d1-11eb-9442-ecfc7fec43ad.jpg)

**Comment by robihorvath** [comment]
The following Issues might to be closed, if this Issue will be accepted and resolved:
#2001
#1985 
#1983 
#1947  
#1946 
#1945 
#1944 
#1930 
#1924 
#1374 
#1364 
There is an Issue, that must to be resolved, too:
#1984 
@marekjez86 I wait for you to check me back! I believe your wisdom!

**Comment by tamasbartos** [comment]
@robihorvath I agree with you, but I do not believe, that this issue will be accepted and resolved. @dscorbett fights his own truth, but  he have no knownledge of circumstantes of  the standardization of Old Hungarian script..

**Comment by robihorvath** [comment]
@marekjez86 @tamasbartos 
#### There is a copy of 
[short format of MSZ ISO/IEC 10646:2015 ](https://github.com/googlefonts/noto-fonts/files/6018060/160378C_rovid.pdf)

### It said:
### "Endorsement notice
#### The International Standard ISO/IEC 10646:2014 is endorsed by the Hungarian Standards Institution as a Hungarian National Standard from the day of its publication. The English language version of the International Standard shall be considered as the Hungarian National Standard."

### It said:
#### "A szabványnak való megfelelőség akkor valósul meg, ha változtatás nélkül érvényesülnek az előírásai."
### It means (I translated with using Google's translator):
#### "Compliance with the standard is achieved if its requirements apply without change."

### The ISO/IEC 10646 standard "family" ensures that the Unicode standard is raised to the international level.

The standard was refreshed in 2018 as MSZ ISO/IEC 10646:2018, but the Old Hungarian section doesn't changed. If you want to check me back, please buy a copy of MSZ ISO/IEC 10646:2018 Hungarian National Standard and/or ISO/IEC 10646:2020 International standard.

#### In these documents are nowhere written about Old Hungarian diacritics and Old Hungarian ligatures.

#### Conclusion: If the developers of Google's Noto-fonts project want to follow the Unicode standard, they must also take into account the international standard. In this case, archived but ignored drafts by Unicode standard should be ignored. So the ligatures need to be deleted from the Old Hungarian font, the issues for diacritics and ligatures should be closed.

**Comment by tamasbartos** [comment]
@robihorvath @marekjez86 I close all issues, I opened by myself
I agree with you, @robihorvath.
If the Google wants stuff nonstandard elements to the Old Hungarian font, I wont assist for it. I go away. I wont go back! Do the developers, that they want.

**Comment by rovasinfo** [comment]
**It is incredible, that how the Unicode standard is misunderstood..**. ZWJ gives options to create any ligatures, this is why there are NOT in the standard. Therefore it is absolutely unprofessional to state that if there is no ligature in the Unicode standard, do not develop any ligatures in the actual font. 
The statement "Compliance with the standard is achieved if its requirements apply without change." is irrelevant, because creating ligatures based on standardized codepoints are not against any standard. 
There are more than 100 ligature option, but these ligatures must meet the rules of creating ligatures (not the rules of any standard) as @tamasbartos clearly stated. **Please ignore @robihorvath statements and false conclusions.**

**Comment by tamasbartos** [comment]
Hi @rovasinfo = Tamás Rumi!
As you can see, this issue is closed!
