### ISSUE TITLE
 Need to use an optimized Old Hungarian font with syllable like ligatures, few ligatures implemented and more of those have form problems.It might to be an another fontvariant

### ISSUE THREAD

**Issue by robihorvath** [googlefonts/noto-fonts#2015]
### Title 
 In the Old Hungarian part of [Unicode standard](https://www.unicode.org/versions/Unicode13.0.0/UnicodeStandard-13.0.pdf#page=377)  are written ligatures, but optional. The NotoSansOldHungarian-Regular font implement those incompletely, and more of them have wrong form and/or unreadable. Several of them unnecessary (which haven't any vowels)

### Font 
 Full file name, 'NotoSansOldHungarian-Regular.ttf'.

### Where the font came from, and when

Site: https://github.com/googlefonts/noto-fonts/blob/master/unhinted/ttf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf 
   Date: 2021-03-01

### Font Version
 2.002 GOOG

### Resolving steps:
1. Remove wrong formatted and/or unknown ligatures, which haven't any vowel.
2. Remove ligatures, which haven't vowels.
3. Remove non-historic ligatures, like "qu' as "ksz", "x" as "kv", "w" as "vv", "y" as "ij". The last two non-historic ligature make display problems, because there are terminal-like programs and editors, which don't use ligatures, and those cases "w" displayed as two "v", "y" displayed as "j" "i", which aren't the same things in Hungarian language.
4. Adding missing syllable-like two letters ligatures. As @tamasbartos suggested
5. Resolving syllable-like (two or three letters) ligatures, when that has formal problems. As @tamasbartos suggested.
My suggestion: consonant + vowel ligatures might to be automatic (discretional) ligatures, vowel+consonant ligatures might be simple ligatures only. It would be made clearer apereance of text.

The Issue #1364 might to be closed, because ligatures were used only that case, when the wooden stick was too short for the text. In these cases in the beginning of the text weren't used ligatures. 
The Issue #1364 is not clear for me, what kind of capital ligatures @dscorbett wants: Full-capital with all capital members, or semi-capital with the first capital letter, and the others low letters. The capital ligatures might be used few times and unnecessarily increase the font's size.

Non-syllable-like ligatures would be used few times, than it would make sense to include it in the font.

@marekjez86 May I start developing (drawing) syllable-like ligatures for Old Hungarian font?

**Comment by robihorvath** [comment]
@marekjez86 All right, Issue #1364  might to be developed. For this issue must to start a newer project. It still not be clear for me that in issue #1364 what kind of ligatures requested: semi-capital or full-capital?

**Comment by robihorvath** [comment]
@marekjez86 I wrong about ligatures, (I so sorry)  but I didn't  do it about Issue #1374

**Comment by tamasbartos** [comment]
@robihorvath Don't  force this! That are enough, that syllable like ligatures will be added, and non historic-ligatures will be removed, wrong ligatures are resolved. 
@marekjez86  and @dscorbett can not understand, that issue #1374  does not conform to the Unicode standard.

**Comment by robihorvath** [comment]
@tamasbartos All right, I close it.
