### ISSUE TITLE
Consider to use non-historic ligatures in Old Hungarian font, "w" and "y" are not real ligatures

### ISSUE THREAD

**Issue by robihorvath** [googlefonts/noto-fonts#2021]
### Title 
The ligature "w" isn't real ligature and appears with combination "v" + "v"
The ligature "y" isn't real ligature and appears with combination "i" + "j"
In Programs, devices without supporting ligatures appears "w" as two "v" and "y" appears as "i" and "j" which aren't the same in Hungarian language.
Because of that these ligatures could appear wrong forms, must be remove. Because of that these ligatures must be removed, "x" and "qu" ligatures must be removed, implementing "x" and "qu" only would be half work, users would not be satisfied.  
### Font 
'NotoSansOldHungarian-Regular.ttf'.

### Where the font came from, and when
 Site: https://github.com/googlefonts/noto-fonts/blob/main/unhinted/ttf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf  Date: 20121-03-03

### Font Version
 2.002, GOOG
### Character data
ligature "qu" (uni10CD3_10CEE) as "k"+ZWJ+"v" (uni10CD3 + uni10CEE)
ligature "x" (uni10CD3_10CE5) as "k" + ZWJ + "sz" (uni10CD3 + uni10CE5)
ligature "w" (uni10CEE_10CEE) as "v"+ ZWJ + "v" (uni10CEE + uni10CEE)
ligature "y" (uni10CD0_10CD2) as "i" + "j" or "i" + ZWJ + "j" (uni10CD0 + uni10CD2)

**Comment by robihorvath** [comment]
@marekjez86 This issue is the extended Issue derived from #1983  that was opened and later closed by @tamasbartos.

**Comment by tamasbartos** [comment]
@marekjez86 There is arbitrary draft standard about letter "w" and "y" of Tamás Rumi, Gábor Hosszú and László Sípos,  in which he overruled all conventions and did not consult with anyone :
!["Old Hungarian letter y and w"](https://user-images.githubusercontent.com/75836867/112612665-78fe6380-8e1f-11eb-8ff5-a7bebe43bb26.jpg)
There is an explanation, how the designers of Old Hungarian script try to include "y" and "w" into the standard using ligatures:
![Ligatures or letters?](https://user-images.githubusercontent.com/75836867/112615693-19a25280-8e23-11eb-8370-fb15fe9838a3.jpg)
The "ligature y" and "ligature w" appears letters "ij" and two "v" on devices and terminal like editors, which don't use ligature capabilities. Letters "y" and "ij", letters "w" and two "v" aren't the same in Hungarian language.
Ligature "x" and "qu" ligatures come from arbitrary draft standard, is written above.

**Comment by tamasbartos** [comment]
@marekjez86 Here is the document, I talked about in comment https://github.com/googlefonts/noto-fonts/issues/2021#issuecomment-808098220 
[Arbitrary Unicode standard drafts, signed by Dr. Gábor Hosszú](https://www.unicode.org/L2/L2012/12014-n4183-hungarian.pdf#page=27)

**Comment by tamasbartos** [comment]
@marekjez86 Using non-historical ligatures in a historical script is illogical, I think. Especially that two of them are not  real ligatures.
Tamás Rumi, Dr. Gábor Hosszú and László Sípos undertook in 2008 carry out standardization, but did not do what they agreed with the others. Included into the standard draft letters, which never was used in the carpatian basin by Hungarians. That was the reason, why the Old Hungarian script was removed from the DAM period in 2012 or 2011.

**Comment by tamasbartos** [comment]
@marekjez86 Michael Everson tried to work with Tamás Rumi, Dr. Gábor Hosszú and László Sípos, but he can't. The "triumvirate" did not want any cooperation at all.

**Comment by robihorvath** [comment]
@marekjez86 I changed the caption of this issue. Is it correct now? Please read comments of @tamasbartos in this issue, too.

**Comment by robihorvath** [comment]
@marekjez86 Here are several links about Dr. Gábor Hosszú's experiments.

[About Dr. Gábor Hosszú experiment](http://magyarrovas.hu/hosszu-gabor-kiserlete/)

 [About exemption of  Dr. Gábor Hosszú by MSZT](http://magyarrovas.hu/hosszu-felmentese/)

MSZT - Magyar Szabványügyi Testület - Hungarian Standards Board

**Comment by tamasbartos** [comment]
@marekjez86 Somebody uses two "v" ligature as real two "v" ligature, "ij" ligature required for syllable like ligature capabilities. Form of those ligatures differ from "ligature" y and w.
A Hungarian guy develops a spellchecker for Hungarian text written in Old Hungarian script. He wrote me, that use non-historic ligatures made  the spellchecker more comlicated, and these ligatures are not accepted by all users. The result would be that, spellchecker would correct for example ligature "w" to "v" where is it on the Latin based text "w", and two "v", where this ligature is really two "v"

**Comment by tamasbartos** [comment]
@marekjez86 Additional informations for https://github.com/googlefonts/noto-fonts/issues/2021#issuecomment-810957225 :
Old Hungarian "ligature w" activated by Old Hungarian "v" + ZWJ + Old Hungarian "v" keys:
!["w ligature"](https://user-images.githubusercontent.com/75836867/113139320-3ece0100-9227-11eb-8026-34b0dcea332b.jpg)

Old Hungarian ligature two "v" activated by Old Hungarian "v" + ZWJ + Old Hungarian "v" keys:
![two v ligature](https://user-images.githubusercontent.com/75836867/113139544-8a80aa80-9227-11eb-9c22-d7ebc9019251.jpg)

If Noto-fonts project adopt "ligature w" and the other non-historic ligatures, vote the arbitrary standard of  Dr. Gábor Hosszú and his friends, and doesn't allow using ligature two "v" and ligature "ij". See: https://github.com/googlefonts/noto-fonts/issues/2021#issuecomment-808175023
and https://github.com/googlefonts/noto-fonts/issues/2021#issuecomment-809317369
and https://github.com/googlefonts/noto-fonts/issues/2021#issuecomment-810957225

**Comment by tamasbartos** [comment]
@marekjez86  Please drop a feedback to Unicode, that really revoked Dr. Gábor Hosszú's arbitrary standard draft! If you want quickier answer, please ask Michael Everson directly!
Please send me a quick answer about that, do this or don't.
Thank you!

**Comment by rovasinfo** [comment]
> @marekjez86 There is arbitrary draft standard about letter "w" and "y" of Tamás Rumi, Gábor Hosszú and László Sípos, in which he overruled all conventions and did not consult 

When we say something that is verified and consulted with linguists, and representatives of the Hungarian sciences. A lot of consultation are behind us, please ask me if you do not feel safe in this area.
Letter w is almost hundred years old, the x,y,q letters are 400 years old.

**Comment by rovasinfo** [comment]
> @marekjez86 Michael Everson tried to work with Tamás Rumi, Dr. Gábor Hosszú and László Sípos, but he can't. The "triumvirate" did not want any cooperation at all.
The description of this situation is not correct. The 'triumvirate' is in the other side, they never accepted any fact from the representatives of the Hungarian science. 
If anybody wants to get information about this script, ask experts, not Unicode sponsored agents. Thanks.

**Comment by rovasinfo** [comment]
For the case of W and Y, unfortunately there is no codepoint on the Old Hungarian (correctly: Szekely-Hugarian rovas) area, so simply use the latin basic codepoints for these letters if the ZWJ function is not supported or applicablecin this situation. There are words where two v are existing which can not be converted to w, e.g. 'savval'.

**Comment by rovasinfo** [comment]
For the case of Y, because there is no codepoint for the Y, there is not possibility for the user to write correctly these historical names: Ybl or Bay. The pronounciation different, I and J. I recommend to use the codepoint from the latin character set.

**Comment by tamasbartos** [comment]
@marekjez86 Hi Marek! @rovasinfo would like to associate Old Hungarian capital "W" to u+10CB6, small "w" to u+10CF6, capital "Y"-to u+10CB8, small "y" to u+10CF8.
It might to be done?

**Comment by rovasinfo** [comment]
> Using non-historical ligatures in a historical script is illogical, I think. Especially that two of them are not real ligatures.
> Tamás Rumi, Dr. Gábor Hosszú and László Sípos undertook in 2008 carry out standardization, but did not do what they agreed with the others. Included into the standard draft letters, which never was used in the carpatian basin by Hungarians. That was the reason, why the Old Hungarian script was removed from the DAM period in 2012 or 2011.

It is not true. On the conference held in 2008, there was a section about these letters, led by Sándor Vér, from Szeged. The name of the section was "Transcription of foreign names and letters  Q, W, Y, X, DZS, DZ" See conference publication: ISBN 978-963-87967-5-2, p 105

![versandor2008](https://user-images.githubusercontent.com/81823602/113514282-02274000-956e-11eb-94b7-feaa1e0e9c16.JPG)

The X, Y, Q ligatures first appeared in 1629, the W appeared around 1930, revitalization effort were done by Zoltán Barczy in 1971 and by Balázs Pál in 1991, and by Sándor Vér in 1994, 2001.

**Comment by rovasinfo** [comment]
About the agreement in Gödöllő, 2008. I put here this document, Where Szakács Gábor, Friedrich Klára also accepted the ligatures and X, Y, W, Q, Dz, Dzs letters.  Even András Tisza, Miklós Szondi also attended this conference, and they did know about the agreement. Conference publication: ISBN 978-963-87967-5-2, p 258-259. 

![agreement 2009p1](https://user-images.githubusercontent.com/81823602/113517300-5d156300-957f-11eb-827b-a8af8fedb4d5.jpg)


![agreement 2009p2](https://user-images.githubusercontent.com/81823602/113517310-6b637f00-957f-11eb-9d56-f959333867e6.jpg)


I hope, that the font will includes all these ligatures and X, Y, W, Q, Dz, Dzs letters as well, according to this agreement. This character set is much wider, all of them is based historical or contemporary usage.

**Comment by robihorvath** [comment]
@marekjez86 I close this issue according to @tamasbartos lastest comment in issue #2054 . I know well, what kind of man @rovasinfo in the private life, arrogant and violent.. I go away!
