### ISSUE TITLE
Complete set of script info and testing web pages

### ISSUE THREAD

**Issue by davelab6** [googlefonts/noto-fonts#2040]
https://motaitalic.github.io/devanagari-documentation/languages/dogri/dogri.html is an example of excellent background information on the Dogri language written with Devanagari. 

I'd love to see such script info and testing web pages available for all languages supported by Noto.

**Comment by marekjez86** [comment]
me too

**Comment by r12a** [comment]
@davelab6  I'm curious whether there are things i could add to the following that would help.
https://r12a.github.io/scripts/#scriptnotes

(Plus other stuff linked from that page.)
