### ISSUE TITLE
Wrong glyphs - Old Hungarian numerals 100, 1000

### ISSUE THREAD

**Issue by rovasinfo** [googlefonts/noto-fonts#2061]
## Defect Report
> Noto fonts can be obtained from https://github.com/googlefonts/noto-fonts/tree/master/unhinted/otf/ (unhinted OTF) or https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf/ (hinted TTF). If you find a problem with either of these then please use this template to file a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title: Wrong glyphs - Old Hungarian numerals 100, 1000 
  > These glyphs' lines (axis) should be arranged like numeral 10.

### Font 
  >'NotoSansOldHungarian-Regular.ttf'.
  
### Screenshot

![wrong numeral glyphs](https://user-images.githubusercontent.com/81823602/114279173-9e03f080-9a33-11eb-9429-4611d6b0a5ec.JPG)

The numeral 100 looks like the Cyrillic small letter Zhe U+0436, which is incorrect. The correct glyph can be seen on the Code chart.

**Comment by tamasbartos** [comment]
@marekjez86 With this issue I agree, exceptionally.
