### ISSUE TITLE
Old Hungarian CLOSE E glyph modification request

### ISSUE THREAD

**Issue by rovasinfo** [googlefonts/noto-fonts#2063]
## Defect Report
> Noto fonts can be obtained from https://github.com/googlefonts/noto-fonts/tree/master/unhinted/otf/ (unhinted OTF) or https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf/ (hinted TTF).

### OLD HUNGARIAN CLOSE E 
  >  10C8A / 10CCA Old Hungarian Capital / Small Letter Close E
The recent glyph is topologically identical with 10C8F OLD HUNGARIAN CAPITAL LETTER EH, so the font design could lead to ambiguity and misunderstandings.

![NOTO close E](https://user-images.githubusercontent.com/81823602/114307979-7a4bb380-9ae2-11eb-9f2c-d7d34569b2df.JPG)

### Font 
  > Full file name, for example 'NotoSansOldHungarian-Regular.ttf'.
  > 

### Screenshot
  > Better glyph variant is attached here.  The proposed glyph variant is based on a historical glyph variation of E, between E and EE, therefore it could not be confused with letter EH. 

![szegedclosee](https://user-images.githubusercontent.com/81823602/114307612-bc73f580-9ae0-11eb-92aa-b7cdd62a9c64.JPG)

**Comment by tamasbartos** [comment]
@marekjez86 This issue isn't valid.
@rovasinfo  Every letters must be looks like as appears in yours books?

**Comment by tamasbartos** [comment]
@rovasinfo Does the word "standard" mean anythig to you?

**Comment by rovasinfo** [comment]
@marekjez86 - please do not believe everything to @tamasbartos 

> _@rovasinfo Does the word "standard" mean anythig to you?_
Does the "font creation" mean anything to you? Do you understand that the Unicode's main role is to give a codepoint to a certain letter, regardless the form of glyph? Creating font is not just copypaste the Unicode chart, font designers would not have job.

Do you know that there is a userbase, who have already designed the proper glyph form? Have you ever read their argumentation? See bilingual proposal of Writers Association of Szeged on this [link](https://unicode.org/L2/L2012/12218-hungarian.pdf) page 3.
They draw the illustration I attached earlier: 

![szegedclosee](https://user-images.githubusercontent.com/81823602/114322302-acc7d180-9b1f-11eb-845e-3ccdd0ecab74.JPG)

As we have published the majority of the books written with rovas (Old Hungarian) script, we have more than 10 years experience concerning useability of this script. However, the CLOSE E issue is not our priority, or issue, but it is issue for the members of Writers Association of Szeged. If you have any question concerning the form of proposed glyph, please ask them.

The Noto font designs have its guidelines, so I do not worry about the Noto font will not be exactly the same to our fonts.

**Comment by tamasbartos** [comment]
@marekjez86 As you can see, @rovasinfo published their "best sellers", before the standardization finished. Now he wants their own letters.
You will still have  a lot of trouble with him.
I go away.

**Comment by rovasinfo** [comment]
_@marekjez86 As you can see, @rovasinfo published their "best sellers", before the standardization finished. Now he wants their own letters.
You will still have a lot of trouble with him.
I go away._

@marekjez86 : @tamasbartos mention is irrelevant here. Concerning the CLOSE E, it is used by region around Szeged.
On the other hand, we do prefer use only one kind of E, however we respect those, who might need this CLOSE E as well. 

About our bestsellers: we have been publishing books written in Old Hungarian (Rovas), the alphabet exactly follows the Hungarian latin based alphabet, They are not "our" letters, but it is the official alphabet in Hungary. Some marginal users simply does not accept the fact, that the Old Hungarian is not an extinct script, where the red line is in 1806. There are natural improvements in the Latin based script as well, the Old Hungarian (Rovas) needs to follow it. It is needless to say, that the Noto fonts are designed for living script communities, who want to use this script without limitations. So the trouble is not with me, but the poor standard and the guys who rely on only standards but they have no clue about the reality and they are not familiar with the current Latin based Hungarian alphabet. See Wikipedia [here.](https://en.wikipedia.org/wiki/Hungarian_alphabet)

**A, Á, B, C, Cs, D, Dz, Dzs, E, É, F, G, Gy, H, I, Í, J, K, L, Ly, M, N, Ny, O, Ó, Ö, Ő, P, Q, R, S, Sz, T, Ty, U, Ú, Ü, Ű, V, W, X, Y, Z,**

**Comment by davelab6** [comment]
@tamasbartos @rovasinfo thanks for your many issues posted on this repo about Old Hungarian. I appreciate you both have a lot of passion for these characters. 

I acknowledge that there is an investigation to be done into how to better support Old Hungarian in the Noto project. However, until Marek and I can commission someone to do an independent investigation, nothing will happen, so I do ask for your patience while we arrange for that to happen. 

Since there are many users interested in many issues not related to Old Hungarian on this repo, I am going to close and lock all these issues, and create a new one where we will update you on our progress and invite specific comments.
