### ISSUE TITLE
NotoNaskhArabic NotoNaskhArabicUI multiple issues noticed in U+0641 and  U+0642

### ISSUE THREAD

**Issue by nizarsq** [googlefonts/noto-fonts#2070]
Multiple issues noticed in U+0641 (ARABIC LETTER FEH) and U+0642 (Arabic Letter Qaf)
1- U+0641,  both isolated and initial form have sharp edges/corner especially at the bottom right side, very noticeable in Bold weight
2- U+0641 and U+0642,  the white paths seems not consistent with the other forms, look like diamond shape in the medial form

Font:
NotoNaskhArabic 2.009
NotoNaskhArabicUI 2.009

Font came from:
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoNaskhArabic/NotoNaskhArabic-Regular.ttf
https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoNaskhArabicUI/NotoNaskhArabicUI-Regular.ttf

Character data:
 ققق ق ففف ف

Screenshot:
<img width="1131" alt="Screen Shot 2021-04-18 at 9 45 04 PM" src="https://user-images.githubusercontent.com/22158882/115183104-084e0e00-a090-11eb-9881-6ed3cb5cdfdd.png">

**Comment by moyogo** [comment]
Related to #661.

**Comment by nizarsq** [comment]
Related to https://github.com/googlefonts/noto-fonts/issues/460

**Comment by khaledhosny** [comment]
I don’t see anything wrong here, all are expected from a Naskh-based design.

**Comment by khaledhosny** [comment]
The new medial feh shape is very ugly and makes no sense at all, I really don’t see what the issue that was being fixed here.

**Comment by moyogo** [comment]
@nizarsq I agree with @khaledhosny. The qaf and fa were fine in 2.009.

2.009 | 2.010
--|--
<img width="411" alt="image" src="https://user-images.githubusercontent.com/1923747/117311860-8118dc80-ae7c-11eb-93c5-8d2e657612ac.png"> | <img width="404" alt="image" src="https://user-images.githubusercontent.com/1923747/117311887-87a75400-ae7c-11eb-81f6-a9078f0414ee.png">
<img width="396" alt="image" src="https://user-images.githubusercontent.com/1923747/117311974-9a218d80-ae7c-11eb-9342-ea5e668dbb05.png"> | <img width="394" alt="image" src="https://user-images.githubusercontent.com/1923747/117312001-a1489b80-ae7c-11eb-939f-af95d4add5cb.png">

The corners on the initial and isolate qaf and fa or the diamond shape for medial qaf and fa are fine for the style of the font.

This is what the ductus produces. Those corners inside or outside are found in almost all the round letters. For example on the ba or on the ayn.
<img width="92" alt="image" src="https://user-images.githubusercontent.com/1923747/117309973-d522c180-ae7a-11eb-9802-0b32b668c168.png">
<img width="80" alt="Screenshot 2021-05-06 at 14 52 00" src="https://user-images.githubusercontent.com/1923747/117309761-a3115f80-ae7a-11eb-8bf0-adc9f30112d9.png">

There are also issues with the points and control points of the outlines of the new uni066F.medi:
<img width="309" alt="image" src="https://user-images.githubusercontent.com/1923747/117310657-62feac80-ae7b-11eb-9fcc-11174f4f4fa9.png">
<img width="336" alt="image" src="https://user-images.githubusercontent.com/1923747/117310673-672aca00-ae7b-11eb-8498-3145f2e05cd6.png">
Some of the points were horizontal or vertical extremes, with their control points aligned horizontally or vertically, for better control. But many of those points have been moved  and their control points are not aligned horizontally or vertically anymore.

**Comment by nizarsq** [comment]
@moyogo 
Regarding the corner; yes this font has corners, but it's sharp especially in bold weight. This is true for all glyphs that share same shape. (Work still on going)

Regarding the diamond shape in Qaf medial form; the white space shape in this glyph should be maintained **when a similar shape** (rounded shape ) used.

2.009 using the diamond shape in medial only, Pear shape used in initial and final forms. A very good examples of how to maintain the consistency in all forms can be found in Kufi and Geeza Pro. 
Work still on going and I believe this glyph still can be improved.

<img width="279" alt="Screen Shot 2021-05-06 at 8 46 11 AM" src="https://user-images.githubusercontent.com/22158882/117329965-0d5ddc00-ae4a-11eb-8ba2-ad1b2b9f518c.png">

<img width="281" alt="Screen Shot 2021-05-06 at 9 05 38 AM" src="https://user-images.githubusercontent.com/22158882/117330136-3b432080-ae4a-11eb-82dc-e103847493e6.png">

**Comment by marekjez86** [comment]
<img width="1101" alt="Screen Shot 2021-05-06 at 11 22 32" src="https://user-images.githubusercontent.com/13322623/117347355-db567500-ae5d-11eb-9743-92286dcc05bc.png">
<img width="1101" alt="Screen Shot 2021-05-06 at 11 22 19" src="https://user-images.githubusercontent.com/13322623/117347357-dd203880-ae5d-11eb-80b7-7a323b42a0f9.png">
<img width="1096" alt="Screen Shot 2021-05-06 at 11 21 57" src="https://user-images.githubusercontent.com/13322623/117347359-ddb8cf00-ae5d-11eb-9070-d5d43fb183d5.png">
<img width="1096" alt="Screen Shot 2021-05-06 at 11 21 17" src="https://user-images.githubusercontent.com/13322623/117347360-de516580-ae5d-11eb-8356-16b3f4d0e6c1.png">

**Comment by moyogo** [comment]
I wouldn't compare with Kufi styles. Geeza seems to be based on a more mechanical style.
Noto Sans Arabic is too monolinear.

Instead compare with similar styles. Calibri is probably the best comparison.
However Noto Naskh Arabic still has sharp corners in general compared to those fonts, not just in qaf and fa.
This is a feature of the design.

Noto Naskh Arabic 2.009
<img width="572" alt="image" src="https://user-images.githubusercontent.com/1923747/117340958-70c32a80-ae99-11eb-993b-8c1f3877d4a5.png">

Calibri
<img width="583" alt="image" src="https://user-images.githubusercontent.com/1923747/117340821-3eb1c880-ae99-11eb-8e4c-30f89a7b1ff4.png">
Adobe Arabic
<img width="465" alt="image" src="https://user-images.githubusercontent.com/1923747/117341190-bbdd3d80-ae99-11eb-846e-ce5be8d2ed75.png">
Sakkal Majalla
<img width="492" alt="image" src="https://user-images.githubusercontent.com/1923747/117345795-dd8cf380-ae9e-11eb-80b4-ac2fc3be7aa2.png">

Others also have the same skeleton but are more monolinear.

Kigelia Arabic
<img width="592" alt="image" src="https://user-images.githubusercontent.com/1923747/117347579-2e9de700-aea1-11eb-8869-89fbcfff92ef.png">
Markazi Text
<img width="530" alt="image" src="https://user-images.githubusercontent.com/1923747/117347516-1cbc4400-aea1-11eb-859e-6f7380cf6ec4.png">

**Comment by nizarsq** [comment]
@khaledhosny @moyogo thank you for your opinion. I guess I'll go back to the old design as both likes the old one. 
Old design will be added in 2.011
