### ISSUE TITLE
website very outdated

### ISSUE THREAD

**Issue by berrymot** [googlefonts/noto-fonts#2073]
### Title 
website very outdated

### Issue
the noto fonts website (google.com/get/noto) is nearly four years out-of-date. its last update was back in october 2017. people visiting it who don't want to (or can't) go to the github repo will most likely think there are less fonts than there actually are.

**Comment by marekjez86** [comment]
we are redoing it and a new web site will arrive soon

**Comment by berrymot** [comment]
nice

**Comment by yogamardia** [comment]
Is there any updates for this? @marekjez86

**Comment by ChiefMikeK** [comment]
And how about some 📢 over on [Type & Typography - Library - Google Design](https://design.google/library/google-fonts/ ) 👌

**Comment by marekjez86** [comment]
@yogamardia : it's still work in progress but we are getting closer to publishing it

**Comment by marekjez86** [comment]
@ChiefMikeK : we are going to include more on Noto  on Type & Typography - Library - Google Design  page. Thank you for suggesting it. However, if you wanted something different there please let me know and I'll place a request with the team.

**Comment by marekjez86** [comment]
please check https://fonts.google.com/noto (we are still in the transition so the two sites might exist for a while, but please file any issues that you might find with the new web site only).
