### ISSUE TITLE
Variable fonts have not hinted version

### ISSUE THREAD

**Issue by ryuran** [googlefonts/noto-fonts#2084]
Hello Noto team!

Every `-VF` fonts available in unhinted directory are not available in the hinted version.
Should we use `ttfautohint` to manage it ?

The repository mentioned in FAQ.md is very out of date https://github.com/lemzwerg/noto-hinted

**Comment by davelab6** [comment]
ttfautohint doesn't support variable fonts; we don't plan to hint any variable fonts.
