### ISSUE TITLE
tri in Noto Serif Grantha is incorrect

### ISSUE THREAD

**Issue by sridatta1** [googlefonts/noto-fonts#2089]
### Title 
  > tri in Noto Serif Grantha is incorrect

### Font 

NotoSerifGrantha-Regular.otf

### Where the font came from, and when
  >   Date: 2017-05-22
https://github.com/googlefonts/noto-fonts/tree/main/unhinted/otf/NotoSerifGrantha
https://github.com/googlefonts/noto-fonts/tree/main/unhinted/ttf/NotoSerifGrantha
### Font Version
2.001

### Issue
TRI in Serif Grantha font is incorrect
  1. Steps to reproduce
  𑌤𑍍𑌰𑌿 check in the Noto Serif Grantha and Noto Sans Grantha fonts
  2. Observed results
![image](https://user-images.githubusercontent.com/23263723/119219438-3d240980-bb03-11eb-9aac-04f1695ab9d1.png)
3. Expected results
![image](https://user-images.githubusercontent.com/23263723/119219471-680e5d80-bb03-11eb-99f9-c37f259047cc.png)

  4. Additional information 
Works properly in Noto Sans Grantha

### Character data

𑌤𑍍𑌰𑌿
 ‎11324 GRANTHA LETTER TA
 ‎1134D GRANTHA SIGN VIRAMA
 ‎11330 GRANTHA LETTER RA
 ‎1133F GRANTHA VOWEL SIGN I

**Comment by punchcutter** [comment]
Not sure how that happened, but fixed now.

<img width="257" alt="2089" src="https://user-images.githubusercontent.com/11257204/120070710-db493e00-c0c6-11eb-8a2c-123deae2ffb6.png">
