### ISSUE TITLE
Old Italic - wrong/outdated downloads

### ISSUE THREAD

**Issue by julifos** [googlefonts/noto-fonts#2093]
## Defect Report
Fonts obtained here are defective: [https://www.google.com/get/noto/#sans-ital](https://www.google.com/get/noto/#sans-ital)
Also, they come pre-installed in the latest macOS versions, ie [Catalina](https://support.apple.com/en-us/HT210192) and [Big Sur](https://support.apple.com/en-us/HT211240).
They look mirrored (ie, etruscan) and some characters are wrong (ie, 0x10313), everything according to the [Unicode display](http://www.unicode.org/charts/PDF/U10300.pdf).
![image](https://user-images.githubusercontent.com/34552256/120289606-c5539d00-c2c1-11eb-9098-0d897e502430.png)

### Title 
Old Italic at Google site - wrong/outdated downloads

### Font 
NotoSansOldItalic-Regular.ttf
[NotoSansOldItalic-unhinted.zip](https://github.com/googlefonts/noto-fonts/files/6574571/NotoSansOldItalic-unhinted.zip)

### Where the font came from, and when
[https://www.google.com/get/noto/#sans-ital](https://www.google.com/get/noto/#sans-ital)
Also pre-installed in macOS Catalina, my current OS, at:
`/System/Library/Fonts/Supplemental/NotoSansOldItalic-Regular.ttf`
Date: 2021-06-01 (preferred format)

### Font Version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0
The version obtained at Github says "Version 2.002"

### OS name and version
Doesn't apply.

### Application name and version
Doesn't apply.

### Issue
  1. Steps to reproduce
Download from here: [https://www.google.com/get/noto/#sans-ital](https://www.google.com/get/noto/#sans-ital)
  2. Observed results
The installed font coming from the Google official website (or preinstalled in the latest macOS operative systems) displays different characters from those expected.
  3. Expected results
 Whether you prefer one or another scripts or writing systems, I think this font should be consistent with the Unicode representation, as it is used worldwide to represent different writing systems which are NOT equal, so different people will see different glyphs depending on the installed version of "Noto Sans Old Italic"
  4. Additional information 
The fonts obtained at Github are OK: [https://github.com/googlefonts/noto-fonts/tree/master](https://github.com/googlefonts/noto-fonts/tree/master)
These aren't mirrored, wrong characters are fixed, etc.

### Screenshot
Google website and Apple pre-installed:
![image](https://user-images.githubusercontent.com/34552256/120290436-a0abf500-c2c2-11eb-90ee-ac73d1a20cf2.png)
Versus Github version:
![image](https://user-images.githubusercontent.com/34552256/120290498-ac97b700-c2c2-11eb-92e4-202b4d5a630d.png)

**Comment by simoncozens** [comment]
macOS Monterey now ships Old Italic 2.002, and the Noto web site has been updated to the latest versions.
