### ISSUE TITLE
[NotoSansMono] Unusual glyph confusability between "W" "Ѡ" and "w" "ѡ"

### ISSUE THREAD

**Issue by MasterInQuestion** [googlefonts/noto-fonts#2104]
> For proper representation of this message: https://pastebin.com/raw/nqPs0x7K

Test sample:
[W Ѡ w ѡ]

Character Sequence:

1. "W" (Latin Capital Letter W) (U+0057, 0x57, &#87;)
2. "Ѡ" (Cyrillic Capital Letter Omega) (U+0460, 0xD1A0, &#1120;)
3. "w" (Latin Small Letter W) (U+0077, 0x77, &#119;)
4. "ѡ" (Cyrillic Small Letter Omega) (U+0461, 0xD1A1, &#1121;)

The behavior seems to be unusual. References:
* https://decodeunicode.org/en/u+00460
* https://www.unicode.org/charts/nameslist/n_0400.html#0460
* https://util.unicode.org/UnicodeJsps/confusables.jsp?a=%D1%A0%D1%A1

Their shape in "Roboto Mono" (https://github.com/googlefonts/RobotoMono/blob/26adf5193624f05ba1743797d00bcf0e6bfe624f/fonts/ttf/RobotoMono-Light.ttf) looks alright.

Tested fonts:
* Noto Sans Mono Light ("NotoSansMono-Light.ttf") (https://github.com/googlefonts/noto-fonts/blob/3993960e34d5f3e61fdacd3c835d3da6b6d2258f/hinted/ttf/NotoSansMono/NotoSansMono-Light.ttf)
* Noto Sans Mono Regular ("NotoSansMono-Regular.ttf") (https://github.com/googlefonts/noto-fonts/blob/3993960e34d5f3e61fdacd3c835d3da6b6d2258f/hinted/ttf/NotoSansMono/NotoSansMono-Regular.ttf)

**Comment by simoncozens** [comment]
I'm not convinced this is a bug - the glyphs *are* confusable, which is why they appear in the confusables list. And they are distinct: the Cyrillic forms have clearly rounded sides, compared to the Latin. Noto isn't wrong here; I think this just a matter of stylistic preference.

**Comment by MasterInQuestion** [comment]
<pre style="white-space: pre-wrap; word-wrap: break-word; tab-size: 4">
	[ Quote simoncozens @ CE 2022-04-22 13:57:48 UTC:
https://github.com/googlefonts/noto-fonts/issues/2104#issuecomment-1106544119
	I'm not convinced this is a bug - the glyphs are confusable, which is why they appear in the confusables list. ]
<^>	I suppose such confusability should be reduced, as much as possible.
	.
	[ Quote simoncozens @ CE 2022-04-22 13:57:48 UTC:
https://github.com/googlefonts/noto-fonts/issues/2104#issuecomment-1106544119
	And they are distinct: the Cyrillic forms have '''clearly rounded sides''', compared to the Latin. Noto isn't wrong here; ... ]
<^>	Distinct?..
	<img src="https://user-images.githubusercontent.com/81106051/169278522-dc0ef81c-434e-48fc-87ef-6e00022cebfe.png" alt="[ &quot;WwѠѡ.png&quot; ]" />
	Line 1 of the image is the test sample rendered with "Noto Sans Mono"; line 2 rendered with "Roboto Mono".
	.
	Their behavior with other fonts (observable in the references) also indicates Noto's design (on this aspect) has been unusual.
</pre>
