### ISSUE TITLE
Gujarati fonts should support Transliteration symbols (0AFA - 0AFF)

### ISSUE THREAD

**Issue by lateef-shaikh** [googlefonts/noto-fonts#2105]
## Defect Report
Please include full support of Transliteration symbols (0AFA - 0AFF) in Gujarati fonts.
Here is the [URL](https://unicode.org/L2/L2015/15103r-gujarati-arabic-translit.pdf) of the Unicode proposal that explains these symbols.

### Title 
Gujarati font should support Transliteration symbols (0AFA - 0AFF)

### Font 
NotoSansGujarati-Bold.ttf
NotoSansGujarati-Regular.ttf
NotoSansGujaratiUI-Bold.ttf
NotoSansGujaratiUI-Regular.ttf
NotoSerifGujarati-Bold.ttf
NotoSerifGujarati-Regular.ttf

### Where the font came from, and when
Site: https://www.google.com/get/noto/#sans-gujr
Date: 2021-06-29

### Font Version
Serif 1.02
Sans 1.03

### OS name and version
Windows 10

### Character data
Characters from U+0AFA to U+0AFF are not supported

**Comment by Mercury13** [comment]
Really? IMHO, they are present…
![image](https://user-images.githubusercontent.com/10164882/131250759-d6b598fe-fa31-418d-9f6b-821643d97ce8.png)

**Comment by Mercury13** [comment]
So last repo is OK, Google just needs to update offsite.

**Comment by lateef-shaikh** [comment]
> So last repo is OK, Google just needs to update offsite.

Thank you!

**Comment by lateef-shaikh** [comment]
Closing the issue.
