### ISSUE TITLE
Compact Old Hungarian UI font required with minimal amount of ligatures, like small and capital 'q','w','y','x', "dz" and "dzs"

### ISSUE THREAD

**Issue by viktorkiwikovacs** [googlefonts/noto-fonts#2109]
## Defect Report
The font:
https://github.com/googlefonts/noto-fonts/blob/main/unhinted/ttf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf font still isn't done, because more syllable like ligatures are missing, several of them have wrong form or definition. That font require more development time.
Although an Old Hungarian  UI font under the development, the developers didn't published it, I don't know why.
As I know that font doesn't have the minimal required ligatures, such as "q", "w", "y", "x", "dz", "dzs". 
These ligatures or letters didn't have Unicode code points, must not to assign to direct code points. 
The Noto-fonts project isn't an official standardization body. 
The last two comments are for @rovasinfo and the Rovas Foundation.

**Comment by viktorkiwikovacs** [comment]
@davelab6 @marekjez86 I upload the form of the minimal required ligatures, as soon as I can.

**Comment by sztupy** [comment]
The N4268R unicode proposal is the closest standard on how to address the issue of missing dz/dzs/etc from the Old Hungarian range, and fonts if they want to support these letters should adhere to that. See also https://oldhungarian.eu/index_en.html#notes

**Comment by viktorkiwikovacs** [comment]
@sztupy Thanks for the comment https://github.com/googlefonts/noto-fonts/issues/2109#issuecomment-875777864

**Comment by tamasbartos** [comment]
@marekjez86 Please sign this issue with the label "old hungarian". If you will not to do, please drop me a comment, why.

**Comment by viktorkiwikovacs** [comment]
It seems, I will not labelled as "Old Hungarian script". See #2065 issue. I close it.

**Comment by viktorkiwikovacs** [comment]
Sory: It will not...
