### ISSUE TITLE
Missing syllable like ligatures from NotoSansOldHungarian-Regular font

### ISSUE THREAD

**Issue by viktorkiwikovacs** [googlefonts/noto-fonts#2110]
## Defect Report
The https://github.com/googlefonts/noto-fonts/blob/main/unhinted/ttf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf
has syllable-like ligatures (some of them has wrong forms), but by logic of Hungarian language thete is a must to develope at least all consonant+vowel combinations.
Missing from this font capital ligature "q","w","x" and "y", ligature "y" has forn problem, and "dz", "dzs" aren't developed at all.
In the submission https://www.unicode.org/wg2/docs/n4268.pdf 
are several ligature definitions by handwriting, but this line of standardization process unfortunatelly stopped.
If all syllable-like ligatures won't be developed, all ligatures must be removed, because of the logic of the Hungarian language (except "q", "w", "y" and  "x") and add "dz", "dzs".
In the last case (remove the ligatures) aren't required two kind of Old Hungarian fonts.
Same baseline of small and capital letters are required, too.

I'll upload the screensots of missing syllables, and given syllables, as soon as it possible.

**Comment by tamasbartos** [comment]
@marekjez86 May I ask you to sign it with the label "old hungarian". This issue will be a "container" issue.

**Comment by tamasbartos** [comment]
@marekjez86 If you will not to sign this issue as "old hungarian", please drop me a comment that why will not to do.

**Comment by viktorkiwikovacs** [comment]
It seems, it will not signed as " Old Hungarian script" because of the issue #2065 I close it.
