### ISSUE TITLE
Malayalam Akhands (feature akhn) typed using ZWJ (U+200D)

### ISSUE THREAD

**Issue by hedavids** [googlefonts/noto-fonts#2115]
### Title 
  >   Malayalam Akhands (feature akhn) typed using ZWJ (U+200D)

### Font 
  >   NotoSansMalayalam-Regular.ttf

### Where the font came from, and when
  >   Site: https://github.com/googlefonts/noto-fonts/blob/main/hinted/ttf/NotoSansMalayalam/NotoSansMalayalam-Regular.ttf
  >   Date: 2020-10-02 (preferred format)

### Font Version
  >   2001; ttfautohint (v 1.8.2)

### OS name and version
  >   Windows 10,9,19042 Build 19042 Pro

### Application name and version
  >   All applications

### Issue
  >   We are enquiring to get more information regarding the need of using the ZWJ (U+200D) for a number of the Malayalam Akhands (ligatures). It will really help us when we support the Malayalam translation teams to explain the reasoning behind the decision. This way we will make sure to follow industry standard.

  1. As an example using the above mentioned font type ക ് ട (all Malayalam fonts Sans and Serif have the same behavior)
  2. This keeps the Virama explicit and does not combine as an Akhand (ligature)
  3. Can you confirm why this is the expected behavior?
  4. If you type ക ZWJ (U+200D) ് ട you get the Akhand. This, of course, involves one more keystroke.
  5. There are eight such Akhands (ligatures), please see this link for more details: https://github.com/googlefonts/noto-source/blob/d021c973cfe650df25672acc3015a36a09f57b61/src/NotoSansMalayalam/Noto Sans Malayalam GSUB.txt#L104-L112

### Character data
![No ZWJ vs with ZWJ](https://user-images.githubusercontent.com/75686860/126972397-39d74bcc-1136-4341-a333-4366c5311d65.png)
  >   U+0D15 U+0D4D U+0D1F without ZWJ (Note the font in the browser behaves differently than the Noto fonts)
  >   U+0D15 U+200D U+0D4D U+0D1F ക‍്ട with ZWJ (Note the font in the browser behaves differently than the Noto fonts)

### Screenshot
  >   See attached screenshot.

**Comment by cibu** [comment]
This is done as per the Unicode standards specification [Chapter 12.9](https://www.unicode.org/versions/Unicode14.0.0/ch12.pdf) Sections *Requesting Traditional Ligatures* and *Requesting Open Forms of Conjuncts* in page 521. Essentially, it says:

`<Consonant, ZWJ, VIRAMA, Consonant>` produces traditional cursive form and `<Consonant, ZWNJ, VIRAMA, Consonant>` non-cursive open form.
