### ISSUE TITLE
add Ruble sign (U+20BD) to Phase II Noto Sans and Serif (LGC)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#216]
```
Please add the symbol of the ruble.
```

Original issue reported on code.google.com by `livan97....@gmail.com` on 4 Dec 2014 at 5:10

**Comment by fontguy** [comment]
Should consider adding other currency symbols and a few others from the Symbol fonts to LGC.

**Comment by jungshik** [comment]
Yes. We did (or plan to do)  something similar for Roboto and should do more or less the same for Tinos/Arimo.   @roozbehp

**Comment by marekjez86** [comment]
@dougfelt : I have assigned it to you to decide on what's the right thing to do (per the policy that you've been developing). We'll do what you recommend :-)

**Comment by xiangyexiao** [comment]
Does it matter for Android since Ruble sign (U+20BD) is covered by Noto Sans Symbols? We do plan to add it in Phase III LGC fonts.

**Comment by roozbehp** [comment]
Since the Ruble has been encoded for quite a while now, it has very frequent usage, and the style it uses takes serifs, we need this in Noto Serif and Noto Serif Bold. Showing the ruble sign in sans style when the user has asked for a serif style is no longer good enough.

**Comment by xiangyexiao** [comment]
verified that Ruble sign (U+20BD) has been covered by Phase 3 Noto Serif. Assign it to Jungshik to add it into Phase 2 Noto Serif and Noto Serif Bold.

**Comment by marekjez86** [comment]
Tinos and Arimo has it. Phase III Noto has it. @jungshik only remaining: xiangyexiao comment from Mar 7 (if we need it there).

**Comment by marekjez86** [comment]
Verified the Rubel sign is present in Phase III:
NotoSans
NotoSans Italic
NotoSansDisplay
NotoSansDisplay Italic
NotoSerif
NotoSerif Italic
NotoSerifDisplay
NotoSerifDisplay Italic

Per Xiangye "Jungshik to add it into Phase 2 Noto Serif and Noto Serif Bold."

**Comment by nizarsq** [comment]
U+20BD currently in NotoSans,NotoSansMono and NotoSerif.
<img width="576" alt="Screen Shot 2020-07-23 at 8 47 17 PM" src="https://user-images.githubusercontent.com/22158882/88358923-b3aa7c00-cd25-11ea-8b2f-f89e1216f3ee.png">
