### ISSUE TITLE
Noto Nastaliq support for U+08C7 LAM WITH SMALL TAH

### ISSUE THREAD

**Issue by lateef-shaikh** [googlefonts/noto-fonts#2163]
### Title 
Noto Nastaliq support for U+08C7 LAM WITH SMALL TAH

### Font 
NotoNastaliqUrdu-Regular.ttf
NotoNastaliqUrdu-Bold.ttf

### Issue
This is actually a request not an issue. Can you please add U+08C7 (ARABIC LETTER LAM WITH SMALL ARABIC
LETTER TAH ABOVE) to Noto Nastaliq font? It's shape is similar to Arabic Laam (U+0644).

**Comment by 336459** [comment]
^^ 08C7 is used in Shahmukhi Punjabi which also uses the Nastaliq writing style. Would also appreciate if the character could be supported by this font.

**Comment by simoncozens** [comment]
This character is already supported in the font. (At least in Version 2.001)
