### ISSUE TITLE
Noto Nastaliq support for 5 Hindko characters U+08BE - U+08C2

### ISSUE THREAD

**Issue by lateef-shaikh** [googlefonts/noto-fonts#2164]
### Title 
Noto Nastaliq support for 5 Hindko characters U+08BE - U+08C2

### Font 
NotoNastaliqUrdu-Regular.ttf
NotoNastaliqUrdu-Bold.ttf

### Issue
This is actually a request not an issue. 

Can you please add following Hindko characters to Noto Nastaliq font? 

1. U+08BE - ARABIC LETTER PEH WITH SMALL V. It's shape is similar to U+067E (Arabic Letter Peh)
2. U+08BF - ARABIC LETTER TEH WITH SMALL V. It's shape is similar to U+062A (Arabic Letter Teh)
3. U+08C0 - ARABIC LETTER TTEH WITH SMALL V. It's shape is similar to U+0679 (Arabic Letter Tteh)
4. U+08C1 - ARABIC LETTER TCHEH WITH SMALL V. It's shape is similar to U+0686 (Arabic Letter Tcheh)
5. U+08C2 - ARABIC LETTER KEHEH WITH SMALL V. It's shape is similar to U+06A9 (Arabic Letter Keheh)

**Comment by simoncozens** [comment]
These characters are included in version 2.001.
