### ISSUE TITLE
Overlapping Vithkuqi u and y

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#2167]
### Font
NotoSerifVithkuqi-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/98c892d27a4218fed175349d798673e171a58cc2/unhinted/otf/NotoSerifVithkuqi/NotoSerifVithkuqi-Regular.otf
Date: 2021-10-27

### Font version
Version 1.001

### Issue
All four combinations of U+105B7 VITHKUQI SMALL LETTER U and U+105BB VITHKUQI SMALL LETTER Y are kerned too closely, causing overlap.

### Character data
𐖻𐖷
U+105BB VITHKUQI SMALL LETTER Y
U+105B7 VITHKUQI SMALL LETTER U

### Screenshot
![𐖻𐖷](https://user-images.githubusercontent.com/1124347/139325044-708f9d9b-fb56-4453-b362-2d1f0758aa4a.png)

**Comment by marekjez86** [comment]
Should be fixed ... Please see, for example, https://github.com/googlefonts/noto-fonts/tree/main/unhinted/ttf/NotoSerifVithkuqi
