### ISSUE TITLE
Add digits to Noto Sans Hebrew (and other Hebrew fonts)

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#2175]
a user comment (enhancement request): 
"The Hebrew font ״Noto Sans Hebrew״ has no digits 😥
Is it known when there will be an update and it will also have digits?
This font is really beautiful and it is impossible to embed it in designing a website without numbers (:

Thank you very much for adding more fonts in Hebrew!
from all of us, Israels designers  🙌🍭"

**Comment by simoncozens** [comment]
Merging into #2257.
