### ISSUE TITLE
Sample text for Ethiopian used old orthography

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#218]
```
The font has two dots ( : ) after every word, this type of writing is very old 
and none of the modern writings follow this way. I think spaces should just be 
spaces without the two dots.

```

Original issue reported on code.google.com by `mhret...@gmail.com` on 8 Dec 2014 at 10:13

**Comment by behdad** [comment]
cc @fontguy @roozbehp

**Comment by nizarsq** [comment]
https://www.google.com/get/noto/#sans-ethi currently showing ( : ) after every word.
<img width="1262" alt="Screen Shot 2020-08-01 at 10 26 39 PM" src="https://user-images.githubusercontent.com/22158882/89116195-15659700-d446-11ea-9855-96d1921d1cf2.png">

**Comment by nizarsq** [comment]
@marekjez86 any idea if ( : ) after every word is intentional?

**Comment by simoncozens** [comment]
The redesigned sample page for Noto Serif Ethiopic (https://fonts.google.com/noto/specimen/Noto+Serif+Ethiopic) now has a variety of styles and languages, some of which use the ETHIOPIC WORDSPACE character and some of which do not.

<img width="552" alt="Screenshot 2022-02-28 at 20 12 28" src="https://user-images.githubusercontent.com/106728/156051867-d4754555-eb57-4f95-b866-f474e7baffea.png">
