### ISSUE TITLE
2021.12.16 update: script tags missing for Mahajani?

### ISSUE THREAD

**Issue by satbyy** [googlefonts/noto-fonts#2189]
## Defect Report

`SCRIPT_TO_OPENTYPE_SCRIPT_TAG[ ]` lookup fails for Mahajani. 

### Title 

`SCRIPT_TO_OPENTYPE_SCRIPT_TAG[ ]` lookup fails for Mahajani. 

However, the error does not appear for Brahmi, Lepcha, Khudawadi etc. which were also updated yesterday. It happens only with Mahajani.

### Font 

hinted/ttf/NotoSansMahajani/NotoSansMahajani-Regular.ttf

### Where the font came from, and when

https://github.com/googlefonts/noto-fonts/commit/0605802b5810ac022ce0bbea43701a4f005c22f3

2021-12-16

### Font Version

``` 
otfinfo -i NotoSansMahajani-Regular.ttf

Family:              Noto Sans Mahajani
Subfamily:           Regular
Full name:           Noto Sans Mahajani Regular
PostScript name:     NotoSansMahajani-Regular
Version:             Version 2.002; ttfautohint (v1.8) -l 8 -r 50 -G 200 -x 14 -D latn -f none -a qsq -X ""
Unique ID:           2.002;GOOG;NotoSansMahajani-Regular
Description:         Designed by Monotype design team.
```

### Issue

I noticed that `merge_fonts.py` script broke on my [project pipeline](https://github.com/satbyy/go-noto-universal/runs/4557041692?check_suite_focus=true#step:4:133) after yesterday's update.

```
  File "/home/runner/work/go-noto-universal/go-noto-universal/nototools/nototools/merge_fonts.py", line 230, in main
    valid_files[idx] = add_gsub_to_font(file)
  File "/home/runner/work/go-noto-universal/go-noto-universal/nototools/nototools/merge_noto.py", line 115, in add_gsub_to_font
    script_record.ScriptTag = get_opentype_script_tag(fontfile)
  File "/home/runner/work/go-noto-universal/go-noto-universal/nototools/nototools/merge_noto.py", line 96, in get_opentype_script_tag
    return SCRIPT_TO_OPENTYPE_SCRIPT_TAG[fontfile]
KeyError: 'Mahajani'
```

It used to work fine before the update on 2021-12-16.

**Comment by simoncozens** [comment]
The recent rebuild of Mahajani no longer has a GSUB table, as there are no script specific substitutions. (There are script specific positioning rules, so we have a GSUB table.) 

We could add a dummy GSUB table but that really feels like a hack. I’m not yet familiar with nototools but it looks like we have tooling which relies on having a GSUB table even if it has no lookups, to detect the script. Perhaps it would be better to check for presence of GSUB or GPOS.

**Comment by satbyy** [comment]
Thanks. I think I can workaround the absence of GSUB. There is no need to add a dummy table just for the sake of it.
