### ISSUE TITLE
Bad weights on Nastaliq Urdu Bold and Myanmar Bold

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/noto-fonts#2210]
NotoNastaliqUrdu-Bold.ttf weight 700 outside font capability 400..400, NotoSerifMyanmar-Bold.ttf weight 700 outside font capability 400..400

I am amending the test to expect this (so it can pass again); remove that expectation once fixed

**Comment by rsheeter** [comment]
Reminder to remove changes in #2211 once fonts are fixed

**Comment by marekjez86** [comment]
Fixed
