### ISSUE TITLE
Question: Is it possible to have the whole Noto Fonts collection (CJK + non-CJK) as a .TTC file?

### ISSUE THREAD

**Issue by joachimesque** [googlefonts/noto-fonts#2217]
I'm using Python Pillow to generate images containing text in multiple languages and scripts. Python Pillow doesn't allow fallback fonts—the single font file must contain all the glyphs that will be used in the text.

Right now I'm using Adobe's Source Han Sans, which allows me to use CJK scripts and Latin/Cyrillic/Greek scripts. The font collection is packaged in a TTC file. I noticed that Noto-CJK fonts are also available as a single TTC file.

Would it be possible to compile the Noto font collection, with CJK and non-CJK scripts, as a single TTC file? I understand that there would be some choices to be made (`*-UI` fonts for Arabic scripts, for example), but apart from that, does a TTC file have the same glyphs number limit as a TTF file?

Thank you!

**Comment by punchcutter** [comment]
A TTC file is just a collection of TTFs or OTFs kind of like a zip file. It doesn't overcome the limits of glyph count so even if you have millions of glyphs like the Noto CJK Super OTC they will still show as separate fonts to applications.

**Comment by simoncozens** [comment]
This is another "adding bits of some font into another font" question so I'm going to merge it into #2257.
