### ISSUE TITLE
rendering error in Noto Serif Tibetan

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#2218]
¶ Overview
Here is a possible rendering error by Noto Serif Tibetan.

¶ Description
Text:	སམྦྷོ་ཊ་
U+0F66 U+0F58 U+0FA6 U+0FB7 U+0F7C U+0F0B U+0F4A U+0F0B
“sambhoṭa”

Correct rendering (Kailasa):
<img width="457" alt="Screen Shot 2022-01-20 at 15 22 51" src="https://user-images.githubusercontent.com/13322623/150437874-779be57e-ee85-478d-9b25-3d588aef1dcc.png">

Incorrect rendering (Noto Serif Tibetan):
<img width="453" alt="Screen Shot 2022-01-20 at 15 22 34" src="https://user-images.githubusercontent.com/13322623/150437890-3239af82-db63-4166-8173-72936e101cdb.png">

Note the duplication of the letter བ (b).
¶ Similar behavior and affected characters

Same behavior when U+0FA6 U+0FB7 is replaced with U+0FA7.

Same behavior with སིདྡྷྰརྠ་ “siddhārtha”, where the letter ད (d) is rendered to appear thrice instead of twice.
U+0F66 U+0F72 U+0F51 U+0FA1 U+0FB7 U+0FB0 U+0F62 U+0FA0 U+0F0B
<img width="410" alt="Screen Shot 2022-01-20 at 15 22 18" src="https://user-images.githubusercontent.com/13322623/150437922-c55e73af-11dc-48f6-807e-31eeea83ef89.png">

This word is even rendered incorrectly by Kailasa, in a different way.

Affected characters include:
U+0F93 TIBETAN SUBJOINED LETTER GHA
U+0F9D TIBETAN SUBJOINED LETTER DDHA
U+0FA2 TIBETAN SUBJOINED LETTER DHA
U+0FA7 TIBETAN SUBJOINED LETTER BHA
U+0FAC TIBETAN SUBJOINED LETTER DZHA
U+0FB9 TIBETAN SUBJOINED LETTER KSSA
And their equivalent sequences, such as U+0F92 U+0F87 for U+0F93 (see U+0F00 chart for details)
These characters are used in Tibetan transcriptions of Sanskrit.

**Comment by dscorbett** [comment]
This is #1528.
