### ISSUE TITLE
Kashmiri letter e doesn't work in Nastaliq Urdu font

### ISSUE THREAD

**Issue by r12a** [googlefonts/noto-fonts#2219]
### Font 
NotoNastaliqUrdu-Regular.ttf

### Where the font came from, and when

https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf/
installed today

2022-01-28

### Font Version
2.000;GOOG;NotoNastaliqUrdu-Regular

### OS name and version
macOS 12.1

### Application name and version
Browsers

### Issue
The sound /e/ is represented in Kashmiri using:
یٚ [U+06CC ARABIC LETTER FARSI YEH + U+065A ARABIC VOWEL SIGN SMALL V ABOVE]

The small sign v above appears to be missing from the Noto Nastaliq Urdu font, and the result is that when used medially this letter fails to join to the left.  This is obviously a big problem for using the Noto font for Kashmiri text. 

### Character data

You can find a list of lemmas containing this sequence at https://r12a.github.io/scripts/arabic/ks_vocab?q=%DB%8C%D9%9A.

Here are the top 4 from the list, using the Noto Nastaliq Urdu font.

![Screenshot 2022-01-28 at 12 15 45](https://user-images.githubusercontent.com/4839211/151545442-5f2ade73-4fd4-4dec-a70b-c62ed183f083.png)

Here's what it looks like using SIL's Awami Nastaliq font:

![Screenshot 2022-01-28 at 12 18 54](https://user-images.githubusercontent.com/4839211/151545833-cb20f2b6-9405-4fd5-a2dd-45267d3c4675.png)

**Comment by r12a** [comment]
In case it helps, here are some notes about Kashmiri:  https://r12a.github.io/scripts/arabic/kashmiri

**Comment by simoncozens** [comment]
U+065A was encoded in Noto Nastaliq Urdu 3.001, so this will work as of the next release:

$ shape master_ttf/NotoNastaliqUrdu-Regular.ttf 'آشیٚنؠ' --language=ks
[YehKashmiriFin=5+466|OneDotAboveNS=4@65,-113+0|BehxMed.inT2outD2Y=4@0,379+294|ArSevenAboveNS=2@127,41+0|TwoDotsBelowNS=2@219,268+0|BehxMed.inT1outT2=2@0,429+184|ThreeDotsUpAboveNS=1@330,146+0|sp0=1+0|SeenIni=1@0,494+607|MaddaNS=0@211,18+0|AlefSep=0+330]
![shape](https://user-images.githubusercontent.com/106728/151566238-c8de2aee-a8ca-434d-9f3b-7afcfed24ab7.png)

**Comment by r12a** [comment]
Terrific. Thanks!
