### ISSUE TITLE
Noto Nastaliq Urdu should produce rounded hamzas for Kashmiri text

### ISSUE THREAD

**Issue by r12a** [googlefonts/noto-fonts#2220]
### Font 
NotoNastaliqUrdu-Regular.ttf

### Where the font came from, and when

https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf/
installed today

2022-01-28

### Font Version
2.000;GOOG;NotoNastaliqUrdu-Regular

### OS name and version
macOS 12.1

### Application name and version
Browsers

### Issue

The Noto Nastaliq Urdu font produces s-shaped glyphs for combining hamzas.  Kashmiri, however, generally uses the rounded shapes.  It would be good to use rounded hamzas if the font detects that the language of the content is Kashmiri.

The following shows hamzas using the Noto font:
![Screenshot 2022-01-28 at 11 47 35](https://user-images.githubusercontent.com/4839211/151548295-0b28748f-aae8-4d47-a4a8-e50bd6c829b8.png)

Here is the same text using SIL's Awami Nastaliq font (with appropriate font settings to produce the expected glyphs):
![Screenshot 2022-01-28 at 11 47 26](https://user-images.githubusercontent.com/4839211/151548380-fea2ccb0-2897-4062-95d6-cea816b3b13d.png)

Note that the wavy hamza does have the rounded shape.

The images above were taken from https://r12a.github.io/scripts/arabic/kashmiri#vowel_letters

For sample lemmas containing hamzas, see https://r12a.github.io/scripts/arabic/ks_vocab?q=%D8%A5%7C%D9%95%7C%D8%A3%7C%D9%94

**Comment by r12a** [comment]
In case it helps, here are some notes about Kashmiri:  https://r12a.github.io/scripts/arabic/kashmiri

**Comment by simoncozens** [comment]
I'm afraid I can't reproduce this:

```
simon@Simons-Air ~/tmp $ curl -so NotoNastaliqUrdu-Regular.ttf https://raw.githubusercontent.com/googlefonts/noto-fonts/master/hinted/ttf/NotoNastaliqUrdu/NotoNastaliqUrdu-Regular.ttf
simon@Simons-Air ~/tmp $ shape NotoNastaliqUrdu-Regular.ttf 'إ◌ٕ◌ٕ اٟ◌ٟ◌ٟ' --language=ks
[WavyHamzaBelowNS=10@391,121+0|uni25CC=10+789|WavyHamzaBelowNS=8@391,121+0|uni25CC=8+789|WavyHamzaBelowNS=6@103,119+0|AlefSep=6+330|space=5+132|HamzaBelowAF_NS=3@391,116+0|uni25CC=3+789|HamzaBelowAF_NS=1@391,116+0|uni25CC=1+789|HamzaBelowAF_NS=0@103,114+0|AlefSep=0+330]
```

![shape](https://user-images.githubusercontent.com/106728/151563910-6f6e9e0c-8280-4e40-bccf-903be269a05b.png)

Maybe the browser isn't feeding the language tag to the shaping engine properly?

**Comment by r12a** [comment]
Aaah!  Apologies. I put this issue together quickly this morning because i saw that you were fixing Kashmiri stuff, and i missed something. I added font-language-override: 'URD' to my CSS to get around the problem with jazm (which you just fixed, so i won't need to do that any more). I think that that's what's applying the s-shaped hamza.  I agree that it seems to work ok in normal use of the font. Sorry again about the noise.
