### ISSUE TITLE
U+11941 DIVES AKURU INITIAL RA is confused with U+11942 DIVES AKURU MEDIAL RA

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#2223]
### Font
NotoSerifDivesAkuru-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/d2d73ba685c04742e5a2db2b8bcedaaa08bde0af/unhinted/otf/NotoSerifDivesAkuru/NotoSerifDivesAkuru-Regular.otf
Date: 2022-01-28

### Font version
Version 1.000

### Issue
<i>Rki</i> and <i>rshi</i> look like <i>kri</i> and <i>shri</i>, but they should use the glyph of the initial <i>r</i> rather than the medial <i>r</i>.

### Character data
𑥁𑤌𑤱𑤌𑥂𑤱
U+11941 DIVES AKURU INITIAL RA
U+1190C DIVES AKURU LETTER KA
U+11931 DIVES AKURU VOWEL SIGN I
U+1190C DIVES AKURU LETTER KA
U+11942 DIVES AKURU MEDIAL RA
U+11931 DIVES AKURU VOWEL SIGN I
𑥁𑤪𑤱𑤪𑥂𑤱
U+11941 DIVES AKURU INITIAL RA
U+1192A DIVES AKURU LETTER SHA
U+11931 DIVES AKURU VOWEL SIGN I
U+1192A DIVES AKURU LETTER SHA
U+11942 DIVES AKURU MEDIAL RA
U+11931 DIVES AKURU VOWEL SIGN I

### Screenshot
![𑥁𑤌𑤱𑤌𑥂𑤱 𑥁𑤪𑤱𑤪𑥂𑤱](https://user-images.githubusercontent.com/1124347/151706616-a451db66-5989-4075-bf7d-b3d31e068b0b.png)

**Comment by sergiolmartins** [comment]
Apparently I don't know how to tag issues. This should be solved as of #googlefonts/noto-source/pull/498.

**Comment by dscorbett** [comment]
This should be reopened. <i>Rki</i> still looks like <i>kri</i> and <i>rshi</i> still looks like <i>shri</i>. The only change in the new version is that <i>kri</i> and <i>shri</i> look slightly worse than they originally did, whereas <i>rki</i> and <i>rshi</i> are unchanged.
![𑥁𑤌𑤱𑤌𑥂𑤱 𑥁𑤪𑤱𑤪𑥂𑤱](https://user-images.githubusercontent.com/1124347/164779029-42f736eb-ac04-4dff-be73-8f80e64ff70f.png)
