### ISSUE TITLE
Inconsistent ligation in Noto Serif Dives Akuru

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#2226]
### Font
NotoSerifDivesAkuru-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/d2d73ba685c04742e5a2db2b8bcedaaa08bde0af/unhinted/otf/NotoSerifDivesAkuru/NotoSerifDivesAkuru-Regular.otf
Date: 2022-01-28

### Font version
Version 1.000

### Issue
This font includes some ligatures for certain glyphs but lacks ligatures for closely related glyphs. For example, there is consonant–vowel ligature in <i>dhī</i> but no analogous ligature in <i>ndhī</i>. In the screenshot below, each row has two clusters: the first includes a ligature and the second lacks that ligature where it would be appropriate.

### Character data
𑤬𑤾𑤠𑥂𑤬𑤾𑤠
U+1192C DIVES AKURU LETTER SA
U+1193E DIVES AKURU VIRAMA
U+11920 DIVES AKURU LETTER PA
U+11942 DIVES AKURU MEDIAL RA
U+1192C DIVES AKURU LETTER SA
U+1193E DIVES AKURU VIRAMA
U+11920 DIVES AKURU LETTER PA
𑤞𑤱𑤟𑤾𑤞𑤱
U+1191E DIVES AKURU LETTER DHA
U+11931 DIVES AKURU VOWEL SIGN I
U+1191F DIVES AKURU LETTER NA
U+1193E DIVES AKURU VIRAMA
U+1191E DIVES AKURU LETTER DHA
U+11931 DIVES AKURU VOWEL SIGN I
𑤞𑤲𑤟𑤾𑤞𑤲
U+1191E DIVES AKURU LETTER DHA
U+11932 DIVES AKURU VOWEL SIGN II
U+1191F DIVES AKURU LETTER NA
U+1193E DIVES AKURU VIRAMA
U+1191E DIVES AKURU LETTER DHA
U+11932 DIVES AKURU VOWEL SIGN II
𑤞𑤳𑤟𑤾𑤞𑤳
U+1191E DIVES AKURU LETTER DHA
U+11933 DIVES AKURU VOWEL SIGN U
U+1191F DIVES AKURU LETTER NA
U+1193E DIVES AKURU VIRAMA
U+1191E DIVES AKURU LETTER DHA
U+11933 DIVES AKURU VOWEL SIGN U
𑤖𑤽𑤖𑤾𑤖𑤽
U+11916 DIVES AKURU LETTER TTA
U+1193D DIVES AKURU SIGN HALANTA
U+11916 DIVES AKURU LETTER TTA
U+1193E DIVES AKURU VIRAMA
U+11916 DIVES AKURU LETTER TTA
U+1193D DIVES AKURU SIGN HALANTA
𑤢𑤽𑤤𑤾𑤢𑤽
U+11922 DIVES AKURU LETTER BA
U+1193D DIVES AKURU SIGN HALANTA
U+11924 DIVES AKURU LETTER MA
U+1193E DIVES AKURU VIRAMA
U+11922 DIVES AKURU LETTER BA
U+1193D DIVES AKURU SIGN HALANTA
𑤞𑤽𑤟𑤾𑤞𑤽
U+1191E DIVES AKURU LETTER DHA
U+1193D DIVES AKURU SIGN HALANTA
U+1191F DIVES AKURU LETTER NA
U+1193E DIVES AKURU VIRAMA
U+1191E DIVES AKURU LETTER DHA
U+1193D DIVES AKURU SIGN HALANTA

### Screenshot
![𑤬𑤾𑤠𑥂𑤬𑤾𑤠 𑤞𑤱𑤟𑤾𑤞𑤱 𑤞𑤲𑤟𑤾𑤞𑤲 𑤞𑤳𑤟𑤾𑤞𑤳 𑤖𑤽𑤖𑤾𑤖𑤽 𑤢𑤽𑤤𑤾𑤢𑤽 𑤞𑤽𑤟𑤾𑤞𑤽](https://user-images.githubusercontent.com/1124347/151724991-e589fc36-790d-49ef-b502-302e6e69ccd9.png)

**Comment by sergiolmartins** [comment]
Apologies for the delay in replying.

All but the first example are correct and will be updated with the next PR.

As for the first line (SA, VIRAMA, PA), [ L2/18-016R § 4.3.2](https://www.unicode.org/L2/L2018/18016r-dives-akuru.pdf#page=22) states that _spa_ is to be rendered as a touching ligature, whereas [L2/18-016R § 4.3.4](https://www.unicode.org/L2/L2018/18016r-dives-akuru.pdf#page=23) shows a distinctive ligature.

If required to change normalisation, I would prefer to maintain the shape of _spa_, resulting in a similar solution as _ntra_ (NA, VIRAMA, TA, MEDIAL RA).

**Comment by sergiolmartins** [comment]
Along with the other changes, I have updated spra to reflect the touching form of spa (SA, VIRAMA, PA), for consistency with the proposal.

**Comment by sergiolmartins** [comment]
This is not exactly the same issue, but I've found the exported fonts were not utilising my set anchors (I assume an issue with glyphsLib, since they also fail in Glyphs), so I've set them manually. I'm now unsure if a few are missing – currently double checking.

**Comment by sergiolmartins** [comment]
This should be solved as of #googlefonts/noto-source/pull/498.
