### ISSUE TITLE
Dives Akuru touching conjuncts use 'kern' instead of 'dist'

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#2228]
### Font
NotoSerifDivesAkuru-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/d2d73ba685c04742e5a2db2b8bcedaaa08bde0af/unhinted/otf/NotoSerifDivesAkuru/NotoSerifDivesAkuru-Regular.otf
Date: 2022-01-28

### Font version
Version 1.000

### Issue
Some touching conjuncts are implemented in GPOS. The feature is 'kern', which is intended to be on by default but optional. Because touching conjuncts are not optional, the font should use 'dist' instead.

### Character data
𑤌𑤾𑤛
U+1190C DIVES AKURU LETTER KA
U+1193E DIVES AKURU VIRAMA
U+1191B DIVES AKURU LETTER TA

### Screenshots
![𑤌𑤾𑤛](https://user-images.githubusercontent.com/1124347/151725877-f88a0d9f-c3c8-4785-a05a-ab38af851d30.png)
The default, better rendering, for comparison:
![𑤌𑤾𑤛](https://user-images.githubusercontent.com/1124347/151725889-0d7aa55e-a67e-44b1-9cf6-aafa3f471d02.png)

**Comment by simoncozens** [comment]
This is happening because ufo2ft does not categorise Dives Akuru as a "dist-enabled script". I'll work on updating the list of scripts in ufo2ft.

**Comment by sergiolmartins** [comment]
@simoncozens, would I be able to update the font to use dist now?

**Comment by simoncozens** [comment]
Not quite yet. Once that PR is applied to ufo2ft, then the font will be fixed by the next rebuild.

**Comment by simoncozens** [comment]
Argh. The good news is that, when built with the latest version of ufo2ft, the kerning rules are now being put into the kern feature. The bad news is that the kern feature now isn't being applied, because of this bug here: https://github.com/googlefonts/ufo2ft/issues/578

**Comment by simoncozens** [comment]
The simple fix is to add `languagesystem DFLT dflt` to the top of the languagesystems prefix.

**Comment by dscorbett** [comment]
The font in this repo still uses 'kern'.

**Comment by sergiolmartins** [comment]
Dumb mistake – updated the languagesystem prefix and completely forgot to use "dist".
