### ISSUE TITLE
Problems with U+11933 DIVES AKURU VOWEL SIGN U and U+1193D DIVES AKURU SIGN HALANTA

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#2230]
### Font
NotoSerifDivesAkuru-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/d2d73ba685c04742e5a2db2b8bcedaaa08bde0af/unhinted/otf/NotoSerifDivesAkuru/NotoSerifDivesAkuru-Regular.otf
Date: 2022-01-28

### Font version
Version 1.000

### Issue
Noto Serif Dives Akuru includes 'ss01' to make U+11933 DIVES AKURU VOWEL SIGN U use a glyph similar to that of U+1193D DIVES AKURU SIGN HALANTA. This is inappropriate and should be removed. [L2/18-016R § 4.2.1](https://www.unicode.org/L2/L2018/18016r-dives-akuru.pdf#page=20) explains that U+1193D is usually a vowel killer but may also be used for <i>u</i>. In other words, if it looks like U+1193D, it should be encoded as U+1193D, even if it is pronounced like U+11933.

The bottom section of [Figure 14](https://www.unicode.org/L2/L2018/18016r-dives-akuru.pdf#page=51) renders <U+1192C, U+1193D> differently depending on whether it represents <i>s</i> or <i>sú</i>: the end of the stroke points rightwards or downwards respectively. However, this appears to be an artificial distinction, as the original source in the image above it doesn’t seem to use different shapes for the different pronunciations.

'ss01' also provides alternative, downwards-pointing glyphs for <i>s</i> and <i>ṭ</i>. That is fine. It would be better to to provide such consistent alternative forms for all dead consonants, not just two. Currently, most consonants with U+1193D have rightwards-pointing glyphs, three have downwards-pointing glyphs, and two have both.

### Character data
𑤖𑤳𑤞𑤳𑤢𑤳𑤬𑤳
U+11916 DIVES AKURU LETTER TTA
U+11933 DIVES AKURU VOWEL SIGN U
U+1191E DIVES AKURU LETTER DHA
U+11933 DIVES AKURU VOWEL SIGN U
U+11922 DIVES AKURU LETTER BA
U+11933 DIVES AKURU VOWEL SIGN U
U+1192C DIVES AKURU LETTER SA
U+11933 DIVES AKURU VOWEL SIGN U
𑤞𑤽𑤢𑤽𑤥𑤽
U+1191E DIVES AKURU LETTER DHA
U+1193D DIVES AKURU SIGN HALANTA
U+11922 DIVES AKURU LETTER BA
U+1193D DIVES AKURU SIGN HALANTA
U+11925 DIVES AKURU LETTER YA
U+1193D DIVES AKURU SIGN HALANTA

#### Inappropriate U+1193D-like glyphs for U+11933

![𑤖𑤳𑤞𑤳𑤢𑤳𑤬𑤳](https://user-images.githubusercontent.com/1124347/151729629-536dc2b2-7b40-4371-8bab-a41689998373.png)

#### Downwards-pointing glyphs for U+1193D, not necessarily wrong, but inconsistent

![𑤞𑤽𑤢𑤽𑤥𑤽](https://user-images.githubusercontent.com/1124347/151729823-d9e8afe6-3fb0-423a-b6ce-ef2e525dc9e5.png)

**Comment by sergiolmartins** [comment]
Thank you for pointing this out – somehow I had interpreted the usage of halanta as U sound, as a mutually exclusive stylistic alternative to the U vowel (probably after the type 1 and type 2 vowels), which is clearly not the case.

I will be rectifying this in the next PR.

**Comment by sergiolmartins** [comment]
This should be solved as of #googlefonts/noto-source/pull/498.
