### ISSUE TITLE
Noto Nastaliq Urdu: Incorrect dot positioning for sequences ending in U+06D2 ARABIC LETTER YEH BARREE (ے)

### ISSUE THREAD

**Issue by saadatm** [googlefonts/noto-fonts#2232]
### Fonts 
**NotoNastaliqUrdu-Regular.ttf**
_Came from:_ https://github.com/googlefonts/noto-fonts/blob/58e9e4f4f0abd3104437c0341ffaa53170c02d34/unhinted/ttf/NotoNastaliqUrdu/NotoNastaliqUrdu-Regular.ttf
_Version:_ 2.001

**NotoNastaliqUrdu-Regular.ttf**
_Came from:_ https://github.com/googlefonts/noto-fonts/blob/00bf5493fd1e7e0e3a481d7c003c15961f93483f/unhinted/ttf/NotoNastaliqUrdu/NotoNastaliqUrdu-Regular.ttf
_Version:_ 3.001

### Issue
In v2.001, dot positioning for sequences that end in U+06D2 ARABIC LETTER YEH BARREE (ے) was mostly correct. In v3.001, there are a lot more incorrect cases (for ligatures of 4 or more characters).

Some test strings and examples are below. I also made a [test page](https://saadatm.github.io/test-pages/ligatures-ending-in-yeh-barree/index.html) that lists valid Urdu ligatures ending in _yeh barree_ (taken from [CRULP/CLE](https://www.cle.org.pk/software/ling_resources/UrduLigatures.htm)) and allows switching between versions 2.001 and 3.001 of Noto Nastaliq Urdu.

#### Test strings for examples below
```
نیچے جھپٹتے بھیجتے کھینچتے
```

#### Correct behaviour (in v2.001)
In v2.001, dots for various characters are positioned correctly and without collision.
```
hb-view -u "0646;06CC;0686;06D2;0020;062C;06BE;067E;0679;062A;06D2;0020;0628;06BE;06CC;062C;062A;06D2;0020;06A9;06BE;06CC;0646;0686;062A;06D2" --margin=128 -o output-lig-2.001.png NotoNastaliqUrdu-Regular-2.001.ttf
```
![output-lig-2 001](https://user-images.githubusercontent.com/6615143/152120355-1c7478ac-1d37-4e7b-9f5c-b337210d2308.png)

#### Incorrect behaviour (in v3.001)
In v3.001, dots are incorrectly positioned or not even present.
```
hb-view -u "0646;06CC;0686;06D2;0020;062C;06BE;067E;0679;062A;06D2;0020;0628;06BE;06CC;062C;062A;06D2;0020;06A9;06BE;06CC;0646;0686;062A;06D2" --margin=128 -o output-lig-3.001.png NotoNastaliqUrdu-Regular-3.001.ttf
```
![output-lig-3 001](https://user-images.githubusercontent.com/6615143/152120374-05bf685f-5a97-4283-8809-7f5de2971996.png)

Please see more test cases on the [test page](https://saadatm.github.io/test-pages/ligatures-ending-in-yeh-barree/index.html). There are a few sequences (like `پچھلے`) which show incorrect dot positioning in both fonts.

**Comment by simoncozens** [comment]
Oh, urgh. This was the hardest part of the re-engineering and I was not sure whether or not it was correct. Thanks for these test cases. I will get it fixed.
