### ISSUE TITLE
Contextual forms of letters in Noto Nastaliq Urdu (Regular)

### ISSUE THREAD

**Issue by Etewilak** [googlefonts/noto-fonts#2236]
Some letters in Noto Nastaliq Urdu Regular have no contextual forms. Such letters do not connect properly.
For example:
![image](https://user-images.githubusercontent.com/55674356/152505473-9ecde397-c867-4bee-9e2e-dba94c51e425.png)
Comparison with Noto Nastaliq Urdu Bold:
![image](https://user-images.githubusercontent.com/55674356/152505606-3f6cdbbb-d7eb-4dff-bedb-92d7f6449150.png)

**Comment by simoncozens** [comment]
I believe this is fixed in current builds.
![shape](https://user-images.githubusercontent.com/106728/152989575-3daf5b2f-06eb-43e7-a0b5-3a9b78d7d3fb.png)
