### ISSUE TITLE
Font substitution in Noto Nastaliq Urdu Regular

### ISSUE THREAD

**Issue by Etewilak** [googlefonts/noto-fonts#2239]
Some Arabic characters in Noto Nastaliq Urdu Regular are rendered in a different typeface from others. Characters affected include those in the Arabic Extended-A Unicode block as well as newly added characters in the Arabic and Arabic Supplement Unicode blocks.
The following image shows the issue:
![image](https://user-images.githubusercontent.com/55674356/152640214-cfea6f6a-2f72-43d8-b243-ddf498336c36.png)

**Comment by simoncozens** [comment]
I'm closing this in favour of #1868; we'll track the issue there.

**Comment by simoncozens** [comment]
In fact, all these glyphs are provided in Noto Nastaliq 3.001
