### ISSUE TITLE
Wrong Nastaliq glyphs for U+06BD ARABIC LETTER NOON WITH THREE DOTS ABOVE

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#2249]
### Font
NotoNastaliqUrdu-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/97e5bf0bbaf85c14498696b408d60b517b0e9e70/unhinted/otf/NotoNastaliqUrdu/NotoNastaliqUrdu-Regular.otf
Date: 2022-02-08

### Font version
Version 3.002

### Issue
The initial and medial glyphs for U+06BD should actually have three dots _below_. The final and isolated glyphs should have the rasm of noon.

### Character data
<span dir="auto">ڽڽڽ ڽ</span>
U+06BD ARABIC LETTER NOON WITH THREE DOTS ABOVE
U+06BD ARABIC LETTER NOON WITH THREE DOTS ABOVE
U+06BD ARABIC LETTER NOON WITH THREE DOTS ABOVE
U+0020 SPACE
U+06BD ARABIC LETTER NOON WITH THREE DOTS ABOVE

### Screenshot
![ڽڽڽ ڽ](https://user-images.githubusercontent.com/1124347/153108228-6119255b-5217-43ad-9e17-9b6756df2f3a.png)

**Comment by simoncozens** [comment]
Oops. And they should be *down* dots below:

> If the vendor is lucky enough, he will run into the information while checking the tables and will find about the relative position of the dots. But unfortunately, no glyphs are shown in the Unicode Standard for initial and medial forms of the Jawi Nya. This means that the vendor can not find if the dot pattern that moves below the skeleton does so pointing upwards, or downwards.
(https://unicode.org/L2/L2009/09146-moving-dots.pdf)

**Comment by dscorbett** [comment]
They really ought to add a character name alias.

**Comment by simoncozens** [comment]
Yeah. It should ARABIC LETTER NYA, really. But also I need to slow down and actually read the Standard before adding stuff.
