### ISSUE TITLE
Add vedic accent support to all Indic fonts

### ISSUE THREAD

**Issue by vvasuki** [googlefonts/noto-fonts#2256]
Following up from https://github.com/googlefonts/noto-fonts/issues/1753#issuecomment-1028617929 :

All Indic fonts ought to support all vedic accents (listed below). Currntly - some do (devanAgarI), others don't (partially or fully) - eg. shAradA. 

Examples:
શૂ꣢રો꣣ નૃ꣡ષા꣢તા꣣ શ્ર꣡વ꣢સશ્ચ꣣ કા꣢મ꣣ આ꣡ ગોમ꣢꣯તિ વ્ર꣣જે꣡ ભ꣢જા꣣ ત્વં꣡ નઃ꣢ ॥ 26:0318 ॥

ઇ꣢ન્દ્રં꣣ ન꣡રો꣢ ને꣣મ꣡ધિ꣢તા હવન્તે꣣ ય꣡ત્પાર્યા꣢꣯ યુ꣣ન꣡જ꣢તે꣣ ધિ꣢ય꣣સ્તાઃ꣢। શૂ꣢રો꣣ નૃ꣡ષા꣢તા꣣ શ્ર꣡વ꣢સશ્ચ꣣ કા꣢મ꣣ આ꣡ ગોમ꣢꣯તિ વ્ર꣣જે꣡ ભ꣢જા꣣ ત્વં꣡ નઃ꣢ ॥

(Easy to get examples by changing the last parameter in this url - https://vishvasa.github.io/devaH/hindukaH/indraH/paravastu-saama/indran-naro-nishvaset/?transliteration_target=gujarati )

Vedic literature is huge and it has a pan Indian following, being a core part of Hindu religion. Unicode standards and recommendations are clear:

> U+0951 devanagari stress sign udatta and U+0952 devanagari stress sign anudatta are tone marks used in the representation of Vedic text in Devanagari. These two combining marks **may also occur in the representation of Vedic texts written in other scripts**, including transliterations in the Latin script. They are given the Indic_Syllabic_- Category value of Cantillation_Mark. (Page 476 of https://www.unicode.org/versions/Unicode14.0.0/ch12.pdf)

> Devanagari Extended: U+A8E0–U+A8FF This block of characters is used chiefly for Vedic Sanskrit, although many of the characters are generic and **can be used by other Indic scripts**. (Page 479 of https://www.unicode.org/versions/Unicode14.0.0/ch12.pdf)

> Vedic Extensions: U+1CD0–U+1CFF The Vedic Extensions block includes characters that are used in Vedic texts; they may be used with Devanagari, as **well as many other Indic scripts**. (Page 481 of https://www.unicode.org/versions/Unicode14.0.0/ch12.pdf)

**Comment by simoncozens** [comment]
Let's move all discussion of "adding bits of other fonts into a font" to #2257.
