### ISSUE TITLE
[Not about Noto Fonts] LibreOffice uses Google Sans

### ISSUE THREAD

**Issue by Mwalters75** [googlefonts/noto-fonts#2262]
![image](https://user-images.githubusercontent.com/67456566/155999492-063bd423-da53-4cde-9a39-76cb322d30a8.png)
<sup>They don't allow issues, so, what else am I supposed to do?</sup>

**Comment by kess** [comment]
LibreOffice has its bug tracker over here: https://bugs.documentfoundation.org/.

**Comment by davelab6** [comment]
@Mwalters75 if you have the font installed, it will show in the LibreOffice list. Or do you mean someone is providing it in a web app?
