### ISSUE TITLE
Missing Bold flags for Noto Sans Bold

### ISSUE THREAD

**Issue by moontypespace** [googlefonts/noto-fonts#2279]
## Defect Report
Excuse me for bothering you again, but the style-linking for the Noto-Sans Bold is still not correct.

### Title 
Bold flag in OS/2 and head table are not set.

### Font 
NotoSans-Bold.ttf

### Where the font came from, and when
https://github.com/googlefonts/noto-fonts/blob/main/hinted/ttf/NotoSans/NotoSans-Bold.ttf
  >   Date: 2022-03-07

### Font Version
2.007

### OS name and version
Windows 10

### Application name and version
MS Office 365, Word

### Issue
Text is 'Regular', click Bold-button,  text switches to 'Bold Italic', but should switch to 'Bold'.
The 'Bold' bit is not set in the OS/2 and head table.

**Comment by xctvcd** [comment]
Original Issue #2269 

Is there an ETA for a fix? Would be much appreciated to have this feature working.

**Comment by xctvcd** [comment]
Hi there, I’m aware that Noto is an open source project, please don’t take this as pushy, just courius: Is there a rough ETA for this?

**Comment by simoncozens** [comment]
Sorry; I had planned to look at this this week but COVID hit! On it now. Fix is easy, then over to Marek who will rebuild the font and deploy to this repo.
