### ISSUE TITLE
Manichaean ligatures do not work anymore

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#2281]
### Font
NotoSansManichaean-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/9b479a1e7c843da5ea247530a8578f288b49f870/unhinted/otf/NotoSansManichaean/NotoSansManichaean-Regular.otf
Date: 2022-03-07

### Font version
Version 2.002

### Issue
Ligatures don’t work anymore. The glyphs are still present in the font.

### Character data
<span dir="ltr">𐫝𐫏𐫝𐫗</span>
U+10ADD MANICHAEAN LETTER SADHE
U+10ACF MANICHAEAN LETTER YODH
U+10ADD MANICHAEAN LETTER SADHE
U+10AD7 MANICHAEAN LETTER NUN

### Screenshot
![𐫝𐫏𐫝𐫗](https://user-images.githubusercontent.com/1124347/157125471-c98a0bcf-a29d-4c37-a911-eaae1e011da6.png)

**Comment by simoncozens** [comment]
This is odd, and it depends on Harfbuzz version. With the same font file, Harfbuzz 4.1.0 does not apply the ligatures and Harfbuzz 2.7.4 does. I presume the difference is to do with whether Manichaean goes through the Arabic shaper (old version) or the USE shaper (new version). But that doesn't really help, and I don't understand *why* it's happening; the code looks right. Even more bizarrely, the other rules in the same lookup (variation selectors) are working fine:

```
sub u10ADD u10ACF by u10ADD10ACF;
sub u10ADD u10AD7 by u10ADD10AD7;

sub u10AC5 uniFE00 by u10AC5.alt;
sub u10AC6 uniFE00 by u10AC6.alt;
sub u10AD6 uniFE00 by u10AD6.alt;
sub u10AD7 uniFE00 by u10AD7.alt;
sub u10AE1 uniFE00 by u10AE1.alt;
```

**Comment by dscorbett** [comment]
It’s because those rules are in 'ccmp'. USE applies 'ccmp' within clusters and the Arabic shaper doesn’t. Two adjacent letters are not in the same USE cluster. A variation sequence is all within the same USE cluster.
