### ISSUE TITLE
U+A9BF JAVANESE CONSONANT SIGN CAKRA blocks ligatures of above-base marks

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#2332]
### Font 
NotoSansJavanese-Regular.otf

### Where the fonts came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/c8729a9e61b2a54a9d2b4c61a82d4d93213bd6e3/unhinted/otf/NotoSansJavanese/NotoSansJavanese-Regular.otf
Date: 2022-04-20

### Font version
Version 2.002

### Issue
U+A9BF JAVANESE CONSONANT SIGN CAKRA, when ligated with the base, blocks ligatures between U+A9B3 JAVANESE SIGN CECAK TELU and above-base marks.

### Character data
ꦥ꦳ꦿꦁ
U+A9A5 JAVANESE LETTER PA
U+A9B3 JAVANESE SIGN CECAK TELU
U+A9BF JAVANESE CONSONANT SIGN CAKRA
U+A981 JAVANESE SIGN CECAK

### Screenshot
![ꦥ꦳ꦿꦁ](https://user-images.githubusercontent.com/1124347/164359274-b7282abd-2e97-4c11-a45f-8b055dfdb3d8.png)

**Comment by simoncozens** [comment]
I don't understand this. Why would one ligate but not the other?

<img width="1270" alt="Screenshot 2022-04-21 at 08 46 04" src="https://user-images.githubusercontent.com/106728/164405367-8e09e00f-0fe0-43af-a3a0-5fb250d2a12e.png">

**Comment by dscorbett** [comment]
HarfBuzz has [some complex rules](https://github.com/harfbuzz/harfbuzz/blob/a85461b9b6367d5ce313c800f9efc6a1ad750616/src/hb-ot-layout-gsubgpos.hh#L999-L1012) about which glyphs may ligate:
```
   * - Ligatures cannot be formed across glyphs attached to different components
   *   of previous ligatures.  Eg. the sequence is LAM,SHADDA,LAM,FATHA,HEH, and
   *   LAM,LAM,HEH form a ligature, leaving SHADDA,FATHA next to eachother.
   *   However, it would be wrong to ligate that SHADDA,FATHA sequence.
   *   There are a couple of exceptions to this:
   *
   *   o If a ligature tries ligating with marks that belong to it itself, go ahead,
   *     assuming that the font designer knows what they are doing (otherwise it can
   *     break Indic stuff when a matra wants to ligate with a conjunct,
   *
   *   o If two marks want to ligate and they belong to different components of the
   *     same ligature glyph, and said ligature glyph is to be ignored according to
   *     mark-filtering rules, then allow.
   *     https://github.com/harfbuzz/harfbuzz/issues/545
```
It seems like this case should work too. Maybe this is a deficiency of HarfBuzz, not Noto. What do you think?

**Comment by simoncozens** [comment]
pa_cakra is coming out as a base glyph in GDEF, not a ligature. Stranger and stranger.

**Comment by simoncozens** [comment]
Ah! But if I force it to be a ligature and add `IgnoreLigatures` to the substitution, the ligature works. (But then mark attachment fails because in ufo2ft you can't do mark-to-base on a ligature glyph, only mark-to-lig, so I need to rename all the anchors to `top_1` etc. *sigh*)
