### ISSUE TITLE
Javanese below-base combining characters ignore pasangan forms

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#2333]
### Font 
NotoSansJavanese-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/c8729a9e61b2a54a9d2b4c61a82d4d93213bd6e3/unhinted/otf/NotoSansJavanese/NotoSansJavanese-Regular.otf
Date: 2022-04-20

### Font version
Version 2.002

### Issue
Below-base combining characters should be positioned relative to, and may ligate with, pasangan forms, but this font ignores any intervening non-spacing pasangan forms when shaping below-base combining characters.

### Character data
ꦤ꧀ꦝꦸꦱ꧀ꦏꦽ
U+A9A4 JAVANESE LETTER NA
U+A9C0 JAVANESE PANGKON
U+A99D JAVANESE LETTER DDA
U+A9B8 JAVANESE VOWEL SIGN SUKU
U+A9B1 JAVANESE LETTER SA
U+A9C0 JAVANESE PANGKON
U+A98F JAVANESE LETTER KA
U+A9BD JAVANESE CONSONANT SIGN KERET

### Screenshot
![ꦤ꧀ꦝꦸꦱ꧀ꦏꦽ](https://user-images.githubusercontent.com/1124347/164361675-e267e405-4369-4d55-9468-8c33472e9d67.png)

**Comment by simoncozens** [comment]
This is an anchor attachment problem (and the one I warned @marekjez86 about). The situation is that when he builds the font, the signs attach (incorrectly) to the bases, and when I build the font, the signs (correctly) attach to the subscripts. One day (soon) GitHub Actions will be building the font, and we will both have an independent build to point to which does not depend on our specific environment.
