### ISSUE TITLE
Incomplete contextualization of U+103C MYANMAR CONSONANT SIGN MEDIAL RA

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#2357]
### Font
NotoSansMyanmar-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/6e3b4a05578a452fa8c76e34e15904d9aae61b85/unhinted/otf/NotoSansMyanmar/NotoSansMyanmar-Regular.otf
Date: 2022-05-18

### Font version
Version 2.103 (according to 'name')
2.104 (according to 'head')

### Issue
Noto Sans Myanmar 2.104 broke the contextualization of U+103C MYANMAR CONSONANT SIGN MEDIAL RA.

### Character data
သ္ကြ
U+101E MYANMAR LETTER SA
U+1039 MYANMAR SIGN VIRAMA
U+1000 MYANMAR LETTER KA
U+103C MYANMAR CONSONANT SIGN MEDIAL RA

#### 2.104
![သ္ကြ](https://user-images.githubusercontent.com/1124347/169165891-bd25dd01-9834-44c4-9399-b56b594ef5ce.png)

#### 2.103
![သ္ကြ](https://user-images.githubusercontent.com/1124347/169165819-0005f5f0-f6b7-487f-b456-e5d950ac21df.png)

**Comment by simoncozens** [comment]
Huh, weird. I don't remember touching that bit of the code. I'll take a look.

**Comment by ohbendy** [comment]
Also https://github.com/googlefonts/noto-fonts/issues/1926#issuecomment-1133608560
