### ISSUE TITLE
U+16AA7 TANGSA LETTER PA and U+16ABA TANGSA LETTER XA are swapped

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#2358]
### Font
NotoSansTangsa-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/6e3b4a05578a452fa8c76e34e15904d9aae61b85/unhinted/otf/NotoSansTangsa/NotoSansTangsa-Regular.otf
Date: 2022-05-18

### Font version
Version 1.501

### Issue
The glyphs for U+16AA7 TANGSA LETTER PA and U+16ABA TANGSA LETTER XA are swapped. [Here](https://en-media.thebetterindia.com/uploads/2021/09/tangsa-tribe-3.jpg) is a good image of a primary source showing which glyph is which.

### Character data
𖪧𖪺
U+16AA7 TANGSA LETTER PA
U+16ABA TANGSA LETTER XA

### Screenshots
![𖪧𖪺](https://user-images.githubusercontent.com/1124347/169171150-07049a84-0a1f-49e6-b478-79312234e6ef.png)

In [Tangsa Lakhum Unicode](https://languagetools-153419.appspot.com/nst/downloads/), for comparison:
![𖪧𖪺](https://user-images.githubusercontent.com/1124347/169171224-256a36b5-db1c-41e6-a358-538d34d5499f.png)

**Comment by marekjez86** [comment]
Should be fixed by https://github.com/googlefonts/noto-fonts/blob/main/unhinted/variable-ttf/NotoSansTangsa-VF.ttf and instances
