### ISSUE TITLE
Roboto Slab Bold Font Has Wrong Font Metadata Name

### ISSUE THREAD

**Issue by TheSmiley007** [googlefonts/noto-fonts#2367]
### Font 
  > RobotoSlab-Bold.ttf
  > [RobotoSlab-Bold.zip](https://github.com/googlefonts/noto-fonts/files/8789632/RobotoSlab-Bold.zip) 

### Where the font came from, and when
  >   Site: https://fonts.google.com/specimen/Roboto+Slab?query=roboto+slab
  >   Date: 2013-04-10 

### Font Version
  > 2.001

### Issue
  > The font roboto slab bold has the wrong font metadata name

1. Open the font.

  2. Observed results:
   > Font name: Roboto Slab.

  3. Expected results:
  > Font name: Roboto Slab Bold.

  5. Additional information: 
  > I found this because i needed both roboto slab bold and robot slab regular fonts, and upon inspecting i realised the bold one has the same name as the regular one. 

## Screenshot
  > Inside the zip

**Comment by simoncozens** [comment]
Firstly, this isn't a bug related to the Noto project at all; if there is a bug here, it should be filed at https://github.com/google/robotoslab/

But I'm not sure it is a bug at all. I downloaded Roboto Slab from fonts.google.com (and also checked the file you attached), and both files report the font metadata correctly:

```
$ ttx -o - -t name RobotoSlab-Bold.ttf
Dumping "RobotoSlab-Bold.ttf" to "-"...
Dumping 'name' table...
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="4.33">

  <name>
    <namerecord nameID="0" platformID="3" platEncID="1" langID="0x409">
      Copyright 2018 The Roboto Slab Project Authors (https://github.com/googlefonts/robotoslab)
    </namerecord>
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Roboto Slab
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Bold
    </namerecord>
    <namerecord nameID="3" platformID="3" platEncID="1" langID="0x409">
      2.001;GOOG;RobotoSlab-Bold
    </namerecord>
    <namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">
      Roboto Slab Bold
    </namerecord>
...
```

Font files contain two separate name fields: the family name (which identifies which font family this is) and the subfamily name (Bold, Regular, Italic, etc). For Roboto Slab Bold, you should expect the family name to be Roboto Slab and the subfamily name to be Bold. This is what we find above, so the font is behaving correctly.
