### ISSUE TITLE
Multiocular O needs updating

### ISSUE THREAD

**Issue by nicolasnoble** [googlefonts/noto-fonts#2404]
### Title
The Multiocular O glyph (U+A66E) has been updated by the unicode committee, according to new information that came to light.

### Font
'NotoSans-Regular.ttf' is affected, but many other versions are affected too.

### Where the font came from, and when
Site: https://github.com/google/fonts/raw/main/ofl/notosans/NotoSans-Regular.ttf
Date: 2022-12-01

### Font Version
2.007

### OS name and version
n/a

### Application name and version
n/a

### Issue
The Multiocular O glyph was initially thought to contain 7 eyes. A closer inspection of the script revealed that it contains, in fact, 10 eyes.

### Character data
See https://en.wikipedia.org/wiki/Multiocular_O for more details.

### Screenshot
The current version from Noto Sans:
![image](https://user-images.githubusercontent.com/7281574/205207417-1d69649b-169b-4fc4-92c3-6e9ef8ed6125.png)

The newly adopted glyph by the Unicode committee:
![image](https://user-images.githubusercontent.com/7281574/205207734-68cdc7a4-037a-4bf1-8bb7-89f0e0e42cb8.png)

**Comment by simoncozens** [comment]
Thank you! We're already tracking this at https://github.com/notofonts/latin-greek-cyrillic/issues/6
