### ISSUE TITLE
Browser display for Noto Sans Bamum

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#248]
```
What steps will reproduce the problem?
1. Download & install Noto Sans Bamum
2. Produce text in the font
3. Open text in a browser

What is the expected output? 
Bamum script

What do you see instead?
Empty boxes

What version of the product are you using? On what operating system?
I believe it's 1.0, on Chrome v. 40.0.2214.111, on Windows 7

Please provide any additional information below.
There are likely additional issues to be worked out regarding the rendering of 
combining diacritics.




```

Original issue reported on code.google.com by `Zenodo...@gmail.com` on 7 Feb 2015 at 9:16

**Comment by jungshik** [comment]
What browser do you use and where? 

If it's Chrome, you have to restart Chrome after install a font.

**Comment by nizarsq** [comment]
All codepoints in NotoSansBamum.
<img width="1268" alt="Screen Shot 2020-08-01 at 10 21 06 PM" src="https://user-images.githubusercontent.com/22158882/89116117-4e513c00-d445-11ea-9214-1b235f7f9e0c.png">
