### ISSUE TITLE
Where is 'Noto Sans CJK KR' '.ttf' edition?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#249]
```
What steps will reproduce the problem?
1. Noto Sans CJK KR, There is only '.otf' edition. 
     So, Please make '.ttf' edition for generality.

What is the expected output? What do you see instead?
 * for generality

What version of the product are you using? On what operating system?
* Android KK 4.4.4 for Mobile

Please provide any additional information below.


```

Original issue reported on code.google.com by `goodman...@gmail.com` on 10 Feb 2015 at 12:01

**Comment by varinder-singh** [comment]
I was looking for NotoSansCJK TTFs for Simplified Chinese and Traditional Chinese for my Jasper Reports Custom Fonts, however, the OTFs are available but my application parses only TTF. Hard to change the application to accept other fonts. 

I would like to use TTFs for enterprise use. Is it possible to get it?

**Comment by twardoch** [comment]
Installing https://pypi.org/project/afdko/ will get you an "otf2ttf" tool that you can use to create TTF versions yourself. 

Note: the resulting fonts will be unhinted so they will display quite poorly on Windows screens.
