### ISSUE TITLE
ligature for "allah"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#261]
```
What steps will reproduce the problem?
1. type اللہ ا+ل+ل+ہ
2. or type  اللّٰہ ا+ل+ل+ّ + ٰ+ہ

What is the expected output? What do you see instead?
In the first case, no tashdid with standing alif appears over the second laam.
In the second case, the tashdid+standing alif appear *after* the word.

What version of the product are you using? On what operating system?
The last version; just downloaded. OS X 10.10.2

Please provide any additional information below.


```

Original issue reported on code.google.com by `marri....@gmail.com` on 21 Feb 2015 at 11:28

**Comment by behdad** [comment]
cc @roozbehp

**Comment by aalasolutions** [comment]
+1 bump

**Comment by nizarsq** [comment]
ARABIC SHADDA U+0651 (ّ) on the ligature for "allah" positioned correctly in the current NotoNastaliqUrdu in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoNastaliqUrdu

<img width="1043" alt="Screen Shot 2020-07-30 at 7 51 11 PM" src="https://user-images.githubusercontent.com/22158882/88994803-0643e500-d29e-11ea-89a5-40dd034781b2.png">
