### ISSUE TITLE
nastaliq redundant dots  دیتے 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#263]
```
What steps will reproduce the problem?
1.  دیتے 
What is the expected output? What do you see instead?

Dots are copied, picture attached.
What version of the product are you using? On what operating system?
OS X 10.10.2

Please provide any additional information below.


```

Original issue reported on code.google.com by `marri....@gmail.com` on 21 Feb 2015 at 11:44

Attachments:
- [Screen Shot 2015-02-22 at 00.43.15.png](https://storage.googleapis.com/google-code-attachments/noto/issue-263/comment-0/Screen Shot 2015-02-22 at 00.43.15.png)

**Comment by nizarsq** [comment]
There is no redundant dots in U+06D2 using the current NotoNastaliqUrdu font in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoNastaliqUrdu. Closing the bug for now.
<img width="1164" alt="Screen Shot 2020-07-30 at 7 26 04 PM" src="https://user-images.githubusercontent.com/22158882/88993342-85371e80-d29a-11ea-8b2d-144ad5d76e7b.png">
