### ISSUE TITLE
Patch for /nototools/add_emoji_gsub.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#30]
```
Don't call font._buildReverseGlyphOrderDict().  It automatically rebuilds that 
when needed.  See:

https://github.com/behdad/fonttools/blob/master/Lib/fontTools/ttLib/__init__.py#
L561
```

Original issue reported on code.google.com by `behdad@google.com` on 2 Jul 2014 at 10:10

Attachments:
- [add_emoji_gsub.py.patch](https://storage.googleapis.com/google-code-attachments/noto/issue-30/comment-0/add_emoji_gsub.py.patch)

**Comment by behdad** [comment]
cc @behdad
