### ISSUE TITLE
Noto Sans Devanagari: U+1CF5 and U+1CF6 missing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#31]
```
A hindi user reports "lack of support for jihvAmUlIya and upadmAnIya" - see 
attached screenshot
```

Original issue reported on code.google.com by `dcrossland@google.com` on 8 Jul 2014 at 6:58

Attachments:
- [png-2.png](https://storage.googleapis.com/google-code-attachments/noto/issue-31/comment-0/png-2.png)

**Comment by behdad** [comment]
cc @davelab6
