### ISSUE TITLE
Meetei Mayek design issues

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#311]
```
Attached is a PDF with design feedback on the Meetei Mayek font from a native 
user of the language, as well as an accomplished type designer on Bengali.


```

Original issue reported on code.google.com by `xian...@google.com` on 27 Mar 2015 at 10:48

**Comment by behdad** [comment]
cc @xiangyexiao

**Comment by dougfelt** [comment]
Work on Meetai Mayek for phase II is complete. Planned work on Meetei Mayek for phase III does not include font redesign.  We will take this feedback under advisement for possible redesign work after phase III.

**Comment by roozbehp** [comment]
Why close the issue then?

**Comment by dougfelt** [comment]
Well, because leaving bugs open for some possible future that's at least 2 years out just clutters the bug database.  If we do want to keep such bugs, then we need some way to tag them so that they can easily be ignored for 2+ years.

**Comment by dougfelt** [comment]
That said, Xiangye thinks we might want to revisit this in phase 3, if we have money for it.

**Comment by xiangyexiao** [comment]
I don't think the issues mentioned in the PDF are entire redesign. They are design issues that need to be fixed in Phase III.

**Comment by marekjez86** [comment]
[NotoSansMeeteiMayek_Review (3).pdf](https://github.com/googlei18n/noto-fonts/files/1589512/NotoSansMeeteiMayek_Review.3.pdf)

Duplicating the above file so it's not lost. For future (Phase III) consideration.

**Comment by JelleBosmaMT** [comment]
Please remove the assignment to me as I have no involvement at all.
