### ISSUE TITLE
Eighth note (♪, U+266A) size

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#336]
```
Shouldn't the eighth note (and beamed eighth notes, U+266B, for that matter) 
have the size of uppercase letters (cap or ascender height) instead of 
lowercase (x-height)?


What version of the product are you using? On what operating system?
Noto Sans 1.04
```

Original issue reported on code.google.com by `eemail...@gmail.com` on 17 Apr 2015 at 7:32

**Comment by aaaxx** [comment]
Could this be corrected, please? I know there are probably more pressing matters but this should really be a quick and easy fix.

**Comment by nizarsq** [comment]
Look like 266A 266B are consistent now. Closing this bug for now.
<img width="1126" alt="Screen Shot 2020-08-01 at 8 17 35 PM" src="https://user-images.githubusercontent.com/22158882/89114672-0d046080-d434-11ea-9f7f-68a776b0880d.png">
