### ISSUE TITLE
Noto Nastaliq U+0658 shape

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#350]
```
The diacritic mark for indicating noon ghunna (sporadically used but sometimes 
essential) in the middle of a word, here on top of noon, ن٘, could be 
slightly reshaped. It appears too big in comparison with the dot; moreover, its 
shape should be a bit more along the lines of a V. Here attached pictures from 
calligraphed sources.

Thank you.
```

Original issue reported on code.google.com by `marri....@gmail.com` on 27 Apr 2015 at 2:00

Attachments:
- [Screen Shot 2015-04-27 at 03.54.38.png](https://storage.googleapis.com/google-code-attachments/noto/issue-350/comment-0/Screen Shot 2015-04-27 at 03.54.38.png)
- [Screen Shot 2015-04-27 at 03.54.06.png](https://storage.googleapis.com/google-code-attachments/noto/issue-350/comment-0/Screen Shot 2015-04-27 at 03.54.06.png)
- [Screen Shot 2015-04-27 at 03.52.02.png](https://storage.googleapis.com/google-code-attachments/noto/issue-350/comment-0/Screen Shot 2015-04-27 at 03.52.02.png)

**Comment by nizarsq** [comment]
U+0658 still appears too big in comparison with the dot
<img width="1140" alt="Screen Shot 2020-07-30 at 2 10 26 PM" src="https://user-images.githubusercontent.com/22158882/88975041-6c187880-d26e-11ea-83bd-ab3489a3d602.png">
