### ISSUE TITLE
Noto Nastaliq ک final and isolated? shape

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#361]
```
What steps will reproduce the problem?
The 'kaaf' which is used at this moment produces the miniature kaaf symbol 
together with the letter in the final and stand-alone positions. This occurs in 
some words while in others it doesn't!
What is the expected output? What do you see instead?
In Urdu it is never used, to the contrary, this shape is Arabic only. I suppose 
it is neither used in Persian.
Please see the attached illustration.
What version of the product are you using? On what operating system?
OS X but this time in Microsoft Word which enables me to see the characters 
without the interference of Apple's core code error.

```

Original issue reported on code.google.com by `marri....@gmail.com` on 6 May 2015 at 3:39

Attachments:
- [namak jhalak talak tak shak.jpg](https://storage.googleapis.com/google-code-attachments/noto/issue-361/comment-0/namak jhalak talak tak shak.jpg)

**Comment by nizarsq** [comment]
U+06A9 ک final and isolated looks ok to me now.
<img width="1154" alt="Screen Shot 2020-07-30 at 2 02 11 PM" src="https://user-images.githubusercontent.com/22158882/88974312-45a60d80-d26d-11ea-9ca3-ecd759302679.png">
