### ISSUE TITLE
Noto Sans Gurmukhi ਕ + ◌੍ + ਰ needs a special glyph

### ISSUE THREAD

**Issue by kulpreetchilana** [googlefonts/noto-fonts#387]
Noto Sans Gurmukhi renders the foot character (PAIRIN RA)
in the wrong position when joined with U+0A15 ਕ:
![screen shot 2015-06-14 at 9 07 47](https://cloud.githubusercontent.com/assets/235441/8152949/6ff2efa8-12d9-11e5-8d40-52d730f7b78e.png)
The glyph should be similar to Arial Unicode MS, with the foot character to the left, under the loop:
![screen shot 2015-06-14 at 9 07 52](https://cloud.githubusercontent.com/assets/235441/8152950/716f0f60-12d9-11e5-88fb-b1d8d5f3edf5.png)

**Comment by fontguy** [comment]
I see other fonts which use the same form as Noto Sans Gurmukhi - i.e. Gurmukhi MT. Is this an optional form or a required one?

**Comment by kulpreetchilana** [comment]
Gurmukhi MT also has the PAIRIN RA under the loop. It's true that there are other fonts that have it like Noto Sans and that it's not "required" to have it under the loop, but it does look kind of ridiculous. I've never seen it written where it is attached the way it currently is in the font. Most of the lower quality Gurmukhi fonts have overlooked this.

**Comment by kulpreetchilana** [comment]
An example is in the middle of the second line in this handwritten Gurmukhi sample
![varan_gyan_ratnavali](https://cloud.githubusercontent.com/assets/235441/8968309/35285dfa-35f1-11e5-98e2-626ac8e40e7a.jpg)

**Comment by JelleBosmaMT** [comment]
I actually made the Arial Unicode MS and Gurmukhi MT fonts that are being compared with. Of course these are (very) old Monotype designs. Looking at various contemporary fonts, I do not see this ligature and assumed the ligature has gone out of fashion. It is a bit unexplainable exception to how subscripts are being attached.
