### ISSUE TITLE
Noto Sans Gurmukhi is missing dotted circle for U+0A51 UDAAT and U+0A75 YAKAASH

### ISSUE THREAD

**Issue by kulpreetchilana** [googlefonts/noto-fonts#389]
Noto Sans Gurmukhi is missing dotted circle for U+0A51 UDAAT and U+0A75 YAKAASH. When typing these characters alone, it should look like:
![screen shot 2015-06-14 at 9 10 24](https://cloud.githubusercontent.com/assets/235441/8152973/cd72c932-12d9-11e5-8ca8-01cd316dc302.png)

**Comment by fontguy** [comment]
It is not required to have the dotted circle for lone combining marks. However, since the fonts have dotted circles for some of the combining marks it should be consistent.

cc @waksmonskiMT

**Comment by JelleBosmaMT** [comment]
The decision whether or not to insert dotted circles in front of stand
alone marks or other types of invalid character combinations are taken by
the shaper software on the basis of Unicode sequences. This has nothing to
do with the font.

**Comment by marekjez86** [comment]
check https://github.com/googlefonts/get-noto/tree/master/unhinted/Gurmukhi

**Comment by nizarsq** [comment]
Look like this issue has been resolved. Closing the bug for now
<img width="945" alt="Screen Shot 2020-06-15 at 10 21 12 AM" src="https://user-images.githubusercontent.com/22158882/84687182-212ae780-aef2-11ea-888f-a0711841ad0c.png">
