### ISSUE TITLE
Noto Sans Gurmukhi U+0A01 ADAK BINDI should be centered above the character and allow for vowels to follow

### ISSUE THREAD

**Issue by kulpreetchilana** [googlefonts/noto-fonts#392]
U+0A01 ADAK BINDI should be centered above the character and allow for vowels to follow as shown in the excerpt from an 1850 Punjabi dictionary below. Currently this renders as:
![screen shot 2015-06-14 at 9 14 50](https://cloud.githubusercontent.com/assets/235441/8153009/6e88fc9c-12da-11e5-898c-ba2244446388.png)

**Comment by behdad** [comment]
Show me the text you are using.  Thanks.

cc @roozbehp

**Comment by kulpreetchilana** [comment]
The text is from this 1850 Punjabi dictionary: https://books.google.com/books?id=YqoCAAAAMAAJ&dq=punjabi%20dictionary&pg=PA9.

In particular, this word: ਅਧਰੰਗਁੀ

**Comment by fontguy** [comment]
cc @waksmonskiMT

**Comment by JelleBosmaMT** [comment]
The only information I have found about this character is: “Adak Bindu:
Not used in Punjabi”

- What is it used for?

- Is it used in dictionaries after 1850?

- Is it possible that its position over the Ga in a dictionary from 1850
(or 1895) reflects the technical limitations of the time or practices of
one particular printer. The sample shows a tippi centered over Ra too.
That is not what we expect today.

- If it is a vowel modifier it would be ordered after any vowel. If it is
not, then what is the order? Uniscribe seems to expect it after the vowel.

**Comment by JelleBosmaMT** [comment]
An online dictionary has ਅਧਰੰਗੀ or ਅਧਰੰਗਾ as paralyzed: without adak bindi. I did not find ਅਡਿਠ.

**Comment by roozbehp** [comment]
Jelle, I couldn't find much more, but here's the original proposal that came from the government on India in 2001: http://www.unicode.org/L2/L2001/01304-feedback.pdf. It's very limited in information too.

My understanding is the character works like U+0901 DEVANAGARI SIGN CANDRABINDU in the character ordering.

**Comment by JelleBosmaMT** [comment]
It looks like the candrabindu, it is encoded like the candrabindu, it is
ordered like the candrabindu.

It seems very unlikely the adak bindu is written in front of any vowel
sign. In particular the ee and ai do not provide any room.

**Comment by marekjez86** [comment]
see https://github.com/googlefonts/get-noto/tree/master/unhinted/Gurmukhi
