### ISSUE TITLE
Noto Sans Gurmukhi does not support special/rare PAIRIN conjuncts

### ISSUE THREAD

**Issue by kulpreetchilana** [googlefonts/noto-fonts#393]
Noto Sans Gurmukhi does not support special/rare PAIRIN conjuncts. These are officially supported in Unicode (Table 12-14).
![screen shot 2015-06-14 at 9 15 49](https://cloud.githubusercontent.com/assets/235441/8153018/91bdd5ca-12da-11e5-9c21-826b7712b49f.png)
These conjuncts supported in Gurmukhi MN / GurmukhiSangam MN:
![screen shot 2015-06-14 at 9 15 55](https://cloud.githubusercontent.com/assets/235441/8153017/91bd7d50-12da-11e5-97ed-dabec450056b.png)
The following documents have more information on these special conjuncts:
http://www.unicode.org/versions/Unicode7.0.0/ch12.pdf (p. 464)

**Comment by behdad** [comment]
cc @roozbehp

**Comment by fontguy** [comment]
Actually, Unicode does not officially support them. Table 12-14 is not a prescriptive part of Unicode - it merely describes the behaviour of the old forms but does not require them. Some Gurmukhi fonts support the old forms and some do not.

**Comment by marekjez86** [comment]
see https://github.com/googlefonts/get-noto/tree/master/unhinted/Gurmukhi
