### ISSUE TITLE
Lepcha - stacked superscripts are misplaced horizontally

### ISSUE THREAD

**Issue by serkhang** [googlefonts/noto-fonts#395]
Stacked superscripts including Lepcha character RAN (U+1C36) are out of alignment.

Screenshot: examples left - expected; examples right - actual result

**Comment by serkhang** [comment]
/Users/steff/Desktop/expected-actual.png

**Comment by serkhang** [comment]
Don't manage to get the screenshot added ...

**Comment by serkhang** [comment]
A second set of samples demonstrating the problem to be more general, i.e. not related to RAN exclusively.

Most combinations consisting of two or three superscripts/subscripts tend to misaligned rendering. Subscript NUKTA (1C37) combined with one superscript displays well, however.

The first example of every group shows expected rendering.
Second and third examples show the actual results with varying order of input, including non-canonical.
![samples_2](https://cloud.githubusercontent.com/assets/12939461/8632559/d6486b94-27a0-11e5-9e9a-d2b2097c9baf.png)

**Comment by schriftgestalt** [comment]
can you post the text of the samples?

**Comment by serkhang** [comment]
I'm sorry for my late response, I've been away a few days. Examples below:

ᰕᰦᰚᰯᰬ   ᰃᰭᰬᰍᰪ   ᰕᰉᰧᰶᰰ   ᰣᰦᰛᰧᰵᰶᰛᰮᰬ   ᰊᰗᰶᰳ   ᰠᰊᰳᰬ

**Comment by fontguy** [comment]
When I look at the text that you left above on the Mac in TextEdit it seems to display correctly.

![lepcha](https://cloud.githubusercontent.com/assets/5133817/8947313/2efc3f62-354e-11e5-89a3-529097ee1bef.png)

Could you check the above image and tell me if it looks ok? Also, could you give more details about your environment?

**Comment by serkhang** [comment]
Results posted above were from Mac OS 10.8 with coinciding rendering in OpenOffice, TextEdit and Nisus Writer.

I reprodruced your result using TextEdit in Mac OS 10.10. This is the expected rendering:
![expected](https://cloud.githubusercontent.com/assets/12939461/8951851/bcf91960-35d1-11e5-8b68-3db7150c7540.png)

Below, you see the actual results.

- First line: Logical order of input - RAN (1C36) immediately follows the wovel sign, with the final consonant typed last. The double superscripts overlie, while the consonant sign KANG is misplaced.

- Second line: Typing order according to SIL - RAN typed last. Double superscripts stacked correctly but misplaced, consonant sing KANG placed correctly.

Thanks for caring!
![text_edit_10_10](https://cloud.githubusercontent.com/assets/12939461/8951868/dce2c794-35d1-11e5-95ad-6cf6bf2f6ed3.png)

**Comment by jungshik** [comment]
What I got with the latest harfbuzz is shown below when I ran the string you gave through hb-view. It's different from your expected result, but your input is not per the Unicode encoding model. (see below). 

![bug395 new](https://cloud.githubusercontent.com/assets/8578343/10982518/8d87e0b4-83c2-11e5-9f3f-3102f6e22656.png)

Some of 'syllables' in your input have U+1C36 at the very end while others have U+1C36 before 'final consonant sign'. 

1c1b 1c27 1c35 1c36  ; 1c36 at the end 
1c0a 1c17 1c36 1c33  ; 1c36 before a final consonant sign 1c33

Other syllables in your input have 'final consonant sign' before 'dependent vowels'.  

1c1b 1c2e 1c2c  ; 1c2e (final consonant sign) before 1c2c (dependent vowel)


Unicode has the following for Lepcha syllable structure:

1. consonant, letter a
2. nukta
3. medial-ra
4. medial-ya
5. dependent vowel
6. final consonant sign
7. syllable modifier : U+1C36 

We need to try an input text per the above order and see what we get.

**Comment by jungshik** [comment]
With the order fixed, I got the same result (with harfbuzz trunk) as the 3rd screenshot in @serkhang 's July 29 comment. 

![bug395 order fixed new](https://cloud.githubusercontent.com/assets/8578343/10984508/d1012d08-83ce-11e5-8ce5-c49eca463e0f.png)


U+1C30 and U+1C33 are positioned correctly above base glyphs when they're used by themselves (2nd line in the screenshot) . 
When they're followed by U+1C36, the stack of two marks are misplaced horizontally (1st line in the screenshot)

![topmark new](https://cloud.githubusercontent.com/assets/8578343/10984555/09aeb0ee-83cf-11e5-82ed-f1aa576438c1.png)

[topmark.txt](https://github.com/googlei18n/noto-fonts/files/28508/topmark.txt)  : input text

BTW, I briefly thought that the absence of U+1C36 in mark2 coverage in GPOS mkmk (lookup index 3) is causing this misplacement, but that does not account for this issue because the relative positions of two marks are correct.

**Comment by serkhang** [comment]
The collation order ACCEPTED by the Unicode Consortium in 2008 is

1. consonant, letter a
2. nukta
3. medial-ra
4. medial-ya
5. dependent vowel
6. syllable modifier: U+1C36
7. final consonant sign

With due reason! U+1C36/RAN is inseparably linked with the vowel signs influencing length and timbre of their pronunciation, so much so, that VOWEL SIGN O + RAN has been merged to a single character, i.e. VOWEL SIGN OO. Likewise, VOWEL SIGN UU is a VOWEL SIGN U including a rudimentary RAN.

So, this is what I called the 'logical order of input', while you seem to advocate the order used at SIL based on several misunderstandings.

This and other details have been mixed up in a carelessly prepared Unicode Standard Core Specifications v. 6 and were never since properly rectified.

As found out with experts at Firefox a few days ago, the font should, indeed, not carry the 'lepc' tag if used in Firefox or Chrome (or in Win10, as such). The tag will induce rendering according to the Universal Shaping Engine included in harfbuzz. Noto Sans Lepcha, however, is not USE compliant.

**Comment by serkhang** [comment]
The collation order ACCEPTED by the Unicode Consortium in 2008 is

1. consonant, letter a
2. nukta
3. medial-ra
4. medial-ya
5. dependent vowel
6. syllable modifier: U+1C36
7. final consonant sign

With due reason! U+1C36/RAN is inseparably linked with the vowel signs influencing length and timbre of their pronunciation, so much so, that VOWEL SIGN O + RAN has been merged to a single character, i.e. VOWEL SIGN OO. Likewise, VOWEL SIGN UU is a VOWEL SIGN U including a rudimentary RAN.

So, this is what I called the 'logical order of input', while you seem to advocate the order used at SIL based on several misunderstandings.

This and other details have been mixed up in a carelessly prepared Unicode Standard Core Specifications v. 6 and were never since properly rectified.

As found out with experts at Firefox a few days ago, the font should, indeed, not carry the 'lepc' tag if used in Firefox or Chrome (or in Win10, as such). The tag will induce rendering according to the Universal Shaping Engine included in harfbuzz. Noto Sans Lepcha, however, is not USE compliant.

**Comment by jungshik** [comment]
Thank you, @serkhang. Indeed, it's ```C(·)(R)(Y)(V)(^)(F)```.  I was wondering about that, too because the text around the table 13-4 implies that U+1C36 (RAN) should appear right after a dependent vowel 
(although there's an ambiguity and I took the table as a definitive source). 

Have you filed a bug report against the Unicode? 

@roozbehp : what's the best course of action here? File a feedback report at the unicode web site? 




A bit of clarification is due : 

> you seem to advocate the order used at SIL based on several misunderstandings.

I'm not advocating anything. I don't know anything about Lepcha other than what's in the Unicode standard. I was just pointing out what the current Unicode standard says about the syllable structure.

**Comment by jungshik** [comment]
> , the font should, indeed, not carry the 'lepc' tag if used in Firefox or Chrome (or in Win10, as such). 
> The tag will induce rendering according to the Universal Shaping Engine included in harfbuzz. Noto 
> Sans Lepcha, however, is not USE compliant.

Yes, that's what I'm doing in bug 451.  @behdad is the lead developer of harfbuzz and is deeply involved in USE.

**Comment by serkhang** [comment]
Nothing is at it looks at first sight …
… and I should test before commenting. :)

It looks like there's no reason to remove the 'lepc' tag from the GPOS script list of Noto Sans Lepcha. I wrote you a page with a few Róng/Lepcha rhymes for demonstration at

http://www.darjeeling-unlimited.com/darjulyang.html

The first version is in my pre-release 'fail-safe' font which renders correctly irrespective of the engine in action.

The second version is in Noto Sans Lepcha including the 'lepc' tag.

The third version is in Noto Sans Lepcha with the 'lepc' tag removed.

The second version renders way better in Firefox and Chrome, while it does not make any difference in WebKit browsers. The only inaccuracies left with USE in action are likely to be due to the differing collating order.

**Comment by serkhang** [comment]
@jungshik: The errors in the published Unicode Specs were reported by Lorna Priest (SIL) in 2011.

http://www.unicode.org/L2/L2011/11305-lepcha.pdf

She seems somewhat inclined to accept the reversed collating order - implemetation is a bit less complicated as U+1C36/RAN does not need re-positioning if added last. Accordingly, the Lepcha font 'Mingzat' developed at SIL works that way.

I do not know about any decisions taken in that matter by the Unicode Consortium. The Unicode repositories host another document, however, in which developer Ka'onohi (Daniel J.) Kai (XenoType Technologies) clearly argues for the collating order with input of RAN immediately after the vowel sign.

http://www.unicode.org/L2/L2003/03259-intro-lepcha.pdf

**Comment by jungshik** [comment]
> She seems somewhat inclined to accept the reversed collating order - implemetation is a bit less 
> complicated as U+1C36/RAN does not need re-positioning if added last. Accordingly, the Lepcha font 
> 'Mingzat' developed at SIL works that way.

Yes, that's what I thought, too. With the current Unicode syllable structure (RAN at the very end), shaping  logic is simpler. 

Anyway, I'm really curious how the UTC responded to the Lepcha syllable structure discrepancy between the original proposal and the published standard.

**Comment by jungshik** [comment]
> It looks like there's no reason to remove the 'lepc' tag from the GPOS script list of Noto Sans Lepcha. I > wrote you a page with a few Róng/Lepcha rhymes for demonstration at

> http://www.darjeeling-unlimited.com/darjulyang.html

Well, I downloaded your fonts (both Noto.ttf and Noto_lepc.ttf). It appears that you made tons of changes in GPOS for DFLT (in addition to dropping 'lepc' script). 

What I did (not yet merged) is just remove 'lepc' from GPOS. GSUB is already 'DFLT'.  And, your sample is rendered identically to the current version ( one with lepc in GPOS).

**Comment by serkhang** [comment]
@jungshik: I really ONLY removed the 'lepc' tag from GPOS. Other changes you may have encountered must be due to the conversion to .woff and back to .ttf or .otf. I used

https://andrewsun.com/projects/woffjs/woffer-woff-font-converter/

with the font file time-stamped September 28, 2015.

**Comment by jungshik** [comment]
> I really ONLY removed the 'lepc' tag from GPOS. Other changes you may have encountered must
 > be due to the conversion to .woff and back to .ttf or .otf.

It's beyond me how woff compression can change GPOS table. Anyway, I believe you :-) @serkhang 
BTW, you can us Tools/pyftsubset in fonttools (behdad/fonttools ) for woff-compression. 


@kmansourMT,  can you fix this issue with DFLT script?  Thanks

**Comment by jungshik** [comment]
It's not gonna happen in Phase 2.  Changing the milestone to Phase 3 using USE-compatible tables.

**Comment by roozbehp** [comment]
@jungshik, the order specified in the Unicode standard is correct. The proposal's order was not accepted. UTC discussed this in its January meeting, and decided to keep the order as is, at least for now. It only recorded an action item for now: http://www.unicode.org/L2/L2016/16004.htm#146-A31, but the position it agreed with is spelled in item 6 in http://www.unicode.org/L2/L2016/16037-script-rec.pdf.

**Comment by serkhang** [comment]
@roozbehp: Best thanks for your insights. Though this may be terribly off-topic, I can't resist to add a few remarks.

The UTC did not approve the correction submitted in the mentioned proposal (L2/15-332). There is, however, still no documented resolution to reject the collation as proposed in Everson's paper (L2/05-158R). Thus, the suspicion that the presently published position of RAN was created by poor editorial work has not been proven wrong.

The recommendations of the UTC in L2/16-037 are somewhat confusing. What does "be remanded to the Editorial Committee" actually mean? According to the response the petitioners got from Dr. Anderson, the combinattion AA+RAN will be explicitly mentioned in coming editions of the standard, hence, just the opposite of what SIBLAC proposed.

**Comment by roozbehp** [comment]
@serkhang, the position of RAN is not about poor editorial work. I was there at both the scripts ad hoc meeting and the UTC meeting when these were discussed. Members mentioned that the ordering was a deliberate decision. There will be some small changes in the text of the standard, as far as I understand. Anyway, I think the best is waiting for the text of the Unicode 9 (due to be published in July or August) and move from there.

**Comment by serkhang** [comment]
@roozbehp: Best thanks for your response.

I just want to make sure what I meant with 'poor editorial work' as I fear a misunderstanding. I spoke of the editorial work for the published Unicode Standard Version 6.0 which included Lepcha for the first time. It contained several errors and inaccuracies reported to the UTC by Lorna Priest in 2011 (L2/11-305). Some of these deplorable failures were corrected, some were perpetuated to the present version (8.0).

**Comment by mgbellarosa** [comment]
![screen shot 2017-06-16 at 12 50 27 pm](https://user-images.githubusercontent.com/29443471/27242575-c3fc4d1a-5292-11e7-88d2-dde7bc9ad5ab.png) ![screen shot 2017-06-16 at 12 51 19 pm](https://user-images.githubusercontent.com/29443471/27242590-cbcc1700-5292-11e7-81e3-375399ccb370.png)

Hello, my name is Glenda Bellarosa and I work with Kamal. I am working on Noto Lepcha.

@serkhang The LazongRong.pdf you linked to in #451 shows the Nukta dot combining with the lower E-vowel (pages 17-21). The first image is taken from that proof. However, while the Nukta's input follows the consonant, the E-vowel appears first. Is it common for the order to switch? Is it acceptable for the E-vowel to appear below the Nukta like in the 2nd image?

Thank you,
Glenda

**Comment by mgbellarosa** [comment]
Hello, 
In the next release of Noto Lepcha, Issue #395 is resolved. Note that the Syllabic Structure is compliant with Unicode 10 in that the Ran (u1C36) is input last, after the final consonant sign. The attached image was produced in Harfbuzz.

![lepchaissue395](https://user-images.githubusercontent.com/29443471/27403785-92d0b090-5680-11e7-94da-20ace2856418.png)

Thank you,
Glenda

**Comment by marekjez86** [comment]
@mgbellarosa : thank you Glenda.

**Comment by serkhang** [comment]
Best thanks for your work, Glenda. 

Ran typed last is compliant with Unicode standards. Since the Lepchas themselves don't agree with that, we handled input differently in the SIBLAC fonts (i.e. input after vowel signs), which is not compliant with Unicode, however.

Nukta should be the lowest sign in the array. But, again, Lepcha scholars (especially Damsangmoo) reject the very character for not being original. Nukta was proposed/introduced by G.B. Mainwaring (1876) to differentiate (as an example) between the syllable KRA in Lepcha words and KRA pronounced as TA in Tibetan loanwords.

**Comment by serkhang** [comment]
@mgbellarosa  The verdict of the Lepcha scholars is clear: Nukta is positioned atop vowel sign E.

Just as a side note:
My informants also stated that, in handwriting, Nukta is placed to the right of vowel sign E.
![nukta_position](https://user-images.githubusercontent.com/12939461/27770626-3e1d5c72-5f42-11e7-84e7-039882b77867.png)

**Comment by mgbellarosa** [comment]
Hello @serkhang. My apologies for the delayed response as I was on vacation. Thank you for checking on the nukta placement! I'm glad to know I don't have to change anything in the font.
Cheers,
Glenda

**Comment by nizarsq** [comment]
<img width="797" alt="Screen Shot 2020-08-01 at 5 51 37 PM" src="https://user-images.githubusercontent.com/22158882/89112972-a70dde00-d41f-11ea-8a2a-6ca7cf85ca3a.png">

**Comment by punchcutter** [comment]
As stated above that text is invalid according to the USE spec. The correct input order is:
ᰕᰦᰚᰬᰯ ᰃᰬᰭᰍᰪ ᰕᰉᰧᰰᰶ ᰣᰦᰛᰧᰵᰶᰛᰬᰮ ᰊᰗᰳᰶ ᰠᰊᰬᰳ

Result:
![lepcha_395](https://user-images.githubusercontent.com/11257204/89113232-3bc60b00-d423-11ea-8a98-5fe0b5f00661.png)

**Comment by marekjez86** [comment]
@punchcutter : thanks
