### ISSUE TITLE
Sinhala: Standard vs Alternate forms for `Da` 

### ISSUE THREAD

**Issue by pathumego** [googlefonts/noto-fonts#405]
By default Noto Sans Sinhala uses alternative consonant+matra forms of 'Da' 

<img width="989" alt="screen shot 2015-07-10 at 12 29 47 am" src="https://cloud.githubusercontent.com/assets/6846609/8635338/8fec7374-283c-11e5-925a-0b9dc76992d1.png">

After a discussion on this for another font project, with @pushpananda, a Sinhala type designer, we think the standard form is much better for reading in smaller sizes, readers are used to the standard form. Noto could have the other form glyphs  as alternate set.

**Comment by marekjez86** [comment]
Reviewing Sinhala entries. Jelle please consider this (the key here is phrase "the standard form is much better for reading in smaller sizes" - the target users have smartphones that do not have high resolution displays, so a standard form will be easier to read)

**Comment by JelleBosmaMT** [comment]
Please confirm if this applies to all cases where Da and its siblings are using the subscript vowels and ya. The image showing the complete set of ligatures that would be replaces by standard shapes.

![overview](https://cloud.githubusercontent.com/assets/12729011/11312111/5557763c-8fd4-11e5-802c-48f153c76cc3.png)

**Comment by marekjez86** [comment]
@pathumego please respond to @JelleBosmaMT . Thank you.

**Comment by JelleBosmaMT** [comment]
The rendering of Noto Sans Sinhala builds on the Bhashita Complex fonts that have been created as a standard for correct rendering. But there are given 3 levels of support for Sinhala, running from Basic to advanced (Guide to creating Sinhala and Tamil Unicode fonts. 2010): Bhashita and Noto supporting the advanced level: "advanced publications and printing applications that supports Pali and Sanskrit scriptsand historic documents". It is very well possible that the subscript marks are less appropriate for the lower level(s). Newsprint, advertising and such seem to make do with the standard forms.

Of course, when we use the standard forms by default, we need to make a choice as to which feature adds support for the subscript marks. The obvious candidates are liga (standard ligature) or dlig (discretionary ligatures). I guess these are more discretionary as standard. The hlig (historical ligature) seems less suitable.

**Comment by JelleBosmaMT** [comment]
Preparing new version with dlig feature for da subscripts.

**Comment by pathumego** [comment]
@marekjez86 Sorry about disappearing on this. Notifications were turned off for some reason. 
@JelleBosmaMT Yes, it applies to all the variations that you have posted, including conjunct forms  with Da. I agree dlig is the best feature to use for this. BTW ICTA standard dose not explicitly address the issue mentioned here, as this is a stylistic decision than language support decision.

**Comment by pathumego** [comment]
And this change might cause a considerable text reflow.

**Comment by nizarsq** [comment]
I'm not Sinhala speaker/reader and I had some difficulty in getting the correct characters data. I tried to do some research to come up with a valid test case. The following line shows the combination characters I "think" will demonstrate the issue:
\u0daf\u0dcf --->දා
\u0daf\u0dca --->ද්
\u0daf\u0dd2 --->දි
\u0daf\u0dd4 --->දු
Assuming they are correct combination, \u0daf\u0dcf (දා) only is in standard form the rest are alternate form
<img width="1143" alt="Screen Shot 2020-07-31 at 2 50 56 PM" src="https://user-images.githubusercontent.com/22158882/89080258-40b08f00-d33d-11ea-982e-0647fbeb64fd.png">
