### ISSUE TITLE
Include Lao Kip currency symbol in Lao fonts

### ISSUE THREAD

**Issue by davelab6** [googlefonts/noto-fonts#412]
Noto Sans Lao (+ UI) could include ₭ (`u+20AD`), the Lao Kip currency symbol; this exists in the Noto Symbol font

**Comment by TidharC** [comment]
The Kip symbol is still missing in both Noto Sans Lao and Noto Serif Lao.

**Comment by nizarsq** [comment]
Issue resolved u+20AD in NotoSansLao and NotoSansLaoUI <img width="934" alt="Screen Shot 2020-07-31 at 6 47 57 PM" src="https://user-images.githubusercontent.com/22158882/89091412-5aae9980-d35e-11ea-8b36-293fdc2456f6.png">
