### ISSUE TITLE
U+0ED3 digit 3 in Lao looks rectangle

### ISSUE THREAD

**Issue by MahaHas** [googlefonts/noto-fonts#414]
It doesn't look the same shape as defined in Unicode set

Attached is a comparison between MAC,Android & Unicode
![lao digit three](https://cloud.githubusercontent.com/assets/12836138/8791985/d28a0bc0-2f16-11e5-8df9-fa836c339183.png)

**Comment by roozbehp** [comment]
@xiangyexiao or @marekjez86, would you please ask a Lao linguist/expert if this bug is valid?

**Comment by ohbendy** [comment]
This is merely a stylistic decision. The style with the loop relates more closely to handwriting, it's less typographic and not so suitable for a contemporary sans serif design. ໓ should relate to the shape of ນ.

**Comment by nizarsq** [comment]
Look like  rendering U+0ED3 currently consistent in MAC and Android. I may have a concern about how it should look comparing with the unicode. See https://unicode.org/charts/PDF/U0E80.pdf @marekjez86 any opinion?
<img width="1179" alt="Screen Shot 2020-07-31 at 6 35 32 PM" src="https://user-images.githubusercontent.com/22158882/89091210-9f393580-d35c-11ea-90d9-277e94427f97.png">

**Comment by marekjez86** [comment]
Some SE Asian have two versions of script styles loopless and with loops. Current NotoSansLao is loopless (and this is OK). We are also trying to produce with loops Noto Sans Lao.
