### ISSUE TITLE
Noto Nastaliq: U+FBB0 Arabic letter YEH BARREE WITH HAMZA ABOVE

### ISSUE THREAD

**Issue by marrish** [googlefonts/noto-fonts#442]
On OSX 10.11 (Beta) this letter is not functioning. Instead, it is displayed as Arial type font and can't join other Nastaliq letters.

**Comment by khaledhosny** [comment]
This is a comparability code point and its use is discouraged. Why do you use/need it?

**Comment by marekjez86** [comment]
marrish@ could you respond to khaledhosny's question? " Why do you use/need it?"

**Comment by marrish** [comment]
Excuse me for delay. I need it obviously for typing the sexuence "YEH BARREE"+ "HAMZA ABOVE" which is needed for several words, eg. grape wine=mai-e-aNguur مۓ ان٘گُور. It's essential for Urdu.

**Comment by khaledhosny** [comment]
I think the proper (per Unicode) input here would be just "YEH BARREE"+ "HAMZA ABOVE" i.e. U+06D2 + U+0654: مۓ ان٘گُور.

**Comment by kmansourMT** [comment]
When the input characters are as listed below (Yeh Barree with Hamza above is 06D3), the rendering is correct as shown:

0645 06D3 0020 0627 0646 0658 06AF 064F 0648 0631

![screen shot 2017-04-13 at 15 53 41](https://cloud.githubusercontent.com/assets/12738181/25027444/7a19a598-2061-11e7-971c-50494ed9681e.png)

**Comment by nizarsq** [comment]
U+FBB0 Arabic Letter Yeh Barree with Hamza Aboveia  isolated form, it should not connect. The right character to use is U+06D3 as mentioned before

**Comment by nizarsq** [comment]
<img width="1194" alt="Screen Shot 2020-07-30 at 1 38 31 PM" src="https://user-images.githubusercontent.com/22158882/88972156-f6aaa900-d269-11ea-88f0-127d8e9a59ef.png">
