### ISSUE TITLE
Runic: extra zero bytes at the end of glyphs

### ISSUE THREAD

**Issue by jungshik** [googlefonts/noto-fonts#443]
Moved from googlei18n/noto-alpha#182 

Imported from [Google Code issue #182](https://code.google.com/p/noto-alpha/issues/detail?id=182) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-02-01T06:23:46.000Z:

---

The OpenType spec requires that the indexes in the 'loca' table (which are really pointers to the 'glyf' table) be multiples of 4:
http://www.microsoft.com/typography/otspec/loca.htm

The Noto Sans Runic font does that OK, but for some reason appears to add 4 extra bytes of \x00 at the end of the glyph data for some of the glyphs, even when the end of the data for a glyph is already at a multiple of 4, when there's no need to add them at all.

Apart from making the font file unnecessarily longer, this is resulting in TTX/fontTools choking on the font, which makes font inspection and manipulation harder.

The extra 4 zero bytes exist in the 'glyf' table for the following glyphs:

uni16A0, uni16B9, uni16BA, uni16C5, uni16CB, uni16D2, uni16D7, uni16D8, uni16DA, uni16E3, uni16E5, uni16E6, uni16EA, uni16ED, uni16EF, uni16F0

The problem doesn't seem to exist in any of the other Noto fonts, so it may be a production problem with just the Runic font. (The problem also exists in an old delivery of Droid Sans Georgian and Droid Sans Armenian from December 2011, but not in the later deliveries of the Georgian or Armenian fonts.)

**Comment by TidharC** [comment]
Is this issue still reproducible?

**Comment by marekjez86** [comment]
Fixed
