### ISSUE TITLE
Symbols: Ancient Greek musical notation need proper GPOS support

### ISSUE THREAD

**Issue by jungshik** [googlefonts/noto-fonts#446]
Moved from googlei18n/noto-alpha#236

Imported from [Google Code issue #236](https://code.google.com/a/google.com/p/noto-alpha/issues/detail?id=236) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-05-29T17:08:39.000Z:

---

Proper GPOS and GDEF support is needed for the ancient Greek musical symbols notation at U+1D200..U+1D245. The combining marks at U+1D242..1D244 should be able to combine with the rest of the symbols in the set.

**Comment by TidharC** [comment]
It seems U+1D242 U+1D243 U+1D244 now combine with musical symbols (see screenshot).  Is this the expected result?

![notosanssymbolsgreekmusicalnotation](https://cloud.githubusercontent.com/assets/16353803/19535286/db6ced82-95fb-11e6-9ff4-9827cb9995c3.png)

**Comment by dscorbett** [comment]
Many symbols, including these musical marks, were removed from Noto Sans Symbols between versions 1.09 and 2.000. Was that intentional? If so, this bug report no longer applies.

**Comment by nizarsq** [comment]
@marekjez86 look like Greek musical symbols notation (U+1D200..U+1D245) removed from NotoSansSymbols and NotoSansSymbols2?

**Comment by marekjez86** [comment]
Not relevant to Symbols: Greek musical symbols notation (U+1D200..U+1D245) is part of NotoMusic now.
