### ISSUE TITLE
Arabic: Reversed Comma and Reversed Semicolon needed for Sindhi

### ISSUE THREAD

**Issue by jungshik** [googlefonts/noto-fonts#448]
Moved from googlei18n/noto-alpha#235
Imported from [Google Code issue #235](https://code.google.com/a/google.com/p/noto-alpha/issues/detail?id=235) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-05-24T01:00:01.000Z:

---

We need support for the following two punctuation marks in the Arabic Naskh fonts, which are needed to support Sindhi:

U+2E41 REVERSED COMMA
U+204F REVERSED SEMICOLON

---

/cc @roozbehp 
/cc @kmansourMT

**Comment by TidharC** [comment]
Both U+204F and U+2E41 are now included in Noto Naskh Arabic.  I think this bug can be closed.

**Comment by nizarsq** [comment]
U+204F REVERSED SEMICOLON  and  U+2E41 REVERSED COMMA are supported in the Arabic Naskh fonts.
<img width="998" alt="Screen Shot 2020-06-02 at 10 55 27 PM" src="https://user-images.githubusercontent.com/22158882/83601019-a68ebf00-a524-11ea-96e2-b6d523d33212.png">
