### ISSUE TITLE
Nastaliq: Europen digits U+0030..0039 needed in Noto Nastaliq

### ISSUE THREAD

**Issue by jungshik** [googlefonts/noto-fonts#449]
googlei18n/noto-fonts#274 (moved from)
Imported from [Google Code issue #274](https://code.google.com/a/google.com/p/noto-alpha/issues/detail?id=274) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-11-13T00:33:43.000Z:

---

This is because they interact with Arabic subtending marks. Sequences such as the SANAH sign (U+0601) followed by European numbers should work the same way the same sequences with native digits work.

**Comment by behdad** [comment]
Still outstanding.

**Comment by marekjez86** [comment]
Fixed. Digits added.
