### ISSUE TITLE
Tamil: Font should support superscript and subscript 2, 3, and 4

### ISSUE THREAD

**Issue by jungshik** [googlefonts/noto-fonts#457]
Moved from googlei18n/noto-alpha#245
Imported from [Google Code issue #245](https://code.google.com/p/noto-alpha/issues/detail?id=245) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-06-26T23:39:09.000Z:

---

Tamil uses superscript and subscript 2, 3, and 4 to display the missing consonants in transcriptions. They should be added to the Tamil fonts.

Here are the codepoints: U+00B2, U+00B3, U+2074, U+2082, U+2083, U+2084

/cc @roozbehp

**Comment by jungshik** [comment]
Comment [#1](https://code.google.com/p/noto-alpha/issues/detail?id=245#c1) originally posted by jelle.bosma@monotypeimaging.com on 2014-07-07T09:50:31.000Z:

-----
This is a bit more complicated.
- We went into this project with the limitation to not include characters outside the Indic Unicode ranges. Because there is a need to adapt spaces, punctution and numerals, I selected a range of shared characters that I added tom the fonts. Do these super- and subscripts require adaptation
- If we add these to the fonts, like the other shared characters, they would not be used in Android and Chrome anyway. For stand alone use of the fonts, there might be many more characters missing.
- Are the Unicode characters actually used? Would there not be a good chance that these are stored in text as ASCII numerals with superscript or subscript formatting. It might be displayed as scaled numerals (with or without the scaling values from the OS/2 table), numerals with OTL substitution or maybe as Unicode characters.

**Comment by jungshik** [comment]
Comment [#2](https://code.google.com/p/noto-alpha/issues/detail?id=245#c2) originally posted by roozbeh@google.com on 2014-07-09T00:10:56.000Z:

-----
Jelle, we don't know if these would need adaptation (you can make a better call there), but they should be included in the Tamil fonts because they are considered a part of Tamil syllables and may also need kerning etc.

Android, Chrome, etc would also use them if they are available in the Tamil font. Regarding usage, they are indeed used. See for example http://tipitaka.org/taml/cscd/e0802n.nrf1.xml. Also, see the beginning of the Tamil section in Unicode where it says they could be used: http://www.unicode.org/versions/Unicode6.2.0/ch09.pdf

**Comment by jungshik** [comment]
Comment [#4](https://code.google.com/p/noto-alpha/issues/detail?id=245#c4) originally posted by jelle.bosma@monotypeimaging.com on 2014-07-09T08:12:06.000Z:

-----


I haven not looked at Android rendereing for quite a while:
In Chrome as expected the numerals and punctuation are substituted (Roboto not Robotica). The 4 superior is quite a bit larger than the two and three. It is a real problem the line distance of Tamil being smaller than the given minimum line distance.
In Firefox the numerals and punctuation are substituted too, but not by Roboto. It is also not Droid sans, at least not a version that I know. Worrying that it is still using the Tamil UI font and that the bold is the regular with a pixel extra weight. At least the line distance is nice...

**Comment by jungshik** [comment]
Comment [#4](https://code.google.com/p/noto-alpha/issues/detail?id=245#c4) originally posted by jelle.bosma@monotypeimaging.com on 2014-07-09T08:12:06.000Z:

-----


I haven not looked at Android rendereing for quite a while:
In Chrome as expected the numerals and punctuation are substituted (Roboto not Robotica). The 4 superior is quite a bit larger than the two and three. It is a real problem the line distance of Tamil being smaller than the given minimum line distance.
In Firefox the numerals and punctuation are substituted too, but not by Roboto. It is also not Droid sans, at least not a version that I know. Worrying that it is still using the Tamil UI font and that the bold is the regular with a pixel extra weight. At least the line distance is nice...

**Comment by marekjez86** [comment]
jungshik@ or xiangyexiao@: who should own this? on whose plate this should be?

**Comment by jungshik** [comment]
We should add these characters to Tamil in phase 3.

**Comment by JelleBosmaMT** [comment]
I added these characters in 2014. Due to mix up in QA it was redelivered in March 2015. In other words, this issue was fixed before it was reported on Github.

**Comment by nizarsq** [comment]
@marekjez86 what is the current status of adding U+00B2, U+00B3, U+2074, U+2082, U+2083, U+2084 (²³⁴₂₃₄)to Tamil? I don't see  them in NotoSansTamil or NotoSerifTamil.

**Comment by nizarsq** [comment]
U+00B2, U+00B3, U+2074, U+2082, U+2083, U+2084 Added Tamil
<img width="1252" alt="Screen Shot 2020-06-23 at 10 26 11 PM" src="https://user-images.githubusercontent.com/22158882/85504311-9fe1ed80-b5a0-11ea-904a-7afdb571d254.png">
