### ISSUE TITLE
Symbols: Requirements for Western musical symbols

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#469]
moved from https://github.com/googlei18n/noto-alpha/issues/238

imported from [Google Code issue #238](https://code.google.com/p/noto-alpha/issues/detail?id=238) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-05-29T17:20:56.000Z:

---

We need individual notes with their annotations to be displayed properly.

We also do need support for ornament strokes (U+1D19B to U+1D1A5), as specified in Table 15-7 of the Unicode Standard, chapter 15 to work within themselves. This is probably achievable with designing the glyphs carefully with minimal or no GPOS/GSUB support.

We _don’t_ need support for beams, ties, slurs, and phrases at this phase.

For the individual notes with annotations, here are character classes:

Rest: U+1D13A..1D142
Notehead: U+1D143..1D15B (including the empty notehead, U+1D159) and U+1D1B9..1D1BA
Augmentation: U+1D16D
Flag: U+1D16E..U+1D172
Stem: U+1D165..U+1D166
Combining Tremolo: U+1D167..U+1D169
Combining Articulation: U+1D17B..U+1D182 and U+1D185..1D18B
Instrumentation: U+1D1AA..1D1AD
Precomposed Note: U+1D15C..1D164 and U+1D1BB..1D1C0

The structure of an individual note is as follows:

(&lt;Rest&gt;
   | &lt;Notehead&gt;&lt;Combining Tremolo&gt;?(&lt;Stem&gt;&lt;Flag&gt;?)?
   | &lt;Precomposed Note&gt;&lt;Combining Tremolo&gt;?)
(&lt;Combining Articulation&gt;|&lt;Instrumentation&gt;)*
&lt;Augmentation&gt;*

Examples are given in tables 15-12, 15-13, and 15-14 of the Unicode Standard.

Additional comments:
1. The combining tremolo appears over the stem of the note (including a Sprechgesang stem). It can also appear when there is no stem, just with a notehead or precomposed note with no stem, where it will appear above or below the note (for Noto, use above).
2. When the empty notehead is used by itself, it should be like white space, with a width typical of other noteheads.

**Comment by nizarsq** [comment]
@marekjez86 what is the status of issue/request?

**Comment by marekjez86** [comment]
The font in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoMusic resolves this requirement.
