### ISSUE TITLE
Not supported bitcoin symbol "฿"

### ISSUE THREAD

**Issue by flashgangsta** [googlefonts/noto-fonts#478]
Hi!
Thank you for very good font, I spent very long time for search beautiful font supported vietnamese lang "Tiếng Việt",
and I'm very happy that I found Noto Sans, but I find one little problem. Your font not support Bitcoin icon — ฿.

May be you will be fix it? This is symbol very popular now.
But in any case, thank you for your work.

Best Regards,
Sergey.

**Comment by marekjez86** [comment]
xiangyexiao to evaluate (this applies not only to vietnamese language, but all others also)

**Comment by roozbehp** [comment]
Bitcoin is being proposed as a new character in Unicode: http://www.unicode.org/L2/L2015/15229-bitcoin-sign.pdf. It will most probably be encoded in Unicode 9 or 10.

**Comment by xiangyexiao** [comment]
will add support to it if it is included in Unicode 9.

**Comment by fitojb** [comment]
Note that the actual bitcoin sign is not ฿, but ₿ (U+20BF). You’re confusing it with the Thai baht symbol. The bitcoin sign is already requested in issue #548, which, albeit newer, has more info than this thread.

**Comment by fitojb** [comment]
@davelab6  Please close this as duplicate, as noted in the above 2017 comment.

**Comment by marekjez86** [comment]
BTW, both NotoSans and NotoSerif support U+20BF (Bitcoin currency sign).
