### ISSUE TITLE
IPA U+02C8 and 02CC are too short

### ISSUE THREAD

**Issue by moyogo** [googlefonts/noto-fonts#491]
ˈ U+02C8 and ˌ U+02CC are too short in general and look to much like dots at small sizes.
ˌ U+02CC should get closer to or slightly above the baseline and ˈ U+02C8 should match its length getting closer to the x-height.

See Noto Sans, Noto Serif compared with Brill, Doulos SIL and DejaVu Sans:
![screen shot 2015-09-03 at 09 18 28](https://cloud.githubusercontent.com/assets/1923747/9653659/e52ff982-521c-11e5-9daa-c898c79e4f31.png)

**Comment by marekjez86** [comment]
MTI: 'Steve and Kamal think 02C8 and 02CC are fine "as is" providing at small sizes they do not rasterize to one pixel. Steve said these marks will not round to one pixel on displays in use today.'

**Comment by moyogo** [comment]
The problem remains, they are too short in Noto fonts. Please look at the sample provided.

**Comment by nizarsq** [comment]
This issue seem to be fixed

<img width="508" alt="Screen Shot 2020-07-22 at 1 24 50 PM" src="https://user-images.githubusercontent.com/22158882/88225064-bbcbc400-cc1e-11ea-8e15-cc60fa7de482.png">

**Comment by moyogo** [comment]
👍 Thanks!
