### ISSUE TITLE
Noto Sans Kannada document fonts misrendering RA+VIRAMA+RA

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#5]
```
I found one immediate minor bug. The sequence 0CB0 + 0CCD + 0CB0 is rendered 
wrongly. I have attached the screenshot depicting the wrong and correct display 
forms. 

Thanks and regards,
Pavanaja




```

Original issue reported on code.google.com by `pavan...@gmail.com` on 17 Jul 2013 at 11:38

Attachments:
- [NotoSansKannada-Wrong-display-Jul-16-2013.jpg](https://storage.googleapis.com/google-code-attachments/noto/issue-5/comment-0/NotoSansKannada-Wrong-display-Jul-16-2013.jpg)

**Comment by behdad** [comment]
cc @cibu

**Comment by lirang** [comment]
Hi,

I encountered the same issue of misrendering of consonant + virama + consonant in Telugu.
Was that bug fixed only for Kannada and for other languages that has Virama in their script.
Is a fix for Telugu expected soon?
