### ISSUE TITLE
Copyright notice issues 

### ISSUE THREAD

**Issue by loveualot** [googlefonts/noto-fonts#513]
To whom it may concern, 

Hi. I have few questions regarding the copyright notice of the Apache License 2.0. 
We are an online game developer and publisher. 
We would like to use the ‘Noto Sans’ font by combining other styles to create a new font that will be proprietary to our company.  We will then use the font within our game.  We note that ‘Noto Sans’ is published under the Apache License, Version 2.0 (“License”). 
Below are my questions. 

1)     We are planning to distribute  the game client program via on-line to our end-users. Is this regarded as the ‘Redistribution’ pursuant to the Section 4 of the License or simply a ‘display’? Our end users, after they launch the game client, will not have access to the code, so they will only have access to the “font’ in its final outward form – therefore it seems akin to a “display” or “performance”.

2)     Nevertheless if it should be deemed a “redistribution”, how do we give the copy of the License, and how do we attach the boilerplate notice in the Appendix? Would the requirement to provide the Apache License be satisfied by including a text (file) containing the License and the boilerplate within the library files in the client program (we expect to be distributing the client in executable file form)?   We expect that the new font will be our proprietary work; however, as we have used the  “Noto Sans” files, by the terms of the License, if we are deemed to be redistributing, we will need to “in any modified files carry prominent notices stating that [we] changed the files.” Is it sufficient to include a file in the program code?  Our reading of the license is that we do not  necessarily have to carry prominent notices within the game that we have changed the files pursuant to the Section 4. B (i.e., we do not need to have it displayed on a screen within the game).

Thank you.

**Comment by dougfelt** [comment]
As of today, the license for all Noto fonts is the [Open Font License 1.1](http://scripts.sil.org/OFL).  Let us know if this addresses your issue.
