### ISSUE TITLE
Add U+2BD2 GROUP MARK to Symbols fonts

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#547]
Proposal for addition of U+2BD2 GROUP MARK symbol [Shirriff, L2/15-083](http://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/15-083) was accepted by Unicode in May of 2015 with the left glyph on page 9 of [L2/15-083](http://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/15-083)

Please add it to Symbol fonts

**Comment by marekjez86** [comment]
@roozbehp FYI

**Comment by nizarsq** [comment]
This issue resolved.
<img width="985" alt="Screen Shot 2020-07-28 at 6 46 00 PM" src="https://user-images.githubusercontent.com/22158882/88746940-964d2780-d102-11ea-9bd9-9e1bea5d2cd2.png">
