### ISSUE TITLE
Please add U+20BF (Bitcoin currency sign) to Noto Sans and Serif fonts

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#548]
Please add Unicode Character U+20BF (Bitcoin currency sign) to any Noto Sans and Serif fonts that have dollar sign and euro sign.

@roozbehp  : FYI

**Comment by roozbehp** [comment]
The character was just approved by UTC. Background information is at http://www.unicode.org/L2/L2015/15229-bitcoin-sign.pdf

**Comment by xiangyexiao** [comment]
@dougfelt 

The desired timeline by Roozbeh is April/May, I am not sure if our Phase III LGC fonts are ready to use by that time. If not, can we fix this issue by ourselves, i.e., extract U+20BF from Phase III Noto LGC sans/serif fonts and merge it into Phase II fonts?

**Comment by xiangyexiao** [comment]
@waksmonskiMT, we want it to be fixed in Phase II fonts by end of March. Let me know if it is infeasible.

**Comment by jungshik** [comment]
@roozbehp Do you really need this in Noto Serif Phase 2 TTF? Doesn't Roboto have this character ?

**Comment by roozbehp** [comment]
Roboto doesn't have the character, and we don't have an easy way to add it at the moment.

As for priority, we don't necessarily need the character in Noto Sans or Noto Serif. We need it somewhere. So Noto Sans Symbols is good enough for us.

**Comment by xiangyexiao** [comment]
@waksmonskiMT 

An update. We want to add U+20BF in Noto Sans Symbols for Phase 2. Please make sure U+20BF is covered by Noto Sans and Serif fonts for Phase 3.

**Comment by Perlover** [comment]
+1

**Comment by shirriff** [comment]
Apple now supports U+20BF (₿) in macOS Sierra and iOS 10. So it would be nice for Noto to support it too.

**Comment by nizarsq** [comment]
U+20BF (Bitcoin currency sign) in NotoSans and NotoSerif.
<img width="1187" alt="Screen Shot 2020-08-13 at 9 30 28 PM" src="https://user-images.githubusercontent.com/22158882/90214049-374b0c00-ddac-11ea-9102-2cecfccd68c8.png">
