### ISSUE TITLE
Possible kerning issue with Noto Nastaliq Urdu

### ISSUE THREAD

**Issue by deepakjois** [googlefonts/noto-fonts#567]
The DDAL and the PEH seem to be too close together here. As seen on OS X El Capitan.

<img width="76" alt="screenshot 2015-11-17 17 29 00" src="https://cloud.githubusercontent.com/assets/5342/11217346/d61ad87e-8d75-11e5-88b2-4d03ffc08e65.png">

**Comment by deepakjois** [comment]
Here is another possible kerning issue:

![out](https://cloud.githubusercontent.com/assets/5342/11523542/197d79f4-98e9-11e5-90f1-1bb3f3b45829.png)

**Comment by marekjez86** [comment]
The kerning issues have been corrected.
