### ISSUE TITLE
Noto San SInhala Not rendering Repaya

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#58]
```
What steps will reproduce the problem?

1. Type කීර්‍ණ  

2. See the attatched image



What version of the product are you using? On what operating system?

Noto v .0.07 

Tested on Mac
Chrom Version 35.0.1916.153
Safari Version 7.0.5 (9537.77.4)
Indesing CS 6


Please provide any additional information below.

THis is a unicode level problem to my knowledge. Has been Documented in the 
attached pdf.


```

Original issue reported on code.google.com by `pathum...@gmail.com` on 16 Jul 2014 at 6:20

Attachments:
- [noto_issues.jpg](https://storage.googleapis.com/google-code-attachments/noto/issue-58/comment-0/noto_issues.jpg)
- [12358-yans-rakar.pdf](https://storage.googleapis.com/google-code-attachments/noto/issue-58/comment-0/12358-yans-rakar.pdf)

**Comment by behdad** [comment]
cc @roozbehp @nyshadhr9

**Comment by nizarsq** [comment]
Look like rendering Repaya in NotoSanSInhala resolved. Tested කර්මය කීර්‍ණ and they rendered ok using NotoSanSInhala in  https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansSinhala/NotoSansSinhala-Regular.ttf

<img width="1120" alt="Screen Shot 2020-07-31 at 6 28 24 PM" src="https://user-images.githubusercontent.com/22158882/89091080-a01d9780-d35b-11ea-9508-ba70e0befdba.png">
