### ISSUE TITLE
Noto Sans Sinhala-  Letter Na  Enhancement

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#59]
```
THis is a design issue.

Letter Danthaja Na (0DB1) seems absurd. Cheked with around 10 native readers 
and all seem to notice this slight issue.

The head part is slightly slanted

I have attached a comparison to a few widely used good fonts.


```

Original issue reported on code.google.com by `pathum...@gmail.com` on 16 Jul 2014 at 6:46

Attachments:
- [Screen Shot 2014-07-17 at 12.10.53 AM.png](https://storage.googleapis.com/google-code-attachments/noto/issue-59/comment-0/Screen Shot 2014-07-17 at 12.10.53 AM.png)

**Comment by behdad** [comment]
cc @jungshik @fontguy
