### ISSUE TITLE
Exclamation mark missing in Noto Nastaliq Urdu

### ISSUE THREAD

**Issue by saadatm** [googlefonts/noto-fonts#597]
I was surprised to find out that there is no glyph for exclamation mark in Noto Nastaliq Urdu. Is this intentional?

**Comment by marekjez86** [comment]
is this intentional? looks that new Noto Sans Arabic has exclamation mark. This might be as designed, but I don't know. @xiangyexiao could you answer?

**Comment by dougfelt** [comment]
There's a lot of Latin block punctuation in Nastaliq, but curiously, no exclamation point.  I expect we should add it.  It's in Naskh (but conversely, not a lot of the other punctuation). I'm trying to find out from Roozbeh what's the appropriate punctuation to include in each.

**Comment by xiangyexiao** [comment]
@kmansourMT any particular reason of excluding exclamation mark from Nastaliq?

It seems that exclamation mark is a common punctuation in Urdu. See these references:
http://wikitravel.org/en/Urdu_phrasebook
http://weburdu.blogspot.com/2009/08/urdu-punctuation-marks.html

**Comment by kmansourMT** [comment]
The exclamation mark was inadvertently omitted.

**Comment by marekjez86** [comment]
Fixed. The exclamation has been added.
