### ISSUE TITLE
Bengali and Devanagari: Adjust usWinAscent in OS/2 table

### ISSUE THREAD

**Issue by brawer** [googlefonts/noto-fonts#601]
From @lemzwerg via e-mail: GDI hinting [of NotoSansBengali], as shown e.g. on [this page](https://raw.githubusercontent.com/lemzwerg/noto-hinted/master/NotoSansBengali/NotoSansBengali-Regular-gGD-bn-win8.1_firefox_37.0.png), gets clipped at the top.  This could be fine-tuned with ttfautohint options, but I think it would be better to adjust NotoSansBengali's value of `usWinAscent` in the `OS/2` table – if you look at [this image](https://raw.githubusercontent.com/lemzwerg/noto-hinted/master/NotoSansBengali/NotoSansBengali-Regular-manual-bn-win8.1_firefox_37.0.png) you can see that even with manual hinting the top gets cut off also at 9px.  The same happens for NotoSansDevanagari, BTW.

**Comment by marekjez86** [comment]
[@lemzwerg](https://github.com/lemzwerg) we just received delivery of Noto SERIF {Bengali,Devanagari}. Could you check if this is an issue there also if I provided you with the fonts (hinted?unhinted?)?

Thanks

**Comment by lemzwerg** [comment]
I've checked the NotoSerifBengali fonts (as currently available in the repository), and they seem OK. As soon as the NotoSerifDevanagari fonts are checked in, I will test them, too.

**Comment by JelleBosmaMT** [comment]
As part of the delivery of Noto Sans Bengali MM I have been asked to comment on open issues:
The clipping is result of a cvt delta trying to make 9 ppm slightly more legible  by adding a pixel to the ascend. To fix this, adjusting WinAscend is not a particular good idea. Improving our careful manual hinting by tweaking ttfautohint parameters would be counter productive. The proper solution would have been to add a VDMX table with an entry for 9 ppem and 9 ppm only.
Of course 9 ppm Devanagari is not a size recommended for actual reading, more to give an impression of text. So I don't think this clipping issue has any practical consequences.

**Comment by nizarsq** [comment]
Is this issue still reproducible? I see @marekjez86 mentioned new NotoSerifBengali build.

**Comment by simoncozens** [comment]
I'm not convinced this is still a bug, and we no longer appear to be using the manual hints anyway.
