### ISSUE TITLE
Supporting a Kashida variant of Noto Nastaliq Urdu font

### ISSUE THREAD

**Issue by ebraminio** [googlefonts/noto-fonts#607]
Urdu Wikipedia uses a Kashida variant of a Nastaliq font, "Jameel Noori Kasheeda", instead making the default font, "Jameel Noori Nastaleeq", italic. Kashida variant on here means making text occupy twice as space they do in normal typography [may even more] and this is a technique to avoid making Italic text which is not familiar concept for Arabic script and specially Nastaliq.

In order to help  Urdu Wikipedia on adapting Noto Urdu Nastaliq font, it would be nice if Noto font could provide Kashida variant by supporting a OpenType feature (say, a feature that could be enabled `font-feature-settings: "ss01" 1;` on CSS) or making another variant of the font specially for making Kashida applied text. Thank you.

**Comment by ebraminio** [comment]
@behdad as requested

**Comment by jungshik** [comment]
@kmansourMT

**Comment by kmansourMT** [comment]
Using an elongated version of the font as an italic-like variant is quite unusual. Another approach would be to provide a bold weight of the same typeface.

**Comment by ebraminio** [comment]
Bold has different meaning on context of Wikipedia manual of style so that would not applicable but elongated version is already used on Urdu Wikipedia. Also if we have a deeper look, italic on Latin script is variant of text where writer wanted to write faster[1], where "تحریری" writing which on Nastaliq[2] means using elongations have same role[3] so it also makes sense to use that even the fact I didn't make or suggested that use on Urdu Wikipedia and I don't know Urdu.

[1]: https://en.wikipedia.org/wiki/Italic_script#History
[2]: https://fa.wikipedia.org/wiki/%D8%AE%D8%B7_%D8%AA%D8%B9%D9%84%DB%8C%D9%82#.DA.A9.D8.A7.D8.B1.D8.A8.D8.B1.D8.AF
[3]: http://www.honarabad.com/13-%D9%86%DA%A9%D8%AA%D9%87-%D8%AA%D8%AE%D8%B5%D8%B5%DB%8C-%D8%AE%D8%B7-%D8%AA%D8%AD%D8%B1%DB%8C%D8%B1%DB%8C.html

**Comment by simoncozens** [comment]
This is a nice idea, but I don't think realistically it is going to happen. Noto went with using bold for emphasis, rather than width, and it would be a considerable amount of drawing work to add a new axis. It would be an interesting variable font project for anyone who wants to extend the font as a community contribution, though!
