### ISSUE TITLE
Make Mongolian Ali Gali Baludas combining marks

### ISSUE THREAD

**Issue by roozbehp** [googlefonts/noto-fonts#616]
Unicode has corrected the combining class of two Mongolian characters to become combining marks. 

The background is explained in the first two pages of http://www.unicode.org/L2/L2016/16041r-mongolian.pdf

/cc @kmansourMT

**Comment by marekjez86** [comment]
Unicode is re-working Mongolian. I expect some results toward end of this year. We will NOT make any changes in Mongolian until we hear from the Unicode Consortium.

**Comment by marekjez86** [comment]
fixed in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansMongolian
