### ISSUE TITLE
Noto Sans: Precomposed characters with tildes appear identical to same character with a macron at certain font sizes

### ISSUE THREAD

**Issue by iwsfutcmd** [googlefonts/noto-fonts#622]
At certain font sizes, some of the precomposed characters with tildes appear as the same character with macrons at certain font sizes. e.g. at 8, 9, 10, 10.5, and 11 points, LATIN SMALL LETTER A WITH TILDE (U+00E3) appears identical to LATIN SMALL LETTER A WITH MACRON (U+0101). This seems to affect every character with a tilde, as well as all Greek characters with a perispomeni (albeit at different font sizes for different characters).

This is an issue because there are many instances in which the tilde and macron should be unambiguous, such as in IPA transcription (where the tilde indicates nasalization and the macron indicates mid tone) or some forms of Indic transliteration (where the tilde also indicates nasalization but the macron indicates vowel length). 

I am currently using the latest version of Noto Sans from the Github repository (as of 02016-02-10). My OS is Ubuntu 16.04, and I have noticed this problem on LibreOffice Writer, LibreOffice Calc, Document Viewer (for PDFs), Firefox 44.0.1, and Chrome 48.0.2564.103 (64-bit). 

I've attached a spreadsheet with the tilde characters that are identical to macron characters highlighted in yellow, and the tilde characters that resemble macrons (but either look different from the equivalent macron character, or have no equivalent macron character). Note that this is not comprehensive - through spot-checking, I've noticed that every character with a tilde or a perispomeni suffers from this issue at some font size or another.

I've also attached screenshots of what I'm seeing in LibreOffice Calc, as well as the issue in Firefox.

Thanks

[noto-sans-tilde-problems.xlsx](https://github.com/googlei18n/noto-fonts/files/125632/noto-sans-tilde-problems.xlsx)
![noto-sans-tilde-problems](https://cloud.githubusercontent.com/assets/12055904/12964812/0698bfce-d007-11e5-9973-fe53de12bda1.png)

![atilde](https://cloud.githubusercontent.com/assets/12055904/12964638/1db994f4-d006-11e5-924e-ed0af122091e.png)

**Comment by jungshik** [comment]
This might be an issue with FreeType autohinting. (see #750 and http://savannah.nongnu.org/bugs/?49312 )

@iwsfutcmd,  can you turn off FreeType autohinting and see if things change?

**Comment by marekjez86** [comment]
copying what was said above:

This might be an issue with FreeType autohinting. (see #750 and http://savannah.nongnu.org/bugs/?49312 )

@iwsfutcmd, can you turn off FreeType autohinting and see if things change?

**Comment by iwsfutcmd** [comment]
Turns out this is indeed a FreeType issue. Tweaking some settings clears it up. Closing this issue...
