### ISSUE TITLE
Noto Sans Batak doesn't position as required by Unicode Standard

### ISSUE THREAD

**Issue by NorbertLindenberg** [googlefonts/noto-fonts#623]
The Unicode Standard, section 17.6, specifies the positioning of glyphs in certain situations:

"The two consonant signs, U+1BF0 batak consonant sign ng and U+1BF1 batak consonant sign h, are nonspacing marks, usually rendered above the spacing vowel signs. When U+1BF0 batak consonant sign ng occurs together with the nonspacing mark, U+1BE9 batak vowel sign ee, both are rendered above the base consonant, with the glyph for the ee at the top left and the glyph for the ng at the top right."

See http://www.unicode.org/versions/Unicode8.0.0/ch17.pdf

The Noto Sans Batak font does not implement this positioning correctly in all situations.

The expected/actual results are about one case where a glyph is clearly positioned incorrectly. The screen shot highlights some additional cases in blue where the Unicode Standard doesn’t specify the positioning, but which are similar to the situation described in the Standard and should also be rechecked.

Steps to Reproduce:
1. Open Firefox.
2. Go to http://lindenbergsoftware.com/google/noto/batak-vowel-consonant.html

Expected Results:
For the syllable with vowel sign ee and final consonant ng, the glyph for the ee should be at the top left and the glyph for the ng at the top right.

Actual Results:
For the syllable with vowel sign ee and final consonant ng, the glyph for the ng is stacked above the glyph for the ee at the top left. The resulting glyph combination is indistinguishable from that for a syllable with sign tompi.

See the red highlight in the screen shot.

Configuration:
Noto Sans Batak Regular 1.05. Firefox 44.0.1 on Mac OS X 10.11.3.

![batak vowel positioning](https://cloud.githubusercontent.com/assets/216206/12969599/b73ffd08-d037-11e5-9207-a5f685ddb95d.png)

**Comment by nizarsq** [comment]
Modified the [test case provided](http://lindenbergsoftware.com/google/noto/batak-vowel-consonant.html) in the bug description to use the [latest NotoSansBatak ]( https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansBatak/NotoSansBatak-Regular.ttf). Behavior reported with vowel sign U+1BE9 (ee) and final consonant U+1BF0 (ng) can be reproduced in Chrome and Firefox. Page 19 in http://www.unicode.org/versions/Unicode8.0.0/ch17.pdf says "... When
U+1BF0 batak consonant sign ng occurs together with the nonspacing mark, U+1BE9
batak vowel sign ee, both are rendered above the base consonant, with the glyph for the
ee at the top left and the glyph for the ng at the top right..." @marekjez86 any thoughts?
<img width="651" alt="Screen Shot 2020-08-11 at 3 24 20 PM" src="https://user-images.githubusercontent.com/22158882/89954883-bbec2d80-dbe6-11ea-96f8-d8d0654dfb1a.png">

**Comment by NorbertLindenberg** [comment]
This article describes mark positioning for Batak:
https://lindenbergsoftware.com/en/notes/constructing-fonts-for-batak/index.html#Positioning

**Comment by marekjez86** [comment]
@NorbertLindenberg  : please check https://github.com/googlefonts/noto-fonts/tree/main/unhinted/ttf/NotoSansBatak or https://github.com/googlefonts/noto-fonts/tree/main/hinted/ttf/NotoSansBatak

**Comment by simoncozens** [comment]
The rendering is currently
![shape](https://user-images.githubusercontent.com/106728/164948098-0004a4ca-a953-4306-9a5b-e1a2f0dbe190.png)

so I believe this issue is fixed.
