### ISSUE TITLE
Some unhinted Noto fonts fail on win 8.1/IE 11

### ISSUE THREAD

**Issue by brawer** [googlefonts/noto-fonts#626]
E-mail from @lemzwerg:

In the process of updating some screenshots in my noto-hinted
repository (due to a new udhr string for Bengali) I've just discovered
that apparently IE 11 on Win 8.1 refuses to display some unhinted Noto
fonts, cf.

  https://raw.githubusercontent.com/lemzwerg/noto-hinted/master/NotoNaskhArabic/NotoNaskhArabic-Regular-unhinted-ar-win8.1_ie_11.0.png
  https://raw.githubusercontent.com/lemzwerg/noto-hinted/master/NotoNastaliqUrdu/NotoNastaliqUrdu-Regular-unhinted-ur-win8.1_ie_11.0.png
  https://raw.githubusercontent.com/lemzwerg/noto-hinted/master/NotoSansBengali/NotoSansBengali-Regular-unhinted-bn-win8.1_ie_11.0.png
  https://raw.githubusercontent.com/lemzwerg/noto-hinted/master/NotoSansDevanagari/NotoSansDevanagari-Regular-unhinted-hi-win8.1_ie_11.0.png

The above images show that IE 11 uses the default system fonts of
Windows 8.1 instead of loading the webfonts.  Note that various other
unhinted fonts like NotoSansHebrew work fine.

First I thought it is probably a problem with accessing the
`noto-fonts' git repository via`rawgit.com', but given that the
images were created at various dates, and the other browsers are just
fine, I think there's a deeper problem within the fonts...

Additionally, I've just tried a live session on BrowserStack using

  https://rawgit.com/lemzwerg/noto-hinted/master/NotoSerifBengali/NotoSerifBengali-Regular-unhinted-bn.html

as the page to display, and it confirms my observation: IE 11 on Win
8.1 (and other Windows versions, too) doesn't load this and some other
unhinted fonts.

Is this a known problem?  AFAICS, MS Edge is not affected.

**Comment by marekjez86** [comment]
@brawer are these fonts generated by the pipeline (i.e., phase III fonts) or delivered for phase II or both?

**Comment by marekjez86** [comment]
@brawer : what should we do about it? is this MS bug or something that we should document in FAQ?

**Comment by marekjez86** [comment]
we discovered we needed DSIG, we add this in a post-processing to hinted but not unhinted
