### ISSUE TITLE
Noto Nastaliq Urdu: 06BA dotless nun should be dotless

### ISSUE THREAD

**Issue by moyogo** [googlefonts/noto-fonts#634]
Noto Nastaliq Urdu shows dotless nun 06BA as nun with dots and mark nun ghunna in initial and medial forms by default, in Urdu, Kashmiri and Sindhi.

![screen shot 2016-03-07 at 22 53 47](https://cloud.githubusercontent.com/assets/1923747/13586446/db77d304-e4b8-11e5-8601-02f2f04cdbeb.png)

In Arabic or Persian the correct glyphs without any dot are shown.
![screen shot 2016-03-07 at 23 04 04](https://cloud.githubusercontent.com/assets/1923747/13586460/e91e4006-e4b8-11e5-99b7-6195cc18f045.png)

The correct glyphs without any dot should be shown by default and in any language.

See http://www.unicode.org/versions/Unicode8.0.0/ch09.pdf#page=26 page 26-27
in particular 

> Rendering systems should display U+06BA as a dual-joining letter, 
> with all four contextual forms shown dotless, regardless of the language of the text.

Although this is correct with regard to spelling, it should be done much earlier at the character level (i.e. when keyed in as the Unicode Standard suggests) and shouldn’t be done in the font at the glyph level.

**Comment by roozbehp** [comment]
I confirm @moyogo's report. The letter should be dotless in all forms.

**Comment by moyogo** [comment]
The same applies to Noto Kufi Arabic.

![screen shot 2016-03-08 at 07 46 30](https://cloud.githubusercontent.com/assets/1923747/13595274/e672b3b6-e501-11e5-8710-25ebf2022567.png)

Noto Naskh Arabic is alright.

**Comment by marrish** [comment]
1. I agree, it should abide by what is being used now.
2. I wonder in which language(-s) the inital and medial glyph is used and what it represents.
3. What is in Noto Nastaliq at present is not correct but in the good direction:
a) in careful Urdu publications, manuscripts, poetry, dictionaries etc., MARKED NOON GHUNNAH is used and must be the standard. Here it is already made possible.
b) whereas MARKED NOON GHUNNAH is necessary as an option, it must not be confused with the final or separate DOTLESS NOON. Dotless nuun in final and separate position is always required in Urdu while MEDIAL form is optional. If one decides to type a text with medial marked nuun ghunnah one has no way to replace only those instances with a normal dotted nuun (as is the standard without diacritics) without the final dotless nuuns getting replaced too, which is unacceptable.
c) In Urdu an initial form of dotless nuun is not needed at all. I can't imagine any need for it in any language.

**Comment by moyogo** [comment]
@marrish dotless nūn is used in Ormuri in initial, medial and final forms according to https://web.archive.org/web/20041116193413/http://www.nipa-khi.edu.pk/rozi%20khan%20burki.pdf#page=15 (last paragraph of the page).

**Comment by marrish** [comment]
Yes, it seems so. Thank you very much, now I know that the letter is designed for Ormuri. With all respects to Ormuri which has a 6.000 something strong community of speakers, Urdu's hundreds of millions speakers don't see their problems with dotless nuun in medial and final position addressed (it should be at the Unicode level, possibly).

**Comment by moyogo** [comment]
Urdu and other languages use nūn in medial position with or without the nūn ghunna diacritic and dotless nūn in final position. Early and Koranic Arabic also use dotless nūn in other positions.

See http://www.unicode.org/versions/Unicode8.0.0/ch09.pdf#page=26
> Noon Ghunna. The letter noon ghunna is used to mark nasalized vowels at the ends of
words and some morphemes in Urdu, Balochi, and other languages of Southern Asia. It is
represented by U+06BA arabic letter noon ghunna. The noon ghunna has the shape of
a dotless noon and typically appears only in final and isolated contexts in these languages.
In the middle of words and morphemes, the normal noon, U+0646 arabic letter noon, is used instead. To avoid ambiguity, sometimes a special mark, U+0658 arabic mark
noon ghunna, is added to the dotted noon to indicate nasalization.

> U+06BA arabic letter noon ghunna is also used as a dotless noon for the noon skeleton
in all four of its contextual forms. As such, it is used in representation of early Arabic and
Koranic Arabic texts. Rendering systems should display U+06BA as a dual-joining letter,
with all four contextual forms shown dotless, regardless of the language of the text.

> Advanced text entry applications for Urdu, Balochi, and other languages using noon
ghunna may include specialized logic for its handling. For example, they might detect midword
usage of the noon ghunna key and emit the regular dotted noon character (U+0646)
instead, as appropriate for spelling in that context.

**Comment by behdad** [comment]
Marek, we need to ask Monotype to fix Nastaliq font for this.  If Kufi font is still under warranty, request fixing that as well.  Thanks.

**Comment by kmansourMT** [comment]
As specified, the default language (locale) for this font is Urdu. Consequently, the default rendering of the dotless Noon (u+06BA) is the dotless form in final and separate contexts, while in initial and medial positions, the letter is rendered with one dot above and the Noon Ghunna mark. In refined writing, this is the convention for Urdu and Kashmir languages. For other locales, such as Arabic or Farsi, U+06BA is rendered as dotless in _all_ context. Below is a pertinent excerpt from TUS that corroborates the described behavior.

______________________________________________
**Noon Ghunna.** The letter noon ghunna is used to mark nasalized vowels at the ends of words and some morphemes in Urdu, Balochi, and other languages of Southern Asia. It is
represented by U+06BA arabic letter noon ghunna. The noon ghunna has the shape of a dotless noon and typically appears only in final and isolated contexts in these languages.
In the middle of words and morphemes, the normal noon, U+0646 arabic letter noon, is used instead. To avoid ambiguity, sometimes a special mark, U+0658 arabic mark
noon ghunna, is added to the dotted noon to indicate nasalization.

**Comment by roozbehp** [comment]
kmansourMT@: Confirming that U+06BA should be dotless in all forms. Unicode charts say "dotless in all four contextual forms". Also, the next paragraph in the Unicode Standard after your quote reads "Rendering systems should display U+06BA as a dual-joining letter, with all four contextual forms shown dotless, **regardless of the language of the text**."

**Comment by kmansourMT** [comment]
Then, apparently, there is a contradiction between these two paragraphs of the Standard.

**Comment by roozbehp** [comment]
There's no contradiction (although I agree it's not the best prose and could be misinterpreted). I actually proposed the last iteration of these paragraphs myself. The intent of the text you are quoting is **not** that U+06BA should be rendered with a dot and a nasalization mark.

Read the last two sentences in the paragraph you quoted carefully: "In the middle of words and morphemes, the normal noon, U+0646 arabic letter noon, is used instead. To avoid ambiguity, sometimes a special mark, U+0658 arabic mark noon ghunna, is added to the dotted noon to indicate nasalization."

The language uses codepoints. It means that "when encoding text that contains the phoneme represented by noon ghunna, use U+0646 if you want a dot, and add a U+0658 if you want to disambiguate". It never says "U+06BA should appear with a dot and a ghunna mark". And the next paragraph clarifies that.

Here's another confirmation: http://www.unicode.org/L2/L2012/12343.htm#133-C33. Quote: "Consensus: Document in the standard and the nameslist that Noon Ghunna is dotless in all its contextual forms. [[L2/12-381](http://www.unicode.org/L2/L2012/12381-dotless-noon.pdf)]"

**Comment by kmansourMT** [comment]
Ok. Got it.

**Comment by marekjez86** [comment]
Fixed. The letter is dotless in all forms.
