### ISSUE TITLE
TIbetan sequence  <U+0F41, U+0F9A> is not stacked.

### ISSUE THREAD

**Issue by jungshik** [googlefonts/noto-fonts#637]
Spun off from googlei18n/nototools#38. Below is the result of shaping U+0F41, U+0F9A with Noto Sans Tibetan + harfbuzz: 

![ཁྚ](https://cloud.githubusercontent.com/assets/1527880/13630850/c62bf9d8-e5e1-11e5-810d-37a4faa048da.png)

@kmansourMT : please, take a look at it. It's from 
[Chris Fynn’s list](https://sites.google.com/site/chrisfynn2/home/tibetanscriptfonts/standardization/precomposedtibetan-parta/precomposed-tibetan---part-a-page-4)

**Comment by marekjez86** [comment]
should be fixed in newly updated https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSerifTibetan (and its TTF counterpart)

**Comment by marekjez86** [comment]
[tib-637-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/3288473/tib-637-Serif.pdf)
