### ISSUE TITLE
Explain Noto roadmap

### ISSUE THREAD

**Issue by brawer** [googlefonts/noto-fonts#640]
@xiangyexiao, what would you think of having a roadmap section in the [Noto README](https://github.com/googlei18n/noto-fonts/blob/master/README.md)? It could briefly explain phase 2 versus phase 3; coverage targets; which scripts will be hinted; plans for [monospaced](https://github.com/googlei18n/noto-fonts/issues/638); etc. Currently, this is not very clear to outsiders.

Actually, the current README is quite long already. Should we move some parts (such as Droid vs Noto) to the [FAQ](https://github.com/googlei18n/noto-fonts/blob/master/FAQ.md)?

**Comment by xiangyexiao** [comment]
good suggestion! will do!

**Comment by brawer** [comment]
“I don't know how upstream handles releases (they have non obvious phase II and phase III milestones” — https://bugzilla.redhat.com/show_bug.cgi?id=1321685
