### ISSUE TITLE
missing unicode 218A and 218B

### ISSUE THREAD

**Issue by workoft** [googlefonts/noto-fonts#651]
The characters 218A ↊ (TURNED DIGIT TWO) and 218B ↋ (TURNED DIGIT THREE) have been introduced to unicode mid 2015 but have not yet been added to noto.

**Comment by jungshik** [comment]
They'll be in Phase 3.

**Comment by TidharC** [comment]
Still missing in Noto Sans and Noto Serif.

**Comment by dougfelt** [comment]
These are targeted for Symbols in Phase 3.

**Comment by nizarsq** [comment]
NotoSansSymbols have 218A, 218B glyphs in the font
<img width="1016" alt="Screen Shot 2021-02-11 at 8 59 52 PM" src="https://user-images.githubusercontent.com/22158882/107732043-34be6600-6cac-11eb-9561-6c3565fe3e1e.png">
