### ISSUE TITLE
Some Arabic characters missing in Noto Nastaliq 

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [googlefonts/noto-fonts#652]
When I browsing Wikipedia article [Pentaglot Dictionary](https://en.wikipedia.org/wiki/Pentaglot_Dictionary) with Noto Nastaliq, I found several Arabic characters looks so different within text, see my screenshot.
![Click here to enlarge](https://cloud.githubusercontent.com/assets/10364351/19418180/70be9564-93f1-11e6-9a86-ffb32c949c9f.PNG)

**Comment by KrasnayaPloshchad** [comment]
Look at the following material if you want to support more characters in Noto Nastaliq
http://www.wul.waseda.ac.jp/kotenseki/html/ho05/ho05_01928/index.html

**Comment by jungshik** [comment]
Thank you for the report. 
Noto Nastaliq didn't strive to support all the languages ever written in Nastaliq.  Specifically, I believe that Uyghur was not in scope for Noto Nastaliq. 

@roozbehp @behdad @kmansourMT

**Comment by KrasnayaPloshchad** [comment]
@jungshik The _Pentaglot Dictionary_ has many words written in Chagatai language (known as "Huiwen" (回文) in the Qing Dynasty), which is the origin of modern Uighur and Uzbek, and used as literary language for their speakers until 1920s.

Wikipedia has said the spread of Nastaliq:
> Nastaʿlīq is the core script of the post-Sassanid Persian writing tradition, and is equally important in the areas under its cultural influence. The languages of Iran (Western Persian, Azeri, Balochi, Kurdi, Luri, etc.), Afghanistan (Dari, Pashto, Uzbek, Turkmen, etc.), Pakistan (Punjabi, Urdu, Kashmiri, Saraiki, etc.), and the Turkic Uyghur language of the Chinese province of Xinjiang, rely on Nastaʿlīq.

**Comment by KrasnayaPloshchad** [comment]
cc @khaledhosny

**Comment by KrasnayaPloshchad** [comment]
Another case can be seen directly from there
![Click to enlarge](http://chuantu.biz/t2/44/1459361075x3340469574.png)
Compare with:
![Original text](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Yuzhi_Wuti_Qingwen_Jian_Tian.svg/556px-Yuzhi_Wuti_Qingwen_Jian_Tian.svg.png)

**Comment by dougfelt** [comment]
@jungshik, do you have an opinion?  If we want this we need a list of the unicode codepoints to add, at a minimum.

**Comment by KrasnayaPloshchad** [comment]
@jungshik, if you want to know which of them need to be added, the following resource would be helpful:
http://www.pentaglot.net/

**Comment by KatMomoi** [comment]
I think this is a product decision. How do we want to define the scope of Noto Nastaliq font? And if we want scripts like Machu, Mongolian, Tibetan, Chagatai included, what arguments can be offered for them other than historical completeness? Can someone want to argue a case?

**Comment by KrasnayaPloshchad** [comment]
I think this bug should be related to #991.

**Comment by nizarsq** [comment]
U+069B (ARABIC LETTER SEEN WITH THREE DOTS BELOW) still missing from NotoNastaliqUrdu font
<img width="1377" alt="Screen Shot 2020-06-04 at 11 16 39 AM" src="https://user-images.githubusercontent.com/22158882/83795980-21ef8e00-a655-11ea-84e0-13d9c083898f.png">
.

**Comment by simoncozens** [comment]
SEEN THREE DOTS BELOW (ڛ) is now supported in Noto Nastaliq Urdu. Please reopen if there are other Arabic characters that you feel this font should support.
