### ISSUE TITLE
Several Tibetan shorthand contractions misbehaviored in Noto Sans Tibetan

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [googlefonts/noto-fonts#658]
The following Tibetan shorthand contractions found at BabelStone website (http://www.babelstone.co.uk/Tibetan/Contractions.html) are misbehiviored when using Noto Sans Tibetan, they have some characters don't combined, placed incorrect, or displaying dotted circle within the text:

དཀྱོིར་ སྐྱེུ་ གྱིུག་ གྲུབྙི་ གྲོིན་ གྲོེར་ དགློེང་ རྪོ་ དངྲོུབ་ བཅྲུག་ ཆྡ་ ཆྲིུན་ ཆུབྙི་ ཆྲོུལ་ ཆྲོུལ་ མཆོེན་ འཆྡིག་ འཆྱོིར་ འཇིགྙི་ མཐྡག་ མཐོེང་ མཐོིས་ དྲུངྡུ་ བདུདྙི་ རྡོེ་ ཕྙོ་ འཕེལྙི་ མི་འཕྲོདྙི་ མོེག་ མྟོེག་ མོེང་ སྨིནྲུག་ ཙྡན་ ཚྡེན་ མཚྮུཾས་ རྫྲུལ་ འོེར་ ཡྟོན་ རིནོེ་ ཤྑོན་ སངྱས་ སྲོེས་ ལྷྒ་ ལྷྱས་ ལྷནོ༹ཊ་ ལྷུནྲུབ་ ལྷྱོགས་

My user agent is Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by TidharC** [comment]
This issue is at least partially reproducible.

Comparing Noto Sans Tibetan to Kokonor, Noto has fewer dotted circles (see screenshot).
![notosanstibetanandkokonor](https://cloud.githubusercontent.com/assets/16353803/18768155/1ede5fbc-80d8-11e6-9254-b4a711c7b60d.png)

**Comment by marekjez86** [comment]
should be fixed in newly updated https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSerifTibetan (and its TTF counterpart)

**Comment by marekjez86** [comment]
[tib-658-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/3288475/tib-658-Serif.pdf)
