### ISSUE TITLE
Noto Sans Sinhala has the wrong ascender.

### ISSUE THREAD

**Issue by JelleBosmaMT** [googlefonts/noto-fonts#660]
Noto Sans Sinhala as dowloaded from https://www.google.com/get/noto/ has the ascender values set to 2189, which is the value for usage as UI font in Android. For use as stand alone font, which I assume the download is intended for, the ascender values in the OS/2 and hhea tables should be set to 2070.

**Comment by JelleBosmaMT** [comment]
For Phase 3 there will be separate instances for document and UI version.

**Comment by marekjez86** [comment]
check ascender in the newest fonts

**Comment by marekjez86** [comment]
fixed
