### ISSUE TITLE
Noto Naskh Arabic variants of qaf and feh 06A4 06A6 06A8 08A4 are inconsistent

### ISSUE THREAD

**Issue by moyogo** [googlefonts/noto-fonts#661]
In Regular, 06A4 06A6 06A8 08A4 (veh, peheh, qaf with three dots above, feh with dot below and three dots above) have initial forms that don’t match the initial forms of 0641 0642 (feh, qaf) while they do in Bold.

Here’s:
ققق ففف ڨڨڨ ڤڤڤ ࢤࢤࢤ ڦڦڦ

![screen shot 2016-04-13 at 09 46 35](https://cloud.githubusercontent.com/assets/1923747/14487825/b6817f4e-015c-11e6-9c69-cc949b02e8fb.png)

**Comment by nizarsq** [comment]
I was able to observe this issue using multiple apps for e.g. TextEdit on Mac and on google translate, I noticed this issue is not specific to a font, for some reason this character (U+08A4) does't accept any font other than Arial, please look at http://www.fileformat.info/info/unicode/char/08a4/fontsupport.htm.

**Comment by nizarsq** [comment]
By going back to the bug and reread it seem i misunderstood the bug, going to go over it again. Thanks

**Comment by nizarsq** [comment]
Apparently the regular form of 06A4, 06A6, 06A8, 08A4 in all contextual forms (Final, Media, Initial) lose the space under the circle (look at the screenshots), however, when it is in isolated form or bolded will show the space under the circle.
![noto naskh arabic variants of qaf and feh 06a4 06a6 06a8 08a4 are inconsistent 661](https://cloud.githubusercontent.com/assets/22158882/18796957/708bf3bc-8180-11e6-83ba-4d467ad1b086.png)

![final media initial](https://cloud.githubusercontent.com/assets/22158882/18797083/08822df8-8181-11e6-8368-6b94c9f0520b.png)

**Comment by nizarsq** [comment]
This issue look to me fixed,  both shapes in Regular and Bold are consistent.
<img width="1025" alt="Screen Shot 2020-06-04 at 5 00 10 PM" src="https://user-images.githubusercontent.com/22158882/83822100-f7b5c480-a684-11ea-9adf-e82266f0517e.png">

**Comment by dscorbett** [comment]
It’s better than it used to be, but the initial forms of U+06A4, U+06A6, U+06A8, and U+08A4 are still noticeably different than those of U+0641 and U+0642 in Noto Naskh Arabic Regular, as can be seen in the previous comment’s image. This issue should be reopened.

**Comment by dscorbett** [comment]
This has not been fixed. Please reopen this.

**Comment by dscorbett** [comment]
@nizarsq, this issue has not been fixed.

**Comment by nizarsq** [comment]
I have no idea why U+06A4, U+06A6, U+06A8, and U+08A4 have different than U+0641 and U+0642. @marekjez86 to approve design change. I recommend the change.
<img width="1184" alt="Screen Shot 2021-01-26 at 12 09 56 PM" src="https://user-images.githubusercontent.com/22158882/105899397-78884e80-5fcf-11eb-8abd-ad75fd136877.png">

**Comment by nizarsq** [comment]
I think we might need another bug since the initial issue here filed for inconsistent shape between Regular and Bold
