### ISSUE TITLE
Bad placement of U+0F39 in Noto Sans Tibetan

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#663]
In Noto Sans Tibetan, the sequence ⟨ཕ༹⟩ (U+0F55 TIBETAN LETTER PHA, U+0F39 TIBETAN MARK TSA -PHRU) is rendered with the diacritic at the lower left, whereas it should be at the upper right.

**Comment by TidharC** [comment]
I am able to repro this on Mac with TextEdit (see screenshot).
![nototibetantsa-phru](https://cloud.githubusercontent.com/assets/16353803/18762435/980f7eea-80bd-11e6-9e90-bf207a4d7a8f.png)

**Comment by marekjez86** [comment]
should be fixed in newly updated https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSerifTibetan (and its TTF counterpart)

**Comment by marekjez86** [comment]
[tib-663-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/3288477/tib-663-Serif.pdf)
