### ISSUE TITLE
Noto Mono lacks math glyphs

### ISSUE THREAD

**Issue by loskutov** [googlefonts/noto-fonts#669]
Noto Mono lacks glyphs for many mathematical symbols, such as U+2192 RIGHTWARDS ARROW, U+2227 LOGICAL AND, U+2228 LOGICAL OR, U+2229 INTERSECTION, U+222A UNION and many others. These symbols are used in some programming languages (such as Haskell and Agda), so their lack prevents some users from using Noto Mono as the system monospace font.

**Comment by dougfelt** [comment]
If you could provide references to the symbols that are used and their unicode codepoints, that would help us ensure that future coverage in the monospace font will be better.

**Comment by loskutov** [comment]
The most important ones missing are probably the following:
* →/⇒ (U+2192 and U+21D2)
* ∈/∉ (U+2208 and U+2209)
* ∘ (U+2218)
* ∧/∨ (U+2227 and U+2228)
* ∩/∪ (U+2229 and U+222A)
* ⊢/⊨ (U+22A2 and U+22A8)
* ⊤/⊥(U+22A4 and U+22A5)
* ↵ (U+21B5)

Actually, full U+22xx coverage would be even nicer :)

**Comment by dougfelt** [comment]
We are going to cover U+22XX, but we have not planned to cover it in the
monospace font.

If you can point us to a reference discussing use of these symbols in
(Haskell/Agda) that would help.  For instance, in the Haskell 2010 report
it appears default bindings for standard operators are ASCII but _any_
unicode symbol is allowed in creating a symbol, this is too many symbols
for Monospace so a selection is useful.  It appears you've chosen these as
nicer aliases to which to rebind standard Haskell operators whose default
representation uses sequences of ASCII symbols/punctuation?

It would also help if you provided more detail about why you need support
for these in the monospace font specifically, as opposed to just providing
support in one of the Noto fonts and accessing it via fallback.  I'm not
clear in general what the drivers are for including characters in
monospace, mostly we've been assuming they are fairly niche environments
(UI text designed for display on terminals, for example).

**Comment by loskutov** [comment]
There are no special symbols defined in Haskell 2010 standard, but in GHC there is [UnicodeSyntax directive](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/syntax-extns.html#unicode-syntax) which defines a few symbols, and also a few packages defining a plenty of ones, like  [base-unicode-symbols](https://hackage.haskell.org/package/base-unicode-symbols/docs/), so it would be really nice if Noto Mono supported at least the ones for [Prelude.Unicode](https://hackage.haskell.org/package/base-unicode-symbols/docs/Prelude-Unicode.html) so that it could be used for editing Haskell code. ↵ (U+21B5) is widely used in text editors to denote the end of line.

**Comment by dougfelt** [comment]
I think I have a reasonable list of symbols for Haskell.  I just need to understand why they need to be in the monospace font.  What is requirement that drives a need for them to be in this font and not a symbols font?

**Comment by marekjez86** [comment]
@loskutov :  What is requirement that drives a need for them to be in this font and not a symbols font?

**Comment by fitojb** [comment]
Well, for instance, applications such as GNOME Terminal will fail to display glyphs correctly if they are missing from the monospaced font you’re using, and will substitute those from another font but without doing any effort to avoid overlapping. (It’s perhaps a GNOME bug, but they’re so reluctant to fix anything…)

**Comment by andersk** [comment]
The [Agda standard library](https://github.com/agda/agda-stdlib) includes a [script](https://github.com/agda/agda-stdlib/blob/master/AllNonAsciiChars.hs) to list all the non-ASCII characters used in the library (in order of usage frequency). [Here is its output.](https://glot.io/snippets/eem9juj73n/raw) There are 184 of them.

**Comment by dougfelt** [comment]
Thanks.  For reference, these are the chars we would need to add to the planned Monospace font.

@jungshik and I think a reasonable course of action is to request compatible monospace versions of these when we build the Math font, and then add them to Monospace at that time.

```
2190 ← LEFTWARDS ARROW
2191 ↑ UPWARDS ARROW
2192 → RIGHTWARDS ARROW
2193 ↓ DOWNWARDS ARROW
2194 ↔ LEFT RIGHT ARROW
219d ↝ RIGHTWARDS WAVE ARROW
219e ↞ LEFTWARDS TWO HEADED ARROW
21a0 ↠ RIGHTWARDS TWO HEADED ARROW
21a2 ↢ LEFTWARDS ARROW WITH TAIL
21a3 ↣ RIGHTWARDS ARROW WITH TAIL
21a6 ↦ RIGHTWARDS ARROW FROM BAR
21d0 ⇐ LEFTWARDS DOUBLE ARROW
21d1 ⇑ UPWARDS DOUBLE ARROW
21d2 ⇒ RIGHTWARDS DOUBLE ARROW
21d3 ⇓ DOWNWARDS DOUBLE ARROW
21d4 ⇔ LEFT RIGHT DOUBLE ARROW
21db ⇛ RIGHTWARDS TRIPLE ARROW
21e8 ⇨ RIGHTWARDS WHITE ARROW
2200 ∀ FOR ALL
2201 ∁ COMPLEMENT
2203 ∃ THERE EXISTS
2204 ∄ THERE DOES NOT EXIST
2205 ∅ EMPTY SET
2208 ∈ ELEMENT OF
2209 ∉ NOT AN ELEMENT OF
220b ∋ CONTAINS AS MEMBER
220e ∎ END OF PROOF
2218 ∘ RING OPERATOR
2223 ∣ DIVIDES
2227 ∧ LOGICAL AND
2228 ∨ LOGICAL OR
222a ∪ UNION
2236 ∶ RATIO
2237 ∷ PROPORTION
2238 ∸ DOT MINUS
223c ∼ TILDE OPERATOR
2241 ≁ NOT TILDE
2243 ≃ ASYMPTOTICALLY EQUAL TO
2245 ≅ APPROXIMATELY EQUAL TO
2247 ≇ NEITHER APPROXIMATELY NOR ACTUALLY EQUAL TO
2249 ≉ NOT ALMOST EQUAL TO
224a ≊ ALMOST EQUAL OR EQUAL TO
224b ≋ TRIPLE TILDE
2254 ≔ COLON EQUALS
2257 ≗ RING EQUAL TO
225f ≟ QUESTIONED EQUAL TO
2262 ≢ NOT IDENTICAL TO
226c ≬ BETWEEN
226e ≮ NOT LESS-THAN
226f ≯ NOT GREATER-THAN
2270 ≰ NEITHER LESS-THAN NOR EQUAL TO
2271 ≱ NEITHER GREATER-THAN NOR EQUAL TO
2272 ≲ LESS-THAN OR EQUIVALENT TO
2273 ≳ GREATER-THAN OR EQUIVALENT TO
2275 ≵ NEITHER GREATER-THAN NOR EQUIVALENT TO
227a ≺ PRECEDES
227b ≻ SUCCEEDS
2286 ⊆ SUBSET OF OR EQUAL TO
2287 ⊇ SUPERSET OF OR EQUAL TO
2288 ⊈ NEITHER A SUBSET OF NOR EQUAL TO
228e ⊎ MULTISET UNION
2291 ⊑ SQUARE IMAGE OF OR EQUAL TO
2292 ⊒ SQUARE ORIGINAL OF OR EQUAL TO
2293 ⊓ SQUARE CAP
2294 ⊔ SQUARE CUP
2295 ⊕ CIRCLED PLUS
2296 ⊖ CIRCLED MINUS
2297 ⊗ CIRCLED TIMES
2298 ⊘ CIRCLED DIVISION SLASH
2299 ⊙ CIRCLED DOT OPERATOR
229a ⊚ CIRCLED RING OPERATOR
229b ⊛ CIRCLED ASTERISK OPERATOR
229c ⊜ CIRCLED EQUALS
22a4 ⊤ DOWN TACK
22a5 ⊥ UP TACK
22b4 ⊴ NORMAL SUBGROUP OF OR EQUAL TO
22b8 ⊸ MULTIMAP
22c2 ⋂ N-ARY INTERSECTION
22c3 ⋃ N-ARY UNION
22c6 ⋆ STAR OPERATOR
22c9 ⋉ LEFT NORMAL FACTOR SEMIDIRECT PRODUCT
22ca ⋊ RIGHT NORMAL FACTOR SEMIDIRECT PRODUCT
22ce ⋎ CURLY LOGICAL OR
22d0 ⋐ DOUBLE SUBSET
22e2 ⋢ NOT SQUARE IMAGE OF OR EQUAL TO
2308 ⌈ LEFT CEILING
2309 ⌉ RIGHT CEILING
230a ⌊ LEFT FLOOR
230b ⌋ RIGHT FLOOR
236e ⍮ APL FUNCTIONAL SYMBOL SEMICOLON UNDERBAR
2474 ⑴ PARENTHESIZED DIGIT ONE
2475 ⑵ PARENTHESIZED DIGIT TWO
25a1 □ WHITE SQUARE
25b7 ▷ WHITE RIGHT-POINTING TRIANGLE
25bb ▻ WHITE RIGHT-POINTING POINTER
25c2 ◂ BLACK LEFT-POINTING SMALL TRIANGLE
25c3 ◃ WHITE LEFT-POINTING SMALL TRIANGLE
25c5 ◅ WHITE LEFT-POINTING POINTER
25c7 ◇ WHITE DIAMOND
25c8 ◈ WHITE DIAMOND CONTAINING BLACK SMALL DIAMOND
266d ♭ MUSIC FLAT SIGN
266f ♯ MUSIC SHARP SIGN
2736 ✶ SIX POINTED BLACK STAR
27e6 ⟦ MATHEMATICAL LEFT WHITE SQUARE BRACKET
27e7 ⟧ MATHEMATICAL RIGHT WHITE SQUARE BRACKET
27e8 ⟨ MATHEMATICAL LEFT ANGLE BRACKET
27e9 ⟩ MATHEMATICAL RIGHT ANGLE BRACKET
27ea ⟪ MATHEMATICAL LEFT DOUBLE ANGLE BRACKET
27eb ⟫ MATHEMATICAL RIGHT DOUBLE ANGLE BRACKET
27f6 ⟶ LONG RIGHTWARDS ARROW
2987 ⦇ Z NOTATION LEFT IMAGE BRACKET
2988 ⦈ Z NOTATION RIGHT IMAGE BRACKET
2a00 ⨀ N-ARY CIRCLED DOT OPERATOR
2a05 ⨅ N-ARY SQUARE INTERSECTION OPERATOR
2a06 ⨆ N-ARY SQUARE UNION OPERATOR
ff5b ｛ FULLWIDTH LEFT CURLY BRACKET
ff5d ｝ FULLWIDTH RIGHT CURLY BRACKET```

**Comment by dougfelt** [comment]
@andersk: the Agda script includes ff5b/d, and I'm not sure why the standard curly brackets don't suffice.  Is there a distinction between standard and full-width curly braces that is important to maintain in a monospace environment?

**Comment by andersk** [comment]
That seems like a questionable hack to prevent the library’s singleton set syntax `｛x｝` from colliding with the compiler’s implicit argument syntax `{x}`. The doubled width is probably important in CJK environments and makes it somewhat distinguishable already; I don’t know of other important distinctions.

**Comment by dougfelt** [comment]
@andersk thanks.  not sure if I want to add these to noto Mono since they're basically CJK characters.  They'd be double-wide in MONO and only for this use.

Also, any idea why the Agda script includes 236e APL FUNCTIONAL SYMBOL SEMICOLON UNDERBAR?

**Comment by andersk** [comment]
Fullwidth forms are [supposed](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms) to be double-wide in mono; they take up two columns of a terminal and `wcwidth` returns 2. (It’s your decision whether to include them, of course, but surely you have a rationale that doesn’t amount to “CJK is different from Latin”.)

236E seems to be used once [here](https://github.com/agda/agda-stdlib/blob/2.4.2.6/src/Relation/Unary/PredicateTransformer.agda#L28).

**Comment by dougfelt** [comment]
@jungshik fyi.

Yeah.  The background is that our existing fullwidth characters are supported in the CJK fonts, because that's where they see the most use.  Noto Monospace is sourced from a different design house and there's no spec that says that Noto Monospace's standard width must be half the CJK's standard width, so they're likely different.  So we have to replicate these characters into different Noto 'subfonts' and give them different treatment, which is something we prefer to avoid as it can cause subtle behavior differences in systems doing font fallback since they handle it differently.

I think we'll provide these two fullwidth chars so that viewing this source text in Noto Monospace will look ok, and wait until/unless someone requests other fullwidth latin in Noto Monospace, or let them just propose additions themselves once the sources are up in the repo.

I'm thinking APL characters will only be in Mono, so 236E will be available there or via fallback in non-monospace environments, which should be ok I presume?

**Comment by joeyaiello** [comment]
Just wanted to offer up a completely different use case for including a few of these characters in Noto Monospace. I use Noto Mono as my console font, and tools like [git-radar](https://github.com/michaeldfallen/git-radar) and [posh-git](https://github.com/dahlbyk/posh-git) use U+2190-2193, 2195, and 2262 as a way to communicate the status of a Git repository in your console prompt.

**Comment by cpitclaudel** [comment]
As a quite note, having good math support in Noto Monospace would fix a bunch of alignment issues that pop up when using a fallback, non-monospace symbol font.  This kind of alignment issues led to https://github.com/cpitclaudel/monospacifier ,  but it's an ugly hack.

**Comment by dougfelt** [comment]
The current range of characters targeted for the phase 3 version of Noto
Mono is as follows.  it contains 3324 chars in the cmap.

0000 000d 0020-007e 00a0-0377 037a-037f 0384-038a 038c 038e-03a1 03a3-03e1
03f0-052f 1ab0-1abe 1c80-1c88 1d00-1df5 1dfb-1f15 1f18-1f1d 1f20-1f45
1f48-1f4d 1f50-1f57 1f59 1f5b 1f5d 1f5f-1f7d 1f80-1fb4 1fb6-1fc4 1fc6-1fd3
1fd6-1fdb 1fdd-1fef 1ff2-1ff4 1ff6-1ffe 2000-2064 2066-2071 2074-208e
2090-209c 20a0-20be 20f0 2100-215f 2184 2189 2190-2195 219c-219e 21a0
21a2-21a4 21a6 21d0-21d4 21da-21db 21e6 21e8 2200-220e 2210 2212 2218-221a
221e 2220 2223 2227-222a 2234-2238 223c-223d 2241 2243 2245 2247-224b
2254-2255 2257 225f-2262 2264-2265 226c 226e-2275 227a-227b 2282-2289 228e
2291-229c 22a2-22a5 22b4-22b5 22b8 22c2-22c4 22c6 22c8-22ca 22cd-22ce
22d0-22d1 22e2-22e3 2308-230b 2310 2319 2320-2321 2336-237a 2395 239b-23ae
23b0-23bd 23dc-23e1 2474-2475 2500-25ff 266d-266f 2736 2758-275a 27d5-27d7
27e6-27eb 27f5-27f6 2987-2988 29b8 2a00 2a05-2a06 2c60-2c7f 2de0-2e44
a640-a69f a700-a7ae a7b0-a7b7 a7f7-a7ff a92e ab30-ab65 fb00-fb06 fe00
fe20-fe2f feff ff5b ff5d fffc-fffd 1f67c-1f67f

**Comment by marekjez86** [comment]
@loskutov , @fitojb , @andersk , @joeyaiello : please check https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/otf/sans/NotoSansMono ; it should have all the symbols described above

**Comment by lancejpollard** [comment]
@dougfelt not sure if this is helpful but regarding references in the wild, Coq uses quite a few symbols, such as [here](https://github.com/coq/coq/blob/15331729aaab16678c2f7e29dd391f72df53d76e/theories/Unicode/Utf8_core.v):

    Notation "∀ x .. y , P" := (forall x, .. (forall y, P) ..)
      (at level 200, x binder, y binder, right associativity,
      format "'[  ' ∀  x  ..  y ']' ,  P") : type_scope.
    Notation "∃ x .. y , P" := (exists x, .. (exists y, P) ..)
      (at level 200, x binder, y binder, right associativity,
      format "'[  ' ∃  x  ..  y ']' ,  P") : type_scope.

    Notation "x ∨ y" := (x \/ y) (at level 85, right associativity) : type_scope.
    Notation "x ∧ y" := (x /\ y) (at level 80, right associativity) : type_scope.
    Notation "x → y" := (x -> y)
      (at level 99, y at level 200, right associativity): type_scope.

    Notation "x ↔ y" := (x <-> y) (at level 95, no associativity): type_scope.
    Notation "¬ x" := (~x) (at level 75, right associativity) : type_scope.
    Notation "x ≠ y" := (x <> y) (at level 70) : type_scope.

    (* Abstraction *)
    Notation "'λ' x .. y , t" := (fun x => .. (fun y => t) ..)
      (at level 200, x binder, y binder, right associativity,
      format "'[  ' 'λ'  x  ..  y ']' ,  t").

**Comment by cpitclaudel** [comment]
@lancejpollard and company-coq adds more: × ¬ ± ⧺ 𝓝 𝓟 ℕ ℤ ℚ ⊢ ‖ ∧ ∨ → ← ↔ ⇒ ≤ ≥ ≠ ⊤ ⊥ λ ∀ ∃ ℕ ℙ ℝ 𝔹 ↣ ⟶ ⟵ ⟷ ⟹ ⟸ ⟿ ⬳

**Comment by nizarsq** [comment]
This issue has been resolved, below screenshots for all math glyphs tested using NotoSansMono in this directory https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSansMono
<img width="435" alt="Screen Shot 2020-07-20 at 9 38 14 AM" src="https://user-images.githubusercontent.com/22158882/87962879-bcbcf400-ca6c-11ea-8d44-3945b0ce615f.png">
<img width="405" alt="Screen Shot 2020-07-20 at 9 38 37 AM" src="https://user-images.githubusercontent.com/22158882/87962906-ca727980-ca6c-11ea-8d36-9db8d5754391.png">
<img width="391" alt="Screen Shot 2020-07-20 at 9 38 59 AM" src="https://user-images.githubusercontent.com/22158882/87962935-d78f6880-ca6c-11ea-8786-77ce3d05c9f6.png">

**Comment by cpitclaudel** [comment]
Is there a reason why many of these characters seem to occupy two columns instead of one?
