### ISSUE TITLE
Burushaski letters should connect in Noto Nastaliq Urdu

### ISSUE THREAD

**Issue by moyogo** [googlefonts/noto-fonts#673]
Burushaski letters (0775 0776 0777 0778 0779 077A 077B 077D) don’t connect as they should in Noto Nastaliq Urdu, with the exception of 077C which connects properly.
077A and 077B should also have initial and medial forms (the same as 0775 and 0776), see http://www.unicode.org/versions/Unicode8.0.0/ch09.pdf#page=23 and http://www.unicode.org/Public/8.0.0/ucd/ArabicShaping.txt.

Note: Burushaski letters are not in Noto Kufi Arabic.

**Comment by marekjez86** [comment]
@moyogo : when you say "Note: Burushaski letters are not in Noto Kufi Arabic" are you indicating that they should be there and this ought to be corrected or this is just an observation?

**Comment by moyogo** [comment]
It was just an observation.
They are Noto Nastaliq Urdu and Noto Naskh Arabic but not in Noto Kufi Arabic.
In Noto Naskh Arabic they connect correctly.

**Comment by nizarsq** [comment]
@moyogo what platform you used to reproduce this issue?  tested 0775, 0776 on Apple native app (TextEdit) using Noto Nastaliq Urdu and was able to reproduce the issue; those letters will not get connected as they supposed, they basically rendered separately.

![burushaski letters should connect in noto nastaliq urdu 673](https://cloud.githubusercontent.com/assets/22158882/18691069/6ed694fa-7f46-11e6-8f36-1a7ced2f48e6.png)

**Comment by behdad** [comment]
Confirming original report.  Marek, please send to Monotype to fix.

**Comment by marekjez86** [comment]
Fixed. These characters now connect.
