### ISSUE TITLE
in Roman Arimo and roman Cousine, ʹ ʺ should be slanted

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#687]
This bug reflects here the remaining issues with Arimo, Cousine and/or Tinos mentioned in https://github.com/googlei18n/noto-fonts/issues/510

per @moyogo we still need: "in Roman Arimo and roman Cousine, ʹ ʺ should be slanted"

Arimo (top/pinkish line is the reference font, greenish line is this font):
![arimo-510](https://cloud.githubusercontent.com/assets/13322623/15328265/1e7e7bb2-1c09-11e6-987b-f127585acad2.jpg)

Cousine (top/pinkish line is the reference font, greenish line is this font):
![cousine-510](https://cloud.githubusercontent.com/assets/13322623/15328273/23a0f674-1c09-11e6-80a9-7d9f120bd6de.jpg)

Tinos (top/pinkish line is the reference font, greenish line is this font):
![tinos-510](https://cloud.githubusercontent.com/assets/13322623/15328279/29599d8c-1c09-11e6-9b6c-20bf7dede0ce.jpg)

**Comment by nizarsq** [comment]
Original issue #510 is closed. I'll  close this issue for now.
