### ISSUE TITLE
Add U+23FB - U+23FE to Noto Sans Symbols (Unicode 9 power symbols)

### ISSUE THREAD

**Issue by edent** [googlefonts/noto-fonts#689]
Unicode 9 contains some additions to the [Miscellaneous Technical block](http://www.unicode.org/Public/9.0.0/charts/blocks/U2300.pdf)

These are 

```
Power        &#x23FB;   ⏻
Toggle Power &#x23FC;   ⏼
Power On     &#x23FD;   ⏽
Power Off    &#x2B58;   ⭘
Sleep Mode   &#x23FE;   ⏾
```

Please can these be added to Noto Sans Symbols.

Free reference fonts can be found at http://unicodepowersymbol.com/font/ or https://github.com/jloughry/Unicode 

(I'm [one of the proposers of the symbols](http://www.unicode.org/L2/L2014/14009r-power-symbol.pdf))

**Comment by dougfelt** [comment]
Yes, these are scheduled for the update to the Noto fonts.

It turns out though that we did not include 2B58 in the same font as the others, not being aware of this use.  I'll see about getting that changed.

**Comment by dougfelt** [comment]
U+2B58 will be in the same font as the others.

**Comment by edent** [comment]
Is there anything else I can do to help this issue along? Happy to provide sample characters.

**Comment by dougfelt** [comment]
These are in the beta Symbols font, which has not been relased yet.

**Comment by edent** [comment]
Currently available in:

https://github.com/googlei18n/noto-fonts/blob/master/alpha/from-pipeline/unhinted/variable-ttf/sans/NotoSansSymbols-GX.ttf

https://github.com/googlei18n/noto-fonts/blob/master/alpha/from-pipeline/unhinted/ttf/sans/NotoSansSymbols-Black.ttf

https://github.com/googlei18n/noto-fonts/blob/master/alpha/from-pipeline/unhinted/ttf/sans/NotoSansSymbols-Regular.ttf

**Comment by edent** [comment]
The repo has been updated.  Any news on when they will move out of alpha?

Currently available in: https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/ttf/sans

**Comment by dougfelt** [comment]
Not in the initial release.  Sometime after the font is final, but the timing is up to the Android folks.

**Comment by edent** [comment]
Thanks. Any word on when the final release will be? 

Anything I can do to help?

**Comment by dougfelt** [comment]
> Thanks. Any word on when the final release will be?

Android?  I can't comment on release timing, unfortunately.  

We're trying to push a lot of phase 3 fonts out at the moment, we're still working kinks out of our release process.  I don't see Symbols on the initial list, but I believe the current thinking is to release it as-is and then update it.  @marekjez86 might know more.

**Comment by edent** [comment]
Hello! Anything I can do to help the process along?

**Comment by dougfelt** [comment]
NotoSansSymbols was released on github awhile ago.  Does it not have the characters you're interested in?

We're still working through some kinks pushing out the release on get/noto.

Can't say anything about Android.

**Comment by edent** [comment]
It does not as far as I can see. I've checked:

* https://github.com/googlei18n/noto-fonts/blob/master/hinted/NotoSansSymbols-Regular.ttf
* https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSansSymbols-Regular.ttf
* And the latest release on https://www.google.com/get/noto/

I understand that you can't say anything about Android. I don't mind about that. But I would like to know about the updated font.

**Comment by dougfelt** [comment]
Oh, sorry, that should be in Symbols2.  My mistake.  That should be up
fairly soon, the font was approved.

**Comment by ashman399** [comment]
I DONT HAVE A CLUE WHAT IM DOING DOES THAT HELP OR COUNT  LOL NEVER HAVE.
DONT KNOW WHY I EVEN SUBSCRIBED IN THE FIRST POLACE

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#m_7155706837941465977_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by marekjez86** [comment]
@edent : Please see https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSansSymbols2-Regular.ttf  (soon, within days, it will also be up on get/noto)

**Comment by edent** [comment]
Woo! Thanks 😀

**Comment by ashman399** [comment]
lmao ok simple question how do i unsubscribe lmfao


[image: Inline image 1]😎😎😎😎


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by nizarsq** [comment]
23FB, 23FC, 23FD, 2B58 and 23FE added to NotoSansSymbols2. IssUE FISED

<img width="614" alt="Screen Shot 2020-07-27 at 9 02 16 PM" src="https://user-images.githubusercontent.com/22158882/88617853-765b2c80-d04c-11ea-8c7b-91b19808c33e.png">
