### ISSUE TITLE
Noto Nastaliq Urdu rendered wrong on Android 4.4 native and webview

### ISSUE THREAD

**Issue by snowpong** [googlefonts/noto-fonts#691]
I'm seeing Noto Nastaliq Urdu rendered wrong in both TextView and WebView on an Huwai Honor 4C running Android 4.4.1. I've attached a screenshot and marked some errors with a red circles.

![noto nastaliq urdu wrong on native and webview android 4 4 1](https://cloud.githubusercontent.com/assets/177436/15542392/dbcf56cc-2290-11e6-9720-98f62b4035fa.png)

I've compared the Noto Nastaliq Urdu font with the Nafees font found at https://fontlibrary.org/en/font/nafees-nastaleeq which seems to render more correctly.

A typical error is that strokes that should be one continuous line are broken up.

Devices running later versions of Android (for example 5.1 or 6.0) seems to render Noto Nastaliq Urdu fine in both TextView and WebView.

Note: I do not speak or read Urdu so I'm relying on end users to help me point out errors.

**Comment by brawer** [comment]
@behdad, do you know if Noto Nastaliq needs a particular Harfbuzz version?

**Comment by behdad** [comment]
> @behdad, do you know if Noto Nastaliq needs a particular Harfbuzz version?

No, but does require recent enough Android.  In this case, since both webview and textview are affected, I'm guessing that there's something else going on.  Don't know, impossible to debug this way.

cc @raphlinus to advise if 4.4.1 has proper HarfBuzz.

**Comment by snowpong** [comment]
@behdad Is anything I could do to make it easier for you to debug?

**Comment by marekjez86** [comment]
I do not speak Arabic, Urdu, etc (so I don't know if the text below is correct, is the same as the text in question ...)
but I used the following input 
کیا خلاتی مخلوق وجود رکھتی ے ؟

I ran hb-view from recent harfbuzz using as fonts both 

https://fontlibrary.org/en/font/nafees-nastaleeq
![nafeesnastaleeq](https://cloud.githubusercontent.com/assets/13322623/15969075/241925da-2ee3-11e6-9d66-c749a79a1aa3.png)



and 
https://www.google.com/get/noto/#nastaliq-aran
![notonastaliqurdu](https://cloud.githubusercontent.com/assets/13322623/15969084/2fb657be-2ee3-11e6-99d8-2d2e166e4541.png)


Looks that the most recent harbuzz looks OK

**Comment by behdad** [comment]
> @behdad Is anything I could do to make it easier for you to debug?

Not really.  I'm not going to debug this.  Someone else needs to. You can start by getting the exact version of HarfBuzz used in your product built and test against it in isolation from Android.  Or just find which version of HarfBuzz it was and test that.

**Comment by byDigitalAlchemist** [comment]
Hi Guys, Thanks for the wonderful work, i can help out in urdu font development, Quite good with writing and speaking urdu, any guide how to co-ordinate?

**Comment by simoncozens** [comment]
I'm afraid I'm going to close this now on the basis that Android 4 is currently ten years old and affects less than 2% of users. This is a rendering bug, not a font bug anyway.
