### ISSUE TITLE
Bad UPA tone letter glyphs

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#712]
In Noto Sans 1.06, U+A720..U+A721 MODIFIER LETTER STRESS AND HIGH/LOW TONE are non-spacing but should be spacing. They are horizontal but should slant downwards. U+A721 is backwards. U+02FB..U+02FC MODIFIER LETTER BEGIN/END LOW TONE are too high: they should be on the baseline. All of these tone letters plus U+02F9..02FA MODIFIER LETTER BEGIN/END HIGH TONE are too small and squat. See [figure 75 of N2419](http://www.unicode.org/L2/L2002/02141-n2419-uralic-phonetic.pdf#55) and [figure 3 of N2958](http://www.unicode.org/L2/L2005/05189-n2958-upa-report.pdf#3).

**Comment by TidharC** [comment]
I can reproduce the issues above in Noto Sans (see screenshot).
![upanotosans](https://cloud.githubusercontent.com/assets/16353803/18734797/ad5a54a0-802c-11e6-9822-34b1e5b111f2.png)

**Comment by TidharC** [comment]
Fix verification in progress.

**Comment by TidharC** [comment]
Retested with Noto Sans and Noto Serif variants.  All fonts look good, except for Noto Sans Italic which is still not fixed.  Renderings are attached.



[specimenNotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/626073/specimenNotoSans-Italic.pdf)



[specimenNotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/626063/specimenNotoSans-Black.pdf)
[specimenNotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/626064/specimenNotoSansDisplay-Black.pdf)
[specimenNotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/626065/specimenNotoSansDisplay-Italic.pdf)
[specimenNotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/626068/specimenNotoSerif-Black.pdf)
[specimenNotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/626067/specimenNotoSerifDisplay-Black.pdf)
[specimenNotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/626066/specimenNotoSerifDisplay-Italic.pdf)
[specimenNotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/626070/specimenNotoSerif-Italic.pdf)

**Comment by marekjez86** [comment]
test sample
```html
<html lang="en">
<p><span style="font-size:48.0px">A꜠B꜡C˹D˺E˻F˼G</span></p>
</html>
```

en-712-NotoSans-Italic looks incorrect
![en-712-notosans-italic](https://cloud.githubusercontent.com/assets/13322623/21629591/acc6e93c-d1de-11e6-9c4e-678d0859da34.jpeg)

all other Noto look fine

@dscorbett @roozbehp : what do you think of Roboto's positioning of these glyphs?
All Roboto's look like this Roboto Regular
![en-712-roboto-regular](https://cloud.githubusercontent.com/assets/13322623/21629663/41beb5e2-d1df-11e6-8d1b-f3f1fe080663.jpeg)

[en-712-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683776/en-712-NotoSans-Black.pdf)
[en-712-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683775/en-712-NotoSans-Italic.pdf)
[en-712-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683778/en-712-NotoSans-Regular.pdf)
[en-712-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683780/en-712-NotoSansDisplay-Black.pdf)
[en-712-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683777/en-712-NotoSansDisplay-Italic.pdf)
[en-712-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683779/en-712-NotoSansDisplay-Regular.pdf)
[en-712-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683781/en-712-NotoSansMono-Black.pdf)
[en-712-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683782/en-712-NotoSansMono-Regular.pdf)
[en-712-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683783/en-712-NotoSerif-Black.pdf)
[en-712-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683784/en-712-NotoSerif-Italic.pdf)
[en-712-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683786/en-712-NotoSerif-Regular.pdf)
[en-712-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683785/en-712-NotoSerifDisplay-Black.pdf)
[en-712-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683788/en-712-NotoSerifDisplay-Italic.pdf)
[en-712-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683787/en-712-NotoSerifDisplay-Regular.pdf)
[en-712-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683789/en-712-Roboto-Black.pdf)
[en-712-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683790/en-712-Roboto-Italic.pdf)
[en-712-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683791/en-712-Roboto-Regular.pdf)

**Comment by nizarsq** [comment]
This issue resolved for NotoSans-Italic and other fonts as well. Closing the bug for now.
<img width="595" alt="Screen Shot 2020-07-20 at 9 20 21 AM" src="https://user-images.githubusercontent.com/22158882/87961190-3dc6bc00-ca6a-11ea-98e0-45e200ece09a.png">
