### ISSUE TITLE
U+061C (ALM) should be removed from Thaana and Nastaliq fonts

### ISSUE THREAD

**Issue by roozbehp** [googlefonts/noto-fonts#721]
The presence of the glyph in the Thaana font is forcing weird behavior in Android, causing the Thaana font to get selected for the colon in a sequence such as <ARABIC-INDIC DIGIT ONE, ALM, COLON>. Of course Android should know better (I'll file a separate bug for that), but the fonts should be cleaner too.

The Nastaliq font is not shipped on Android devices, but should have the glyph removed too.

PS: If there's a legitimate reason for Nastaliq and Thaana fonts to support ALM, then all fonts for scripts whose letters default to bidi=AL should have support ALM.

/cc @raphlinus

**Comment by behdad** [comment]
But, if it wasn't for Android's don't selection issue, we do want ALM in these fonts, right?

**Comment by roozbehp** [comment]
> But, if it wasn't for Android's don't selection issue, we do want ALM in these fonts, right?

That's a hard question:

Theoretically, you may want a glyph similar to that of RLM and LRM so that you can do "show invisible" with it. In practice, several platforms may not know about the character ALM at all, not even know it's default-ignorable, so it may be better for the glyph to be empty and zero-advance.

So, it all depends on which platform/product and which specific version of that you are targeting.

**Comment by behdad** [comment]
Agree empty and zero-advance is preferable.

**Comment by marekjez86** [comment]
ALM is present, but is now empty and zero width as per Google's suggestion.
