### ISSUE TITLE
Noto Serif Bengali critique

### ISSUE THREAD

**Issue by jacobathomas** [googlefonts/noto-fonts#725]
I'm here at the TDi at Reading University with Marek, and he asked me to critique the Noto Serif Bengali.  For a little background, I grew up in Bangladesh where I have worked for the last decade as a graphic designer with Latin and Bengali designs.  My feedback on the Noto Serif Bengali font:
-     The ও strikes the eye as feeling too large
-     The থ head (curl/ball) feels too small and cramped
-     The স্থ (sth) feels very stunted and short
-     The এ feels like it extends too high
-     The bottom tail of the হ/ই feels too short and cramped into the upper body
-     The perfectly vertical initial stem of the দ seems too geometric
-     The chandrabindu is over the consonant instead of the vowel, which is wrong
-     The 'গ' is too cramped together, it feels like it should extend further down
-     The 'গ্র' (ga with raphala) compresses this even more, and the contrast between the compressed and non-compressed looks even more awkward
-     The 'ষ্ট' feels like it's falling forward
-     The rikaar is too compressed into the 'ত' ('তৃ')
-     The flourish in the 'i-kaar' seems pulled high
-     The ফ্র feels too condensed vertically
-     The reph feels too small and weak
-     The top left elbow of the জ feels weak and indecisive

Honestly, I wouldn't use it the way it stands.  I do use the Noto Sans Bengali now and then, but I really don't like their weak "ণ" in the sans.

Hope that helps!

**Comment by marekjez86** [comment]
Thank you very much for a thorough feedback. Could you elaborate on 'weak "ণ" in the sans'? Is it too small, poorly drawn or structured? Is there an image of text from a newspaper, a website, a magazine, a sign, etc... with what you'd consider 'strong "ণ"' ?

**Comment by jacobathomas** [comment]
![notoserifbengali-critique](https://cloud.githubusercontent.com/assets/20583790/17035451/3121b4e2-4f7f-11e6-910c-0a32f586ee89.jpg)
The letter doesn't extend far down enough; the curve ends too early.  This may have been an attempt to match the curvature of the other similar strokes in the ন and ম, but it needs to be different here.  I hope the image makes it clear.

**Comment by JelleBosmaMT** [comment]
Seems a fair comment about the Sans ণ.  Unification of features and simplification of shapes is what a Sans makes a Sans for scripts that do not have serifs to begin with. I may have been too consistent here. I haven't looked at the design in several years, but will be having a fresh look when starting with additional weights.

Of course this Github item being mostly about the Serif, maybe the bowl of ণ should have a separate issue number. Now I am assigned to an issue that I am not expected to do something about.

**Comment by marekjez86** [comment]
The new version of Bengali was reviewed by Fiona hence I hope the critique here was addressed. See https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSerifBengali

**Comment by Dhiman4us** [comment]
1. The first missing feature of NotoSansBengali is the missing of bunch of i-kars of different lengths. Just like Devanagari, In Bengali the length of ikar depends on very much of the wideness of a character. Though NotoSansHindi/Devanagari has it.


2. Some glyphs of Samsung default/stock SEC-Bengali font are wrong! Some years ago it was smooth without any glitch. I think the old one was Google NotoSansBengali without any modifications. But later SAMSUNG have modified the fonts i.e. Google NotoSansBengali to SEC-Bengali in such a way that become disaster for the whole Bengali community. It changes the shape of some BASIC IMPORTANT glyphs like "ম"(Bengali-Ma, U+09AE) thats very different from the original one and looks so close with other glyph "য"(Bengali-Ya, U+09AF). I am attaching screenshots comparing both previous and new wrong glyphs. We, the whole Bengali community who are using samsung devices are suffering from this issue from past 2/3 years. Please ordered Samsung to fix it.
![20200405_203444](https://user-images.githubusercontent.com/63197770/78502284-07488800-777e-11ea-99c6-71a21d993c61.jpg)
![PicsArt_01-21-10 21 21](https://user-images.githubusercontent.com/63197770/78502291-0e6f9600-777e-11ea-86e4-2509b2fd6baf.jpg)
![PicsArt_01-21-10 09 25](https://user-images.githubusercontent.com/63197770/78502292-0fa0c300-777e-11ea-87fc-faff81393589.jpg)

**Comment by JelleBosmaMT** [comment]
The maintenance update of Noto Sans Bengali has i-vowel signs with variable length. It also has a Ma  with what I think are improved proportions (new version to the right). I am not sure if I would have recognised the Ma of SEC-Bengali as being a Ma. Noto Sans Bengali was criticised by some for using a style without knots. Maybe the SEC version was an attempt to make it into the knot style, but then without a knot.

![ma change](https://user-images.githubusercontent.com/12729011/79216356-4f863b00-7e4d-11ea-80f1-774d7facde23.png)
