### ISSUE TITLE
noto nastaleeq urdu

### ISSUE THREAD

**Issue by sipraomer** [googlefonts/noto-fonts#726]
The word Allah isn't displaying properly. It is missing the shaddah. It should be typed automatically when we type the word Allah. However, I can't even put it manually at the right place.

**Comment by behdad** [comment]
Right.  MarkLig attachment on LamLamHeh ligature seems to be missing or wrong.  Kamal, can you please confirm?

**Comment by behdad** [comment]
Note that you must type the shaddah.  But yes, even if you do, the positioning is wrong.

**Comment by kmansourMT** [comment]
I confirm the reported error. It will be fixed in the next version.

**Comment by behdad** [comment]
Thanks Kamal.

**Comment by kmansourMT** [comment]
As previously agreed, the upcoming version will comply with the behavior specified below. @roozbehp @behdad 

=======================================
From: Roozbeh Pournader <roozbeh@google.com>
Date: Friday, 12 August 2016 at 15:52
To: Behdad Esfahbod <behdad@google.com>
Subject: Re: [pan-unicode-font] Noto Nastaliq Urdu: uFDF2

Ok, this is the spec for all our Arabic scripts fonts. I'm basically showing the input in term of characters, and the output we expect (some of this can be found in https://github.com/googlei18n/noto-fonts/issues/384 and earlier bugs):

FDF2: Show both the Alef, the Shadda, and the Superscript Alef.
Lam, Lam, Heh: Do not ligate in any way. Three separate glyphs expected, with the middle lam with its common height. (No initial Alef, of course.)
Lam, Lam, Shadda, Heh: Ligate with a shorter middle Lam, but do not add a superscript Alef, just the Shadda. (No initial Alef, of course.)
Lam, Lam, Shadda, Alef Maksura, Heh: Ligate and show the proper full ligature that has both superscript Alef and Shadda. (No innitial Alef, of course).

The same patterns should be followed for Heh Goal, with a different ligature form that has a final Heh Goal form. There would be no FDF2 for Heh Goal, of course.

Also, make sure you place the vowels properly on all these sequences. More sequences to test:
<Lam, Kasra, Lam, Shadda, Fatha, Heh, Kasra>
<Lam, Kasra, Lam, Shadda, Superscript Alef, Heh, Kasra>
<Lam, Fatha, Lam, Kasra, Heh, Combining Hamza Above>

**Comment by behdad** [comment]
Sounds good.  I can test when that's available.  Marek, please reassign to me when it is.

**Comment by marekjez86** [comment]
Fixed. Characters combine correctly.
