### ISSUE TITLE
Sans Bengali "ণ" too weak

### ISSUE THREAD

**Issue by dougfelt** [googlefonts/noto-fonts#728]
see #725, in particular the following image:

https://cloud.githubusercontent.com/assets/20583790/17035451/3121b4e2-4f7f-11e6-910c-0a32f586ee89.jpg

The letter doesn't extend far down enough; the curve ends too early. This may have been an attempt to match the curvature of the other similar strokes in the ন and ম, but it needs to be different here. I hope the image makes it clear.

**Comment by jungshik** [comment]
@dougfelt ,  do you think this issue belongs to  Phase 2 bucket?

**Comment by dougfelt** [comment]
Well, maybe not, I wasn't thinking when I assigned the milestone.  We probably couldn't get a fix in time for Android, and since Bengali is a priority 2 it should come soon.  On the other hand from looking at the estimated delivery dates, it's blank, which I interpret as not before next year, so this wouldn't be fixed for 6 months.  Seems like a long wait.

**Comment by hrhatada** [comment]
Hi JelleBosmaMT, This is a separated issue form #725 as you suggested.

**Comment by JelleBosmaMT** [comment]
This is a bit scary. With the plan to start with the design proposal to extend Noto Sans Bengali this morning, I started my computer, to be greeted by the one and only Noto Sans Bengali Github issue...

![new nna](https://cloud.githubusercontent.com/assets/12729011/18670309/98a00732-7f3f-11e6-8e02-eea158c9993c.png)

The ণ is now more like গ and প in posture and less like ন and ল. To the far right the original ণ.

**Comment by JelleBosmaMT** [comment]
With the Bold tried another step: harmonizing the left of the white counter shape of ণ with the left of the right counter of শ.
![new nna bold](https://cloud.githubusercontent.com/assets/12729011/18687749/cfbb6530-7f81-11e6-895a-24444101d444.png)

**Comment by nizarsq** [comment]
U+09A3 has been fixed in NotoSansBengali, currently the curve extend enough as it should. Closing the bug for now.
<img width="1192" alt="Screen Shot 2020-06-11 at 7 31 06 AM" src="https://user-images.githubusercontent.com/22158882/84399456-bd34b600-abb5-11ea-9723-02f45498e46e.png">
