### ISSUE TITLE
Noto Naskh Arabic - rendering problems on OS X/macOS and iOS

### ISSUE THREAD

**Issue by aiaf** [googlefonts/noto-fonts#730]
The following string pattern causes the text to break apart for Noto Naskh Arabic v1.060 downloaded from https://www.google.com/get/noto/

On any given line, if the line contains an Alef with Hamza above أ or below إ and ends with a ligature followed by blank space, the entire line exhibits weird rendering issues.

Example problematic strings (note that they end with a blank space):

**Example 1** (has Alef w/ Hamza above & ends with لا + space)

`أرشيف المدرسة لا`

Result on OS X 10.11.6 [https://i.imgur.com/C00VRQ6.png](https://i.imgur.com/C00VRQ6.png)
Result on iOS 9.3 [https://i.imgur.com/qDte4yw.png](https://i.imgur.com/qDte4yw.png)

**Example 2** (has Alef w/ Hamza above & ends with الله + space)

`ونبدأ بسم الله`

Result on OS X 10.11.6 [https://i.imgur.com/eT99qe1.png](https://i.imgur.com/eT99qe1.png)
Result on iOS 9.3 [https://i.imgur.com/ZApvMTA.png](https://i.imgur.com/ZApvMTA.png)

Note the position of the caret-- goes to end of line.

A similar behavior is also present in Noto Nastaliq Urud & the Mirza font https://github.com/Tarobish/Mirza which I downloaded from fonts.google.com so I'm thinking maybe a problem with a common toolchain or OT code? Just guessing.

Thanks!

**Comment by Tarobish** [comment]
@aiaf please check our live testing page
I didn't find any problem here

![screen shot 2016-08-05 at 12 58 31 pm](https://cloud.githubusercontent.com/assets/8403973/17449035/92dd027a-5b0c-11e6-9975-1953af64f2b2.png)

**Comment by aiaf** [comment]
@Tarobish these must be tested with a native application that uses Apple's Core Text. Depending on the browser you used, it's probably using its own layout engine.

**Comment by Tarobish** [comment]
@graphicore

**Comment by nizarsq** [comment]
I was able to reproduce this bug on TextEdit, it looks weird. Noticed two things, first when letter Alef shift the Hamza will disappear, the other thing noticed is when you change any part of the sentence the text will display correctly.

![screen shot 2016-09-15 at 10 06 45 am](https://cloud.githubusercontent.com/assets/22158882/18559447/21b1ab9c-7b2c-11e6-94d4-885ee98452e8.png)
 
![screen shot 2016-09-15 at 10 28 41 am](https://cloud.githubusercontent.com/assets/22158882/18560292/d32b1efa-7b2f-11e6-8d56-123463913068.png)

**Comment by nizarsq** [comment]
Update, Tested this font (Noto Naskh Arabic) on windows platform and issue NOT produceable, rendering is perfectly fine.

**Comment by KatMomoi** [comment]
Not sure if this is the font side problem or platform side problem. But the problem does exist on Mac OS X for sure. Need a bit more digging.

**Comment by KatMomoi** [comment]
We should add that it is important to get this correctly for Arabic on Mac OSX.

**Comment by dougfelt** [comment]
@behdad, can you look at this?

**Comment by behdad** [comment]
First we need to verify it happens with OS X 10.12.  If it does, report to Apple.  When you do, send me the bug number so I can follow up with CoreText people.

**Comment by jungshik** [comment]
@brawer, this might be one case of what you're looking for if it's still broken on Mac OS 10.12.

**Comment by aiaf** [comment]
FYI this is still an issue on macOS Sierra 10.12.

**Comment by marekjez86** [comment]
@behdad : created an apple developer bug # 29201865

![bug29201865](https://cloud.githubusercontent.com/assets/13322623/20189101/8e9ca6dc-a730-11e6-95cb-cbdf366c1d7f.jpg)

**Comment by behdad** [comment]
Thanks.  Asked Ned to check.

**Comment by nizarsq** [comment]
Tested string pattern mentioned on OS X 10.15.4 (19E287) and this issue to reproducible in this platform. closing this bug.
<img width="547" alt="Screen Shot 2020-06-04 at 12 01 15 PM" src="https://user-images.githubusercontent.com/22158882/83799939-7138bd00-a65b-11ea-8ed5-a401b6c5ab7a.png">
