### ISSUE TITLE
Rename NotoNastaliqUrdu to NotoNastaliq?

### ISSUE THREAD

**Issue by brawer** [googlefonts/noto-fonts#735]
NotoNastaliqUrdu seems to support other languages beyond Urudu. Should it really have “Urdu” in its name? Or should it be renamed to just “NotoNastaliq”?

<img alt="NotoNastaliqUrdu in FontView" src="https://cloud.githubusercontent.com/assets/1527880/17967186/0010ee38-6ac6-11e6-9eeb-f4528983c221.png">

In theory, we could release a NotoNastaliqPersian, NotoNastaliqKashmiri etc. with different _default_ language systems but otherwise identical glyphs and lookups. This would be similar to what we currently do for NotoSansCJK. However, this would make things more complicated to maintain and to explain. Also, not sure if the marginal benefit would be worth the complexity: afaik localized letterforms are supported by all the modern platforms we care about; including Android, Firefox, and Chrome.

**Comment by roozbehp** [comment]
The font is named Urdu because this is the Urdu style of writing Nastaliq. Others languages (like Persian and Pashto) write Nastaliq in a different style, and sharing one font for the quite different styles doesn't make much sense.

**Comment by brawer** [comment]
@xiangyexiao, should we plan making Nastaliq fonts for Persian or Pashto?

**Comment by ebraminio** [comment]
> should we plan making Nastaliq fonts for Persian or Pashto?

That would be fantastic I believe, have a look at [this](https://en.wikipedia.org/w/index.php?title=Template:Script/Nastaliq&action=edit), lots of scripts with their favorite list of fonts are listed there. Another interesting note, as [said before](https://groups.google.com/d/msg/noto-font/blDzCkGkT_4/LQJepS8lD-kJ). it seems 'Urdu Emad Nastaleeq' which is an Urdu font, is also appealing for Persian so there might be a chance for building a unified Nastaliq font, but that isn't the current Noto Nastaliq Urdu design which is good for its goal of course. 


As a test, ask from a Persian or Urdu speaker to guess which one is their flavor Nastaliq style?
![emadvsirannastaliq](https://cloud.githubusercontent.com/assets/833473/19560418/47e18af0-96e1-11e6-8c90-07ccd3a81ef9.png)


One (not necessarily the first) is IranNastaliq and the other is the mentioned font. (hint: look at گ diacritic and also dots)


Another comparison, which is highly different from the first, which Emad is compared with Taj Nastaliq which is only appealing for Urdu people I'd guess.
![emadvstajnastaliq](https://cloud.githubusercontent.com/assets/833473/19560470/87758694-96e1-11e6-9605-f04d758ec3f7.png)

**Comment by xiangyexiao** [comment]
How popular is the Nastaliq style to Persian, compared to Naskh? @ebraminio

**Comment by xiangyexiao** [comment]
This [wikipedia page](https://en.wikipedia.org/wiki/Nasta%CA%BFl%C4%ABq_script) says: In Persian it is used for poetry only.

**Comment by ebraminio** [comment]
Yes, not very, unfortunately. My last comment was just [not scientific and reliable, but worth to further researched, IMO] thoughts that if you like to have some unified Nastaliq font, the little differences of Persian and Urdu on that [imaginary] font could be filled with some opentype language tag, if you choose right overall design perhaps.

**Comment by ebraminio** [comment]
A generic Nastaliq can be useful to reduce complication of implementing such improvements:  https://www.w3.org/Bugs/Public/show_bug.cgi?id=29953 (by referencing same font for entire Arabic script, Nastaliq is not unfamiliar for Arabic speaker, a Persian appealing Nastaliq font was used to be on [Arabic Wikipedia](https://web.archive.org/web/20130301123752/http://ar.wikipedia.org/wiki/%D8%A7%D9%84%D8%B5%D9%81%D8%AD%D8%A9_%D8%A7%D9%84%D8%B1%D8%A6%D9%8A%D8%B3%D9%8A%D8%A9) for years)

**Comment by marekjez86** [comment]
It is called Urdu as this is the Urdu style of writing Nastaliq. Urdu should stay in name.

**Comment by davelab6** [comment]
@ebraminio Marek and I discussed the other issue you raised here, and agree that a Persian (non Urdu) style Nastaliq is theoretically in scope for Noto, but is unlikely to be commissioned by Google this year.

**Comment by ebraminio** [comment]
Thanks. Definitely great to even be considered I believe.

**Comment by ebraminio** [comment]
And just to note HarfBuzz logo https://github.com/harfbuzz is also from IranNastaliq font but I definitely wished it was a Noto font, either a Persian flavor of Nastaliq or some Nastaliq that could be used for Urdu and Persian at the same time, which, as said repeatedly I see it possible and like it also just that it isn't the current design and some considerations would be needed.

Maybe supporting different calligraphic styles of Arabic script as listed by https://w3c.github.io/alreq/#h_writing_styles specially am referring to Shekasteh Nastaliq https://en.wikipedia.org/wiki/Nastaliq#Shekasteh_Nastaliq the ones you may see more relevant of course, can be the next hit for Noto project.
