### ISSUE TITLE
Noto Sans T Chinese "spacing problem" in Office Word 2011 for MAC OS.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#74]
```
What steps will reproduce the problem?
When use Noto Sans T Chinese, the spacing becomes very big. 

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
Office Word 2011 for MAC OS.

Please provide any additional information below.


```

Original issue reported on code.google.com by `stacycha...@gmail.com` on 18 Jul 2014 at 2:32

Attachments:
- [Google Noto T Chinese - spacing problem.png](https://storage.googleapis.com/google-code-attachments/noto/issue-74/comment-0/Google Noto T Chinese - spacing problem.png)

**Comment by kenlunde** [comment]
I just installed Microsoft Office 2016 for Mac, and this issue seems to have been fixed.
