### ISSUE TITLE
Noto Sans Coptic: double inverted breve

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#748]
In Noto Sans Coptic, U+0361 COMBINING DOUBLE INVERTED BREVE extends over the previous character. It should extend over the next character.

The same problem applies to U+1DCD COMBINING DOUBLE CIRCUMFLEX ABOVE. Also, U+1DCD looks like an inverted breve instead of a circumflex.

**Comment by TidharC** [comment]
In Noto Sans Coptic, I see both combining marks extend toward the next char (see screenshot).  But the two marks do look the same.

By comparison, in Antinoou the two marks look different.
![notosanscopticcombining](https://cloud.githubusercontent.com/assets/16353803/18804055/eae395e6-81aa-11e6-9156-8d50ad789486.png)

**Comment by TidharC** [comment]
Can you provide more specifics on how you reproduce the extension issue?

**Comment by dscorbett** [comment]
U+0361 extends backwards in BabelMap, which uses Uniscribe. It extends forwards in Firefox, which uses Graphite. Maybe it is a Uniscribe bug. The character does work in other fonts in BabelMap though.

**Comment by jungshik** [comment]
We have to check first if Noto Sans Coptic has those two combining characters.

**Comment by TidharC** [comment]
I verified that both U+0361 and U+1DCD are listed in Noto Sans Coptic.

Does BabelMap use Uniscribe or DirectWrite?  Which version of Windows is it on?

**Comment by dscorbett** [comment]
BabelMap uses Uniscribe. This is on Windows 7 and Windows 8.

**Comment by marekjez86** [comment]
@dscorbett : please check https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/ttf/sans/NotoSansCoptic 
According to my understanding it should be fixed

**Comment by dscorbett** [comment]
U+1DCD has a better shape now, but both glyphs are still mispositioned in Uniscribe.

```bash
$ echo $'\xe2\xb2\x81\xcd\xa1\xe2\xb2\x83' | hb-shape NotoSansCoptic-Regular.ttf
[uni2C81=0+574|uni0361=0@461,0+0|uni2C83=2+576]
$ echo $'\xe2\xb2\x81\xcd\xa1\xe2\xb2\x83' | hb-shape NotoSansCoptic-Regular.ttf --shapers=uniscribe
[uni2C81=0+574|uni0361=0+0|uni2C83=2+576]
```
