### ISSUE TITLE
Noto Sans Hebrew space character showing as tofu

### ISSUE THREAD

**Issue by davelab6** [googlefonts/noto-fonts#762]
A user reported an issue with Noto Sans Hebrew downloaded from google.com/get/noto at https://github.com/google/fonts/issues/400

> Spaces show up as a box/tofu with Noto Sans Hebrew loaded onto a Mac running macOS 10.12; spaces show up correctly when text is entered-as/changed-to to Arial.

**Comment by TidharC** [comment]
Tested with Text Edit on macOS 10.11.6, could not repro.

**Comment by TidharC** [comment]
Not reproducible on MacOS 10.12 using:
TextEdit, Chrome, Firefox, Safari.
Test string: U+05D0 U+0020 U+05D1

@davelab6, are you still seeing this problem?

**Comment by nizarsq** [comment]
No tofu noticed on any of the 3 fonts (NotoSansHebrew, NotoRashiHebrew or NotoSerifHebrew). Closing this bug for now.
<img width="673" alt="Screen Shot 2020-08-04 at 10 34 08 PM" src="https://user-images.githubusercontent.com/22158882/89375496-9d47dd00-d6a2-11ea-92d3-3e7b5d30a98a.png">
