### ISSUE TITLE
Why are only TTF, but not OpenType files distributed?

### ISSUE THREAD

**Issue by lvml** [googlefonts/noto-fonts#771]
Every comparison of TrueType versus OpenType font file formats I found claims that OpenType is the better, more advanced format. Yet, the files advertised for downloading at https://www.google.com/get/noto are of TrueType format.

Do the OpenType files hidden in https://github.com/googlei18n/noto-fonts/tree/master/alpha/OTF/from-pipeline have any disadvantage that one should know of?

**Comment by marekjez86** [comment]
re: Do the OpenType files hidden in https://github.com/googlei18n/noto-fonts/tree/master/alpha/OTF/from-pipeline have any disadvantage that one should know of?

The files there are from a pipeline that is a "work-in-progress" at this point and while we tested them they might have I do not think we tested them enough to post them publicly.

**Comment by lvml** [comment]
On 10/17/2016 05:03 PM, Marek Jeziorek wrote:
> The files there are from a pipeline that is a "work-in-progress" at this point and while we tested
> them they might have I do not think we tested them enough to post them publicly.

If the TTF files were more thoroughly / earlier tested than the OTF files,
does this imply the OTF files were derived from the TTF version - and do not
make use of any of the OTF-specific features which would make it worth to
prefer the OTF version over the TTF version?

**Comment by jungshik** [comment]
@lvml  'TTF' files we published do have all the opentype features (GSUB, GPOS, etc). That is, they're Opentype fonts with truetype (quadratic) outlines. What's in master/alpha/OTF/from-pipeline is Opentype fonts with CFF/postscript (cubic) outlines.

**Comment by lvml** [comment]
Thanks for the explanation - but it still leaves me somewhat uncertain whether the Noto authors recommend using the TTF variant or the OTF variant, where the software is capable of both.
Maybe one or two sentences on this added to README.md could clarify the situation?

**Comment by xiangyexiao** [comment]
TTF fonts are more widely used than CFF fonts. In the past, we only got TTF fonts from Monotype. With fontmake and noto-sources, we/users can generate both TTF and CFF fonts.

**Comment by lvml** [comment]
@xiangyexiao I understand these two options exist - but is there any reason to prefer one over the other?

**Comment by simoncozens** [comment]
We now provide both OTF and TTF binaries in this repository.
