### ISSUE TITLE
Rendering of Noto Sans Devanagari with FOP 2.1

### ISSUE THREAD

**Issue by claudius108** [googlefonts/noto-fonts#777]
Hi,

Thank you for this nice initiative!

I tested Noto Sans Devanagari with the attached fo file, and there are some small (but important) differences in the generated PDF. For testing, you will just need to updated the path to the image in fo:external-graphic/@src.
![noto-devanagari-font](https://cloud.githubusercontent.com/assets/1745822/19593228/da17f4ce-977f-11e6-857c-de15cc5ecd79.png)

Claudius Teodorescu,
University of Heidelberg, Germany

**Comment by marekjez86** [comment]
@claudius108 : Claudius, (i) could you provide us with the text (as opposed to the image - I'm not a speaker/reader of the language and I cannot duplicate the text to try to reproduce the problem) and (ii) what should be the right rendering of the "small (but important) differences" (could you take a photo?) and where was the right rendering obtained (which system with which font)? This would help us to define the goal and enable non-speakers to test it.

**Comment by claudius108** [comment]
Hi,

The test is in the attached FO file, and I am adding it here, too: कारणत्त्वङ्गवाश्वादीनमपीति चेत् युक्तम्.

I attached an image showing the small vertical lines that are missing in FOP output. To see what is missing, one needs just to convert the attached FO file to PDF with FOP 2.1.

In order to show the correct rendering, I took the correct text from an XML file and simply created a PNG file by using gimp on Ubuntu.

If you need more details, please ask.

![noto-devanagari-font-error-marked](https://cloud.githubusercontent.com/assets/1745822/19611390/d05b41d6-97e1-11e6-98f8-a8d84e58af2b.png)

**Comment by marekjez86** [comment]
thank you

**Comment by jungshik** [comment]
@claudius108 
Given that you can get the correct shaping result with GIMP while you can't with FOP 2.1, it's most likely that it's not a font bug but a bug in FOP (or a PDF viewer).  Have you contacted FOP folks about this issue? 

Can you also attach a PDF file you generated with FOP with this problem?
Do you have the same issue when the target format is PNG instead of PDF?

**Comment by lingv-ro** [comment]
I filed a FOP issue, indeed, see https://issues.apache.org/jira/browse/FOP-2454.

I attached a PDF file.
[noto-sans-devanagari.pdf](https://github.com/googlei18n/noto-fonts/files/619640/noto-sans-devanagari.pdf)

I attached the output for PNG generation.
![noto-sans-devanagari](https://cloud.githubusercontent.com/assets/16834112/20720296/4b1d55b4-b667-11e6-8f7b-2f32947647b2.png)

**Comment by nizarsq** [comment]
Test case created.
<img width="1098" alt="Screen Shot 2020-06-09 at 12 13 26 AM" src="https://user-images.githubusercontent.com/22158882/84117666-b9066e00-a9e6-11ea-88b9-edfad7bd742f.png">

**Comment by claudius108** [comment]
It is much better, thanks.

**Comment by nizarsq** [comment]
Great! Thank you
