### ISSUE TITLE
Noto Sans Hebrew missing basic punctuation

### ISSUE THREAD

**Issue by shikuru** [googlefonts/noto-fonts#781]
commas and full stops seem to be completely missing (using indesign cc)

**Comment by dougfelt** [comment]
Are you referring to Latin punctuation?  The Noto fonts are designed to be used with fallback in conjunction with NotoSans/NotoSerif to get common Latin characters like punctuation and ASCII digits.

**Comment by hrhatada** [comment]
@shikuru, have you downloaded NotoSans/NotoSerif together with Noto Sans Hebrew?  If not, please download them and see if you can use the punctuation and ASCII digits.

**Comment by shikuru** [comment]
i downloaded the whole font, problem is that in InDesign the punctuation is missing from symbols of NatoSans Hebrew and therefor cant find it

**Comment by TidharC** [comment]
I found a couple of inDesign-related articles which may be useful:

https://forums.adobe.com/thread/1103338

http://graphicdesign.stackexchange.com/questions/34992/can-i-automatically-replace-missing-fonts-by-other-fonts-in-indesign

**Comment by bg-sclark** [comment]
I am trying to update Adobe Illustrator CC files from using Arial Hebrew to Noto Sans Hebrew and periods, commas, and parentheses are not changing.

**Comment by nizarsq** [comment]
@marekjez86 I think this is WAI.

**Comment by marekjez86** [comment]
Correct observation. Noto tries to implement Unicode standard for each script. Hebrew script is defined in https://unicode.org/charts/PDF/U0590.pdf ... Which characters in https://unicode.org/charts/PDF/U0590.pdf we are specifically missing? Please advise and I'll reopen this.
