### ISSUE TITLE
Jupiter symbol

### ISSUE THREAD

**Issue by dougfelt** [googlefonts/noto-fonts#811]
This was originally misfiled in googlei18n/noto-cjk#31

I think the only issue that needs addressing is the Jupiter symbol U+2643, most of the others are not currently an issue in the phase 3 font.  The Jupiter symbols should be a bit more upright, like https://en.wikipedia.org/wiki/File:Jupiter_symbol.svg

**Comment by nizarsq** [comment]
This issue fixed.
<img width="1089" alt="Screen Shot 2020-07-27 at 8 49 37 PM" src="https://user-images.githubusercontent.com/22158882/88617129-b1f4f700-d04a-11ea-8a42-6407726b9878.png">
