### ISSUE TITLE
UPA doesn’t look great

### ISSUE THREAD

**Issue by brawer** [googlefonts/noto-fonts#812]
Noto doesn’t seem to render the [Uralic Phonetic Alphabet (UPA)](https://en.wikipedia.org/wiki/Uralic_Phonetic_Alphabet) very well. Compare [expected rendering](http://www.jltypes.com/Uvallanne/UvallanneTesti.pdf) (from a third-party font) to [current rendering with Noto](https://github.com/googlei18n/noto-fonts/files/666435/und-fonupa.pdf). This was generated by running fontdiff on [UPA test cases](https://github.com/googlei18n/noto-source/blob/master/test/und-fonupa.html). Not sure if the [test cases](https://github.com/googlei18n/noto-source/blob/master/test/und-fonupa.html) are 100% correctly encoded in Unicode; if not, they might need fixing.

**Comment by brawer** [comment]
Compare `ᵏ͔χ͔um` when rendered with Noto versus an UPA font. This could probably be fixed by defining anchor points, which would attach marks such as U+0354 to base glyphs. Many more examples can be found by looking at the PDFs attached to the first post on this bug.

![ᵏ͔χ͔um rendered with Noto](https://cloud.githubusercontent.com/assets/1527880/21424654/8acd8672-c844-11e6-871d-db5bc9b05f27.png)  
![same rendered with an UPA font](https://cloud.githubusercontent.com/assets/1527880/21424693/b3f1e160-c844-11e6-95f9-e42db9e4b821.png)

**Comment by marekjez86** [comment]
see related https://github.com/googlei18n/noto-fonts/issues/816

**Comment by nizarsq** [comment]
UPA looks good now for NotoSans, NotoSerif and NotoSansMono
<img width="650" alt="Screen Shot 2020-07-18 at 10 16 54 PM" src="https://user-images.githubusercontent.com/22158882/87867679-648ad280-c944-11ea-8ee1-561e50d40e59.png">
