### ISSUE TITLE
Collision between a tilde above an i and “]”

### ISSUE THREAD

**Issue by sommerluk** [googlefonts/noto-fonts#813]
Following text (first is an i with two combining diacritics, second is a pre-composed i with tilde (without combining diacritics):

aĩ̄]
aĩ]

Noto Sans has a collision between the tilde and the following character “]”. This applies to both, the pre-composed i with tilde and the simple i with combining diacritics.

Tested with current Noto Sans Regular Alpha from github.

![screenshot 1](https://cloud.githubusercontent.com/assets/6830724/21427271/e5dfca0c-c853-11e6-90f4-2577100caa47.png)

**Comment by nizarsq** [comment]
This issue has been fixed
<img width="377" alt="Screen Shot 2020-07-18 at 10 12 47 PM" src="https://user-images.githubusercontent.com/22158882/87867619-d0b90680-c943-11ea-9749-9e7d1470d43f.png">

**Comment by sommerluk** [comment]
Thanks a lot!
