### ISSUE TITLE
Noto Serif: Anchor points for superscript letters

### ISSUE THREAD

**Issue by brawer** [googlefonts/noto-fonts#816]
In Noto Serif, consider defining anchor points for positioning marks on superscript letters. Here’s the sequence `ᵏ͔χ͔um` from [UPA tests](https://github.com/googlei18n/noto-source/blob/master/test/und-fonupa.html):

![image](https://cloud.githubusercontent.com/assets/1527880/21502053/5083aa2a-cc4d-11e6-8d07-c5185b7deffb.png)

**Comment by brawer** [comment]
Another example is the UPA string `ki̮d́ᶻ̌́`, which currently looks like this in Noto Serif:

![image](https://cloud.githubusercontent.com/assets/1527880/21502741/4ed03ae0-cc52-11e6-96eb-977ea5de0146.png)

**Comment by marekjez86** [comment]
test case from https://github.com/googlei18n/noto-source/blob/master/test/und-fonupa.html
produces the following using fontdiff where --before is Roboto and --after is Noto Sans

[und-fonupa-Roboto-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677701/und-fonupa-Roboto-NotoSans-Black.pdf)
[und-fonupa-Roboto-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677702/und-fonupa-Roboto-NotoSans-Italic.pdf)
[und-fonupa-Roboto-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677703/und-fonupa-Roboto-NotoSans-Regular.pdf)

**Comment by nizarsq** [comment]
Look like this issue has been taken care of. Please reopen if you have other thoughts.
<img width="585" alt="Screen Shot 2020-07-23 at 8 31 05 PM" src="https://user-images.githubusercontent.com/22158882/88358349-70e7a480-cd23-11ea-98a1-76e847c872cd.png">
