### ISSUE TITLE
Add Mongolian Supplement characters

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [googlefonts/noto-fonts#822]
The Mongolian Supplement block (U+11660–U+1167F) was added to the Unicode Standard in June, 2016 with the release of version 9.0, this block should be available in Noto Sans Mongolian.

**Comment by TidharC** [comment]
It seems the character block is not included in Noto Sans Mongolian as of version 1.901.

http://www.unicode.org/charts/PDF/U11660.pdf

[NotoSansMongolian-Regular1.901.pdf](https://github.com/googlei18n/noto-fonts/files/756206/NotoSansMongolian-Regular1.901.pdf)

**Comment by KrasnayaPloshchad** [comment]
They can be done via derivating existed glyphs.

**Comment by dougfelt** [comment]
@marekjez86, Monotype should be fixing this, no?

**Comment by marekjez86** [comment]
Unicode is re-working Mongolian. I expect some results toward end of this year. We will NOT make any changes in Mongolian until we hear from the Unicode Consortium.

**Comment by marekjez86** [comment]
fixed in the previous release and in https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansMongolian
