### ISSUE TITLE
issues exporting variable Noto LGC fonts from the Glyphs.app

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#827]
When I try in the Glyphs.app to export variable font from any Noto LGC font source I get an error stating:

_Can't convert to compatible TrueType curves.
Glyph 'eopenreversed' is not compatible._

Could be that this is just the first error (Glyphs.app reports one error at a time).

![notosans-italic-var](https://cloud.githubusercontent.com/assets/13322623/22254628/05694ed2-e20a-11e6-8be7-5490525f6430.jpeg)
![notosans-var](https://cloud.githubusercontent.com/assets/13322623/22254630/056a7f28-e20a-11e6-8ac5-30c98e25b3ab.jpeg)
![notosansdisplay-italic-var](https://cloud.githubusercontent.com/assets/13322623/22254633/056e44c8-e20a-11e6-8ab2-fe48a84d100f.jpeg)
![notosansdisplay-var](https://cloud.githubusercontent.com/assets/13322623/22254629/056a427e-e20a-11e6-96a1-96bd53502c87.jpeg)
![notosansmono-var](https://cloud.githubusercontent.com/assets/13322623/22254631/056a75e6-e20a-11e6-9d94-f857d9f81f6a.jpeg)
![notoserif-italic-var](https://cloud.githubusercontent.com/assets/13322623/22254632/056e00ee-e20a-11e6-8cf3-6049d4bf53fa.jpeg)
![notoserif-var](https://cloud.githubusercontent.com/assets/13322623/22254634/057a26d0-e20a-11e6-9b1a-3627f8cbf3e9.jpeg)
![notoserifdisplay-italic-var](https://cloud.githubusercontent.com/assets/13322623/22254635/057a7c7a-e20a-11e6-8f3e-7eaea9a37188.jpeg)
![notoserifdisplay-var](https://cloud.githubusercontent.com/assets/13322623/22254636/05816706-e20a-11e6-98f3-a61a6eb5d75e.jpeg)

**Comment by Massi2310** [comment]
Hallo, did you find a solution for your problem? I am currently struggling with the same issue:
![bildschirmfoto 2017-03-31 um 10 11 38](https://cloud.githubusercontent.com/assets/26812549/24542052/770d3642-15fa-11e7-8d17-bbb09dc6f2f4.png)
