### ISSUE TITLE
Glyph change for Brahmi letter II ,Vowel signs vocalic r and rr

### ISSUE THREAD

**Issue by sridatta1** [googlefonts/noto-fonts#833]
UTC just accepted my documents on glyph change for these characters ( see [[150-C11](http://www.unicode.org/L2/L2017/17016.htm#150-C11)] and [[150-A64]](http://www.unicode.org/L2/L2017/17016.htm#150-A64) )
Noto Sans Brahmi should use correct glyphs from these documents
http://www.unicode.org/L2/L2016/16321r-brahmi-11008-glyph.pdf
http://www.unicode.org/L2/L2016/16343-brahmi-vs-glyphs.pdf
also the existing four dotted form should be substituted for letter I+Anusvara.

**Comment by TidharC** [comment]
Assigning to MT.

**Comment by sridatta1** [comment]
Closing this issue as I see this issue has been fixed in the latest version (v 2.001) https://raw.githubusercontent.com/googlefonts/noto-fonts/master/phaseIII_only/unhinted/ttf/NotoSansBrahmi/NotoSansBrahmi-Regular.ttf 
![image](https://user-images.githubusercontent.com/23263723/82141303-7a035380-9852-11ea-8d48-0cd14dd45a28.png)
( text: 𑀇𑀈𑀓𑀾𑀇𑀈𑀓𑀾)
