### ISSUE TITLE
Diacritic on word god using NotoSansArabic

### ISSUE THREAD

**Issue by nizarsq** [googlefonts/noto-fonts#836]
The word god (اللٌهُ) (alif, lam, lam, shadda, superscript (dagger) alif and ha) has some issues with placing diacritic. Apparently Noto Sans Arabic designed to automatically add the shaddah and superscript (dagger) on the top of the letter lam (second lam). This feature is fine and commonly used by other fonts, however, it should take care of the existing diacritic entered by writer to avoid overlapping or make it grammatically wrong. Keeping in mind this word is commonly used in the middle east (Arabic,Urdu etc. speakers). 
![unnamed 1](https://cloud.githubusercontent.com/assets/22158882/22834018/b50cf17a-ef68-11e6-9c26-a4c77ad177fd.png)
![unnamed](https://cloud.githubusercontent.com/assets/22158882/22834024/b87bd6c8-ef68-11e6-8607-356cc462d0f6.png)

**Comment by marekjez86** [comment]
@nizarsq : could you add a test case here? Alternatively try with the two static fonts (non -var) https://github.com/googlei18n/noto-fonts/blob/master/alpha/from-pipeline/unhinted/ttf/sans/NotoSansArabic-Regular.ttf and https://github.com/googlei18n/noto-fonts/blob/master/alpha/from-glyphsapp/unhinted/ttf/sans/NotoSansArabic-Regular.ttf 

If both of the above fonts work then the problem could be with either variable font binary (ie. pipeline made them incorrectly) or with the code that handles the displaying variable fonts.

If both are bad then we have source problem.
If https://github.com/googlei18n/noto-fonts/blob/master/alpha/from-glyphsapp/unhinted/ttf/sans/NotoSansArabic-Regular.ttf  looks OK then we have pipeline problem.

Just curious what the results of other tests are.

**Comment by nizarsq** [comment]
@marekjez86 I used fontdiff to see the difference between pipeline/NotoSansArabic-Regular and glyphsapp/NotoSansArabic-Regular and here the result (pink from .glyphsapp/)
``<html lang="ar"><span style="font-weight:700"><p>اللَّهُ</p></span> </html>``
[NotoSansglyphsappPipeline.pdf](https://github.com/googlei18n/noto-fonts/files/794829/NotoSansglyphsappPipeline.pdf)
I also checked checked NotoSansArabicUI-VF and NotoSansArabic-VF and here the result
[NotoSansArabicUI-VFNotoSansArabic-VF.pdf](https://github.com/googlei18n/noto-fonts/files/794830/NotoSansArabicUI-VFNotoSansArabic-VF.pdf)

Apperantly this issue not specific to variable fonts

**Comment by marekjez86** [comment]
@nizarsq : please check if this reproduces with the current version of fonts. Thank you

**Comment by jungshik** [comment]
If it still adds Taskeel for the input <Alef, Lam, Lam, Heh>, we'd better remove the GSUb entry for the automatic insertion of taskeel from Noto Sans Arabic (UI) fonts  per @behdad  .

**Comment by jungshik** [comment]
#1200 also talks about   the **discretionary** ligature for Muhammad. It's not on by default, I guess. 

> the discretionary ligature for Muhammad insert diacritics not present in the text. If the text does include diacritics, the rendering includes both the real diacritics and the ligatures’ figments.

**Comment by nizarsq** [comment]
This extra diacritics issue fixed. There is another issue observed but it's unrelated to this specific issue. closing as fixed.
