### ISSUE TITLE
Tibetan shaping does not work for "syllables" (character seq) for which there's no pre-composed glyphs

### ISSUE THREAD

**Issue by jungshik** [googlefonts/noto-fonts#838]
Tibetan fonts have pre-composed glyphs for widely used "syllables" (character sequences). For syllables outside the set, shaping still should work by putting together pieces. 

The designer of another Tibetan font from India pointed us that that's not the case of a lot of syllables. 

An example (only one of the numerous): 

```
ཛཱཛཁྐཛྩའཇྟ
U+0F5B U+0F71 U+0F5B U+0F41 U+0F90 U+0F5B U+0FA9 U+0F60 U+0F47 U+0F9F 
```

With Noto Sans Tibetan, I got:

![image](https://cloud.githubusercontent.com/assets/8578343/22897310/169d7164-f1d8-11e6-993c-ae53c86e9648.png)

With Monlam font, I got

![image 1](https://cloud.githubusercontent.com/assets/8578343/22897340/3036375a-f1d8-11e6-9232-8fc2abac6a12.png)

@kmansourMT ,  sorry that I didn't get back to you sooner on this issue. 
Could you start taking a look at this issue?   Have you checked the shaping of all the syllables in all 3 tiers.  I'm well aware that we decided to have pre-composed glyphs for only the 1st tier and perhaps a subset of the 2nd tier, but the rest of syllables are supposed to be shaped properly by putting together pieces.  

I lost your email with the 3 sets of Tibetan syllables. Could you send me the list (3 sets)?  You can attach them here.  Thanks in advance.

**Comment by jungshik** [comment]
http://languagetools-153419.appspot.com/demo_bo/  is a demo page you can type any Tibetan strings and get them rendered with both Noto Sans Tibetan and Monlam fonts.

**Comment by jungshik** [comment]
@KatMomoi , FYI

**Comment by jungshik** [comment]
Ping @kmansourMT :-)

**Comment by kmansourMT** [comment]
I have confirmed the failure to compose arbitrary syllables that are not pre-formed, and am looking into the best way to fix it.

**Comment by jungshik** [comment]
Thanks a lot, @kmansourMT

**Comment by settinger** [comment]
Hi all, has there been any progress on this topic? It's preventing me from finishing a manuscript that happens to use the word ལྷྭམ་ (shoe) in many examples.
![leipz35](https://cloud.githubusercontent.com/assets/7494643/25058495/cce46754-212e-11e7-9b8f-79a93b3e4a85.png)

**Comment by marekjez86** [comment]
@settinger : It will be fixed in a new update, but it may take some time

**Comment by marekjez86** [comment]
should be fixed in newly updated https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSerifTibetan (and its TTF counterpart)

**Comment by marekjez86** [comment]
[tib-838-Serif.pdf](https://github.com/googlefonts/noto-fonts/files/3288481/tib-838-Serif.pdf)
