### ISSUE TITLE
some common Arabic character sequences go outside UI box for Noto Sans Arabic UI

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#842]
The following Arabic sequences were reported as clipping in the NotoNaskhArabicUI font. They shouldn't be clipping. 

U+0623 U+064E (common)
U+0623 U+064B (very rare)
U+0623 U+064F (common)
U+0623 U+064C (very rare)
U+0623 U+0652 (happens sometimes in Persian, possibly other languages too)
U+0625 U+0650 (common)

Five of the above go outside the vertical extent for the UI fonts:

أَ (170, 2231)
أً (170, 2314)
أُ (170, 2344)
أٌ (170, 2344)
أْ (170, 2285)
where vertical UI box is (2163, -555). 

These sequences also have a problem with Noto Sans Arabic UI.

أً (0, 1219)
أُ (0, 1235)
أٌ (0, 1244)
أْ (0, 1199)
إِ (-430, 714)
where the vertical UI box is (1056, -270)

**Comment by roozbehp** [comment]
The solution is making Alef-Hamza-Above and Alef-Hamza-Below shorter when they are followed by a combining accent at the same location of the hamza.

**Comment by jungshik** [comment]
@kmansourMT

**Comment by marekjez86** [comment]
the upper line (red) is a non-UI font and the lower line is the UI Arabic font. Anything outside of the line bound is clipping (see the content of the green line).

![arabic-clipping](https://cloud.githubusercontent.com/assets/13322623/23195844/9e209d12-f86a-11e6-9673-6bc5d88c9e36.jpeg)

different sample but the same principle

![arabic-clipping2](https://cloud.githubusercontent.com/assets/13322623/23195872/c13c2dc0-f86a-11e6-8dc0-48be701832aa.jpeg)

**Comment by jungshik** [comment]
What's urgent is to fix Noto Naskh Arabic UI because that's the font used on Android devices.

**Comment by jungshik** [comment]
@marekjez86 ,   How about using this bug for **Noto Naskh Arabic UI only** and file a new one for 'Noto Sans Arabic UI'? The former is more urgent than the latter.

**Comment by marekjez86** [comment]
**this bug is for Noto Naskh Arabic UI only**

**Comment by nizarsq** [comment]
This issue still reproducible on NotoNaskhArabicUI and NotoSansArabicUI.
<img width="1164" alt="Screen Shot 2020-05-31 at 9 59 41 PM" src="https://user-images.githubusercontent.com/22158882/83377315-10269600-a38a-11ea-81f7-e9fd28332d4d.png">
<img width="1212" alt="Screen Shot 2020-05-31 at 9 59 32 PM" src="https://user-images.githubusercontent.com/22158882/83377317-10bf2c80-a38a-11ea-8efd-5deac4b28075.png">

**Comment by nizarsq** [comment]
@marekjez86 will you revisit this issue and verify if there are truncation using mentioned code points? Thanks

**Comment by nizarsq** [comment]
I believe this issue fixed. Will close now and reopen if the issue exist
