### ISSUE TITLE
U+0608 ARABIC RAY is confusing

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/noto-fonts#843]
The Arabic ray symbol is نق (short of نصف القطر) but the current symbol in Noto Naskh Arabic and Noto Sans Arabic looks more like a stylised ق. This symbol is used in math where it will be used standalone with no much context and I have been told students (the main audience of Arabic math) have difficulty recognizing it.

I suggest adding a tooth to the horizontal stroke so it looks more like a dotless نق.

**Comment by nizarsq** [comment]
@khaledhosny Are you aware of any font that adds horizontal stroke to نق? From my point of view if a special shape نق  needed then it should have a different code point to represent it. @marekjez86 any thoughts on this?

**Comment by khaledhosny** [comment]
The symbol is rather new, so I don’t know other fonts supporting it before Noto and it seems fonts are now just following Noto’s example. I don’t any other uses of نق that require the design used by Noto.
