### ISSUE TITLE
Noto Sans: wrong U+AB35 lenis f

### ISSUE THREAD

**Issue by moyogo** [googlefonts/noto-fonts#848]
U+AB35 lenis in Noto Sans should be like in Noto Serif, with the bottom of stem above baseline, also in italic.

See "ꬵf" <AB35 0066> (lenis f, f) in Noto Sans compared with Noto Serif:
![screen shot 2017-02-19 at 4 16 44 pm](https://cloud.githubusercontent.com/assets/1923747/23104088/0f403d34-f6bf-11e6-81b5-a0be124f1b45.png)

**Comment by moyogo** [comment]
It also needs to be fixed in Arimo, Cousine, Tinos and Roboto.

**Comment by jungshik** [comment]
@moyogo  What version of Noto Sans  did you find this issue in ?  Have you tried a newer version in 'from-pipeline' ?

**Comment by moyogo** [comment]
@jungshik That’s the one I’m using: Noto Sans Version 1.902, shasum 3f1ff7da39f0e435dbc42012e39651feb028e980.

**Comment by marekjez86** [comment]
test + test results with the current fonts
[en-848.zip](https://github.com/googlefonts/noto-fonts/files/3292162/en-848.zip)

**Comment by moyogo** [comment]
It looks good:
![NotoSans-sample-nꬵf](https://user-images.githubusercontent.com/1923747/59541267-69d34d80-8ef8-11e9-8d11-7a7a373192ee.png)


This and #1099 by @dscorbett are resolved.
Thanks.

**Comment by dscorbett** [comment]
The italic U+AB35 should reach the baseline; see the attestations in [L2/11-202](https://www.unicode.org/L2/L2011/11202-n4081-teuthonista.pdf). The idea that U+AB35 should not touch the baseline [was invented for the roman style used in the Unicode code chart](https://www.unicode.org/L2/L2011/11240-n4106-teuthonista-adhoc.pdf#page=2) and is not how this character should look in italics.

**Comment by moyogo** [comment]
Good point, you had mentioned that in #1099.

**Comment by nizarsq** [comment]
This issue has been resolved 
<img width="547" alt="Screen Shot 2020-07-13 at 5 32 01 PM" src="https://user-images.githubusercontent.com/22158882/87366942-c3a8ab80-c52e-11ea-8196-deb9fab97df7.png">
