### ISSUE TITLE
NotoSansArabicUI static and variable connect some letters that should stay disconnected

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#851]
NotoSansArabicUI static and variable connect some letters that should stay disconnected, for example letter waw (U+0648) get connect with letter ain (U+0639). see the images below

![screen shot 2017-02-23 at 9 51 37 1](https://cloud.githubusercontent.com/assets/13322623/23277076/7ae36b1a-f9c1-11e6-92fd-c79a4df06f4f.png)
![screen shot 2017-02-23 at 9 51 37 2](https://cloud.githubusercontent.com/assets/13322623/23277075/7adcb040-f9c1-11e6-9e0f-985ffd0b2616.png)

@nizarsq : could you write the text for me so I can test it ? are there more letters that are connected but shouldn't be connected? Once you answer please assign it to me. Thank you.

**Comment by marekjez86** [comment]
@nizarsq : could you provide me with the Arabic text for this?

**Comment by nizarsq** [comment]
وقوع جوع

**Comment by marekjez86** [comment]
I created a duplicate of this bug in https://github.com/googlei18n/noto-fonts/issues/1164 (for now both are open).

**Comment by marekjez86** [comment]
I didn't mean to close it.

**Comment by marekjez86** [comment]
duplicate of bug of #1164
