### ISSUE TITLE
NotoSansArmenian-VF add space between some characters 

### ISSUE THREAD

**Issue by nizarsq** [googlefonts/noto-fonts#868]
Compared the rendering for this combination "լի" (U+053C U+056B) using NotoSansArmenian-VF (1.902) and NotoSansArmenian-Regular (1.902) and noticed some extra spaces added between those 2 characters when NotoSansArmenian-VF used, the issue noticed originally on Android settings under battery settings. I noticed this issue happens with "լի" and "լխ". Tried to reproduce this issue on our app and noticed same issue, tried to reproduce the issue on font view but I didn't not notice the issue.

Note: I checked character "լ" on both fonts and both characters have same width, checked "ի" on both fonts and both characters have same width.

Fonts used:
Variable font downloaded from https://github.com/googlei18n/noto-fonts/tree/master/alpha/from-pipeline/unhinted/variable-ttf/sans
Static font downloaded from https://github.com/googlei18n/noto-fonts/tree/master/alpha/from-pipeline/unhinted/ttf/sans

![notosansarmenian variable vs notosansarmenian static](https://cloud.githubusercontent.com/assets/22158882/23770082/8500b6ec-04c6-11e7-8a44-3acf809479ee.png)
![notosansarmenian variable vs notosansarmenian static fontview](https://cloud.githubusercontent.com/assets/22158882/23770084/87e62d4c-04c6-11e7-9a58-fe55f662ac45.png)

**Comment by marekjez86** [comment]
not reproducible
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansArmenian
and
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSerifArmenian
... and corresponding variable fonts
