### ISSUE TITLE
Some alpha otfs not valid on Windows

### ISSUE THREAD

**Issue by Kanjilearner817** [googlefonts/noto-fonts#872]
I downloaded some of the otf alpha fonts from the pipeline and have yet to go through them all, but there are already quite a few that Windows doesn't recognize as valid (I'm running Windows 10 post-Anniversary Update):
Noto Sans Extra Condensed Extra Light
Noto Sans Extra Condensed Extra Light Italic
Noto Sans Semi Condensed Extra Light
Noto Sans Semi Condensed Extra Light Italic
Noto Sans Arabic Condensed Black
Noto Sans Arabic Condensed Extra Bold
Noto Sans Arabic Condensed Extra Light
Noto Sans Arabic Condensed Light
Noto Sans Arabic Condensed Medium
Noto Sans Arabic Extra Condensed Black
Noto Sans Arabic Extra Condensed Extra Bold
Noto Sans Arabic Extra Condensed Extra Light
Noto Sans Arabic Extra Condensed Light
Noto Sans Arabic Extra Condensed Medium
Noto Sans Arabic Extra Condensed Semi Bold
Noto Sans Arabic Extra Condensed Thin
Noto Sans Arabic Semi Condensed Black
Noto Sans Arabic Semi Condensed Extra Bold
Noto Sans Arabic Semi Condensed Extra Light
Noto Sans Arabic Semi Condensed Light
Noto Sans Arabic Semi Condensed Medium
Noto Sans Arabic Semi Condensed Semi Bold
Noto Sans Arabic Semi Condensed Thin
Noto Sans Arabic UI Condensed Black
Noto Sans Arabic UI Condensed Extra Bold
Noto Sans Arabic UI Condensed Extra Light
Noto Sans Arabic UI Condensed Light
Noto Sans Arabic UI Condensed Medium
Noto Sans Arabic UI Condensed Semi Bold
Noto Sans Arabic UI Condensed Thin
Noto Sans Arabic UI Extra Condensed Black
Noto Sans Arabic UI Extra Condensed Bold
Noto Sans Arabic UI Extra Condensed Extra Bold
Noto Sans Arabic UI Extra Condensed Extra Light
Noto Sans Arabic UI Extra Condensed Light
Noto Sans Arabic UI Extra Condensed Medium
Noto Sans Arabic UI Extra Condensed Semi Bold
Noto Sans Arabic UI Extra Condensed Thin
Noto Sans Arabic UI Semi Condensed
Noto Sans Arabic UI Semi Condensed Black
Noto Sans Arabic UI Semi Condensed Bold
Noto Sans Arabic UI Semi Condensed Extra Bold
Noto Sans Arabic UI Semi Condensed Extra Light
Noto Sans Arabic UI Semi Condensed Light
Noto Sans Arabic UI Semi Condensed Medium
Noto Sans Arabic UI Semi Condensed Semi Bold
Noto Sans Arabic UI Semi Condensed Thin

**Comment by marekjez86** [comment]
@Kanjilearner817 : what message do you get? what are the symptoms?

**Comment by arrowtype** [comment]
This issue was reported again in connection to the Noto Nüshu project with the [current TTF](https://github.com/LisaHuang2017/noto-sans-nushu/blob/c89f05023df1d49707dd16f8e7a3d01e498a37b8/fonts/NotoSansNushu-Regular.ttf).

> Tried to install your NotoSansNushu font from GitHub, but Windows 10 (64 bit) returns the message "does not appear to be a valid font". Any suggestions?

I suspect this may be caused by fonts lacking a basic English alphabet, but I need to dig deeper.

**Comment by punchcutter** [comment]
No, it has nothing to do with English alphabet. The download was probably corrupted or something. I just installed from that link and it works fine in Windows 10 (2004) in the font settings and also in Word (Office 365).

**Comment by arrowtype** [comment]
Oh, strange. Thank you for looking into it and letting me know!

**Comment by arrowtype** [comment]
Huh, yeah, sure enough, testing Nüshu on Windows 10, Version 1909, I had no problems [downloading it from GitHub](https://github.com/notofonts/noto-sans-nushu/releases/tag/1.001), installing, and using it. Here’s a screenshot of basic testing in WordPad:

![image](https://user-images.githubusercontent.com/45946693/86820621-4d500900-c057-11ea-832d-915a6d6b2e6f.png)
