### ISSUE TITLE
NotoSansArabic static font misplace diacritics

### ISSUE THREAD

**Issue by nizarsq** [googlefonts/noto-fonts#876]
NotoSansArabic static font place diacritics lower than supposed, when it become to the alef with hamza diacritics will be placed under the hamza, for e.g. (U+0623 U+064F). Please check attached.

Font downloaded from https://github.com/googlei18n/noto-fonts/tree/master/alpha/from-pipeline/unhinted/ttf/sans
![notossansarabic](https://cloud.githubusercontent.com/assets/22158882/24007493/fe66b292-0a2b-11e7-911f-97f05f6abd15.png)

**Comment by marekjez86** [comment]
@nizarsq : unable to reproduce it with the current build

**Comment by nizarsq** [comment]
I think this issue was observable because when the font tested there was missing characters in the font file, and apparently fallback to another font caused this issue.

**Comment by nizarsq** [comment]
This issue still reproducible on NotoSansArabic, in fact U+064F currently is sitting on the top of Hamza.
<img width="1134" alt="Screen Shot 2020-05-31 at 3 45 40 PM" src="https://user-images.githubusercontent.com/22158882/83364467-59f58900-a356-11ea-9ae9-cf454e432f7f.png">

**Comment by nizarsq** [comment]
This issue fixed
