### ISSUE TITLE
Noto Sans Old Italic's D and R look like R and D

### ISSUE THREAD

**Issue by kkdd** [googlefonts/noto-fonts#884]
In Noto Sans Old Italic (= http://www.google.com/get/noto/#sans-ital ) ,

* U+10303  &#66307; doesn't look like D but R.
* U+10313  &#66323; doesn't look like R but D.

**Comment by TidharC** [comment]
@kkdd the glyphs look like a mirrored R and a mirrored D, respectively.  This is consistent with the image on the font download page:

![olditalic](https://user-images.githubusercontent.com/16353803/27157384-18eb5fc4-5116-11e7-981c-40a63f9e028b.png)

Do you have an image showing that the glyphs should look different?


@marekjez86 looks like the Noto Sans Old Italic ttf from:
https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/ttf/sans
is empty.  I see no glyphs in it.

**Comment by marekjez86** [comment]
http://www.unicode.org/charts/PDF/U10300.pdf shows that U+10303 and U+10313 look like

![unicode-u 10303 u 10313](https://user-images.githubusercontent.com/13322623/27158222-cf1cc77a-511a-11e7-8b9d-d702697a5a97.jpeg)

Currently released font file in https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSansOldItalic-Regular.ttf
have U+10303 as
![notosansolditalic10303](https://user-images.githubusercontent.com/13322623/27158429-c032aee0-511b-11e7-85e0-a1486996a4cd.jpeg)


and U+10313 as
![notosansolditalic10313](https://user-images.githubusercontent.com/13322623/27158433-c614988c-511b-11e7-992a-2dcd451ba1b6.jpeg)


I tried to do Google search to see what others think they should look like and I get
on http://www.fileformat.info/info/unicode/char/10303/index.htm U+10303 as
![fileformat-u 10303](https://user-images.githubusercontent.com/13322623/27158614-9b5111d8-511c-11e7-987c-51672ebd31dd.jpeg)

and
on  http://www.fileformat.info/info/unicode/char/10313/index.htm U+10313 as
![fileformat-u 10313](https://user-images.githubusercontent.com/13322623/27158616-a15a3b18-511c-11e7-81af-c00350a9a886.jpeg)

**Comment by marekjez86** [comment]
What we have doesn't look like what Unicode has, however others seem to be also confused. We probably should look like what Unicode has listed on http://www.unicode.org/charts/PDF/U10300.pdf  unless there are some corrections to this page.

**Comment by marekjez86** [comment]
@waksmonskiMT : when we do conversion we should resolve this in the new font.

**Comment by c933103** [comment]
Is it now fixed on Noto Sans?
https://i.imgur.com/ay6gUdz.png

**Comment by marekjez86** [comment]
https://docs.google.com/viewer?url=https%3A%2F%2Fgithub.com%2Fgooglefonts%2Fnoto-fonts%2Fblob%2Fmaster%2FphaseIII_only%2Funhinted%2Fttf%2FNotoSansOldItalic%2FNotoSansOldItalic-Regular.ttf has this fixed

**Comment by kkdd** [comment]
It looks to be fixed when seeing http://www.google.com/get/noto/#sans-ital :
![Noto Sans Old Italic](https://user-images.githubusercontent.com/5372642/81814823-2a780b80-9564-11ea-87c9-81884baef3a0.jpg)
