### ISSUE TITLE
Support Svasti characters in Indic scripts

### ISSUE THREAD

**Issue by sridatta1** [googlefonts/noto-fonts#886]
Much thanks for supporting svastika characters(U+0FD5-U+0FD8) in Tibetan. These are important part of Hindu, Jaina and Buddhist traditions. For some reasons these were encoded in Tibetan block, but are intended for general use in other Asian scripts. Since they are supported in Noto Sans Tibetan, I assume there isn't any problem in supporting them in other fonts.

**Comment by roozbehp** [comment]
Would you please provided evidence of textual use in other Indic script? If you write a proposal with samples for UTC, we can add them to ScriptExtensions, and then Noto will inherit that information to know which scripts it should the characters to.

**Comment by Shreeshrii** [comment]
https://pothi.com/pothi/book/हेमंतकुमार-गजानन-पाध्या-स्वस्तिकामृत-swastikamrut-0

Sample usage with Devanagari and Gujarati scripts

**Comment by sridatta1** [comment]
Will close this issue, when the information is added to Unicode Script extensions, will file new issues
