### ISSUE TITLE
Hebrew fonts difficult to read

### ISSUE THREAD

**Issue by ronshapiro** [googlefonts/noto-fonts#909]
### Where the font came from, and when
  >   Date: 2017-05-01 (preferred format)

### Font Version
 > * Linux -- use (Gnome) Font Viewer: open a font and click on Info tab.

### Issue
I find the Hebrew fonts to be very difficult to read compared to Roboto. The characters are more round, and extend far out from the center of the character's bounding-box. After reading a lot of Hebrew text, I find it less enjoyable to read compared to Roboto. The accents also seem to be more subdued compared to Roboto

In particular, the letters I find most difficult are:

ע - the extension at the bottom left is very short

ט - very round and not so descript from ס
ן - again, the extension is very short. if this has an accent, it should be a bit longer. or it can be totally omitted. But the current accent is a tease, and hard to read
ג 
מ - the upper left curve downwards feels very drastic
ז - the top part doesn't seem to be similar to they way זis typically displayed

### Character data
ע 
ט
ן
ג 
מ
ז

**Comment by dougfelt** [comment]
@marekjez86 fyi.  Since it's a design issue not sure what we do but collect feedback and see.

**Comment by marekjez86** [comment]
@ronshapiro : could you prepare for me some text samples. I'm not a reader/speaker of Hebrew hence I'm unable to do it.

**Comment by nizarsq** [comment]
Looks good to me now but I'm not Hebrew native reader/speaker. @marekjez86 any opinion?
<img width="824" alt="Screen Shot 2020-08-04 at 3 33 16 PM" src="https://user-images.githubusercontent.com/22158882/89351908-d151dc80-d667-11ea-8b27-78b7d936ca87.png">
