### ISSUE TITLE
Noto Sans Ethiopic: wrong marker added for U+1310

### ISSUE THREAD

**Issue by fgaim** [googlefonts/noto-fonts#914]
In Noto Sans Ethiopic, the glyph of `U+1310` has an additional wrong marker on top. It is misleading/annoying to native users and needs to be removed, the rest of the glyphs are great.

![gue-issue](https://cloud.githubusercontent.com/assets/4906991/25966586/6a227fcc-36c6-11e7-8779-356678f2e5d5.png)

**Comment by marekjez86** [comment]
@waksmonskiMT : I checked and Noto Serif Ethiopic also has the marker on top. When I look at http://unicode.org/charts/PDF/U1200.pdf u1310 doesn't have the marker. Please correct.

**Comment by marekjez86** [comment]
@fgaim : thank you for catching and reporting this

**Comment by dyacob** [comment]
when this glyph is updated, it should be based on ጉ (U+1309) with the -o diacritic added to it.  This approach will both get the letter height right as well as the vertical position of the diacritical mark.

**Comment by nizarsq** [comment]
This issue fixed on the current NotoSansEthiopic and NotoSerifEthiopic  
<img width="856" alt="Screen Shot 2020-11-17 at 9 02 25 PM" src="https://user-images.githubusercontent.com/22158882/99485895-33cda080-2918-11eb-8e78-396cb69beebb.png">
