### ISSUE TITLE
Google Fonts Attribution Page Shows License as Apache

### ISSUE THREAD

**Issue by brightestpixel** [googlefonts/noto-fonts#944]
Hey there, I apologize if I am posting this issue in the wrong spot, but I have no idea where to put it.

This is not an issue about the font itself; it is an issue about the license.

I got Noto Sans off of fonts.google.com, and I went to fonts.google.com/attribution to figure out what credit I needed.  On that page, it says the Noto Sans license is the Apache 2.0 one still, even though it was changed to SIL awhile ago.  It took me a long time to figure this out, so I was wondering if someone could update that page to show the correct license.  EDIT: It also says this on the Google Fonts page for Noto Sans: [https://fonts.google.com/specimen/Noto+Sans](url)

Thanks.

**Comment by hrieke** [comment]
Some clarification would be wonderful.
But also to toss some gasoline onto the 🔥 -
Using Exiftool I see that:
1. NotoSans-Bold
2. NotoSans-BoldItalic
3. NotoSans-Regular
Have the SIL Open File license assigned to them, while:
1. NotoSans-Italic
has the Apache License 2.0 assigned.
🎢 fun!

**Comment by simoncozens** [comment]
Noto Sans now has OFL license everywhere; I checked the web site and the italic files in the repo.
