### ISSUE TITLE
NotoSansMono-MM.glyphs has incompatible masters

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#948]
One of the masters (Light) in NotoSansMono-MM.glyphs has a kern feature, but other masters don't.  Since this is a monospace font, it looks like a bug in the Light master.  The kern feature seems to be kerning U+0259 LATIN SMALL LETTER SCHWA with U+02DE MODIFIER LETTER RHOTIC HOOK.

**Comment by marekjez86** [comment]
@anthrotype : comment from MTI "




NotoSansMono-MM.glyphs has incompatible masters  Script-LatinGreekCyrillic  #948
--
https://github.com/googlei18n/noto-fonts/issues/948

**Comment by anthrotype** [comment]
@marekjez86 Thanks for the update! In the meantime, do you want me to revert https://github.com/googlei18n/noto-source/pull/93?

**Comment by marekjez86** [comment]
No. Please keep it. I'm not sure when we'll get the update.

**Comment by marekjez86** [comment]
unable to reproduce with the newest sources
