### ISSUE TITLE
NotoSansDevanagari-MM.glyphs glyph dabhadeva has incompatible masters

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#949]
glyph dabhadeva in NotoSansDevanagari-MM.glyphs has incompatible masters ; we cannot generate variations for this glyph

WARNING:fontTools.varLib:glyph dabhadeva has incompatible masters; skipping

**Comment by JelleBosmaMT** [comment]
The dabhadeva shows up in all instances as interpolated by Glyphs.app in my source files. Glyphs doesn't show any incompatible glyph.

![image](https://user-images.githubusercontent.com/12729011/66483728-f3a9b680-eaa5-11e9-9ce0-76a865df4323.png)

**Comment by simoncozens** [comment]
We've been producing and shipping Devanagari variable fonts since February, so this is fixed.
