### ISSUE TITLE
Notosans Devanagari: Appearance of श+ृ incorrect in Hindi

### ISSUE THREAD

**Issue by JeetendraJ** [googlefonts/noto-fonts#958]
Hello,

 When we type Hindi श+ृ the out put is incorrect. When we type word shrinkhla in Hindi the ru appears below sha. But the correct appearance should be 
![shrinkhla non standard one](https://user-images.githubusercontent.com/31063238/29355504-ef00820c-828e-11e7-9541-609559e9b29b.PNG)
![shrinkhla correct one](https://user-images.githubusercontent.com/31063238/29355506-f0cfc2be-828e-11e7-930c-858019b55467.PNG)

**Comment by JeetendraJ** [comment]
Any updates on above issue

**Comment by marekjez86** [comment]
@JeetendraJ : could you provide the whole text for the word shrinkhla in Hindi ? I do not speak Hindi. Also where did you get the Notosans Devanagari font from (or how did you get it)?

**Comment by JeetendraJ** [comment]
@marekjez86 : Shrinkhla is typed correctly as शृंखला in Hindi. I downloaded the Noto Sans Devanagari fonts from here : https://www.google.com/get/noto/

**Comment by srinidhi97** [comment]
Here is the example of शृ . 
![image](https://user-images.githubusercontent.com/27153077/33663489-365e060e-dab6-11e7-81d5-3a03803e0513.png)
Today most fonts depict the proposed glyph as you can see below.  It is convention to write as शृ similar to श्र. 
![image](https://user-images.githubusercontent.com/27153077/33663507-475ecfc4-dab6-11e7-8c01-2678c030778e.png)

**Comment by marekjez86** [comment]
@JeetendraJ and @srinidhi97 : We are working on correcting Hindi... any other issues that you see or are aware of? Thank you for your feedback and help.

**Comment by marekjez86** [comment]
@JelleBosmaMT : is there a prior art for what Noto has right now? If not or not strong enough, could we change it (including is SOW12)?

**Comment by JelleBosmaMT** [comment]
Noto is not the only typeface without this variant of sha when combined with r-vocalic. Checking fonts I happen to have on my PC: Annapurna SIL, Aparajita (Microsoft), CDAC-GIST Surekh (has one in the glyph set, but doesn't render), Gargi, Kalimati, Kokali (Modular Infotech, Microsoft), Utsaah (Modular Infotech, Microsoft). My impression was this is optional, not required. If I am wrong it is relatively easy to add, because the variant shape is already part of ligatures. A new glyph can be created with copy and paste and updating GDEFs and GSUBs.

**Comment by JeetendraJ** [comment]
I will confirm you soon.

On Dec 16, 2017 1:05 AM, "Jelle Bosma" <notifications@github.com> wrote:

Noto is not the only typeface without this variant of sha when combined
with r-vocalic. Checking fonts I happen to have on my PC: Annapurna SIL,
Aparajita (Microsoft), CDAC-GIST Surekh (has one in the glyph set, but
doesn't render), Gargi, Kalimati, Kokali (Modular Infotech, Microsoft),
Utsaah (Modular Infotech, Microsoft). My impression was this is optional,
not required. If I am wrong it is relatively easy to add, because the
variant shape is already part of ligatures. A new glyph can be created with
copy and paste and updating GDEFs and GSUBs.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/googlei18n/noto-fonts/issues/958#issuecomment-352092871>,
or mute the thread

**Comment by srinidhi97** [comment]
In almost all manuscripts and many books(example given below) so far I have seen, the proposed glyph is used for शृ. 
![image](https://user-images.githubusercontent.com/27153077/36606645-5e422642-18ea-11e8-827a-5fc51a864508.png)
The current glyph for श+ृ may not be incorrect. This is not the traditional and preferred glyph as in श्र. The appearance of current glyph in some new publication may be attributed as lack of font support and not the knowing about this special form.

**Comment by jitenderjeet** [comment]
निश्चिनत, सुनिश्चिनत - whey च is getting underneath the leg of श and same again happening while writing God in window 8.1 in Annpurna Sil font...pls help

**Comment by nizarsq** [comment]
Look like this issue has been fixed. Please reopen if you have other thoughts.
<img width="1051" alt="Screen Shot 2020-06-08 at 10 40 39 PM" src="https://user-images.githubusercontent.com/22158882/84110393-a6396c80-a9d9-11ea-987b-32e2402fcf8b.png">
