### ISSUE TITLE
Small Tilde followed by character appears as combined tilde character

### ISSUE THREAD

**Issue by sarmstrong** [googlefonts/noto-fonts#961]
Not entirely sure if this is the forum for reporting issues w/ the webfont, but here it goes . . . .

### Font 
 Webfont

### Where the font came from, and when, today!
https://fonts.googleapis.com/css?family=Noto+Sans:400

### Font Version
Current I assume

### OS name and version
Reproduce on Chrome and Firefox on Mac

### Issue
When a Small Tilde (Unicode Decimal 732) is followed by a an "n" (Unicode Decimal 110), the text appears as a "Latin Small Letter N With Tilde" (Unicode Decimal 241). However, other fonts show this combination as two separate characters. I'm not sure if this is intentional, nonetheless, our users find it confusing. They expect to see two separate characters. 

![screen shot 2017-09-01 at 2 42 18 pm](https://user-images.githubusercontent.com/928849/29983447-de789b26-8f23-11e7-9ffd-7f986c9e1fd6.png)

You can reproduce this issue in Chrome using this bin. The "Noto Sans Input" is editable so you can play around w/ other combinations.
http://jsbin.com/badameduza/edit?html,js,output

Ultimately, I'm wondering if this is the expected behavior and if so, what is the reason behind the decision. Thanks!

**Comment by rogersachan** [comment]
Reddit's new redesign is hitting this issue and quite a few people are noticing: https://www.reddit.com/r/redesign/comments/8jul8h/the_font_really_needs_to_be_changed_from_noto_sans/

**Comment by fitojb** [comment]
> Not entirely sure if this is the forum for reporting issues w/ the webfont, but here it goes . . . .

See the repo [google/fonts](https://github.com/google/fonts)

**Comment by nizarsq** [comment]
Look like this issue has been resolved. Tested using fonts in the following directories:
<img width="562" alt="Screen Shot 2020-07-17 at 10 17 58 PM" src="https://user-images.githubusercontent.com/22158882/87845362-5fae1c00-c87b-11ea-9be7-3ea7fff78dab.png">
