### ISSUE TITLE
Misrendering of Telugu virama in Noto font

### ISSUE THREAD

**Issue by lirang** [googlefonts/noto-fonts#964]
Misrendering of Telugu virama in NotoSansTelugu fonts

### Font 
 NotoSansTelugu-Regular.ttf 

### Where the font came from, and when
downloaded from : https://www.google.com/get/noto/#sans-telu
Date: 2017-09-11 

### Font Version
1.1

### OS name and version
 Mac, using oracle java

### Issue
The Telugu Noto fonts misrendr the sequence of consonant+virama+consonant.
(For example, \u0c24 + \u0c4d + \u0c24 - see attached image for correct and incorrect form.) 
The three unicodes shall be merged and displayed as one glyph.

According to https://github.com/googlei18n/noto-fonts/issues/5 it has already fixed for the Kannada language. I guess the same fix is required for languages containing the Virama character.

Tried to use another font (i,e TeluguOTS) and it rendered correctly!!!

### Harfbuzz hb-view and hb-shape
This is the weird part... the text renders properly with hb-view

Example: \u0c24 + \u0c4d + \u0c24 + \u0c3f 
Good rendering - 
![image](https://user-images.githubusercontent.com/6205723/30279669-88318f7a-9716-11e7-83ba-6456af0a02b7.png)

Bad rendering - 
![image](https://user-images.githubusercontent.com/6205723/30279756-bb462772-9716-11e7-8d67-bf9848107070.png)

**Comment by JelleBosmaMT** [comment]
I get the correct results with the Microsoft and Apple shakers as well has the Chrome browser (Harfbuz).

**Comment by nizarsq** [comment]
Rendering for \u0c24 + \u0c4d + \u0c24 looks ok in NotoSansTelugu this directory https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansTelugu/NotoSansTelugu-Regular.ttf. Closing this bug for now.
<img width="1093" alt="Screen Shot 2020-06-23 at 11 14 20 PM" src="https://user-images.githubusercontent.com/22158882/85507594-76789000-b5a7-11ea-9209-649c56bb9d16.png">
