### ISSUE TITLE
Incorrect glyph's shape of Cyrillic Small Letter Shha

### ISSUE THREAD

**Issue by yuriy7779** [googlefonts/noto-fonts#972]
### Title 
  > The glyph's shape of Cyrillic Small Letter Shha (U+04BB) is not standard

### Font 
  > NotoSerif-Bold.ttf, NotoSerif-BoldItalic.ttf, NotoSerif-Italic.ttf, NotoSerif-Regular.ttf
  > NotoSans-Bold.ttf, NotoSans-BoldItalic.ttf, NotoSans-Italic.ttf, NotoSans-Regular.ttf.

### Where the font came from, and when
  >   Site: https://noto-website.storage.googleapis.com/pkgs/NotoSans-hinted.zip, https://noto-website.storage.googleapis.com/pkgs/NotoSerif-hinted.zip
  >   Date: 2017-10-04

### Font Version
  > NotoSerif-Bold.ttf, NotoSerif-BoldItalic.ttf, NotoSerif-Italic.ttf - Version 1.05
  > NotoSerif-Regular.ttf, NotoSans-Bold.ttf, NotoSans-BoldItalic.ttf, NotoSans-Regular.ttf - Version 1.06
  > NotoSans-Italic.ttf - Version 1.07

### OS name and version
  > Windows 10 x64

### Application name and version
  > Characters Map, LibreOffice Writer

### Issue
  > The glyph's shape of Cyrillic Small Letter Shha (U+04BB) is not standard. It should be like Latin Small Letter H (U+0068). See https://en.wikipedia.org/wiki/Shha

### Screenshot
  > Now the Small Letter Shha in Noto fonts looks like a Capital Shha but smaller in size (Screenshots are taken from Noto Sans Regular, other fonts are similar):
![sample_1](https://user-images.githubusercontent.com/32511878/31175152-f23ce9de-a916-11e7-9fe8-48e48283b2c1.PNG)

  > It should look like Latin Small Letter H:
![sample_3](https://user-images.githubusercontent.com/32511878/31175205-1a639188-a917-11e7-87f1-e0bf3a23bb2a.PNG)

  > Here is the example of Cyrillic Small Letter Shha With Descender (U+0527). Logically, these two letters should look similar:
![sample_2](https://user-images.githubusercontent.com/32511878/31175296-7b43cef0-a917-11e7-902f-7d4139ecd86b.PNG)

  > As a comment. Roboto fonts do not have this issue. In them the Cyrillic Small Letter Shha looks like a Latin Small Letter H.

**Comment by marekjez86** [comment]
I ran the following test
```html
<html lang="ru">
	<p><span style="font-weight:400">U+04BA Һ U+04BB һ </span></p>
	<p><span style="font-weight:400">U+0526 Ԧ U+0527 ԧ </span></p>
</html>
```
against all Noto fonts (from https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/ttf ) and released Roboto. I didn't see a problem (but maybe I don't understand it). @yuriy7779 : Could you look at my PDFs and help me understand?

[ru-972-LGC-Roboto-vs-self.pdf](https://github.com/googlei18n/noto-fonts/files/1362383/ru-972-LGC-Roboto-vs-self.pdf)
[ru-972-LGC-Sans-Italic-vs-self.pdf](https://github.com/googlei18n/noto-fonts/files/1362384/ru-972-LGC-Sans-Italic-vs-self.pdf)
[ru-972-LGC-Sans-Regular-vs-self.pdf](https://github.com/googlei18n/noto-fonts/files/1362385/ru-972-LGC-Sans-Regular-vs-self.pdf)
[ru-972-LGC-SansDisplay-Italic-vs-self.pdf](https://github.com/googlei18n/noto-fonts/files/1362388/ru-972-LGC-SansDisplay-Italic-vs-self.pdf)
[ru-972-LGC-SansDisplay-Regular-vs-self.pdf](https://github.com/googlei18n/noto-fonts/files/1362387/ru-972-LGC-SansDisplay-Regular-vs-self.pdf)
[ru-972-LGC-SansMono-Regular-vs-self.pdf](https://github.com/googlei18n/noto-fonts/files/1362386/ru-972-LGC-SansMono-Regular-vs-self.pdf)
[ru-972-LGC-Serif-Italic-vs-self.pdf](https://github.com/googlei18n/noto-fonts/files/1362389/ru-972-LGC-Serif-Italic-vs-self.pdf)
[ru-972-LGC-Serif-Regular-vs-self.pdf](https://github.com/googlei18n/noto-fonts/files/1362390/ru-972-LGC-Serif-Regular-vs-self.pdf)
[ru-972-LGC-SerifDisplay-Italic-vs-self.pdf](https://github.com/googlei18n/noto-fonts/files/1362391/ru-972-LGC-SerifDisplay-Italic-vs-self.pdf)
[ru-972-LGC-SerifDisplay-Regular-vs-self.pdf](https://github.com/googlei18n/noto-fonts/files/1362392/ru-972-LGC-SerifDisplay-Regular-vs-self.pdf)

**Comment by yuriy7779** [comment]
Hi Marek! Thanks for your help. Sorry that was not clear enough. English is not my native language. :) Your PDSs look great. But somehow, when I install Noto fonts to my computer, the character's shape is different. (I mean U+4BB) It looks like:
![1](https://user-images.githubusercontent.com/32511878/31275457-f2ef391a-aa9f-11e7-9a4d-407c79114cd0.PNG)
But it should look like this:
![2](https://user-images.githubusercontent.com/32511878/31275467-ffc06eca-aa9f-11e7-8ede-3a2f628f9f97.PNG)
Does this information helps?

**Comment by marekjez86** [comment]
@yuriy7779 : could you download https://github.com/googlei18n/noto-source/blob/master/test/LGC/ru-972-NotoSans-Regular.html and  https://github.com/googlei18n/noto-source/blob/master/test/LGC/ru-972-NotoSerif-Regular.html . These files are the same as my test html file above, but they pull the font directly from the repository I pointed you to. Could you open these downloaded files in your favorite browser(s) on your system and check what you see? If they look OK then there's a bug (unknown to me) in Characters Map, LibreOffice Writer or how Windows installs and uses installed fonts. If they don't look OK then there might be an issue in rendering these characters on Windows. Please let me know what you see.

**Comment by yuriy7779** [comment]
Hi Marek! The test html files are ok. Now I understand that only version 1.06 of the fonts have the issue. The version 2.0 (alpha) are ok. Do you know when they will be released for common use?

**Comment by marekjez86** [comment]
They might be released this week (although we are getting close to the end of this week) or next week. They'll be posted on https://www.google.com/get/noto/

**Comment by yuriy7779** [comment]
Thank you VERY much!!!

**Comment by yuriy7779** [comment]
It seems that the fonts available on https://www.google.com/get/noto/ are not updated until now. Are there any information about when the fonts will be released? Please excuse my impatience.

**Comment by marekjez86** [comment]
@dougfelt : any projections for @yuriy7779 ?

**Comment by nizarsq** [comment]
Look like this issue fixed. @yuriy7779 can you confirm that? I'm using fonts in these directories https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSansMono
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSans
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSerif

Thanks
<img width="665" alt="Screen Shot 2020-07-17 at 9 54 59 PM" src="https://user-images.githubusercontent.com/22158882/87845040-2aec9580-c878-11ea-803b-18cf9d8456e3.png">

**Comment by yuriy7779** [comment]
Yes, I can confirm. Thank you very much.
