### ISSUE TITLE
Hindi Notosans Font: Appearance of क्त incorrect in NotoSansDevanagariUI-Regular.ttf font

### ISSUE THREAD

**Issue by gsksarath** [googlefonts/noto-fonts#974]
Hi,

When we type letter रक्त the output is incorrect. 

Wrong output image is attached below

![hindi1](https://user-images.githubusercontent.com/2748530/31342228-b1f45b8e-ad29-11e7-8c3d-2b598a46e967.JPG)

**Comment by JelleBosmaMT** [comment]
Noto has a correct _Devanagari_ ligature for "K-Ta", but if it is one of the ligatures which is not always recognised by Hindi readers, we can disable it for default rendering.
Interestingly to note that while for Nepali we use only a minimal set of consonant ligatures, this is one of them, so the glyph has to stay in the font.

**Comment by nizarsq** [comment]
Look like this issue fixed. Closing for now, if any issue exist please reopen
<img width="842" alt="Screen Shot 2020-06-08 at 11 02 01 AM" src="https://user-images.githubusercontent.com/22158882/84064527-9852ff80-a977-11ea-8387-eb2c090ef7c0.png">
