### ISSUE TITLE
ra+ZWJ+virama+ya should render as a special form in Hindi

### ISSUE THREAD

**Issue by roozbehp** [googlefonts/noto-fonts#988]
The Unicode Technical Committee just confirmed that the sequence ra+ZWJ+virama+ya in Devanagari should appear as a stand-alone ra followed by a post-form of ya, similar to Bengali (see http://www.unicode.org/L2/L2017/17309-rya-devanagari.pdf for background).

Noto (Sans|Serif) Devanagari should display the sequence correctly. This doesn't appear to be case currently.

The character sequence to test is <U+0930, U+200D, U+094D, U+092F>.

**Comment by nizarsq** [comment]
Look like U+0930, U+200D, U+094D, U+092F still not displayed as the special rendering of Rya in NotoSerifDevanagari and NotoSansDevanagari.
<img width="1084" alt="Screen Shot 2020-06-08 at 10 33 40 PM" src="https://user-images.githubusercontent.com/22158882/84109712-2363e200-a9d8-11ea-9cfa-ac8327f7f84b.png">

**Comment by Azzert** [comment]
The test cases already show the special rendering of Rya. The normal rendering (without ZWJ) is ya with reph.

**Comment by nizarsq** [comment]
@Azzert  Thank you.
