### ISSUE TITLE
Accepting ڛ (Sin + three dots below) for Noto Nastaliq 

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [googlefonts/noto-fonts#991]
The letter ڛ (Sin + three dots below) sometimes appeared in Nastaliq-style caligraphies, however it does not work in Noto Nastaliq font. One example of such usage can be found here:
![خط نڛتعلیق](https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Khatt-e_Nastaliq.jpg/639px-Khatt-e_Nastaliq.jpg)

**Comment by simoncozens** [comment]
This character is now encoded in Noto Nastaliq.
