### ISSUE TITLE
U+2070 – U+209C: Noto Sans, Noto Serif: Vertical Alignment of Some Superscripts and Subscripts Seems Wrong

### ISSUE THREAD

**Issue by rhodium-103** [googlefonts/noto-fonts#995]
### Font: Noto Serif and Noto Sans
All weights and styles I checked; e. g., use NotoSerif-Regular.ttf

### Source:
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerif-hinted.zip
Date: 2017-11-01

### Font Version
2.000;GOOG;noto-source:20170915:90ef993387c0; ttfautohint (v1.7)

### OS name and version
Linux Mint 18.2
_Font was installed/updated manually_

### Issue
First of all, thank you very much for completing the full set of superscripts and subscripts in the Unicode range U+2070 – U+209C in the latest major release. The superscript minus and plus are especially important to me as they can be used to correctly print composed units in plain text, e. g., meter per second: m⋅s⁻¹. Unfortunately, the baseline of the minus and plus signs are different from that of the superscript numbers. To me, this seems like a bug. Please find attached two screenshots from the standard text editor – first one is Noto Serif Regular, second one is Cambria for comparison. At least for my use case, the alignment in Cambria is superior. A similar issue is found with the subscripts, although the example has no real meaning, so it does not matter as much, at least not to me.

### Character data
Plain text of the examples shown in the screenshots:
m⋅s⁻¹
m⋅s⁻¹⁺⁵⁽⁹⁻⁸⁾
CH₁₂₊₅

### Screenshots for comparison
Noto Serif: 
![notoserif](https://user-images.githubusercontent.com/33369296/32404199-8eeb4252-c14b-11e7-8956-b0872d2bdd4d.png)

Cambria: 
![cambria](https://user-images.githubusercontent.com/33369296/32404203-97fbc330-c14b-11e7-91f2-948749c52509.png)

Thank you very much for your work on these great fonts!

**Comment by nizarsq** [comment]
This issue has been resolved. Font used in the test are exist in the following directories:
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSansMono
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSans
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSerif

<img width="261" alt="Screen Shot 2020-07-17 at 10 24 17 PM" src="https://user-images.githubusercontent.com/22158882/87845436-42c61880-c87c-11ea-9d5e-d648c5ef6077.png">
